### ISSUE TITLE
How to connect to a Forge Server?

### ISSUE THREAD

**Issue by schleumer** [PrismarineJS/mineflayer#1008]
## Versions
 - mineflayer: 2.15.0
 - server: vanilla 1.15.2 forge 31.1.30
 - node: 14.3.0

## Detailed description of a question

How could i connect to a vanilla server with forge? I've tried the `minecraft-protocol-forge`, but it seems outdated, i think Forge changed something in the protocol.

**Comment by rom1504** [comment]
Update minecraft-protocol-forge then use it. And please make a pull request
after you got it to work
