### ISSUE TITLE
How should I format the kick messages?

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1015]
## Versions
 - mineflayer: newest
 - server: spigot
 - node: newest

## Detailed description of a question
when using the on kicked event, I can get a kick message such as `{"text":"§b§l§nCosmic§r §e§l§nSky§r\n\n§d§lempires.cosmicsky.com\n§7The Cosmoverse is preparing for §fMAP #7: §nEMPIRES§7!\n§7Join us again §fThursday, May 28th at 2pm CST.\n\n§7No public access is authorized.\n§7Please try again later.\n\n§7Read more at §fforum.cosmicsky.com\n§7Follow us on twitter §f@CosmicSkyblock\n§7Download the client §fcosmicclient.com\n"}` or something as simple as `"byee"` this type of difference makes it hard to format the kick message, so I was wondering if anyone has any ideas how to format them all in the same way

**Comment by wvffle** [comment]
Some like a snippet below should work but you may probably JSON.stringify kickMessage. 

We should probably return the chat message by default, @rom1504 what do you think? In some cases we're returning the ChatMessage and sometimes we don't this should be one way or another. Not both.
```js
const ChatMessage = require('mineflayer/lib/chat_message')(bot.version)

bot.on('kick', (kickMessage) => {
	const message = new ChatMessage(kickMessage)
	console.log(message.toAnsi())
})
```

**Comment by rom1504** [comment]
Yeah I agree, we should probably always return the chatmessage

**Comment by u9g** [comment]
> Some like a snippet below should work but you may probably JSON.stringify kickMessage.
> 
> We should probably return the chat message by default, @rom1504 what do you think? In some cases we're returning the ChatMessage and sometimes we don't this should be one way or another. Not both.
> 
> ```js
> const ChatMessage = require('mineflayer/lib/chat_message')(bot.version)
> 
> bot.on('kick', (kickMessage) => {
> 	const message = new ChatMessage(kickMessage)
> 	console.log(message.toAnsi())
> })
> ```
when using that code I get an error of 
`TypeError: Cannot read property 'language' of null
    at loader (c:\Users\<User>\Documents\js-projects\testing-modules\node_modules\mineflayer\lib\chat_message.js:8:24)
    at Object.<anonymous> (c:\Users\<User>\Documents\js-projects\testing-modules\index.js:25:59)
    at Module._compile (internal/modules/cjs/loader.js:1130:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47`

**Comment by wvffle** [comment]
> but you may probably JSON.stringify kickMessage

Try that
