### ISSUE TITLE
Create a big exhaustive FAQ

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#1018]
We always get the same questions on discord.
Build a FAQ by looking at the discord chat, listing all questions, and then putting these questions and answers in the FAQ
Once done, refer the FAQ to everyone asking the same question in discord.

Overtime we can improve the doc to decrease the number of FAQ questions

**Comment by rom1504** [comment]
Questions : 

Q: "How can I send a command" A: "by using bot.chat"

Please comment on this issue with the same format

**Comment by rom1504** [comment]
Q: "Is it possible to login multiple accounts using bot = mineflayer.createbot but you can control them all seperately" A: "Create different bot instances by calling createBot then do different things for each, see multiple.js"

**Comment by dada513** [comment]
**Q:** How would I make the bot drop it's entire inventory?
**A:** `bot.inventory.items()` returns an array of the bot's items. You can use a recursive function to loop through them and drop every item using `bot.toss()`. Click [here](https://gist.github.com/dada513/3d88f772be4224b40f9e5d1787bd63e9) to see an example

**Comment by rom1504** [comment]
fixed now, for any new things, add to FAQ.md
