### ISSUE TITLE
Inventory on website

### ISSUE THREAD

**Issue by MikeMottonix** [PrismarineJS/mineflayer#1020]
## Versions
 - mineflayer: current
 - server: vanilla 1.15.2
 - node: 12.17.0

I want to have my Inventory shown on a website. Is that possible?
Im new to nodejs and js.

**Comment by AlexProgrammerDE** [comment]
@MikeMottonix i think thats something for advanced coders. If you really want to do this try it the way navigate does: [radar](https://github.com/andrewrk/mineflayer-radar/) - web based radar interface using [canvas](https://github.com/Automattic/node-canvas) and [socket.io](socket.io).

Übrogens ich denke Englisch ist für andere auf der Platform besser.

**Comment by ImHarvol** [comment]
I created https://github.com/ImHarvol/inventory-viewer as a very basic example of this.

**Comment by rom1504** [comment]
Have a look at https://github.com/rom1504/web-minecraft-crafter/blob/master/README.md and dependencies

**Comment by rom1504** [comment]
I think imharvol package is pretty good, let's close this
