### ISSUE TITLE
How can i make Mineflayer auto-eating?

### ISSUE THREAD

**Issue by MikeMottonix** [PrismarineJS/mineflayer#1023]
## Versions
 - mineflayer: current
 - server: vanilla 1.15.2
 - node: 12.17.0

I want that my afk-bot is eating automatically, how can i make that?
It should eat when having 3 hunger points.

**Comment by AlexProgrammerDE** [comment]
@MikeMottonix take a look at this two parts of the api: 
1. http://mineflayer.prismarine.js.org/#/api?id=botfood
2. http://mineflayer.prismarine.js.org/#/api?id=botconsumecallback

**Comment by MikeMottonix** [comment]
Thanks
