### ISSUE TITLE
Mineflayer emitting 'spawn' event twice

### ISSUE THREAD

**Issue by S0LDR** [PrismarineJS/mineflayer#1024]
## Versions
 - mineflayer: 2.17.0
 - server: spigot
 - node: v12 LTS

## Bug
Mineflayer seems to emit 2 'spawn' events, or 2 'death' events on the bot's spawn or death
![image](https://user-images.githubusercontent.com/66232265/83585524-0d59ab80-a518-11ea-8cf6-2de3e1089e2c.png)
![image](https://user-images.githubusercontent.com/66232265/83585602-4265fe00-a518-11ea-938c-8e40fb739932.png)

## Code
```
//dead
bot.on('death', function() {
	const deathEmbed = new Discord.MessageEmbed()
		.setTitle('Bot was killed')
		.setColor('#ff0000')
		.setFooter(`${config.version}`)
	channel.send(deathEmbed)
})

//spawned
bot.on('spawn', function() {
	const spawnEmbed = new Discord.MessageEmbed()
		.setTitle('Bot Spawned')
		.setColor('#00ff00')
		.setFooter(`${config.version}`)
	channel.send(spawnEmbed)
})
```

**Comment by Karang** [comment]
have you tested your code on a vanilla server ? I see two possibilities:
* In your code you register your event twice (verify that's not the case)
* Spigot server send 2 spawn packets
