### ISSUE TITLE
How do I start on creating a bot that mines, then walks, then mines again.

### ISSUE THREAD

**Issue by lookingforthis** [PrismarineJS/mineflayer#1025]
## Versions
 - mineflayer: most recent
 - server: vanilla 1.15.2
 - node: 12.18.0

I want to create a bot that mines the block in front of him and then the one under that block so he creates a path that he can walk and then repeat the process so he creates a long aisle basically. I have little coding experience in C++ and Java so I was wondering on where to start. I do understand most of the examples though but when I try to recreate for example the digger.js I am having trouble to get him to look in the right direction or making him wallk at all.

**Comment by AlexProgrammerDE** [comment]
@lookingforthis you can set where the bot looks at with the blt.lookAt function. You just have to get the position of the current block.

**Comment by ImHarvol** [comment]
In fact, you shouldn't need to worry about `bot.lookAt`, [`bot.dig` already does that for you](https://github.com/PrismarineJS/mineflayer/blob/12727810b326bca7725099353b59560eff409c80/lib/plugins/digging.js#L13).

**Comment by lookingforthis** [comment]
Thanks but how do I find out the position?

**Comment by ImHarvol** [comment]
Which position? You can get the bot's position with  `bot.entity.position`, see https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#entity

**Comment by lookingforthis** [comment]
I mean the position of the block(s) that I want it to mine

**Comment by ImHarvol** [comment]
If for example you want to mine to +x (east), you would mine blocks:
* `bot.blockAt(bot.entity.position.offset(1, 0, 0))`
* `bot.blockAt(bot.entity.position.offset(1, 1, 0))`

If you need to mine exactly the cardinal your bot is facing, you can check which cardinal your bot is facing by checking its yaw (`bot.entity.yaw`)
