### ISSUE TITLE
How can i trade with plugin villagers

### ISSUE THREAD

**Issue by TechNafo** [PrismarineJS/mineflayer#1029]
## Versions
 - mineflayer: ^2.18.0
 - server: spigot? 1.8 - 1.5.2
 - node: v12.17.0

## Detailed description of a question

I am trying to do personal bot which mine sponges for me on a public server. It works perfect but i have to trade sponges to coins. At this point bot needs trade with villagers. here is my [full code](https://hastebin.com/oqorodorod.js) here.

This villagers spawned by some plugins i think. How can i trade with them. I have to do this :(

**Comment by TechNafo** [comment]
Sory i forgot post error :p

`(node:9950) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Expected "actual" to be strictly unequal to: null
    at Bot.trade (/home/technafo/node_modules/mineflayer/lib/plugins/villager.js:113:12)
    at /home/technafo/mcbot/main.js:121:29
(node:9950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9950) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
WARNING : unknown transaction confirmation for window 0, action 1414 and accepted false`

**Comment by rom1504** [comment]
can you try to extract a minimal example that reproduces ?

**Comment by rom1504** [comment]
please re-open with a clear description and reproductive example
