### ISSUE TITLE
When i run the example named chatAddPattern i keep getting an error

### ISSUE THREAD

**Issue by mikekmp** [PrismarineJS/mineflayer#1031]
I have just downloaded mineflayer, i have tried chatterbox example(it worked) but when i try to ru chatAddPattern i keep getting this error:
![image](https://user-images.githubusercontent.com/45897741/83788800-6eab8700-a69e-11ea-8b9f-b259c764446e.png)

**Comment by rom1504** [comment]
It means you run it too early, you need to wait for some ready event, for example spawn
