### ISSUE TITLE
What exactly is bot.connect used for?

### ISSUE THREAD

**Issue by 6ixDev** [PrismarineJS/mineflayer#1034]
I would like to make a bot reconnect without me having to create a new bot object.
i tried bot.connect(botOptions), as soon as it gets kicked, but that seems to do nothing

**Comment by rom1504** [comment]
That method doesn't exist

**Comment by 6ixDev** [comment]
Edit: im so sorry, i meant bot.connect. 
my bad

**Comment by JungleDome** [comment]
Currently mineflayer does not have reconnect method, everytime bot.connect is called it will initialize a new bot object and connects it to a defined server ip in the bot options.

You could refer to this post to get more details on how you could reconnect your bot for now. #975
