### ISSUE TITLE
Problem with bot.chat()

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1038]
## Versions
 - mineflayer: newest
 - server: spigot
 - node: newest

## Detailed description of a question
when using this code in a .on message event
```js
for (const ix in users) {
    setTimeout(() => {
      bot.chat("/bal " + users[ix]);
    }, 100 * (ix + 1));
  }
```
my output is spammed with 404 errors from **discord**???
an example of the error here:
```
DiscordAPIError: 404: Not Found
    at RequestHandler.execute (C:\Users\---\Documents\js-projects\cosmicbot\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'get',
  path: '/channels/',
  code: 0,
  httpStatus: 404
}
```
one of those^ is sent for each time a settimeout expires and the function is sent

I know it's a problem with bot.chat() because if I replace that with a console.log() the errors aren't sent anymore

**Comment by rom1504** [comment]
Your error is unrelated with the code your posted, it mentions discord so
it's something else in your code.

However that loop is incorrect. If you put a setTimeout in a loop like
this, it's going to do all the timeouts at the same time.

**Comment by u9g** [comment]
what would be a better way to do a loop with a setTimeout then?

**Comment by rom1504** [comment]
wait actually I'm not sure it depends on what you want to do. this seems correct if you want to have bots sending chat 100 then 200 then 300 ms after this loop is executed

what is your code (will be useful to know the actual errror) ?

**Comment by u9g** [comment]
sorry for the confusion, it turns out a different plugin was listening for the same string in game, was my fault, thanks.
