### ISSUE TITLE
asynchronous events

### ISSUE THREAD

**Issue by s4mukka** [PrismarineJS/mineflayer#1040]
How do I use an event as an asynchronous? I want to wait for an event to happen and then proceed to the next line of my algorithm.
Is there a Mineflayer community on Discord?
Thanks :D

**Comment by ImHarvol** [comment]
Here's the discord https://discord.gg/GsEFRM8

About asynchronous events, mineflayer instead of using Promises, uses callbacks (at least for now), which are functions called once the event is done:
```js
function callbackFunction() {
  console.log('This will be printed once the function bot.lookAt() is done')
}
bot.lookAt(point, null, callbackFunction)

// Usually it's written like this:
bot.lookAt(point, null, () => {
  console.log('This will be printed once the function bot.lookAt() is done')
})

```

Sometimes, instead of callback, mineflayer emits events:
```js
let chest = bot.openChest(chestBlock)
chest.once("open", () => {
  console.log("This will be printed once the chest is open")
})
```
See more about the Chest instante in [docs/api.md#mineflayerchest](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#mineflayerchest)
See more about events in https://nodejs.org/api/events.html

I hope this helps you :)

**Comment by s4mukka** [comment]
But what about cases where I want some function to occur after a bot.on() happens?
Thanks for answering :)

**Comment by ImHarvol** [comment]
Events with bot.on() are similar to the example of chest.once():
- `bot.on(event, callback)`: The _.on_ will run the callback function every time the event is emitted
- `bot.once(event, callback)`: The _.once_ will run the callback function only once

Your would be something like this:
```js
function teleport (home) {
  bot.chat(`/home ${home}`);

  // Should probably be run **once**, otherwise his keeps listening to the event
  // So if teleport() is called the for 3rd the third time it will run the callback 3 times
  bot.once('teleported', () => {
    bot.look(0,-90);
  })
}

function herbalismo() {
  teleport('cana')
}
```
By the way, you should probably listen to ["forcedmove" event](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#forcedmove)

---

You can also use Promises which take away the callback hell
```js
function teleport (home) {
  return new Promise ((resolve, reject) => {
    bot.chat(`/home ${home}`)

    bot.once('teleported', resolve)
  })
}

async function herbalismo() {
  await teleport('cana')
  bot.look(0,-90)
}
```
`await teleport('cana')` waits for the function to run `resolve()` which is called once the bot has been teleported.
