### ISSUE TITLE
is there something like onTick-Event?

### ISSUE THREAD

**Issue by 6ixDev** [PrismarineJS/mineflayer#1043]
So basically i need an event that updates regularly (more than once every second).
While coding mods with forge, i solved it with the OnTick method. 
Is there something like it on mineflayer, and if not, could it please be added?
Thanks!
(i appologize for my english.)

**Comment by Karang** [comment]
You can use:
```js
bot.on('physicTick', () => {

})
```
The event is called just after a physic update (every game tick).
