### ISSUE TITLE
Directory problems

### ISSUE THREAD

**Issue by beartravels** [PrismarineJS/mineflayer#1044]
in order to get node 12 i had to use snap command, i get thei error when i try to test every thing
i dont know how to move forward
 0 info it worked if it ends with ok
1 verbose cli [ '/snap/node/2797/bin/node', '/snap/node/2797/bin/npm', 'test' ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose config Skipping project config: /home/bear/.npmrc. (matches userconfig)
5 verbose stack Error: EISDIR: illegal operation on a directory, read
6 verbose cwd /home/bear
7 verbose Linux 5.3.0-59-generic
8 verbose argv "/snap/node/2797/bin/node" "/snap/node/2797/bin/npm" "test"
9 verbose node v12.18.0
10 verbose npm  v6.14.4
11 error code EISDIR
12 error syscall read
13 error errno -21
14 error EISDIR: illegal operation on a directory, read
15 verbose exit [ -21, true ]

**Comment by ImHarvol** [comment]
Not sure about your problem, but I recommend you using NVM: https://github.com/nvm-sh/nvm#installing-and-updating
