### ISSUE TITLE
your peer directories are broken 

### ISSUE THREAD

**Issue by beartravels** [PrismarineJS/mineflayer#1045]
## Versions
 - mineflayer: #.#.# idk
 - server: vanilla/spigot/paper #.#.# iodk
 - node: 14.4.0

## Detailed description of a question
i wish i could know what to ask.
 this is wht i get when i try to download mineflayer
it seem s to be broken
unless there a way to download the whole peer folder sepretly that you did not tlell us assuming only techs woud do this
![Screenshot from 2020-06-12 08-41-01](https://user-images.githubusercontent.com/64866787/84520820-fab64380-ac88-11ea-895d-0aa376c4bb86.png)

**Comment by beartravels** [comment]
ive gone thru and downloaded every peer dependancy it does not regonize that ive donte this so i orbabkly did it worn id there an easy way tpo do this?

**Comment by beartravels** [comment]
from my research so far ther is not a repositiory of files for peers so idk how you htink this is gonna work

**Comment by rom1504** [comment]
There is no error in your screenshot. It works.
You can now start using the library. I advise you take a look at the examples and the tutorial.

**Comment by beartravels** [comment]
thanks ya im still learning all this i thught there eas errors
