### ISSUE TITLE
Broken peer directorys

### ISSUE THREAD

**Issue by beartravels** [PrismarineJS/mineflayer#1046]
## Versions
 - mineflayer: #.#.# idk i cnat install it
 - server: vanilla/spigot/paper #.#.# haven got that far but it will be paper

 - node: #.#.# 12
idk what the problem is ive donloaded all the peer directorys it tell me but istill get the same errods

![Screenshot from 2020-06-12 09-07-45](https://user-images.githubusercontent.com/64866787/84522848-330b5100-ac8c-11ea-90e3-ae435374b95a.png)

**Comment by rom1504** [comment]
I answered in https://github.com/PrismarineJS/mineflayer/issues/1045
