### ISSUE TITLE
npm test failure

### ISSUE THREAD

**Issue by beartravels** [PrismarineJS/mineflayer#1047]
## Versions
 - mineflayer: #.#.# i dont think its properly doenloaded
 - server: vanilla/spigot/paper #.#.# it will ine day be paper
 - node: #.#.# 12

## Detailed description of a problem
A clear and concise description of what the problem is.
Good question....
![Screenshot from 2020-06-12 09-27-10](https://user-images.githubusercontent.com/64866787/84524507-f1c87080-ac8e-11ea-88e4-075979e97a9d.png)

```js
bot.placeBlock('grass', (err) => {
  if (err) return bot.chat(err.message)
})
```

**Comment by beartravels** [comment]
https://discord.gg/UyAj4YE

**Comment by rom1504** [comment]
you need to run npm test in the folder where you cloned mineflayer.
If the doc is too difficult in your case, do join the discord to ask questions.

**Comment by beartravels** [comment]
cpy copy did not know you ahd a discord have not seen a link 
\

\
\
a
a

s

**Comment by rom1504** [comment]
the link is there https://github.com/PrismarineJS/mineflayer
