### ISSUE TITLE
findBlocks is not working properly

### ISSUE THREAD

**Issue by RealPeha** [PrismarineJS/mineflayer#1048]
## Versions
 - mineflayer: 2.19.0
 - server: vanilla 1.15.2
 - node: 13.9.0

## Detailed description of a problem
findBlocks method does not return the nearest blocks

## Current code
```js
const blocks = bot.findBlocks({
	point: bot.entity.position,
	matching: 9, // dirt
	maxDistance: 2,
	minCount: 2
})
				
console.log(bot.entity.position)
// Vec3 { x: 50.12733864306501, y: 4, z: -35.27180865196587 }

console.log(blocks.length)
// 512
// Why so much?

console.log(bot.blockAt(blocks[0]))
// Block {
//    type: 9,
//    position: Vec3 { x: 48, y: 1, z: -33 }, // why so far?
//    name: 'dirt',
//    // another block data...
// }
```

## Expected behavior
I want to find the nearest blocks in radius 2. But this method returns me 512 blocks that are far from the coordinates I need

**Comment by Karang** [comment]
Can you show more of the returned blocks array ?

As said in the api, minCount specifies the minimum number of block to return, but more can be returned: https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botfindblocksoptions

The blocks array should be ordered with closest first. I you find that it is not the case, then indeed there is a bug.

The difference between the bot position and the first block in the array seems relatively low, are you sure there is a closer block ?

**Comment by rom1504** [comment]
For sure 512 blocks is wrong for max distance of 2. Maybe max distance is not working ?

**Comment by RealPeha** [comment]
@Karang my bot is in a flat world from a ditrt blocks, so the nearest block is the block on which it stands

this is an array of blocks that I get when my bot stands on a dirt block at coordinates {x: 50.12733864306501, y: 4, z: -35.27180865196587}
[data.txt](https://github.com/PrismarineJS/mineflayer/files/4775071/data.txt)

**Comment by superego546** [comment]
I've had the same issue. You can use something like this: https://codeshare.io/5wJ0gR

**Comment by Bacto** [comment]
Same problem here.
It seems that the blocks are not sorted by distance and that maxDistance is not honored.

PS: this project is awesome!

**Comment by rom1504** [comment]
I think we should add some tests to check and address this.

**Comment by rom1504** [comment]
Also I think it would really make a lot of sense if we could use
prismarine-world and move find block there. Would make stuff much more
natural.
Hopefully we will get there

**Comment by RealPeha** [comment]
@rom1504 and I think that OctahedronIterator is not working properly
This algorithm is difficult for my brain to understand, but I took it out separately and received the following result during testing:

```js
const it = new OctahedronIterator({x: 1, y: 1, z: 1}, 2) // but it returns not this.start.offset(X, Y, Z) but simply {X, Y, Z}

it.next()
// {X: -1, Y: -0, Z: -0}
it.next()
// {X: -0, Y: -0, Z: -1}
it.next()
// {X: -0, Y: -1, Z: -0}
it.next()
// {X: -1, Y: -0, Z: 0} // same result as first
```

**Comment by Karang** [comment]
There was indeed a bug in the sorting (should be fixed with https://github.com/PrismarineJS/mineflayer/pull/1050)

The maxDistance is rounded up to the next multiple of 16, as we iterate over sections and not block (see https://github.com/PrismarineJS/mineflayer/pull/1035 for a writeup of why). If needed we can filter the array before returning.

The octahedron iterator does indeed go through the same positions sometimes (this is why we have a set in findblocks that ensure we don't process twice the same section) (see https://github.com/Darthfett/mineflayer-blockfinder/issues/3 for more details on the iterator)

**Comment by rom1504** [comment]
I think it would make sense to filter by max distance before returning indeed. I don't think it would impact performance
