### ISSUE TITLE
Improve proxy support

### ISSUE THREAD

**Issue by ShakatarYT** [PrismarineJS/mineflayer#1055]
## Versions
 - mineflayer: 2.19.0
 - server: spigot 1.8.9
 - node: 12.14.0

## Detailed description of a question
Hello,
I'm trying to connect the mineflayer bot through a socks5 proxy. But when I run the script with node nothing happens. By the way, I don't understand the "stream" property of the createBot function. I don't find anything in the documentation of NMP or mineflayer.

(I have opened port 25565 of my box, the ip in the code is my public ip and the proxy credentials are good and the socks proxy has been tested just before...)

```
var Socks  = require("socks5-client");
var minecraft = { host: "My public ip", port: 25565 };
var proxy = { host: 'fr305.nordvpn.com', port: 1080 };

var mineflayer = require('mineflayer');
mineflayer.createBot({
  stream: Socks.createConnection({
    host: minecraft.host,
    port: minecraft.port,
    socksHost: proxy.host,
    socksPort: proxy.port,
    socksUsername: "NordVPN email:",
    socksPassword: "NordVPN password"
  }),
  username: "TestBot1",
})
```

**Comment by ShakatarYT** [comment]
I finally found a way. 
I found a tcp proxy server code written in python. I added 3 lines so that the packets sent from the client are forwarded to my minecraft server through my socks 5 nordvpn proxy and it works! Plus I can see the packets sent for debugging.

Player minecraft >> Local proxy (localhost:9090) >> NordVPN socks proxy >> Minecraft server

Here is the python code :

```
import socket
import socks
import select
import time
import sys

# Changing the buffer_size and delay, you can improve the speed and bandwidth.
# But when buffer get to high or delay go too down, you can broke things
buffer_size = 4096
delay = 0.0001
forward_to = ('remote minecraft server ip', remote minecraft server port)

class Forward:
    def __init__(self):
        socks.set_default_proxy(socks.SOCKS5, "82.102.18.245", 1080, True, 'username','password')
        self.s = socks.socksocket()

    def start(self, host, port):
        try:
            self.s.connect((host, port))
            return self.s
        except (Exception, e):
            print(e)
            return False

class TheServer:
    input_list = []
    channel = {}

    def __init__(self, host, port):
        self.server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.server.bind((host, port))
        self.server.listen(200)

    def main_loop(self):
        self.input_list.append(self.server)
        while 1:
            time.sleep(delay)
            ss = select.select
            inputready, outputready, exceptready = ss(self.input_list, [], [])
            for self.s in inputready:
                if self.s == self.server:
                    self.on_accept()
                    break

                self.data = self.s.recv(buffer_size)
                if len(self.data) == 0:
                    self.on_close()
                    break
                else:
                    self.on_recv()

    def on_accept(self):
        forward = Forward().start(forward_to[0], forward_to[1])
        clientsock, clientaddr = self.server.accept()
        if forward:
            print(clientaddr, "has connected")
            self.input_list.append(clientsock)
            self.input_list.append(forward)
            self.channel[clientsock] = forward
            self.channel[forward] = clientsock
        else:
            print("Can't establish connection with remote server.")
            print("Closing connection with client side", clientaddr)
            clientsock.close()

    def on_close(self):
        print(self.s.getpeername(), "has disconnected")
        #remove objects from input_list
        self.input_list.remove(self.s)
        self.input_list.remove(self.channel[self.s])
        out = self.channel[self.s]
        # close the connection with client
        self.channel[out].close()  # equivalent to do self.s.close()
        # close the connection with remote server
        self.channel[self.s].close()
        # delete both objects from channel dict
        del self.channel[out]
        del self.channel[self.s]

    def on_recv(self):
        data = self.data
        # here we can parse and/or modify the data before send forward
        print(data)
        self.channel[self.s].send(data)

if __name__ == '__main__':
        server = TheServer('localhost', 9090)
        try:
            server.main_loop()
        except KeyboardInterrupt:
            print("Ctrl C - Stopping server")
            sys.exit(1)
```
Source : https://voorloopnul.com/blog/a-python-proxy-in-less-than-100-lines-of-code/

**Comment by Nic2309** [comment]
are you able to translate this into javascript?

**Comment by rom1504** [comment]
can you try https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js ?

**Comment by Nic2309** [comment]
ok thank you, i pasted the code into my bot but got this error:
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'proxy-agent'
Require stack:

Where do i find the file proxy-agent?

**Comment by rom1504** [comment]
npm install proxy-agent

**Comment by Nic2309** [comment]
thx for the fast help, i'll test tomorrow and edit this comment!

**Comment by rom1504** [comment]
seems pretty clear, is your proxy working ?

**Comment by Nic2309** [comment]
i was looking for some proxy (socks5) lists in the internet, but maybe they are all not working?

**Comment by rom1504** [comment]
Yeah try to test them with another application (your browser for example)

**Comment by Nic2309** [comment]
https://prnt.sc/t0qa6c i tested all the green ones and even those aren't working 😕
Can i send a the code of the bot?

**Comment by rom1504** [comment]
did you validate any of them work using another application ?

**Comment by Nic2309** [comment]
yes i did, proxies are working just not in the program. Does it work for you?

**Comment by rom1504** [comment]
what code are you running exactly ?

**Comment by Nic2309** [comment]
exactly this proxy example which you've told me to try, getting same error as above. Maybe you can try it on the server playfuchsgames.de 25565 by using proxy: 50.62.61.96 46861 or 59.36.171.26 38801

**Comment by rom1504** [comment]
I fixed the example a bit, but there seems to be an issue in interaction between proxy agent and yggdrasil module
```
(node:12494) UnhandledPromiseRejectionWarning: Error: write EPROTO 140113582311296:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```
if you're ok with not going through the proxy for the mojang auth, then just comment the line starting with `agent:`

I might look what's up with yggdrasil

**Comment by Nic2309** [comment]
Ok i think it's almost working now, just sometimes getting errors like this 
iMac-Nic2309:examples nicolas$ node botsv2.js localhost 57520 104.248.63.15 30588 3 "Hi" 1 1
SocksClientError: Socks5 proxy rejected connection - Failure
    at SocksClient._closeSocket (/Users/nicolas/node_modules/socks/build/client/socksclient.js:368:32)
    at SocksClient.handleSocks5FinalHandshakeResponse (/Users/nicolas/node_modules/socks/build/client/socksclient.js:569:18)
    at SocksClient.processData (/Users/nicolas/node_modules/socks/build/client/socksclient.js:310:22)
    at SocksClient.onDataReceived (/Users/nicolas/node_modules/socks/build/client/socksclient.js:285:14)
    at Socket._onDataReceived (/Users/nicolas/node_modules/socks/build/client/socksclient.js:201:47)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  options: {
    proxy: { host: '104.248.63.15', port: 30588, type: 5 },
    command: 'connect',
    destination: { host: 'localhost', port: 57520 }
  }
}

**Comment by rom1504** [comment]
> SocksClientError: Socks5 proxy rejected connection - Failure

that's exactly what it says, can't do anything about it, just use another proxy server

**Comment by CrazyWords1** [comment]
Have the same error like this, proxy is good
SocksClientError: Socks5 proxy rejected connection - Failure
    at SocksClient._closeSocket (/Users/nicolas/node_modules/socks/build/client/socksclient.js:368:32)
    at SocksClient.handleSocks5FinalHandshakeResponse (/Users/nicolas/node_modules/socks/build/client/socksclient.js:569:18)
    at SocksClient.processData (/Users/nicolas/node_modules/socks/build/client/socksclient.js:310:22)
    at SocksClient.onDataReceived (/Users/nicolas/node_modules/socks/build/client/socksclient.js:285:14)
    at Socket._onDataReceived (/Users/nicolas/node_modules/socks/build/client/socksclient.js:201:47)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  options: {
    proxy: { host: '104.248.63.15', port: 30588, type: 5 },
    command: 'connect',
    destination: { host: 'localhost', port: 57520 }
  }
}

**Comment by Aroxis** [comment]
> can you try https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js ?

This only worked for me after adding host and port to the config besides agent, username and password.

**Comment by hdhdheheheh198-glitch** [comment]
Please help me with premium mobile socks5 proxies , here is the code: """const mineflayer = require('mineflayer');
const { SocksClient} = require('socks');
const bot = mineflayer.createBot({
 host: 'hidden',
port: 25565,
username: 'jshser',
auth: 'offline',
connect: (client) => {
 SocksClient.createConnection({
proxy: {
ipaddress: '185.189.132.214',
port: 17103,
type: 5,
userId: 'hidden',
 password: 'hidden'
},
command: 'connect',
 destination: {
 host: client.host,
 port: client.port
 }
 }, (err, info) => {
 if (err) return console.error('Proxy connection error:', err.message);
 client.setSocket(info.socket);
 client.emit('connect');
 });
 }
});
bot.on('login', () => console.log(`Bot ${bot.username} logged in via proxy.`));
bot.on('spawn', () => console.log('Bot spawned.'));
bot.on('error', (err) => console.error('Bot error:', err));
bot.on('kicked', (reason) => console.log('Bot kicked:', reason));
bot.on('end', () => console.log('Disconnected.'));
""" the server for connection works, it also works in geoproxy, the proxy itself works through proxyfier, and moreover, you can use proxyfier to connect to this server via this domain, that is, everything works in the console, the IP proxy is displayed, that is, everything works, but with this code it always outputs a "Connection broken: socketClosed " as I have not tried, if anything the problem is not in the server, I tried and does not work with any server.😭😭😭

**Comment by hdhdheheheh198-glitch** [comment]
And that's how I understood that the problem is with the domain.
