### ISSUE TITLE
Hold LClick

### ISSUE THREAD

**Issue by Lucasx150** [PrismarineJS/mineflayer#1058]
## Versions
 - mineflayer:2.19.0
 - server: vanilla/spigot/paper vanilla 1.8
 - node: v12.18.0

## Detailed description of a question
How can i hold the left mouse button? I want to make a cobblestone farming bot (skyblock cobblestone generator)

**Comment by superego546** [comment]
Take a look at this.

https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/digging.js

**Comment by wvffle** [comment]
A simplified behavior of a minecraft client is that it when currently digged block is being broken, next block in line with cursor gets targeted and the digging packets are sent for those block. 

You can either use this approach or:
- save locations of 4 blocks before you to some variable
- listen to events on those for blocks
- if distance between new block and player is less than distance of currently digged block and player
  - cancel digging
  - start digging closer block
