### ISSUE TITLE
findBlocks doesn't work

### ISSUE THREAD

**Issue by vasyaaliseychik** [PrismarineJS/mineflayer#1059]
- mineflayer: 2.19.0
 - server: vanilla 1.12.2
 - node: v12.18.0

Hi. I've got a problem. `findBlocks` doesn't work. I'm trying to launch one of the example scripts.
That's it: https://github.com/PrismarineJS/mineflayer/blob/master/examples/farmer.js

When I start it, I'm gettting the following every second:
```
TypeError: Cannot read property '0' of undefined
    at Bot.bot.findBlocks (C:\.pp\bot\node_modules\mineflayer\lib\plugins\blocks.js:154:40)
    at Bot.findBlock (C:\.pp\bot\node_modules\mineflayer\lib\plugins\blocks.js:182:24)
    at blockToHarvest (C:\.pp\bot\1.js:39:14)
    at Timeout.loop [as _onTimeout] (C:\.pp\bot\1.js:49:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
I added console.log in findBlocks function (it's located in mineflayer/lib/plugins/blocks.js in line ~150) 

```
    const it = new OctahedronIterator(start, maxDistance)
    // the octahedron iterator can sometime go through the same section again
    // we use a set to keep track of visited sections
    const visitedSections = new Set()
    let startedLayer = 0
    let next = start
    while (next) {
      const column = columns[columnKeyXZ(next.x * 16, next.z * 16)]
-->console.log(column);
      if (next.y >= 0 && next.y < 16 && column && !visitedSections.has(next.toString())) {
        const section = column.sections[next.y]; <-- cause error
        if (isBlockInSection(section, matcher)) {
          const cursor = new Vec3(0, 0, 0)
          for (cursor.x = next.x * 16; cursor.x < next.x * 16 + 16; cursor.x++) {
            for (cursor.y = next.y * 16; cursor.y < next.y * 16 + 16; cursor.y++) {
              for (cursor.z = next.z * 16; cursor.z < next.z * 16 + 16; cursor.z++) {
                const found = bot.blockAt(cursor, false)
                if (matcher(found)) blocks.push(cursor.clone())
              }
            }
          }
```
and get this:
```
Chunk {
  data: <Buffer 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 70 00 ... 196814 more bytes>,
  hasSkylight: true
}
```
It seems that there are no `sections` property in `column` object.

Please help me)

**Comment by rom1504** [comment]
What minecraft version ?

**Comment by rom1504** [comment]
Problem is in 1.9-1.12
https://github.com/PrismarineJS/prismarine-chunk/issues/85

This find block implementation is uses .section which is not exposed in prismarine-chunk (not in API) and indeed not implemented that way.
We need to either stop using . sections either change implementation for 1.9 and add sections to the API

(cc @Karang do we really need to expose .sections ?)

**Comment by rom1504** [comment]
Related https://github.com/PrismarineJS/mineflayer/issues/1060

**Comment by Karang** [comment]
> Problem is in 1.9-1.12
> [PrismarineJS/prismarine-chunk#85](https://github.com/PrismarineJS/prismarine-chunk/issues/85)
> 
> This find block implementation is uses .section which is not exposed in prismarine-chunk (not in API) and indeed not implemented that way in 1.9.
> We need to either stop using . sections either change implementation for 1.9 and add sections to the API
> 
> (cc @Karang do we really need to expose .sections ?)

Yes we need to expose sections.

**Comment by rom1504** [comment]
I did it, just run `npm update --depth 9999`

**Comment by vasyaaliseychik** [comment]
thank you very much, but it doesn't work anyway. Now it just can't find any block

**Comment by vasyaaliseychik** [comment]
additional info: minecradt version: 1.12.2

the code I used:

```
const Vec3 = require('vec3')
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  
  port: parseInt(process.argv[2]),
  username: 'farmer',
})

let mcData
bot.on('inject_allowed', () => {
  mcData = require('minecraft-data')(bot.version)
})

// To fish we have to give bot the seeds
// /give farmer wheat_seeds 64

function blockToSow () {
  return bot.findBlock({
    point: bot.entity.position,
    matching: (block) => {
      if (block && block.type === mcData.blocksByName.farmland.id) {
        const blockAbove = bot.blockAt(block.position.offset(0, 1, 0))
        return !blockAbove || blockAbove.type === 0
      }

      return false
    },
  })
}

function blockToHarvest () {
  return bot.findBlock({
    point: bot.entity.position,
    matching: (block) => {
      if (block.type === mcData.blocksByName.wheat.id && block.metadata === 7) {
        return true;
      }
      //return block && block.type === mcData.blocksByName.wheat.id && block.metadata === 7
    },
  })
}

function loop () {
  try {
    const toHarvest = blockToHarvest()
    console.log(toHarvest);
    if (toHarvest) {
      return bot.dig(toHarvest, () => {
        return setImmediate(loop)
      })
    }
    
    const toSow = blockToSow()
    console.log(toSow);
    if (toSow) {
      return bot.equip(mcData.itemsByName.wheat_seeds.id, 'hand', () => {
        bot.placeBlock(toSow, new Vec3(0, 1, 0), () => {
          setImmediate(loop)
        })
      })
    }
  } catch (e) {
    console.log(e)
  }

  // None blocks to harvest or sow. Postpone next loop a bit
  setTimeout(loop, 1000)
}

bot.once('login', loop)
```
I debugged a bit, and as I understand there something wrong with `columns`: my world and id's in palettes doesn't match. 
There I'm on beginning of the column, And there's only one object in the section: redsone torch. 
![image](https://user-images.githubusercontent.com/42637020/84760265-72a9a400-afd0-11ea-8fc4-70ad4bb0c5fa.png)
But when I look in debugger, there are more than one id's.
![image](https://user-images.githubusercontent.com/42637020/84760860-4b9fa200-afd1-11ea-836b-a7b5f0166351.png)

![image](https://user-images.githubusercontent.com/42637020/84761001-7c7fd700-afd1-11ea-9c70-81d3efc3c340.png)

**Comment by rom1504** [comment]
did you update the dependencies ? (run `npm update --depth 999`)

**Comment by vasyaaliseychik** [comment]
yes

**Comment by vasyaaliseychik** [comment]
You mean npm update --depth 9999?

> I did it, just run `npm update --depth 9999`

**Comment by vasyaaliseychik** [comment]
is my json correct?
```
{
  "name": "bot",
  "version": "1.0.0",
  "description": "farmer bot",
  "main": "1.js",
  "dependencies": {
    "minecraft-data": "^2.55.0",
    "mineflayer": "^2.19.2",
    "mineflayer-navigate": "0.0.10"
  },
  "devDependencies": {},
  "scripts": {
    "test": "none"
  },
  "author": "",
  "license": "ISC"
}

```

**Comment by rom1504** [comment]
which one is failing in your code exactly ? the `blockToSow` has a weird matching function

**Comment by vasyaaliseychik** [comment]
I've just tested this script in 1.15.2 and find this error in `blockToSow`:
```
TypeError: Cannot read property 'offset' of null
    at matching (C:\.pp\bot\1.js:23:55)
    at isBlockInSection (C:\.pp\bot\node_modules\mineflayer\lib\plugins\blocks.js:127:13)
    at Bot.bot.findBlocks (C:\.pp\bot\node_modules\mineflayer\lib\plugins\blocks.js:153:13)
    at Bot.findBlock (C:\.pp\bot\node_modules\mineflayer\lib\plugins\blocks.js:180:24)
    at blockToSow (C:\.pp\bot\1.js:19:14)
    at Timeout.loop [as _onTimeout] (C:\.pp\bot\1.js:54:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
but in 1.12.2 there are another thing

**Comment by vasyaaliseychik** [comment]
I mean, yeah, `blockToSow` is incorrect, but `findblocks` in 1.12.2 is also incorrect.

**Comment by rom1504** [comment]
yes your `blockToSow` code is incorrect, but I was asking which findBlocks code you are using is not working (beside blockToSow) ?

**Comment by vasyaaliseychik** [comment]
another script that doesn't work in 1.12.2:

```
const mineflayer = require('mineflayer')
const bot = mineflayer.createBot({
  port: 55288,
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  switch (message) {
    case 'sleep':
      goToSleep()
      break
    case 'wakeup':
      wakeUp()
      break
  }
})

bot.on('sleep', () => {
  bot.chat('Good night!')
})
bot.on('wake', () => {
  bot.chat('Good morning!')
})

function goToSleep () {
  const bed = bot.findBlock({
    matching: block => bot.isABed(block)
  })
  if (bed) {
    bot.sleep(bed, (err) => {
      if (err) {
        bot.chat(`I can't sleep: ${err.message}`)
      } else {
        bot.chat("I'm sleeping")
      }
    })
  } else {
    bot.chat('No nearby bed')
  }
}

function wakeUp () {
  bot.wake((err) => {
    if (err) {
      bot.chat(`I can't wake up: ${err.message}`)
    } else {
      bot.chat('I woke up')
    }
  })
```
also from the examples folder

**Comment by rom1504** [comment]
ok I'll have a look

**Comment by vasyaaliseychik** [comment]
thank you

**Comment by rom1504** [comment]
ok I used tried https://github.com/PrismarineJS/mineflayer/blob/master/examples/sleeper.js
it works fine on 1.12.2 vanilla ?

what server did you try this one ?

**Comment by rom1504** [comment]
also tried https://github.com/PrismarineJS/mineflayer/blob/master/examples/blockfinder.js which works fine

**Comment by vasyaaliseychik** [comment]
it didn't work because I'm didn't reset dependencies myself. I thought what it's making automatically.
After I reset it with `npm init` everything become perfect. I'm just a novice to nodeJS. Thank you very much. Your Api is awesome!
