### ISSUE TITLE
findBlocks doesn't work again

### ISSUE THREAD

**Issue by vasyaaliseychik** [PrismarineJS/mineflayer#1061]
previous: https://github.com/PrismarineJS/mineflayer/issues/1059
 - server: vanilla 1.12.2 

Now it's just can't find any blocks

**Comment by rom1504** [comment]
You can reopen an issue if it's the same one.
Can you post the code you used and all the context ? (Minecraft version, mineflayer version,...)

**Comment by rom1504** [comment]
it's now fixed, just run `npm update --depth 9999`

**Comment by vasyaaliseychik** [comment]
I cant reopen my issue if you closed it
