### ISSUE TITLE
"chestLidMove" is triggered twice on a double chest

### ISSUE THREAD

**Issue by MrZillaGold** [PrismarineJS/mineflayer#1064]
## Detailed description of a problem
When catching the "chestLidMove" event, the handler trigger twice if the chest is double.

## Current code
```js
bot.on("chestLidMove", () => {
  console.log("Chest updated");
})
```

## Expected behavior
The handler is triggered once, regardless of the type of chest.

**Comment by rom1504** [comment]
Well it kind of makes sense, there is 2 chest. Do you think it would be better to have only one event emitted ?

**Comment by MrZillaGold** [comment]
Yes, you can make a separate type event or parameter. These two events have a difference in only 1 coordinate.

**Comment by rom1504** [comment]
how would it be easier to use from the user side with one event ? what is your use case ?

**Comment by MrZillaGold** [comment]
You can create a separate type and in position pass an array of Vec3 objects. I want to receive an event and send a notification to one of the social networks along with the coordinates of the chest.

**Comment by rom1504** [comment]
Ok, feel free to implement it

**Comment by wvffle** [comment]
Is there a way to check if 2 chests are double chests? You can put multiple chests in line while holding shift.

**Comment by rom1504** [comment]
Yes it's possible, it's needed to simulate the same logic the server has to detect and create double chests, store these chests then whenever you have an event check in this list and emit only once.
Maybe there's an easier way if the server send the chest information using block entities.

Anyway, this is not trivial to do and for this use case there are much easier approximate ways (like storing the position of the event you just send and if it's nearby don't send it again)

**Comment by ImHarvol** [comment]
> Maybe there's an easier way if the server send the chest information using block entities.

I think it does. In 1.12.2 (you couldn't place chests together by shift-clicking) it doesn't send any info, but since the shift-click change, the server sends a `type` property with one of this values:
* single
* left
* right

I might work on this :smile:
