### ISSUE TITLE
bot.chat isn!t working

### ISSUE THREAD

**Issue by MikeMottonix** [PrismarineJS/mineflayer#1066]
## Versions
 - mineflayer: newest
 - server: vanilla 1.15.2
 - node: 12

the bot isn't chatting but the food-level gets shown when i do #food , why?
The code:
app.get('/chat', function (req, res) {
  if(req.query.msg) {
    var message = req.query.msg
    if(message == "#food") {
      chatLog.push("Hunger: " + bot.food)
      if(chatLog.lenght > 10) {
        chatLog.shift()
      }
    } else {
      bot.chat(message)
      if(chatLog.lenght > 10) { 
        chatLog.shift() 
      } 
    }
  }
  res.sendFile(__dirname + "/index.html");
});

**Comment by MikeMottonix** [comment]
Im using Raspberry Pi os.
On my laptop with Peppermint it worked

**Comment by rom1504** [comment]
can you share a fully working minimal example ? are you doing this after the bot spawned ?

**Comment by MikeMottonix** [comment]
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send({"content": chatLog});
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});



const mineflayer = require('mineflayer')
//SERVER GESTARTET

const fs = require('fs');

let rawdata = fs.readFileSync('account.json');
let loginInfos = JSON.parse(rawdata)

//ACCOUNT.JSON AUSLESEN

var chatLog = ["NO", "NO EasterEgg"]

const bot = mineflayer.createBot({
  host: "mc.peacefulvanilla.club",
  port: 25565,
  username: loginInfos.email,
  password: loginInfos.passw,
  version: "1.15.2"
})

//MINEFLAYER STARTEN

bot.on('login', () => {
  bot.setControlState('forward', true)
  setTimeout(function() {
    bot.setControlState('back', true)
    setTimeout(function() {
    bot.clearControlStates()
    }, 400)
  }, 300)
})

//BEIM LOGIN BEWEGEN

app.get('/chat', function (req, res) {
  if(req.query.msg) {
    var message = req.query.msg
    if(message == "#food") {
      chatLog.push("Hunger: " + bot.food)
      if(chatLog.lenght > 10) {
        chatLog.shift()
      }
    } else {
      bot.chat(message)
      if(chatLog.lenght > 10) {
        chatLog.shift()
      }
    }
  }
  res.sendFile(__dirname + "/index.html");
});

//CHATEN VIA WEBSITE

var radarPlugin = require('mineflayer-radar')(mineflayer);
var options = {
  host: '0.0.0.0',
  port: 3001,
}
radarPlugin(bot, options);
//RADAR UND INVENTAR STARTEN


bot.on('chat', (username, message) => {
  //console.log(username + "  >  " + message)
  chatLog.push(username + " > " + message)
  if (chatLog.length > 10) {
    chatLog.shift()
  }
});

//CHAT AUSLESEN

setInterval(function () {
  if (bot.food < 8) {
    console.log("Hunger zu groß... Beende .....")
    proces.exit()
  }
}, 1000);


//AUTO HUNGER LEAVING

**Comment by MikeMottonix** [comment]
and im first chatting when the bot is online

**Comment by rom1504** [comment]
any error ?

can you enable debug mode and report the output ? https://github.com/PrismarineJS/node-minecraft-protocol#debugging

**Comment by MikeMottonix** [comment]
there isn't an error.
That's why I'm asking.
But there is this:

(node:13892) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by rom1504** [comment]
What about my second question

**Comment by MikeMottonix** [comment]
The debug screen is running endless.
What do you need of it?

**Comment by MikeMottonix** [comment]
(node:2246) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at ServerResponse.res.setHeader (/home/pi/bot/node_modules/connect/lib/patch.js:48:14)
    at expressInit (/home/pi/bot/node_modules/express/lib/middleware/init.js:30:42)
    at Layer.handle [as handle_request] (/home/pi/bot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/bot/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/bot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/bot/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/bot/node_modules/express/lib/router/index.js:275:10)
    at query (/home/pi/bot/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/home/pi/bot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/bot/node_modules/express/lib/router/index.js:317:13)


i get this when i run: node --trace-deprecation afk.js

**Comment by SiebeDW** [comment]
Are u sure incoming requests are working?

**Comment by MikeMottonix** [comment]
If its running on my Laptop it is working.
If its running on my Raspberry Pi it isnt working, when i use the Laptop to chat with the site.
But... if i use the Chat function from my IPad and IMac (the script is runnning on the Pi) its working.
Can it be the Browser?
Im using Firefox and Safari on the Apple Devices and Brave on the Laptop.
