### ISSUE TITLE
Fast digging

### ISSUE THREAD

**Issue by RealPeha** [PrismarineJS/mineflayer#1067]
## Versions
 - mineflayer: 2.20.0
 - server: vanilla 1.15.2
 - node: 13.9.0

## Detailed description of a question
Is there any way to make the bot dig blocks as quickly as possible?

I wrote this code:
(I also use a [pathfinder](https://github.com/Karang/mineflayer-pathfinder) plugin)
```js
const currentBlock = mcData.blocksByName.gold_block

const dig = () => {
	const block = bot.findBlock({
       		matching: currentBlock.id,
		maxDistance: 1
	})

	if (!block) {
		return bot.chat('Не могу найти этот блок поблизости')
	}

	bot.pathfinder.setMovements(defaultMove)
	bot.pathfinder.setGoal(new GoalNear(block.position.x, block.position.y, block.position.z, 1))

	bot.once('goal_reached', () => {
		bot.chat('Копаю')
      		bot.dig(block, () => {
			bot.chat('Выкопал')
			dig()
		})
	})
}
```

The problem is that he slowly digs block by block. I want to achieve the effect of digging as when holding the left mouse button. I tried other ways to find the blocks that need to be dug, but this is not the problem and it still digs slowly

**Comment by wvffle** [comment]
There is no such thing as 'hold left click' in vanilla minecraft client. It works 'slowly' as well.

See https://github.com/PrismarineJS/mineflayer/issues/1058#issuecomment-644386645

**Comment by rom1504** [comment]
@RealPeha do you observe vanilla client digging faster than the bot ?
It's not impossible our calculation for some tools/blocks is off.

**Comment by RealPeha** [comment]
@rom1504 if I take in my hand a pickaxe with enchantment for level 10 effectiveness and hold down the left mouse button, I will dig very quickly. But if I give this pick to the bot, then he slowly digs block by block, focusing on each of them

**Comment by wvffle** [comment]
Enchantments are not implemented yet. Feel free to make them work :)

**Comment by RealPeha** [comment]
I would really like to help you with this, but I don’t know if I can figure out how it works.

**Comment by Karang** [comment]
This is a relatively easy issue to solve:
* Here is the function that needs to be modified: https://github.com/PrismarineJS/prismarine-block/blob/master/index.js#L109
* And here is what it should look like: https://minecraft.gamepedia.com/Breaking#Calculation

Finally implementing enchantments will be appreciated by a lot of people :)
