### ISSUE TITLE
Investigate chest on some spigot servers

### ISSUE THREAD

**Issue by 6ixDev** [PrismarineJS/mineflayer#1084]
Hey, so im trying to make the bot open a chest. I just cant get it to work, cause all of the code seems fine to me.
code:
```js
var blockObj = bot.getInstance().blockAt(blockPos);
if (blockObj != null && (blockObj.name == 'trapped_chest' | blockObj.name == 'chest')) {
    var chest = bot.getInstance().openChest(blockObj); //getInstance() returns the current bot object
    chest.on('open', (window) => {
        console.log("yee it fking worked");
        exports.mapping.set(blockPos, window.containerItems());
        bot.getInstance().closeWindow(window);
    })
}
```
The bot is right next to the chest at BlockPos, and i can see him turning and swinging his hand at the chest, it just wont open.
could this be because of the servers anticheat? (it only lets you open a chest while looking at it)

I already spent about 5Hours trying different stuff. 

Thanks already and sorry for bad english.

**Comment by rom1504** [comment]
How far is the chest ?

**Comment by rom1504** [comment]
Does it work on vanilla ?

**Comment by 6ixDev** [comment]
The chest is 1.4 blocks away from the bot.
ill try on my private vanilla in a sec

**Comment by 6ixDev** [comment]
just tested, nope, it doesnt work on a 1.8.9 spigot server without gameplay relevant plugins.

**Comment by Shiiiwa** [comment]
is there now a solution ?

**Comment by rom1504** [comment]
No but also the problem is not identified or reproducible

**Comment by rom1504** [comment]
reopen if you still have the problem

**Comment by TacoNoBurrito** [comment]
im having the same issue, the bot gets close to the chest, turns, and then theres a swinging animation. The chest is never opened and no items are ever deposited. There is no error.
