### ISSUE TITLE
On a specific spigot server the bot get kicked

### ISSUE THREAD

**Issue by mihabozic123** [PrismarineJS/mineflayer#1088]
[ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.22.0
 - server: spigot (i think)
 - node: 12.18.1

## Detailed description of a problem
When i run the bot, it sometimes spits the [bot object](https://pastebin.com/NJvEjA19) and exits the process or dies without spitting it.

## Current code
```js
const mineflayer = require("mineflayer");

const bot = mineflayer.createBot({
host: "play.galacticpvp.me",
port: 25565,
username: "no",
password: "no",
version: false
});

bot.on("chat", (username, message) => {
  if (username == "mihabozic321" || "1133") {
    if (message == "!start") {
      bot.chat("Starting...");
      setTimeout(() => {
        bot.chat("/server bukkit-galactic");
      }, 300000);

      setTimeout(() => {
        bot.chat("/f c f");
        bot.chat("Don't forget to check the walls!!");
      }, 600000);
    }
  }
});

bot.on("error", err => console.log(err));

bot.on("login", () => {
console.log(bot.username + " is online!")
});
``` 
or 
```js
const mineflayer = require("mineflayer");
```
(both same result)

## Expected behavior
It should join the server and send the command `/server bukkit-galactic` every 5 minutes and `/f c f` and "Don't forget to check the walls!!" every 10 minutes.

## Additional context
i removed everything except const mineflayer and it still got logged in console (sometimes the process just dies without logging the bot object) if i add a console.log under the const it logs it and dies

**Comment by 6ixDev** [comment]
what I think your code does:
the bot 
connects to server
waits for x to chat !start
then, after...
-> 5mins chats something
-> 10mins chats something
end. (back to waiting for !start)

so i dont see why he would chat every x minutes after a specific player says !start.
this might not be specifically your problem, but its the first thing i thought wenn seing the "Expected Behaviour".
PS: sorry for my english.

**Comment by wvffle** [comment]
Check if bot is kicked or not with a special event handler. This might be the case why it 'dies'. 
If that doesn't work, use the debug flag and post the result on gist. You can read about it in the readme.

It's weird that is logs the bot instance though. Seems like some console.log in the code or it may be thrown for some reason somewhere.

**Comment by rom1504** [comment]
reopen if it's still a problem
