### ISSUE TITLE
Consider using merge release action

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#1092]
https://github.com/mikeal/merge-release

Benefit : all commits are released automatically
Drawback : no history.md, package.json not updated (must stay at version "0.0.0-dev")

Basically commit log becomes the history
It means being more careful about the commit log

Not really sure if this would be the best choice

Maybe only for some repos who have more trivial changes

**Comment by G07cha** [comment]
It's also possible to automate changelog generation and updating version in package.json by using tools like [standard-version](https://github.com/conventional-changelog/standard-version). But that also implies your point to be more careful with commit log which could be somewhat prevented by using [commitlint](https://github.com/conventional-changelog/commitlint) but that could deter potential new contributors.

**Comment by rom1504** [comment]
let's not
