### ISSUE TITLE
bot.dig freezes after 100th or so call

### ISSUE THREAD

**Issue by thesourceoferror** [PrismarineJS/mineflayer#1096]
## Versions
 - mineflayer: 2.21.0
 - server: vanilla/spigot/paper 1.15.2
 - node: 12.18.1

## Detailed description of a problem
I am developing a famer bot, and the bot walks over a layer of soul sand to both harvest and sow nether warts. However, after a couple minutes or so of harvesting, the bot freezes.

## Expected behavior
Simply expect the bot to break a block, without freezing.

## Additional context
I need to call the function bot.dig(block, cb) quite frequently, which is where I encounter a problem. Most of the time, bot.dig works just perfectly, however, once every 100th or so function call, it freezes, and with it the whole bot.

I looked into the source code and where it stalls seems to be in a function called "checkYaw" in plugins/physics.js, in which there is an if statement that requires a math equation to be less than 0.001, however, when the bug is encountered, this statement is at a consistent 2PI instead of dropping towards 0.001.

I havent investigated the issue further.

**Comment by rom1504** [comment]
Interesting. 2Pi is indeed the same as 0
Probably something somewhere doesn't reset it to 0.

**Comment by thesourceoferror** [comment]
Fixed with pull request #1101
