### ISSUE TITLE
"playerJoined" event emits in wrong context

### ISSUE THREAD

**Issue by thesourceoferror** [PrismarineJS/mineflayer#1103]
## Versions
 - mineflayer: 2.21.0
 - server: spigot 1.15.2
 - node: 12.18.1

## Detailed description of a problem
When the bot joins the server, it will emit "playerJoined" for all the current, already active players in the server, as opposed to calling it once the players join the server.

## Current code
```js
bot.on("playerJoined", player => {
    console.log(player.username + " joined the game!");
});
```

## Expected behavior
I expected the "playerJoined" to be emitted, only when the players join the server. However, the bot emits the event for all the already active players on the server, when the bot joins the server.

**Comment by rom1504** [comment]
Sounds to me like the current behavior makes the most sense. It means "all
these players are new"
What is your use case ?
Maybe we can introduce a new event for it

**Comment by thesourceoferror** [comment]
Fair enough. I just imagined it to only emit once these players actually join the server, and not when the bot discovers "new players". It just caused a slight confusion.
