### ISSUE TITLE
Returned username using custom Prefixes and Suffixes truncates string before last space.

### ISSUE THREAD

**Issue by DrakoTrogdor** [PrismarineJS/mineflayer#1111]
[X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.22.0
 - server: paper 1.16.1 Build 47
 - node: 12.4.0

## Detailed description of a problem
Paper server has VaultChatFormatter 1.0 to enable custom player prefixes/suffixes. When sending chat to the bot the function(username, message) only has the last word of the username. i.e. current username is "DrakoTrogdor", but I have the prefix "&7[&5VIP&7]&r" ( "[VIP]" with some color coding ) and the suffix ", &4T&ch&6e &eB&6u&cr&en&ci&6n&ea&6t&co&4r&r" ( "The Burninator" also with color coding ). Code is returning "Burninator" as username

## Current code
```js
bot.on('chat', function(username, message, translate, jsonMsg, matches) {
  if (debugging) {
    console.log('Username:');
    console.log(username);
    console.log('Message:');
    console.log(message);
    console.log('Translate:');
    console.log(translate);
    //console.log('JSON Message:');
    //console.log(jsonMsg);
    console.log('Matches:');
    console.log(matches);
  }
  var isMeRegex = new RegExp('^((?:\\[.+\\]\\s*)?\\@?' + bot.username + '(?:\\s+|$))','i');
  if (username.match(isMeRegex)) return;
  message=message.trim();
  if (debugging) console.log(message);
  if (message.match(isMeRegex)) {
    message = message.replace(isMeRegex,'').trim();
    var command = message.replace(/\s.*/,'').toLowerCase();
    message = message.replace(/^[^\s]+/,'');
    switch (command) {
      case 'say':
        bot.chat(message);
        break;
      case 'come':
      case 'hither':
        bot.chat('I have not figured out how to "come" yonder yet.');
        break;
      default:
        bot.chat('I am still quite intellectually simple-minded.  Please program "' + command + '" into my lexicon.');
        break;
    }
    console.log('I have received a command.');
  }
});
bot.on('error', err => console.log(err));
})
```

## Expected behavior
The "username" variable should be set to the string "[VIP] DrakoTrogdor, The Burninator" or some variation possibly with color coding characters (I would parse it after that).
My current code requires that I type the message as "<botname> <command> [something]", such as "DrakaTrogdor say hello" (where DrakaTrogdor is the name of my bot account).

## Additional context
Current server is running on Paper-1.16.1+build.47 with LuckPerms-Bukkit-5.1.66, Vault-1.7.2, and VaultChatFormatter-1.0.0 in order to manage username prefixes and suffixes.

**Comment by rom1504** [comment]
You can look at the chat pattern example or just use message event and do it yourself

**Comment by DrakoTrogdor** [comment]
Thank you for letting me know. I can confirm this works and was never a bug in the first place! 10/10 stars! AAA+ rating, <add superlatives here>.
