### ISSUE TITLE
Is there any way I can log into an NFA account (no email and password) like the ones at alt.shop with Mineflayer?

### ISSUE THREAD

**Issue by Kenzoid** [PrismarineJS/mineflayer#1116]
Hey, so I've been thinking about buying some alts at alt.shop but I'm wondering if I can get NFA alts which use tokens or some other verification to play to interact with the Mineflayer package?

**Comment by MrKinauJr** [comment]
I never used alts.shop but you might be able to with the clientToken and accessToken.

**Comment by WeiiswurstDev** [comment]
NFA Account =
You get email and password (and you can login with those)
You do NOT get security question answers or access to the email adress ==> You cannot change skin, email or other settings.

**Comment by MrKinauJr** [comment]
That's true, but some services like Altening only give out tokens. Not the actual account info.

**Comment by WeiiswurstDev** [comment]
If you want to use TheAltening or MCLeaks tokens, you have to implement the
API of the service of your choice yourself. There are docs for that.

MrKinauJr <notifications@github.com> schrieb am Mo., 6. Juli 2020, 18:46:

**Comment by mmccall0813** [comment]
> If you want to use TheAltening or MCLeaks tokens, you have to implement the API of the service of your choice yourself. There are docs for that.
I cant find that in the docs

**Comment by satyamedh** [comment]
@mmccall0813 Those accounts are mostly hacked accounts. I would say not to support them and buy the accounts. if you would like to go ahead, those accounts will be useless after the migration is over. @rom1504 I think you should make a rule on not supporting questions that involve these hacked accounts, as they are literally a crime, stealing!

**Comment by WeiiswurstDev** [comment]
I meant docs from TheAltening and McLeaks. Their API is documented, you
just have to implement it.

**Comment by satyamedh** [comment]
LOLOL 10 SECOND DIFFERENCE

**Comment by tropeco777** [comment]
como crio ou extraio uma conta nfa ?

**Comment by furkankoykiran** [comment]
I’ve only seen people logging into their Minecraft accounts using sessions, and I’m looking for websites where I can get sessions like that. What should I search for to find those kinds of sites?
