### ISSUE TITLE
make it possible to hide warnings :  unknown transaction confirmation

### ISSUE THREAD

**Issue by PnsDev** [PrismarineJS/mineflayer#1117]
My console keep spamming warning along the line of this and I'm not sure what it means, could someone help me with this:

WARNING : unknown transaction confirmation for window 0, action 2871 and accepted false WARNING : unknown transaction confirmation for window 0, action 1966 and accepted false WARNING : unknown transaction confirmation for window 0, action 1001 and accepted false WARNING : unknown transaction confirmation for window 0, action 1863and accepted false WARNING : unknown transaction confirmation for window 0, action 1625 and accepted false

All I'm doing is reading chat. Nothing else.

**Comment by Nurutomo** [comment]
sometimes this happens to me too!
I tried to hide it. but don't know where the message or error came from?

maybe this message or error came from prismarine-window

Pada tanggal Sen, 6 Jul 2020 20.32, Jose Casas <notifications@github.com>
menulis:

**Comment by rom1504** [comment]
We could hide it but it just means your server is doing incorrect things
with inventory

**Comment by PnsDev** [comment]
I'll just try to hide it, do you know where it comes from and how I could hide it? @rom1504

**Comment by Karang** [comment]
Here is the line: https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js#L477
You can comment/remove it to hide the message.

**Comment by rom1504** [comment]
You could add a if(!options.hideErrors) there

**Comment by Oreoezi** [comment]
> My console keep spamming warning along the line of this and I'm not sure what it means, could someone help me with this:
> 
> WARNING : unknown transaction confirmation for window 0, action 2871 and accepted false WARNING : unknown transaction confirmation for window 0, action 1966 and accepted false WARNING : unknown transaction confirmation for window 0, action 1001 and accepted false WARNING : unknown transaction confirmation for window 0, action 1863and accepted false WARNING : unknown transaction confirmation for window 0, action 1625 and accepted false
> 
> All I'm doing is reading chat. Nothing else.

Certain anticheats send transactions. I'd assume it's watchdog in this case.

**Comment by rom1504** [comment]
As you can see above the hideErrors option allows you to ignore warnings

**Comment by Oreoezi** [comment]
I know

**Comment by INotSleep** [comment]
I dont want to hide errors. Im nothing do with my inventory. Why it error comes?

**Comment by U5B** [comment]
Server has anticheat that sends invalid packets. Mineflayer warns that the server is being weird.

**Comment by INotSleep** [comment]
Vulcan. Hmmm. what a packets?)

**Comment by U5B** [comment]
You can add hideErrors: true to hide it. Other than that, you can't really prevent the error from showing.
