### ISSUE TITLE
window.containerItems() is not a function

### ISSUE THREAD

**Issue by 6ixDev** [PrismarineJS/mineflayer#1118]
in the docs, it is said that, for instance, in this piece of code: (i updated mineflayer on my local mashine today)

bot.on("windowOpen",(window)=>{
       let a = window.containerItems();
})

the variable a would be a list containing item instances.

What happens though, is that an error is thrown, saying that window.containerItems() is not a function.
I believe that this is a bug, correct me if im wrong.

**Comment by rom1504** [comment]
Can you point to the doc that says this ?

**Comment by 6ixDev** [comment]
https://github.com/PrismarineJS/prismarine-windows

**Comment by 6ixDev** [comment]
is where i get redirected to when clicking on base class in these docs:
https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#windowswindow-base-class

**Comment by Naomi-alt** [comment]
Maybe try using `window.items()`?

It seems that there is no `containerItems` function, so the readme is not up to date.

**Comment by Karang** [comment]
You can use `window.itemsRange(0, window.inventoryStart)` (see https://github.com/PrismarineJS/mineflayer/blob/master/lib/chest.js#L31). The issue is now tracked at https://github.com/PrismarineJS/prismarine-windows/issues/11 (thanks Naomi)

**Comment by 6ixDev** [comment]
thanks!
