### ISSUE TITLE
what can i do after "not authenticated with minecraft.net" kickreason?

### ISSUE THREAD

**Issue by 6ixDev** [PrismarineJS/mineflayer#1119]
so, i have my script that always reconnects the bot.
The server the bot is on ocasionally opens a gui (for afk) that doesnt let the bot do anything until he leaves and reconnects.
i call bot.end() whenever that gui opens.
my problem now is that, when the bot then proceeds to reconnect (creates a new bot instance), he gets kicked for said reason, then reconnects and gets kicked for said reason (and so on).
How do i refresh the session without closing my program and re-running it? (using code)
sry for my english btw.

**Comment by Karang** [comment]
can you share the code you use for reconnecting ? If you recreate a bot from scratch, it should re-authenticate with mc.net
