### ISSUE TITLE
Accounts locked and not logging in.

### ISSUE THREAD

**Issue by GunnerBasil** [PrismarineJS/mineflayer#1121]
[ x ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.23.0
 - server: vanilla 1.12.2
 - node: 14.4.0

## Detailed description of a problem
I tried to log in with an account, but when I ran the script, it just said invalid credentials, and then I couldn't log into the account in the Minecraft launcher

## Current code
```js
const accounts = require('./accounts.json');

// import mineflayer
const mineflayer = require('mineflayer');
console.log(accounts.accounts[0][0]);
console.log(accounts.accounts[0][1]);

// setup options
const options = {
  host: '192.168.0.22', // optional / minecraft server address
  port: 25565, // optional
  username: accounts.accounts[1][0], // email and password are required only for
  password: accounts.accounts[1][1], // online-mode=true servers
  version: '1.12.2' // false corresponds to auto version detection (that's the default), put for example '1.8.8' if you need a specific version
};

// create bot
const bot = mineflayer.createBot(options);

bot.once('spawn', function () {
  bot.chat('hi!');
});
```

## Expected behavior
I expected the alt to log in and say hi, but that didn't happen.

**Comment by Karang** [comment]
You print `console.log(accounts.accounts[0][0]);`
But use `accounts.accounts[1][0]`
Is that correct ?

**Comment by thesourceoferror** [comment]
What I think happened here, is that you tried to login to the same account too frequently. This results in the account being, sort of, "closed" for a minute - This is to avoid brute-force attacks on minecraft accounts. So, a way to avoid getting the "invalid credentials" message, is to simply avoid logging in too frequently (which is several times a minute). Moreover, when you get the "invalid credentials" message from the mineflayer bot, you will not be able to login to your minecraft launcher for a while either. However, after a minute or so, you will be able to login to the account again.

**Comment by GunnerBasil** [comment]
ok, so update. I changed my code:
```js

// import mineflayer
const mineflayer = require('mineflayer');

// setup options
const options = {
  host: 'localhost', // optional / minecraft server address
  port: 25565, // optional
  username: '', // email and password are required only for
  password: '', // online-mode=true servers
  version: '1.12.2' // false corresponds to auto version detection (that's the default), put for example '1.8.8' if you need a specific version
};

// create bot
const bot = mineflayer.createBot(options);

bot.once('spawn', function () {
  bot.chat('hi!');
});
```
I left the login stuff empty, but I have valid logins. I'm now running this on my Mac, and in my launcher, I'm logged in to my account, but the other account is also there and I can log in to it as well. when I run the above code, the console output is the following:
```
Error: Invalid credentials. Invalid username or password.
    at /Users/av/Downloads/MCBotting/node_modules/yggdrasil/lib/utils.js:60:10
    at /Users/av/Downloads/MCBotting/node_modules/phin/lib/phin.js:89:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by GunnerBasil** [comment]
@thesourceoferror I haven't logged in using mineflayer in a while. any other ideas?

**Comment by thesourceoferror** [comment]
@GunnerBasil Perhaps you simply put in your username as opposed to the email attached to the account. Otherwise, I have no idea  why it doesnt work. Sorry.

**Comment by GunnerBasil** [comment]
I put in my email and password. darn :( is there like a support discord?

**Comment by thesourceoferror** [comment]
@GunnerBasil Indeed there is! In the README.md of the mineflayer repo, you will find a small black-green button saying "Chat on discord". Just press that, and voila!

**Comment by GunnerBasil** [comment]
thx!

**Comment by GunnerBasil** [comment]
ok, so I still need help :(

**Comment by Nurutomo** [comment]
`if (options.password.length) delete options.password`
Because mineflayer thinks if options has object password. It thinks you use
`online-mode=true` servers

Pada tanggal Rab, 8 Jul 2020 03.46, GunnerBasil <notifications@github.com>
menulis:

**Comment by Karang** [comment]
@GunnerBasil is it solved ?
