### ISSUE TITLE
Chunks don't unload, memory leak

### ISSUE THREAD

**Issue by algiuxass** [PrismarineJS/mineflayer#1123]
## Versions
 - mineflayer: 2.23.0
 - server: spigot 1.12.2
 - node: 12.13.1

## Detailed description of a problem
Memory leak when traveling, chunks don't unload.
Node.js will crash if you load too many chunks.

## Current code
```js
let mineflayer = require('mineflayer');

//heap grows when traveling
setInterval(()=>{
    let v = process.memoryUsage();
    console.log(v.rss/1000000+"MB", v.heapTotal/1000000+"MB");
},1000);

var bot = mineflayer.createBot({
    host: "127.0.0.1",
    port: 25565,
    username: 'test_bot',
    version: "1.12.2"
});

bot.on('message', function(message) {
  bot.chat(message);
});
bot.on('login', i=>console.log('Joined.'))
bot.on('end', i=>{
    console.log('Left.')
    process.exit();
})
bot.on('error', err => console.log(err))
```

## Expected behavior
Unload chunks when bot is out of rendering distance.

## Additional context
I manually teleported bot around the world just to make sure that it wasn't some bug in my code. I noticed that heap memory doesn't go lower.

**Comment by algiuxass** [comment]
```js
bot.on('chunkColumnUnload',(point)=>{
    console.log(point);
})
// output:
// Vec3 { x: NaN, y: 0, z: NaN }
```
This is weird.

**Comment by Karang** [comment]
In 1.12, the x/z values are names chunkX, chunkZ: https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.12.2/protocol.json#L1478
It needs to be fixed here https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/blocks.js#L262
But first, check if it was always missnamed, or if it change from one version to an other.

**Comment by algiuxass** [comment]
Made a PR. I wonder how this problem was unnoticed for so long?

**Comment by rom1504** [comment]
I guess people don't move their bot around that much. If you don't look for
it it'll get noticable only if you load like 10x the view size.
You'd have to do something a bit special (auto exploration I guess) to get
to this point

Thanks for finding and fixing this bug !

**Comment by IdanHo** [comment]
must have missed it when i wrote that, my bad :disappointed_relieved:

**Comment by rom1504** [comment]
thanks
