### ISSUE TITLE
bot.players[name].entity.position sometimes randomly doesnt find player?

### ISSUE THREAD

**Issue by 6ixDev** [PrismarineJS/mineflayer#1124]
i need a piece of code, that if a player(name) is not in renderdistance, says something in chat.
my code:
try{
      bot.players[name].entity.position
}catch{bot.chat("where did you go!?!")}

It just randomly catches eventhough the player is clearly in renderdistance(its executed on tick). Why is this? does anybody have a better piece of code?
Thanks :D

**Comment by rom1504** [comment]
Yes, use events

**Comment by 6ixDev** [comment]
my problem though is that players are given the ablility to morph into animals, and i want the bot to detect that. I know which players should be around me (by name), and need to see if all playernames in the list have playerentities around me.

**Comment by 6ixDev** [comment]
is this considered a bug? if yes, please fix it, i dont see any workaround by using events with my problem

**Comment by Karang** [comment]
It is not a bug, `bot.players` only contains player entities, if you want also mobs: `bot.entities` will give you everything.

**Comment by 6ixDev** [comment]
even with this code, he just sometimes doesnt find the player (especially while the player is moving)
var found = false;
            Object.values(bot.entities).forEach((entity)=>{
                
                if(entity.username !=null && entity.username !=undefined){
                    
                    if(entity.username == playername){
                        found = true;
                        console.log("FOUND!")
                    }
                }
            })

**Comment by Karang** [comment]
No it is not a bug, you need to read the doc:
https://github.com/PrismarineJS/prismarine-entity#entityusername
https://github.com/PrismarineJS/prismarine-entity#entitydisplayname

**Comment by rom1504** [comment]
What events did you try ?
Doing this check every tick is quite inefficient

**Comment by 6ixDev** [comment]
nevermind, i figured that the entities not being there randomly is a server-sided problem because it also happens when using similar code in Forge.
