### ISSUE TITLE
Interact with Entities

### ISSUE THREAD

**Issue by andrewrk** [PrismarineJS/mineflayer#113]
#### Unable to open minecart chest
it's an entity not a block

---
Edit:

Interacting with all entities needs to be implemented, including interacting with villagers
- Changed by @nevercast

**Comment by rom1504** [comment]
related to #179

**Comment by Gjum** [comment]
Is this working in the latest version?

**Comment by rom1504** [comment]
> interacting with villagers

This certainly isn't implemented.

**Comment by Gjum** [comment]
There could be a clear checklist of things that still need work.

**Comment by rom1504** [comment]
done !
