### ISSUE TITLE
can I login using a Client-or Access token?

### ISSUE THREAD

**Issue by 6ixDev** [PrismarineJS/mineflayer#1130]
So, in the docs it says:
clientToken : generated if a password is given
accessToken : generated if a password is given

Can i create a bot with these?
I have the problem, that the bot gets kicked(for any reason, mostly being the server restarting), it tries to reconnect but gets kicked for "not authenticated with minecraft.net".
Maybe that is because the session cant be renewed so fast (it reconnects instantly (on end)), so ill try to use the old one. 
Any ideas?

**Comment by MrKinauJr** [comment]
You might be able to set a session in the options while connecting to the bot. According to the Code in the minecraft-protocol repo it the session to the client obj. You might be able to login using the session then via settings the session parameter to the `bot._client.session` variable.

Basic Example

```js

bot.on('kicked',()=>{
    options.session = bot._client.session
    bot.connect(options)
})
```

I linked the code responsible for the login, incase i might be wrong and you wanna look for yourself.

[loginCode](https://github.com/PrismarineJS/node-minecraft-protocol/blob/54380a3cb7579bf040aafaa03ed7d3fbc99c4712/src/client/auth.js#L4)
