### ISSUE TITLE
Consider adding examples subfolder using some plugins

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#1136]
Using for example mineflayer pathfinder, prismarine viewer, etc
Make these folders have their own package.json so mineflayer itself doesn't depend on these plugins

similar to what is done there https://github.com/PrismarineJS/node-minecraft-protocol/tree/master/examples
(we don't need to make one folder per example, just create folders for the one that do need specific dependencies)

**Comment by Karang** [comment]
Can't we just link to the examples in the respective plugin packages ?

**Comment by rom1504** [comment]
We can do that too, but I think it's nice for users if they can just look at mineflayer examples and start playing with that.
I did an example of what I mean for the viewer there https://github.com/PrismarineJS/mineflayer/pull/1137

This is not meant to replace the example in the corresponding plugins (which can be more advanced / show more possibilities), but I think it's a good advertisement / doc for the existence and usefulness of these plugins.

What do you think ?
