### ISSUE TITLE
Click on NPC!

### ISSUE THREAD

**Issue by xjulianD** [PrismarineJS/mineflayer#1156]
[ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.24.0
 - server: spigot i think
 - node: v12.16.3

## Detailed description of a problem
Hello, I'm trying to make my bot join a server, click on a NPC that opens a window.
The problem is that the bot can't click on a NPC, I tried:
bot.activateEntity(entity)
bot.useOn(entity)
bot._client.write('use_entity', { ... });
#1133 #924 #826 #939 
Nothing worked, it doesn't trigger 'windowOpen' event (the npc/entity is armor stand)!

How to make the bot right click on the npc? (left click wont work..)
Help me plz, thanks.

## Current code
```js
let entity = getNPC();
bot.lookAt(entity.position.offset(0, 1, 0), false, async () => {
    await bot.setQuickBarSlot(2); // empty slot
    await sleep(500);
    await bot.activateEntity(entity, err => err ? console.error(err) : console.log('activated entity'));
});
```

## Expected behavior
To open a window and trigger 'windowOpen' event

**Comment by xjulianD** [comment]
Found the problem, I was trying to click on the armor stand (the nametag of the npc) not the player entity.

**Comment by MidlesLex** [comment]
is it possible for the bot to move to a cordinate
