### ISSUE TITLE
reconnect / move bot to a certain location

### ISSUE THREAD

**Issue by lol-sys** [PrismarineJS/mineflayer#1163]
## Versions
 - mineflayer: lastest
 - server: vanilla/spigot/paper 1.8
 - node: lastest

## Detailed description of a question

So if i want to move the bot to a location what i need to do and the kicked event applies on change server (bungeecord)

**Comment by rom1504** [comment]
that information is present in the readme and the examples

**Comment by lol-sys** [comment]
> 
> 
> that information is present in the readme and the examples

so wat i need to do is use vec3 to walk to a location 
and if i get kicked of the server and go to skyblock hub the bot just gonna handle it like a disconect function?

(im trying to do a skyblock afk bot)

**Comment by rom1504** [comment]
can you point where you read that in the doc and which example you read ?

**Comment by lol-sys** [comment]
> 
> 
> can you point where you read that in the doc and which example you read ?

forget i alterady found it ty for the elp

**Comment by Nurutomo** [comment]
bot.setControlState(state, condition)

Pada tanggal Min, 19 Jul 2020 08.37, lol-sys <notifications@github.com>
menulis:
