### ISSUE TITLE
Get server hash

### ISSUE THREAD

**Issue by the-markus** [PrismarineJS/mineflayer#1164]
Hello, I'm trying to implement MCLeaks into my bot and I need to create the server hash for the MCLeaks API [(https://mcleaks.net/apidoc)](url) in order for it to join the server. Is there a way for doing that or a method for that?

**Comment by wvffle** [comment]
You can get some info on mcleaks in this issue: https://github.com/PrismarineJS/mineflayer/issues/790#issuecomment-489279008

**Comment by the-markus** [comment]
Yeah I already read that but to generate the server hash I need the server id, the public key and a shared secret from the server and I don't know how to get them

**Comment by the-markus** [comment]
Ok I got it thanks to this: [https://github.com/PrismarineJS/node-minecraft-protocol/pull/572](url)

**Comment by xdevapps** [comment]
@the-markus Can you please share what you did to get the required inputs?

**Comment by SinanAkkoyun** [comment]
> Ok I got it thanks to this: [https://github.com/PrismarineJS/node-minecraft-protocol/pull/572](url)

Hey, the link is leading to emptyness, could you please share the code?

**Comment by the-markus** [comment]
> > Ok I got it thanks to this: [https://github.com/PrismarineJS/node-minecraft-protocol/pull/572](url)
> 
> Hey, could you please share your working code?

I've updated the link, you can also find a working example here: https://github.com/the-markus/mc-bot

**Comment by SinanAkkoyun** [comment]
> > > Ok I got it thanks to this: [https://github.com/PrismarineJS/node-minecraft-protocol/pull/572](url)
> > 
> > 
> > Hey, could you please share your working code?
> 
> I've updated the link, you can also find a working example here: https://github.com/the-markus/mc-bot

Thank you so much!!!

**Comment by SinanAkkoyun** [comment]
> > > Ok I got it thanks to this: [https://github.com/PrismarineJS/node-minecraft-protocol/pull/572](url)
> > 
> > 
> > Hey, could you please share your working code?
> 
> I've updated the link, you can also find a working example here: https://github.com/the-markus/mc-bot

Hey, may I ask, where does joinTheAltening get called in your code? I don't get where you actually pass the auth and session URLs to the createBot function.

**Comment by the-markus** [comment]
> > > > Ok I got it thanks to this: [https://github.com/PrismarineJS/node-minecraft-protocol/pull/572](url)
> > > 
> > > 
> > > Hey, could you please share your working code?
> > 
> > 
> > I've updated the link, you can also find a working example here: https://github.com/the-markus/mc-bot
> 
> Hey, may I ask, where does joinTheAltening get called in your code? I don't get where you actually pass the auth and session URLs to the createBot function.

I had to make a fork of node-minecraft-protocol, so I could implement MCLeaks and TheAltening integration: https://github.com/the-markus/node-minecraft-protocol

It's a bit janky, but it essentially overrides the join and auth request according to the service chosen.
