### ISSUE TITLE
Bot.toss() Beacon?

### ISSUE THREAD

**Issue by hall-of-code** [PrismarineJS/mineflayer#1170]
## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a question
Hello,

I want to Drop a single Beacon,, the problem is, that beacon has the ID 138,, but if I do ``bot.toss(138, 0, 1)``, an error comes up, "missing sourceitem 138:0" ,, if I do ``bot.toss(138)``, then the error says "missing source item".

Can sb help me?

**Comment by ImHarvol** [comment]
Try `bot.toss(138, null, 1)` and make sure you have the beacon in the inventory

**Comment by hall-of-code** [comment]
Hm then the error "missing source item 138:null" comes up. Also I tryed NULL and false.

Or must have the Beacon in the first slot of invenotry?

**Comment by Karang** [comment]
You most likely have the wrong item id.
In 1.13.+ id 138 is not beacon https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.13.2/items.json#L831

You need to use mcdata to get the Block id by name.

**Comment by hall-of-code** [comment]
Ou thx. ... :D
