### ISSUE TITLE
Find all Players in Radius of N Blocks?

### ISSUE THREAD

**Issue by hall-of-code** [PrismarineJS/mineflayer#1173]
## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a question
Hello,
Is there any function to get all Player names in Radius of 30 Blocks for example?
Or have I parse the bot.entities manually?

Thx.

**Comment by wvffle** [comment]
Loop over `bot.players` and check for `player.entity.position.distanceTo(bot.entity.position)

**Comment by hall-of-code** [comment]
Okay thanks I'll try it tommorow
