### ISSUE TITLE
Doesn't connect under Linux / Ubuntu

### ISSUE THREAD

**Issue by hall-of-code** [PrismarineJS/mineflayer#1176]
## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a question
Hello,
I've created a Mineflayer Bot on my Windows PC, If I running it here via PowerShell - all worked.

But when I try to run it on my Ubuntu 18 VPS, with "Debug" -- then the message "pinging -server ip- +0ms" comes up, and after a while, the error "ENETWORK Timeout -server ip-",,, I've tryed to reset my IPtables Firewall (with "iptables -F",,, "iptab-els -P input / output / forwared accept ...", stopped ufw) But nothing works.

Does sb know whats the solution for my Problem? Is there a specific IP-Tables rule requered? Thx

**Comment by rom1504** [comment]
You need to have a route directing towards the network of your minecraft
server with the outgoing port open for the minecraft server

**Comment by hall-of-code** [comment]
Hm. I don't know what to do? I've rent a new VPS, but the same comes up ...

![dewwde](https://user-images.githubusercontent.com/42320700/88169097-c20c7100-cc1b-11ea-9edb-c3caa94e1f1e.PNG)

**Comment by rom1504** [comment]
Is this happening on a specific minecraft server ?

**Comment by hall-of-code** [comment]
Yes. But I can Ping the IP... 
And under Windows it works.

I've tryed to run the Script on a Ubuntu 18 LXC VPS - and on a Debian 9 KVM VPS ... but nothing works. It's Timing out. 

I'll tryed it via MC-server-IP "bausucht.net" -- also via direkt IP -- Port 25565 , 25566 ------ 

On localhost servers it works. on Hivemc it works too ... but not in Bausucht.net ,, griefergames.net ,, 

I think that the Minecraft Servers disalow connects from IP Adresses from specific Datacenter/ IP Network ... but I don't know it.

**Comment by rom1504** [comment]
Can you connect with the vanilla client to this server on your Ubuntu setup
?

**Comment by hall-of-code** [comment]
I've try to Install Graphical System on my VPS tommorow.

Than I'll try it.

**Comment by hall-of-code** [comment]
So, I can't install Minecraft on My VPS becaue my Hoster have enought graphics-card. And VPN isn't allowed on the Minecraft Server.. So I dont know. Thx

(I think the error is on my side)

**Comment by maantjemol** [comment]
I'm currently facing the same issue, it's working on my Windows machine but when i run it in docker or I run it on my ubuntu server it times out. Has there been an solution found for this issue?

**Comment by u9g** [comment]
> I'm currently facing the same issue, it's working on my Windows machine but when i run it in docker or I run it on my ubuntu server it times out. Has there been an solution found for this issue?

please make a new issue
