### ISSUE TITLE
Usage example MineflayerAutoAuth

### ISSUE THREAD

**Issue by goncharov5606** [PrismarineJS/mineflayer#1187]
You can give an example of a bot using MineflayerAutoAuth?

**Comment by shketov** [comment]
И снова привет! Исходя из предыдущего вопроса про каптчу, я думаю, что ты пытаешься подключится к ПростоКрафту

В таком случае MineflayerAutoAuth просто бесполезен, так как сперва тебе потребуется ввести каптчу на сервере, а после пароль - т.е при подключении бот сразу введет пароль, минуя каптчу, соответственно ты будешь получать предупреждение, что каптча неверная и далее можешь получить блокировку IP адреса на некоторое время.

**Comment by goncharov5606** [comment]
> И снова привет! Исходя из предыдущего вопроса про каптчу, я думаю, что ты пытаешься подключится к ПростоКрафту
> 
> В таком случае MineflayerAutoAuth просто бесполезен, так как сперва тебе потребуется ввести каптчу на сервере, а после пароль - т.е при подключении бот сразу введет пароль, минуя каптчу, соответственно ты будешь получать предупреждение, что каптча неверная и далее можешь получить блокировку IP адреса на некоторое время.

А как тогда действовать ? Просто отправить команду входа в чат после ввода капчи ?

**Comment by shketov** [comment]
> > И снова привет! Исходя из предыдущего вопроса про каптчу, я думаю, что ты пытаешься подключится к ПростоКрафту
> > В таком случае MineflayerAutoAuth просто бесполезен, так как сперва тебе потребуется ввести каптчу на сервере, а после пароль - т.е при подключении бот сразу введет пароль, минуя каптчу, соответственно ты будешь получать предупреждение, что каптча неверная и далее можешь получить блокировку IP адреса на некоторое время.
> 
> А как тогда действовать ? Просто отправить команду входа в чат после ввода капчи ?

Как вариант - да. Также можно немного автоматизировать это, если ты отлавливаешь события сообщений сервера (Сообщение сервера и пароль случайны):

```
bot.on('message', (message) => {
var msg = message.toString()
	if(msg.includes("[ProstoCraft] Вы успешно ввели каптчу, авторизуйтесь")){
		bot.chat("/login mineflayer")
	}
})
```

**Comment by goncharov5606** [comment]
> > > И снова привет! Исходя из предыдущего вопроса про каптчу, я думаю, что ты пытаешься подключится к ПростоКрафту
> > > В таком случае MineflayerAutoAuth просто бесполезен, так как сперва тебе потребуется ввести каптчу на сервере, а после пароль - т.е при подключении бот сразу введет пароль, минуя каптчу, соответственно ты будешь получать предупреждение, что каптча неверная и далее можешь получить блокировку IP адреса на некоторое время.
> > 
> > 
> > А как тогда действовать ? Просто отправить команду входа в чат после ввода капчи ?
> 
> Как вариант - да. Также можно немного автоматизировать это, если ты отлавливаешь события сообщений сервера (Сообщение сервера и пароль случайны):
> 
> ```
> bot.on('message', (message) => {
> let msg = message.toString()
>         // Это происходит после успешного ввода каптчи
> 	if(msg.includes("[ProstoCraft] Вы успешно ввели каптчу, авторизуйтесь")){
> 		bot.chat("/login mineflayer")
> 	}
> })
> ```

Спасибо
