### ISSUE TITLE
TypeError: Cannot read property 'entity' of null

### ISSUE THREAD

**Issue by 0vertime-dev** [PrismarineJS/mineflayer#1193]
[ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

/Users/overtime/Desktop/WalterBotMC2.0/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'entity' of null

## Versions
 - mineflayer: 6.14.6
 - server: vanilla/spigot/paper 1.12.2
 - node: v12.18.3

## Detailed description of a problem
A clear and concise description of what the problem is.

I am trying to make a Minecraft bot for an anarchy server but every time I boot it up after anywhere from 10 seconds to 5 minutes I get the error

## Current code
```js
  if (!stop) {
      while (this.buffer.length >= offset + size + value) {
        try {
          this.push(this.buffer.slice(offset + size, offset + size + value))
          offset += size + value;
          ({ value, size } = readVarInt(this.buffer, offset))
        } catch (e) {
          if (e.partialReadError) {
            break
          }
        }
      }
    }
```

## Expected behavior
I don't know as this is from a npm plugin, I just know its not supposed to do that

**Comment by wvffle** [comment]
- The `Current Code` section refers to YOUR code, not code of another library. 
- You left the description blank. At least tell us what you're trying to do with the bot.

Please, update your issue with required info.

**Comment by 0vertime-dev** [comment]
Ok, the only problem is I don’t know what in my code cause that, it just randomly happens

**Comment by wvffle** [comment]
also, without full error stack it's harder for us to locate the potential bug

**Comment by Karang** [comment]
@0vertime-dev You need to provide the full error stack and a minimal example (of your code) to reproduce the issue.
