### ISSUE TITLE
Please help using bot.clickWindow(slot, mouseButton, mode, cb)

### ISSUE THREAD

**Issue by flymer5** [PrismarineJS/mineflayer#1195]
what values ​​should be used in this request?  bot.clickWindow(slot, mouseButton, mode, cb)

**Comment by wvffle** [comment]
Just take a look at the docs...

1. https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botclickwindowslot-mousebutton-mode-cb
2. https://wiki.vg/Protocol#Click_Window

**Comment by goncharov5606** [comment]
what is cb?

**Comment by wvffle** [comment]
Docs are your friend: https://github.com/PrismarineJS/mineflayer/blob/master/docs/tutorial.md#callbacks
