### ISSUE TITLE
an error occurs when using, what should I do?

### ISSUE THREAD

**Issue by goncharov5606** [PrismarineJS/mineflayer#1207]
- [x ] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x ] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x ] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: #.#.#
 - server: spigot
 - node: #.#.#

## Detailed description of a question

`const position = new Vec3(-19,5,10);`
`const block = bot.blockAt(position);`

`bot.dig(block)`

![89268229-0d7e4080-d65a-11ea-88db-404aea71b8e4](https://user-images.githubusercontent.com/58649986/89280552-97cea080-d66a-11ea-86cd-faf0f3153718.jpg)

an error occurs when using, what should I do?

**Comment by rom1504** [comment]
const Vec3 = require('vec3').Vec3
Next time, do a quick search in the repo
