### ISSUE TITLE
help me with my bot

### ISSUE THREAD

**Issue by hammarez** [PrismarineJS/mineflayer#1215]
Hello, I have a bot almost ready, I can't figure out how to find out the coordinates of the block that the bot itself looks at? Please help me)

**Comment by wvffle** [comment]
You're not sticking to the template. You haven't read the API, nor the examples.

**Comment by hammarez** [comment]
> You're not sticking to the template. You haven't read the API, nor the examples.
> 
> Please, stick to the template and read the API **AND** examples before posting the question.
> 
> Here's your answer: https://github.com/PrismarineJS/mineflayer/blob/master/examples/raycast.js



Sorry I just don't know English well, I have another question what to do if the bot kicks from the server in 1 minute, or maybe it turns off itself, what to do if the script stops?

**Comment by wvffle** [comment]
> I have another question

That means you should look through the issues, FAQ, and if you won't find any info then create a new issue with your problem filling all of the required info.

Judging from the context, I suppose your issue is solved now.
