### ISSUE TITLE
kick bot on hub server

### ISSUE THREAD

**Issue by hammarez** [PrismarineJS/mineflayer#1220]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 1.12.2
 - server: vanilla/spigot/paper    spigot
 - node: 12.16.1

## Detailed description of a question

Hello everyone, faced with such a problem bot for no reason kicking from the server ip:mc.prostocraft.ru, if I use this code to detect the cause and the cause is not detected bot.on('kicked', (reason) => { console. log ("[Minecraft] Bot kicked " + reason ); });

**Comment by wvffle** [comment]
Are you logging all of the messages, the server sends to you? You haven't event told us if the server has any plugin that requires user authentication, which may be the cause of the bot getting kicked. If you do have a part of code that makes the bot log into these type of plugins, then show it to us. There is not enough context to get started with your problem.

**Comment by hammarez** [comment]
> Are you logging all of the messages, the server sends to you? You haven't event told us if the server has any plugin that requires user authentication, which may be the cause of the bot getting kicked. If you do have a part of code that makes the bot log into these type of plugins, then show it to us. There is not enough context to get started with your problem.

yes, I register all messages from the server, sending my messages go through the VK bot to the server itself. After logging in to your account the bot is disabled for no reason in the server hub

**Comment by hammarez** [comment]
> Вы регистрируете все сообщения, которые сервер отправляет вам? Вы еще не сказали нам, есть ли на сервере какой-либо плагин, требующий аутентификации пользователя, что может быть причиной пинка бота. Если у вас есть часть кода, которая заставляет бота входить в эти плагины, то покажите ее нам. Нет достаточного контекста, чтобы начать работу с вашей проблемой.

Sorry, can you help me with my problem?
