### ISSUE TITLE
special chat

### ISSUE THREAD

**Issue by flymer5** [PrismarineJS/mineflayer#1223]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper 1.12.2
 - node: 12.18.3

## Detailed description of a question

How to make an output of a chat like in the screenshot?

![image](https://user-images.githubusercontent.com/58649986/89725521-3031a000-da32-11ea-9ba2-3071122a38f4.png)

**Comment by rom1504** [comment]
Which example mentioning chat in its file name did you try?

**Comment by flymer5** [comment]
I'm sorry, but I don't understand you. This is how I get the chat 
`bot.on('chat', function (username, message) {
console.log(username, message)`

**Comment by ARandomAssGuy** [comment]
> I'm sorry, but I don't understand you. This is how I get the chat
> `bot.on('chat', function (username, message) { console.log(username, message) })`

So i am assuming that some of these chat messages don't get logged in the console?
or do you have another issue?

**Comment by flymer5** [comment]
yes, that's right, some of the messages from the chat do not go to the console.

**Comment by rom1504** [comment]
I encourage you to through the list of example and ctrl+f chat, there is
one that does exactly what you want

**Comment by ARandomAssGuy** [comment]
> yes, that's right, some of the messages from the chat do not go to the console.
alright then, use
```
bot.on('message', function (jsonMessage) {console.log(jsonMessage)})
```
this will give you the raw json message, after which you can make your own parsing for it, or use [mine here](https://github.com/ARandomAssGuy/mineflayerstuff/blob/master/simplechatparser.js)

**Comment by Nurutomo** [comment]
To display colored chat `bot.on('message', json => console.log(json.toAnsi()))`

**Comment by flymer5** [comment]
thank!
