### ISSUE TITLE
Bot does not change the item in hand

### ISSUE THREAD

**Issue by flymer5** [PrismarineJS/mineflayer#1224]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper 1.12.2
 - node: 12.18.3

## Detailed description of a question

When using `bot.setQuickBarSlot(8)`, the bot does not change the item in hand, what should I do?

**Comment by ranguli** [comment]
I don't think anyone will be able to help without more information and some code.

You could also use `bot.equip()` (documented [here](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botequipitem-destination-callback)) to accomplish this depending on your objective. You can see this live in code examples like [this one](https://github.com/PrismarineJS/mineflayer/blob/d1d644554c3b22749e88046668d87b4c3e710e59/examples/auto_totem.js)
