### ISSUE TITLE
How to get Username of nearest player 

### ISSUE THREAD

**Issue by Hobb0Y** [PrismarineJS/mineflayer#1242]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a question
How can I get the Username of the player which is next to the bot?

**Comment by wvffle** [comment]
As fast as #1243 will get merged, you could do
```js
const { username } = bot.nearestEntity(({ type }) => type === 'player')
```

**Comment by Hobb0Y** [comment]
Thank you
