### ISSUE TITLE
Held item

### ISSUE THREAD

**Issue by TheAirBlow** [PrismarineJS/mineflayer#1246]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.0
 - server: Paper 1.12.2
 - node: 14.7.0

## Detailed description of a question
How can I get item, that bot is holding right now? Or how can I check, is bot holding something or not?
(API haven't any of these)

**Comment by rom1504** [comment]
Try to ctrl+f hold in the API

**Comment by TheAirBlow** [comment]
Already

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botupdatehelditem

bot.heldItem
