### ISSUE TITLE
Connect bot to SOCKS4

### ISSUE THREAD

**Issue by invok1svgg** [PrismarineJS/mineflayer#1248]
Hi guys, I need help, I need to connect bots through a proxy, I tried this script https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js#L13 everything works, but I need not SOCKS5, I need SOCKS4. I tried to change type 5 to type 4. Error:
TypeError: Cannot read property 'socket' of undefined

**Comment by rom1504** [comment]
If you still have this problem, please specify your current code and re-open
