### ISSUE TITLE
help with chat on/off

### ISSUE THREAD

**Issue by hammarez** [PrismarineJS/mineflayer#1260]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 1.12.2
 - server: vanilla/spigot/paper.   spigot
 - node: 12.16. 1

## Detailed description of a question

I made a bot to output the server chat, how to do it so that using the command "Chat off" you can disable sending messages from the server, because they go constantly

**Comment by rom1504** [comment]
use a if

**Comment by TheAirBlow** [comment]
Here we go

```js
// Init variables
chat = true

// Chat event
bot.on('event', (username, message) => {
    if (!chat) {
        if (message === "chat on") {
            chat = true;
            bot.chat("Chat has been enabled")
        }
    } else {
        if (message === "chat off") {
            chat = false;
            bot.chat("Chat has been disabled")
        }
        // The rest of your code
    }
}
```

**Comment by hammarez** [comment]
> ```js
> // Init variables
> chat = true
> 
> // Chat event
> bot.on('event', (username, message) = > > {
>     if (!chat) {
>         if (message = = = "chat on") {
>             chat = true;
>             bot.chat("Chat has been enabled")
>         }
>     } else {
>         if (message = = = "chat off") {
>             chat = false;
>             bot.chat("Chat has been disabled")
>         }
>         // The rest of your code
>     }
> }
> ```

![Screenshot_1](https://user-images.githubusercontent.com/67218956/90598337-e56b1180-e203-11ea-99ae-793862587969.png)

**Comment by rom1504** [comment]
you cannot add spaces randomly in the code, spaces have meaning
for example you cannot replace `=>` by `= >`

**Comment by hammarez** [comment]
> you cannot add spaces randomly in the code, spaces have meaning
> for example you cannot replace `=>` by `= >`

![Screenshot_2](https://user-images.githubusercontent.com/67218956/90626123-933de680-e22b-11ea-8351-24ca3e5f4dce.png)

**Comment by Karang** [comment]
You were given the code without these errors... Can't you just copy paste ? Also, this is not an issue related to mineflayer, you need to learn how to read error messages and how to use javascript.

**Comment by np6hd** [comment]
LMAO
