### ISSUE TITLE
Help with picking up water

### ISSUE THREAD

**Issue by 7n7o** [PrismarineJS/mineflayer#1262]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.24.0
 - server: vanilla 1.12.2
 - node: 12.18.3

## Detailed description of a question

I've been creating a bot to automatically create lava casts and after placing the water I cant figure out a way to pick it back up, i tried using activate item a second time and it does nothing, i tried doing activateItem() deactivateItem() activateItem() deactivateItem() to place then pick up and nothing works, anybody know how this can be done?

**Comment by Karang** [comment]
You can try https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botactivateblockblock-callback with the empty bucket in hand.

**Comment by 7n7o** [comment]
> You can try https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botactivateblockblock-callback with the empty bucket in hand.


I just tried this it didn't work, the bot just kinda hits the water

**Comment by 7n7o** [comment]
im really stupid i just needed some delay activate item works perfectly
