### ISSUE TITLE
The function bot.blockInSight(5,5/16) returns the value of the first block from the bot's view, even if it is not there

### ISSUE THREAD

**Issue by flymer5** [PrismarineJS/mineflayer#1269]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: spigot 1.12.2
 - node: 12.18.3

## Detailed description of a question

what to do if, when using bot.blockInSight(5,5/16), after the block disappears, this function returns the same value.
what to do ? Maybe I am doing something wrong?

**Comment by rom1504** [comment]
If you still have this problem, please specify your current code and re-open
