### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by alx-alexpark** [PrismarineJS/mineflayer#1271]
- [`x`] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [`x`] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [`x`] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: vanilla/spigot/paper 1.16.1
 - node: 12.16.1

## Detailed description of a question

My Minecraft bot gets the invalid credentials error even though the credentials are correct, and I can log into the Minecraft website using the credentials. Could Minecraft be blocking the ip adress? Or is this a bug?

**Comment by TheEpicProgrammer** [comment]
Thanks
