### ISSUE TITLE
ChatMessage parsed with unsupported color

### ISSUE THREAD

**Issue by Zailer43** [PrismarineJS/mineflayer#1273]
- [] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.28.1
 - server: vanilla 1.16.1
 - node: 14.7.0

## Detailed description of a problem
When you send a message with some RGB color in the cmd appears as an error, and it can be annoying if it is a prefix or a nick custom

## Your current code
```js

var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "localhost",
  port: 64470,
  username: "FraZaMaMe",
  version: false
bot.on('chat', function(username, message) {
  if (username === bot.username) return;
  bot.chat(message);
});
bot.on('error', err => console.log(err))
```
```
/tellraw @a {"text":"test","color":"#00ff00"}
```

## Expected behavior
It should not show error in the cmd

## Additional context
![image](https://user-images.githubusercontent.com/63565983/90997759-c7e9cf00-e598-11ea-8a34-04a5e7556799.png)
![image](https://user-images.githubusercontent.com/63565983/90997776-d0daa080-e598-11ea-86a4-26d4dd61b99f.png)

**Comment by wvffle** [comment]
It's already tracked in https://github.com/PrismarineJS/prismarine-chat/issues/6
