### ISSUE TITLE
Add event for 'actionbar' packet

### ISSUE THREAD

**Issue by Nurutomo** [PrismarineJS/mineflayer#1274]
## Is your feature request related to a problem? Please describe.
`message` event emitted when actionbar is appear.
```js
// Currently
bot.on('message', (data) => {
  console.log(data.toAnsi())
})
```

## Describe the solution you'd like
Create a new event or just add an argument to the `message` event
```js
// Solution1
bot.on('message', (data, isChat) {
  if (isChat) console.log(data.toAnsi()) // Log if it is chat (not action bar)
})

// Solution 2
bot.on('actionbar', (data) => {
  console.log(data.toAnsi())
})
```

## Additional context
I'm currently creating project `minecraft-chat` in terminal (You can also display your inventory with ASCII Art)
https://repl.it/@NurutomosSecond/MC-Chat

**Comment by wvffle** [comment]
It already exists: https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#actionbar-jsonmsg

**Comment by wvffle** [comment]
Unfortunately we have #859, we could add aliases to the events to make the names more predictable. I guess that in such case as this, the alias is a good option but it should have it's own issue or be tracked in #859.
