### ISSUE TITLE
I need help with the code

### ISSUE THREAD

**Issue by Tragafantas** [PrismarineJS/mineflayer#1280]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: latest
 - server: vanilla/spigot/paper: paper 1.16.1
 - node: latest

This might sound a dumb question, but i need help, when I run the code with "node x.js" it says "x" is not a function. What should I do?

**Comment by wvffle** [comment]
Show us your code

**Comment by Tragafantas** [comment]
Sorry my fault, problem fixed
