### ISSUE TITLE
How to disable physics for a bot?

### ISSUE THREAD

**Issue by invok1svgg** [PrismarineJS/mineflayer#1281]
How to disable physics for a bot?
I need to turn off the physics of the bot so that it just stands and does not move.

Eg: Disable fall, disable repulsion

**Comment by rom1504** [comment]
You want the bot to fly in survival mode ?
It's going to get kicked

**Comment by invok1svgg** [comment]
No, I want added to bot antiknockback

**Comment by Karang** [comment]
knockback velocity is applied here https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/entities.js#L254
feel free to experiment with disabling it and pr an option for anti-knockback

**Comment by invok1svgg** [comment]
thank you all, I got it
