### ISSUE TITLE
help with windows

### ISSUE THREAD

**Issue by laskgay** [PrismarineJS/mineflayer#1284]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 1.12.2
 - server: vanilla/spigot/paper     spigot
 - node: 12.16.1

## Clear question
A clear question, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code

Please put here any custom code you tried yet.

```js

/*
Some code here, replace this
*/

```

## Additional context

How can I find out the list and description of items in the window when I try to output, undefined

**Comment by rom1504** [comment]
Please fill the template
