### ISSUE TITLE
help with windows v2.0

### ISSUE THREAD

**Issue by laskgay** [PrismarineJS/mineflayer#1285]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: spigot
 - node: 12.16.1

## Clear question
How can I find out the list and description of items in the window when I try to output, undefined

## What did you try yet?
window() 

## Your current code
code:
bot.on('WindowOpen', function (window) {
console.log(window.slots.slot)
} 

function:
 window.slots
 [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

Please put here any custom code you tried yet.

```js

/*
Some code here, replace this
*/

```

**Comment by IdanHo** [comment]
window.slots is an array, not an object, so to access the first element you would do:
```js
window.slots[0]
```
For example. I suggest you read the documentation, and maybe a js tutorial if you're not familiar with arrays.
