### ISSUE TITLE
lookAt not working when on slab

### ISSUE THREAD

**Issue by L3g7** [PrismarineJS/mineflayer#1286]
lookAt doesn't work when the bot is standing on a slab.
The callback triggers, but the bot doesn't change its head rotation.
Same code works when the bot is standing on a "solid" block.

Mineflayer version: idk, latest i guess
Minecraft version: 1.8.9
Serverversion: Bungeecord / Spigot 1.8.8

**Comment by Karang** [comment]
What block is it trying to look at ?

**Comment by L3g7** [comment]
(Trapped) chests

**Comment by Karang** [comment]
We don't care about the type, lookAt is coordinate based, what are the block coordinates relative to the bot ?
Can you try to add some console.log() in https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/physics.js#L222
Like:
```js
  bot.lookAt = (point, force, cb) => {
    console.log('point', point)
    console.log('bot', bot.entity.position.offset(0, bot.entity.height, 0))
    const delta = point.minus(bot.entity.position.offset(0, bot.entity.height, 0))
    console.log('delta', delta)
    const yaw = Math.atan2(-delta.x, -delta.z)
    console.log('yaw', yaw)
    const groundDistance = Math.sqrt(delta.x * delta.x + delta.z * delta.z)
    console.log('groundDistance', groundDistance)
    const pitch = Math.atan2(delta.y, groundDistance)
    console.log('pitch', pitch)
    bot.look(yaw, pitch, force, cb)
  }
```

**Comment by L3g7** [comment]
Hey, sry, i misunderstood it.
The block is at about ~2 ~.5 ~ 
Log is coming soon, bot is currently crashing, will edit this when i have it.

**Comment by L3g7** [comment]
nvm can't reproduce it anymore, idk what happened
