### ISSUE TITLE
How to catch a window closing?

### ISSUE THREAD

**Issue by Denaryplanet** [PrismarineJS/mineflayer#1288]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: spigot 1.12.2
 - node: 12.18.3

## Clear question
I tried to catch the window closing, but I couldn't do it. Can you show me an example?

## What did you try yet?
I tried to use

bot.on('windowClose', (window) 
But I got nothing
## Your current code

```js

bot.on('windowClose', (window) => {
console.log("Window closed")
})

```

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/9b14ae7509c8eb1c48448c5b60bba1e99b5ef3e3/lib/plugins/inventory.js#L334

What kind of window is closing?

**Comment by flymer5** [comment]
> https://github.com/PrismarineJS/mineflayer/blob/9b14ae7509c8eb1c48448c5b60bba1e99b5ef3e3/lib/plugins/inventory.js#L334
> 
> What kind of window is closing?

server menu window

**Comment by Karang** [comment]
You can listen directly to the "close_window" packet as in https://github.com/PrismarineJS/mineflayer/blob/9b14ae7509c8eb1c48448c5b60bba1e99b5ef3e3/lib/plugins/inventory.js#L641

If you don't receive it, that means the server doesn't send a packet on window close (and the closing must happen client-side)
