### ISSUE TITLE
PartialReadError: Deserialization error for play.toClient : Read error for undefined : Missing characters in string, found size is 40761 expected size was 3325017

### ISSUE THREAD

**Issue by flymer5** [PrismarineJS/mineflayer#1289]
If you go through the server menu to the mode from 1.14.4, then this error appears. But when entering the hub, there is no such error.
![Screenshot_20200905_075503](https://user-images.githubusercontent.com/58649986/92294395-99cb9e00-ef4d-11ea-8b45-10e5d3275db0.jpg)
But with 1.12.2 everything is fine

**Comment by wvffle** [comment]
Stick to the issue template. Paste the error to the code block.

**Comment by flymer5** [comment]
> Придерживайтесь шаблона проблемы. Вставьте ошибку в блок кода.
 Хорошо , сейчас закрою вопрос

**Comment by flymer5** [comment]
> Stick to the issue template. Paste the error to the code block.

Хорошо , сейчас закрою вопрос

**Comment by Denaryplanet** [comment]
> Придерживайтесь шаблона проблемы. Вставьте ошибку в блок кода.

Or maybe this error is due to an empty message?
