### ISSUE TITLE
How do I drop an item from a specific slot?

### ISSUE THREAD

**Issue by flymer5** [PrismarineJS/mineflayer#1292]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: spigot 1.12.2
 - node: 12.18.3

## Clear question
What method can be used to drop an item from a specific slot? 
## What did you try yet?
I used the method bot.clickWindow(3, 0, 4) but it was giving an error 

## Your current code

Please put here any custom code you tried yet.

```js

if (message == 'drop') {
bot.clickWindow(3, 0 ,4)

```

**Comment by Karang** [comment]
Why do you want it to be in a specific slot ? You have the toss method that drop an item based on its id:
https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#bottossitemtype-metadata-count-callback

**Comment by flymer5** [comment]
> Why do you want it to be in a specific slot ? You have the toss method that drop an item based on its id:
> https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#bottossitemtype-metadata-count-callback

It's just that in this case it's more convenient for me on the slot. I just can't find out the ID, because the VKontakte bot won't be able to display it

**Comment by Karang** [comment]
I don't know what a VKontakte bot is, so I'm not able to help you with that. For tossing a specific slot, look at how toss() is implemented in mineflayer.
