### ISSUE TITLE
Is there a method to determine if an account is running?

### ISSUE THREAD

**Issue by flymer5** [PrismarineJS/mineflayer#1293]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: spigot 1.12.2
 - node: 12.18.3

## Clear question
How can I find out if an account is running? I didn't find anything about it in api

## What did you try yet?
-
## Your current code

Please put here any custom code you tried yet.

```js

/*
-
*/

```

**Comment by rom1504** [comment]
I don't think that's possible

**Comment by flymer5** [comment]
> I don't think that's possible
and something like that?

**Comment by rom1504** [comment]
What do you mean ?

**Comment by flymer5** [comment]
> What do you mean ?

some ways to find out if the bot is online

**Comment by rom1504** [comment]
If you are the one starting the bot then you know
If not and you know which server the bot may be connected to you can connect to the server with an other accounts and check bot.players
If you don't know which server, I believe there is no way (except checking all the servers)

**Comment by HelpLessNitro** [comment]
console.log('Bot is online!')

thats all it

**Comment by flymer5** [comment]
> console.log('Bot is online!')
> 
> thats all it

i need a condition
