### ISSUE TITLE
Need help with repl.js

### ISSUE THREAD

**Issue by Tragafantas** [PrismarineJS/mineflayer#1296]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: vanilla/spigot/paper 1.16.1
 - node: 12.18.3

## Clear question
I'm making a bot that prints in chat the text that I put in the console, but when I use repl.js, it prints in the console ">", and when I type something and hit enter, the terminal says "[text] is not defined". What should I do to solve this? Does anyone know and example?

## Your current code

I didn't change the code

```js

const mineflayer = require('mineflayer')
const repl = require('repl')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node repl.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'repl',
  password: process.argv[5]
})

bot.on('login', () => {
  const r = repl.start('> ')
  r.context.bot = bot
  
  r.on('exit', () => {
    bot.end()
  })
})

```

**Comment by Karang** [comment]
Repl input is javascript try to type:
> bot.chat("hello")

**Comment by Tragafantas** [comment]
It works now, thank you very much :)
