### ISSUE TITLE
How to make a bot till dirt to make farmland

### ISSUE THREAD

**Issue by Vaylle** [PrismarineJS/mineflayer#1298]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: vanilla server / open to lan (I use 1.12.2)
 - node: v12.18.3

## Clear question

I am trying to make my bot to till dirt to make farmland

## What did you try yet?

I am mainly trying to use "bot.activateItem(offHand=false)" to use a hoe and till the dirt

Someone suggested in gitter to use "bot.useOn(targetEntity)" but a block isn't an entity 

I've looked in different repos and farmer.js but I can't find any example

I don't get any error from doing so, the bot just does nothing apparently

## Your current code

```js

    let pos1 = new Vec3(100, 64, 100);

    minecraftBot.lookAt(pos1); // I have tried with lookAt but also with manually looking at the block then starting the bot

    minecraftBot.setQuickBarSlot(0); // I manually placed the hoe in the bot hand
    minecraftBot.activateItem(true); // I also have tried false
    minecraftBot.deactivateItem(); // I tried with and without this

```

## Additional context

no additional context

**Comment by vektrix1** [comment]
There is an example for this afaik, farmer.js

**Comment by vektrix1** [comment]
nvm

**Comment by sefirosweb** [comment]
you said in farmer.js have one example but i dont see it

I see how to place plant into farmland, but no how use a hoe on dirt

**Comment by a-nanasov** [comment]
@sefirosweb have you found a solution? I've spent today's evening on that, but without any luck...
Looked through examples and voyager skills - found nothing. Even asked chat gpt for help: it thinks mineflayer has tillBlock function, which apparently it doesn't, and generates only non working code :(
Look like this is something related: https://github.com/maximmasiutin/Minecraft-Bot/blob/main/minecraft-bot.js#L861 but it uses non stable internal api, guess it's better to avoid such approach

**Comment by TheFeather293** [comment]
I think instead of activateitem u could use activateblock

**Comment by sefirosweb** [comment]
@a-nanasov sorry for delay yep is interact
```ts
    this.bot.activateBlock(block)
      .then(() => {
        this.isEndFinished = true
      })
      .catch(err => {
        console.log(err)
      })
```
