### ISSUE TITLE
Block definition problem for digging

### ISSUE THREAD

**Issue by Denaryplanet** [PrismarineJS/mineflayer#1302]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: vanilla/spigot/paper 1.12.2
 - node: 12.18.3

## Clear question
When trying to dig at the look, the bot gives out 3 blocks as undefined. There is cobblestone there, though. How can this problem be corrected?

When digging by coordinates everything is fine
## What did you try yet?

bot.blockInSight()
bot.dig()
bot.targetDigBlock

## Your current code

```js

function dig() {
	var block = bot.blockInSight(5, 5/16)
	if(bot.targetDigBlock){
		dig()
	}else{
		if (block == undefined) {
			console.log(block)
			dig()
		}else{
			console.log(block)
			bot.dig(block, onDiggingCompleted)
		}
	}
	function onDiggingCompleted (err) {
		if (err) {
			console.log(err.stack)
			return
		}
		dig()
	}
}

```

## Additional context
P.s cobblestone generator 5 blocks up

**Comment by flymer5** [comment]
everything worked out for me, but I ran into this error. How can you solve it?
![image](https://user-images.githubusercontent.com/58649986/92715373-37c0cd80-f37f-11ea-8144-a2e65bcb00d5.png)

**Comment by wvffle** [comment]
You're calling the dig function recursively, in case of `bot.targetDigBlock` or `block == undefined` you'll most likely loop yourself

**Comment by flymer5** [comment]
> You're calling the dig function recursively, in case of `bot.targetDigBlock` or `block == undefined` you'll most likely loop yourself

I already found this and fixed it, but here is a new problem:
![image](https://user-images.githubusercontent.com/58649986/92734696-96477500-f39a-11ea-9571-9998390f18ca.png)

**Comment by wvffle** [comment]
No, you havent. This is obviously the case. If you have 'fixed' it then show us your code again.

**Comment by flymer5** [comment]
> No, you havent. This is obviously the case. If you have 'fixed' it then show us your code again.
```js
function dig() {
	if (bot.blockInSight(55, 5/16) !== undefined) {
		var blockD = bot.blockAt(bot.blockInSight(55, 5/16).position)
		if (blockD !== undefined) {
			bot.dig(blockD,onDiggingCompleted)
		}else{
			dig()
		}
	}else{
		dig()
	}
	function onDiggingCompleted (err) {
		if (err) {
			console.log(err.stack)
			return
			dig()
		}else{
			dig()
		}
	}
}
```

**Comment by flymer5** [comment]
> If ther is no block in sight or `onDiggingCompleted` will error, then you'll loop

Well so this is digging for a 5 block generator

**Comment by Karang** [comment]
You can't just call the same function over and over again, you will fill your stack and cause that error. https://www.freecodecamp.org/news/understanding-the-javascript-call-stack-861e41ae61d4/

You need to use one of the following solution:
* `setInterval(function, period)` : call the function every period https://www.w3schools.com/jsref/met_win_setinterval.asp
* `setTimeout(function, delay)` : call the function after a delay https://www.w3schools.com/jsref/met_win_settimeout.asp
* `.on('blockUpdate', function)` : call the function when the block is mined or generated https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#blockupdate-oldblock-newblock

**Comment by flymer5** [comment]
> You can't just call the same function over and over again, you will fill your stack and cause that error. https://www.freecodecamp.org/news/understanding-the-javascript-call-stack-861e41ae61d4/ (this is js 101, I suggest you look it up a bit)
> 
> You need to use one of the following solution:
> 
> * `setInterval(function, period)` : call the function every period https://www.w3schools.com/jsref/met_win_setinterval.asp
> * `setTimeout(function, delay)` : call the function after a delay https://www.w3schools.com/jsref/met_win_settimeout.asp
> * `.on('blockUpdate', function)` : call the function when the block is mined or generated https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#blockupdate-oldblock-newblock

can you give a concrete example? And then how much I dig and I can't do it normally

**Comment by Karang** [comment]
Since from your code in https://github.com/PrismarineJS/mineflayer/issues/1318 you seems to have found the solution, I consider this solved.

It would be nice that:
* you don't open a gazillion issues for the same problem
* you close your own issues when they are solved
