### ISSUE TITLE
how many bots can log in at the same time?

### ISSUE THREAD

**Issue by gettyt** [PrismarineJS/mineflayer#1304]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [ ] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: vanilla/spigot/paper localhost
 - node: 16.6.0
## Clear question
A clear question, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code

Please put here any custom code you tried yet.

```js

/*

*/

```

## Additional context
how many bots can go to 1 server? I have 7 bots, no more, is that how it should be?

**Comment by gettyt** [comment]
> * [x]  I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
> * [ ]  I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
> * [x]  I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.
> 
> ## Versions
> * mineflayer: 2.28.1
> * server: vanilla/spigot/paper localhost
> * node: 16.6.0
> 
> ## Clear question
> A clear question, with as much context as possible.
> What are you building? What problem are you trying to solve?
> 
> ## What did you try yet?
> Did you try any method from the API?
> Did you try any example? Any error from those?
> 
> ## Your current code
> Please put here any custom code you tried yet.
> 
> ```js
> /*
> 
> */
> ```
> 
> ## Additional context
> how many bots can go to 1 server? I have 7 bots, no more, is that how it should be?

**Comment by MrMoraschi** [comment]
It is closed, but if the program is hosted on your machine, the components determine the instances that can be run, for example, when I want 5 bots that cam follow me, that takes a lot of time to load when I execute it
