### ISSUE TITLE
how many bots can go to 1 server?

### ISSUE THREAD

**Issue by gettyt** [PrismarineJS/mineflayer#1305]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: vanilla/spigot/paper localhost
 - node: 14.6.0

## Clear question
how many bots can go to 1 server? I have 7 bots, no more, is that how it should be?

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code

Please put here any custom code you tried yet.

```js

/*
Some code here, replace this
*/

```

**Comment by MrMoraschi** [comment]
If the program is hosted on your machine, the components of the machine determine the instances that can be run, for example, when I want to log 5 bots on my localhost, that can follow me, it takes a lot of time to load when I execute it.

**Comment by Vaylle** [comment]
There is no "hard" limit on how many bot can log on a server. Keep in mind that other limits are put in place :

- Mojang Auth Servers will only accept so many request per minute
- The server have a limit on max player
- The server may also have a limit on max player per IP
- Your computing power
