### ISSUE TITLE
findblock no detect block "update" in world 

### ISSUE THREAD

**Issue by sefirosweb** [PrismarineJS/mineflayer#1314]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - server: vanilla/spigot & local server
- mineflayer version: 2.28.1
- minecraft version 1.6.2

## Detailed description of a problem
The findblock and findblocks function does not detect new changes,
If you use find bed, they found it but it is in loop and you destroy the bed (or block), they still "find them"
The reverse is the same

## What did you try yet?
They must find the "current" state blocks right?

## Your current code
Example:
```js
let bed = null;
const ids = 75; //id  white_bed

bot.on('time', () => {
    let itemsFound  = bot.findBlock({ matching: ids, maxDistance: 50 })
  
    if(JSON.stringify(bed) !== JSON.stringify(itemsFound)){
        console.log(itemsFound);
        bed = itemsFound
        bot.chat('Bed found!')
    }
    
})
```

**Comment by wvffle** [comment]
Give us the mineflayer version  and the minecraft version.

btw, comparing output of `JSON.stringify` is a bad way to compare objects.

**Comment by sefirosweb** [comment]
Addin extra info:

Looking the code i see findblock use inside the function **bot.blockAt** and seems this fuction have an a bug:

This issue is related with bug: https://github.com/PrismarineJS/mineflayer/issues/591

**Comment by Karang** [comment]
I guess you meant minecraft version 1.16.2 ? This version is not supported yet.

**Comment by sefirosweb** [comment]
For a now seems working well (avoiding this bug)

Sorry my fault, I dont checked differents block,

Seems only this bug occurs when bed block, white, red... or isAbed() function 

I tried a other blocks and seems works fine (obsidian, diamond...)

I think the cause the bed use 2 blocks instead 1,

This is a little bad for me, if i want to move the bed, the bot can't detect it

**Comment by Karang** [comment]
* Try it with a supported version (1.8.9 - 1.16.1)
* Post the latest code you try
* Post a screenshot of the bot near the bed and the output of a console.log() of the results of findBlocks()
