### ISSUE TITLE
bot says bed block isn't a bed block

### ISSUE THREAD

**Issue by ArcadeZtheWolf** [PrismarineJS/mineflayer#1315]
- [X ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.28.1
 - server: vanilla 1.16.2
 - node: 12.18.3

## Detailed description of a problem
i'm trying to have my bots go to sleep when it's night to avoid phantoms spawning, but whenever i try to get them to sleep with the bot.sleep method, it gives me an error saying "wrong block : not a bed block."

## What did you try yet?
i've tried getting a handle to the block by using the findBlock function, and that always returns null when searching for beds, so i instead tried constructing a block with the coordinates of both the head and the foot of the bed (on separate attempts)which also found no luck.

## Your current code
```js
const mineflayer = require('mineflayer')
const pathfinder = require('mineflayer-pathfinder').pathfinder
const Movements = require('mineflayer-pathfinder').Movements
const { GoalNear } = require('mineflayer-pathfinder').goals
const armorManager = require('mineflayer-armor-manager')
const Block=require("prismarine-block")("1.8");



let positionBeforeBed

//there would normally be a list of accounts stored in the array emails, and the array passwords, but seeing as that's private information i'm not going to post that here


const bot = mineflayer.createBot({ //this would also include a server and port, but i don't want random people connecting to my private server
  username: emails[parseInt(process.argv[2])],
  password: passwords[parseInt(process.argv[2])]
})


bot.loadPlugin(pathfinder)
bot.loadPlugin(armorManager);

bot.once('spawn', () => {

  const mcData = require('minecraft-data')(bot.version)

  const defaultMove = new Movements(bot, mcData)
  
  
  bot.on('wake', () => {
	  if (positionBeforeBed != null)
		  pathfindTo(positionBeforeBed)
  })
  
 
  bot.on('time', () => {
	  if (bot.time.timeOfDay >= 12000 && bot.time.timeOfDay <= 23000 && !bot.isSleeping){
		  positionBeforeBed = bot.entity.position
		  bot.pathfinder.setMovements(defaultMove)
		  bot.pathfinder.setGoal(new GoalNear(482, 78, 1160, 1))
			bot.sleep(new Block(480,78,1163))
	  }
  })
  
  function eatsomedarnFood(){
	  if (bot.food < 20 && bot.inventory.count(740) > 0){
		bot.equip(bot.inventory.findInventoryItem(740),"hand")
		bot.consume(eatsomedarnFood)
	  } else {
		  return;
	  }
  }
  
  function pathfindTo(position){
      bot.pathfinder.setMovements(defaultMove)
      bot.pathfinder.setGoal(new GoalNear(position.x, position.y, position.z, 1))
  }
  
  bot.on('health', () => {
	  if (bot.food < 20) {
		  eatsomedarnFood()
	  }
  })
	  
  bot.on('chat', function(username, message) {
  
    if (username === bot.username) return

    const target = bot.players[username] ? bot.players[username].entity : null
    if (message === 'come') {
      if (!target) {
		bot.chat('error: failed to pathfind')
        return
      }
      const p = target.position
	  pathfindTo(p)
	}
	
	if (message.startsWith('come') && message[5] == process.argv[2]){
		if (!target) {
			bot.chat('error: failed to pathfind')
			return
		}
		pathfindTo(target.position)
	}
  })
})

```

## Expected behavior
when the time of day reaches sunset (the time at which you may sleep in a bed), the bot should pathfind to the area in which the beds are located in my world and sleep in one

## Additional context
there's a lot of code in there that has nothing to do with the problem, but i left it in there so that i didn't have to go through the trouble of deleting it, and possibly removing a key bracket or the like
also, a lot of my code is kinda messy and uncommented, but that's because i never expected to show it to anyone

**Comment by ImHarvol** [comment]
Instead using `bot.sleep(new Block(480,78,1163))` try `bot.sleep(bot.blockAt(new vec3(480,78,1163)))`
Otherwise the Block instance only has the coordinates, but not the block ID and the other metadata
You may need to install and import [_vec3_](https://www.npmjs.com/package/vec3):  `npm i vec3`  and `const vec3 = require('vec3').Vec3;`

**Comment by ArcadeZtheWolf** [comment]
thanks, that seemed to work. i got the block id from a website that was linked somewhere in the documentation (this website https://minecraft-data.prismarine.js.org/?d=items), although i'm not sure how up-to-date it is. sorry for having to ask about this, i'm still getting used to javascript and this api.

**Comment by Karang** [comment]
This website is up to date, but you have to give the block id, not the item id https://minecraft-data.prismarine.js.org/?d=blocks

Anyway, as @ImHarvol suggested you should always use `mcData.blocksByName.white_bed.id`
