### ISSUE TITLE
Bot sometimes kicks when connected to mini mode through a window

### ISSUE THREAD

**Issue by NikitaLik** [PrismarineJS/mineflayer#1322]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: vanilla/spigot/paper 1.13.2
 - node: 12.18.4

## Clear question

Bot sometimes kicks after entering the mini-mode "Skyblock" at number 3 on server mc.prostocraft.ru.

## What did you try yet?
bot.on('WindowOpen',()=>{})
bot.clickwindow()
## Your current code

```js

bot.on("windowOpen", () => {
bot.clickWindow(10,0,0)
bot.clickWindow(12,0,0)
})


```

**Comment by rom1504** [comment]
What did you try yet to debug this?

**Comment by Denaryplanet** [comment]
> What did you try yet to debug this?

If you use debugging, then the bot kicks from the server hub due to the large number of maps.

**Comment by rom1504** [comment]
I advise you join discord and ask there, there is not enough information in this issue to help without coding the bot for you

**Comment by Denaryplanet** [comment]
> I advise you join discord and ask there, there is not enough information in this issue to help without coding the bot for you

What information is needed specifically? I can't go to Discord, I don't know English well.

**Comment by rom1504** [comment]
Exact error message, full log of packets, to begin with

**Comment by Denaryplanet** [comment]
> Exact error message, full log of packets, to begin with

No error is observed. Packet logos end on authorization due to kick due to a large number of cards, maybe they can somehow be turned off? So that I can see the package log.

**Comment by rom1504** [comment]
Log it to a file

**Comment by Denaryplanet** [comment]
> Записать в файл

Is it possible to change the way to debug output?

**Comment by rom1504** [comment]
DEBUG=minecraft-protocol node script.js > yourfile

**Comment by Denaryplanet** [comment]
> DEBUG=minecraft-protocol node script.js > yourfile

does not record, everything goes to the console

**Comment by rom1504** [comment]
DEBUG=minecraft-protocol node script.js 2> yourfile

**Comment by Denaryplanet** [comment]
Heroku cannot be written to a file. Maybe there is another way out

**Comment by Denaryplanet** [comment]
> DEBUG=minecraft-protocol node script.js > yourfile

is it possible somehow not to receive certain packages? And then I strongly assume that because of this he kicks. probability 90%

**Comment by rom1504** [comment]
You can filter out the output using grep
If heroku is the problem, simply don't use it to debug

**Comment by Denaryplanet** [comment]
> You can filter out the output using grep
> If heroku is the problem, simply don't use it to debug

And if without debugging too? Is it possible to filter packets somehow? for example do not accept effects, etc.

**Comment by rom1504** [comment]
I see no reason why that would help
But try node-minecraft-protocol that's the minimal amount of packet handling

**Comment by Denaryplanet** [comment]
> I see no reason why that would help
> But try node-minecraft-protocol that's the minimal amount of packet handling

No more solutions? It's just that I have already done a lot and it will take a lot of time to redo it.

**Comment by rom1504** [comment]
I told you already to give me the packet log if you want help, still waiting for it.
About node-minecraft-protocol I mean you just take any example of it and run it directly, you don't do anything.
Same for mineflayer btw, if that doesn't kick then the error is in your code.

Btw can you also share your code ? You don't seem to have given it yet, you may have bugs in it

**Comment by Denaryplanet** [comment]
> I told you already to give me the packet log if you want help, still waiting for it.
> About node-minecraft-protocol I mean you just take any example of it and run it directly, you don't do anything.
> Same for mineflayer btw, if that doesn't kick then the error is in your code.
> 
> Btw can you also share your code ? You don't seem to have given it yet, you may have bugs in it

oh, I didn't think so about the minecraft node protocol. Ok, in 2 hours I can share the debug

**Comment by Denaryplanet** [comment]
> I told you already to give me the packet log if you want help, still waiting for it.
> About node-minecraft-protocol I mean you just take any example of it and run it directly, you don't do anything.
> Same for mineflayer btw, if that doesn't kick then the error is in your code.
> 
> Btw can you also share your code ? You don't seem to have given it yet, you may have bugs in it

the problem is that you need to make a bot template to select window slots, activate items and more
