### ISSUE TITLE
window deposit

### ISSUE THREAD

**Issue by klokwert** [PrismarineJS/mineflayer#1324]
hi, i know that you can do `bot.currentWindow` to get the current window but that doesn't work with .deposite and .withdraw, is there anything like `bot.currentChest`?

**Comment by ImHarvol** [comment]
I dont think so, but you can use [bot.transfer(options, cb)](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#bottransferoptions-cb). Also check _[Lower level inventory methods](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#lower-level-inventory-methods)_.

**Comment by klokwert** [comment]
Ok, but how does that work?
Is it like:
`bot.transfer({
  window: bot.currentWindow,
  itemType: 57,
  metadata: null,
})` to transfer 1 stack of diamond blocks to the current open chest?

**Comment by ImHarvol** [comment]
If `bot.currentWindow` was your inventory, running the following code would move 1 diamond from the slot 36 of your inventory to the slot 44.
```js
const options = {
      window: bot.currentWindow,
      itemType: 57,
      metadata: undefined,
      count: 1,
      sourceStart: bot.currentWindow.inventoryStart,
      sourceEnd: bot.currentWindow.inventoryEnd,
      destStart: 36,
      destEnd: 44
    }
    bot.transfer(options, cb)
```
![steve inventory](https://wiki.vg/images/1/13/Inventory-slots.png)
Check [_Inventory Windows_](https://wiki.vg/Inventory#Windows) to see more about windows and their slots

---

 [bot.putAway(slot, cb)](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botputawayslot-cb) might facilitate some movements, bot.putAway() moves some slot from the window to your inventory, and you dont need to specify where to put it exactly in your inventory.

By the way, I just noticed [bot.moveSlotItem(sourceSlot, destSlot, cb)
](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botmoveslotitemsourceslot-destslot-cb) which is easier to use than bot.transfer

**Comment by klokwert** [comment]
I think I need `bot.putAway(slot, cb)` because I have to move it between the inventory and a window, but bot.putAway moves it from window to inventory but I need from inventory to window how do I do that?

**Comment by ImHarvol** [comment]
Then just use `bot.moveSlotItem(sourceSlot, destSlot, cb)` you can see the number of the slots here: https://wiki.vg/Inventory#Windows

**Comment by klokwert** [comment]
Is slot 46 the first slot of the chest?

**Comment by ImHarvol** [comment]
Small Chest:
![](https://wiki.vg/images/1/19/Chest-slots.png)

Large Chest:
![](https://wiki.vg/images/b/bb/DoubleChest-slots.png)

**Comment by klokwert** [comment]
Ok, thank you so much
