### ISSUE TITLE
Get player username by their entity.id ?

### ISSUE THREAD

**Issue by Shiiiwa** [PrismarineJS/mineflayer#1353]
```
`bot.on('entitySpawn', entity => {
    // do something
});`
```

I´m currently working with this event. On the Server, where I play, you can transform yourself with a command to a mob. 
If this event is triggered, it should check: 

 
```
if(bot.entities[entity.id].type === 'mob') {
    console.log(entity);
}
```

The output for a real player would be: 
```
Entity {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: 12010386,
  type: 'player',
  position: Vec3 { x: -7272.5, y: 44, z: -11913.5 },
  velocity: Vec3 { x: 0, y: 0, z: 0 },
  yaw: 1.521708941582556,
  pitch: -0.024543692606170175,
  onGround: true,
  height: 1.62,
  effects: {},
  equipment: [ <5 empty items> ],
  heldItem: undefined,
  isValid: true,
  metadata: [],
  username: 'Shiiiwa',
  uuid: 'f8eb4637-5a65-43bb-9661-d6dbfdde60fe',
  dataBlobs: undefined,
  [Symbol(kCapture)]: false
}
```

The output of transformed player would be: 
```
Entity {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: 12010386,
  type: 'mob',
  position: Vec3 { x: -7272.5, y: 43, z: -11913.5 },
  velocity: Vec3 { x: 0, y: 0, z: 0 },
  yaw: 1.4971652489763858,
  pitch: 0.07363107781851097,
  onGround: true,
  height: 0,
  effects: {},
  equipment: [ <5 empty items> ],
  heldItem: undefined,
  isValid: true,
  metadata: [],
  uuid: 'c8c61096-5305-41f5-8760-d4ced30c3089',
  mobType: 'Creeper',
  displayName: 'Creeper',
  entityType: 12,
  name: 'creeper',
  kind: 'Hostile mobs',
  headPitch: -0.04908738521234035,
  [Symbol(kCapture)]: false
}
```

So, I know how to distinguish between a real mob and a player, which is transformed to a mob. How can i get the name of the transformed player (output 1)  from the output 2 ? Thought something like:

bot.players[entity.id] // doenst work !

Thanks for your time

**Comment by ImHarvol** [comment]
I would try 2 things:
- id seems to be the same, so try to look for two entities (a mob and a player) with the same id
- Position is probably the same, so try to look for two entities (a mob and a player) with the same position

**Comment by Shiiiwa** [comment]
> I would try 2 things:
> 
> * id seems to be the same, so try to look for two entities (a mob and a player) with the same id
> * Position is probably the same, so try to look for two entities (a mob and a player) with the same position

Yes, could be a possible solution, thanks. But how can I check all player ids ? I know, there is a variable for all players:
`console.log(bot.players)`

herefor the output (for one player):
```
'example': {
    username: 'example',
    ping: 24,
    uuid: '04a2f472-baf6-4ae1-abe8-02a308bb1027',
    displayName: ChatMessage {
      json: [Object],
      text: '',
      extra: [Array],
      bold: undefined,
      italic: undefined,
      underlined: undefined,
      strikethrough: undefined,
      obfuscated: undefined,
      color: undefined
    },
    entity: null
  },
```
or, if the player has transformed:
```
example: {
    username: 'example',
    ping: 35,
    uuid: 'f8eb4637-5a63-43bb-9661-d6dbfdde60fe',
    displayName: ChatMessage {
      json: [Object],
      text: '',
      extra: [Array],
      bold: undefined,
      italic: undefined,
      underlined: undefined,
      strikethrough: undefined,
      obfuscated: undefined,
      color: undefined
    },
    entity: Entity {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      id: 611355,
      type: 'player',
      position: [Vec3],
      velocity: [Vec3],
      yaw: 5.5714182216006485,
      pitch: 0.09817477042468115,
      onGround: true,
      height: 1.62,
      effects: {},
      equipment: [Array],
      heldItem: undefined,
      isValid: true,
      metadata: [Array],
      username: 'example',
      uuid: 'f8eb4637-5a63-43bb-9661-d6dbfdde60fe',
      dataBlobs: undefined,
      headYaw: 5.522330836388308,
      [Symbol(kCapture)]: false
    }
  },
```
How can I access the json output for one person, to check his id (if entity != null) ?

**Comment by ImHarvol** [comment]
> > I would try 2 things:
> > 
> > * id seems to be the same, so try to look for two entities (a mob and a player) with the same id
> > * Position is probably the same, so try to look for two entities (a mob and a player) with the same position
> 
> Yes, could be a possible solution, thanks. But how can I check all player ids ? I know, there is a variable for all players:
> `console.log(bot.players)`

The thing is that I think the player must be rendered (must be close to your bot) to have his entity object (which contains the `id`). That means that you can only get the id of the players that are near you. You can get those by loking in bot.entities for entities whose type is 'player'.

**Comment by Shiiiwa** [comment]
Okay, thanks. But now the second part of my question above is still missing. How do I "iterate" through bot.entites ? (And check, if any element matches with type)

**Comment by ImHarvol** [comment]
You're likely to be interested in [Array.prototype.find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) and [Array.prototype.filter()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter).

If you're looking for a player entity with `someId`:
```js
const entity = Object.values(bot.entities).find(entity => entity.type === 'player' && entity.id === someId)
```

If you want to get an array with all the players entities:
```js
const entities = Object.values(bot.entities).filter(entity => entity.type === 'player')
```

Is this what you mean?

**Comment by Shiiiwa** [comment]
Yes, thanks. I hope this will be my last comment, but at all it doesnt fixed my problem, which I´m facing. 
Here´s an example, of a situation. 

There are a few people, lets say 5 arround the bot. He prints five times the entity json of these players. One of them transforms him into a creeper for example. Now, he prints  a new json with the same entity ID, as this player had before. Based on this ID, I want to get the Username of the player, who transformed into a creeper. But this user stays transformed as a creeper. 
If I iterate through bot.entities, it matches with an entity ID, but not with the entity type, because the player stayed  transformed.

Do you see my Problem ? Through what should I iterate, if bot.entities doesnt work ?

**Comment by ImHarvol** [comment]
> Yes, thanks. I hope this will be my last comment, but at all it doesnt fixed my problem, which I´m facing.
> Here´s an example, of a situation.

Don't hesitate to ask! Just know that maybe [PrismarineJS's Discord]() might a better place for this type of questions 😄
You'll get much better response time, you can even send me questions to imharvol#6174

 ---

Ohh, sorry I think I was misunderstanding you. Then, the only way is to keep track of the user ids (in something like an array) so when they transform into a mob you can check whose username had that ID.

The thing is that when they transform your actual minecraft client really perceives that entity as a mob, not as a player, so the client really thinks there's no actual relation between the mob and an actual player that transformed into that mob.

**Comment by Shiiiwa** [comment]
So, where I can find the IP of this discord server?

**Comment by ImHarvol** [comment]
I linked this issue 🤦 , sorry

There you go!
https://discord.gg/7tpFSP
