### ISSUE TITLE
Get FakePlayer-Tablist

### ISSUE THREAD

**Issue by Zynoxi** [PrismarineJS/mineflayer#1364]
I wanted to ask how I can read "Fake Player" in the tab list.
With `console.log(bot.players); ` I unfortunately only get the normal players
Example: https://i.imgur.com/juowxfR.png (What I mean as a Fake Player.)

**Comment by rom1504** [comment]
bot._client.on('player_info', data

**Comment by uniquadev** [comment]
> I wanted to ask how I can read "Fake Player" in the tab list. With `console.log(bot.players); ` I unfortunately only get the normal players Example: https://i.imgur.com/juowxfR.png (What I mean as a Fake Player.)

did you found a way?
