### ISSUE TITLE
Move features.json to mcdata

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#1392]
and move supportFeature.js to node-minecraft-data

possibly keep a mineflayerSpecificFeatures.json that would be merged with the mcdata one for quick iteration (or maybe not)

then merge flying-squid one into the mcdata one

**Comment by rom1504** [comment]
1. move current features.json to mcdata, move supportFeature implementation to node-minecraft-data (or a prismarine-feature maybe)
2. use that in mineflayer
3. add the functionality to be able to use other values than true/false
4. use in pitem and friends

**Comment by rom1504** [comment]
done

next : use it everywhere
* [ ] pitem https://github.com/PrismarineJS/prismarine-item/blob/master/index.js#L73
* [ ] pblock https://github.com/PrismarineJS/prismarine-block/blob/master/index.js#L31
* [ ] flying-squid https://github.com/PrismarineJS/flying-squid/blob/master/src/lib/features.json
* [ ] p-windows https://github.com/PrismarineJS/prismarine-windows/blob/master/index.js#L7

**Comment by rom1504** [comment]
* [ ] use _major syntax in features.json

**Comment by rom1504** [comment]
this could be used in pblock, flying-squid and pwindows now that you move features in mcdata @Epirito

**Comment by Epirito** [comment]
Yeah I'll get around to it

**Comment by Epirito** [comment]
tried to do it on flying-squid but it turns out that the tests are currently broken. They fail even if you don't modify anything. So I can't change it while that's the case

**Comment by rom1504** [comment]
Ok yeah let's focus on the other 2

**Comment by rom1504** [comment]
flying-squid didn't receive a lot of attention for a while, would need some work to get it back in a good state

**Comment by rom1504** [comment]
This is done
