### ISSUE TITLE
bot.sleep or sleeper.js don't work

### ISSUE THREAD

**Issue by DrMoraschi** [PrismarineJS/mineflayer#1400]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.32.0
 - server: vanilla/spigot/paper 1.16.1
 - node: 12.18.3

## Detailed description of a problem
I run sleeper.js, and everytime i tell it to go to sleep(bed already placed in front of him) he sends "I can't sleep: it's not night". I think this is a problem of bot.sleep.

## What did you try yet?

Did some tweaking on sleeper.js but it seems like the problem is bot.sleep

## Expected behavior
Make the bot sleep.

**Comment by imharvol** [comment]
Yeah, makes sense! Related issue: #1398

**Comment by DrMoraschi** [comment]
> Yeah, makes sense! Related issue: #1398

Yeah, saw this issue before, didn't know if I had to write the issue there in the comments or not, so I created a new issue.
