### ISSUE TITLE
Using SOCKS5 (with authentication) proxies

### ISSUE THREAD

**Issue by EvernoteMC** [PrismarineJS/mineflayer#1418]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

I've read through multiple issues regarding the usage of proxies with mineflayer, however I was unable to figure out how to use SOCKS5 (with authentication) proxies in mineflayer.

I have the proxy ip, proxy port, proxy username and proxy password.

I'd appreciate it if someone could help me with what code to add to ensure that the proxy could be used.

**Comment by rom1504** [comment]
same as https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js

**Comment by rom1504** [comment]
maybe you could solve this task once you got this working https://github.com/PrismarineJS/mineflayer/issues/438
(you're probably the 10th person asking this, the 11th one could use the doc)

**Comment by EvernoteMC** [comment]
I used the following code:

```javascript
const config = require("./config.json")
const bot = mc.createClient({
  connect: client => {
    socks.createConnection({
      proxy: {
        host: config.proxy_ip,
        port: parseInt(config.proxy_port),
        type: 5,
        userId: config.proxy_username,
        password: config.proxy_password
      },
      command: 'connect',
      destination: {
        host: config.server_ip,
        port: parseInt(config.server_port)
      }
    }, (err, info) => {
      if (err) {
        console.log(err)
        return
      }
      client.setSocket(info.socket)
      client.emit('connect')
    })
  },
  agent: new ProxyAgent({ protocol: 'socks5:', host: config.proxy_ip, port: parseInt(config.proxy_port), userId: config.proxy_username, password: config.proxy_password}),
  username: config.email,
  password: config.password
})
bot.on('connect', function (spawn) {
    console.log("Logged in")
});
bot.on('end', packet => {
    console.log("Connection ended abruptly")
})
```

On running this code, I get the following output:
> Logged in
> Connection ended abruptly

No other output in the console

I checked the proxy I was using and it works fine

**Comment by EvernoteMC** [comment]
bump

**Comment by rom1504** [comment]
remove ProxyAgent part
