### ISSUE TITLE
With hexxit?

### ISSUE THREAD

**Issue by lilRufi** [PrismarineJS/mineflayer#1419]
Can I use mineflayer with hexxit?

**Comment by rom1504** [comment]
what is hexxit ?

**Comment by mat-1** [comment]
Mineflayer doesn't have support for forge mods, you'd have to use node-minecraft-protocol-forge and implement the packets yourself

**Comment by lilRufi** [comment]
h-how can i do that :3

**Comment by lilRufi** [comment]
oh get it now
