### ISSUE TITLE
Mineflayer is unusable - version 2.33.0 - TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by Zyrexus** [PrismarineJS/mineflayer#1426]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.33.0
 - server: vanilla/spigot/**paper** 1.8.8
 - node: v11.0.0

## Detailed description of a problem
Hello I've been using mineflayer version 2.28.1 for the past week and it's been working great, but when I decided to update to mineflayer version 2.33.0 I get the following error:
![image](https://user-images.githubusercontent.com/14060724/97809864-a0357800-1c67-11eb-9675-8bda4f3498be.png)

## What did you try yet?

Did you try any method from the API? mineflayer.createBot(Options);
Did you try any example? Any error from those? All examples create the same error (with the login details adjusted)

## Your current code
```js

const mineflayer = require('mineflayer');
const Auth = require('./auth.json');

const session = {
    accessToken: Auth[1].accessToken,
    clientToken: Auth[1].clientToken,
    selectedProfile: {
        id: Auth[1].selectedUser.profile,
        name: Auth[1].displayName
    }
};

const botOptions = {
    host: 'zyrex.cx', // optional zyrex.cx
    port: 25565, // optional
    version: "1.8.8"
}

const botOptions_ = botOptions;
botOptions_['session'] = session;


let bot = mineflayer.createBot(botOptions_);
botFunctions(bot);

```

## Expected behaviour
The bot to work like normal (like 2.28.1)

## Additional context
**IDE:**  JetBrains Webstorm 2020.2.3
**PC Specs:**
Windows 10 Pro
Ryzen 7 1800x
AMD Rx 5700xt
32GB Ram

**Comment by Zyrexus** [comment]
Irrelevant functions, WebSocket & HTTP server methods have been removed in the visible current code.

**Comment by imharvol** [comment]
Object.fromEntries() seems like was added in node v12.0.0, so consider using node v12.0.0 or higher.

Should we consider replacing that function, not to break mineflayer's node backwards compatibility @rom1504 ?

**Comment by rom1504** [comment]
You need to update your node version

We should add a check for this

**Comment by rom1504** [comment]
No I think we should simply state clearly (and add a check in the code)
that we support only node >= 12

**Comment by rom1504** [comment]
We could use https://www.npmjs.com/package/check-node-version

**Comment by rom1504** [comment]
#1427
