### ISSUE TITLE
how to get the list of players that are in the visibility area.

### ISSUE THREAD

**Issue by qqqZXzz123** [PrismarineJS/mineflayer#1438]

**Comment by imharvol** [comment]
You probably want to look for player in `bot.entities`:
```js
const playerEntities = bot.entities.filter(e => e.type === 'player')
```

**Comment by qqqZXzz123** [comment]
TypeError: bot.entities.filter is not a function

**Comment by imharvol** [comment]
Yeah, sorry, `bot.entities` is not an array. It should be:
```js
const playerEntities = Object.values(bot.entities).filter(e => e.type === 'player')
```

**Comment by qqqZXzz123** [comment]
Thank you, but how do I get the names of players as text?

**Comment by DrMoraschi** [comment]
I think `console.log(playerEntities)`

**Comment by qqqZXzz123** [comment]
how to extract a player's name from username: ?

**Comment by DrMoraschi** [comment]
Could you paste your code?

**Comment by qqqZXzz123** [comment]
bot.on('death', () => {
	let playerEntities = Object.values(bot.entities).filter(e => e.type === 'player')
	console.log(playerEntities)
})

prints

[
  Entity {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    id: 124,
    type: 'player',
    position: Vec3 { x: -141.2974700556448, y: 68, z: 260.62227700985477 },
    velocity: Vec3 { x: 0, y: 0, z: 0 },
    yaw: 4.3933209765044765,
    pitch: -0.12271846303085132,
    onGround: true,
    height: 1.62,
    width: 0.6,
    effects: {},
    equipment: [ [Item], <4 empty items> ],
    heldItem: Item {
      type: 276,
      count: 1,
      metadata: 0,
      nbt: null,
      name: 'diamond_sword',
      displayName: 'Diamond Sword',
      stackSize: 1
    },
    isValid: true,
    metadata: [
      0,        300,      '',
      false,    false,    false,
      0,        20,       0,
      false,    0,        0,
      35,       127,      1,
      [Object], [Object]
    ],
    username: 'qqqZXzz123',
    uuid: 'a5d430dd-e349-3d23-9979-4550651085f4',
    dataBlobs: undefined,
    headYaw: 4.417864669110647,
    [Symbol(kCapture)]: false
  },
  Entity {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    id: 3214,
    type: 'player',
    position: Vec3 { x: -132.5, y: 65, z: 251.5 },
    velocity: Vec3 { x: 0, y: -0.0784, z: 0 },
    yaw: 3.141592653589793,
    pitch: 0,
    onGround: true,
    height: 1.62,
    width: 0,
    effects: {},
    equipment: [ <5 empty items> ],
    heldItem: Item {
      type: 346,
      count: 1,
      metadata: 0,
      nbt: null,
      name: 'fishing_rod',
      displayName: 'Fishing Rod',
      stackSize: 1,
      slot: 36
    },
    isValid: true,
    metadata: [
      0,        300,      '',
      false,    false,    false,
      0,        20,       0,
      false,    0,        0,
      5,        127,      1,
      [Object], [Object]
    ],
    username: 'autobotfish_1',
    timeSinceOnGround: 0,
    isInWater: false,
    isInLava: false,
    isInWeb: undefined,
    isCollidedHorizontally: false,
    isCollidedVertically: true,
    [Symbol(kCapture)]: false
  }
]
chat autobotfish_1 fell out of the world
[
  Entity {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    id: 124,
    type: 'player',
    position: Vec3 { x: -141.2974700556448, y: 68, z: 260.62227700985477 },
    velocity: Vec3 { x: 0, y: 0, z: 0 },
    yaw: 4.3933209765044765,
    pitch: -0.12271846303085132,
    onGround: true,
    height: 1.62,
    width: 0.6,
    effects: {},
    equipment: [ [Item], <4 empty items> ],
    heldItem: Item {
      type: 276,
      count: 1,
      metadata: 0,
      nbt: null,
      name: 'diamond_sword',
      displayName: 'Diamond Sword',
      stackSize: 1
    },
    isValid: true,
    metadata: [
      0,        300,      '',
      false,    false,    false,
      0,        20,       0,
      false,    0,        0,
      35,       127,      1,
      [Object], [Object]
    ],
    username: 'qqqZXzz123',
    uuid: 'a5d430dd-e349-3d23-9979-4550651085f4',
    dataBlobs: undefined,
    headYaw: 4.417864669110647,
    [Symbol(kCapture)]: false
  },
  Entity {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    id: 3214,
    type: 'player',
    position: Vec3 { x: -132.5, y: 65, z: 251.5 },
    velocity: Vec3 { x: 0, y: -0.078375, z: 0 },
    yaw: 3.141592653589793,
    pitch: 0,
    onGround: true,
    height: 1.62,
    width: 0,
    effects: {},
    equipment: [ <5 empty items> ],
    heldItem: Item {
      type: 346,
      count: 1,
      metadata: 0,
      nbt: null,
      name: 'fishing_rod',
      displayName: 'Fishing Rod',
      stackSize: 1,
      slot: 36
    },
    isValid: true,
    metadata: [
      0,        300,      '',
      false,    false,    false,
      0,        0,        0,
      false,    0,        0,
      5,        127,      1,
      [Object], [Object]
    ],
    username: 'autobotfish_1',
    timeSinceOnGround: 0,
    isInWater: false,
    isInLava: false,
    isInWeb: undefined,
    isCollidedHorizontally: false,
    isCollidedVertically: true,
    [Symbol(kCapture)]: false
  }
]

**Comment by wvffle** [comment]
```js
bot.on('death', () => {
  const players = Object.values(bot.entities)
    .filter(e => e.type === 'player')
    .map(p => p.username)
  console.log(players)
})
```

Those are some basics of javascript. If it's your first contact with this language, please refer to one of the guides: https://github.com/PrismarineJS/mineflayer/blob/master/docs/tutorial.md, [javascript.info](javascript.info)

**Comment by qqqZXzz123** [comment]
thank you so much
