### ISSUE TITLE
Address desynchronization of world data and bot entity properties

### ISSUE THREAD

**Issue by christopherthompson81** [PrismarineJS/mineflayer#1439]
- [✓] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [✓] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [✓] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.34.0
 - server: vanilla 1.16.3
 - node: 12.19.0

## How do I address desynchronization of world data and bot entity properties like inventory?

I am working on another related package - autobot. It's currently a plugin that offers high-level behaviours that emit events so player-simulator bots can be built in an event-driven way. I want the bot to be able to run over night, but it ends up getting stuck or behaving poorly and the cause appears to be the the way it sees the world does not match the current world state. For example, physical blocks are seen as air or its inventory doesn't match the server value.

## What have I already tried?

I'm thinking that means there is a need to reload world sections or chunks, or force a lower-level refresh of the inventory, but I can't see any methods to do that. I want to know where to look and which repository covers this.

The mineflayer API does not provide a _client reload function. The minecraft-protocol client also does not offer a reload function.

## Your current code

https://github.com/christopherthompson81/autobot

**Comment by flowl** [comment]
I am developing a similiar bot and cannot confirm all the problems you mentioned.
Only thing I have sometimes is the `bot.waitForChunksToLoad(() => {` triggering before neighboring chunks loaded, but it could be related to non-vanilla server issues.

In my case, the bot spawns and looks for signs with specific texts. The `waitForChunksToLoad` triggers without error but not all signs of direct neighbornig chunks are loaded.

Other than that, I see you are working a lot with millisecond timeouts and there could be a lot of race conditions in your code.

**Comment by christopherthompson81** [comment]
That's fantastic that your bot works without those issues. The timeouts are addressing callback flaws from other packages (like mineflayer itself) where things like crafting trigger the callback before the item is available n the inventory or pathfinding states failing to be set correctly. The server also can't be spammed without causing issues. Fixing those issues in the parent packages would require a whole different set of work.

One of the clearest ways to demonstrate the problem is to have a tree sapling grow into a tree while the bot is running - the bot will not see the logs and leaves as being there and you're welcome to verify that. The "fill" command also works to cause a world state the bot is not synchronized with.

So, respectfully, that's not it.

**Comment by rom1504** [comment]
If you could write one (or several if you observe several bugs) minimal
example reproducing your issue, it would help a lot to fix them

**Comment by christopherthompson81** [comment]
I found what I was looking for - it appears to be the "Location" class and the "unloadColumn" function from prismarine-world.

**Comment by rom1504** [comment]
why did you close? there was no bug in the end ?
