### ISSUE TITLE
Flint and Steel won't activate using bot.activateItem()

### ISSUE THREAD

**Issue by SoLegendary** [PrismarineJS/mineflayer#1441]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 1.16.1
 - server: vanilla
 - node: v12.18.3

## Detailed description of a problem
I am just trying to have the bot equip a flint and steel and light a fire but bot.activateItem() doesn't seem to do anything. The same code below with 'flint_and_steel' replaced with 'lava_bucket' works as intended - the bot places the lava on the block it's looking at.

## What did you try yet?
I tried all combinations of bot.activateItem() and bot.deactivateItem() with delays included as well as other 'activate' right click functions like fishing and placing blocks.

## Your current code
```js

let items = bot.inventory.items()
for (let item of items) {
  if (item.name == 'flint_and_steel') {
    bot.equip(item, 'hand', () => {
      bot.activateItem()
    })
  }
}

```

## Expected behavior
I expected it to light a fire

**Comment by qqqZXzz123** [comment]
I wrote a function that lights up the tip of the wooden block

function podjog() {
			const mcData = require('minecraft-data')(bot.version)
		const block = bot.findBlock({
        matching: mcData.blocksByName.log.id,
        maxDistance: 4,
    })
	console.log(block)
const faceVector = new Vec3(0, 1, 0)
const referenceBlock = new Vec3(block.position.x, block.position.y, block.position.z)
bot.placeBlock(bot.blockAt(referenceBlock), faceVector)
console.log(referenceBlock)
console.log(faceVector)
}

**Comment by qqqZXzz123** [comment]
flint_and_steel used through bot.placeBlock

**Comment by SoLegendary** [comment]
Thanks for that qqq, didn't realise it treated flint and steel as a block placement

**Comment by qqqZXzz123** [comment]
))
