### ISSUE TITLE
the bot does not place the block after it is breaken.

### ISSUE THREAD

**Issue by qqqZXzz123** [PrismarineJS/mineflayer#1442]
function postavicacao(block) {
	console.log("ставлю какао")
	console.log(block)
const faceVector = new Vec3(0, 1, 0)
const referenceBlock = new Vec3(block.position.x, block.position.y - 1, block.position.z)
console.log(referenceBlock)
console.log(faceVector)
bot.placeBlock(bot.blockAt(referenceBlock), faceVector)
}

function lomaykakao() {
		const block = bot.findBlock({
  point: bot.entity.position,
  matching: (block) => {
    return block && block.type === 127 && block.metadata > 7
  }
})
	if (block == null) {
		return
	}
	console.log(block)
		bot.dig(block, [postavicacao(block)])
}

**Comment by christopherthompson81** [comment]
Your "dig" call does not comport with the API: https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botdigblock-forcelook--true-callback

Try this:
```js
function postavicacao(block) {
	console.log("ставлю какао");
	console.log(block);
	const faceVector = new Vec3(0, 1, 0);
	const referenceBlock = new Vec3(
		block.position.x,
		block.position.y - 1,
		block.position.z
	);
	console.log(referenceBlock);
	console.log(faceVector);
	bot.placeBlock(bot.blockAt(referenceBlock), faceVector);
}

function lomaykakao() {
	const block = bot.findBlock({
		point: bot.entity.position,
		matching: (block) => {
			return block && block.type === 127 && block.metadata > 7;
		},
	});
	if (block == null) {
		return;
	}
	console.log(block);
	bot.dig(block, false, () => { postavicacao(block); });
}
```

Make note of the changes on the last line.

**Comment by qqqZXzz123** [comment]
Error: No block has been placed : the block is still air

**Comment by qqqZXzz123** [comment]
how to put a block on coordinates without faceVector ?
