### ISSUE TITLE
Jump event

### ISSUE THREAD

**Issue by DevPieter** [PrismarineJS/mineflayer#1445]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
please add a jump event that fires when a player jumps like the entityCrouch event.

(if it already exists please tell me)

**Comment by rom1504** [comment]
you can use entityMoved to try and detect jumps https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#entitymoved-entity

**Comment by DevPieter** [comment]
Can you please give an example I can't get it to work

**Comment by DevPieter** [comment]
please

**Comment by extremeheat** [comment]
The server never sends the jump action over the network, you only get an entity movement packet with a new position. So you can't really know if an entity jumped, but you can have your code assume a jump if:
* the entity has a positive y velocity
* the player isn't on the ground
* isn't colliding with any existing bounding box (liquid, slime block, etc.)
* the entity isn't riding anything

And many other edge cases, so it depends how accurate you need it to be. So watch for changes in positive y velocity, and run tests for what you think is important for your use case

**Comment by DevPieter** [comment]
Thank you, I'll try to figure it out.
