### ISSUE TITLE
Is it possible to get the FPV of the bot?

### ISSUE THREAD

**Issue by nerdimite** [PrismarineJS/mineflayer#1448]
Hi,

I am hoping to use mineflayer for a reinforcement learning project which basically takes the bot's FPV image as input and then uses that to take an action. However, I can't seem to find anything in the API which returns what the bot is seeing as an image (or consecutive frames for that matter). Is there any possible way to get the frames of what the bot is seeing in the game? I did check prismarine-viewer but it gives the world view and not the bot's perspective of the world. Even if you have any other resources or ways to basically use Minecraft for AI projects do share them.

Thanks!

p.s. I did check with Project Malmo (by microsoft) but it runs the bot independently and human players cannot really join the bot.

**Comment by Karang** [comment]
https://github.com/PrismarineJS/prismarine-viewer/blob/master/examples/firstperson_bot.js

**Comment by nerdimite** [comment]
@Karang Thanks for that! Although is it possible to get the frames as images and save them in a folder or something? Also, why are the players and other mobs always like a cube of blue or red color? Is it possible to show the exact world view as is?

**Comment by Karang** [comment]
prismarine-viewer is still a work in progress and open for contributions.
There is a way to capture frames using puppeteer (what we use in the tests of pviewer to generate the screenshots).
I'm afraid there is no plug and play solution for what you want to do exactly, but using pviewer can be a good starting point.

**Comment by nerdimite** [comment]
oh okay, I will try the screenshot method. Thanks again!

**Comment by nerdimite** [comment]
One issue though in pviewer, currently the bot is set to look at the player but when i fly up, it shows the frames as if its looking down even though the bot head is tilted up. And when i go down the viewer looks up. I guess the y-axis is inverted in the viewer which is causing this issue. How do I fix this?

**Comment by Karang** [comment]
ah it's probably a sign error here: https://github.com/PrismarineJS/prismarine-viewer/blob/master/src/index.js#L59

**Comment by nerdimite** [comment]
should i change the package src in my installation?

**Comment by Karang** [comment]
It's probably better to make a pull request ;)

**Comment by nerdimite** [comment]
I tried negating it as `camera.rotation.y = - camera.rotation.y * 0.9 + yaw * 0.1` and it did fix the y-axis inversion problem but now the x-axis doesn't work. It only looks at one half of the view. If I go behind it doesn't turn on the x-axis while continuing to work on the y-axis.

**Comment by Karang** [comment]
you need to negate the pitch, not the yaw

**Comment by nerdimite** [comment]
tried that but still no luck, i will try different things and see. If it doesn't work then i will create a new issue on the prismarine viewer repo

**Comment by Karang** [comment]
pviewer now have a way to record frame as video.
the issue with the camera rotation have been fixed.
