### ISSUE TITLE
Will there ever be a python port?

### ISSUE THREAD

**Issue by satyamedh** [PrismarineJS/mineflayer#1450]
So I wanted to control the player using python(cuz I am more famaliar with it and has full tensorflow support), quickly found https://github.com/Microsoft/malmo, but it is outdated and has poor documentation. next found this but is in js.

So is there ever going to be a port t python?

**Comment by rom1504** [comment]
I believe the best way to do that is simply to talk with mineflayer over the network, see https://github.com/PrismarineJS/mineflayer/issues/1158

**Comment by rom1504** [comment]
https://github.com/SpockBotMC/RikerBot is another option, but it's currently much less feature complete than mineflayer

**Comment by satyamedh** [comment]
@rom1504 Rickerbot seems good, but can you explain abt your issue?

**Comment by satyamedh** [comment]
I didnt get what u mean

**Comment by rom1504** [comment]
Rikerbot is missing most features. As you can see from the readme it doesn't have physics which means the bot cannot move

**Comment by satyamedh** [comment]
I get that, I mean how to talk with mineflayer over the net

**Comment by rom1504** [comment]
Click on the issue I pointed.
You'd have to build a web server, express for example, exposing mineflayer features

**Comment by satyamedh** [comment]
Sockets? ok lol

**Comment by DrMoraschi** [comment]
If you want to make a chat that is displayed in 'localhost' you can check socket.io

**Comment by satyamedh** [comment]
I'll just use sockets, If any python port pls reopen!

**Comment by extremeheat** [comment]
> I'll just use sockets, If any python port pls reopen!

There's now Python support, look at the README and the click on the "Open in Colab" badge for usage steps and look in the examples folder for examples.
