### ISSUE TITLE
mulitiple.js doesn't work

### ISSUE THREAD

**Issue by Kiepi** [PrismarineJS/mineflayer#1455]
This code [multiple.js](https://github.com/PrismarineJS/mineflayer/blob/master/examples/multiple.js) doesnt work. Only 1 bot joins server.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
Need more info

**Comment by Kiepi** [comment]
Versions
mineflayer: latest
server: paper 1.16.3
node: latest

Only 1 bot joins server

`const mineflayer = require('mineflayer')

if (process.argv.length < 3 || process.argv.length > 5) {
  console.log('Usage : node multiple.js <host> <port>')
  process.exit(1)
}

let i = 0
function next () {
  if (i < 10) {
    i++
    setTimeout(() => {
      createBot(`mineflayer-bot${i}`)
      next()
    }, 100)
  }
}
next()

function createBot (name) {
  mineflayer.createBot({
    host: process.argv[2],
    port: parseInt(process.argv[3]),
    username: name
  })
}`
