### ISSUE TITLE
Delay in joining bots

### ISSUE THREAD

**Issue by Mario637868** [PrismarineJS/mineflayer#1456]
How to do delay between every time bot join. Because on minecraft servers is connection throttle 4000 ms, on my server too.
I modified this code and it almost works, but not like I want to. Because still every 5 sec, 5 bots joins server and after next 5 sec again 5 bot join, of course only 1 enter server, every 5 sec, so there are useless connections and overload my PC, how to change this?

Code I used [mineflayer/multiple.js](https://github.com/PrismarineJS/mineflayer/blob/master/examples/multiple.js) and [pathfinder/multiple.js](https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/examples/multiple.js)

My code below

```
const mineflayer = require('mineflayer')

mineflayer.multiple = (bots, constructor) => {
  const { Worker, isMainThread, workerData } = require('worker_threads')
  if (isMainThread) {
    const threads = []
    for (const i in bots) {
      threads.push(new Worker(__filename, { workerData: bots[i] }))
    }
  } else {
    constructor(workerData)
  }
}

const bots = []
for (let i = 0; i < 5; i++) {
  bots.push({ username: `Bot${i}` })
}

let i = 0
function next () {
  if (i < 5) {
    i++
    setTimeout(() => {
      mineflayer.multiple(bots, ({ username }) => {
        const bot = mineflayer.createBot({
          username,
          host: 'IP',
          port: port
        })
      
        bot.on('kicked', function(reason, loggedIn) {
          console.log('Kick: '+reason, loggedIn)
        })
        
        bot.on('error', function(err) {
          console.log(err)
        })
      })
      next()
    }, 5000)
  }
}
next()
```

**Comment by goncharovchik** [comment]
I'm not a professional, but in my opinion it is better to use traditional mineflayer.createBot()  with delays.

**Comment by Mario637868** [comment]
The way you propose, is much less optimal IMO

**Comment by rom1504** [comment]
you need to propagate the i variable
