### ISSUE TITLE
how to disconnect a bot from the server and finish js code execution?

### ISSUE THREAD

**Issue by qqqZXzz123** [PrismarineJS/mineflayer#1463]

**Comment by imharvol** [comment]
```js
bot.end() // You can also use bot.quit(reason)
process.exit() // Terminates the process
```

See https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botend and https://nodejs.org/api/process.html#process_process_exit_code

It would be better to post questions like this one in Discord, you probably would get a quicker response: https://discord.gg/r7pE9aRH
