### ISSUE TITLE
Multiple server

### ISSUE THREAD

**Issue by areny7** [PrismarineJS/mineflayer#1465]
A multiplayer server, enter the game login, need to right click the robot to enter the main city, but I do not know the command to enter the main city, how should I do this?

**Comment by goncharovchik** [comment]
> A multiplayer server, enter the game login, need to right click the robot to enter the main city, but I do not know the command to enter the main city, how should I do this?

You can use chat to log `bot.chat(message)` into the server if the server is offline. If online, add a password value. To click on a robot, try: `bot.activateEntityAt(entity, position, [callback])`

Please fill out the template
