### ISSUE TITLE
Workbench problem

### ISSUE THREAD

**Issue by areny7** [PrismarineJS/mineflayer#1466]
How do I control the robot to use the table for synthesis, my goal now is for the robot to take the watermelon pieces out of the box, and then use the table for synthesis into watermelon pieces

**Comment by DrMoraschi** [comment]
Please read the API first like goncharo said

**Comment by unnown** [comment]
i'm sorry what in the what now?

This repo is used for making your own code/bot to do things with, people don't write code for you
My advice is to try looking at the example codes and see if they partially do what you want and go from there
