### ISSUE TITLE
What is the Discord link?

### ISSUE THREAD

**Issue by DrMoraschi** [PrismarineJS/mineflayer#1468]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Clear question

I searched it in the README but I couldn't find it, there was a link in an old issue but it doesn't work anymore. Can someone paste the link? Thanks

**Comment by rom1504** [comment]
First line of the readme

**Comment by DrMoraschi** [comment]
Oh yeah it was really tiny, sorry
