### ISSUE TITLE
Use mineflayer in React

### ISSUE THREAD

**Issue by Tashex** [PrismarineJS/mineflayer#1470]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [X] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [X] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.34.0
 - server: Spigot
 - node: 15.2.1

## Clear question
Hey I would like to use mineflayer in React. Unfortunately during the build I get the error that mineflayer cannot find the module "pref_hooks" or that eg net.isIp is not a function. But my goal is that I can use mineflayer on the client side and not on the server side. 
Is there any way I can run mineflayer or minecraft protocol on the client side and best use it with react?

**Comment by rom1504** [comment]
You can use mineflayer on the client side if you have a websocket proxy
running somewhere that will do the link with tcp connection to minecraft
servers

**Comment by Tashex** [comment]
Thanks for the answer. But could you please explain this to me in more detail.
I do not want mineflayer to run on a node.js server because then the IP is used by the server. But I want to use the IP from the client as the IP for the Minecraft client.

**Comment by rom1504** [comment]
Yeah that is impossible as minecraft server only accept tcp connection and
the browser cannot open tcp connection

**Comment by Tashex** [comment]
Ahh that's not good. 
Okay then I have to try differently. Nevertheless, thanks for the answer.

Do you happen to be familiar with the Minecraft Protocol (https://wiki.vg/Protocol) and can you help me to create a bot in Java?

**Comment by rom1504** [comment]
I don't understand what you are trying to do. If your environment can run
java then it can run node and it's not client side. So you can run
mineflayer in that environment.
