### ISSUE TITLE
bot.dig doesn't work (vanilla, 1.12.2)

### ISSUE THREAD

**Issue by recursivetree** [PrismarineJS/mineflayer#1471]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.34.0
 - server: vanilla

## Detailed description of a problem
I tried to build a bot which mines the closest block, but bot.dig doesn't work. It gets stuck in front of the block and it swings it's arms, but doesn't actually mine it.

This also affect mineflayer-pathfinder

## What did you try yet?

I added a ton of debug logs

## Your current code
```js
const mineflayer = require('mineflayer')
const { pathfinder, Movements } = require('mineflayer-pathfinder')
const { GoalGetToBlock } = require('mineflayer-pathfinder').goals

botOptions = {
    host: 'localhost',
    port: 25565,
    username: "miner"
}

const bot = mineflayer.createBot(botOptions)
bot.loadPlugin(pathfinder)

async function findAndMine(id){
    const block = bot.findBlock({ matching: id, maxDistance: 32 })
    if (block){
        const promiseHack = new Promise((res,rej)=>{
            bot.once('goal_reached', (goal) => {
                if (!bot.canDigBlock(block)){
                    throw new Error("unable to reack block")
                }
                bot.dig(block,false)
                bot.once("diggingCompleted",(block)=>{
                    res()
                })
             })
             bot.pathfinder.setGoal(new GoalGetToBlock(block.position.x, block.position.y, block.position.z))
         })
         await promiseHack
         console.log("promise")
         return
    } else {
        throw new Error("no block found")
    }
}
bot.on("diggingAborted",(block)=>{
    console.log("diggingAborted")
})
bot.on("diggingCompleted",(block)=>{
    console.log("diggingCompleted")
})

bot.once('spawn',() =>{
    const mcData = require('minecraft-data')(bot.version)
    const moves = new Movements(bot, mcData)
    bot.pathfinder.setMovements(moves)

    const blockName = "log"

    const blockIds = mcData.blocksByName[blockName].id

    findAndMine(blockIds)
    .catch(function(err){
        console.log(err)
    })
    .then(function(){
        console.log("done")
        bot.quit()
    });
})

```

## Expected behavior
The bot should mine the block

**Comment by rom1504** [comment]
You're starting your code too early. Spawn is before chunks are loaded

**Comment by recursivetree** [comment]
What should I use then? Anyways, this doesn't seem to be the problem, because it still finds a valid block position and walks to it.

**Comment by goncharovchik** [comment]
> - [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 
> 
> ## Versions
>  - mineflayer: 2.34.0
>  - server: vanilla
> 
> ## Detailed description of a problem
> I tried to build a bot which mines the closest block, but bot.dig doesn't work. It gets stuck in front of the block and it swings it's arms, but doesn't actually mine it.
> 
> This also affect mineflayer-pathfinder
> 
> ## What did you try yet?
> 
> I added a ton of debug logs
> 
> ## Your current code
> ```js
> const mineflayer = require('mineflayer')
> const { pathfinder, Movements } = require('mineflayer-pathfinder')
> const { GoalGetToBlock } = require('mineflayer-pathfinder').goals
> 
> botOptions = {
>     host: 'localhost',
>     port: 25565,
>     username: "miner"
> }
> 
> const bot = mineflayer.createBot(botOptions)
> bot.loadPlugin(pathfinder)
> 
> async function findAndMine(id){
>     const block = bot.findBlock({ matching: id, maxDistance: 32 })
>     if (block){
>         const promiseHack = new Promise((res,rej)=>{
>             bot.once('goal_reached', (goal) => {
>                 if (!bot.canDigBlock(block)){
>                     throw new Error("unable to reack block")
>                 }
>                 bot.dig(block,false)
>                 bot.once("diggingCompleted",(block)=>{
>                     res()
>                 })
>              })
>              bot.pathfinder.setGoal(new GoalGetToBlock(block.position.x, block.position.y, block.position.z))
>          })
>          await promiseHack
>          console.log("promise")
>          return
>     } else {
>         throw new Error("no block found")
>     }
> }
> bot.on("diggingAborted",(block)=>{
>     console.log("diggingAborted")
> })
> bot.on("diggingCompleted",(block)=>{
>     console.log("diggingCompleted")
> })
> 
> bot.once('spawn',() =>{
>     const mcData = require('minecraft-data')(bot.version)
>     const moves = new Movements(bot, mcData)
>     bot.pathfinder.setMovements(moves)
> 
>     const blockName = "log"
> 
>     const blockIds = mcData.blocksByName[blockName].id
> 
>     findAndMine(blockIds)
>     .catch(function(err){
>         console.log(err)
>     })
>     .then(function(){
>         console.log("done")
>         bot.quit()
>     });
> })
> 
> ```
> 
> ## Expected behavior
> The bot should mine the block
> 
> 

Hmm, I faced this problem too. But I never found a solution :(

**Comment by rom1504** [comment]
You can wait for chunks or just use a 20s set timeout

**Comment by recursivetree** [comment]
I tried all your suggestions, having a faster tool doesn't use anything and waiting doesn't use anything

**Comment by rom1504** [comment]
Does the digging example work for you ?

**Comment by recursivetree** [comment]
no, the example doesn't work either. It seems that everything points to bot.dig.

**Comment by rom1504** [comment]
Do you get the same result on 1.16.1 ?

**Comment by recursivetree** [comment]
I don't think this is resolved. Sorry, I didn't have time to test it in 1.16, i'll do it soon

**Comment by recursivetree** [comment]
I don't encounter this issue on 1.16.1

**Comment by introquest** [comment]
Possible relate to [this](https://github.com/PrismarineJS/mineflayer/issues/1555)

**Comment by introquest** [comment]
> Does the digging example work for you ?

In all the tutorials and all the examples, I noticed that they are testing on an "Open to LAN" server, in my case the behavior on the remote server is different(all i found was different `success` status in readed packet **play.acknowledge_player_digging**).

**Comment by Karang** [comment]
I tested your exact code on a vanilla 1.12.2 server and everything works as expected with `mineflayer@2.40.1` and `mineflayer-pathfinder@1.3.0`. Make sure your bot is not in the spawn protection radius (you can set `spawn-protection=0` in `server.properties`). Reopen if you sill have an issue.
