### ISSUE TITLE
how to get online players

### ISSUE THREAD

**Issue by ntloff** [PrismarineJS/mineflayer#1495]
how to get online players on de srver?

**Comment by goncharovchik** [comment]
use
```js
bot.players
```
Please fill out the template

**Comment by DrMoraschi** [comment]
`const playerList = Object.keys(bot.players).join(", ")

console.log(playerList)`

**Comment by goncharovchik** [comment]
> how to get online players on de srver?

Read the documentation and there will be no such questions

**Comment by ntloff** [comment]
> ```js
> const playerList = Object.keys(bot.players).join(", ")
> 
> console.log(playerList)
> ```
> 
> You can get faster replies in the Discord

D:\!minecraft\minecorp\minecorp.js:12
const playerList = Object.keys(bot.players).join(", ");
                               ^

ReferenceError: Cannot access 'bot' before initialization
    at Object.<anonymous> (D:\!minecraft\minecorp\minecorp.js:12:32)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by DrMoraschi** [comment]
Obviously after initialazing the bot

**Comment by DrMoraschi** [comment]
What?

**Comment by DrMoraschi** [comment]
Please move this to discord, and read the docs and the api before

**Comment by ntloff** [comment]
channel.setTopic("hi") is not working

**Comment by DrMoraschi** [comment]
Thats not even a mineflayer function, if its discord.js please ask it in the discord.js github

**Comment by goncharovchik** [comment]
> channel.setTopic("hi") is not working
> 

Please show the code for better help and understanding of the situation
