### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by PhoenixXKN** [PrismarineJS/mineflayer#1518]
I have read #509, but the fix provided there doesn't work for me either. I did check the password and email for typos, but there aren't any. My code is: ```js 
 let bot = mineflayer.createBot({
        host: "phoenixxkn.aternos.me",
        username:"my.email@provider.com",
        password: "correctPassword",
        port: 25565
    });
```
I also haven't received any mojang emails that something is wrong with my account, and logging in from the launcher works just fine, on the same computer.

**Comment by rom1504** [comment]
What error do you get ?

**Comment by PhoenixXKN** [comment]
```Error: Invalid credentials: Invalid username or password```

**Comment by goncharovchik** [comment]
> ```Error: Invalid credentials: Invalid username or password```

Try adding to the bot launch parameters  `auth: 'mojang'`

**Comment by rom1504** [comment]
This is the default, it won't do anything

**Comment by rom1504** [comment]
If you log out and log in in the launcher, does it still work ?

**Comment by PhoenixXKN** [comment]
> > `Error: Invalid credentials: Invalid username or password`
> 
> Try adding to the bot launch parameters `auth: 'mojang'`

This fixed it, thanks! Maybe this could be added into the api/tutorial/FAQs in some way?

**Comment by Kashalls** [comment]
Don't know how this fixed it. Changing that option has no effect on the code.
