### ISSUE TITLE
bot.openFurnace doesn't work with Smokers and Blast Furnaces

### ISSUE THREAD

**Issue by SoLegendary** [PrismarineJS/mineflayer#1526]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.37.1
 - server: vanilla 1.16.3
 - node: 6.14.8

## Detailed description of a problem

bot.openFurnace(furnaceBlock) doesn't work with specialised types of furnaces (blast furnaces and smokers)

## What did you try yet?

Placed down regular furnace, smoker and blast furnace but only the regular furnace returns a valid response while the others give the below error.

**EDIT: I can do a very hacky fix by manually renaming the Block object to 'furnace' from 'smoker' or 'blast_furnace' but this really isn't such a great long term solution**

**EDIT 2: This works to trigger the furnace.on() events but any methods like adding items/fuel won't work (no error but bot does nothing)**

## Your current code
```js
let furnaceBlock = bot.findBlock({
  matching: mcdata.blocksByName.blast_furnace.id,
  count: 1,
  maxDistance: 4,
})
let furnace = bot.openFurnace(furnaceBlock)
```
Something went wrong processing a chat command:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
```js
  assert.ok(furnaceBlock.name === 'furnace' || furnaceBlock.name === 'lit_furnace')
```

## Expected behavior
Expected it to return a Furnace object with all its usual methods like add fuel, check time etc.

## Additional context
I don't really mind if it fails to recognise what kind of items can be put in or not (eg. trying to use food in a blast furnace), I can easily handle that in my own code. I just want to be able to use them like regular furnaces.

**Comment by rom1504** [comment]
fixed
