### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by botboi37** [PrismarineJS/mineflayer#1552]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.39.2
 - server: vanilla/spigot/paper 1.16.4
 - node: 15.4.0

## Detailed description of a problem
I am simply trying to connect to a minecraft server.
"error" event fires immediately after calling createBot:
```
Error occurred: Error: self signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1508:34)
    at TLSSocket.emit (node:events:376:20)
    at TLSSocket._finishInit (node:_tls_wrap:942:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:716:12)
```

## What did you try yet?
I changed the host (for example mc.hypixel.net, etc) still receiving this error.
This problem is clearly not originating from the minecraft server host though, since if I input a random string as host, I still receive this error.

Did you try any method from the API? createBot
Did you try any example? Any error from those? this was almost entirely copied from the example

## Your current code
```js
var master = mineflayer.createBot({
        host: host, // these can be anything, nothing works
        port: 25565,
        username: "email@example.com",
        password: "12345678"
});
master.on("error", (e) => {
        console.log("Error occurred: " + e.message);
});
```

## Expected behavior
I expected to connect to the server

## Additional context
This error might be originating from my environment, since I see no other issues about this (except one, and that wasn't helpful since no solution was posted.)

**Comment by rom1504** [comment]
Are you connecting through some kind of proxy ?
The error is saying your connection to mojang auth is not secure

**Comment by botboi37** [comment]
Thanks for the suggestion, I realized I was indeed not connecting to the proper server because of my network settings, closing issue.
