### ISSUE TITLE
2.40.0 breaks Typescript compilation

### ISSUE THREAD

**Issue by hivivo** [PrismarineJS/mineflayer#1557]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.40.0
 - server: does not matter
 - node: 14.13.0
 - typescript: 4.1.3

## Detailed description of a problem

After bumping mineflayer from `2.39.2` to `2.40.0`, typescript compiler will report the error:

```
error TS2339: Property 'on' does not exist on type 'Bot'.
```

## What did you try yet?

Did you try any method from the API? N/A
Did you try any example? Any error from those? N/A

## Your current code

Any code with event listeners. such as:

```typescript
bot.on('error', err => console.log(err));
```

## Expected behavior

The code should compile.

## Additional context

May related with some changes about Bot interface?

**Comment by rom1504** [comment]
can you try to replace this line https://github.com/PrismarineJS/mineflayer/blob/master/index.d.ts#L143
by `export interface Bot extends TypedEmitter<BotEvents> {` and tell me if that improves on your issue ?
(in node_modules/mineflayer/index.d.ts)

**Comment by hivivo** [comment]
Yup! That fixes the issue! 👍
