### ISSUE TITLE
How to get face vector by sight 

### ISSUE THREAD

**Issue by goncharovchik** [PrismarineJS/mineflayer#1560]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer:  2.40.1
 - server: spigot 1.13.2
 - node: 14

## Clear question
How can I calculate `face vector` for `bot.placeBlock(referenceBlock, faceVector, cb)`, to place a block according to the bot's view.

## What did you try yet?

`bot.blockAtCursor()`
`bot.placeBlock(referenceBlock, faceVector, cb)`

## Your current code

-

## Additional context

-

**Comment by Karang** [comment]
Its an interesting question. We have everything to implement it but its not currently exposed.

If you look at the blockAtCursor implementation, its using the Raycast iterator (that is now exposed): https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/ray_trace.js#L19

You can implement your own version of blockAtCursor that also return the clicked face:
```js
bot.blockAtCursorCustom = (maxDistance = 256) => {
    const { position, height, pitch, yaw } = bot.entity

    const eyePosition = position.offset(0, height, 0)
    const viewDirection = getViewDirection(pitch, yaw)

    const iter = new RaycastIterator(eyePosition, viewDirection, maxDistance)
    let pos = iter.next()
    while (pos) {
      const block = bot.blockAt(new Vec3(pos.x, pos.y, pos.z))
      // TODO: Check boundingBox of block
      if (block && block.type !== 0) {
        block.face = pos.face // <<<<<<<<<<< Here is the added line
        return block
      }
      pos = iter.next()
    }
    return null
  }
```

Using this function you know which face was clicked https://github.com/PrismarineJS/prismarine-world/blob/master/src/iterators.js#L92 and you can convert it to a face vector

```js
const faceToDirection = [
new Vec3(0,-1,0), // BOTTOM
new Vec3(0,1,0), // TOP
new Vec3(0,0,-1), // NORTH
new Vec3(0,0,1), // SOUTH
new Vec3(-1,0,0), // WEST
new Vec3(1,0,0), // EAST
] // some directions might be inverted, i didnt checked

const block = bot.blockAtCursorCustom()
const face = block.face // the id of the clicked face
const dir = faceToDirection[face]
```

@rom1504 we should probably add this to mineflayer it can be useful

**Comment by goncharovchik** [comment]
> Its an interesting question. We have everything to implement it but its not currently exposed.
> 
> If you look at the blockAtCursor implementation, its using the Raycast iterator (that is now exposed): https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/ray_trace.js#L19
> 
> You can implement your own version of blockAtCursor that also return the clicked face:
> ```js
> bot.blockAtCursorCustom = (maxDistance = 256) => {
>     const { position, height, pitch, yaw } = bot.entity
> 
>     const eyePosition = position.offset(0, height, 0)
>     const viewDirection = getViewDirection(pitch, yaw)
> 
>     const iter = new RaycastIterator(eyePosition, viewDirection, maxDistance)
>     let pos = iter.next()
>     while (pos) {
>       const block = bot.blockAt(new Vec3(pos.x, pos.y, pos.z))
>       // TODO: Check boundingBox of block
>       if (block && block.type !== 0) {
>         block.face = pos.face // <<<<<<<<<<< Here is the added line
>         return block
>       }
>       pos = iter.next()
>     }
>     return null
>   }
> ```
> 
> Using this function you know which face was clicked https://github.com/PrismarineJS/prismarine-world/blob/master/src/iterators.js#L92 and you can convert it to a face vector
> 
> ```js
> const faceToDirection = [
> new Vec3(0,-1,0), // BOTTOM
> new Vec3(0,1,0), // TOP
> new Vec3(0,0,-1), // NORTH
> new Vec3(0,0,1), // SOUTH
> new Vec3(-1,0,0), // WEST
> new Vec3(1,0,0), // EAST
> ] // some directions might be inverted, i didnt checked
> 
> const block = bot.blockAtCursorCustom()
> const face = block.face // the id of the clicked face
> const dir = faceToDirection[face]
> ```
> 
> @rom1504 we should probably add this to mineflayer it can be useful

Thanks for the extended help!
