### ISSUE TITLE
Cant connect to server!

### ISSUE THREAD

**Issue by RomanBZK-dev** [PrismarineJS/mineflayer#1570]
Cant connect to server!
IP = mc.mstnw.net
PING IP = 104.24.113.85

From the client I can connect to the server, but through mineflayer it does not work.
Eternal waiting!

**Comment by Kashalls** [comment]
104.24.113.85 is an IP of Cloudflare. You will not be able to connect using 25565 to this IP because Cloudflare is proxying it. This is not an issue with mineflayer. (Also looks like they are using vBotfilter)

**Comment by Kashalls** [comment]
Doing a SRV Lookup, I can see the server has a SRV record. You will have to change the port. 
![image](https://user-images.githubusercontent.com/17620516/103699476-d63cf400-4f57-11eb-873c-0f8e0deb0603.png)

**Comment by Kashalls** [comment]
Mineflayer will not resolve it correctly because it does not pull the port. Change the port in your client options.

**Comment by RomanBZK-dev** [comment]
> 
> 
> Doing a SRV Lookup, I can see the server has a SRV record. You will have to change the port.
> ![image](https://user-images.githubusercontent.com/17620516/103699476-d63cf400-4f57-11eb-873c-0f8e0deb0603.png)

I changed the port, but there were no changes.
connection = Connection(
			'104.24.112.85', 25500, username='BotUser', allowed_versions=allowed_versions)
