### ISSUE TITLE
Thinks it broke block but doesn't (hinders pathfinding completely)

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer#1575]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.40.1
 - server: vanilla 1.16.4
 - node: v15.5.0

## Detailed description of a problem
The bot breaks a block (usually when strip mining at head level), thinks it's gone and then tries to walk into it (cause I am using collect-block), but it is still there server-side.
From the perspective of a player on the server the bot is obviously staying still, but from the prismarine-viewer side it shows that it thinks the block is gone.

## What did you try yet?

The only thing that helps is by manually breaking the block. I did not try to change the source code of the modules.

Maybe there is a packet that can get the block state/type of a single block?

## Your current code
```js

//It is very big including the mineflayer viewer and stuff, but here is the only problem executing code, basically the collect-block example:

if (args[0] === 'collect') {
        let count = 1
        if (args.length === 3)
            count = parseInt(args[1])

        let type = args[1]
        if (args.length === 3)
            type = args[2]

        const blockType = mcData.blocksByName[type]
        if (!blockType) {
            bot.chat("I don't know any blocks with that name: " + type)
            return
        }

        const blocks = bot.findBlocks({
            matching: blockType.id,
            maxDistance: 64,
            count: count
          })
        
          if (blocks.length === 0) {
            bot.chat("I don't see that block nearby.")
            return
          }
        
          const targets = []
          for (let i = 0; i < Math.min(blocks.length, count); i++) {
            targets.push(bot.blockAt(blocks[i]))
          }
        
          bot.chat(`Found ${targets.length} ${type}(s)`)
        
          collect = targets

          bot.collectBlock.collect(collect, err => {
            if (err) {
              // An error occurred, report it.
              bot.chat(err.message)
              console.log(err)
              collect = undefined
            } else {
              // All blocks have been collected.
              bot.chat('Done')
              collect = undefined
            }
          })
    }


```

## Expected behavior
I expect the bot to recognise that it did not break the block.
While at it, I don't know about for example spawn protection block break recognition, but this could also be added if it makes sense to combine these things.

## Additional context
Thank you for your great module, it is undescribable cool and capable!

**Comment by Karang** [comment]
May be related to #1555

**Comment by u9g** [comment]
can be closed because the pr in mineflayer-collectblock was merged

**Comment by pyth0nic** [comment]
Still an issue in the latest version.

**Comment by rom1504** [comment]
open an issue in mineflayer collectbot
