### ISSUE TITLE
Cant login in microsoft account 

### ISSUE THREAD

**Issue by Shiiiwa** [PrismarineJS/mineflayer#1577]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: ^2.40.1
 - server: vanilla/spigot/paper 1.8.8
 - node: 14.13.1

## Detailed description of a problem
I´ve bought an new Minecraft account, which belongs to an microsoft account. Now I cant login to my minecraft account with 
`mineflayer.createBot({...});` as usually. It keeps telling me, that a module is could not be found.
So I tried the following :

## What did you try yet?
```
 const bot = mineflayer.createBot({
    host: "example.net", 
    port: 25565,
    auth: 'microsoft',
    username: "email",
    password: "password",
}); 
```
 
Here is my package.json : 
```
{
  "name": "Bot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mineflayer": "^2.40.1"
  }
}
```

Every time I want to start the bot there is this errror:
```
Error: Cannot find module 'c:\Users\User\Desktop\Bot\node_modules\@xboxreplay\xboxlive-auth\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:344:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:557:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:911:27)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (c:\Users\Marco\Desktop\adada\node_modules\minecraft-protocol\src\client\microsoftAuth.js:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'c:\\Users\\User\\Desktop\\Bot\\node_modules\\@xboxreplay\\xboxlive-auth\\package.json',
  requestPath: `'@xboxreplay/xboxlive-auth'`
```

I tried to delete the node_module folder and package-lock.json file and reinstall mineflayer: 
```
npm i mineflayer

added 66 packages, and audited 67 packages in 2s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

But it keeps telling the same error.

**Comment by rom1504** [comment]
Update your dependencies

**Comment by Shiiiwa** [comment]
@rom1504 I´´ve updated my issue

**Comment by extremeheat** [comment]
Delete the node_modules folder and run npm install again

**Comment by Shiiiwa** [comment]
> Delete the node_modules folder and run npm install again

Done and telling the same error as before.

**Comment by Karang** [comment]
https://github.com/XboxReplay/xboxlive-auth/commits/master was just updated and seems to have been wrongly exported to npm

**Comment by DrMoraschi** [comment]
It should be fixed now.

https://github.com/XboxReplay/xboxlive-auth/issues/11

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/791#issuecomment-757367628

**Comment by MikeMottonix** [comment]
I have the same problem and want to know in which ways i can now join with my Microsoft-account, because i dont know if theres a solution now or not. Im very unsettled right now.

**Comment by rom1504** [comment]
Feel free to contribute to the issue I mentioned above

**Comment by Kashalls** [comment]
This issue should be closed now as the issue has been fixed in the library. https://github.com/XboxReplay/xboxlive-auth/issues/11

**Comment by rom1504** [comment]
I don't see any fix for this issue in the issue from xboxlive-auth that you're linking

**Comment by brainTrain** [comment]
I'm having this issue regularly, it intermittently works. Is this still an open issue or is it an issue with the xbox auth api?

my output:
```
Unable to authenticate with Microsoft XboxReplayError: Invalid credentials.
    at Object.unauthorized (/home/mcbot/github/brainsevenrain/mind-the-bot/node_modules/@xboxreplay/errors/dist/index.js:25:74)
    at /home/mcbot/github/brainsevenrain/mind-the-bot/node_modules/@xboxreplay/xboxlive-auth/dist/core/live/index.js:71:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  __XboxReplay__: true,
  details: { statusCode: 401, reason: 'UNAUTHORIZED' }
}
Retrying auth with device code flow
```

**Comment by extremeheat** [comment]
@brainTrain you can ask this question on the discord. As for your error specifically, you can ignore it or remove it by omitting the password field in your bot createBot options.

**Comment by brainTrain** [comment]
@extremeheat sorry but I can't seem to find a discord link on either https://prismarine.js.org/ or https://mineflayer.prismarine.js.org/#/ is there somewhere else I should look for a discord link?

**Comment by Kashalls** [comment]
@brainTrain Here you go: https://discord.gg/xFPPmYEV Link expires in 7 days from now.

**Comment by brainTrain** [comment]
@Kashalls thank you so much!

**Comment by WaterNewt423976** [comment]
hey @Kashalls can you please send a new link the link has expired.

**Comment by Kashalls** [comment]
> hey @Kashalls can you please send a new link the link has expired.

What if I told you it was in the readme. Has a big ol button that says discord.
