### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by MoonVN571** [PrismarineJS/mineflayer#1579]
*\node_modules\mineflayer\lib\plugins\inventory.js:467
    while (actionId > click.id) {
                            ^

TypeError: Cannot read property 'id' of undefined
    at confirmTransaction (*\node_modules\mineflayer\lib\plugins\inventory.js:467:29)
    at Client.<anonymous> (*\node_modules\mineflayer\lib\plugins\inventory.js:568:5)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (*\node_modules\minecraft-protocol\src\client.js:89:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (*\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (*\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (*\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (*\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (*\node_modules\protodef\src\serializer.js:89:10)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js#L460 that is not possible with that last code.
Is your mineflayer up to date ?

**Comment by MoonVN571** [comment]
> https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js#L460 that is not possible with that last code.
> Is your mineflayer up to date ?

Im use node install mineflayer for it, thanks you

**Comment by Karang** [comment]
The test line 460 have been there for a while + the code at line 467 is matching the latest version. However as rom stated, this error shouldn't be possible. Can you go in your `\node_modules\mineflayer\lib\plugins\inventory.js` and copy here the code of the function confirmTransaction ? https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js#L456

**Comment by Karang** [comment]
@rom1504 ah I got what might be happening:
```js
while (actionId > click.id) {
      onAccepted()
      click = windowClickQueue.shift()
    }
```
click get redefined in the loop and not tested for undefined again.

**Comment by MoonVN571** [comment]
> @rom1504 ah I got what might be happening:
> 
> ```js
> while (actionId > click.id) {
>       onAccepted()
>       click = windowClickQueue.shift()
>     }
> ```
> 
> click get redefined in the loop and not tested for undefined again.

lemme try

**Comment by rom1504** [comment]
Ah yeah actually I don't get how these lines work at all, in the end shift always return undefined

**Comment by MoonVN571** [comment]
> Ah yeah actually I don't get how these lines work at all, in the end shift always return undefined

mhmmm

**Comment by Karang** [comment]
Vanilla doesn't send unknown transaction confirmations so its not very surprising that this code is untested.

**Comment by MoonVN571** [comment]
> Vanilla doesn't send unknown transaction confirmations so its not very surprising that this code is untested.

i can use this but sometime it error

**Comment by rom1504** [comment]
Yeah so the solution is clear, just add an undefined check in that loop
