### ISSUE TITLE
Add entity.visible

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1581]
## Is your feature request related to a problem? Please describe.
https://github.com/PrismarineJS/prismarine-entity/issues/14#issue-782513032

## Describe the solution you'd like
https://github.com/PrismarineJS/prismarine-entity/issues/14#issuecomment-757100278

## Describe alternatives you've considered
I don't think there are any?

## Additional context
https://github.com/PrismarineJS/prismarine-entity/issues/14

**Comment by rom1504** [comment]
Prismarine-entity is indeed the right place for this
