### ISSUE TITLE
EventEmitter overflow

### ISSUE THREAD

**Issue by Rob9315** [PrismarineJS/mineflayer#1585]
## Is your feature request related to a problem? Please describe.
When using mineflayer-pathfinder, it adds a listener to blockupdates, when these blockupdates don't happen because e.g. an entity blocks the placement, the listener remains and causes too many EventEmitters

## Describe the solution you'd like
I would like for mineflayer to have a timeout on the blockupdate listeners, so that they are removed automatically if not activated to prevent this kind of eventemitter overflow that can crash bots after some time

## Describe alternatives you've considered
changing the pathfinding myself with a statemachine, adding a listener to check if the blockplace or break is rejected

## Additional context
this happens in cases, when multiple bots try to pathfind on top of each other. they get stuck when trying to place a block below 
(which is not the problem) and attach a listener each time they retry. if these listeners were to get deleted automatically to prevent them from crashing, that would be great

**Comment by rom1504** [comment]
I guess that would be solved by your new place block idea @Karang (would be good if you can describe what we said about that in discord in a mineflayer issue)

**Comment by Karang** [comment]
Hmm, yes and no. It would eliminate most of the cause by not registering the event and returning early if the client guessed it's not possible to place a block, but there could still be some issues. IMO the right way to fix it is to force having only 1 listener active at a time. (Meaning if a player call placeblock again it either fail or replace the current active listener).

**Comment by Roizor** [comment]
(I do but don't recommend this)
I hack-fix it by adding `const events = require('events').EventEmitter.defaultMaxListeners = Infinity`

**Comment by Rob9315** [comment]
that does not solve the issue of the Listeners using resources, which slows the program significantly down in my case, though I do have my own 'hack-fix' for the time being. Will still try to push a proper fix like [suggested in discord ](https://discord.com/channels/413438066984747026/671423547541028884/795380060496068628) to resolve this issue properly

**Comment by Rob9315** [comment]
[issue moved](https://github.com/PrismarineJS/mineflayer/issues/1589)
