### ISSUE TITLE
How do I get a complete list of players and their donations?

### ISSUE THREAD

**Issue by goncharovchik** [PrismarineJS/mineflayer#1593]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 3.40.1
 - server: spigot, bungee 1.16.4
 - node: 15

## Clear question
How can I get a complete list of players with their donations (suffixes and prefixes)? 
In the launcher, you can see all this by pressing key `Tab`

## What did you try yet?
-

## Your current code
-

## Additional context
-

**Comment by Rob9315** [comment]
what you are looking for is probably `bot.players` to get a list of all players, the ones which would be displayed on a tablist in a minecraft client

**Comment by goncharovchik** [comment]
> what you are looking for is probably `bot.players` to get a list of all players, the ones which would be displayed on a tablist in a minecraft client

This will only give out nicknames, but I need to get prefixes and suffixes.

**Comment by imharvol** [comment]
What about **displayName**: `bot.players[player].player.displayName`?

**Comment by goncharovchik** [comment]
> What about **displayName**: `bot.players[player].displayName`?
> 
> If not, I would try to debug the packet `player_info` https://wiki.vg/Protocol#Player_Info
> ```js
> bot._client.on('player_info', (packet) => {
>   console.log(packet)
> }
> ```
> I think the name including the name including suffixes and prefixes should be contained there

thanks!
