### ISSUE TITLE
multi-line messages and group them together

### ISSUE THREAD

**Issue by shketov** [PrismarineJS/mineflayer#1596]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
mineflayer: 2.40.1
server: vanilla/spigot/paper spigot 1.12.2
node: 14.15.4

## Clear question
Is it possible to implement multi-line messages in one object?
I.e. a message that has a multi-line view sends one line of this message to one ChatMessage object. Because of this, when using the VK/Discord/Telegram <=> bridge, the Minecraft server, when entering a command that returns a multi-line message, sends several messages to the user in the dialog (depending on the number of message lines )
Example:
Single server message of the form
```
Guilds| Top 5 players:
#1 - Player1, invested in the guild 5 coins
#2 - Player2 , invested in the guild 4 coins
#3 - Player3, invested in the guild 3 coins
#4 - Player4, invested in the guild 2 coins
#5 - Player5, invested in the guild 1 coins
```
Returns 6 objects where 1 object is 1 message string
1 object -``` Guilds| Top 5 players:```
2 object - ```#1 - Player1, invested in the guild 5 coins ``` 
3 object - ``` #3 - Player3, invested in the guild 3 coins ``` etc.

What I want it to look like:
1 object - 
```
Guilds| Top 5 players:
#1 - Player1, invested in the guild 5 coins
#2 - Player2 , invested in the guild 4 coins
#3 - Player3, invested in the guild 3 coins
#4 - Player4, invested in the guild 2 coins
#5 - Player5, invested in the guild 1 coins
```

As a regular user sees it in VK (6 messages are sent to him)
![image](https://user-images.githubusercontent.com/56227259/104913145-3db66300-599e-11eb-9b46-ef3e01018caa.png)

I wish I could see it: (one message instead of 6)
![image](https://user-images.githubusercontent.com/56227259/104913316-79512d00-599e-11eb-8de8-e27d2cff14fc.png)

**Comment by goncharovchik** [comment]
> - [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
> - [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
> - [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.
> 
> 
> 
> ## Versions
> mineflayer: 2.40.1
> server: vanilla/spigot/paper spigot 1.12.2
> node: 14.15.4
> 
> ## Clear question
> Is it possible to implement multi-line messages in one object?
> I.e. a message that has a multi-line view sends one line of this message to one ChatMessage object. Because of this, when using the VK/Discord/Telegram <=> bridge, the Minecraft server, when entering a command that returns a multi-line message, sends several messages to the user in the dialog (depending on the number of message lines )
> Example:
> Single server message of the form
> ```
> Guilds| Top 5 players:
> #1 - Player1, invested in the guild 5 coins
> #2 - Player2 , invested in the guild 4 coins
> #3 - Player3, invested in the guild 3 coins
> #4 - Player4, invested in the guild 2 coins
> #5 - Player5, invested in the guild 1 coins
> ```
> Returns 6 objects where 1 object is 1 message string
> 1 object -``` Guilds| Top 5 players:```
> 2 object - ```#1 - Player1, invested in the guild 5 coins ``` 
> 3 object - ``` #3 - Player3, invested in the guild 3 coins ``` etc.
> 
> What I want it to look like:
> 1 object - 
> ```
> Guilds| Top 5 players:
> #1 - Player1, invested in the guild 5 coins
> #2 - Player2 , invested in the guild 4 coins
> #3 - Player3, invested in the guild 3 coins
> #4 - Player4, invested in the guild 2 coins
> #5 - Player5, invested in the guild 1 coins
> ```

Hello. I would advise you to use a function that accumulates messages in one lowercase n and poisons them through the bot every 2 seconds.
