### ISSUE TITLE
Project funding

### ISSUE THREAD

**Issue by flowl** [PrismarineJS/mineflayer#1597]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2442%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/PrismarineJS/mineflayer/issues/1597)

Donation to mineflayer, choose any PR.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $42.00)

- [<img src='https://avatars2.githubusercontent.com/u/4543262?v=4' alt='flowl' width=24 height=24> flowl](https://issuehunt.io/u/flowl) ($15.00)
- [<img src='https://avatars.githubusercontent.com/u/25093857?v=4' alt='theycallmelinux' width=24 height=24> theycallmelinux](https://issuehunt.io/u/theycallmelinux) ($25.00)
- [<img src='https://avatars.githubusercontent.com/u/32192232?v=4' alt='nyaasu66' width=24 height=24> nyaasu66](https://issuehunt.io/u/nyaasu66) ($2.00)

### Submitted pull Requests
- [#434 Add 1.17.1 protocol.json](https://issuehunt.io/r/PrismarineJS/minecraft-data/pull/434)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PrismarineJS/mineflayer/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by rom1504** [comment]
closing that now, for general donations please use https://github.com/sponsors/PrismarineJS
