### ISSUE TITLE
Still: "Invalid credentials" when credentials are fine.

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer#1599]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: lts
 - server: vanilla/spigot/paper 1.16.4
 - node: lts

## Detailed description of a problem
"Invalid credentials. Invalid username or password."
Comes with totally fine credentials. I even logged in seconds before trying the bot.

## What did you try yet?

console.log the username and password -> no success

## Your current code
```js

let bot = mineflayer.createBot({
    host: argv.host,
    port: argv.port,
    username: argv.username,
    password: argv.password
})


```

## Expected behavior
It should log in normally.

## Additional context
/

**Comment by DrMoraschi** [comment]
Its process.argv[ ]

**Comment by SinanAkkoyun** [comment]
> Its process.argv[ ]

No, that's not the point. I am using yargs.

```js
var argv = require('yargs/yargs')(process.argv.slice(2)).argv;
```

**Comment by SinanAkkoyun** [comment]
I am even displaying the credentials, copying them as is into my launcher and there they work.

**Comment by SinanAkkoyun** [comment]
Oh wow, I forgot to delete whitespaces hahah

```js
str.replace(/\s+/g, '')
```
