### ISSUE TITLE
Chataddpattern fails in chatAddPattern.js example

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1602]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?
i don't really know what I would try

Did you try any method from the API?
yeah, the chataddpattern
Did you try any example? Any error from those?
it was the example that doesnt work

## Your current code
https://github.com/PrismarineJS/mineflayer/blob/master/examples/chatAddPattern.js

## Expected behavior
It works

## Additional context
error:
```
TypeError: bot.chatAddPattern is not a function
    at Object.<anonymous> (C:\Users\---\Documents\git-projs\prismarinejs\mineflayer\examples\chatAddPattern.js:31:5)
```

**Comment by rom1504** [comment]
You need to use it in spawn event
