### ISSUE TITLE
Bot connects for a second before timing out

### ISSUE THREAD

**Issue by Hadimhz** [PrismarineJS/mineflayer#1606]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.40.1
 - server: vanilla 1.6.4
 - node: v14.15.4
 
## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?

Did you try any method from the API? 
haven't experienced with the API yet
Did you try any example? Any error from those?
i tried the example in the README

## Your current code
```js

const mineflayer = require('mineflayer');

const bot = mineflayer.createBot({
    host: 'ip',
    username: 'Email',
    password: 'pass',
})

bot.on('chat', function (username, message) {
    if (username === bot.username) return
    bot.chat(message)
})

bot.on('kicked', (reason, loggedIn) => console.log(reason, loggedIn))

bot.on('error', err => console.log(err))


```

## Expected behavior
Bot to login and stay online 
## Additional context

Bot returns 
```TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined```

**Comment by tascord** [comment]
Reproducing on 1.16.5.

**Comment by goncharovchik** [comment]
> - [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 
> 
> ## Versions
>  - mineflayer: 2.40.1
>  - server: vanilla 1.6.4
>  - node: v14.15.4
>  
> ## Detailed description of a problem
> A clear and concise description of what the problem is, with as much context as possible.
> What are you building? What problem are you trying to solve?
> 
> ## What did you try yet?
> 
> Did you try any method from the API? 
> haven't experienced with the API yet
> Did you try any example? Any error from those?
> i tried the example in the README
> 
> ## Your current code
> ```js
> 
> const mineflayer = require('mineflayer');
> 
> const bot = mineflayer.createBot({
>     host: 'ip',
>     username: 'Email',
>     password: 'pass',
> })
> 
> bot.on('chat', function (username, message) {
>     if (username === bot.username) return
>     bot.chat(message)
> })
> 
> bot.on('kicked', (reason, loggedIn) => console.log(reason, loggedIn))
> 
> bot.on('error', err => console.log(err))
> 
> 
> ```
> 
> ## Expected behavior
> Bot to login and stay online 
> ## Additional context
> 
> Bot returns 
> ```TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined```
> 

What do you write in the field `host` ?

**Comment by goncharovchik** [comment]
> - [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 
> 
> ## Versions
>  - mineflayer: 2.40.1
>  - server: vanilla 1.6.4
>  - node: v14.15.4
>  
> ## Detailed description of a problem
> A clear and concise description of what the problem is, with as much context as possible.
> What are you building? What problem are you trying to solve?
> 
> ## What did you try yet?
> 
> Did you try any method from the API? 
> haven't experienced with the API yet
> Did you try any example? Any error from those?
> i tried the example in the README
> 
> ## Your current code
> ```js
> 
> const mineflayer = require('mineflayer');
> 
> const bot = mineflayer.createBot({
>     host: 'ip',
>     username: 'Email',
>     password: 'pass',
> })
> 
> bot.on('chat', function (username, message) {
>     if (username === bot.username) return
>     bot.chat(message)
> })
> 
> bot.on('kicked', (reason, loggedIn) => console.log(reason, loggedIn))
> 
> bot.on('error', err => console.log(err))
> 
> 
> ```
> 
> ## Expected behavior
> Bot to login and stay online 
> ## Additional context
> 
> Bot returns 
> ```TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined```
> 

Try adding a field `Port` in the parameters. Can you tell the server ip?

**Comment by DEVTomatoCake** [comment]
Can confirm for 1.16.5

Fix for me was to set "version" to 1.16.4 instead of false or 1.16.5

**Comment by tascord** [comment]
Yep! Seems like something weird with the 1.16.5 internals. Changing to 1.16.4 seems to fix the issue.

**Comment by actualdankcoder** [comment]
also reproduced in 1.16.5, changing to 1.16.4 fixed this issue

**Comment by u9g** [comment]
Is anyone still having trouble with this?

**Comment by Hadimhz** [comment]
changing to 1.16.4 seems to fix the problem.
