### ISSUE TITLE
How to use the bot.clickwindow 

### ISSUE THREAD

**Issue by im-moies** [PrismarineJS/mineflayer#1608]
Okay so I’m making a bot to trade using guis and I can open the GUI but for clicking items kinda like hovering over them in inventory then clicking which I do bot.clickwindow but idk which numbers go where and if I change which numbers to select which slots

**Comment by goncharovchik** [comment]
> Okay so I’m making a bot to trade using guis and I can open the GUI but for clicking items kinda like hovering over them in inventory then clicking which I do bot.clickwindow but idk which numbers go where and if I change which numbers to select which slots

Show screenshot of the window.

**Comment by u9g** [comment]
Have you considered getting the slot of the item based on the querying the window? I made a simple example where I left click on the first boat in a window. 
```js
bot.on('windowOpen', (window) => {
    const boats = window.slots
      .filter(x => x != null)
      .filter(x => x.displayName === 'Oak Boat')
    const mouseButton = 0 // 0: left click, 1: right click
    const mode = 0 // 0: single click
    bot.clickWindow(boats[0].slot, mouseButton, mode)
  })
```

Reference: 
- displayName: [here](https://minecraft-data.prismarine.js.org/) (make sure to specify what version you are playing on at the top)
- windowOpen event: [here](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botclickwindowslot-mousebutton-mode-cb)
- click types: [here](https://wiki.vg/Protocol#Click_Window) (only click mode 0 and mouse buttons 0, 1 are supported as of now)
