### ISSUE TITLE
Gets banned on hypixel when trying to placeBlock

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer#1610]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest release
 - server: vanilla/spigot/paper 1.16.4
 - node: lts

## Detailed description of a problem
Disclaimer: I suspected this will happen BUT:

The bot just gets banned when trying to stack up. He is not even placing blocks somewhere where his crosshair is not (cause when towering he should place the crosshair where it belongs)

I saw that he could not look down to the block.

Is there a way I could improve things like adding a smoothing or even lerping to the aim, I mean could you please provide me the source files where to look for?

Thank you so much, when I gave him proper head movement AND legit bridging (will do myself if nobody has a base ofc) I will also do a pull request!

## What did you try yet?

/

## Your current code
```js

/*
the basic pathfinder example GoalFollow
*/


```

## Expected behavior
Rotate head smoothly if thats the issue?

## Additional context
/

**Comment by satyamedh** [comment]
@SinanAkkoyun  mineflayer doesn't mimic a java client entirely, maybe it misses some packets and watchdog adds it to the ban list. 
also bots are against hypixel's tos. so dont try it.

**Comment by SinanAkkoyun** [comment]
> @SinanAkkoyun  mineflayer doesn't mimic a java client entirely, maybe it misses some packets and watchdog adds it to the ban list. 
> also bots are against hypixel's tos. so dont try it. 

Well, I thought sending the placeblock and swing packet is enough, innt?

I thought this has to do with the rapid head movement or something, if somebody has a clue whats going on please tell me!

**Comment by satyamedh** [comment]
@SinanAkkoyun its probably just that mineflayer is a missing a packet that isnt coded into it ATM, head movement is very smooth Right now!

**Comment by SinanAkkoyun** [comment]
> @SinanAkkoyun its probably just that mineflayer is a missing a packet that isnt coded into it ATM, head movement is very smooth Right now!

Thank you, I'll look into the decoded source code of MC, maybe I'll find something :)

**Comment by imharvol** [comment]
> > @SinanAkkoyun its probably just that mineflayer is a missing a packet that isnt coded into it ATM, head movement is very smooth Right now!
> 
> Thank you, I'll look into the decoded source code of MC, maybe I'll find something :)

I also recommend you that you enter to Hypixel with a vanilla client through a mineflayer proxy so you can see exactly which packets are being sent by the vanilla client and try to replicate it in your code

Keep in mind that I don't know if entering through a mineflayer proxy could cause problems or even get you banned

**Comment by SinanAkkoyun** [comment]
> > > @SinanAkkoyun its probably just that mineflayer is a missing a packet that isnt coded into it ATM, head movement is very smooth Right now!
> > 
> > Thank you, I'll look into the decoded source code of MC, maybe I'll find something :)
> 
> I also recommend you that you enter to Hypixel with a vanilla client through a mineflayer proxy so you can see exactly which packets are being sent by the vanilla client and try to replicate it in your code
> 
> Keep in mind that I don't know if entering through a mineflayer proxy could cause problems or even get you banned

Oh, thank you for that suggestion, I didn't even know that a mineflayer proxy exists!

If it contains the looked for packet but just doesnt send it when building, I should be fine.

I will try it 😉

**Comment by SinanAkkoyun** [comment]
@imharvol Please provide me with the mineflayer proxy

**Comment by Karang** [comment]
PrismarineJS/node-minecraft-protocol/examples

**Comment by imharvol** [comment]
Right, it's the one Katanga says. Keep in mind that it has `'online-mode': false`, that's something you need to change. Also you need to specify the account's password

**Comment by SinanAkkoyun** [comment]
I will try the proxy example later, thank you guys!

**Comment by Roizor** [comment]
> @SinanAkkoyun mineflayer doesn't mimic a java client entirely, maybe it misses some packets and watchdog adds it to the ban list.
> also bots are against hypixel's tos. so dont try it.

bots are allowed
but only chat bots. no spam, only utility chat bots (example: a bot in a housing)
