### ISSUE TITLE
How get crossbow is charged?

### ISSUE THREAD

**Issue by sefirosweb** [PrismarineJS/mineflayer#1615]
- [X] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [X] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [X] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Clear question
How I can get if the item crossbow is charged?

## Your current code

For a now i have this code, for get if held item crossbow is charged, and seems works fine, but i'm not sure if are the "correct" way to get this info
![Screenshot_23](https://user-images.githubusercontent.com/20754836/105628159-8e650a80-5e3b-11eb-8f31-4869b63596fb.png)
![Screenshot_24](https://user-images.githubusercontent.com/20754836/105628163-8f963780-5e3b-11eb-8279-2e7cf757fa40.png)

```js
    if ($weapon === 'crossbow') {
        if (
          // Detects if crossbow is charged
          bot.heldItem.nbt.value.ChargedProjectiles &&
          bot.heldItem.nbt.value.ChargedProjectiles.value.value[0] &&
          bot.heldItem.nbt.value.ChargedProjectiles.value.value[0]['id']['value']) {
          bot.activateItem()
        } else {
          // Disable click for charge the bow
          bot.deactivateItem()
          return // Wait until next physicTick for shot
        }
      }

```

**Comment by u9g** [comment]
`Boolean(bot.heldItem.nbt.value.Charged.value === 1)` will tell you if the crossbow is charged, but it will only tell you if you first `bot.activateItem()`, wait 25 ticks, then `bot.deactivateItem()`. If you only ran `bot.activateItem()`, charged will still be 0, but you can run `bot.activateItem()` again, it doesn't cause issues. An example of fully firing a crossbow is available here: https://github.com/PrismarineJS/mineflayer/pull/1695

**Comment by sefirosweb** [comment]
Thanks @ u9g, so I look bad variable,

I'd rather do a more dynamic check than wait 25 ticks, because the crossbow can have an enchantment and can recharge faster,

I will check every tick of the game if the crossbow is charged or not,

Best!

**Comment by sefirosweb** [comment]
Hi @u9g  i'm try to optimize, 

I see "bot.heldItem.nbt.value.Charged.value" only returns if arrow is charged in crossbow, but no returns if is "ready" for shot,

For a now I check if crosswbow have enchant and i reduce the time in 0.25s for each enchant,

** Now is a machine gun :D (with enchant 5 is instan shots!)

** I make soon a PR un your example of crossbow =P

```js
function shotCrossbow() {
  if (chargingArrow) {
    bot.activateItem()
    bot.deactivateItem()
    chargingArrow = false
    preparingShot = false
    return
  }

  if (bot.heldItem === null) {
    stop()
    return
  }
  const isEnchanted = bot.heldItem.nbt.value.Enchantments.value.value.find(enchant => {
    return enchant.id.value === 'quick_charge'
  })

  const shotIn = 1250 - ((isEnchanted ? isEnchanted.lvl.value : 0) * 250)

  if (weapon === 'crossbow' && !chargingArrow && Date.now() - preparingShotTime > shotIn) {
    bot.deactivateItem()
    chargingArrow = true
    return
  }
}
```
