### ISSUE TITLE
Authentication Mojang doesnt throw error

### ISSUE THREAD

**Issue by peter12908** [PrismarineJS/mineflayer#1616]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.40.1
 - server: spigot 1.8.8
 - node: latest

## Detailed description of a problem
When i am using mojang authenticate and put an email and password which arent correct it doesnt give me an error and the bot doesnt join.

## What did you try yet?
I manuelly tried setting hideErrors to false but even when i do that i dont get an error

## Your current code
```js

/*
const bot = mineflayer.createBot({
  host: 'localhost', // optional
  port: 25565,       // optional
  username: 'email@example.com', // email and password are required only for
  password: '12345678',          // online-mode=true servers
  version: false,                 // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
  auth: 'mojang'      // optional; by default uses mojang, if using a microsoft account, set to 'microsoft'
})
*/


```

**Comment by rom1504** [comment]
did you use bot.on('error', err => console.log(err)) ?

**Comment by peter12908** [comment]
thank you it worked
