### ISSUE TITLE
Dropping full inventory

### ISSUE THREAD

**Issue by legendary-cookie** [PrismarineJS/mineflayer#1622]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper 1.16.4
 - node: #.#.#

## Clear question
Im trying to let my fishingbot drop its inventory and only the fishingrod should stay in it. The gist from the FAQ didn't work as I would like it to do and I don't know how to accomplish that...
I searched through older issues but didn't find any answer
## What did you try yet?

Did you try any method from the API?
yes, bot.tossStack
Did you try any example? Any error from those?
I did try an example but I need to drop the inventory and not only a certain item.
## Your current code

Please put here any custom code you tried yet.

```js

// drop inv
  if (message === 'drop') {
    bot.inventory.items().forEach(item => {
      if(item.name!="fishing_rod") bot.tossStack(item)
      console.log("trying to toss item: " + item.name)
      wait(1000)
    });
  }
// this is from an older issue, I tested some things but didn't manage to get it work
```

**Comment by legendary-cookie** [comment]
The gist returns "Error: missing source item [object Object]:() => dropper(i + 1) in (9,45)" any way to fix that?

**Comment by sefirosweb** [comment]
You can try with promises? instead of using a wait in bucle

Calling itself until all items is dropped

*also with this can you drop a lot of faster the items =)

**Comment by sefirosweb** [comment]
Example I added on my bot:

```js
  function dropAll () {
    const excludedItems = ['fishing_rod']
    const item = bot.inventory.items().find(item => !excludedItems.includes(item.name))
    if (item) {
      bot.tossStack(item)
        .then(() => {
          setTimeout(dropAll)
        })
        .catch(err => {
          console.log(err)
          setTimeout(dropAll, 100)
        })
    }
  }
```

**Comment by legendary-cookie** [comment]
Thanks! Got it working now
