### ISSUE TITLE
bot.getDirection()?

### ISSUE THREAD

**Issue by satyamedh** [PrismarineJS/mineflayer#1629]
## Is your feature request related to a problem? Please describe.
Its so irritating, Im bad at math, and ant to get what the bot is facing. radiants, degrees i am not good at all that. is there a way to just add a bot.getDirection?

## Describe the solution you'd like
Bot.getDirection()
returns north west east south depending on what direction the bot is looking at

## Describe alternatives you've considered
bot.entity.yaw and calculate it, but it isnt working ATM

## Additional context
idek

**Comment by sefirosweb** [comment]
In wich example you need know to where is looking at?

If you want to force looking at direction you can use  bot.look(yaw, pitch)
or bot.lookAt(position) // Position is vec3 variable type

**Comment by satyamedh** [comment]
It isn't a example, I'm writing my own code, that code works, but the
question is to get the direction the bot is looking at!

**Comment by imharvol** [comment]
Neither do I understand how yaw and pitch works. For this purpose I usually get into Minecraft press F3 and take note of which pitch and yaw are shown when I'm looking at each cardinal, then I just hardcode them into my code.

Though I agree this would be a great feature and easy to implement.

**Comment by satyamedh** [comment]
Hahahahahahha it's not that, it's in radians first of all and then it just
increases to infinity after 180 instead of wrapping back to -180


Check my other issue #1628

**Comment by sefirosweb** [comment]
You can convert degrees to radians

=P

```js
function degreesToRadians (degrees) {
  const pi = Math.PI
  return degrees * (pi / 180)
}

function radiansToDegrees (radians) {
  const pi = Math.PI
  return radians * (180 / pi)
}
```

I think lookAt use similar formula,
```js
function getTargetYaw (origin, destination) {
  const xDistance = destination.x - origin.x
  const zDistance = destination.z - origin.z
  const yaw = Math.atan2(xDistance, zDistance) + Math.PI
  return yaw
}
```

For pitch is same but chaning to Y position
bot.look(yaw, pitch)

**Comment by satyamedh** [comment]
I tried it but didn't understand it not it worked. Check #1628

But still it would be helpful if the command was added

**Comment by extremeheat** [comment]
Here’s some code I wrote earlier to get the cardinals,

untested in mc,
```js
let getCardinal = (degrees) => ["N", "NE", "E", "SE", "S", "SW", "W", "NW"][(degrees / 45) & 0x7]
let degrees = (radians * 180 / Math.PI) - 180
let cardinal = getCardinal(degrees)
```

where radians is the bots facing yaw
