### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by DOGGOLOVER679** [PrismarineJS/mineflayer#1632]
Hey, i tried using mineflayer with a lower version like 12 and gives an error: “too low node version”. Is there a way to use mineflayer with a lower version?

(If you are wondering why i am using version 12. I want to do a project where i use play.js on ios to make a minecraft bot. The only problem is that this only supports node version 12)

**Comment by goncharovchik** [comment]
> Hey, i tried using mineflayer with a lower version like 12 and gives an error: “too low node version”. Is there a way to use mineflayer with a lower version?
> 
> 
> (If you are wondering why i am using version 12. I want to do a project where i use play.js on ios to make a minecraft bot. The only problem is that this only supports node version 12)
> 

The only option is to use an older version mineflayer

**Comment by rom1504** [comment]
is there any way to make play.js compatible with 14?

we've started using node14 features all over prismarine packages so it's going to be complicated to go back to 12

**Comment by DOGGOLOVER679** [comment]
What older version of mineflayer is for node 12 or is there a way to update to node 14 on play.js?

**Comment by DOGGOLOVER679** [comment]
Where can i see what version is for node 12 and is there a way to update to nodejs 14 on play.js?

**Comment by Kashalls** [comment]
> Where can i see what version is for node 12 and is there a way to update to nodejs 14 on play.js?

What are you trying to do exactly? Why do you need Node 12 over 14?

**Comment by DOGGOLOVER679** [comment]
Ok, is there a way to update play.js to nodejs 14?
