### ISSUE TITLE
Example for Block facing to position? (Observers, torch, similars)

### ISSUE THREAD

**Issue by sefirosweb** [PrismarineJS/mineflayer#1636]
H guys, anyone have a bit example how I can set observers or touches to position?

I read the documentation and with this function it should work, but is not facing to the way I want,

```js
bot.placeBlock(position, new Vec3(0,1,0))
```

For examples the torch are they are placed on the wall if there is stone between the bot and the placed side

```js
bot.placeBlock(position, new Vec3(0,-1,0))
```
Only the best way is to force go very near to force put it on the ground?  or direction?

**Comment by imharvol** [comment]
I would say that with torches setting the faceVector is enough, but to set the direction of the observers I think you should tweak the cursor position, which is hardcoded into mineflayer:
https://github.com/PrismarineJS/mineflayer/blob/90bc3db58ab157a02b122f69684052067150358c/lib/plugins/inventory.js#L373-L421

See more here https://wiki.vg/Protocol#Player_Block_Placement

**Comment by sefirosweb** [comment]
Hi imharvol, for torchs some times works and others no :/

For that I requested about "observers" are a bit hard to make facing to,

I take a look the documentation

Thanks!

**Comment by Karang** [comment]
Facing data is very tricky to get right, I ran into similar issues when doing mineflayer-builder, my solution was to have a bot place every blocks with a facing property and observe how the block was placed. Here is the data https://github.com/PrismarineJS/mineflayer-builder/blob/master/lib/facingData.json#L577

* is3D: tells if the block can be oriented in 6 directions or only 4
* faceDirection: if true the orientation is determined by the clicked face, else its set according to the player look direction
* inverted: if the block is oriented in the direction of the face/player or on the opposite direction

Observers facing is determined by the player position, so you need to place the bot at the right spot relative to the block. This is a bit tricky to do, but pathfinder now have a special goal to do that, take a look at mineflayer-builder, it requires a bit of setup, but i don't have a better example. https://github.com/PrismarineJS/mineflayer-builder/blob/master/index.js#L70

**Comment by sefirosweb** [comment]
Thanks alot @Karang  then I understood this a bit complex to resolve,
We will take a look your documentaion,
I close the ticket then, 

Best!
