### ISSUE TITLE
Update PrismarineJS mineflayer dependents to mineflayer 3.0.0

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#1645]
* flying-squid (for tests)
* some plugins (in examples)
* anything else?

**Comment by u9g** [comment]
Is there a list of breaking changes?

**Comment by Karang** [comment]
Yes https://github.com/PrismarineJS/mineflayer/blob/master/docs/history.md#300

**Comment by rom1504** [comment]
Dependabot opened two failing PRs in flying-squid for this
