### ISSUE TITLE
Bot can't ride bubble elevators

### ISSUE THREAD

**Issue by ZunDubCore** [PrismarineJS/mineflayer#1655]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.41.0
 - server: paper 1.16.5
 - node: v15.8.0

## Detailed description of a problem
The bot can't ride bubble elevators. It just stays at the bottom.

## Expected behavior
The bot should float to the top

**Comment by goncharovchik** [comment]
> - [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 
> 
> ## Versions
>  - mineflayer: 2.41.0
>  - server: paper 1.16.5
>  - node: v15.8.0
> 
> ## Detailed description of a problem
> The bot can't ride bubble elevators. It just stays at the bottom.
> 
> ## Expected behavior
> The bot should float to the top
> 
> 

#1601
