### ISSUE TITLE
Find Block by Filter && Bot not breaking sugar cane

### ISSUE THREAD

**Issue by xPythh** [PrismarineJS/mineflayer#1656]
- [ x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x ] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [ x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 3.0.0
 - server: vanilla/spigot/paper vanilla
 - node: v14.15.4

## Clear question
How could i use bot.findBlock with a filter, i would like to find sugar cane, ONLY if the block under is not sand.
I also would like to know why my bot isn't breaking the sugar cane.

## What did you try yet?
I tried to use the "matching" option from findBlock, but its not possible as the block is still not found, so i can't check the offset position from the block under it

## Your current code

Please put here any custom code you tried yet.

```js
function findAndBreak()
{
	var blockType = mcData.blocksByName["sugar_cane"];
	var block = bot.findBlock({
    	matching: blockType.id,
    	maxDistance: 64
  	})
  	if (!block) 
  	{
  		console.log("Could not find block");
  	} 
  	console.log(bot.blockAt(block.position.offset(0, -1, 0)))

	bot.collectBlock.collect(block, err => {
	    if (err) bot.chat(err.message)
	    	else
	    console.log("Succesfully fucked up sugar cane")
	 })
}

```

## Additional context
Video (of the sugar cane not getting breaked) :  https://vimeo.com/510714266

**Comment by u9g** [comment]
You only console.log the block, you don't actually break it.

**Comment by xPythh** [comment]
what does 
`
	bot.collectBlock.collect(block, err => {
	    if (err) bot.chat(err.message)
	    	else
	    console.log("Succesfully fucked up sugar cane")
	 })
`

**Comment by Zn10plays** [comment]
Collect Block plugin currently doesn't support mineflayer 3.X . So you might have issues in the future.

**Comment by rom1504** [comment]
please open collect block issues on collect block repo
