### ISSUE TITLE
After i upgraded, it is not working at all!

### ISSUE THREAD

**Issue by XfedeX** [PrismarineJS/mineflayer#1659]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a problem
My bot was working perfectly.
I runned "npm install mineflayer" with CMD; and i got no error.
After running bot, I get now this error:
```
C:\Users\Toshiba\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'protocolVersion' of null
    at Client.next (C:\Users\Toshiba\node_modules\mineflayer\index.js:110:81)
    at Object.onceWrapper (events.js:421:28)
    at Client.emit (events.js:327:22)
    at C:\Users\Toshiba\node_modules\minecraft-protocol\src\client\autoVersion.js:53:12
    at Client.<anonymous> (C:\Users\Toshiba\node_modules\minecraft-protocol\src\ping.js:39:7)
    at Object.onceWrapper (events.js:422:26)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (C:\Users\Toshiba\node_modules\minecraft-protocol\src\client.js:89:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (C:\Users\Toshiba\node_modules\readable-stream\lib\_stream_readable.js:298:12)
```

## Expected behavior
It was expected to work.

**Comment by u9g** [comment]
what is your code?

**Comment by CC044** [comment]
I have the same issue. 
Running an example code the bot doesn't connect, but instead reports a timeout:

```
Error: ETIMEDOUT
    at Timeout._onTimeout (/home/user/mineflayer/node_modules/minecraft-protocol/src/ping.js:64:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Error: connect ETIMEDOUT 185.116.156.135:48721
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '185.116.156.135',
  port: 48721
}
```

Running my own code throws the same error as XfedeX.

It seems the problem is not related to version update 1.16.5, because after downgrading my server the problem persists.
I noticed the problem after upgrading npm to version 7.5.4, problem still persist after installing 6.14.11. Idk which version I've used before 7.5.4. 
Node version is 14.15.5
I tried deleting the folder node_modules/ and reinstalling with npm install mineflayer, but the problem persists.
Here's my code:

```
const mineflayer = require('mineflayer');
const AutoAuth = require('mineflayer-auto-auth');
const options = {
	host: '185.116.156.135',
	port: '48271',
	username: 'Player',
	version: false, //removing this doesn't change the problem
};

const bot = mineflayer.createBot(options);

function auth(bot) {
	bot.on('serverAuth', function() {
	// Here bot should be already authorized
	console.log('bot authorized');
	})
};

bot.on('error', function(err) {
	console.log("Bot has encountered an error" + err);
});

function relog() {
	console.log("Attempting to reconnect...");
	bot = mineflayer.createBot(options);
	auth(bot);
};
```

**Comment by u9g** [comment]
> mineflayer-auto-auth

maybe try putting '1.16.5' instead of false for version?

**Comment by CC044** [comment]
```
/home/user/mineflayer/node_modules/mineflayer/index.js:114
    const latestProtocolVersion = require('minecraft-data')(latestTestedVersion).protocolVersion
                                                                                ^
TypeError: Cannot read property 'protocolVersion' of null
    at next (/home/chris/mineflayer/node_modules/mineflayer/index.js:114:81)
    at Object.createBot (/home/chris/mineflayer/node_modules/mineflayer/index.js:105:34)
    at Object.<anonymous> (/home/chris/mineflayer/alter.js:51:24)
    at Module._compi [...]
```
I doubt the error is in the code though, since the [reconnector.js example](https://github.com/PrismarineJS/mineflayer/blob/master/examples/reconnector.js) fails, too.

**Comment by rom1504** [comment]
try with `port:  48271`

**Comment by CC044** [comment]
Upgraded from 2.41.0 to 3.0.0. and now it seems to works. 

1. I checked the version in package.json which was 2.41.0,
2. deleted node_modules folder and
3. upgraded with ```npm i mineflayer@3.0.0```

hope this helps @XfedeX
still not sure what is causing the issue exactly though.

**Comment by u9g** [comment]
If you found this issue by searching, look here: https://github.com/PrismarineJS/mineflayer/discussions/1689
