### ISSUE TITLE
Using anvils

### ISSUE THREAD

**Issue by RegenixMC** [PrismarineJS/mineflayer#1665]
Is there a way to put enchantment books on gear using a Anvil with mineflayer.

**Comment by u9g** [comment]
anvils arent implemented in mineflayer

**Comment by RegenixMC** [comment]
Can you add it maybe? That would be very useful.

**Comment by u9g** [comment]
https://github.com/PrismarineJS/mineflayer/issues/237 follow the progress here

**Comment by u9g** [comment]
can be closed, duplicate of #237
