### ISSUE TITLE
Running in docker and ubuntu times out

### ISSUE THREAD

**Issue by maantjemol** [PrismarineJS/mineflayer#1672]
## Versions
 - mineflayer: 3.0.0
 - server: all
 - node: 14.5.15

## Issue
I'm trying to dockerize or deploy an mineflayer application that I made on my windows machine to ubuntu, but when I try to run it on my Ubuntu machine, the message "pinging -server ip- +0ms" comes up, and after a while it times out.  The same happens in a nodejs docker container. I think issue #1176  had the same problem and he didn't find a fix for it. Does someone know a solution for this problem?

**Comment by extremeheat** [comment]
Did you see the suggestions on the other issue? This is not really a mineflayer problem. The problem is your machine isn’t allowing outbound connections to the server. 

Try running “telnet <server ip> 25565” and see if the connection is successful (should have no output).

**Comment by maantjemol** [comment]
Thanks for the fast reply, telnet does indeed not have an output. Is there a way I could allow outbound connections to the server?

**Comment by u9g** [comment]
> Thanks for the fast reply, telnet does indeed not have an output. Is there a way I could allow outbound connections to the server?

Not related to mineflayer, related to docker.

**Comment by everettperiman** [comment]
Why was this closed out? At least helping mediate a solution on here would be helpful for future users. I have a similar issue but no where else to consult.

**Comment by rom1504** [comment]
to propose a solution we would first need to know what is the problem
no problem is clearly stated here

**Comment by MrSpeedy35** [comment]
I am facing the same problem, any fixes?
The mineflayer code works on Windows but as soon as I run on my Oracle VPS, it does not work.

**Comment by extremeheat** [comment]
> as soon as I run on my Oracle VPS, it does not work

Firewall issue

**Comment by mallusrgreatv2** [comment]
The VPS @MrSpeedy35 is talking about is mine. I tried telnet, it works as expected:
![image](https://user-images.githubusercontent.com/69511006/222632315-a4671cb5-6b13-4f43-94dd-1b2904ca31d8.png)
