### ISSUE TITLE
Mining problem

### ISSUE THREAD

**Issue by areny7** [PrismarineJS/mineflayer#1675]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper 1.15.2
 - node: v15.1.0

## Clear question
I need my robot to be in a spot, look up vertically, then pick up the script and keep digging the square, whatever the square is, how do I do that? Related FAQ, I have read other questions, now I want to know how to implement?

1.How do you dig all the way up?

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code

Please put here any custom code you tried yet.

```js

/*
Some code here, replace this
*/

```

**Comment by u9g** [comment]
this isn't a problem, this is just you asking someone to code for you
