### ISSUE TITLE
Unreadable position

### ISSUE THREAD

**Issue by areny7** [PrismarineJS/mineflayer#1681]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 3.0.0
 - server: vanilla/spigot/paper #.#.#
 - node: 14.5

## Clear question
I consulted the code for #1318 to keep my robot in one line of sight and digging all the time, but there was a problem and it kept prompting when it was running"[deprecated] use bot.blockAtCursor instead",I checked the document and replaced it with :' BOT.BLOCKATCURSOR ', but it returns an error at runtime:
![QQ截图20210219171059](https://user-images.githubusercontent.com/65305146/108484583-ed9d2a00-72d6-11eb-8667-d4ca66df7a82.png)

My Code:
![QQ截图20210219171409](https://user-images.githubusercontent.com/65305146/108484637-fe4da000-72d6-11eb-97b9-777886b4a744.png)

How should I solve this problem

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code

Please put here any custom code you tried yet.

```js

/*
Some code here, replace this
*/

```

**Comment by Karang** [comment]
To test if `target !== undefined && target !== null` you can simply use `if (target &&`

**Comment by areny7** [comment]
> 测试`target !== undefined && target !== null`您是否可以简单地使用`if (target &&`

Oh, yeah, I can try this
