### ISSUE TITLE
problems with multiple bots on mineflayer.

### ISSUE THREAD

**Issue by Hotdog-Sama** [PrismarineJS/mineflayer#1684]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a problem
Im trying to get a swarm of bots going, and i tried to merge multiple.js and *pretty much* guard.js, cuz im lazy. and its
not working out at all, like, im getting errors like server rejected transaction, all with error code 1. im also using the mineflayer-pvp and mineflayer-pathfinder plugins.

## What did you try yet?

i dont think there was an api.
multiple.js, and guard.js

## my code here:
```js

const mineflayer = require('mineflayer')
const pvp = require('mineflayer-pvp').plugin
const { pathfinder, Movements, goals} = require('mineflayer-pathfinder')
const armorManager = require('mineflayer-armor-manager')


let i = 0
function next () {
  if (i < 10) {
    i++
    setTimeout(() => {
      createBot(`mineflayer-bot${i}`)
      next()
    }, 100)
  }
}
  const bot = mineflayer.createBot({
    host: process.argv[2],
    port: 60528,
    username: process.argv[4] || 'Guard',
    password: process.argv[5],
    logErrors: false

})


function createBot (name) {
    mineflayer.createBot({
      host: process.argv[2],
      port: parseInt(process.argv[3]),
      username: name
    })
  }


next()

bot.loadPlugin(pvp)
bot.loadPlugin(armorManager)
bot.loadPlugin(pathfinder)


bot.on('playerCollect', (collector, itemDrop) => {
  if (collector !== bot.entity) return

  setTimeout(() => {
    const sword = bot.inventory.items().find(item => item.name.includes('sword'))
    if (sword) bot.equip(sword, 'hand')
  }, 150)
})

bot.on('playerCollect', (collector, itemDrop) => {
  if (collector !== bot.entity) return

  setTimeout(() => {
    const shield = bot.inventory.items().find(item => item.name.includes('shield'))
    if (shield) bot.equip(shield, 'off-hand')
  }, 250)
})

let guardPos = null

function guardArea (pos) {
  guardPos = pos.clone()

  if (!bot.pvp.target) {
    moveToGuardPos()
  }
}

function stopGuarding () {
  guardPos = null
  bot.pvp.stop()
  bot.pathfinder.setGoal(null)
}

function moveToGuardPos () {
  const mcData = require('minecraft-data')(bot.version)
  bot.pathfinder.setMovements(new Movements(bot, mcData))
  bot.pathfinder.setGoal(new goals.GoalBlock(guardPos.x, guardPos.y, guardPos.z))
}

bot.on('stoppedAttacking', () => {
  if (guardPos) {
    moveToGuardPos()
  }
})

bot.on('physicTick', () => {
  if (bot.pvp.target) return
  if (bot.pathfinder.isMoving()) return

  const entity = bot.nearestEntity()
  if (entity) bot.lookAt(entity.position.offset(0, entity.height, 0))
})

bot.on('physicTick', () => {
  if (!guardPos) return

  const filter = e => e.type === 'mob' && e.position.distanceTo(bot.entity.position) < 16 &&
                      e.mobType !== 'Armor Stand' // Mojang classifies armor stands as mobs for some reason?

  const entity = bot.nearestEntity(filter)
  if (entity) {
    bot.pvp.attack(entity)
  }
})

bot.on('chat', (username, message) => {
  if (message === 'guard') {
    const player = bot.players[username]

    if (!player) {
      bot.chat("I can't see you.")
      return
    }

    bot.chat('I will guard that location.')
    guardArea(player.entity.position)
  }

  if (message === 'fight me') {
    const player = bot.players[username]

    if (!player) {
      bot.chat("I can't see you.")
      return
    }

    bot.chat('Prepare to fight!')
    bot.pvp.attack(player.entity)
  }

  if (message === 'stop') {
    bot.chat('I will no longer guard this area.')
    stopGuarding()
  }
})


```

## Expected behavior
i expected to be able to log multiple bots onto lan.

## Additional context
uhhh, prolly no extra context, idk tell me if i missed anything.

**Comment by brenoxavier** [comment]
You are probably exceeding the capacity of the main JavaScript thread (Mineflayer is a single thread).

Try to create a thread for each bot. [https://nodejs.org/dist/latest-v14.x/docs/api/worker_threads.html#worker_threads_worker_threads](url)

**Comment by u9g** [comment]
> You are probably exceeding the capacity of the main JavaScript thread (Mineflayer is a single thread).
> 
> Try to create a thread for each bot:
> [https://nodejs.org/dist/latest-v14.x/docs/api/worker_threads.html#worker_threads_worker_threads](url)

mineflayer is **not** a single thread. pathfinder is.

**Comment by brenoxavier** [comment]
> > You are probably exceeding the capacity of the main JavaScript thread (Mineflayer is a single thread).
> > Try to create a thread for each bot:
> > [https://nodejs.org/dist/latest-v14.x/docs/api/worker_threads.html#worker_threads_worker_threads](url)
> 
> mineflayer is **not** a single threaded library. pathfinder is.

I had the same problem reported by him and solved it this way.

**Comment by Karang** [comment]
Here is an example of using one worker thread for each bot: https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/examples/multiple.js
