### ISSUE TITLE
Awaiting bot.lookAt resolves too quickly

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1694]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.1.0
 - server: (vanilla)/spigot/paper 1.16.5
 - node: v14.8.0

## Detailed description of a problem
Trying to shoot a crossbow, using bot.lookAt resolves too quickly and shoots something else because it was still moving.

## What did you try yet?
`await bot.waitForTicks(5)` after the lookat works but It should just be able to be awaited within the bot.lookat event
Did you try any method from the API? Yes.
Did you try any example? Any error from those? No.

## Your current code
```js
await bot.lookAt(bot.players[username].entity.position, true)
```

## Expected behavior
it look at the player then resolve

**Comment by Zn10plays** [comment]
This is not a problem with bot.lookAt, but a problem with bot.look

bot.look return instantly if the force condition is true. And Ideally, that is what would happen, but usually doesn't

**Comment by rom1504** [comment]
the solution is to avoid using force look
