### ISSUE TITLE
socks5 and mineflayer

### ISSUE THREAD

**Issue by areny7** [PrismarineJS/mineflayer#1697]
Because I need SOCks or HTTP proxies to log in to the server, this will use "node-minecraft-protocol", but I found a problem when I was using it. In mineflayer, there are many parameters that I can call, such as mining, but in "node-minecraft-protocol". There are many events that are not documented. How do I do this? And can I use "node-minecraft-protocol" with mineflayer? Do you have a complete example? Thank you!

**Comment by goncharovchik** [comment]
> Because I need SOCks or HTTP proxies to log in to the server, this will use "node-minecraft-protocol", but I found a problem when I was using it. In mineflayer, there are many parameters that I can call, such as mining, but in "node-minecraft-protocol". There are many events that are not documented. How do I do this? And can I use "node-minecraft-protocol" with mineflayer? Do you have a complete example? Thank you!

You can use proxy from mineflayer:

`
const mineflayer = require('mineflayer)
const socks = require('socks').SocksClient
const ProxyAgent = require('proxy-agent')

const serverHost = 'localhost'
const serverPort = 25565
const proxyHost = 'ProxyHost'
const proxyPort = 'ProxyPort'
const nickname = 'player'
const password = 'password'

const bot = mineflayer.createClient({
  connect: client => {
    socks.createConnection({
      proxy: {
        host: proxyHost,
        port: parseInt(proxyPort),
        type: 5
      },
      command: 'connect',
      destination: {
        host: serverHost,
        port: serverPort
      }
    }, (err, info) => {
      if (err) {
        console.log(err)
        return
      }

      bot.setSocket(info.socket)
      bot.emit('connect')
    })
  },
  agent: new ProxyAgent({ protocol: 'socks5:', host: proxyHost, port: proxyPort }),
  username: nickname,
  password: password
})`

**Comment by Liar-Sama** [comment]
hmm, is there a way to use multiple proxies for different bots? is it in the api?
