### ISSUE TITLE
How can i run mineflayer with older node version

### ISSUE THREAD

**Issue by peter12908** [PrismarineJS/mineflayer#1701]
So i am using node.js version v10.11.0.
Yes i know that I need v14+ to run the newest version of mineflayer.
But I cant change the version of Node so updating node wont be a solution for me.
The Reason why I am using v10.11.0 is that I use electron and even the latest electron version doesnt have v14+ built into it only v12.

**Comment by peter12908** [comment]
ok i found somekind of solution i just used old mineflayer version with newest minecraft-data

**Comment by extremeheat** [comment]
Update your Electron. If you're using Node.js 10, you're using Electron 5, the latest version is Electron 13. You need Electron 12+ for Node.js 14.
I believe 13 is only beta currently, so you can update to 12 with `npm i electron@12`.
