### ISSUE TITLE
On 3.2.0 canSeeBlock return null instead true / false

### ISSUE THREAD

**Issue by sefirosweb** [PrismarineJS/mineflayer#1704]
Hello after update 3.2.0 the function "canSeeBlock" returns null all time instead true

the code is very simply:
```js
 if (bot.canSeeBlock(blockPosition)) {
 /// do anything
}
```

I see on block.js this code breaks,

bot.world.raycast(headPos, dir.normalize(), 5)

The 5 is te distance? some times i need to "know"  i can see it a more 5 blocks of distance

Also that can be calcullate automatically A pos - b pos => distance

**Comment by Karang** [comment]
Yes the new behavior is that the block should be in range to be seen. Do you think that's wrong ? it could be changed. What's your use case for this function ?

**Comment by sefirosweb** [comment]
I'm trying if i can see an a mob

I get mob.position + mob.y + mob.height

With this info i try to use a canSeeBlock

Of course the block is a "air", i think for that was broken ;_;

**Comment by sefirosweb** [comment]
Yes i confirm the raycast skip the air blocks until end, 
Then the result of equation the block more far away as mob original position,
I need to think alternatives or make any pluging

**Comment by sefirosweb** [comment]
Hi @Karang  you can check the PR: https://github.com/PrismarineJS/prismarine-world/pull/63 ?
If they is ok I can do one PR more for solve this issue

**Comment by Karang** [comment]
Merged

**Comment by sefirosweb** [comment]
Solved with https://github.com/PrismarineJS/mineflayer/pull/1738
