### ISSUE TITLE
ETIMEDOUT  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16)

### ISSUE THREAD

**Issue by Liar-Sama** [PrismarineJS/mineflayer#1706]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: latest
 - server: idk, but its a hub server #.#.#
 - node: #.#.#

## Clear question
im trying to solve this error when i try to connect my bots.

Error: connect ETIMEDOUT 147.135.9.100:25551
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:132:14)
Emitted 'error' event at:
    at Client.<anonymous> (c:\Users\King_Periwinkle\node_modules\mineflayer\index.js:97:9)
    at Client.emit (node:events:378:20)
    at c:\Users\King_Periwinkle\node_modules\minecraft-protocol\src\client\autoVersion.js:13:30
    at Client.<anonymous> (c:\Users\King_Periwinkle\node_modules\minecraft-protocol\src\ping.js:24:5)
    at Client.emit (node:events:378:20)
    at Socket.onFatalError (c:\Users\King_Periwinkle\node_modules\minecraft-protocol\src\client.js:149:12)
    at Socket.emit (node:events:390:22)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '147.135.9.100',
  port: 25550
}
and 
## What did you try yet?

I have carefully read the api.

## Your current code

Please put here any custom code you tried yet.

```js

/*
const mineflayer = require('mineflayer')
const { pathfinder, Movements, goals} = require('mineflayer-pathfinder')
const { GoalInvert, GoalFollow } = require('mineflayer-pathfinder').goals
const pvp = require('mineflayer-pvp').plugin
const viewer = require('prismarine-viewer').mineflayer
const autoauth = require('mineflayer-auto-auth')

const botName = process.argv[2]
const botPassword = process.argv[3]

createNewBot(botName, botPassword)

function createNewBot (botName, Password = 'shit1223') {
  const bot = mineflayer.createBot({
    username: botName,
    host: 'massivecraft.com',
    logErrors: false,
    port: 25551,
    version: false,
    auth: 'tlauncher.org',
    verbose: true
  })
  bot.once('login', () => {
    console.log(bot.username);
    console.log("OK")

  bot.once('spawn', () => {
    bot.loadPlugin(pathfinder)
    bot.loadPlugin(pvp)
    bot.on('playerCollect', (collector, itemDrop) => {
      if (collector !== bot.entity) return
    
      setTimeout(() => {
        const sword = bot.inventory.items().find(item => item.name.includes('sword'))
        if (sword) bot.equip(sword, 'hand')
      }, 150)
    })
    
    bot.on('playerCollect', (collector, itemDrop) => {
      if (collector !== bot.entity) return
    
      setTimeout(() => {
        const shield = bot.inventory.items().find(item => item.name.includes('shield'))
        if (shield) bot.equip(shield, 'off-hand')
      }, 250)
    })
    
    let guardPos = null
    
    function guardArea (pos) {
      guardPos = pos.clone()
    
      if (!bot.pvp.target) {
        moveToGuardPos()
      }
    }
    
    function stopGuarding () {
      guardPos = null
      bot.pvp.stop()
      bot.pathfinder.setGoal(null)
    }
    
    function moveToGuardPos () {
      const mcData = require('minecraft-data')(bot.version)
      bot.pathfinder.setMovements(new Movements(bot, mcData))
      bot.pathfinder.setGoal(new goals.GoalBlock(guardPos.x, guardPos.y, guardPos.z))
    }
    
    bot.on('stoppedAttacking', () => {
      if (guardPos) {
        moveToGuardPos()
      }
    })
    
    bot.on('physicTick', () => {
      if (bot.pvp.target) return
      if (bot.pathfinder.isMoving()) return
    
      const entity = bot.nearestEntity()
      if (entity) bot.lookAt(entity.position.offset(0, entity.height, 0))
    })
    
    bot.on('physicTick', () => {
      if (!guardPos) return
    
      const filter = e => e.type === 'mob' && e.position.distanceTo(bot.entity.position) < 16 &&
                          e.mobType !== 'Armor Stand' // Mojang classifies armor stands as mobs for some reason?
    
      const entity = bot.nearestEntity(filter)
      if (entity) {
        bot.pvp.attack(entity)
      }
    })
    
    bot.on('chat', (username, message) => {
      if (message === 'guard') {
        const player = bot.players['__facts__']
    
        if (!player) {
          bot.chat("I can't see you.")
          return
        }
    
        bot.chat('I will guard that location.')
        guardArea(player.entity.position)
      }

      if (message === 'swarm') {
        const player = bot.players['__facts__']
    
        if (!player) {
          bot.chat("I can't see you.")
          return
        }
    
        bot.chat('I will guard that location.')
        guardArea(player.entity.position)
        while (1) {
          moveToGuardPos()
        }
      }


      if (message === 'fight me') {
        const player = bot.players[username]
    
        if (!player) {
          bot.chat("I can't see you.")
          return
        }
    
        bot.chat('Prepare to fight!')
        bot.pvp.attack(player.entity)
      }
    
      if (message === 'stop') {
        bot.chat('I will no longer guard this area.')
        stopGuarding()
      }
    
      if (message === 'hp') {
        bot.chat(bot.health)
      }
      bot.on('error', err=> console.log(err))
    })
  })
})
}
*/
## index.js
/*
const cp = require('child_process')
const path = require('path')
const assert = require('assert')
const { Vec3 } = require('vec3')
const readFile = (fileName) => util.promisify(fs.readFile)(fileName, 'utf8')
const events = require('events').EventEmitter.defaultMaxListeners = Infinity

function startBot (botName, Password) {
  const command = 'node ' + path.join(__dirname, 'start_bot') + ' ' + botName
  cp.exec(command, (err, stdout, stderr) => {
    if (err) {
      console.log(`Error: ${err}`)
      console.log(`Bot broken: ${botName}`)
      console.log(`Restarting bot ${botName}...`)
      setTimeout(() => startBot(botName, Password), 15000)
      return
    }

    if (stdout) {
      console.log(`Stdout: ${stdout}`)
    }

    if (stderr) {
      console.log(`Stderr: ${stderr}`)
    }
  })  
}

const botsToStart = [
  { username: 'someone.lol123456@gmail.com' },
  { username: 'idk.johnson.uno@gmail.com' },
  { username: 'epicaa534@gmail.com' },
  { username: 'hotdogsama22@gmail.com' },
  { username: 'villzy.bizz@gmail.com' },
  
]

let i = 0
function runNextBot () {
  const botToStart = botsToStart[i]
  i++
  if (i <= botsToStart.length) {
    setTimeout(() => {
      startBot(botToStart.username)
      runNextBot()
    }, 6000) //I recommended you wait for dont stuck the server they can detect too many connections at same time
  }
};

runNextBot()
*/
```

## Additional context
i am trying to connect to massivecraft.com

**Comment by goncharovchik** [comment]
> - [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
> - [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
> - [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.
> 
> 
> 
> ## Versions
>  - mineflayer: latest
>  - server: idk, but its a hub server #.#.#
>  - node: #.#.#
> 
> ## Clear question
> im trying to solve this error when i try to connect my bots.
> 
> Error: connect ETIMEDOUT 147.135.9.100:25551
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16)
>     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:132:14)
> Emitted 'error' event at:
>     at Client.<anonymous> (c:\Users\King_Periwinkle\node_modules\mineflayer\index.js:97:9)
>     at Client.emit (node:events:378:20)
>     at c:\Users\King_Periwinkle\node_modules\minecraft-protocol\src\client\autoVersion.js:13:30
>     at Client.<anonymous> (c:\Users\King_Periwinkle\node_modules\minecraft-protocol\src\ping.js:24:5)
>     at Client.emit (node:events:378:20)
>     at Socket.onFatalError (c:\Users\King_Periwinkle\node_modules\minecraft-protocol\src\client.js:149:12)
>     at Socket.emit (node:events:390:22)
>     at emitErrorNT (node:internal/streams/destroy:188:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:153:3)
>     at processTicksAndRejections (node:internal/process/task_queues:81:21) {
>   errno: -4039,
>   code: 'ETIMEDOUT',
>   syscall: 'connect',
>   address: '147.135.9.100',
>   port: 25550
> }
> and 
> ## What did you try yet?
> 
> I have carefully read the api.
> 
> ## Your current code
> 
> Please put here any custom code you tried yet.
> 
> ```js
> 
> /*
> const mineflayer = require('mineflayer')
> const { pathfinder, Movements, goals} = require('mineflayer-pathfinder')
> const { GoalInvert, GoalFollow } = require('mineflayer-pathfinder').goals
> const pvp = require('mineflayer-pvp').plugin
> const viewer = require('prismarine-viewer').mineflayer
> const autoauth = require('mineflayer-auto-auth')
> 
> const botName = process.argv[2]
> const botPassword = process.argv[3]
> 
> createNewBot(botName, botPassword)
> 
> function createNewBot (botName, Password = 'shit1223') {
>   const bot = mineflayer.createBot({
>     username: botName,
>     host: 'massivecraft.com',
>     logErrors: false,
>     port: 25551,
>     version: false,
>     auth: 'tlauncher.org',
>     verbose: true
>   })
>   bot.once('login', () => {
>     console.log(bot.username);
>     console.log("OK")
> 
>   bot.once('spawn', () => {
>     bot.loadPlugin(pathfinder)
>     bot.loadPlugin(pvp)
>     bot.on('playerCollect', (collector, itemDrop) => {
>       if (collector !== bot.entity) return
>     
>       setTimeout(() => {
>         const sword = bot.inventory.items().find(item => item.name.includes('sword'))
>         if (sword) bot.equip(sword, 'hand')
>       }, 150)
>     })
>     
>     bot.on('playerCollect', (collector, itemDrop) => {
>       if (collector !== bot.entity) return
>     
>       setTimeout(() => {
>         const shield = bot.inventory.items().find(item => item.name.includes('shield'))
>         if (shield) bot.equip(shield, 'off-hand')
>       }, 250)
>     })
>     
>     let guardPos = null
>     
>     function guardArea (pos) {
>       guardPos = pos.clone()
>     
>       if (!bot.pvp.target) {
>         moveToGuardPos()
>       }
>     }
>     
>     function stopGuarding () {
>       guardPos = null
>       bot.pvp.stop()
>       bot.pathfinder.setGoal(null)
>     }
>     
>     function moveToGuardPos () {
>       const mcData = require('minecraft-data')(bot.version)
>       bot.pathfinder.setMovements(new Movements(bot, mcData))
>       bot.pathfinder.setGoal(new goals.GoalBlock(guardPos.x, guardPos.y, guardPos.z))
>     }
>     
>     bot.on('stoppedAttacking', () => {
>       if (guardPos) {
>         moveToGuardPos()
>       }
>     })
>     
>     bot.on('physicTick', () => {
>       if (bot.pvp.target) return
>       if (bot.pathfinder.isMoving()) return
>     
>       const entity = bot.nearestEntity()
>       if (entity) bot.lookAt(entity.position.offset(0, entity.height, 0))
>     })
>     
>     bot.on('physicTick', () => {
>       if (!guardPos) return
>     
>       const filter = e => e.type === 'mob' && e.position.distanceTo(bot.entity.position) < 16 &&
>                           e.mobType !== 'Armor Stand' // Mojang classifies armor stands as mobs for some reason?
>     
>       const entity = bot.nearestEntity(filter)
>       if (entity) {
>         bot.pvp.attack(entity)
>       }
>     })
>     
>     bot.on('chat', (username, message) => {
>       if (message === 'guard') {
>         const player = bot.players['__facts__']
>     
>         if (!player) {
>           bot.chat("I can't see you.")
>           return
>         }
>     
>         bot.chat('I will guard that location.')
>         guardArea(player.entity.position)
>       }
> 
>       if (message === 'swarm') {
>         const player = bot.players['__facts__']
>     
>         if (!player) {
>           bot.chat("I can't see you.")
>           return
>         }
>     
>         bot.chat('I will guard that location.')
>         guardArea(player.entity.position)
>         while (1) {
>           moveToGuardPos()
>         }
>       }
> 
> 
>       if (message === 'fight me') {
>         const player = bot.players[username]
>     
>         if (!player) {
>           bot.chat("I can't see you.")
>           return
>         }
>     
>         bot.chat('Prepare to fight!')
>         bot.pvp.attack(player.entity)
>       }
>     
>       if (message === 'stop') {
>         bot.chat('I will no longer guard this area.')
>         stopGuarding()
>       }
>     
>       if (message === 'hp') {
>         bot.chat(bot.health)
>       }
>       bot.on('error', err=> console.log(err))
>     })
>   })
> })
> }
> */
> ## index.js
> /*
> const cp = require('child_process')
> const path = require('path')
> const assert = require('assert')
> const { Vec3 } = require('vec3')
> const readFile = (fileName) => util.promisify(fs.readFile)(fileName, 'utf8')
> const events = require('events').EventEmitter.defaultMaxListeners = Infinity
> 
> function startBot (botName, Password) {
>   const command = 'node ' + path.join(__dirname, 'start_bot') + ' ' + botName
>   cp.exec(command, (err, stdout, stderr) => {
>     if (err) {
>       console.log(`Error: ${err}`)
>       console.log(`Bot broken: ${botName}`)
>       console.log(`Restarting bot ${botName}...`)
>       setTimeout(() => startBot(botName, Password), 15000)
>       return
>     }
> 
>     if (stdout) {
>       console.log(`Stdout: ${stdout}`)
>     }
> 
>     if (stderr) {
>       console.log(`Stderr: ${stderr}`)
>     }
>   })  
> }
> 
> const botsToStart = [
>   { username: 'someone.lol123456@gmail.com' },
>   { username: 'idk.johnson.uno@gmail.com' },
>   { username: 'epicaa534@gmail.com' },
>   { username: 'hotdogsama22@gmail.com' },
>   { username: 'villzy.bizz@gmail.com' },
>   
> ]
> 
> let i = 0
> function runNextBot () {
>   const botToStart = botsToStart[i]
>   i++
>   if (i <= botsToStart.length) {
>     setTimeout(() => {
>       startBot(botToStart.username)
>       runNextBot()
>     }, 6000) //I recommended you wait for dont stuck the server they can detect too many connections at same time
>   }
> };
> 
> runNextBot()
> */
> ```
> 
> ## Additional context
> i am trying to connect to massivecraft.com
> 

Why are you using the port `25551`, the correct port for this server is `25565`.

**Comment by Liar-Sama** [comment]
oh ok

**Comment by Liar-Sama** [comment]
well, im dumb
