### ISSUE TITLE
How to talk to chat through bot

### ISSUE THREAD

**Issue by Febzey** [PrismarineJS/mineflayer#1709]
Hi as you can probably tell I am new to mineflayer and I am wondering how I am able to talk to game chat through my bot, I am assuming this can be done if I make it a discord bot as well? Just need a solid answer on how to do this. Thanks.

**Comment by DrMoraschi** [comment]
Look at the API, look at the examples.

Example:
```js
bot.chat("Hi, Im talking through discord")
```

If you want to link discord with minecraft, you create a discors bot, then every message you send, bot.chat it

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/examples/discord.js
