### ISSUE TITLE
How to catch an error when attempting to connect?

### ISSUE THREAD

**Issue by JonnyD** [PrismarineJS/mineflayer#171]
I'm getting this error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```

when I try to reconnect to the server after being kicked by a server restart. I'd like to keep attempting to reconnect while disconnected.

I've tried this so far:

```
bot.on('kicked', function(reason) {
    console.log("I got kicked for", reason, "lol");
    try {
      bot = mineflayer.createBot(options);
      bindEvents(bot);
   } catch (e) {
      console.log("caught error");
      bot = mineflayer.createBot(options);
      bindEvents(bot);
    }
  });
```

but it doesn't seem to catch the error. Any ideas? Thanks

**Comment by soshimee** [comment]
Same issue, sometimes Microsoft authentication fails and I have to try again, or the server sometimes doesn't respond and I have to try again, but mineflayer just decides to crash the application whatsoever.
