### ISSUE TITLE
Bot mines blocks slower than it should

### ISSUE THREAD

**Issue by WooHooASDF** [PrismarineJS/mineflayer#1710]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: vanilla 1.12.2, locally hosted
 - node: 16.8.0

## Detailed description of a problem
Bot is mining slowly. Begins to mine, almost completes, and then stops and kind of starts again

## What did you try yet?
I have tried the bot.dig() function. this is the only one that can perform the task
Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
````
mineBlock.js

const mineflayer = require("mineflayer")
const bot = mineflayer.createBot({
    host:"localhost",
    port: 50146,
    username: "mineTest"
})
//mine the block below the bot on spawn
bot.once("spawn", () => {bot.dig(bot.blockAt(bot.entity.position.offset(0,-1,0)))})



## Expected behavior
It should mine it all quickly.

## Additional context
Add any other context about the problem here.

**Comment by WooHooASDF** [comment]
It appears that this is caused by mining directly after spawning in, adding a delay solves this

**Comment by WooHooASDF** [comment]
This is apparently not the cas

Uploading Minecraft 1.12.2 2021-02-23 13-22-05.mp4…

**Comment by WooHooASDF** [comment]
Apparently this is not the case

https://user-images.githubusercontent.com/76736350/108850723-94d1d800-75db-11eb-8ed4-cb7e014a9c2a.mp4

**Comment by WooHooASDF** [comment]
Apparently this is not the case:



https://user-images.githubusercontent.com/76736350/108851091-f72ad880-75db-11eb-8c08-9943a3649f17.mp4

**Comment by u9g** [comment]
> Apparently this is not the case:
> 
>  Minecraft.1.12.2.2021-02-23.13-30-32_Trim.mp4

can you do `npm uninstall mineflayer` then `npm install mineflayer` ? I just tried myself and it worked, so I think you have an outdated version of mcData.

**Comment by goncharovchik** [comment]
> - [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 
> 
> ## Versions
>  - mineflayer: latest
>  - server: vanilla 1.12.2, locally hosted
>  - node: 16.8.0
> 
> ## Detailed description of a problem
> Bot is mining slowly. Begins to mine, almost completes, and then stops and kind of starts again
> 
> ## What did you try yet?
> I have tried the bot.dig() function. this is the only one that can perform the task
> Did you try any method from the API?
> Did you try any example? Any error from those?
> 
> ## Your current code
> ````
> mineBlock.js
> 
> const mineflayer = require("mineflayer")
> const bot = mineflayer.createBot({
>     host:"localhost",
>     port: 50146,
>     username: "mineTest"
> })
> //mine the block below the bot on spawn
> bot.once("spawn", () => {bot.dig(bot.blockAt(bot.entity.position.offset(0,-1,0)))})
> 
> 
> 
> ## Expected behavior
> It should mine it all quickly.
> 
> ## Additional context
> Add any other context about the problem here.
> 

Mineflayer does not support enchant version below 1.13.2

**Comment by WooHooASDF** [comment]
Does that mean I cannot use an enchanted pickaxe?

**Comment by goncharovchik** [comment]
> Does that mean I cannot use an enchanted pickaxe?

You can use it, but it will dig like a pickaxe without enchantments.

Repetition of animation is most likely just a visible bug, and the bot continues to dig (not exactly).

**Comment by WooHooASDF** [comment]
Ok, that would be great.

**Comment by WooHooASDF** [comment]
Meanwhile, how would I send a custom packet to the server through mineflayer?

**Comment by goncharovchik** [comment]
> Meanwhile, how would I send a custom packet to the server through mineflayer?


```js 
bot._client.write('name', {
Packet Data
})

```

**Comment by goncharovchik** [comment]
> Ok, that would be great.

I created a PR's which fixes this problem
 https://github.com/PrismarineJS/prismarine-block/pull/23 and #1711

**Comment by WooHooASDF** [comment]
Thank you so much for this.

**Comment by WooHooASDF** [comment]
I am now going to close this with the pull request being accepted.

**Comment by WooHooASDF** [comment]
Sorry to reopen this, but with the new version, the bot can mine individual blocks fine, but whenever I add a callback, it goes back to taking longer.

**Comment by rom1504** [comment]
can you share the exact code you ran to get this behavior ? (and prefer using promises than callbacks, we're going to remove callbacks soon)

**Comment by WooHooASDF** [comment]
It also appears to happen when using promises

**Comment by WooHooASDF** [comment]
Here is the code I am using, with breakBlocks being a list of blocks, and the version being 1.12.2, with an enchanted pickaxe on obsidian

```const mine = async () => {
    let i = 0
    while (i < breakBlocks.length) {
        await bot.dig(breakBlocks[i], true)
        i ++
    }
}```

**Comment by WooHooASDF** [comment]
Strangely, it does not occur if I do not use a loop at all

**Comment by WooHooASDF** [comment]
On a closer inspection, does not seem to be doing it with async

**Comment by u9g** [comment]
should be closed, fixed by https://github.com/PrismarineJS/mineflayer/pull/1711
