### ISSUE TITLE
Code works just Sometimes?

### ISSUE THREAD

**Issue by 1jokras** [PrismarineJS/mineflayer#1712]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [ ] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 3.2.0
 - server: paper 1.16.5
## Clear question
Hello, this code wokrs just sometimes, but most of the time, the bot dose not dig a tree but thinks that he did it.
(Thanks for Help, and sorry for bad English)

## Your current code
```js

/*
const mineflayer = require('mineflayer')
const { pathfinder, Movements, goals } = require("mineflayer-pathfinder")
const pvp = require('mineflayer-pvp').plugin
const GoalNear = goals.GoalNear

const bot = mineflayer.createBot({
host: 'localhost', // optional
username: 'JokrasBotTest', // email and password are required only for
})

bot.loadPlugin(pathfinder)

function fellingTrees(){
const mcData = require('minecraft-data')(bot.version)
const movements = new Movements(bot, mcData)
bot.pathfinder.setMovements(movements)
const LogsArray = [mcData.blocksByName.oak_log.id, mcData.blocksByName.spruce_log.id, mcData.blocksByName.birch_log.id, mcData.blocksByName.jungle_log.id, mcData.blocksByName.acacia_log.id, mcData.blocksByName.dark_oak_log.id]
const WoodLog = bot.findBlock({matching: LogsArray})
if (!WoodLog){
bot.chat("Why is here no wood")
return
}
const goal = new GoalNear(WoodLog.position.x, WoodLog.position.y, WoodLog.position.z, 3)
bot.pathfinder.setGoal(goal)
bot.dig(WoodLog,true, function(){bot.stopDigging();fellingTrees()})

}
bot.on('chat', function (username, message) {
if (username === bot.username) return
if (message === "go"){
fellingTrees()
}
})
*/

**Comment by u9g** [comment]
is there spawn protection near the bot?

**Comment by 1jokras** [comment]
Thank you
That was the Problem
