### ISSUE TITLE
socket closed error with socks5 proxies.

### ISSUE THREAD

**Issue by Liar-Sama** [PrismarineJS/mineflayer#1713]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Clear question
I am attempting to connect to play.ultimismc.com

## What did you try yet?
i tried: 
```
const mineflayer = require('mineflayer')
const socks = require('socks').SocksClient
const ProxyAgent = require('proxy-agent')

const serverHost = 'play.ultimismc.com'
const serverPort = '25565'
const proxyHost = 'myProxy'
const proxyPort = 'myProxy'
const nickname = 'ggGuard'
const password = 'shit1223'

const bot = mineflayer.createBot({
  connect: client => {
    socks.createConnection({
      proxy: {
        host: proxyHost,
        port: parseInt(proxyPort),
        type: 5
      },
      command: 'connect',
      destination: {
        host: serverHost,
        port: parseInt(serverPort)
      }
    }, (err, info) => {
      if (err) {
        console.log(err)
        return
      }

      client.setSocket(info.socket)
      client.emit('connect')
    })
  },
  agent: new ProxyAgent({ protocol: 'socks5:', host: proxyHost, port: proxyPort }),
  username: nickname,
})
```

from https://github.com/PrismarineJS/mineflayer/issues/461 by robabla and i also tried the other example from:
https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md#how-can-i-use-a-socks5-proxy

and im still getting this: 
Error: Socket closed
    at SocksClient.closeSocket (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:386:32)
    at SocksClient.onCloseHandler (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:352:14)
    at Socket.onClose (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:220:35)
    at Object.onceWrapper (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\events.js:485:26)
    at Socket.emit (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\events.js:378:20)
    at TCP.<anonymous> (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\net.js:665:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:132:14) {options: {…}, stack: 'Error: Socket closed
    at SocksClient.close…Trampoline (node:internal/async_hooks:132:14)', message: 'Socket closed'}
Error: Socket closed
    at SocksClient.closeSocket (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:386:32)
    at SocksClient.onCloseHandler (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:352:14)
    at Socket.onClose (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:220:35)
    at Object.onceWrapper (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\events.js:485:26)
    at Socket.emit (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\events.js:378:20)
    at TCP.<anonymous> (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\net.js:665:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:132:14) {options: {…}, stack: 'Error: Socket closed
    at SocksClient.close…Trampoline (node:internal/async_hooks:132:14)', message: 'Socket closed'}
message:'Socket closed'
options:{proxy: {…}, command: 'connect', destination: {…}}
stack:'Error: Socket closed\n    at SocksClient.closeSocket (c:\\Users\\King_Periwinkle\\node_modules\\socks\\build\\client\\socksclient.js:386:32)\n    at SocksClient.onCloseHandler (c:\\Users\\King_Periwinkle\\node_modules\\socks\\build\\client\\socksclient.js:352:14)\n    at Socket.onClose (c:\\Users\\King_Periwinkle\\node_modules\\socks\\build\\client\\socksclient.js:220:35)\n    at Object.onceWrapper (node:events:485:26)\n    at Socket.emit (node:events:378:20)\n    at TCP.<anonymous> (node:net:665:12)\n    at TCP.callbackTrampoline (node:internal/async_hooks:132:14)'
__proto__:Error

## Your current code

Please put here any custom code you tried yet.

```

const mineflayer = require('mineflayer')
const socks = require('socks').SocksClient
const ProxyAgent = require('proxy-agent')

const serverHost = 'play.ultimismc.com'
const serverPort = '25565'
const proxyHost = 'myProxy'
const proxyPort = 'myProxy'
const nickname = 'ggGuard'
const password = 'shit1223'

const bot = mineflayer.createBot({
  connect: client => {
    socks.createConnection({
      proxy: {
        host: proxyHost,
        port: parseInt(proxyPort),
        type: 5
      },
      command: 'connect',
      destination: {
        host: serverHost,
        port: parseInt(serverPort)
      }
    }, (err, info) => {
      if (err) {
        console.log(err)
        return
      }

      client.setSocket(info.socket)
      client.emit('connect')
    })
  },
  agent: new ProxyAgent({ protocol: 'socks5:', host: proxyHost, port: proxyPort }),
  username: nickname,
})

bot.on('spawn', function() {
    console.log('ok')
    bot.chat('/register password1223')
})

```

## Additional context
im also suspecting it might be a bug, bcuz i sometimes get another error. (i forgot the name of it)

**Comment by goncharovchik** [comment]
> - [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
> - [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
> - [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.
> 
> 
> 
> ## Versions
>  - mineflayer: #.#.#
>  - server: vanilla/spigot/paper #.#.#
>  - node: #.#.#
> 
> ## Clear question
> I am attempting to connect to play.ultimismc.com
> 
> ## What did you try yet?
> i tried: 
> ```
> const mineflayer = require('mineflayer')
> const socks = require('socks').SocksClient
> const ProxyAgent = require('proxy-agent')
> 
> const serverHost = 'play.ultimismc.com'
> const serverPort = '25565'
> const proxyHost = 'myProxy'
> const proxyPort = 'myProxy'
> const nickname = 'ggGuard'
> const password = 'shit1223'
> 
> const bot = mineflayer.createBot({
>   connect: client => {
>     socks.createConnection({
>       proxy: {
>         host: proxyHost,
>         port: parseInt(proxyPort),
>         type: 5
>       },
>       command: 'connect',
>       destination: {
>         host: serverHost,
>         port: parseInt(serverPort)
>       }
>     }, (err, info) => {
>       if (err) {
>         console.log(err)
>         return
>       }
> 
>       client.setSocket(info.socket)
>       client.emit('connect')
>     })
>   },
>   agent: new ProxyAgent({ protocol: 'socks5:', host: proxyHost, port: proxyPort }),
>   username: nickname,
> })
> ```
> 
> from https://github.com/PrismarineJS/mineflayer/issues/461 by robabla and i also tried the other example from:
> https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md#how-can-i-use-a-socks5-proxy
> 
> and im still getting this: 
> Error: Socket closed
>     at SocksClient.closeSocket (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:386:32)
>     at SocksClient.onCloseHandler (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:352:14)
>     at Socket.onClose (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:220:35)
>     at Object.onceWrapper (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\events.js:485:26)
>     at Socket.emit (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\events.js:378:20)
>     at TCP.<anonymous> (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\net.js:665:12)
>     at TCP.callbackTrampoline (node:internal/async_hooks:132:14) {options: {…}, stack: 'Error: Socket closed
>     at SocksClient.close…Trampoline (node:internal/async_hooks:132:14)', message: 'Socket closed'}
> Error: Socket closed
>     at SocksClient.closeSocket (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:386:32)
>     at SocksClient.onCloseHandler (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:352:14)
>     at Socket.onClose (c:\Users\King_Periwinkle\node_modules\socks\build\client\socksclient.js:220:35)
>     at Object.onceWrapper (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\events.js:485:26)
>     at Socket.emit (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\events.js:378:20)
>     at TCP.<anonymous> (c:\Users\King_Periwinkle\Desktop\bots\pvp-bot\lib\net.js:665:12)
>     at TCP.callbackTrampoline (node:internal/async_hooks:132:14) {options: {…}, stack: 'Error: Socket closed
>     at SocksClient.close…Trampoline (node:internal/async_hooks:132:14)', message: 'Socket closed'}
> message:'Socket closed'
> options:{proxy: {…}, command: 'connect', destination: {…}}
> stack:'Error: Socket closed\n    at SocksClient.closeSocket (c:\\Users\\King_Periwinkle\\node_modules\\socks\\build\\client\\socksclient.js:386:32)\n    at SocksClient.onCloseHandler (c:\\Users\\King_Periwinkle\\node_modules\\socks\\build\\client\\socksclient.js:352:14)\n    at Socket.onClose (c:\\Users\\King_Periwinkle\\node_modules\\socks\\build\\client\\socksclient.js:220:35)\n    at Object.onceWrapper (node:events:485:26)\n    at Socket.emit (node:events:378:20)\n    at TCP.<anonymous> (node:net:665:12)\n    at TCP.callbackTrampoline (node:internal/async_hooks:132:14)'
> __proto__:Error
> 
> ## Your current code
> 
> Please put here any custom code you tried yet.
> 
> ```
> 
> const mineflayer = require('mineflayer')
> const socks = require('socks').SocksClient
> const ProxyAgent = require('proxy-agent')
> 
> const serverHost = 'play.ultimismc.com'
> const serverPort = '25565'
> const proxyHost = 'myProxy'
> const proxyPort = 'myProxy'
> const nickname = 'ggGuard'
> const password = 'shit1223'
> 
> const bot = mineflayer.createBot({
>   connect: client => {
>     socks.createConnection({
>       proxy: {
>         host: proxyHost,
>         port: parseInt(proxyPort),
>         type: 5
>       },
>       command: 'connect',
>       destination: {
>         host: serverHost,
>         port: parseInt(serverPort)
>       }
>     }, (err, info) => {
>       if (err) {
>         console.log(err)
>         return
>       }
> 
>       client.setSocket(info.socket)
>       client.emit('connect')
>     })
>   },
>   agent: new ProxyAgent({ protocol: 'socks5:', host: proxyHost, port: proxyPort }),
>   username: nickname,
> })
> 
> bot.on('spawn', function() {
>     console.log('ok')
>     bot.chat('/register password1223')
> })
> 
> ```
> 
> ## Additional context
> im also suspecting it might be a bug, bcuz i sometimes get another error. (i forgot the name of it)
> 

Have you tried using a different proxy?

**Comment by Liar-Sama** [comment]
yes, i've tried 13 now.

**Comment by Liar-Sama** [comment]
im also getting this error: Debugger attached.
Process exited with code 1
C:\Program Files\nodejs\node.exe .\test2.js
PartialReadError: Read error for undefined : undefined
    at new ExtendableError (c:\Users\King_Periwinkle\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (c:\Users\King_Periwinkle\node_modules\protodef\src\utils.js:70:5)
    at Object.readVarInt [as varint] (c:\Users\King_Periwinkle\node_modules\protodef\src\datatypes\utils.js:69:45)
    at Object.string (eval at compile (c:\Users\King_Periwinkle\node_modules\protodef\src\compiler.js:245:12), <anonymous>:44:61)
    at Object.packet_server_info (eval at compile (c:\Users\King_Periwinkle\node_modules\protodef\src\compiler.js:245:12), <anonymous>:206:67)
    at eval (eval at compile (c:\Users\King_Periwinkle\node_modules\protodef\src\compiler.js:245:12), <anonymous>:220:62)
    at packet (eval at compile (c:\Users\King_Periwinkle\node_modules\protodef\src\compiler.js:245:12), <anonymous>:224:9)
    at CompiledProtodef.read (c:\Users\King_Periwinkle\node_modules\protodef\src\compiler.js:64:12)
    at e.message (c:\Users\King_Periwinkle\node_modules\protodef\src\compiler.js:99:49)
    at tryCatch (c:\Users\King_Periwinkle\node_modules\protodef\src\utils.js:50:16)
c:\Users\King_Periwinkle\node_modules\protodef\src\serializer.js:82
Uncaught TypeError: Cannot read property 'minecraftVersion' of undefined
Debugger attached.
Waiting for the debugger to disconnect...
c:\Users\King_Periwinkle\node_modules\minecraft-protocol\src\client\autoVersion.js:34
    const minecraftVersion = versions[0].minecraftVersion
                                         ^

TypeError: Cannot read property 'minecraftVersion' of undefined
    at c:\Users\King_Periwinkle\node_modules\minecraft-protocol\src\client\autoVersion.js:34:42
    at Timeout._onTimeout (c:\Users\King_Periwinkle\node_modules\minecraft-protocol\src\ping.js:32:7)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by goncharovchik** [comment]
const mineflayer = require('mineflayer')
const socks = require('socks').SocksClient
const ProxyAgent = require('proxy-agent')

const serverHost = 'play.ultimismc.com'
const serverPort = '25565'
const proxyHost = 'myProxy'
const proxyPort = 'myProxy'
const nickname = 'ggGuard'
const password = 'shit1223'
const version = '1.13.2'

const bot = mineflayer.createBot({
  connect: client => {
    socks.createConnection({
      proxy: {
        host: proxyHost,
        port: parseInt(proxyPort),
        type: 5
      },
      command: 'connect',
      destination: {
        host: serverHost,
        port: parseInt(serverPort)
      }
    }, (err, info) => {
      if (err) {
        console.log(err)
        return
      }

      client.setSocket(info.socket)
      client.emit('connect')
    })
  },
  agent: new ProxyAgent({ protocol: 'socks5:', host: proxyHost, port: proxyPort }),
  username: nickname,
  password: password,
  version: version
})

bot.on('spawn', function() {
    console.log('ok')
    bot.chat('/register password1223')
})

bot.on('kicked', (reason, loggedIn) => {
    console.log(reason, loggedIn)
})

bot.on('error', (err) => {
    console.log(err)
})

```

**Comment by Liar-Sama** [comment]
thanks, it says proxy connection timed out so i know its my proxy connection!

**Comment by Liar-Sama** [comment]
ayy it worked!!!
