### ISSUE TITLE
newListener and removeListener stacking up on world change

### ISSUE THREAD

**Issue by U5B** [PrismarineJS/mineflayer#1719]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.2.0
 - server: paper 1.16.4
 - node: 14.15.4

## Detailed description of a problem
On world change, listeners called "newListener" and "removeListener" are added. They keep adding up on every world change until it prints an "MaxListenersExceededWarning" to my console. It only happens on world change and dimension change.
The warning is only printed once, however listeners are continuously added.
## What did you try yet?
I tried using bot.removeEventListener('newListener), however that function was not defined.

Did you try any method from the API?
I did not.
Did you try any example? Any error from those?
I used looker.js with some modifications

## Your current code
```js

const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node echo.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'looker',
  password: process.argv[5],
  version: '1.16.4'
})

setInterval(() => {
  console.log(bot._events)
}, 5000)

bot.on('spawn', () => {
  bot.chat('uwu')
})
bot.once('spawn', function () {
  setInterval(() => {
    const entity = bot.nearestEntity()
    if (entity !== null) {
      if (entity.type === 'player') {
        bot.lookAt(entity.position.offset(0, 1.6, 0))
      } else if (entity.type === 'mob') {
        bot.lookAt(entity.position)
      }
    }
  }, 50)
})

```

## Expected behavior
I expect to be only one "newListener" and "removeListener" and not have them stack up over time.
## Additional context
This seems to only happem on world change, or dimension change.
Running bot.quit and relogging into the server resets it.

Easiest way to reproduce it:
1. Enter nether portal
2. Teleport bot to you
3. Loop

Might help:
https://gist.github.com/U5B/2243710e2c9ccd768d8ecdd375a86d48

**Comment by U5B** [comment]
My concern about this is memory leaks.

**Comment by rom1504** [comment]
this can be fixed there https://github.com/PrismarineJS/mineflayer/blob/1c75d3a37afaaa8c1c7cae4ce0119a8309650e4a/lib/plugins/blocks.js#L456

by removing the listeners when we change world

do you want to PR it ?

**Comment by U5B** [comment]
I do not know how to use github, what would be the process to PR it?

**Comment by rom1504** [comment]
push on a branch in your fork then https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by U5B** [comment]
Oh okay, I don't really know how to fix the problem in this with a PR since I am really unfamiliar with javascript programming.
