### ISSUE TITLE
chest.deposit() not working properly since mineflayer version 3.X.X

### ISSUE THREAD

**Issue by sefirosweb** [PrismarineJS/mineflayer#1720]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.2.0
 - server: vanilla 1.6.5
 - node: 1.14.#

## Detailed description of a problem
Since i updated mineflayer to 3.X+ the chest.deposit no works fine,

Is throwing this error randomly

![image](https://user-images.githubusercontent.com/20754836/109398924-f5e10f00-793f-11eb-9a83-f8c58ba9698d.png)

I see on logs the behavior of this function has been changed, now uses a windows functions
window.deposit
https://github.com/PrismarineJS/mineflayer/pull/1640/files?file-filters%5B%5D=.js#diff-43f2845439ef016d592378adeb4b9085fddb239031f857b1d76a51d631fa1d02

## Your current code
```js

  async depositToChest (itemType, quantity) {
    try {
      await this.chest.deposit(itemType, null, quantity)
    } catch (err) {
      console.log(err)
    }

```

The data is sending correctly, but sometimes the windows.deposits is broken

![image](https://user-images.githubusercontent.com/20754836/109399135-43aa4700-7941-11eb-8488-aa93d199c905.png)

**Comment by rom1504** [comment]
What code are you running ?

**Comment by sefirosweb** [comment]
Hi room I will refactorize my function,

In the previus version i can call deposit x300 dirt and they do it alone fine or call to bot.inventory.items() in each .deposit(),
But now seems this is not refresh enough fast,

Now i try to call 1 time to bot.inventory.items() and make a loop, instead call bot.inventiry.items() on each call of deposit

Now with new example seems works fine:

```js
const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node chest.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'chest',
  password: process.argv[5]
})

bot.once('spawn', () => {
  const mcData = require('minecraft-data')(bot.version)
  setTimeout(() => {
    openChest()
  }, 1000)

  let chest, itemsToDeposit
  async function openChest () {
    const chestToOpen = bot.findBlock({
      matching: ['chest', 'ender_chest', 'trapped_chest'].map(name => mcData.blocksByName[name].id),
      maxDistance: 3
    })

    chest = await bot.openChest(chestToOpen)
    itemsToDeposit = bot.inventory.items()
    depositItems()
  }

  async function depositItems () {
    if (itemsToDeposit.length === 0) {
      chest.close()
      return
    }

    const itemToDeposit = itemsToDeposit.shift()

    console.log(itemToDeposit.name)
    console.log(itemToDeposit.type)
    console.log(itemToDeposit.count)

    await chest.deposit(itemToDeposit.type, null, itemToDeposit.count)

    depositItems()
  }
})
```

**Comment by sefirosweb** [comment]
Hi @rom1504 I refactorized my code but still happens same erorr 

I'm going crazy, the code is VERY simple, I don't understand why it doesn't work,

I use mineflayer-statemachine and I have a behavior that is responsible for depositing objects and this is the one that does not work

Code:

```js
module.exports = class BehaviorDepositChest {
  constructor (bot, targets) {
    this.bot = bot
    this.targets = targets
    this.stateName = 'BehaviorDepositChest'
    this.isEndFinished = false
  }

  onStateEntered () {
    this.isEndFinished = false
    this.openCHest()
  }

  onStateExited () {
    this.isEndFinished = false
    this.targets.items = []
  }

  isFinished () {
    return this.isEndFinished
  }

  async openCHest () {
    const mcData = require('minecraft-data')(this.bot.version)
    const chestToOpen = this.bot.findBlock({
      matching: ['chest', 'ender_chest', 'trapped_chest'].map(name => mcData.blocksByName[name].id),
      maxDistance: 3
    })

    if (!chestToOpen) {
      this.isEndFinished = true
      return
    }

    const itemsToDeposit = this.bot.inventory.items()
    const chest = await this.bot.openChest(chestToOpen)

    while (itemsToDeposit.length > 0) {
      const itemToDeposit = itemsToDeposit.shift()
      console.log(itemToDeposit)
      await chest.deposit(itemToDeposit.type, null, itemToDeposit.count)
    }

    chest.close()
    this.isEndFinished = true
  }
}

```

**Comment by sefirosweb** [comment]
I finally found the package that causes this,
After many tests, I see that when I enable **mineflayer-web-Inventory**, it breaks the deposit function,

I don't know why, but the tests tell me this,
Maybe use a any windows function for check the inventory or something

**Comment by rom1504** [comment]
moved there https://github.com/imharvol/mineflayer-web-inventory/issues/19
