### ISSUE TITLE
Mineflayer Bot.craft() doesnt do anything

### ISSUE THREAD

**Issue by Shiiiwa** [PrismarineJS/mineflayer#1726]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.0.0
 - server: vanilla/spigot/paper 1.8.9
 - node: 15.5.1

## Detailed description of a problem
I wanted to try the crafting function in mineflayer. I´ve used the example given on this page:
https://github.com/PrismarineJS/mineflayer/blob/master/examples/inventory.js

But it doesnt seem to work. There isnt any error in the code or there isnt any stacktrace. The bot turns to the crafting table, clicks on it and then does nothing. The code after `bot.craft()` will be executed.
Even if he has the necessary items in his inventory, it wont craft anything.
## What did you try yet?

I used the method `bot.craft();` from the API. No error, stacktrace etc. The code for crafting an item is the same as in the example.

## Your current code
```

/*
// same code as in the example above

const recipe = bot.recipesFor(item.id, null, 1, craftingTable)[0]
JSON.stringify(console.log(recipe), null, 2) // below is the log for this object

Recipe {
  result: RecipeItem { id: 41, metadata: null, count: 1 },
  inShape: [
    [ [RecipeItem], [RecipeItem], [RecipeItem] ],
    [ [RecipeItem], [RecipeItem], [RecipeItem] ],
    [ [RecipeItem], [RecipeItem], [RecipeItem] ]
  ],
  outShape: null,
  ingredients: null,
  delta: [
    RecipeItem { id: 266, metadata: null, count: -9 },
    RecipeItem { id: 41, metadata: null, count: 1 }
  ],
  requiresTable: true
}

// After removing [0]
const recipe = bot.recipesFor(item.id, null, 1, craftingTable)
JSON.stringify(console.log(recipe), null, 2) // below is the log for this object

[
  Recipe {
    result: RecipeItem { id: 41, metadata: null, count: 1 },
    inShape: [ [Array], [Array], [Array] ],
    outShape: null,
    ingredients: null,
    delta: [ [RecipeItem], [RecipeItem] ],
    requiresTable: true
  }
]
*/


```

## Expected behavior
The Bot should craft the item with the given ID (in my case : gold_ingot to gold_block) but it doesnt do anything.

**Comment by rom1504** [comment]
bot.craft does work according to tests
if you still experience this please say (btw don't use hard coded item ids, take them from mcdata)
