### ISSUE TITLE
Bot can not handle with nicks

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer#1733]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: vanilla/spigot/paper 1.16.5
 - node: latest

## Detailed description of a problem
The bot does recognize nicknames as they are (and also returns something for the entity) but then fails to get the actual entity.
This is my code:

## Your current code
```js
if(bot.players[cmd[1]] && bot.players[cmd[1]].entity)
                target = bot.players[cmd[1]].entity
//...

goal_memory = [new goals.GoalFollow(target, 2), (cmd[2] ? (isYes(cmd[2]) ? true : false) : true)]
bot.pathfinder.setGoal(goal_memory[0], goal_memory[1])
```
Here the error:
```
node_modules\mineflayer-pathfinder\lib\goals.js:222
    this.x = Math.floor(entity.position.x)
                               ^

TypeError: Cannot read property 'position' of undefined
    at new GoalFollow (C:\NodeJS-Bot\node_modules\mineflayer-pathfinder\lib\goals.js:222:32)
    at parseCommand (C:\NodeJS-Bot\swarm_bot.js:256:28)
    at run (C:\NodeJS-Bot\swarm_bot.js:130:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

## Expected behavior
no crash, nickname recognize. Maybe go with the displayname instead of the actual name when getting the entity but idk.

**Comment by SinanAkkoyun** [comment]
Hi, turns out my code did not check if the entity exists, duh.

But anyways, it would be nice if the bot would be able to make out nicknames if thats even possible!

**Comment by DrMoraschi** [comment]
player.displayName should contain the nick

**Comment by SinanAkkoyun** [comment]
Thannks, I will try to implement a reverse search function that looks up if the entity contains this displayName, ty, brilliant!

**Comment by SinanAkkoyun** [comment]
Can somebody please help me to iterate through all bot.entities?

**Comment by SinanAkkoyun** [comment]
Hey guys, I fixed it:
```js
players = Object.values(bot.players).filter(player => player.displayName.toString().trim() === name.toString().trim())
```
