### ISSUE TITLE
Zombie entity attack

### ISSUE THREAD

**Issue by areny7** [PrismarineJS/mineflayer#1734]
- [ ] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [ ] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [ ] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 3.0.0
 - server: vanilla/spigot/paper #.#.#
 - node: 14

## Clear question
I need my robot to attack in a place all the time, because this place is a spawn tower I made, there will be a lot of different kinds of zombies fall down, consult the relevant API, and examples, but did not find useful information, so, I would like to know how I should achieve, is there any relevant examples?

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code

    function attack(){
        console.log('这里是attack');
        if(attack_stop === true){
            console.log('机器人已停止攻击！')
            return ;
        }
        let entity = bot.nearestEntity();
        console.log(entity);
        if(entity !== undefined && entity !== null && entity.position.distanceTo(bot.entity.position.offset(0,1,0)) > 5.6){
            entity = undefined;
        };
        if(entity !== undefined && entity !== null){
            bot.equip(mcData.itemsByName.iron_sword.id);
            bot.lookAt(entity.position);
            bot.attack(entity,true);
            setTimeout(attack, 100);
        }else{
            setTimeout(attack, 100);
            return;
        }
    }

```js

/*
Some code here, replace this
*/

```

**Comment by Zn10plays** [comment]
There is a relative example.
Try to look at https://github.com/PrismarineJS/mineflayer/blob/master/examples/guard.js
and see if it answers your question.

**Comment by sefirosweb** [comment]
mineflayer-pvp is a good point for start

If you want to do a bit more complex pvp bot, maybe you need to use a [mineflayer-statemachine,](https://github.com/PrismarineJS/mineflayer-statemachine)

In my case have a custom behavior and they use bow  on range distance and if detect is nearest or can't "see target" then change to melé,
Also they detect if one second mob is nearest than targets and switch to this one
https://github.com/sefirosweb/minecraftLegion/blob/master/NestedStateModules/combatFunction.js
Is a bit hard to read ^_^U
