### ISSUE TITLE
auto-eat

### ISSUE THREAD

**Issue by areny7** [PrismarineJS/mineflayer#1739]
In the automatic feeding, the server may not be able to eat at one time, so it needs to stop eating and then eat again. So in the "auto-eat" I used, errors were reported all the time during eating:Error: Consuming cancelled due to calling bot.consume() again,This causes me to be unable to execute things in the "AUTOEAT_STOPPED" event,How can I avoid this problem?

**Comment by areny7** [comment]
The robot may need to eat 3 times before it gets full, so I need to get an event, and then execute my code after eating. Now the problem is that I eat once and then execute my code once, and there will be a BUG. My description may not be complete, I hope you can understand

**Comment by rom1504** [comment]
can you open this on auto eat repo ?
