### ISSUE TITLE
click on tellraw message

### ISSUE THREAD

**Issue by FuntyGithub** [PrismarineJS/mineflayer#1741]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Clear question
Is it possible to let the bot click on a tellraw message? in the chat will be send a tellraw message what will run a command if you click on it. Can the bot click on it to run the command?

**Comment by SinanAkkoyun** [comment]
You could (if the message object contains the info) get the contents out of the message and execute the command by yourself manually, eg bot,chat("/command")

For testing purposes use JSON stringify to see all the contents of the message like so:

```js
bot.on("message", (msg) => {
    console.log(JSON.stringify(msg, null, 2))
}
```

Then, when you see what the content is and want to use it, just do something like (this is just an example)
msg.tellraw.toString() or something, idk, you can try it out

**Comment by SinanAkkoyun** [comment]
You could (if the message object contains the info) get the contents out of the message and execute the command by yourself manually, eg bot,chat("/command")

For testing purposes use JSON stringify to see all the contents of the message like so:

```js
bot.on("message", (msg) => {
    console.log(JSON.stringify(msg, null, 2))
}
```

Then, when you see what the content is and want to use it, just do something like (this is just an example)
msg.tellraw.toString() or something, idk, you can try it out

**Comment by SinanAkkoyun** [comment]
Were you able to resolve your issue?
