### ISSUE TITLE
(Issue) Mineflayer not compatible with node 12.16.0

### ISSUE THREAD

**Issue by circularsprojects** [PrismarineJS/mineflayer#1744]
I'm trying to make a mobile bot controller using play.js (iOS app) however play uses node version 12.16.0, and mineflayer is only compatible with 14 or higher. I used to be able to run mineflayer code in play back around when Minecraft version 1.16.1 was the latest. Is there a fix to this?

**Comment by DrMoraschi** [comment]
You can use 2.39.0 (i think) because that's the last version where you can use v12.
But apart from that, no I don't think there's a solution

**Comment by flowl** [comment]
node >= 14 version constraint has been pulled last christmas 🎄  in this PR https://github.com/PrismarineJS/mineflayer/pull/1529

This is the last release with node 12 support:

https://github.com/PrismarineJS/mineflayer/releases/tag/2.39.2

**Comment by rom1504** [comment]
can you ask play.js devs to update their app ?
mineflayer supports node 14
node 12 will go out of nodejs support in a year
