### ISSUE TITLE
Chat modularization : make chat work for all non-vanilla

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/mineflayer#175]
Currently, chat support is, IMO, broken. The current implementation kind-of works on vanilla minecraft, but doesn't work any kind of third-party chat systems, and there is no documentation about how to make it work, if possible at all.

As such, we need to modularize chat entirely. I propose removing chat.js entirely, and instead reworking it into a module system similar to #165. 

Essecially, we need to define three things : 
- Our own ChatMessage "class", which would work similarely to minecraft's, without the translation bit. It would have a toString method to return the raw string without any kind of color codes and a sender property to recover the sender.
- A ChatBase "interface", that defines convertMessage(string) and returns a ChatMessage. It also defines and implements a function, stringTojson (silly name, I know), that would transform the old format codes (those with the paragraph signs) into the equivalent proper json message as sent by newer servers. 
- A default chat implementation, that works on vanilla servers.

I think we don't need to actually provide support for any other chat systems, community will provide them as needed. It's not complicated to write one anyway. 

I'll start working on a PR to implement this tomorrow.

@nevercast

**Comment by rom1504** [comment]
related https://github.com/andrewrk/mineflayer/tree/chat-plugins

**Comment by zuazo** [comment]
Hey guys!

Thanks for all the work you are doing in these projects! I'm the one who did the old #165 PR and the [#chat-plugins](https://github.com/andrewrk/mineflayer/tree/chat-plugins) branch was also mine (it is the same code).

That code is old and I don't it will work as it is. Not to mention that it seems it was not the best solution. I think I was not very inspired at that moment. Also, I think that parsing the old (*non-JSON*) format no longer makes sense.

To avoid falling into the same error and seeing that it can be tricky or difficult to implement, I recommend starting by defining the exact API changes and how would be an ideal chat plugin example.

**Comment by rom1504** [comment]
Last issue before 1.1 release, it would be nice to get this done :)

**Comment by rom1504** [comment]
I'm not exactly sure what an "interface" would be in js ?
Also what of https://github.com/andrewrk/mineflayer/blob/master/lib/chat_message.js ?

I'm not sure fixing that issue needs to be blocking for 1.1 : vanilla server chat currently works, other formats probably not but they never really worked. Which mean no regression.
What do you think @roblabla @zuazo ?

**Comment by roblabla** [comment]
Doesn't need to be blocking.

In JS, an interface is an entry in the documentation. Maybe a base class with helper methods if necessary. And then a reference implementation (in our case, vanilla chat).

**Comment by zuazo** [comment]
I agree with @roblabla. If chat works for vanilla, the chat modularization task should not block the 1.1 release. I do not know how it would be the best way to implement an interface me neither.

**Comment by rom1504** [comment]
On that topic : 
Non verbal messages need to be emmited in some event. How to parse them : 
https://github.com/AlexKvazos/MinecraftChat/blob/master/app/server/parsers/vanilla.js

or something like http://hastebin.com/uvozajimex.coffee http://hastebin.com/tisalowasa (made by @roblabla )

**Comment by rom1504** [comment]
AFAIK chat is broken in 99% of real uses (ie people always come complaining it doesn't work)
I believe we should setup some automatic testing for chat for

spigot
paper
a selection of real servers out there
Testing would just be "check we can decode pseudo/message"

https://github.com/PrismarineJS/mineflayer/pull/605

**Comment by roblabla** [comment]
The problem is, we also need to test with a variety of plugins. And even then, there are many server that have very customized formats that we simply cannot hope to parse ourselves. This whole situation is a mess.

**Comment by rom1504** [comment]
Well yes, we probably won't support all formats since anyone can create new ones. But it would be convenient if we could support formats of popular servers and make it clear and easy how to add new formats (and automatically testing them would be nice)

**Comment by rom1504** [comment]
We went with chat patterns and some universal (default) ones that work ok enough. I consider this done
