### ISSUE TITLE
  options.username = options.username ?? 'Player'

### ISSUE THREAD

**Issue by hwamzz** [PrismarineJS/mineflayer#1751]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.0.0
 - server: spigot 1.8.9
 - node: 12.13.0

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
I get the error 

  options.username = options.username ?? 'Player'
                                       ^

SyntaxError: Unexpected token '?'

when I try to run my code.

What are you building? What problem are you trying to solve?

Just starting out and testing to join a server.

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

Tried the basic example of creating a bot.

## Your current code
```
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'play.blizzardmc.org',
  username: 'email of the account here in code',
  password: 'password here in code'
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)

```

## Expected behavior

The bot to login to the server.

**Comment by Karang** [comment]
Mineflayer supports only node > 1.14. Update your node.

**Comment by hwamzz** [comment]
Thanks :)
