### ISSUE TITLE
how to make a chat limit? | как сделать лимит на чат?

### ISSUE THREAD

**Issue by Msgumor** [PrismarineJS/mineflayer#1756]
RU: как сделать лимит на чат?
EN: how to make a chat limit?

bot.on('login', function() {
	console.log("Bot started.");
	bot.chat('/register dffdfsdf')
	bot.chat('/l dffdfsdf')
});

**Comment by rom1504** [comment]
what kind of limit ?

**Comment by Msgumor** [comment]
chat message delay

**Comment by rom1504** [comment]
```js
let i= 10
function chatLimit(message)
{
i-=1
if(i < 0 ) { return }
bot.chat(message)
}
```

Here's a chat limit.

Feel free to reopen if you want to explain your problem

**Comment by Msgumor** [comment]
The bot does not send messages to the chat
