### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by sando1234** [PrismarineJS/mineflayer#1757]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.3.0
 - server: vanilla/spigot/paper 1.16.5
 - node: 14.16.0

## Detailed description of a problem
[[A/srv/mineflyer/strip.js:85
bot.inventory.items()
              ^

TypeError: Cannot read property 'items' of undefined
    at Object.<anonymous> (/srv/mineflyer/strip.js:85:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

## Your current code
const mineflayer = require('mineflayer')
const { mineflayer: mineflayerViewer } = require('prismarine-viewer')
const vec3 = require('vec3')
const debug = true;

// node strip.js <host> <name> <password>
//   0      1       2      3        4
if (process.argv.length != 5) {
    console.log('Usage: node strip.js <host> <name> <password>')
    process.exit(1)
}

const bot = mineflayer.createBot({
    host: process.argv[2],
    port: 1,
    username: process.argv[3],
    password: process.argv[4]
})

bot.on('kicked', console.log)
bot.on('error', console.log)

bot.once('spawn', () => {
    mineflayerViewer(bot, { port: 3000, firstPerson: true})
})

const log = message => {
    if (debug) bot.chat(message)
}

bot.on('chat', (username, message) => {
    console.log(message)
    if (username === bot.username) return
    const command = message.split(' ')

    if (command[0] == 'jump') {
        bot.setControlState('jump', true)
        bot.setControlState('jump', false)
    }
})

//bot.waitForChunksToLoad()

bot.inventory.items()
/*while (true) {
    const items = bot.inventory.items()
    console.log(items)
}*/

## Expected behavior
That i can use bot.inventory.items

**Comment by DrMoraschi** [comment]
Put it inside the spawn event
