### ISSUE TITLE
Farming example no longer works?

### ISSUE THREAD

**Issue by SpencerGreene** [PrismarineJS/mineflayer#1759]
- [ X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.3.1
 - server: spigot 1.16.5
 - node: 14.16.0

## Detailed description of a problem
In examples/farmer.js, the sowing function appears to not work.

Steps to reproduce:
1. Dig out a few blocks of grass and replace with dirt,
2. Hoe,
3. Place water,
4. Invoke farmer.js,
5. Give him seeds,
6. Watch him wave his arm but never plant anything.

There are two separate issues.
First, ```const blockAbove = bot.blockAt(block.position.offset(0, 1, 0))``` throws because position is null.

Second, if you get past that (which I did by just ignoring the blockAbove test), then the farmer tries to do something - he waves his arm - but no planting occurs.  The placeBlock throws an error "Place failed Error: No block has been placed : the block is still air"

## What did you try yet?

As noted above: removed the blockAbove test (which was throwing).  Also tried both placeBlock (from the example) and activateBlock, as you can see below.  The placeBlock throws the error above.  The activateBlock does not throw but also does not successfully plant.

## Your current code
```js
const Vec3 = require('vec3')
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'localhost',
  port: 25565,
  username: 'farmer',
})

let mcData
bot.on('inject_allowed', () => {
  mcData = require('minecraft-data')(bot.version)
})

var count = 0

// To farm we have to give bot the seeds
// /give farmer wheat_seeds 64

function blockToSow () {
  return bot.findBlock({
    point: bot.entity.position,
    matching: (block) => {
      if (block && block.type === mcData.blocksByName.farmland.id) {
        // The following line fails because position is null,
        // so comment it out for now.  Just don't try if something is above.
        // const blockAbove = bot.blockAt(block.position.offset(0, 1, 0))
        // return !blockAbove || blockAbove.type === 0
        return true 
      }

      return false
    }
  })
}

function blockToHarvest () {
  return bot.findBlock({
    point: bot.entity.position,
    matching: (block) => {
      return block && block.type === mcData.blocksByName.wheat.id && block.metadata === 7
    }
  })
}

async function loop () {
  try {

    const toHarvest = blockToHarvest()
    if (toHarvest) {
      return bot.dig(toHarvest, () => {
        return setImmediate(loop)
      })
    } else console.log(count, 'nothing to harvest')

    const toSow = blockToSow()
    if (toSow) {
      // since we didn't test in the findBlock, let's test here
      const blockAbove = bot.blockAt(toSow.position.offset(0, 1, 0))
      if (blockAbove && blockAbove.type !== 0) {
        console.log('cannot plant because there is already', blockAbove)
      }

      // this is what the original example did
      await bot.equip(mcData.itemsByName.wheat_seeds.id, 'hand')
      try {
        await bot.placeBlock(toSow, new Vec3(0, 1, 0)) 
      } catch (placeError) {
        console.log('Place failed', placeError)
      }

      // tried activateBlock as well, also no dice
      try {
        await bot.activateBlock(toSow) 
      } catch (activateError) {
        console.log('Activate failed', activateError)
      }    } else console.log(count, 'nothing to sow')

  } catch (e) {
    console.log(e)
  }
  count = count + 1  // just so we can see console changing

  // Postpone next loop a bit
  setTimeout(loop, 1000)
}

bot.once('login', loop)
```

## Expected behavior
Expected the seeds to be planted one one block then bot to move on to the next available.

## Additional context
Harvest also fails - if you plant wheat manually the bot also waves his arm trying to harvest it.  But once the sowing is diagnosed I suspect the harvesting issue will be obvious.

**Comment by alebaldissera** [comment]
I have the same issue. It seems that farmlands doesn't have a position. In fact if you try to print 'block' on blockToSow() it say null on field 'position'. Wheat instead has position setted correctly

**Comment by u9g** [comment]
yes, it doesnt work due to a few reasons, for the matcher not returning a block with a position, adding `useExtraInfo: true` to the findblock options should give the .position in the block object. The bigger problems are with the rest of the example

**Comment by SpencerGreene** [comment]
@u9g any hints on what made it not work?  I'm happy to attempt a fix and PR, but not sure where to start.

**Comment by u9g** [comment]
uh, theres a few things, if you add what I said above and try it on a server, you can start to see, that 1) theres no check for how far can the bot place/break, or a check for if the bot has seeds before it plants them (i guess this isnt a problem, but its an easy fix), and after that, you will see that dig resolves too quickly and placeblock throws an error every time, (in my testing)

**Comment by SpencerGreene** [comment]
For (1) in my simple test the bot was right next to the block, and (2) it has the seeds.  Agreed (4) is what I'm seeing with place block throwing every time.  Do you think that (3) the dig resolving too quickly is why the place block fails?

**Comment by u9g** [comment]
(4) is what I'm seeing with place block throwing every time.  Do you think that (3) the dig resolving too quickly is why the place block fails?


Now that I think about it, yeah, probably. The bot.dig needs a fix, and then I think it'll fix the placing

**Comment by SpencerGreene** [comment]
Hm actually in the planting code I don't see any call to bot.dig.  Seems like that would be in the harvest not the sow.  Am I missing something?

**Comment by u9g** [comment]
> Hm actually in the planting code I don't see any call to bot.dig.  Seems like that would be in the harvest not the sow.  Am I missing something?

Why would it be in the planting code? iirc it should be in the harvest code, no?

**Comment by SpencerGreene** [comment]
Right, agreed.  So the planting code is failing for some other reason, distinct from whatever is failing in bot.dig.

**Comment by u9g** [comment]
They happen in series, so bot.dig could have not been awaited long enogh before placeblock is called causing problems but thats just a guess

**Comment by SpencerGreene** [comment]
in the simple farmer example the planting doesn't do any dig operation, it assumes everything is already prepared.  So that's why I'm thinking the planting is another thing separate from dig

**Comment by u9g** [comment]
> in the simple farmer example the planting doesn't do any dig operation, it assumes everything is already prepared. So that's why I'm thinking the planting is another thing separate from dig

are we thinking of the same code? https://github.com/PrismarineJS/mineflayer/blob/f0e0f255952dab0e4fa5d9c93484d9b7747d96ff/examples/farmer.js#L51

**Comment by SpencerGreene** [comment]
No for me it's the sow that's failing not the harvest.  But I think it's actually just the findBlocks problem.  So on the sowing I think I'm on the right track.  Thanks.

**Comment by rom1504** [comment]
now fixed
