### ISSUE TITLE
Took too long to log in

### ISSUE THREAD

**Issue by Lusiny** [PrismarineJS/mineflayer#1762]
## Error Message
For some reason when i try to log in in minecraft with method createBot it appears a message saying " "Took too long to log in" false", how can i fix it?

## What did you try yet?

I changed the username, password and ... nothing happened.

## Current code
My code:

```js
const mineflayer = require('mineflayer')
let player = mineflayer.createBot({
    host: "localhost",
    port: 25565,
    username: 'email',
    password: 'password',
    checkTimeoutInterval: 30000
}) 
player.on('kicked', console.log);
player.on('error', console.log);
player.on('login', () => { console.log("I'm in") });
```

**Comment by u9g** [comment]
It's not an error, its a kicked message. maybe try getting rid of checkTimeoutInterval

**Comment by Lusiny** [comment]
Returned the same thing! Looking at the server console we have this:
```java
Disconnecting com.mojang.authlib.GameProfile@412a81ea[id=<null>,name=Lusinho555,a={},legacy=false] (/myip): Took too long to log in
com.mojang.authlib.GameProfile@412a81ea[id=<null>,name=Lusinho555,properties={},legacy=false] (/myip) lost connection: Timed out
```
Por algum motivo demorou muito para me retornar o erro!

My current code:
```js
const mineflayer = require('mineflayer')

let player = mineflayer.createBot({
    host: "localhost",
    port: 25565,
    username: 'email',
    password: 'password',
}) 
player.on('kicked', console.log);
player.on('error', console.log);
player.on('login', () => { console.log("I Joined") });
```

**Comment by u9g** [comment]
`checkTimeoutInterval`'s default is `30000`, maybe try `240000` instead

**Comment by Lusiny** [comment]
It returned the same message **"Took too long to log in" false"** actually!

Regarding your suggestion, I noticed that the default of the `check Timeout Interval` would be `300000` and not `30000` by logic.
So instead of putting `240000` I put `24000` and the error message returned me faster.

By the name I imagine it is what determines the time interval in which you check if you have been kicked.
