### ISSUE TITLE
Chat Spammer

### ISSUE THREAD

**Issue by Msgumor** [PrismarineJS/mineflayer#1767]
## Versions
 - mineflayer: 3.2.0
 - server: Spigot
 - node: 14.16.0

How to force a bot to have a spammer when entering the server, messages must be from the config and different, and moreover, the limit for these messages must be in order to bypass the kicked from spamming system

message a spam

bot.chat('Message1')
limit a chat message
bot.chat('Message2')

**Comment by rom1504** [comment]
Here's a better idea: don't spam
Thanks
