### ISSUE TITLE
bot.username undefined

### ISSUE THREAD

**Issue by EaterSteam** [PrismarineJS/mineflayer#1783]
If the bot gets disconnected before joining the server for reasons like Server Full, etc. bot.username gets logged as undefined

**Comment by EaterSteam** [comment]
https://prnt.sc/10q1lfs

**Comment by u9g** [comment]
what is your code?

**Comment by EaterSteam** [comment]
const bot = mineflayer.createBot({
        host: "jartex.fun",
        username,
        version: "1.8",
        plugins:{
            chest: false,
            conversions: false,
            dispenser: false,
            enchantment_table: false,
            furnace: false,
            math: false,
            painting: false,
            scoreboard: false,
            villager: false,
            bed: false,
            block_actions: false,
            blocks: false,
            book: false,
            boss_bar: false,
            command_block: false,
            craft: false,
            digging: false,
            experience: false,
            physics: false,
            rain: false,
            ray_trace: false,
            sound: false,
            tablist: false,
            time: false,
            title: false
        }
    });
        bot.on("end", () => {
        console.log(bot.username + " has ended.")
    });

**Comment by u9g** [comment]
try bot.player.username?

**Comment by EaterSteam** [comment]
> 
> 
> try bot.player.username?

amma try it and let you know in some time

**Comment by u9g** [comment]
where did you find the code bot.username?

**Comment by EaterSteam** [comment]
https://prnt.sc/10qx2kv

**Comment by EaterSteam** [comment]
i didnt find it nowhere xd

**Comment by u9g** [comment]
regardless, username is undefined after bot has ended. You can store the bot's username to a variable when it logs in (if it logs in), but if it doesnt login idk

**Comment by EaterSteam** [comment]
> 
> 
> regardless, username is undefined after bot has ended. You can store the bot's username to a variable when it logs in (if it logs in), but if it doesnt login idk

no thats what i m saying if it doesnt even connect to the server for reasons like Server Full, We are having too many connections. or something else it pops up as undefined

**Comment by Moondarker** [comment]
If you are trying to identify which bot gets kicked, just add a custom property to the bot object right after `mineflayer.createBot` call and read it back on `end`

**Comment by EaterSteam** [comment]
well thats the issue i dont know how to do that stuff xd

**Comment by u9g** [comment]
https://javascript.info/object

**Comment by EaterSteam** [comment]
> 
> 
> If you are trying to identify which bot gets kicked, just add a custom property to the bot object right after `mineflayer.createBot` call and read it back on `end`

also i m not trying to check which bot gets kicked i push the username into an array which reconnects the bot, idk any other alternative tbh

**Comment by u9g** [comment]
> > If you are trying to identify which bot gets kicked, just add a custom property to the bot object right after `mineflayer.createBot` call and read it back on `end`
> 
> also i m not trying to check which bot gets kicked i push the username into an array which reconnects the bot, idk any other alternative for reconnecting multiple bots

this isn't a mineflayer issue anymore, please come to the discord if you want help with code

**Comment by EaterSteam** [comment]
well can you still not make it so bot.username doesnt get logged as undefined?

**Comment by u9g** [comment]
> well can you still not make it so bot.username doesnt get logged as undefined?

go to the discord if you want help, issues tab is for mineflayer issues
