### ISSUE TITLE
Add docs, examples, .github to .npmignore

### ISSUE THREAD

**Issue by wvffle** [PrismarineJS/mineflayer#1786]
## Is your feature request related to a problem? Please describe.
The npm package is bloated.

## Describe the solution you'd like
Add `docs`, `examples`, `.github` to `.npmignore`

Also any configuration dotfiles that are not needed in production.

**Comment by rom1504** [comment]
I don't see any benefit to doing that. We would gain a few kB.
However it increase complexity and decrease a bit the usability of what's in node_modules
