### ISSUE TITLE
Explosion Calculation

### ISSUE THREAD

**Issue by link-discord** [PrismarineJS/mineflayer#1789]
## Is your feature request related to a problem? Please describe.
No it is not.

## Describe the solution you'd like
It would be nice to intergrate functions to calculate explosion damage for entitys as well explosion exposure so it is easier to get how much damage an explosion would do. 

List of features that should be implemented

- A function to calculate explosion exposure that takes a explosion position and a second position as well as blast radius and explosion strength

- A function to calculate explosion damage which would take a position of an explosion and a second position again and also use the function to calculate explosion exposure to calculate the damage that would be done 

- Add blast resistence Information to blocks which would be needed to calculate the explosion exposure as well as the damage

## Resources
[fandom wiki](https://minecraft-archive.fandom.com/wiki/Explosion) 

[explosion java function](https://github.com/OxideWaveLength/Minecraft-Hack-BaseClient/blob/74bf707dbd97df40812e59a2e76f1a9a6abb65c8/minecraft/net/minecraft/world/Explosion.java#L123)

[second part of the explosion function](https://github.com/OxideWaveLength/Minecraft-Hack-BaseClient/blob/74bf707dbd97df40812e59a2e76f1a9a6abb65c8/minecraft/net/minecraft/world/World.java#L1853)

**Comment by rom1504** [comment]
Tasks:
* [ ] Add blast resistance data to minecraft data
* [ ] Write dummy functions with the right input and output
* [ ] Write tests and doc for them
* [ ] Actually code them

**Comment by Karang** [comment]
https://minecraft.gamepedia.com/Explosion has some good infos too

**Comment by LenniDev** [comment]
This would be great for crystal pvp.

**Comment by rom1504** [comment]
done ?
