### ISSUE TITLE
Expand Block Entity support

### ISSUE THREAD

**Issue by nevercast** [PrismarineJS/mineflayer#179]
Implement support for the remaining Block Entities.
- [ ] Anvils (https://github.com/andrewrk/mineflayer/issues/120)
- [ ] Brewing Stands (https://github.com/andrewrk/mineflayer/issues/119)
- [ ] Beacon

Comment if I've missed some.

A more modular approach to this might be to split the implementation of inventories out of the inventory plugin and have the inventory plugin as a generic base class.

Then Chests, Furnaces, Anvils etc would become their own file.

**Comment by rom1504** [comment]
tile entities are now called block entities (see http://minecraft.gamepedia.com/Block_entity). Changing the title of that issue.

**Comment by rom1504** [comment]
This is contained in #237

**Comment by Gjum** [comment]
Could be closed as it's contained in #237.

**Comment by rom1504** [comment]
Yeah let's close it
