### ISSUE TITLE
Digging error

### ISSUE THREAD

**Issue by kirillbul** [PrismarineJS/mineflayer#1798]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.4.0
 - server: spigot 1.13
 - node: 14.16.0

## Detailed description of a problem
When digging, this error sometimes appears. 

## What did you try yet?

bot.dig(block, 'ignore')

## Error

```
(node:35) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
at EventEmitter.onBlockUpdate (/app/node_modules/mineflayer/lib/plugins/digging.js:154:20)
at EventEmitter.emit (events.js:315:20)
at switchWorld (/app/node_modules/mineflayer/lib/plugins/blocks.js:463:15)
at Client.<anonymous> (/app/node_modules/mineflayer/lib/plugins/blocks.js:489:5)
at Client.emit (events.js:327:22)
at FullPacketParser.<anonymous> (/app/node_modules/minecraft-protocol/src/client.js:91:12)
at FullPacketParser.emit (events.js:315:20)
at addChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)
at readableAddChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:280:11)
at FullPacketParser.Readable.push (/app/node_modules/readable-stream/lib/_stream_readable.js:241:10)
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

## Expected behavior

Digging without a problem.

## Additional context
-

**Comment by rom1504** [comment]
Please read the doc. bot.dig takes arguments

**Comment by kirillbul** [comment]
> Please read the doc. bot.dig takes arguments

I use `bot.dig` with arguments. The error occurs when `bot.dig(block, 'ignore')`

**Comment by kirillbul** [comment]
@rom1504 Please open this issue. In the description, the method used was incorrect, now I have added it. And still this error appears.

**Comment by rom1504** [comment]
Can you put share more code ?

**Comment by kirillbul** [comment]
> Can you share more code ?


```js
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'localhost',
  port: 25565,
  username: 'nick',
  version: '1.13.1'
})

bot.on('chat', (username, message) => {
  console.log(message)
  if (message == 'dig block') {
    dig();
  }
})

bot.on('kicked', console.log)
bot.on('error', console.log)

async function dig() {
  var block = bot.blockAtCursor()
  if (block) {
    await bot.dig(block, 'ignore', () => console.log('Success!'))
  }
}
```

**Comment by kirillbul** [comment]
> Can you share more code ?

I want to point out that this started after the update from 2.41.0 to 3.4.0.

**Comment by Karang** [comment]
Given the error message this happen when you started to dig but before it is finished, you respawn (die or teleported ?).
It should be fixed in digging.js to not throw an error but instead cancel the dig properly.

**Comment by kirillbul** [comment]
> Given the error message this happen when you started to dig but before it is finished, you respawn (die or teleported ?).
> It should be fixed in digging.js to not throw an error but instead cancel the dig properly.

The bot was standing still at the moment of the error, could it be due to a block shift?

**Comment by Karang** [comment]
No the block update is explicitly triggered by the respawn event: https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/blocks.js#L486

So there must be something special about your setup that is triggering the respawn.

**Comment by kirillbul** [comment]
> No the block update is explicitly triggered by the respawn event: https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/blocks.js#L486
> 
> So there must be something special about your setup that is triggering the respawn.

Ooh, I'll think about it.
Thanks for the help!
