### ISSUE TITLE
how do I make a bot say its coords

### ISSUE THREAD

**Issue by NoRegret-fake-malware** [PrismarineJS/mineflayer#1801]
so I want to make a bot say its coords but I don't know how to can some one tell me how to

**Comment by KennyHarrer** [comment]
bot.chat(bot.entity.position)
Please consider reading the API.

**Comment by miquelvidal** [comment]
Dear @NoRegret-fake-malware 

Really I'm new on this, but for me :+1: 
//bot.chat(bot.entity.position); --> not work
  bot.chat(''+bot.entity.position); --> work

Regards, Miquel
