### ISSUE TITLE
Proxies with Socks5-Client not working

### ISSUE THREAD

**Issue by foxikdev** [PrismarineJS/mineflayer#1834]
Hi. I'm working on new project and I use proxies there. The problem is Socks5-Client isn't working for me and other developer. I tried about 5 code examples. Can you recommend me good scraping proxy API (you don't need to do that, I already have some - api.proxyscrape.com) and whole code for proxy example? I only found part of code but none worked. btw. I used socks5-client and 'http'. Thx.

**Comment by Msgumor** [comment]
proxy they also do not work for me

**Comment by IceTank** [comment]
There is a socks5 example in node-minecraft-protocol:
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js. 
Mineflayer uses node-minecraft-protocol for its connections. If the example does not work it is most likely due to the proxy not working or the mojang authentication servers blocking the proxy connection.

**Comment by Msgumor** [comment]
> There is a socks5 example in node-minecraft-protocol:
> https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js.
> Mineflayer uses node-minecraft-protocol for its connections. If the example does not work it is most likely due to the proxy not working or the mojang authentication servers blocking the proxy connection.

this code doesn't work

**Comment by IceTank** [comment]
The example is working for me on the newest version of mineflayer and on the newest version of node-minecraft-protocol. I tested it on a socks5 proxy connection with no authentication, connecting to a online 1.12.2 Minecraft server. 
What is the error you get?

**Comment by Msgumor** [comment]
no error, just the bot does not connect to the server

**Comment by IceTank** [comment]
What does it say when you add `bot.on('error',console.log)` at the end of your script?

**Comment by Msgumor** [comment]
ocksClientError: connect ETIMEDOUT 80.234.40.124:1080
    at SocksClient.closeSocket (C:\Users\User\node_modules\socks\build\client\socksclient.js:387:32)
    at SocksClient.onErrorHandler (C:\Users\User\node_modules\socks\build\client\socksclient.js:360:14)
    at Socket.onError (C:\Users\User\node_modules\socks\build\client\socksclient.js:222:38)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  options: {
    proxy: { host: '80.234.40.124', port: 1080, type: 5 },
    command: 'connect',
    destination: { host: 'ip', port: 25565 }
  }
}

**Comment by IceTank** [comment]
Looks like the proxy server is not working or the Minecraft server is for some reasone rejecting the connection

**Comment by IceTank** [comment]
Make sure the proxy is working. Try this in Windows command prompt or any unix based system:
`curl -x "socks5://<proxyHost>:<proxyPort>" "http://ifconfig.me"`
If you see an ip address the proxy is working as a proxy if you see anything else the Proxy is not working.

**Comment by Msgumor** [comment]
curl: (7) Failed to receive SOCKS5 connect request ack.

but the proxy is working

**Comment by IceTank** [comment]
If the proxy you are trying to connect to has a hostname instread of an ip address you can try and change [this line](https://github.com/PrismarineJS/node-minecraft-protocol/blob/61789bbea9cbb8a746d0460c176067ff4076cfbb/examples/client_socks_proxy/client_socks_proxy.js#L36) to `socks5h` instead of `socks5`. Or you could connect to the proxy with its ip address.

**Comment by aesthetic0001** [comment]
this issue should be closed I think
