### ISSUE TITLE
Add `bot.reconnect()`

### ISSUE THREAD

**Issue by FeixuRuins** [PrismarineJS/mineflayer#1835]
## Is your feature request related to a problem? Please describe.
It's a pain to reconnect the bot when it's kicked.

## Describe the solution you'd like
Some way for it to log back in.

**Comment by rom1504** [comment]
You can follow the same pattern as https://github.com/PrismarineJS/mineflayer/blob/master/examples/reconnector.js

For the in-built function, duplicate of #975
