### ISSUE TITLE
Improve proxy docs

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1845]
## Is your feature request related to a problem? Please describe.
People don't know if their proxy works, so when it doesn't they don't know that, so then they complain mineflayer doesn't work.

## Describe the solution you'd like
A guide on how to test a proxy + clearer proxy errors

## Describe alternatives you've considered
explaining it for every one

## Additional context
none

**Comment by rom1504** [comment]
Duplicate of https://github.com/PrismarineJS/mineflayer/issues/438
