### ISSUE TITLE
DoubleChest Handling

### ISSUE THREAD

**Issue by SaubereSache** [PrismarineJS/mineflayer#1846]
## Is your feature request related to a problem? Please describe.
Suppose one wants to open all double chest in the proximity of the bot. 
The following code snipped returns two blocks per double chest, and there is no clear way to tell which block belongs to which double chest.
``bot.findBlocks({
			matching: this.mcData.blocksByName["chest"].id,
			maxDistance: 6,
			count: 64,
})``

## Describe the solution you'd like
An easy way to identify the blocks a double chest is made up of.

## Describe alternatives you've considered
Tried using StateId, but was unable to correctly parse the different states easily. Requires advanced Minecraft knowledge for a problem many developers will run into.

**Comment by u9g** [comment]
here's how you would parse stateId, `const chests = bot.findBlocks({ matching: mcData.blocksByName.chest.id, maxDistance: 6, count: 64 }).map(o => bot.blockAt(o)).map(o => o.getProperties())` but it isnt helpful in this context,

**Comment by SaubereSache** [comment]
Actually this really helped me, for whatever reason this function wasn't present in the type definitions.
Block#getProperties returns `{ waterlogged: false, type: 'left', facing: 'south' }` which allows me to calculate the position of the second block, but I agree that it would be beneficial to have that functionality exposed by default.
