### ISSUE TITLE
Chest deposit failing

### ISSUE THREAD

**Issue by SaubereSache** [PrismarineJS/mineflayer#1851]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.6.0
 - server: spigot 1.16.5
 - node: 14.16.1

## Detailed description of a problem
Trying to deposit the bots inventory to chest(s). Chest#deposit fails internally.
Stacktrace:
`TypeError: Cannot read property 'type' of null
    at clickDest (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:223:51)
    at transferOne (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:220:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async transfer (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:203:5)
    at async C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:292:7
    at async StorageModule.depositItemsInInventory (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\src\modules\storage\StorageModule.js:175:7)`

## What did you try yet?

Consulted examples/chest.js, everything seems to be done the same way.

## Your current code
```js
async depositItemsInInventory() {
	for (const item of this.bot.inventory.items()) {
		let itemName = item.name;
		let itemType = item.type;
		console.log(itemName)

		let result = await this.findUnfinishedStack(itemName) // returns coordinates of chests
		if (result && result.length > 0) {
			let remainingItemCount = item.count
			for(const entry of result) {
				if(remainingItemCount === 0) break

				let chest = this.bot.blockAt(new Vec3(entry.x, entry.y, entry.z));
				if(!chest) {
					console.error("Chest found in database but not ingame!", chest)
				} else {
					let inventory = await this.openChest(chest)
					let currentCount = inventory.count(itemType, null);
					let remainingStackSize = item.stackSize - (currentCount % item.stackSize)

					let depositSize = remainingStackSize > remainingItemCount ? remainingItemCount : remainingStackSize
					await inventory.deposit(itemType, null, depositSize).catch(console.error) // < - - - - - FAILS HERE
					remainingItemCount -= depositSize

					await inventory.close()
					await this.bot.waitForTicks(1)
				}
			}

		}
	}
}
```

## Expected behavior
Bot deposits items into chest

## Additional context
-

**Comment by SaubereSache** [comment]
More understandable code snippet:
```js
	let chestBlock = bot.blockAt(new Vec3(96, 80, 130))
	bot.openChest(chestBlock).then((inventory) => {
		inventory.deposit(bot.mcData.itemsByName["bread"].id)
			.then(() => bot.waitForTicks(2)
				.then(inventory.close())
			).catch(console.error)
	})
```
And the stacktrace:
```
TypeError: Cannot read property 'type' of null
    at clickDest (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:223:51)
    at transferOne (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:220:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async transfer (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:203:5)
    at async C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:292:7
```

**Comment by aesthetic0001** [comment]
have you tried the chest.js example?

**Comment by u9g** [comment]
> More understandable code snippet:
> 
> ```js
> 	let chestBlock = bot.blockAt(new Vec3(96, 80, 130))
> 	bot.openChest(chestBlock).then((inventory) => {
> 		inventory.deposit(bot.mcData.itemsByName["bread"].id)
> 			.then(() => bot.waitForTicks(2)
> 				.then(inventory.close())
> 			).catch(console.error)
> 	})
> ```
> 
> And the stacktrace:
> 
> ```
> TypeError: Cannot read property 'type' of null
>     at clickDest (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:223:51)
>     at transferOne (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:220:13)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async transfer (C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:203:5)
>     at async C:\Users\Constantin Schreiber\WebstormProjects\minecraft_storage_bot\node_modules\mineflayer\lib\plugins\inventory.js:292:7
> ```

Can you describe the conditions around the bot a bit? I put a valid chest location into the vec3, then open a chest that has open slots, then put in a stack of bread, no problems, anything different about your setup?

**Comment by SaubereSache** [comment]
Not a mineflayer issue, mineflayer-web-inventory is the culprit.
The issue is tracked at their github: https://github.com/imharvol/mineflayer-web-inventory/issues/20
