### ISSUE TITLE
Chest deposit stuck

### ISSUE THREAD

**Issue by SaubereSache** [PrismarineJS/mineflayer#1859]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.6.0
 - server: spigot 1.16.5
 - node: 14.16.1

## Detailed description of a problem
* Fill a chest completely with stone, leave the last stack half full (count 32)
* Give your bot some stacks stone and a stack with 4 stone blocks
* Bot will deposit the items but will be stuck at deposit

## Your current code
```js
let testChest = bot.blockAt(new Vec3(91, 80, 124))
bot.openChest(testChest).then((inventory) => {
    inventory.deposit(bot.mcData.itemsByName["stone"].id, null, 32).then(() => inventory.close())
})
```

## Expected behavior
Chest#deposit resolves after depositing the items, but never does

## Additional context
![image](https://user-images.githubusercontent.com/53787471/114928063-6f6e8700-9e32-11eb-8bd0-a23123c00b0d.png)
![image](https://user-images.githubusercontent.com/53787471/114928070-71384a80-9e32-11eb-8b80-a9f38dc42563.png)
![image](https://user-images.githubusercontent.com/53787471/114928119-82815700-9e32-11eb-896b-3c490ec9783f.png)

**Comment by SaubereSache** [comment]
Workaround:
```
await Promise.race([
  inventory.deposit(itemType, null, depositSize),
  this.bot.waitForTicks(10)
])
```
but for sure not a permanent solution.

**Comment by sefirosweb** [comment]
Hi SaubereSache i have same issue

When I try to deposit massive items the bot stucks

```js
  async depositItems () {
    if (this.targets.items.length === 0) { return }
    const itemToDeposit = this.targets.items.shift()
    console.log(itemToDeposit)

    try {
      console.log('Depositing...' + Date.now())
      await this.chest.deposit(itemToDeposit.type, null, itemToDeposit.quantity)
      console.log('Deposited ' + Date.now())
    } catch (err) {
      console.log(err)
      return
    }

    console.log('')
    await this.depositItems()
  }
```
They stop forever in awaitin chest.deposit, and no errors

![image](https://user-images.githubusercontent.com/20754836/122638778-65992680-d0f6-11eb-8594-56bf392bcfc0.png)

**Comment by SaubereSache** [comment]
Just use Promise#race, mineflayers Inventory handling is pretty fucked and noone bothers to even touch it with a 2 meter stick

**Comment by sefirosweb** [comment]
I tried a few times to look wich happening in the core, 

But is a bit complex for me @_@

In the version previus as "Windows" they works fine but after they broke,

This function is very importnat for a me, because i'm mading a very complex bots with farming / mining / skinning function and must need to deposit items :(

I will try again to take a look again,

**Comment by sefirosweb** [comment]
Hi @SaubereSache, you can see a new "container" managment, seems is a great work from owners,

Now using "openContainer" works at perfectly!  and also is updated webinventory and fixed the bugs they have with windows

For my side is complety  works fine, i recomend you to do a bit refactorize

Ex my cod:
```js

this.bot.openContainer(chestToOpen)
      .then((container) => {
        this.depositItems(container)
          .then(async () => {
            await sleep(200)
            await container.close()
            await sleep(500)
            this.isEndFinished = true
          })
      })


depositItems (container) {
    return new Promise((resolve, reject) => {
      if (this.items.length === 0) {
        resolve()
        return
      }
      const itemToDeposit = this.items.shift()

      container.deposit(itemToDeposit.type, null, itemToDeposit.quantity)
        .then(() => {
          this.depositItems(container)
            .then(() => {
              resolve()
            })
            .catch(err => {
              reject(err)
            })
        })
        .catch(err => {
          reject(err)
        })
    })
  }
```

Best!
