### ISSUE TITLE
how to add messages and random chat

### ISSUE THREAD

**Issue by Msgumor** [PrismarineJS/mineflayer#1869]
how to make a bot write a random chat message

**Comment by DrMoraschi** [comment]
Please ask on Discord for this type of questions

**Comment by aesthetic0001** [comment]
^

**Comment by BlueBurgersTDD** [comment]
use this for random hexadecimal `bot.chat(require("crypto").randomBytes(100).toString("hex"))`

**Comment by u9g** [comment]
Hi,
I advise you ask such questions in https://discord.gg/GsEFRM8
