### ISSUE TITLE
Add a way to delete chat patterns

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1877]
## Is your feature request related to a problem? Please describe.
Yes, If I have a pattern for invalid input into chat and valid input into chat, once one is fulfilled, I don't care about the other anymore. I'd like to invalidate the other one before it can cause problems later in my program.

## Describe the solution you'd like
`bot.deleteChatPattern(chatPatternName)` & `bot.deleteChatPatternSet(chatPatternName)` (should be aliases of the same thing)

## Describe alternatives you've considered
none that I can think of

## Additional context
N/A

**Comment by BlueBurgersTDD** [comment]
I'll make a PR for this later today
