### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by ZVH1** [PrismarineJS/mineflayer#1886]
I have the source code of a baritone fork that has elytra support. It can also be controlled by commands. How can I integrate this with mineflayer? I have the source code of the jar.

**Comment by KaffinPX** [comment]
This called as plugins in mineflayer, you can look to Pathfinder plugin for this.

**Comment by ZVH1** [comment]
But that doesn't have elytra. I wanted to load in my mod not that one.

**Comment by extremeheat** [comment]
JavaScript is not Java. You’d need to write a clean room implementation and add support in prismarine-physics.

**Comment by ZVH1** [comment]
@extremeheat How could I do that? Can you dm me at ZVH1#8342? Discord.

**Comment by aesthetic0001** [comment]
you would probably need to rewrite it for mineflayer, not sure if you can integrate otherwise

**Comment by aesthetic0001** [comment]
nope not a java dev sry

**Comment by ZVH1** [comment]
Well can you link a tutorial or smth on how I would do that, bc I have absolutely 0 ideas on that.
