### ISSUE TITLE
Add some way to natively handle resourcepacks

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1888]
## Is your feature request related to a problem? Please describe.
End user shouldn't have to use nmp methods that are described [here](https://github.com/PrismarineJS/mineflayer/blob/master/examples/advanced/accept_texturepack.md) to handle texture packs

## Describe the solution you'd like
I'm thinking either have something in the createBot, or we can implement a mineflayer event for texturepacks and have an easy `bot.acceptTexturepack()` or `bot.rejectTexturepack()`

## Describe alternatives you've considered
using [this](https://github.com/PrismarineJS/mineflayer/blob/master/examples/advanced/accept_texturepack.md)

## Additional context
These are just rough ideas, I am open to suggestions how to implement this better

**Comment by u9g** [comment]
Here's the code which needs to be made into a plugin (up to 1.16.5 this works)

```js
bot._client.on('resource_pack_send', (data) => {
  const { url, hash } = data
  bot.emit('resourcepack', { url, hash })
})

const TEXTURE_PACK_RESULTS = {
  SUCCESSFULLY_LOADED: 0,
  DECLINED: 1,
  FAILED_DOWNLOAD: 2,
  ACCEPTED: 3
}

const acceptPack = () => {
  bot._client.write('resource_pack_receive', {
    result: TEXTURE_PACK_RESULTS.ACCEPTED
  })
  bot._client.write('resource_pack_receive', {
    result: TEXTURE_PACK_RESULTS.SUCCESSFULLY_LOADED
  })
}

const denyPack = () => {
  bot._client.write('resource_pack_receive', {
    result: TEXTURE_PACK_RESULTS.DECLINED
  })
}

/**
 * Example Code:
 * bot.on('resourcepack', () => acceptPack())
 * bot.on('resourcepack', () => denyPack())
 */
```

**Comment by U5B** [comment]
You need to send the hash field on versions below 1.10-pre1

https://wiki.vg/Protocol_History#1.10.2

**Comment by JustinBieberSierreno** [comment]
> You need to send the hash field on versions below 1.10.2
> 
> https://wiki.vg/Protocol_History#1.10.2
> 
> However the code above should work fine from 1.10.2 to 1.16.5

What is the has field and how to send it in lower versions ?

**Comment by B4RC0DE-TM** [comment]
> > You need to send the hash field on versions below 1.10.2
> > https://wiki.vg/Protocol_History#1.10.2
> > However the code above should work fine from 1.10.2 to 1.16.5
> 
> What is the hash field and how to send it in lower versions ?

`bot._client.on('resource_pack_send', (data) => {
  bot._client.write('resource_pack_receive', {
    hash: "Resourcepack", 
    result: 3
  })
  bot._client.write('resource_pack_receive', {
    hash: "Resourcepack",
    result: 0
  })
})`

that's how to do it! 💪
