### ISSUE TITLE
"point.minus is not a function" AND .look(yaw,pitch) doesn't work

### ISSUE THREAD

**Issue by leapbtw** [PrismarineJS/mineflayer#1893]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.6.0
 - server: vanilla 1.16.5
 - node: 14.16.1

## Detailed description of a problem
i'm trying to set the bot pitch and yaw of the camera to set numbers: thing is: it doesn't work with either .look(yaw,pitch) or .lookAt(blockCoords)

## What did you try yet?

i tried bot.look(yaw,pitch) but it just doesn't seem to work?
example: bot.look(100,60) sets instead the bot to yaw: -149.6 and pitch: -90
so then i tried to use bot.lookAt, calculating the block which the bot would be facing if it had the yaw and pitch i needed, but it gives me "point.minus is not a function" as an error (with code 1520)

## Your current code
```
const mineflayer = require('mineflayer')
const pvp = require('mineflayer-pvp').plugin
const { pathfinder, Movements, goals} = require('mineflayer-pathfinder')
const armorManager = require('mineflayer-armor-manager')

const bot = mineflayer.createBot({
    host: '',
    port: '',
    username: '',
    password: '',
    //logErrors: false
})

bot.loadPlugin(pvp)
bot.loadPlugin(armorManager)
bot.loadPlugin(pathfinder)

//equippa la zappa
bot.on('playerCollect', (collector, itemDrop) => {
  if (collector !== bot.entity) return
  setTimeout(() => {
    const hoe = bot.inventory.items().find(item => item.name.includes('hoe'))
    if (hoe) bot.equip(hoe, 'hand')
  }, 150)
})

let guardPos = null

function guardArea (pos) {
  guardPos = pos.clone()

  if (!bot.pvp.target) {
    moveToGuardPos()
  }
}

function stopGuarding () {
  guardPos = null
  bot.pvp.stop()
  bot.pathfinder.setGoal(null)
}

function moveToGuardPos () {
  const mcData = require('minecraft-data')(bot.version)
  bot.pathfinder.setMovements(new Movements(bot, mcData))
  bot.pathfinder.setGoal(new goals.GoalBlock(guardPos.x, guardPos.y, guardPos.z))
}

bot.on('stoppedAttacking', () => {
  if (guardPos) {
    moveToGuardPos()
  }
})

bot.on('physicTick', () => {
  if (bot.pvp.target) return
  if (bot.pathfinder.isMoving()) return

  // guarda l'entità più vicina
  //const entity = bot.nearestEntity()
  //if (entity) bot.lookAt(entity.position.offset(0, entity.height, 0))
})

bot.on('physicTick', () => {
  if (!guardPos) return

  const filter = e => e.type === 'mob' && e.position.distanceTo(bot.entity.position) < 16 &&
                      e.mobType !== 'Armor Stand' // Mojang classifies armor stands as mobs for some reason?

  const entity = bot.nearestEntity(filter)
  if (entity) {
    bot.pvp.attack(entity)
  }
})

bot.on('chat', (username, msg) => { 
  const x = bot.entity.position.x + 5;
  const z = bot.entity.position.z - 5;
  if (msg === 'yaw') bot.lookAt((x, bot.entity.height, z), true);
  if (msg === 'reset') bot.look(0, 0, true);
  if (msg === 'o_py') bot.chat("1: " + bot.entity.yaw + "   2: " + bot.entity.pitch);
  if (msg === 'w') bot.setControlState('forward', true);
  if (msg === 'ww') bot.setControlState('forward', false);
})
```

## Expected behavior

when saying "yaw" in chat, it should set yaw and pitch, it should just move the camera at the right angle but it doesn't

**Comment by U5B** [comment]
[API](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botlookyaw-pitch-force-callback)

bot.look requires that the yaw and pitch should be in radians, not degrees.

**Comment by leapbtw** [comment]
> 
> 
> [API](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botlookyaw-pitch-force-callback)
> 
> bot.look requires that the yaw and pitch should be in radians, not degrees.
> 
> bot.lookAt requires a vec3 instance for the point

i have to make it look towards yaw: -135 and pitch: 0
-135° -> -2,35619 rad according to google
so i did .look(-2,35619, 0, true) but instead the bot looks to -65.4 -90
