### ISSUE TITLE
version 15 doesnt work

### ISSUE THREAD

**Issue by devomaa** [PrismarineJS/mineflayer#1902]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: doesnt tell me
 - server: vanilla/spigot/paper unrelated
 - node: 15.6.0

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?

i ran `yarn add mineflayer`

## Your current code
```bash
error @azure/msal-node@1.0.3: The engine "node" is incompatible with this module. Expected version "10 || 12 || 14". Got "15.6.0"

```

## Expected behavior
for the package to actually install

## Additional context
i use ubuntu btw

**Comment by devomaa** [comment]
hacky solution: use `--no-node-version-check` on your yarn command

**Comment by extremeheat** [comment]
You need to make an issue in the repo for the above library, it cannot be fixed here. Looks like a yarn specific issue. 

https://github.com/AzureAD/microsoft-authentication-library-for-js

**Comment by devomaa** [comment]
oh ok

**Comment by extremeheat** [comment]
Looks like it's already been reported, https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3270

**Comment by rom1504** [comment]
I suggest using the better package management cli which is npm.

**Comment by devomaa** [comment]
yarn is superior

**Comment by flowl** [comment]
What difference does npm/yarn make, when the module's compatibility is limited by the vendor?

**Comment by BlueBurgersTDD** [comment]
> here yarn is having a bug when parsing https://github.com/PrismarineJS/mineflayer/blob/master/package.json#L19
> in general, npm is better

I actually prefer pnpm :) no issues so far
