### ISSUE TITLE
cant break blocks

### ISSUE THREAD

**Issue by pjalsGit** [PrismarineJS/mineflayer#1903]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.6.0
 - server: paper  build 629
 - node: v15.6.0

## Detailed description of a problem
It cant break blocks, the block is in [2 states of breaking](https://imgur.com/a/E1YeC6e)

## What did you try yet?

**Did you try any method from the API?** (im using mineflayer-pathfinder)
**Did you try any example? Any error from those?** I haven't tried, and it isn't a error

## Your current code
This is my follow command
```js
const { pathfinder, Movements, goals: { GoalFollow } } = require("mineflayer-pathfinder");


run = (props) => {
  const { bot, username, mcData } = props;
  const defaultMove = new Movements(bot, mcData);
  
  bot.loadPlugin(pathfinder);
  
  console.log("b")
  const target = bot.players[username] ? bot.players[username].entity : null
  console.log(target)
  if (!target) {
    bot.chat("I don't see you !")
    return
  }
  console.log("c")
  bot.pathfinder.setMovements(defaultMove)
  bot.pathfinder.setGoal(new GoalFollow(target, 0), true)
};

module.exports = { run };
//pathfinder code


```

## Expected behavior
For it to break the block correctly

## Additional context
i use ubuntu btw
(im not sure if this goes in pathfinder, or mineflayer itself)

**Comment by devomaa** [comment]
it breaks the block when i stop the breaking job for some reason

**Comment by a1cd** [comment]
https://mineflayer.prismarine.js.org/#/FAQ?id=the-bot-can39t-breakplace-blocks-or-open-chests

**Comment by devomaa** [comment]
please read my above message? also my bot is op

**Comment by a1cd** [comment]
yes, have you tried an example? also, just see if you can tp it ~100 blocks out and see if it works or tell me if you have tried it.

**Comment by a1cd** [comment]
also, your code does not ask it to break a block using `bot.digBlock(block)`
