### ISSUE TITLE
Display name must be in nbt, not in item name.

### ISSUE THREAD

**Issue by KaffinPX** [PrismarineJS/mineflayer#1904]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: vanilla/spigot/paper probably all
 - node: 14
## Detailed description of a problem
Displayname get from items name, not real display name.

## What did you try yet?
Opened a window and readed custom names

Did you try any method from the API? no
Did you try any example? Any error from those? no

## Your current code
```js

/*
      if (command === 'inventory') {
        const embed = new Discord.MessageEmbed()
        .setTitle('Inventory')
        .setColor('#eeeeee')
        for (const Item of bot.inventory.items()) {
          embed.addField(`${Item.slot}:${Item.displayName}`, `x${Item.count}`, true) //displayName isnt real displayName
        }
  
        channel.send(embed)  
      }
*/


```

## Expected behavior
Displayname must be taken in nbt..

## Additional context
nthing

**Comment by u9g** [comment]
displayName is what the item is called in vanilla minecraft, you can try https://github.com/PrismarineJS/prismarine-item
