### ISSUE TITLE
Crafting item resutling in stacking hangs on slot update.

### ISSUE THREAD

**Issue by SeanMcCord** [PrismarineJS/mineflayer#1916]
- [ x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.0.0
 - server: vanilla 1.16.4 - 1.16.5
 - node: 14.17.0

## Detailed description of a problem
Given two logs the bot hangs when crafting eight planks.
Given one birch log and one birch plank crafting four more planks results in the bot hanging.
Given two birch log crafting four planks then four more planks results in the bot hanging.

## What did you try yet?

I've looked into the mineflayer inventory and prismarine-windows implementations to find the root cause.
It appears that the bot is waiting for a slot update that is not sent from the server when it attempts to place items in a stack.

## Your current code
```js
import mineflayer from 'mineflayer';
import data from 'minecraft-data';

const bot = mineflayer.createBot({
  host: '192.168.1.163',
  username: 'Player'
});

bot.once('spawn', () => {
  const mcData = data(bot.version);
  bot.on('chat', async (username, message) => {
    if (username === bot.username) {
      return;
    }
    if (message.includes('craft 1')) {
      // This works just fine unless the bot has at least one birch plank in inventory
      console.log('start craft 1')
      const recipe = bot.recipesFor(mcData.itemsByName.birch_planks.id, null, 1, null)[0];
      await bot.craft(recipe, 1, null);
      console.log('end craft 1')
    }
    if (message.includes('craft 2')) {
      // This hangs on bot.craft
      console.log('start craft 2')
      const recipe = bot.recipesFor(mcData.itemsByName.birch_planks.id, null, 1, null)[0];
      await bot.craft(recipe, 2, null);
      console.log('end craft 2')
    }
  });
});

```

## Expected behavior
Given 1 birch log craft 4 planks.
Given 2 birch logs craft 8 planks.
Given 1 birch log and 1 birch plank craft 4 more planks.
Given 2 birch log craft 4 planks then 4 more planks.

## Additional context
I've created a demo package for the issue. https://github.com/SeanMcCord/crafting_issue_demo
The issue demo package also contains debug logging showing the set_slot is not set from the server.
My mineflayer testing fork has a test for this issue https://github.com/SeanMcCord/mineflayer/tree/crafting_test
The unresolved promise is found here https://github.com/PrismarineJS/mineflayer/blob/1f6b0aa6261b2691f594af7d66f03f0c090cae3f/lib/plugins/inventory.js#L90

**Comment by SeanMcCord** [comment]
PR https://github.com/PrismarineJS/mineflayer/pull/1666 from two months ago added the slot update waiting behavior. The old behavior was that it did not wait when inventory.putAway was called. This PR changed the default behavior to wait without updating the callers. Example caller in [craft.js](https://github.com/PrismarineJS/mineflayer/blob/1f6b0aa6261b2691f594af7d66f03f0c090cae3f/lib/plugins/craft.js#L121)

Resolution Proposal:
1) Change variable name `noWaiting` to just `waiting` to remove double negative.
2) Invert putAway noWaiting argument from true to false to align with previous interface.
3) Search for other callers to ensure consistency.
4) Swap branches of [this if statement](https://github.com/PrismarineJS/mineflayer/blob/1f6b0aa6261b2691f594af7d66f03f0c090cae3f/lib/plugins/inventory.js#L102-L106) as they are backwards. When noWaiting is true it waits on the slot update.

**Comment by SeanMcCord** [comment]
@DecentralisedTech Does the proposal implementation solve your issue?

**Comment by extremeheat** [comment]
Can you make the PR to fix it? I think it would be a good idea to use timeouts wherever we wait for promises to avoid promise leaks like this.

**Comment by SeanMcCord** [comment]
That might be a better place to have this discussion. I'll turn my proposal into a PR.

**Comment by BonyChops** [comment]
> Rough stab at proposal implementation. [SeanMcCord@d548f7c](https://github.com/SeanMcCord/mineflayer/commit/d548f7c00512f2e2363f518407ff2560c3967fae)

I had the same problem and this commit worked for me! Thanks.
- server: vanilla 1.16.4, 1.15
- node: v14.17.2

**Comment by SeanMcCord** [comment]
This issue was addressed in https://github.com/PrismarineJS/mineflayer/pull/2143
