### ISSUE TITLE
Chat event emitted on any chat event (contrary to API documentation)

### ISSUE THREAD

**Issue by squareblob** [PrismarineJS/mineflayer#1934]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.7.0
 - server: paper 1.16.4
 - node: 16.1.0

## Detailed description of a problem

The API documentation [states](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#chat-username-message-translate-jsonmsg-matches):
> "chat" (username, message, translate, jsonMsg, matches)
> Only emitted when a player chats publicly.

However, the chat event emits on messages such as `From {username}: {message}` and other variations of whispers. I do not recall (though cannot say so with certainty) that the chat event was previously emitted on whispers.

## What did you try yet?

I tried whispering to a bot that logged "chat" events.

## Your current code
```js
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
    host: "[redacted]",
    port: "[redacted]",
    version : "1.16.4",
    username: process.argv[2],
    password: process.argv[3],
})

bot.on("chat", (username, message, translate, jsonMsg, matches) => {
    console.log(username + " : " + message)
    // This event fires when the bot recieves a private message in the form "From {username}: {message}"
    // Per the docs "chat" should only fire "when a player chats publicly"
})
```

## Expected behavior
I expected the chat event to not be emitted. However, contrary to the API documentation, the chat event was emitted.

**Comment by Febzey** [comment]
I was having the same issue, right after I updated to the latest version of mineflayer, although I cannot confirm that is the problem, so do not take my word on that.

**Comment by snowcatman** [comment]
I had an issue like this, this last year. Having trouble locating it.... to share. The issue I was having was differentiating privet chat from public. to issue commands privetly. As I remember right there was no differentiation at all to begin with. Ugh. Now I need to look in my archives. If this gets fixed then maybe I should continue with learning and coding here.  ty.

**Comment by Eagle-Anne** [comment]
Would it be better to update the docs to keep chat as the current implementation of "any message the mineflayer bot receives" and add/document a new event like publicChat or similar to add not-a-whisper filtering? You could do a filter on the received messages in the handler to determine if they're a whisper or a chat, but being able to once() the event and know you have a public message may be valuable to someone.
