### ISSUE TITLE
I can no longer sign in to my Mojang account.

### ISSUE THREAD

**Issue by AcaiBerii** [PrismarineJS/mineflayer#1944]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.7.0
 - server: vanilla/spigot/paper 1.16.5
 - node: 14.17.0

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
I'm debugging a bot that allows me to test anticheats, but now that I've run it on my main account I can no longer log in to the Minecraft launcher.

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?
Tried to look at other answers on the github, such as waiting a minute.

## Your current code
```js

const mineflayer = require('mineflayer')
const { mineflayer: mineflayerViewer } = require('prismarine-viewer')
const prompt = require('prompt-sync')();

const bot = mineflayer.createBot({
  host: '!!!',             // minecraft server ip
  username: '!!!', // minecraft username
  password: '!!!',          // minecraft password, comment out if you want to log into online-mode=false servers
  auth: 'mojang'              // only set if you need microsoft auth, then set this to 'microsoft'
})

console.log("Init Spawn/Viewer")

bot.once('spawn', () => {
    bot.chat(">> Joined. Running JIG v1.0 authored by AcaiBerii. Use >help for commands.")
})

console.log("Init CMD/Log")

bot.on('chat', (username, message) => {
  console.log(username + ": " + message)
  if (username === bot.username) return
  if (message.startsWith(">")) {
    var par = message.substring(1)
    var arg = par.split(' ')
    if (arg[0] == "help") {
        bot.chat(">> Hey! I'm JIG made by AcaiBerii. Here are some Anticheat debug commands:")
        bot.chat(">hit")
        bot.chat(">requi")
    }
    else if (arg[0] == "hit") {
        if (arg.length < 2) {
            bot.chat(">> You need to specify a hand.")
        }
        else {
            bot.swingArm(arg[1]);
        }
    }
    else if (arg[0] == "requi") {
        console.log(">> Requesting an operator's input...")
        let msg = prompt('Please send a message...');
        bot.chat(msg);
    }
  }
})

console.log("Init err handler")

bot.on('kicked', console.log)
bot.on('error', console.log)


```

## Expected behavior
I expected to be able to log into the minecraft launcher after using my bot.

## Additional context
pain

**Comment by mat-1** [comment]
Use your email instead of your username.

**Comment by mat-1** [comment]
Also your account might've been temporarily blacklisted, wait like a day and check your email

**Comment by AcaiBerii** [comment]
> Use your email instead of your username.

Did that



> Also your account or ip might've been temporarily blacklisted, wait like a day and check your email

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by AcaiBerii** [comment]
It seems as I can access my account now as I changed my password. I hope PrismarineJS can fix this in the future.
