### ISSUE TITLE
raycast not working

### ISSUE THREAD

**Issue by a1cd** [PrismarineJS/mineflayer#1951]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.7.0
 - server: paper 1.16.4
 - node: v14.15.5

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?
I am making a bot that can mine a tree using only what it can see. When i use `bot.world.raycast` it sometimes returns a block and usually loops through all of the directions returning null.

## What did you try yet?

Did you try any method from the API?
Yes. `bot.world.raycast`
Did you try any example? Any error from those?
there are no examples for what the API that I'm using. 

## Your current code
```js

getViewedBlocks(density, maxDistance, fov = 170) {
    // this.cacheBlocks(2)
    let fovR = ((Math.PI / 180) * fov)/2
    let vdist = Math.round(Math.tan(fovR)*100)/200
    let realDensity = density * vdist
    var mon = 0
    let entity = this.bot.entity
    for (let x = -realDensity; x < realDensity; x++) {
      for (let y = -realDensity; y < realDensity; y++) {
        var ry = 0
        var rx = 0
        if (x>y) {
          ry=y/x
          rx=1
        } else {
          rx=x/y
          ry=1
        }
        let block = this.bot.world.raycast(entity.position.add(new Vec3(0,0,entity.height)), new Vec3(entity.yaw, ry, rx), 100)
        console.log(block)
      }
    }
    console.log("done", mon)
  }


```

## Expected behavior
print null a lot but also print blocks. this doesn't happen.

## Additional context
there have also been times when I do `bot.blockAt(coord)` and it just returns null even though it's fairly close to the bot and is not air or above or below the world.

**Comment by Karang** [comment]
The height should be added to the y component.
You can use position.offset(0, height, 0) to avoid creating temporary objects.
The direction vector should be normalized.
It doesn't make sense to use the yaw (an angle) directly as the x component of the direction.

**Comment by a1cd** [comment]
Ok thank you. I added the yaw as a last attempt and just forgot to remove it.

**Comment by a1cd** [comment]
```
start mine
19044x null
start mine
19044x null
start mine
19044x null
``` ok so no it did not work

**Comment by a1cd** [comment]
i have figured it out.
I had to make my setup function async and add:
``` js
await this.bot.waitForChunksToLoad()
console.log("chunks loaded");
```
this fixed it
