### ISSUE TITLE
Bot cannot see farther than ~5 blocks

### ISSUE THREAD

**Issue by a1cd** [PrismarineJS/mineflayer#1952]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: paper 1.16.4
 - node: #.#.#

## Detailed description of a problem
I'm using the find block example and the bot will not find blocks that are further than around 10 blocks radius

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?
Yes, the find block. No error but still doesn't do what I want

## Your current code
The example code

## Expected behavior
The bot to see further than 10 blocks radius

## Additional context
When I use `prismarine-viewer` it can see super far

**Comment by aesthetic0001** [comment]
can u please link the example

**Comment by a1cd** [comment]
[Blockfinder.js](https://github.com/PrismarineJS/mineflayer/blob/master/examples/blockfinder.js)

**Comment by a1cd** [comment]
![an image of the bot's range](https://user-images.githubusercontent.com/71281043/120254116-15494a00-c257-11eb-8586-dcaa5bc9e901.png)
this is an image showing how far the bot can see. the diamond blocks are just in view of the bot.

**Comment by aesthetic0001** [comment]
Perhaps increase the count so that it can match more?

**Comment by a1cd** [comment]
i set count to 50 and it did not work.
```js
const blocks = bot.findBlocks({ matching: ids, maxDistance: 128, count: 50 })
```

**Comment by a1cd** [comment]
![2021-06-01_08 16 40](https://user-images.githubusercontent.com/71281043/120321810-bc5acf80-c2b1-11eb-871d-dfdd10a84f93.png)

**Comment by DrMoraschi** [comment]
It's not count, it's maxDistance

**Comment by aesthetic0001** [comment]
ah i thought perhaps the fact that there were so many blocks could cause it to not find all. maxDistance param is 128 so should be fine, maybe something wrong with matching param?

**Comment by Karang** [comment]
If you are using the example block unmodified, make sure the world is loaded by typing the loaded command first, then make sure you typed the name of the block correctly, in this case `diamond_block`. Also if you want some help, you need to provide more details, since you are using the example, screenshots of the chat would be nice.

**Comment by a1cd** [comment]
it's finding the right blocks so I am pretty sure that matching is fine. 

I found a couple more details while messing around. 

- the radius is based around the head
- it is 10-11 blocks in radius

If it helps, I am running macOS Catalina but that should not be a problem.

![2021-06-01_08 58 16](https://user-images.githubusercontent.com/71281043/120327230-87517b80-c2b7-11eb-95e6-de164ea9d105.png)

![2021-06-01_08 56 59](https://user-images.githubusercontent.com/71281043/120327090-62f59f00-c2b7-11eb-8e71-52a6cf36df8a.png)

**Comment by a1cd** [comment]
if it helps, here is the code
```js
/*
 * This simple bot will help you find any block
 */
const mineflayer = require('mineflayer')

const { performance } = require('perf_hooks')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node blockfinder.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'finder',
  password: process.argv[5]
})

bot.on('chat', async (username, message) => {
  if (username === bot.username) return

  const mcData = require('minecraft-data')(bot.version)

  if (message === 'loaded') {
    console.log(bot.entity.position)
    await bot.waitForChunksToLoad()
    bot.chat('Ready!')
  }

  if (message.startsWith('find')) {
    const name = message.split(' ')[1]
    if (mcData.blocksByName[name] === undefined) {
      bot.chat(`${name} is not a block name`)
      return
    }
    const ids = [mcData.blocksByName[name].id]

    const startTime = performance.now()
    const blocks = bot.findBlocks({ matching: ids, maxDistance: 128, count: 50 })
    const time = (performance.now() - startTime).toFixed(2)

    bot.chat(`I found ${blocks.length} ${name} blocks in ${time} ms`)
  }
})
```
i run the code using this command
`/usr/local/bin/node ./example.js localhost 25565 Test`

**Comment by Karang** [comment]
Just tested with a clean mineflayer install and its working as intended. Please make sure you didn't modify the findBlocks function (especially since you opened a PR in this area yesterday).

**Comment by a1cd** [comment]
`npm ci` fixed it. thank you.
