### ISSUE TITLE
`bot.craft([id for planks and such])` never calls back

### ISSUE THREAD

**Issue by a1cd** [PrismarineJS/mineflayer#1963]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.7.0
 - server: paper 1.16.4
 - node: v14.15.5

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?
I am trying to craft a crafting table.

## What did you try yet?

Did you try any method from the API?
yes, `bot.craft()`
Did you try any example? Any error from those?
yes, [inventory.js](https://github.com/PrismarineJS/mineflayer/blob/master/examples/inventory.js) did not work.

## Your current code
how i call my craft function:
```js
await this.craft("oak_planks", 5)
await this.craft("crafting_table", 1)
```
my craft function:
```js
async craft(item, count) {
  console.groupCollapsed("-craft")
  item = mcData.itemsByName[item]
  if (!item) {
    console.groupEnd()
    return false
  }
  let recipes = this.bot.recipesFor(item.id, null, count, null)
  console.log("recipies:",recipes);
  console.trace("start Craft");
  if (recipes[0].requiresTable) {
    console.trace("requires Table");
    let table = this.findBlock("crafting_table")
    await this.bot.craft(recipes[0], Math.ceil(count/recipes[0].result.count), table)
    console.groupEnd()
    return true
  } else {
    console.trace("doesnt require table");

    await new Promise(resolve => {
      this.bot.craft(recipes[0], count, null, () => {
        resolve()// <---------------------------------- is never called
      })
    })
    console.trace("craft done");
    console.groupEnd()
    return true
  }
}
```

## Expected behavior
to have a crafting table in its inventory

## Additional context
i have tried to trace it down to a single line of code. i found it to be this line of code
[line 94 of `./lib/plugins/inventory.js`](https://github.com/PrismarineJS/mineflayer/blob/82910c14f6811e6ad38dc4bb15e89c979871fc44/lib/plugins/inventory.js#L94)
that is where it does not return.
it is specifically 
```js
once(window, `updateSlot:${item.slot}`)
```
i have run `npm ci` to make sure it wasn't me.

**Comment by BonyChops** [comment]
I have mostly the same proplem.
I've tried to craft `hay_block` from `wheat` using [inventory.js](https://github.com/PrismarineJS/mineflayer/blob/master/examples/inventory.js)

- mineflayer: 3.9.0
- server: paper 1.16.4(same), 1.15
- node: v14.17.2

**Comment by psu-de** [comment]
Hello,
i faced this issue as well and I think i figured it out: 

First: If in the spawn area, this will happen,
second: there is a server side check: `this.awaitingPositionFromClient == null` which will not be fullfilled if the bot just joins on the server. When including the pathfinder plugin and walking just one block it worked for me

**Comment by rom1504** [comment]
not enough info to reproduce, the example in the examples folder works
re-open if you have more info
