### ISSUE TITLE
Add Beddrock Edition Support

### ISSUE THREAD

**Issue by LeontKing2** [PrismarineJS/mineflayer#1967]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Add Bedrock Edition Support

## Describe alternatives you've considered
Or add Geyser Mc from bedrock support

**Comment by Hazuki-san** [comment]
duplicate of #842

**Comment by TheBlueBurger** [comment]
Just use https://github.com/PrismarineJS/bedrock-protocol

**Comment by LeontKing2** [comment]
> Just use https://github.com/PrismarineJS/bedrock-protocol

how do i use it @TheBlueBurger  idk how to use it but all i need is to make a bot join the server and rotate random directions
and talk i chat manually

**Comment by TheBlueBurger** [comment]
Read the docs

**Comment by LeontKing2** [comment]
i read the docs but i still dont understand js lol

**Comment by TheBlueBurger** [comment]
1. Learn JS
2. Join the discord

**Comment by LeontKing2** [comment]
oof

**Comment by XfedeX** [comment]
> 
> 
>     1. Learn JS
> 
>     2. Join the discord

3. Play Minecraft Java Edition and not Bedrock Edition.

**Comment by rom1504** [comment]
duplicate
