### ISSUE TITLE
FR: Separate creating bot from logging into bot

### ISSUE THREAD

**Issue by williamd5** [PrismarineJS/mineflayer#1974]
At this time the `mineflayer.createBot` method is utilised to create, authenticate, and connect a bot to a server all at once, which may appear like something pleasant to have as it seemingly simplifies the development experience, however, it makes it impossible to for instance:
* re-use a session (instead of validating username & password and generating a new one)
* re-connect to a server
* connect to a different server
For instance, the standard workflow to connect a bot to a server could be
```js
const bot = mineflayer.createBot({version:"1.16.5"});
bot.authenticate({
    username: "john@doe.com",
    password: ""
});
// creates e.g. bot.session containing an access token

bot.connect({
    host: "localhost",
    port: "25565"
});
```

**Comment by rom1504** [comment]
You can use Yggdrasil directly to create an access token

**Comment by williamd5** [comment]
> You can use Yggdrasil directly to create an access token

link to repo?
