### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#1979]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2455%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/PrismarineJS/mineflayer/issues/1979)

- [x] make protocol.json for node-minecraft-protocol for 1.17
- [x] run protocol.json against node-minecraft-protocol packet cycle tests
- [x] update prismarine-chunk to support the new chunk format for 1.17 https://github.com/PrismarineJS/prismarine-chunk/pull/125 https://github.com/PrismarineJS/minecraft-chunk-dumper/pull/22
- [x] prismarine-block, prismarine-item, prismarine-recipe
- [ ] mineflayer https://github.com/PrismarineJS/mineflayer/pull/1993

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $55.00)

- [<img src='https://avatars.githubusercontent.com/u/26673889?v=4' alt='xlnd47' width=24 height=24> xlnd47](https://issuehunt.io/u/xlnd47) ($5.00)
- [<img src='https://avatars.githubusercontent.com/u/286029?v=4' alt='appenz' width=24 height=24> appenz](https://issuehunt.io/u/appenz) ($50.00)

### Submitted pull Requests
- [#2110 1.17 support](https://issuehunt.io/r/PrismarineJS/mineflayer/pull/2110)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PrismarineJS/mineflayer/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by rom1504** [comment]
first task is done
pr for second task is there https://github.com/PrismarineJS/node-minecraft-protocol/pull/866

**Comment by rom1504** [comment]
@Archengius fyi

**Comment by rom1504** [comment]
please post any relevant PR here

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-physics/pull/45
https://github.com/PrismarineJS/prismarine-block/pull/36

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-chunk/pull/125

**Comment by rom1504** [comment]
nmp support is done

**Comment by Archengius** [comment]
https://github.com/PrismarineJS/minecraft-chunk-dumper/pull/22

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/pull/1993

**Comment by frmdeveloper** [comment]
Please

**Comment by DrMoraschi** [comment]
> Please

Someone open a PR to add patience to users

**Comment by IKnowNoHowPotato** [comment]
hello I am new to this kind of work and I want to help and learn but I don't know what to do. I really love this project tho

**Comment by rom1504** [comment]
you can check the open PRs listed above and see if you can help to finish them

**Comment by CreeperBois** [comment]
hey when will 1.17 mineflayer will come

**Comment by rom1504** [comment]
This is currently blocked by https://github.com/PrismarineJS/prismarine-chunk/pull/125

**Comment by AiryPP** [comment]
WHERE 1.17 !?

**Comment by u9g** [comment]
> WHERE 1.17 !?

Prismarine-chunk support still needs to be done. If you can do it, I encourage you to contribute.

**Comment by mohammad-sayed-ahmad** [comment]
When will 1.17 prismarine_chunck be updated?

**Comment by nickelpro** [comment]
1.17 chunk support is at review
https://github.com/PrismarineJS/prismarine-chunk/pull/133

**Comment by jkcoxson** [comment]
https://github.com/PrismarineJS/mineflayer/pull/2086 gets the world height from the login packet so it can be used as a constructor for the world

**Comment by nickelpro** [comment]
This is blocked on 1.17 Window Click support

**Comment by frmdeveloper** [comment]
Yeey

**Comment by LPDMinecraft** [comment]
When its the problem solved?

**Comment by rom1504** [comment]
Mineflayer now supports minecraft 1.17.1.
For this PR, work has been mostly done by @nickelpro and @U9G , thank you to them :slight_smile: ! I have awarded them some donations we received via issuehunt.
I also want to thanks @Archengius @extremeheat  @imharvol and @willocn that participated to the work needed for the PR.
