### ISSUE TITLE
Unclear proxy documentation in FAQ. EDIT: PROXY IS ALSO NOT WORKING WITH EXTERNAL IPs!

### ISSUE THREAD

**Issue by XfedeX** [PrismarineJS/mineflayer#1992]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

The proxy FAQ doesn't specify a proxy module. When trying to use it as explained [here](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md#how-can-i-use-a-socks5-proxy) , 
ReferenceError: socks is not defined is popping out.
What Socks module should I use? You should add that to the documentation too.
Thank you.

**Comment by u9g** [comment]
this one? https://www.npmjs.com/package/socks just a guess

**Comment by XfedeX** [comment]
> 
> 
> this one? https://www.npmjs.com/package/socks just a guess
Thank you! <3 But i keep the issue open because this needs to be added in the documentation.

**Comment by u9g** [comment]
> 
> 
> > this one? https://www.npmjs.com/package/socks just a guess
> 
> 
> 
> Thank you! <3 But i keep the issue open because this needs to be added in the documentation.

You can contribute it :)

**Comment by XfedeX** [comment]
So, when using my locally hosted proxy everything worked fine.
But when trying to use external proxies nothing works: after 30 seconds I get timed out error,  but in both Firefox FoxyProxy and proxy-server mod they work perfectly, with low ping (< 500).

**Comment by XfedeX** [comment]
EDIT2: Now i somewhat get error: Socket closed

**Comment by u9g** [comment]
This isn't a mineflayer problem, this is a problem with your setup.

**Comment by rom1504** [comment]
check the examples
