### ISSUE TITLE
bot.findInventoryItem id falsely typed

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer#2009]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest

## Detailed description of a problem
Providing a string to
bot.inventory.findInventoryItem(name, null, false)
in typescript results in a type error

## Your current code
```ts

async equipItem(name: string, destination: mineflayer.EquipmentDestination): Promise<void> {
        const item = this.bot.inventory.findInventoryItem(name, null, false)
        return this.bot.equip(item, 'hand', function() {})
    }
```

source of index.d.ts:
```ts
findInventoryItem(itemType: number, metadata: number | null, notFull: boolean): Item | null;
```
itemType is sadly only number

## Expected behavior
item should per code be number and or string:
Window.js (src of mineflayer)
```js
findInventoryItem (item, metadata, notFull) {
      assert(typeof item === 'number' || typeof item === 'string' || typeof item === 'undefined', 'No valid type given')
      return typeof item === 'number'
        ? this.findItemRange(this.inventoryStart, this.inventoryEnd, item, metadata, notFull)
        : this.findItemRangeName(this.inventoryStart, this.inventoryEnd, item, metadata, notFull)
    }
    ```

**Comment by u9g** [comment]
that isn't a mineflayer function, that's pwindow, it should be fixed in this pr: https://github.com/PrismarineJS/prismarine-windows/pull/39

**Comment by SinanAkkoyun** [comment]
Ok thx
