### ISSUE TITLE
Create an example for moving randomly

### ISSUE THREAD

**Issue by JIBSIL** [PrismarineJS/mineflayer#2017]
## Is your feature request related to a problem? Please describe.
I see that there are a lot of examples and plugins for pathfinding, etc., but it would be useful for some users if the devs of this project (or anyone else) provided an example where the bot moves randomly.

## Describe the solution you'd like
An example in the `examples` folder where a bot that moves randomly is made.

## Describe alternatives you've considered
n/a

## Additional context
n/a

Thanks,
-JIBSIL

**Comment by u9g** [comment]
how do you describe moving randomly? towards a random goal? pick a different move choice each ie, forward 1 block, left 1 block etc?

**Comment by JIBSIL** [comment]
Towards a random goal.

**Comment by DrMoraschi** [comment]
What you can do is create a function that returns a random value for each value in a Vec3, given a Minimum Vec3 and a Maximum Vec3, and just set the goal to the returned value

**Comment by JIBSIL** [comment]
DrMoraschi I'm not familiar with Vec3 logic, would I use a package similar to this? https://www.npmjs.com/package/vec3

**Comment by JIBSIL** [comment]
@DrMoraschi  sorry didn't know how Github mentions work, ^^

**Comment by DrMoraschi** [comment]
Yeah that's the package

**Comment by JIBSIL** [comment]
@DrMoraschi How would I use this package? How would I connect it to Mineflayer? Would you recommend using a pathfinding library and using a randomizer between 1 and 65535, and repeating forever?

**Comment by DrMoraschi** [comment]
Use mineflayer-pathfinder to move around, with Math.random()

**Comment by u9g** [comment]
I’m going to consider this solved

**Comment by JIBSIL** [comment]
Working, thank you!
