### ISSUE TITLE
mineflayer locking my accounts after turning on and off the vps 

### ISSUE THREAD

**Issue by Lucklessseal375** [PrismarineJS/mineflayer#2028]
client.login("")

// Mineflayer shit
const bot = mineflayer.createBot({
  version:'1.8',
  auth: 'mojang',
  username:"",
  password:"",
    host: '',
  viewDistance: 'far'
    })
  

bot.on("login", async => {
    console.log("bot on")
    bot.chat("/server factions")
  })

bot.on('kicked', console.log)
bot.on('error', console.log)
  

// Mineflayer message logging - coded by void & seal
bot.on('message', message => {
  const channel = client.channels.cache.get('841874385793974302');

  if (message == '' || message == undefined || message == null || message == " " || message == "") {
  } else {
    channel.send("```"+"Server Message - "+ message + "```")
  }
})
 
  bot.on('chat',(username,message) => {
  console.log((`${username}, said ,"${message}"`))   
})    

// auto commands for mineflayer
client.on('message', message => {
  if (message.author.bot) return
  if (message.channel == "841874385793974302")
  {
    bot.chat(`${message.content}`)
  }

})

//web inv seal 
  const inventoryViewer = require('mineflayer-web-inventory')
  let options = {
    port: "8078",
  }

  inventoryViewer(bot, options)

//web vewier github
const { mineflayer: mineflayerViewer } = require('prismarine-viewer')
const { GoalBlock } = require('mineflayer-pathfinder').goals
bot.loadPlugin(pathfinder)

bot.once('spawn', () => {
  mineflayerViewer(bot, { port: 8069 }) 

  bot.on('path_update', (r) => {
    const nodesPerTick = (r.visitedNodes * 50 / r.time).toFixed(2)
    console.log(`I can get there in ${r.path.length} moves. Computation took ${r.time.toFixed(2)} ms (${nodesPerTick} nodes/tick). ${r.status}`)
    const path = [bot.entity.position.offset(0, 0.5, 0)]
    for (const node of r.path) {
      path.push({ x: node.x, y: node.y + 0.5, z: node.z })
    }
    bot.viewer.drawLine('path', path, 0xff00ff)
  })

  const mcData = require('minecraft-data')(bot.version)
  const defaultMove = new Movements(bot, mcData)

  bot.viewer.on('blockClicked', (block, face, button) => {
    if (button !== 2) return 

    const p = block.position.offset(0, 1, 0)

    bot.pathfinder.setMovements(defaultMove)
    bot.pathfinder.setGoal(new GoalBlock(p.x, p.y, p.z))
  })
})

//mineflayer armor thing thing
const armorManager = require('mineflayer-armor-manager')
bot.loadPlugin(armorManager)
bot.armorManager.equipAll()

//web radar git

const radarPlugin = require('mineflayer-radar')(mineflayer);
var radar = {
  host: '', 
  port: '',
}
radarPlugin(bot, radar);

//wall checked by Seal
  let channel = client.channels.cache.get('841894398106009620');
 bot.on('chat', (username, message) => {
  if (message === "walls checked") {
 client.channels.cache.get('841894398106009620').send("wall checked by " +username);    
  }})

  //raid 
client.on('message', message => {

if(message.content.includes("Obraxis"))
{
 client.channels.cache.get('841873802165878785').send("possible raid detected @everyone");
}
})

**Comment by Lucklessseal375** [comment]
i turn on the vps wait like 10 min no matter how long i wait it just gets locked

**Comment by Lucklessseal375** [comment]
i tried it with accounts that i bought from mojang it locked them nfas too im lost

**Comment by rom1504** [comment]
how many times did you start the bot?

**Comment by Lucklessseal375** [comment]
i started and waited and turned it off
once i turned it back on it locked the account

**Comment by Zn10plays** [comment]
Accounts can be locked for many reasons, are you sure this is Mineflayer's fault and has nothing to do with anythings that violates Mojang's TOS.
