### ISSUE TITLE
Add an alternate authentication server / medium ...

### ISSUE THREAD

**Issue by crazyaccess** [PrismarineJS/mineflayer#2031]
## Is your feature request related to a problem? Please describe.
Yes but no, i am trying to make a bot that will run on a diffrent authentication server rather than minecraft's like https://ely.by

## Describe the solution you'd like
like rather than using the minecraft authentication system by default or offline mode, we can have an optional flag while creating the bot of which authentication server to use

## Describe alternatives you've considered
Adding it directly to the class if i have the time to pr

## Additional context
https://ely.by is an authentication server thats an alt to minecraft authentication server, this will help in testing multiple verified mc bot users without having to purchase accounts on the mainstream account facilities and stuff...

**Comment by u9g** [comment]
as described here: https://github.com/PrismarineJS/node-minecraft-protocol/pull/802#issuecomment-755643338 you can set authServer and sessionServer in the options for createbot which are passed to createClient

**Comment by crazyaccess** [comment]
Uhh lemme check

**Comment by u9g** [comment]
Is that good?
