### ISSUE TITLE
Warning: Accessing non-existent property 'toJSON' of module exports inside circular dependency

### ISSUE THREAD

**Issue by ProfessorQu** [PrismarineJS/mineflayer#2037]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.7.0
 - server: vanilla 1.16.5
 - node: 14.17.3

## Detailed description of a problem
Everytime I try and start my bot it gives this error:
```
(node:14536) Warning: Accessing non-existent property 'toJSON' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

## What did you try yet?
I tried removing/commenting out code that I added.
I tried removing package.json and package-lock.json and reinstalling mineflayer and the plugins,

## Your current code
```js
const mineflayer = require("mineflayer");
const pvp = require("mineflayer-pvp").plugin;
const minecraftHawkEye = require("minecrafthawkeye");
const { pathfinder, Movements, goals } = require("mineflayer-pathfinder");
const armorManager = require("mineflayer-armor-manager");
const collectBlock = require("mineflayer-collectblock").plugin;

// Create the bot
const bot = mineflayer.createBot({
  host: "localhost",
  port: process.argv[2],
  version: "1.16.5",
  username: "TotallyNotABot",
});

// Load plugins
bot.loadPlugin(pvp);
bot.loadPlugin(minecraftHawkEye);
bot.loadPlugin(pathfinder);
bot.loadPlugin(armorManager);
bot.loadPlugin(collectBlock);

// Set mcData and movements
let mcData;
let movements;

bot.once("spawn", () => {
  mcData = require("minecraft-data")(bot.version);
  movements = new Movements(bot, mcData);
  bot.pathfinder.setMovements(movements);
});
```

## Expected behavior
The bot joins the server and nothing else happens

**Comment by u9g** [comment]
1. not an error, its a warning
2. this is fue to one of the plugins you installed, not mineflayer itself

**Comment by ProfessorQu** [comment]
I fixed it by deleting the entire node_modules file and reinstalling every package
