### ISSUE TITLE
Make tests non flaky

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#2047]
https://github.com/PrismarineJS/mineflayer/commits/master

random failures are annoying

**Comment by TheBlueBurger** [comment]
I found these tests to commonly break: ```
- placeEntity place armor stand (Error: Failed to place entity)
- useChests (AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value)
- placeEntity place summon egg (Error: Failed to place entity)
```

**Comment by rom1504** [comment]
now mostly fixed by disabling flaky place entity test (cc @u9g ) https://github.com/PrismarineJS/mineflayer/commit/9fdce7660ff99d2f4a0b67a3f4a544e27c73e117

**Comment by u9g** [comment]
https://github.com/PrismarineJS/mineflayer/pull/2314 has a fail that shouldn't be
