### ISSUE TITLE
Why can't I use water to move my bot?

### ISSUE THREAD

**Issue by EnderBender08** [PrismarineJS/mineflayer#2057]
The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest release
 - server: paper 1.17
 - node: 16.5.0

## Detailed description of a problem
I am using mineflayer bot to make my aternos MC server 24/7 but after 20 minutes it gets kicked for being idle too long. mineflayer-move isn't working with infinite loops (something required to forever jump up and down to not be idle) and I tried using an AFK pool but it didn't budge.

## Current code
```js
const mineflayer = require('mineflayer')
const cmd = require('mineflayer-cmd').plugin
const fs = require('fs');
const move = require('mineflayer-move').plugin
let rawdata = fs.readFileSync('config.json');
let data = JSON.parse(rawdata);
var host = data["ip"];
var username = data["name"];
var autoafk = data["autoafk"];
var bot = mineflayer.createBot({
  host: host,
  username: username
});
bot.loadPlugin(cmd)
bot.loadPlugin(move)


bot.on('login',function(){
	console.log(username," logged In")
	bot.chat("hello");
});


bot.on('spawn',function() {
    connected=1;
});

bot.on('death',function() {
    bot.emit("respawn")
});
```

I thought the water would move the bot but it just stood there.

**Comment by u9g** [comment]
what version of mineflayer do you have?

**Comment by u9g** [comment]
Please reopen when you give more info
