### ISSUE TITLE
 Cannot find module

### ISSUE THREAD

**Issue by norrmi** [PrismarineJS/mineflayer#2066]
Error: Cannot find module 'mineflayer'
Require stack:
- C:\Users\mineflayer-master\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\Users\mineflayer-master\index.js:1:20)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\mineflayer-master\\index.js'←[39m ]

**Comment by aesthetic0001** [comment]
`npm i mineflayer` ?

**Comment by u9g** [comment]
aesthetic is righ

**Comment by XingYuan55** [comment]
I have a similar situation #2920
