### ISSUE TITLE
This probably already exists but how do i make the bot crouch?

### ISSUE THREAD

**Issue by StackoverflowEnjoyer** [PrismarineJS/mineflayer#2067]
How do I make the bot crouch

**Comment by imharvol** [comment]
Check https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botsetcontrolstatecontrol-state 'sneak' option

**Comment by StackoverflowEnjoyer** [comment]
> 
> 
> Check https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botsetcontrolstatecontrol-state 'sneak' option

Another quick question is there an event for a player jumping?

**Comment by imharvol** [comment]
There's no such event. You would have to check if the player's y coordinate changes over time

**Comment by StackoverflowEnjoyer** [comment]
****

> 
> 
> > > Check https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botsetcontrolstatecontrol-state 'sneak' option
> > 
> > 
> > Another quick question is there an event for a player jumping?
> 
> There's no such event. You would have to check if the player's y coordinate changes over time

Do you know how to get y position?
 because bot.position.y doesnt work

**Comment by imharvol** [comment]
If you want your bot's y position: `bot.entity.position.y`

If you want someones y position: `bot.players['username'].position.y`

You probably want to refer to the Discord for these questions: https://discord.gg/HAg7y3wt

**Comment by StackoverflowEnjoyer** [comment]
> 
> 
> If you want your bot's y position: `bot.entity.position.y`
> 
> If you want someones y position: `bot.players['username'].position.y`
> 
> You probably want to refer to the Discord for these questions: https://discord.gg/HAg7y3wt

Ok sorry for asking so many questions im new.
