### ISSUE TITLE
"playerCollect" not beign called when collecting shuker boxes

### ISSUE THREAD

**Issue by bentoemanuel** [PrismarineJS/mineflayer#2075]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.9.0
 - server: spigot 1.17.1
 - node: #.#.#

## Your current code
```js

bot.on("playerCollected", (collector, collected) => {
console.log("collected");
}

```

## Expected behavior
Player collects an item, prints collected, but doesnt wonrk when the item is a shulker box

**Comment by Zn10plays** [comment]
Is this bug happening in any other version?

**Comment by rom1504** [comment]
>  1.17.1

this version is not supported yet
