### ISSUE TITLE
bot loads with no errors but fails to join

### ISSUE THREAD

**Issue by dolphin-cat** [PrismarineJS/mineflayer#2089]
i tried it with your 2 examples gps.js and bot.js
the program opens, no errors in the console but the bot never joins my server

**Comment by u9g** [comment]
on the first line of the file can you add `process.env.DEBUG = 'minecraft-protocol'`

**Comment by dolphin-cat** [comment]
fixed it but... all i want is to break a block(using python version fixed the issue) where do i put the coordinates???

**Comment by dolphin-cat** [comment]
the bot will be near the block, no need for pathfinding

**Comment by dolphin-cat** [comment]
@u9g

**Comment by dolphin-cat** [comment]
from javascript import require, On
mineflayer = require('mineflayer')
pathfinder = require('mineflayer-pathfinder')

RANGE_GOAL = 1
BOT_USERNAME = '*******'

bot = mineflayer.createBot({
  'host': '*****************',
  'port': 25565,
  'username': BOT_USERNAME
})

bot.loadPlugin(pathfinder.pathfinder)
print("Started mineflayer")

@On(bot, 'spawn')
def handle(*args):
	bot.dig(block)

@On(bot, "end")
def handle(*args):
  print("Bot ended!", args)

**Comment by extremeheat** [comment]
You can use `bot.blockAt` to get the position of a block then pass it into `bot.dig`

https://colab.research.google.com/github/PrismarineJS/mineflayer/blob/master/docs/mineflayer.ipynb#scrollTo=xJUk8b21pOzg

**Comment by u9g** [comment]
I'm going to consider this closed
