### ISSUE TITLE
can you add sender_name/sender_username

### ISSUE THREAD

**Issue by Torono909** [PrismarineJS/mineflayer#2093]
example:
`*bot create options*
bot.on('chat' function(sendername or senderusername) {
if (message === '$example') {
bot.chat("you cant run that" + sendername)
}
})`

**Comment by O-of** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#chat-username-message-translate-jsonmsg-matches

`username` option is what you want to get the username
