### ISSUE TITLE
is there a way to make bots join with a custom minecraft version this would be useful since i am trying to make a bot for a anarchy server

### ISSUE THREAD

**Issue by Torono909** [PrismarineJS/mineflayer#2095]
idk what to put in description

**Comment by aesthetic0001** [comment]
sub 1.17.1 is supported, just add a `version` parameter with the version as a string. Ex. '1.12.2'

**Comment by Torono909** [comment]
no i don't mean that

**Comment by Torono909** [comment]
like let me show you

**Comment by Torono909** [comment]
CustomVersion Paramater

**Comment by Torono909** [comment]
example:
const mineflayer = require('mineflayer')
const bot = mineflayer.createBot({
	host: 'host',
	port: 25565,
	username: 'usrname',
	customversion: 'The forge mod or fabric mod name'
});

**Comment by extremeheat** [comment]
Please use the edit feature if you need to add information to your last message instead of posting many comments

**Comment by rom1504** [comment]
you could try using https://github.com/PrismarineJS/node-minecraft-protocol-forge if you need some client side features

**Comment by u9g** [comment]
and for fabric, doesn't fabric allow the vanilla client?
