### ISSUE TITLE
Prismarine-chat typings should be in the prismarine-chat repo

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/mineflayer#2100]
https://github.com/PrismarineJS/mineflayer/blob/1a66db8f1a6b1a1d0238dd2a87ea71242b1ea3e4/index.d.ts#L457-L487 should be in prismarine-chat

**Comment by Gjum** [comment]
hmm even though this was auto-closed, the internal types need to be removed and everything pointed to prismarine-chat instead. would make sense to re-open until that is done.
