### ISSUE TITLE
Typo in TS Defs

### ISSUE THREAD

**Issue by lejakewolf** [PrismarineJS/mineflayer#2116]
- [o] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.9.0
 - server: vanilla/spigot/paper 1.16.5
 - node: v14.17.5

##### What are you building? What problem are you trying to solve?

I was just trying the bot using Typescript and ran into errors originating from the library.

```js
node_modules/.pnpm/prismarine-item@1.10.0_minecraft-data@2.91.1/node_modules/prismarine-item/index.d.ts:3:10 - error TS2724: '"prismarine-nbt"' has no exported member named 'Tag'. Did you mean 'Tags'?

3 import { Tag, TagType } from 'prismarine-nbt'
           ~~~

node_modules/.pnpm/prismarine-item@1.10.0_minecraft-data@2.91.1/node_modules/prismarine-item/index.d.ts:11:10 - error TS2304: Cannot find name 'Tags'.

11     nbt: Tags[TagType] | null;
            ~~~~

node_modules/.pnpm/prismarine-windows@2.2.1/node_modules/prismarine-windows/index.d.ts:109:5 - error TS7010: 'findContainerItem', which lacks return-type annotation, implicitly has an 'any' return type.

109     findContainerItem(itemType: number, metadata: number | null, notFull: boolean)
        ~~~~~~~~~~~~~~~~~


Found 3 errors.
```

## What did you try yet?
I monkey-patched the typo, `import { Tag, TagType } from 'prismarine-nbt';` >> `import { Tags, TagType } from 'prismarine-nbt';`
And added a return type to `findContainerItem(itemType: number, metadata: number | null, notFull: boolean)` >> `findContainerItem(itemType: number, metadata: number | null, notFull: boolean): Item | null`
The return type could be wrong but it built sucessfully after those changes.
Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
```js

import { createBot } from 'mineflayer';

const bot = createBot({host: 'localhost', port: 25565, username: "Miner123"});

bot.on('login', () => {
    console.log('Successfully logged in!');
});
```

#### A clear and concise description of what you expected to happen.

The bot logs in properly.

**Comment by u9g** [comment]
closed when https://github.com/PrismarineJS/prismarine-item/pull/38 is closed

**Comment by u9g** [comment]
Fixed
