### ISSUE TITLE
Bot won't take knockback on hypixel

### ISSUE THREAD

**Issue by chickenPizza** [PrismarineJS/mineflayer#2122]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.9.0
 - server: vanilla/spigot/paper 1.8.9
 - node: 16.6.2

## Detailed description of a problem
Is there any way to make the bot take knockback on hypixel? 

## What did you try yet?
Ive tried using this but it wont work: 

bot._client.on('entity_velocity', v => {
    if (bot.entity.id !== v.entityId) return
    
    bot.entity.velocity.x += v.velocityX
    bot.entity.velocity.y += v.velocityY
    bot.entity.velocity.z += v.velocityZ
})

**Comment by nickelpro** [comment]
Related possibly?
https://github.com/PrismarineJS/mineflayer/pull/2043

**Comment by chickenPizza** [comment]
Solved with:

bot._client.on('explosion', explosion => {
        if (bot.physicsEnabled && bot.game.gameMode !== 'creative') {
          bot.entity.velocity.x += explosion.playerMotionX
          bot.entity.velocity.y += explosion.playerMotionY
          bot.entity.velocity.z += explosion.playerMotionZ
        }
      })

**Comment by u9g** [comment]
fixed in 3.10.0, if you update you dont need those lines
