### ISSUE TITLE
Mineflayer Not Reporting All Chat Messages

### ISSUE THREAD

**Issue by ItzMonkeyMax** [PrismarineJS/mineflayer#2147]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.10.0
 - server: vanilla/spigot/paper Hypixel housing. (Presumed 1.8)
 - node: 16.6.1

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?
I am trying to create a bot on Hypixel housing that reads chat messages, but I am having an issue where it doesn't pick up the death messages.
I have tried the events "Message", "Chat", "MessageStr", "Whisper" but seem to have no luck. I can get the join and leave messages, chat + everything else, but it seems like the death messages don't work.

## What did you try yet?

Did you try any method from the API?
"Message", "Chat", "MessageStr", "Whisper"
Did you try any example? Any error from those?
No errors. Just doesn't log the messages.

## Your current code
```js

/*
bot.on('chat', async (username, message) => {
  console.log(message)
})

bot.on('message', (message) => {
  console.log(message.text)
})

bot.on('messagestr', (message) => {
  console.log(message.text)
})

bot.on('whisper', (message) => {
  console.log(message.text)
})
*/


```

## Expected behavior
It should log the death message, eg: `User was killed by User1`.

**Comment by u9g** [comment]
message.text is not what you think it is (look at Prismarine-Chat for more info), use `bot.on('messagestr', msg => console.log(msg.toString())`
