### ISSUE TITLE
ChatMessage clas in TypeScript has only it's methods when used in message listener

### ISSUE THREAD

**Issue by marzeq** [PrismarineJS/mineflayer#2157]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.0
 - server: spigot
 - node: v16.6.2
 - typescript: v4.3.2

## Detailed description of a problem
In TypeScript the class ChatMessage has only it's methods and not it's properties.

## What did you try yet?

Did you try any example? Any error from those?
Error: `src/index.ts:11:25 - error TS2339: Property 'text' does not exist on type 'ChatMessage'.`
Example is below.

## Your current code
```ts
import mineflayer from "mineflayer"

const bot = mineflayer.createBot({
    host: "localhost",
    username: "my email",
    password: "my password",
    version: "1.8.9",
})

bot.on("message", (message, position) => {
    console.log(message.extras[0].text)
})
```

## Expected behaviour
When I acess a property like `extras` on the class the compiler allows me to use it.

**Comment by u9g** [comment]
> Should I direct this issue to that repo then?

Yeah, that works or prs are welcome :)

**Comment by marzeq** [comment]
Thanks! Gonna resubmit this issue on that repo.
