### ISSUE TITLE
Readme languages

### ISSUE THREAD

**Issue by inthmafr** [PrismarineJS/mineflayer#2158]
Shouldn't the readme language button names be in their language? eg. English, Pусский, Español, Français, etc... Also, shouldn't English be "EN" not "US"

**Comment by extremeheat** [comment]
You can open a PR

**Comment by inthmafr** [comment]
> You can open a PR

I've opened a PR now: https://github.com/PrismarineJS/mineflayer/pull/2193

**Comment by inthmafr** [comment]
PR merged, closing issue 👍
