### ISSUE TITLE
Getting the Item from an item Entity within playerCollect is currently failing.

### ISSUE THREAD

**Issue by EvModder** [PrismarineJS/mineflayer#2176]
## Versions
 - mineflayer: 3.11.0
 - server: paper 1.17.1
 - node: 14.17.6

I am writing a simple bot that checks the type of an item when it picks it up (same as in the [chatterbox.js example](https://github.com/PrismarineJS/mineflayer/blob/5a4cfce0456bf4fec06794287744bcc842f14dbc/examples/chatterbox.js#L170), which also happens to be broken when I try running it)

It currently fails when attempting `Item.fromNotch()`, and I am sure I am using the right field from [the Entity metadata[]](https://wiki.vg/Entity_metadata#Entity_Metadata_Format) for Item entities.

Here is the code from `/examples/chatbox.js` which fails for me:
```
bot.on('playerCollect', (collector, collected) => {
  if (collector.type === 'player' && collected.type === 'object') {
    const rawItem = collected.metadata[10]
    const item = mineflayer.Item.fromNotch(rawItem)
    bot.chat(`${collector.username !== bot.username ? ("I'm so jealous. " + collector.username) : 'I '} collected ${item.count} ${item.displayName}`)
  }
})
```

Overall, I have really enjoyed working with mineflayer, and this is the first and only issue I've encountered :)

**Comment by WhoTho** [comment]
Hey,

For some reason the option to input the metadata item list into a toNotch function was taken away (or I am just dumb). Although, if all you are looking for is the data that you can get from the metadata (like id/name and count) this code should work.
```js
bot.on("playerCollect", (collector, collected) => {
  if (collector.type === "player" && collected.type === "object") {
    const rawItem = collected.metadata[8];
    const id = rawItem.itemId;
    const itemName = mcData.findItemOrBlockById(id).displayName;
    const itemCount = rawItem.itemCount;
    if (collector.username == bot.username) {
      bot.chat(`I collected ${itemCount} ${itemName}`);
    } else {
      bot.chat(`I'm so jealous. ${collector.username} collected ${itemCount} ${itemName}`);
    }
  }
});
```

Hope this helps!

**Comment by EvModder** [comment]
Thank you!  This is all I needed for my project
