### ISSUE TITLE
My bot doesn't work propely until I kill it an he respawn 

### ISSUE THREAD

**Issue by thibaultmthh** [PrismarineJS/mineflayer#2177]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.7.0
 - server: vanilla/spigot/paper paper 1.17.1
 - node: v15.11.0

## Detailed description of a problem
I trying to make pathfinder work propely ( i use the exemple code ) and it don't work utile i kill the bot in game then it work, same for the bot.findBlocks function, but bot.chat work

**Comment by u9g** [comment]
what code are you runnning?

**Comment by thibaultmthh** [comment]
Any code, exemple or personal code it's the same, 
i tested it on a 1.16.5 paper server and it work. but not in my 1.17.1 paper server

**Comment by u9g** [comment]
> Any code, exemple or personal code it's the same,
> i tested it on a 1.16.5 paper server and it work. but not in my 1.17.1 paper server

again give us a code example or we can’t help you

**Comment by thibaultmthh** [comment]
// This is an example that uses mineflayer-pathfinder to showcase how simple it is to walk to goals

const mineflayer = require('mineflayer')
const { pathfinder, Movements, goals: { GoalNear } } = require('mineflayer-pathfinder')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node gps.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'gps',
  password: process.argv[5]
})

const RANGE_GOAL = 1 // get within this radius of the player

bot.loadPlugin(pathfinder)

bot.once('spawn', () => {
  const mcData = require('minecraft-data')(bot.version)
  const defaultMove = new Movements(bot, mcData)

  bot.on('chat', (username, message) => {
    if (username === bot.username) return
    if (message !== 'come') return
    const target = bot.players[username]?.entity
    if (!target) {
      bot.chat("I don't see you !")
      return
    }
    const { x: playerX, y: playerY, z: playerZ } = target.position

    bot.pathfinder.setMovements(defaultMove)
    bot.pathfinder.setGoal(new GoalNear(playerX, playerY, playerZ, RANGE_GOAL))
  })
})


Exemple, on this code the bot will not come until i kill it in game, then it will work propely
