### ISSUE TITLE
Microsoft Accounts marked as incorrect credentials

### ISSUE THREAD

**Issue by dansfilms** [PrismarineJS/mineflayer#2199]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.0
 - server: vanilla
 - node: 16.9.1

## Detailed description of a problem
When trying to login with a "Microsoft" Account it will always give an incorrect Username/Password 
## What did you try yet?
Logging in with the account via minecraft launcher and an authentication mod to show the details are correct

## Expected behavior
I expected the Microsoft account to authenticate and be able to use this.

## Additional context
N/A

**Comment by u9g** [comment]
Did you add the property auth: ‘microsoft’ in createbot
