### ISSUE TITLE
onEntityAttacked event which is called when one entity is attacking another

### ISSUE THREAD

**Issue by andrewrk** [PrismarineJS/mineflayer#22]
Hi. Mineflyaer javascript-engine provides a handlers for some gameplay events like "onChat()" or "onHealthChanged()" etc. Can you add a new event handler like a "onEntityAttacked", this event is called when one entity is attacking another (mob, player or self)? This event is helful to create an bots are strike if they are attacked, for example.

Regards, Cr0s.
P.S. Sorry for my bad english, I'am from Russian Federation.

**Comment by NatoBoram** [comment]
What's the way of knowing when an entity gets attacked now?

**Comment by u9g** [comment]
> What's the way of knowing when an entity gets attacked now?
https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#entityhurt-entity
