### ISSUE TITLE
Logging in with a microsoft account

### ISSUE THREAD

**Issue by Fusezion** [PrismarineJS/mineflayer#2207]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.0
 - server: vanilla/spigot/paper: Paper
 - node: 1.16.6

## Detailed description of a problem
When I'm trying to log in using my microsoft account 
```
auth: 'microsoft',
username: 'dasd'
password: 'adsd'
```
I get a repeating message in the console saying ``"Unable to authenticate with Microsoft XboxReplayError: Request failed with status code 401"``

A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?
I've followed everything that is sent in the console.

## Your current code
```js
const bot = mineflayer.createBot({
	host: 'temp_ip',
	auth: 'microsoft',
	username: 'UNKNOWN@UNKNOWN.com', // minecraft username
	password: 'PASSWORD', // minecraft password, comment out if you want to log into online-mode=false servers
}).once('login', () => {
	console.log('Works')
})

```

## Expected behavior

Was planning to log into the server and have the chat log to a localhost
but I'm unable to even get past the ``createBot`` method

## Additional context

I used this prior to migrating over to my Microsoft however ever since I never really touched it until a friend sent me something he made so I decided to try it out his works fine but whenever I log in with my I get this error

![image](https://user-images.githubusercontent.com/81952476/133375185-41e57f59-5f30-474d-a20e-81c978fc1e38.png)

**Comment by Kashalls** [comment]
We don't recommend using password authentication with microsoft account, we still support it just in-case but Microsoft has been cracking down on it, migrated accounts for me don't seem to work anymore.

Does device auth work?

**Comment by Fusezion** [comment]
> We don't recommend using password authentication with microsoft account, we still support it just in-case but Microsoft has been cracking down on it, migrated accounts for me don't seem to work anymore.
> 
> Does device auth work?

don't fully know what you mean by that but I'm a go with no

**Comment by Kashalls** [comment]
> > We don't recommend using password authentication with microsoft account, we still support it just in-case but Microsoft has been cracking down on it, migrated accounts for me don't seem to work anymore.
> > 
> > Does device auth work?
> 
> don't fully know what you mean by that but I'm a go with no

Device code is when it asks you to open a web browser and put this little tiny code in

**Comment by Fusezion** [comment]
do you know any other method I might be able to use my Microsoft account for this as I doubt buying a new account would be worth it then if I can't even log in with this one

**Comment by extremeheat** [comment]
Fix blocked by https://github.com/PrismarineJS/prismarine-auth/issues/10

**Comment by JakeyPrime** [comment]
+1 to this. Password auth fails with 401, non password asks me for a code, processes it, signs in, but then does nothing and repeats, providing a new code.

**Comment by extremeheat** [comment]
Account date of birth must be >= 18 years old, or added to a Microsoft family. Login to http://xbox.com to do that.

**Comment by Vincent550102** [comment]
I have the same problem.
I add email to the Microsoft family and set the accounting date >= 18.
![image](https://user-images.githubusercontent.com/48404862/142467714-6e92a73b-b8d0-4c72-923a-1500e2de188d.png)

**Comment by extremeheat** [comment]
Update your mineflayer
