### ISSUE TITLE
Kicked from server "Internal Exception: io.netty.handler.timeout.ReadTimeoutException"

### ISSUE THREAD

**Issue by sefirosweb** [PrismarineJS/mineflayer#2209]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.0
 - server: spigot (i think)
 - node: 16.8.0

## Detailed description of a problem
After a few seconds the bot is kicked from server,

I research i did seems is anti cheat / bots, but the bot don't does "nothing" strange, i made a simply code to follow me and also is kicked

Maybe the server is waiting any packet and the bot was doesn't sent it?

The error is thrown via on "kicked" function:
```js
bot.once('kicked', (error) => {
  console.log(error)
})
```
{"text":"Internal Exception: io.netty.handler.timeout.ReadTimeoutException"}

## What did you try yet?
I did a simply code & video:

https://www.youtube.com/watch?v=32ZdaGbUCLw

```js
const { sleep } = require('../modules/utils')
const mineflayer = require('mineflayer')

if (process.argv.length < 3 || process.argv.length > 6) {
  console.log('Usage : node chest.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: process.argv[3] ? parseInt(process.argv[3]) : 25565,
  username: process.argv[4] ? process.argv[4] : 'Sephi',
  password: process.argv[5]
})

bot.once('error', (error) => {
  console.log(error)
})

bot.once('kicked', (error) => {
  console.log(error)
})

bot.once('spawn', async () => {
  const mcData = require('minecraft-data')(bot.version)
  const { pathfinder, Movements, goals } = require('mineflayer-pathfinder')
  bot.loadPlugin(pathfinder)
  bot.pathfinder.setMovements(new Movements(bot, mcData))

  const goPosition = () => {
    bot.pathfinder.setGoal(new goals.GoalBlock(37, 51, 11))

    return new Promise(resolve => {
      bot.on('goal_reached', (goal) => {
        resolve()
      })
    })
  }

  bot.chat('/login password')
  await sleep(2000)
  await goPosition() //
  await sleep(500) //
  let filter = e => e.type === 'player' && e.position.distanceTo(bot.entity.position) < 3 //
  let entity = bot.nearestEntity(filter) //
  if (entity) { //
    bot.useOn(entity) // 
    await sleep(2000) //
    filter = e => e.type === 'player' && e.position.distanceTo(bot.entity.position) < 20 //
    entity = bot.nearestEntity(filter) // I need to do this lines because the bot goes to "fake" player and click for go to "survival" world
    if (entity) {
      const goal = new goals.GoalFollow(entity, 3)
      bot.pathfinder.setGoal(goal, true)
    }
  }
})

```

**Comment by qxZap** [comment]
[15:16:48 WARN]: io.netty.channel.unix.Errors$NativeIoException: syscall:write(..) failed: Broken pipe
[15:16:48 WARN]:        at io.netty.channel.unix.FileDescriptor.writeAddress(..)(Unknown Source)
[15:16:48 WARN]: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
[15:16:48 WARN]:        at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
[15:18:20 WARN]: io.netty.handler.timeout.ReadTimeoutException
[15:19:50 WARN]: io.netty.handler.timeout.ReadTimeoutException
[15:22:35 WARN]: io.netty.handler.timeout.ReadTimeoutException

Same thing down here. Tested all my code on local and worked fine.

**Comment by sefirosweb** [comment]
@qxZap  I have same issue, in local with vanilla servers work perfect

I think the servers have any method for detect is a real client or bot, and they kicks him

**Comment by qxZap** [comment]
Solved (at least in my case). I have seen that error not just here in the bot, but also in many other situations, situations when connection was poor and the version was not defined. I have a ViaVersion plugin installed and i think when you do not specifu the version, won't work
The communications should be like:
Client => Server (what version are you on, server?)
Server => Client (i'm on 1.16.4, but i can accept multiple versions. What version are you in?)
Client => Server (I'm on ????)

This is just my belive, since i specified the version 
`version: "1.16.4"`
And worked like a charm. Give it a shot

**Comment by sefirosweb** [comment]
I tried a alot versions and all of them is not working :(

Also the server "supports" a multiple versions..

![image](https://user-images.githubusercontent.com/20754836/133895543-67d55735-3a58-4769-9dc5-3f380f1565fe.png)

Also the strange is the bot works for a few seconds until 1 min aproax

**Comment by qxZap** [comment]
Common ones for minigame server: 1.12.2 , 1.8 and 1.8.9

**Comment by sefirosweb** [comment]
I tried these versions but nothing,

finally I have to do a foreach for each version and wait several hours xD

**Comment by qxZap** [comment]
Recent findings. You can have this issue if you did not update your mineflayer to 1.17 support and try to login from 1.17 version

**Comment by rom1504** [comment]
seems solved
