### ISSUE TITLE
ContainerWindow methods and bot.openContainer() are not recognized by typescript

### ISSUE THREAD

**Issue by NepNep21** [PrismarineJS/mineflayer#2210]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.0
 - server: Unrelated
 - node: 16.9.0
 - typescript: 4.4.3

## Detailed description of a problem
ContainerWindow methods, such as close() and withdraw() are not recognized by typescript for me, throwing the error below
https://i.imgur.com/Tudp5t8.png
Another thing is bot.openContainer() doesn't appear either

## What did you try yet?
Using "any" type for the result of bot.openChest(), it works, but disables typescript features

## Your current code
```js
const chest = await bot.openChest(chestBlock);
chest.close(); // Compile error

// Works
const chest: any = await bot.openChest(chestBlock);
chest.close();
```

## Expected behavior
For ContainerWindow methods and bot.openContainer() to be recognized by typescript

**Comment by u9g** [comment]
PRs welcome :)

**Comment by NepNep21** [comment]
I may try to see what's wrong next week

**Comment by NepNep21** [comment]
With the latest release, chest typings seem to mostly work, but containerItems(), which is specifically what i need, doesn't, should i just add it to the typings or is there some inheritance i should take into account?

**Comment by liquiddevelopmentnet** [comment]
Request issue close @rom1504
