### ISSUE TITLE
Lever

### ISSUE THREAD

**Issue by barrulik** [PrismarineJS/mineflayer#2216]
Is it possible to change level from on to off, like flicking it

**Comment by aesthetic0001** [comment]
[bot.activateBlock()](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botactivateblockblock-callback) perhaps? also please use GH discussions or ask in the discord next time for questions like this

**Comment by barrulik** [comment]
Ty :)

**Comment by aesthetic0001** [comment]
should be closed
