### ISSUE TITLE
digging blocks at cursor

### ISSUE THREAD

**Issue by hazemfarah123** [PrismarineJS/mineflayer#2223]
## Versions
 - mineflayer: 3.11.1
 - server: vanilla/spigot/paper 1.16.5
 - node: 14.17.6

## Detailed description of a problem
I have been trying for 5 days to make a bot that digs cobblestone in a generator, but after the bot started digging for me less than a minute, the bot stops working with me, an error I do not know the cause

## Your current code
```js

function dig() {
	if (bot.blockAtCursor() !== undefined) {
		var blockD = bot.blockAt(bot.blockAtCursor().position)
		if (blockD !== undefined) {
     
        bot.dig(blockD,onDiggingCompleted)
      
			
		}else{
      
        dig()
      
			
		}
	}else{
    
      dig()
    
		
	}
	function onDiggingCompleted (err) {
		if (err) {
			console.log(err.stack)
			return
			
        dig()
      
		}else{
      setTimeout(() => {
        dig()
      }, 100);
        
      
			
		}
	}
}


```

error:
```js
cannot read property 'position' of null
```

**Comment by SJS830** [comment]
The code on line 2 to check if bot.botAtCursor is indefined isn’t working
