### ISSUE TITLE
add an optional connect method to the bot. (ratelimiting) 

### ISSUE THREAD

**Issue by ClientCrash** [PrismarineJS/mineflayer#2226]
## Is your feature request related to a problem? Please describe.
- Microsoft will ratelimit your account if you login to often i a short timespan.
- you cant easily switch servers if you are already logged in
- constantly logging in and out of the api is time consuming

## Describe the solution you'd like
- Continue to support the 'oldschool' method of connection by specifying the host in the create bot but 
- also offer a connect method (with port and host) to connect / reconnect without signing in to microsoft all the time. This is also usefull for switching servers.

## Describe alternatives you've considered
I have considered the alternative in #975 but this doesnt work without creating a bot (and signing in again) every time you want to reconnect.

## Coding information
The connect method could take a json object with host and port, like createBot but only with this 2 arguments. `bot.connect({host:'hypixel.net',port:25565})`

**Comment by u9g** [comment]
make a token with yggdrasil, then auth the first bot with that token and any consecutive bot with the aame token

**Comment by ClientCrash** [comment]
> make a token with yggdrasil, then auth the first bot with that token and any consecutive bot with the aame token

I will try this thank you. But i still believe adding a connect method will make the bot much more easy to use in the future. This will also prevent many issues on github and many workarounds. I think this library is intended to make bot development easy
