### ISSUE TITLE
hosting on heroku, bot join for a second then left

### ISSUE THREAD

**Issue by EndermanHackerVN** [PrismarineJS/mineflayer#2240]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: vanilla
 - node: 16.9.1

## Detailed description of a problem
I host my bots on Heroku, and after I uploaded the repo, the mineflayer bot just join for a second then left. Running on local machine doesn't have any errors / bug showing up.

## What did you try yet?

Did you try any method from the API? ✅
Did you try any example? Any error from those? ✅

## Your current code
```js
    console.log("--------------------------------------------------------------------------------------------");
    console.log(`${moment().format('MMMM Do YYYY, h:mm:ss a')} | [💬] Starting Minecraft bot in 15 seconds!`) 
    bot = mineflayer.createBot({ host: '', username: '', version: "1.17.1", plugins: [AutoAuth],  AutoAuth: ''})
    
    bot.on('serverAuth', function() {
        console.log(`${moment().format('MMMM Do YYYY, h:mm:ss a')} | [💬] Minecraft bot is now online!`)
        console.log("--------------------------------------------------------------------------------------------");  
    });
    
    bot.on('chat', (username, message) => {
        console.log(`${username} | ${message}`)
    });
```

## Expected behavior
It should be online then logging chat message into the console

## Additional context
I installed mineflayer-auto-auth if you ask

**Comment by mat-1** [comment]
Maybe the server kicks clients logging in from Heroku? Try logging the error/kick message.

**Comment by EndermanHackerVN** [comment]
it is a anti vpn plugin, guess im 2 dumbfolded. Thanks for your help @mat-1.
