### ISSUE TITLE
Bot Launching Issues

### ISSUE THREAD

**Issue by disaaalt** [PrismarineJS/mineflayer#2242]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: vanilla 1.8.9
 - node: 16.6.1

## Detailed description of a problem
I am currently trying to create a Mineflayer bot that simply prints messages into console whenever it receives one (in detail, the `messagestr` event).
I am making it in a Discord bot handler.

## What did you try yet?
- `npm i`
- `npm i mineflayer`
- deleting package.json, reinstalling every package

## Your current code
```js
const mineflayer = require('mineflayer')
module.exports = (bot) => {
    const account = mineflayer.createBot({
        host: bot.config.minecraft.server.ip,
        port: bot.config.minecraft.server.port,

        username: bot.config.minecraft.player.username,
        
        version: "1.8.9"
    })
    bot.L.logCustom('MC', 'Successfully created the account with username ' + account.player.username + '.');
}
```
(on the DiscordJS ready event)
```js
// Start MC bot
bot.L.logCustom('MC', 'Trying to launch Minecraft Bot..')
require('.././utils/functions/minecraft/mineflayerBot')(bot);
```

## Expected behavior
To not error.

## Additional context
Here is the full log.
```MC -> Trying to launch Minecraft Bot..
undefined:71
      let  = value.
      ^^^

SyntaxError: Unexpected strict mode reserved word
    at SizeOfCompiler.compile (D:\Important\glance.top\Glance Helper\node_modules\protodef\src\compiler.js:258:17)
    at ProtoDefCompiler.compileProtoDefSync (D:\Important\glance.top\Glance Helper\node_modules\protodef\src\compiler.js:53:43)
    at createProto (D:\Important\glance.top\Glance Helper\node_modules\prismarine-nbt\nbt.js:21:19)
    at Object.<anonymous> (D:\Important\glance.top\Glance Helper\node_modules\prismarine-nbt\nbt.js:24:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (D:\Important\glance.top\Glance Helper\node_modules\minecraft-protocol\src\datatypes\minecraft.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)```
(and yes, it is the correct file, mineflayerBot.js is the only file which has required mineflayer.)

**Comment by hanatic** [comment]
This is not a bug. This is an issue with your code: I can't see exactly what it is because you sent only part of your code, but as the error shows you haven't declared a variable name. Therefore the JS compiler presume you're trying to assign a variable called "let" to another variable called "value". Add a variable name after the word "let" and your code will be entirely fixed.

**Comment by disaaalt** [comment]
> This is not a bug. This is an issue with your code: I can't see exactly what it is because you sent only part of your code, but as the error shows you haven't declared a variable name. Therefore the JS compiler presume you're trying to assign a variable called "let" to another variable called "value". Add a variable name after the word "let" and your code will be entirely fixed.

Thanks for the reply,
Just to clarify, I am not a beginner JS developer. I understand these things.
I have provided all the code you need, the only reason is that the error only occurs when the code I provided is run. It is not a part, it is the entire file.

**Comment by hanatic** [comment]
Sorry, you've kind of lost me.

**Comment by disaaalt** [comment]
> Sorry, you've kind of lost me.

The code I provided is the entire file and has "technically" no errors in it. **Whenever I run it, it errors.** If I remove it, it doesnt.

**Comment by U5B** [comment]
Could you try mineflayer in a different file? Example: just pasting this into a new file
```js
const config = require('./your config file')
const mineflayer = require('mineflayer')

const options = {
  host: '0.0.0.0', // replace with ip
  port: 25565, // replace with port
  username: 'username', // replace with minecraft username
  version: "1.8.9"
}

const bot = mineflayer.createBot(options)
bot.on('login', () => {
  console.log('success!')
})
bot.on('error', (err) => {
  console.log(err)
})```

**Comment by hanatic** [comment]
> **Whenever I run it, it errors.** If I remove it, it doesn't.

Yes, because that section is causing an error as it's missing some syntax. I'm not sure what your point is other than that. Just in case, do what @U5B said.

**Comment by disaaalt** [comment]
> Could you try mineflayer in a different file? Example: just pasting this into a new file
> 
> EDIT: also make sure that `bot.config.minecraft` is not undefined, as that will cause errors just doing `console.log(bot.config.minecraft)` and make sure that is defined
> 
> ```js
> const mineflayer = require('mineflayer')
> 
> const options = {
>   host: '0.0.0.0', // replace with ip
>   port: 25565, // replace with port
>   username: 'username', // replace with minecraft username
>   version: "1.8.9"
> }
> 
> const bot = mineflayer.createBot(options)
> bot.on('login', () => {
>   console.log('success!')
> })
> bot.on('error', (err) => {
>   console.log(err)
> })
> bot.on('messagestr', (message) => {
>   console.log(message)
> })
> ```

Thank you for this response. I will try after class.

**Comment by disaaalt** [comment]
> > **Whenever I run it, it errors.** If I remove it, it doesn't.
> 
> Yes, because that section is causing an error as it's missing some syntax. I'm not sure what your point is other than that. Just in case, do what @U5B said.

No offense, but all your replies are sort of useless to me. You have pointed out my syntax is incorrect, even though I can't find any syntax errors after endless replies by me. And just for you to know, I know when I miss a damn variable name.
Thanks for your replies though.

**Comment by disaaalt** [comment]
Ive done some research, and I think the error is not about keywords after let. It's something about let itself. Gotta ask U5B though.

**Comment by disaaalt** [comment]
US5's solution worked. Thanks for the help <3

**Comment by malekashkar** [comment]
I would like to re-open this issue because I'm facing the same problem. Running mineflayer alongside my discord bot is causing the same error.

`[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [SyntaxError: Unexpected strict mode reserved word]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at SizeOfCompiler.compile (C:\Users\\Desktop\Projects\test\node_modules\protodef\src\compiler.js:258:17)]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at ProtoDefCompiler.compileProtoDefSync (C:\Users\\Desktop\Projects\test\node_modules\protodef\src\compiler.js:53:43)]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at createProtocol (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\transforms\serializer.js:35:28)]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at createSerializer (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\transforms\serializer.js:49:25)]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at Client.setSerializer (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\client.js:42:23)]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at set state [as state] (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\client.js:133:10)]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at new Client (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\client.js:33:16)]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at Object.createClient (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\createClient.js:37:18)]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at Object.createBot (C:\Users\\Desktop\Projects\test\node_modules\mineflayer\lib\loader.js:98:35)]
[E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at ConsoleAccounts.setupBots (C:\Users\\Desktop\Projects\test\dist\consoleClient\index.js:58:46)]`

**Comment by heheleo** [comment]
> I would like to re-open this issue because I'm facing the same problem. Running mineflayer alongside my discord bot is causing the same error.
> 
> ```
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [SyntaxError: Unexpected strict mode reserved word]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at SizeOfCompiler.compile (C:\Users\\Desktop\Projects\test\node_modules\protodef\src\compiler.js:258:17)]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at ProtoDefCompiler.compileProtoDefSync (C:\Users\\Desktop\Projects\test\node_modules\protodef\src\compiler.js:53:43)]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at createProtocol (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\transforms\serializer.js:35:28)]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at createSerializer (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\transforms\serializer.js:49:25)]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at Client.setSerializer (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\client.js:42:23)]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at set state [as state] (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\client.js:133:10)]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at new Client (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\client.js:33:16)]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at Object.createClient (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\createClient.js:37:18)]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at Object.createBot (C:\Users\\Desktop\Projects\test\node_modules\mineflayer\lib\loader.js:98:35)]
> [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at ConsoleAccounts.setupBots (C:\Users\\Desktop\Projects\test\dist\consoleClient\index.js:58:46)]
> ```

Could you send us your code? I might be able to help this time.

**Comment by malekashkar** [comment]
> > I would like to re-open this issue because I'm facing the same problem. Running mineflayer alongside my discord bot is causing the same error.
> > ```
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [SyntaxError: Unexpected strict mode reserved word]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at SizeOfCompiler.compile (C:\Users\\Desktop\Projects\test\node_modules\protodef\src\compiler.js:258:17)]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at ProtoDefCompiler.compileProtoDefSync (C:\Users\\Desktop\Projects\test\node_modules\protodef\src\compiler.js:53:43)]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at createProtocol (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\transforms\serializer.js:35:28)]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at createSerializer (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\transforms\serializer.js:49:25)]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at Client.setSerializer (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\client.js:42:23)]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at set state [as state] (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\client.js:133:10)]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at new Client (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\client.js:33:16)]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at Object.createClient (C:\Users\\Desktop\Projects\test\node_modules\minecraft-protocol\src\createClient.js:37:18)]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at Object.createBot (C:\Users\\Desktop\Projects\test\node_modules\mineflayer\lib\loader.js:98:35)]
> > [E] [23-01-2024, 05:22:54 PM] [compiler.js:53:43] [UNCAUGHT_EXCEPTION] [at ConsoleAccounts.setupBots (C:\Users\\Desktop\Projects\test\dist\consoleClient\index.js:58:46)]
> > ```
> 
> Could you send us your code? I might be able to help this time.

```
```
/* eslint-disable @typescript-eslint/no-unused-vars */
interface String {
  capitalize(): string;
  toProperCase(): string;
}

String.prototype.capitalize = function () {
  return this.charAt(0).toUpperCase() + this.slice(1).toLowerCase();
};

String.prototype.toProperCase = function () {
  return this
    .replace(/_/g, ' ')
    .replace(/\w\S*/g, (txt) => txt.charAt(0).toUpperCase() + txt.substring(1).toLowerCase());
};

interface Number {
  periodicFormat(): string;
  postFormatter(
    k?: boolean,
    m?: boolean,
    b?: boolean,
    t?: boolean,
  ): string;
  timeFormat(
    showSeconds?: boolean,
    showMinutes?: boolean,
    showHours?: boolean,
    showDays?: boolean,
    showWeeks?: boolean,
    showMonths?: boolean,
    showYears?: boolean,
  ): string;
}

Number.prototype.periodicFormat = function () {
  return this.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
};

Number.prototype.postFormatter = function (k = true, m = true, b = true, t = true) {
  const num = this.valueOf();
  if (Math.abs(num) >= 1000000000000 && t) return `${(Math.sign(num) * (Math.abs(num) / 1000000000000)).toFixed(0)}T`;
  if (Math.abs(num) >= 1000000000 && b) return `${(Math.sign(num) * (Math.abs(num) / 1000000000)).toFixed(0)}B`;
  if (Math.abs(num) >= 1000000 && m) return `${(Math.sign(num) * (Math.abs(num) / 1000000)).toFixed(0)}M`;
  if (Math.abs(num) >= 1000 && k) return `${(Math.sign(num) * (Math.abs(num) / 1000)).toFixed(0)}K`;
  return (Math.sign(num) * Math.abs(num)).toFixed(0);
};

Number.prototype.timeFormat = function (
  showSeconds = true,
  showMinutes = true,
  showHours = true,
  showDays = true,
  showWeeks = true,
  showMonths = true,
  showYears = true,
) {
  const num = this.valueOf() / 1000;

  const years = Math.floor(num / 31536000);
  const months = Math.floor(num / 2592000);
  const weeks = Math.floor(num / 604800);
  const days = Math.floor(num / 86400);
  const hours = Math.floor(num / 3600) % 24;
  const minutes = Math.floor(num / 60) % 60;
  const seconds = Math.floor(num % 60);

  let time = '';

  if (showYears && years > 0) time += `${years}y `;
  if (showMonths && months > 0) time += `${months}mo `;
  if (showWeeks && weeks > 0) time += `${weeks}w `;
  if (showDays && days > 0) time += `${days}d `;
  if (showHours && hours > 0) time += `${hours}h `;
  if (showMinutes && minutes > 0) time += `${minutes}m `;
  if (showSeconds && seconds > 0) time += `${seconds}s`;

  return time.trim();
};

interface Array<T> {
  random(): T;
  shuffle(): T[];
}

Array.prototype.random = function () {
  return this[Math.floor(Math.random() * this.length)];
}

Array.prototype.shuffle = function () {
  for (let i = this.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [this[i], this[j]] = [this[j], this[i]];
  }
  return this;
}

interface Date {
  earlierThanDuration(minutes?: number, hours?: number, days?: number): boolean;
  timeDifference(minutes?: number, hours?: number, days?: number): number;
}

Date.prototype.earlierThanDuration = function (minutes = 0, hours = 0, days = 0): boolean {
  const totalMilliseconds = (minutes * 60000) +
    (hours * 3600000) +
    (days * 86400000);
  return this.getTime() - totalMilliseconds > Date.now();
}

Date.prototype.timeDifference = function (minutes = 0, hours = 0, days = 0): number {
  const totalMilliseconds = (minutes * 60000) +
    (hours * 3600000) +
    (days * 86400000);
  return this.getTime() - totalMilliseconds - Date.now();
}
```

I have the above code in a separate file from the mineflayer stuff, however, I import this file and it causes the error. When removing the import, the error is gone.

Also, when I only run the String prototypes, I don't face the error, I'm guessing it's something with the number or array prototypes.

**Comment by heheleo** [comment]
I rewrote your code using `defineProperty` instead [here](https://srcb.in/ojNJZapdFU). It is working on my setup. No clue why mineflayer doesn't like it.
