### ISSUE TITLE
can toss item

### ISSUE THREAD

**Issue by animovigamlxh** [PrismarineJS/mineflayer#2246]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2(latest )
 - server: vanilla/spigot/paper #.#.#
 - node: 16.10.0(latest )
 - Minecraft version :1.17.1

## Detailed description of a problem
I just test the [`Inventory .js`](https://github.com/PrismarineJS/mineflayer/blob/master/examples/inventory.js) .
when the bot join game ,I give it a diamond ,and say 'list' ,the bot reply 'diamond x 1' correctly .
But then I say 'toss 1 diamond ' ,it just reply 'tossed 1 x diamond ' **three times** without noting to be tossed and then quit the game automatically **without no log** in console.

## What did you try yet?
* try `tossStack(item)`,still don't work 
* update the `mineflayer` and `node`
* reinstall mineflayer
* restart the computer 
## Your current code
* all like `inventory .js` except the head.
```js

const mineflayer = require('mineflayer')
const bot = mineflayer.createBot({
  host: '127.0.0.1',
  port: 63832,
  username: 'player',
})



```

## Expected behavior
If I say 'toss *',the bot can toss something what I want

**Comment by rom1504** [comment]
not enough info to reproduce your issue

**Comment by DarkCoder15** [comment]
Updated both minecraft-protocol and mineflayer, issue seems to be fixed.
