### ISSUE TITLE
Mineflayer commands in discord

### ISSUE THREAD

**Issue by nicksharma0** [PrismarineJS/mineflayer#2261]
So first off let me say I AM A COMPLETE NOOB to coding. Most of what I'm doing is coming from youtube tutorials and such as I'm just trying to learn what code does what and the basics are. So here's what I'm trying to do:

Basically I want to be able to type a command from discord and have the bot output that command in game. So to start off I just did a simple ping command to test in discord that my bot was working, and after I could sudo the bot in game. However when I tried doing this, it didn't work, I got no output in discord nor an error message.

My code for that one command:
```js
client.on('message', message =>{
    if(!message.content.startsWith(prefix) || message.author.bot) return;

    const args = message.content.slice(prefix.length).split(/ +/);
    const command = args.shift().toLowerCase();

    if(command === 'ping'){
        message.channel.send('pong!')
    }
});
```
If anyone knows why this isn't working or need extra information please tell me as I really want to get this up and running.

**Comment by Yanique1** [comment]
Here is the full code, again everything works except the .ping command

const { Client, Intents } = require('discord.js')
const client = new Client({ intents: [Intents.FLAGS.GUILDS] });
const Discord = require('discord.js')
const mineflayer = require('mineflayer')
const prefix = "." 
let sending = false;
let chatData = [];

let bot = mineflayer.createBot({
    host: 'Jartex.fun',
    version: '1.8',
    username: 'NkNukes'
})
client.on("ready", async =>{
    console.log("Online!")
})
bot.on('ready', async =>{
    console.log("Succesfully connected!")
})
bot.on('login', async =>{
    bot.chat('/login eLhQeIfiog1F')
    bot.chat('/server immortal')
})
bot.on('message', message =>{
    let channel = client.channels.cache.get('895462096387600465')
    channel.send("```" + `${message}` + "```")
})
client.on('message', message =>{
    if(!message.content.startsWith(prefix) || message.author.bot) return;

    const args = message.content.slice(prefix.length).split(/ +/);
    const command = args.shift().toLowerCase();
    if(command === 'ping'){
        message.channel.send('pong!')
    }
});
client.login(clientToken)

**Comment by U5B** [comment]
Try console.log(args) and console.log(command) to see if the output matches what you expect.

**Comment by Yanique1** [comment]
Apparently this is working for other people, what could I be missing?

**Comment by Yanique1** [comment]
This is indeed the problem. I myself find discord.js v12 easier to use so I will start using that, thanks for your help :D
