### ISSUE TITLE
CreateMethod broken

### ISSUE THREAD

**Issue by RudiBott** [PrismarineJS/mineflayer#2265]
Hello. i tried to create a Bot with mineflayer. This is my code

``
const mineflayer = require('mineflayer')

const  bot = mineflayer.createBot({
  host: '*****', // minecraft server ip
  username: '****', // minecraft username
  password: '*****' // minecraft password, comment out if you want to log into online-mode=false servers
  // port: 25565,                // only set if you need a port that isn't 25565
  // version: false,             // only set if you need a specific version or snapshot (ie: "1.8.9" or "1.16.5"), otherwise it's set automatically
  // auth: 'mojang'              // only set if you need microsoft auth, then set this to 'microsoft'
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)

``

This is the error message:

 bot = mineflayer.createBot({
                  ^

TypeError: mineflayer.createBot is not a function
    at Object.<anonymous> (/root/mineflayer/mineflayer/index.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
    
    I hope anyone here can help me!

**Comment by U5B** [comment]
Make sure you installed mineflayer by doing 'npm install mineflayer' in your terminal.

**Comment by U5B** [comment]
Can you try installing mineflayer where index.js is? require('mineflayer') basically looks for a package inside node_modules named mineflayer

**Comment by RudiBott** [comment]
i tried it again, but i am getting the same error again.
