### ISSUE TITLE
SkinRestorer plugin: Some mineflayer features don't work if you change the skin

### ISSUE THREAD

**Issue by qsef1256** [PrismarineJS/mineflayer#2269]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: paper 1.17.1-341
 - node: 14.18.1
 - SkinRestorer: 14.1.5
 - ProtocolLib: 4.7.0

## Detailed description of a problem
I'm testing plugins/Skript with mineflayer in offline mode since I don't have another minecraft account.

Mineflayer-pathfinder and knockback of bots do not work after changing skins with SkinRestorer in offline mode. There may be more broken features.

It works fine after respawning.

## What did you try yet?
https://github.com/PrismarineJS/mineflayer/blob/92e54f6d533d5b1e9dd0022754947845606eda56/examples/pathfinder/gps.js
https://github.com/PrismarineJS/mineflayer-pathfinder/blob/29f61cffe3906a82f50d9e176f0a1c0f0d3f4d9b/examples/example.js

I tested two example bots. Same bug occurs.

Tested on clean Paper 1.17.1 server with only ProtocolLib and SkinRestorer loaded.

I got the following output from the example.js bot: `I can get there in 0 moves. Computation took 0.17 ms (1 nodes, 302.30 nodes/tick)`

## Your current code
https://github.com/qsef1256/DiaBot/blob/main/diabot.js

## Expected behavior
The bot should work normally.

## Additional context
Before I realized it was an issue with SkinRestorer, I opened the following issue: 
https://github.com/PrismarineJS/mineflayer-pathfinder/issues/212
https://github.com/qsef1256/DiaBot/issues/1
I'll redirect these issues here.

I also think this issue may be related to these issues: #2177, #1405

**Comment by U5B** [comment]
Could you test this branch and see if this fixes your issue?
https://github.com/U5B/mineflayer/tree/skinsRestorerFix

**Comment by qsef1256** [comment]
The problem seems to have been resolved. My bot works fine now.

Can I close this issue?

**Comment by U5B** [comment]
Don't close it. The PR (when it gets merged) will close it automatically.
