### ISSUE TITLE
Come and see

### ISSUE THREAD

**Issue by Geruays** [PrismarineJS/mineflayer#2289]
I run the bot on spigot 1.17.1 and i got so lag in server it may cause view distance bot

Can u help me?

**Comment by XfedeX** [comment]
This is not fault of the bot, it's fault of your hardware.
You could try using:
```js
bot.settings.viewDistance = "tiny"
```
inside `bot.once(spawn, function() { /* HERE */ })`

**Comment by Geruays** [comment]
> This is not fault of the bot, it's fault of your hardware. You could try using:
> 
> ```js
> bot.settings.viewDistance = "tiny"
> ```
> 
> inside `bot.once(spawn, function() { /* HERE */ })`

ReferenceError: spawn is not defined
    at Object.<anonymous> (/data/data/com.termux/files/home/b/index.js:15:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

**Comment by XfedeX** [comment]
> 
> 
> > This is not fault of the bot, it's fault of your hardware. You could try using:
> > ```js
> > bot.settings.viewDistance = "tiny"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > inside `bot.once(spawn, function() { /* HERE */ })`
> 
> ReferenceError: spawn is not defined at Object. (/data/data/com.termux/files/home/b/index.js:15:10) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) at node:internal/main/run_main_module:17:47

Sorry, it's my fault, i forgot quotes 😞
You should use it inside ```js
bot.once("spawn",function() { /*HERE*/ })
```

**Comment by Zn10plays** [comment]
Like  Geruays said this is not a issue with the bot it is a issue with your hardware or server. 
If you really believe this has something to do with the bot, create a new issue with more info.

**Comment by u9g** [comment]
> This is not fault of the bot, it's fault of your hardware. You could try using:
> 
> ```js
> bot.settings.viewDistance = "tiny"
> ```
> 
> inside `bot.once(spawn, function() { /* HERE */ })`

this does nothing as mineflayer doesn’t do anything with the viewdistance

**Comment by XfedeX** [comment]
> 
> 
> > This is not fault of the bot, it's fault of your hardware. You could try using:
> > ```js
> > bot.settings.viewDistance = "tiny"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > inside `bot.once(spawn, function() { /* HERE */ })`
> 
> this does nothing as mineflayer doesn’t do anything with the viewdistance

It does, it is the max distance the bot can hold chunks in memory: https://mineflayer.prismarine.js.org/#/api?id=botsettingsviewdistance

**Comment by U5B** [comment]
> 
> It does, it is the max distance the bot can hold chunks in memory: https://mineflayer.prismarine.js.org/#/api?id=botsettingsviewdistance

https://github.com/PrismarineJS/mineflayer/search?q=bot.settings.viewDistance
https://github.com/PrismarineJS/mineflayer/blob/a0befeb042fe3851ac35887da116c2910f505791/lib/plugins/settings.js#L28
bot.settings.viewDistance is only sent to the server.
It is not used internally for anything.
It does not limit how many chunks the bot can hold in memory.

**Comment by aesthetic0001** [comment]
should prob be closed

**Comment by u9g** [comment]
You don't lag because of view distance because it doesn't effect the bot, reopen with more info.
