### ISSUE TITLE
Not working without entering port when using a proxy

### ISSUE THREAD

**Issue by XfedeX** [PrismarineJS/mineflayer#2292]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest

## Detailed description of a problem
If you try using Mineflayer with a proxy, it requires to enter a port, and doesn't let you leave it empty.
Some servers use "SERV" domain and if you manually enter port "25565" the SERV domain gets ignored and bot can't connect.

### Any example of servers not working with the proxy?
Any Aternos server.

### What about your code?
```js
// Copyright 2021 D3LT4-Attack - https://github.com/XfedeX/D3LT4-Attack
options = {
connect: r => {
    socks.createConnection({
        proxy: {
            host: "ProxyHost",
            port: 1080,
            type: 5
        },
        command: "connect",
        destination: {
            host: "example.aternos.me",
            port: 25565
        }
    }, (o, t) => {
        o ? LOG(o) : (r.setSocket(t.socket), r.emit("connect"))
    })
},
username: "D3LT4-Attack"
})
```

**Comment by U5B** [comment]
This may help you.
https://github.com/PrismarineJS/node-minecraft-protocol/blob/61789bbea9cbb8a746d0460c176067ff4076cfbb/src/client/tcp_dns.js#L21

You will have to resolve it yourself, get the results and pass them to the host and port of the destination.
