### ISSUE TITLE
Mineflayer AuthTitle error

### ISSUE THREAD

**Issue by pogchamppoly** [PrismarineJS/mineflayer#2306]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: Latest
 - server: vanilla/spigot/paper 1.17.1
 - node: 16.5.0

## Detailed description of a problem
When trying to login using the Microsoft authentication, I receive an error about an AuthTitle.

## What did you try yet?

Did you try any method from the API? Yes
Did you try any example? Any error from those? Yes

## Your current code
```js


    const bot = await createBot({
      host: interaction.options.getString("ip"),
      username: interaction.options.getString("email"),
      password: interaction.options.getString("password"),
      port: interaction.options.getInteger("port")
        ? interaction.options.getInteger("port")
        : 25565,
      version: interaction.options.getString("version")
        ? interaction.options.getString("version")
        : false,
      auth: interaction.options.getString("auth")
        ? interaction.options.getString("auth")
        : "mojang",
    

```

## Expected behavior
Shouldn't error and should log into the account provided.

**Comment by pogchampjacob** [comment]
![Screenshot_20211108-224341_Samsung Internet](https://user-images.githubusercontent.com/79588299/140831940-0f4d15db-3fb5-47e1-bf09-d06a2401efc3.jpg)

**Comment by extremeheat** [comment]
Looks like node-minecraft-protocol needs a release

**Comment by pogchampjacob** [comment]
> Looks like node-minecraft-protocol needs a release

Any idea how to fix?

**Comment by U5B** [comment]
You can add
`authTitle: Titles.MinecraftJava`
to the createBot options and add
`const { Titles } = require('prismarine-auth')`
as a temporary workaround

**Comment by pogchampjacob** [comment]
> You can add `authTitle: Titles.MinecraftJava` to the createBot options and add `const { Titles } = require('prismarine-auth')` to the top of the file as a temporary workaround

This returns error code 401 and saying its invalid credentials. Double checked credentials, works fine when logging in manually

**Comment by pogchampjacob** [comment]
![Uploading Screenshot_20211109-221233_Samsung Internet.jpg…]()

**Comment by pogchampjacob** [comment]
![Screenshot_20211109-221233_Samsung Internet](https://user-images.githubusercontent.com/79588299/141013447-f292b935-1dae-48c0-890f-84301053890f.jpg)

**Comment by U5B** [comment]
Try replacing Titles.MinecraftJava with `00000000402b5328`

**Comment by pogchampjacob** [comment]
> Try replacing Titles.MinecraftJava with `00000000402b5328`

Same error

**Comment by U5B** [comment]
Hmm... maybe that authTitle is blocked now

**Comment by pogchampjacob** [comment]
> Hmm... maybe that authTitle is blocked now
> 
> Try again in a few hours, you might be rate limited

I can change the node IP to see if its a rate limit

**Comment by pogchampjacob** [comment]
> > Hmm... maybe that authTitle is blocked now
> > Try again in a few hours, you might be rate limited
> 
> I can change the node IP to see if its a rate limit

Still an unauthorised 401

**Comment by U5B** [comment]
If you are using a passwordless authentication method for Microsoft, the password field needs to be removed I think.

**Comment by pogchampjacob** [comment]
> If you are using a passwordless authentication method for Microsoft, the password field needs to be removed I think.

Its an actual account with a Microsoft password

**Comment by U5B** [comment]
Could you still try without a password and following the instructions given?
https://github.com/PrismarineJS/mineflayer/issues/2307 says that you can auth with different methods once you are given a code.

**Comment by pogchampjacob** [comment]
> Could you still try without a password and following the instructions given? #2307 says that you can auth with different methods once you are given a code.
> 
> Extremeheat said
> 
> > Yeah, you auth in the browser yourself with a special code, then the program waits for the server to verify you signed in and continues with the auth sequence once it gets the confirmation. The way you auth is not relevant because that’s all done outside in a standard browser.
> 
> > First the program asks for an auth token from the server, we give that to you, you put that into Microsoft.com/link then we constantly poll the server for if the auth was completed. If it is the server gives us a session token which can be used to complete the auth sequence. Exactly how you authenticate is up to you in the browser. If you already signed in, you will probably just be able to click “Allow” after putting the code in.

This does work. Any way to grab the code from the message that it outputs?

**Comment by pogchampjacob** [comment]
![Screenshot_20211109-223419_Samsung Internet](https://user-images.githubusercontent.com/79588299/141016577-63a49521-56e1-48df-bcb8-2ec7519184eb.jpg)
Nevermind.

**Comment by U5B** [comment]
I got no idea then lol. Try it on your own PC instead of a VPS?

**Comment by pogchampjacob** [comment]
> I got no idea then lol. Try it on your own PC instead of a VPS?

Still errors annoyingly

**Comment by extremeheat** [comment]
can you try using the MinecraftNintendoSwitch auth title instead of the MinecraftJava one ?

**Comment by pogchampjacob** [comment]
> can you try using the MinecraftNintendoSwitch auth title instead of the MinecraftJava one ?

This works. Thank you so much!

**Comment by jpeterik12** [comment]
I was having the same issue, and got to the same point with the error

```
/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/common/Util.js:9
    throw Error(`${res.statusText}: ${resp}`)
          ^

Error: Forbidden: [object Object]
    at checkStatus (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/common/Util.js:9:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async XboxTokenManager.getTitleToken (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/TokenManagers/XboxTokenManager.js:248:17)
    at async retry.msa.forceRefresh (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:123:30)
    at async retry (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:22:14)
    at async MicrosoftAuthFlow.getXboxToken (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:117:14)
    at async retry.xbl.forceRefresh (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:144:22)
    at async retry (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:22:14)
    at async MicrosoftAuthFlow.getMinecraftJavaToken (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:143:7)
    at async Object.authenticate (/home/pi/Desktop/AFK/node_modules/minecraft-protocol/src/client/microsoftAuth.js:12:44)
    ```
    However trying to use MinecraftNintendoSwitch did not help.

**Comment by pogchampjacob** [comment]
> I was having the same issue, and got to the same point with the error
> 
> ```
> /home/pi/Desktop/AFK/node_modules/prismarine-auth/src/common/Util.js:9
>     throw Error(`${res.statusText}: ${resp}`)
>           ^
> 
> Error: Forbidden: [object Object]
>     at checkStatus (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/common/Util.js:9:11)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async XboxTokenManager.getTitleToken (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/TokenManagers/XboxTokenManager.js:248:17)
>     at async retry.msa.forceRefresh (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:123:30)
>     at async retry (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:22:14)
>     at async MicrosoftAuthFlow.getXboxToken (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:117:14)
>     at async retry.xbl.forceRefresh (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:144:22)
>     at async retry (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:22:14)
>     at async MicrosoftAuthFlow.getMinecraftJavaToken (/home/pi/Desktop/AFK/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:143:7)
>     at async Object.authenticate (/home/pi/Desktop/AFK/node_modules/minecraft-protocol/src/client/microsoftAuth.js:12:44)
> ```
> 
> However trying to use MinecraftNintendoSwitch did not help.

That is a bit strange. Could you send your code? Mine works perfectly fine with NintendoSwitch

**Comment by jpeterik12** [comment]
> That is a bit strange. Could you send your code? Mine works perfectly fine with NintendoSwitch

my editor had saved, but running it used the old file, so I thought it didn't work. I tried again and it worked.
