### ISSUE TITLE
Logging in with passwordless microsoft account

### ISSUE THREAD

**Issue by poggingfish** [PrismarineJS/mineflayer#2307]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - node: 6.14.12

## Detailed description of a problem
Microsoft allows you to have an account without a password and only a YubiKey/Security key+2fa on phone. Is there any way to sign in with this on mineflayer?

**Comment by extremeheat** [comment]
Do not specify the password field to do code based auth

**Comment by poggingfish** [comment]
> Do not specify the password field to do code based auth
But does this use yubikey or just device auth?

**Comment by extremeheat** [comment]
Yeah, you auth in the browser yourself with a special code, then the program waits for the server to verify you signed in and continues with the auth sequence once it gets the confirmation. The way you auth is not relevant because that’s all done outside in a standard browser.

**Comment by poggingfish** [comment]
Thanks alot!
