### ISSUE TITLE
placeBlock() issue without item in hand

### ISSUE THREAD

**Issue by n0rbyt3** [PrismarineJS/mineflayer#2320]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: vanilla 1.17.1
 - node: 16.13.0

## Detailed description of a problem
You cannot use ```bot.placeBlock()``` without item in your hand even if no item is required in latest protocol versions.

## What did you try yet?
I have dumped the place_block packets to see what is actually sent to the server. There is no item field, just the hand type, the location and a cursor field.

## Your current code
```js
const referenceBlock = bot.findBlock(...); // referenceBlock is not null
const faceVector = new Vec3(....);

console.log(bot.heldItem); // null
bot.placeBlock(referenceBlock, faceVector); // throws Error even if bot.heldItem is not required for protocol
```

## Expected behavior
No error, the place_block packet is sent to the server. The check should only be neccessary if an item is required by the feature.

## Additional context
I tried to set a fake item, but then I get a promise timeout after calling ```bot.placeBlock()```.

**Comment by IceTank** [comment]
What block can be placed without holding an item? Can you provide a more specific example?

**Comment by n0rbyt3** [comment]
Sure. I'm using a server-side mod that enables elevator signs. I can use it with the vanilla client without modifications by either left- or right-clicking on the sign which teleports me to a different location. You don't need any item in your hand for that.

**Comment by PondWader** [comment]
I believe the right click and place block packets are actually different, if no block is placed the client just sends a right click swing arm packet. 

You should be able to use https://mineflayer.prismarine.js.org/#/api?id=botswingarmhand-showhand for the right click packet. I think this is correct anyway, give it a try.

**Comment by n0rbyt3** [comment]
@PondWader I tried, but it has no effect. But you can reproduce the issue with vanilla methods:

1. Setup a local vanilla server (1.17)
2. Setup Pakkit or any other packet sniffer you like
3. Join the server and place a wall sign
4. Right click the sign and inspect the packet

You will notice a ```place_block``` packet sent without any item information.

**Comment by nickelpro** [comment]
@u9g Has strong feelings about this and has advocated for changing the name of these packets to "left click" and "right click" respectively. This is certainly a bug

**Comment by u9g** [comment]
> @u9g Has strong feelings about this and has advocated for changing the name of these packets to "left click" and "right click" respectively. This is certainly a bug

Yeah. the packet does more than place a block.

More to the point, what the main poster wants is to use activateBlock.

**Comment by IceTank** [comment]
> @u9g `bot.activateBlock` has hard-coded `hand: 0` and should be extended by an optional parameter `offHand` like other methods use. Then, the method would be exact the method I was looking for. :)

Placing blocks with your offhand is already a thing. Is it possible to activate a block with your offhand?

**Comment by n0rbyt3** [comment]
You can have a shovel in your offhand to place dirt pathes. Since the protocol allows it, the bot should be flexible enough to send this valid packet, too. However, activateBlock should be the way to go for me and everything else might be a new feature. That's why I'll close it now. Thanks for your help. :)
