### ISSUE TITLE
Error with microsoft auth

### ISSUE THREAD

**Issue by EndermanHackerVN** [PrismarineJS/mineflayer#2326]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: vanilla/spigot/paper 1.17.1
 - node: 16.13.0

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
When login with a microsoft account, it throws back this error
![image](https://user-images.githubusercontent.com/67498765/144425639-c7dd7534-ca07-436c-b34b-ac9c176952e3.png)

## What did you try yet?

Did you try any method from the API? Yes
Did you try any example? Any error from those? Yes

## Your current code
```
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'localhost', 
  username: 'email@example.com', 
  password: '12345678',
  port: 25565,                
  version: false,            
  auth: 'microsoft'       
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  console.log(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)
```

## Expected behavior
It should login.

**Comment by extremeheat** [comment]
Your account probably does not own Minecraft. Looks like Minecraft-protocol needs a release otherwise you would have gotten an error saying this

**Comment by EndermanHackerVN** [comment]
@extremeheat I have purchased minecraft
![image](https://user-images.githubusercontent.com/67498765/144541618-142abd83-90bb-4f94-926c-fbc73bc6c466.png)

**Comment by extremeheat** [comment]
The Microsoft account you used to sign in with does not own Minecraft

**Comment by EndermanHackerVN** [comment]
@extremeheat 

![image](https://user-images.githubusercontent.com/67498765/144541844-30e69308-115e-49ad-98d5-907d86a56bf7.png)


and the error throws randomly. Like 50/50 percent.

**Comment by extremeheat** [comment]
do `npm update` then if you get an error, set `process.env.DEBUG = 'minecraft-protocol'` at the top of your code and post the a link to the log

**Comment by Pix3lPirat3** [comment]
What I've noticed myself is the Microsoft authentication doesn't like the 'password' field, as it wants a verification code, so simply do not set the password field, and you should get an error code from [xboxlive-auth](https://github.com/XboxReplay/xboxlive-auth) along with a link to [Microsoft link](microsoft.com/link) and a short code to type.

This is what I've been using in my own program
```
    let bot = mineflayer.createBot({
      host: 'localhost',
      username: account.email,
      password: account.type == 'mojang' ? account.password : "", // Microsoft doesn't want a password, only verification code
      port: 25565,
      version: '1.8',
      auth: account.type,
      debug: true,
      verbose: true
    })
```

**Comment by rom1504** [comment]
looks solved
