### ISSUE TITLE
Support 1.18

### ISSUE THREAD

**Issue by crazywhalecc** [PrismarineJS/mineflayer#2329]

**Comment by u9g** [comment]
No need for luck, as soon as someone starts working on it, it’ll get done :)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-contribute#updating-to-new-minecraft-versions can help you make progress on this @crazywhalecc

**Comment by crazywhalecc** [comment]
I'll try it but my day job is busy, there is no guarantee that it can be done 😢

**Comment by kegri** [comment]
It has been 6 days, any updates on 1.18 support?

**Comment by extremeheat** [comment]
It's waiting for someone who wants it to work on it. If you're not sure how it's always a great time to learn, just look at how some of the previous updates were done. If that's not possible you can try and promote some progress by using the issue hunter bounties, I think it's a good motivator. Otherwise it's all dependent on someone with free time and in a good mood, which could be tomorrow or maybe next month :)

**Comment by rom1504** [comment]
related https://github.com/PrismarineJS/minecraft-data/issues/474

**Comment by SaubereSache** [comment]
Unable to fund, issuehunter is broken .-.

**Comment by DelanoLeslie** [comment]
Any updates? It looks like the issue hunter page for this issue is broken. :(

**Comment by crazywhalecc** [comment]
I feel that in the end, everyone is waiting for someone to update, but no one updates, except the maintainer.

**Comment by nickelpro** [comment]
I addressed this two weeks ago, we're finishing our finals, and we even made progress on it already (NMP supports 1.18). I did very OK on Linear Algebra, thanks for asking.

**Comment by rom1504** [comment]
Regarding issue hunt, yes it's broken. Feel free to contact them, I tried without success
Does anyone have suggestions for an alternative?

**Comment by nickelpro** [comment]
If it's literally just this issue we could simply move the discussion to a new one for the purpose of linking to issue hunt. It's not like this issue has collected a lot of useful discussion.

**Comment by rom1504** [comment]
Hmm yeah indeed it seems it's not all issues and maybe only a few 
However not sure if I want to keep trusting people money to this platform if they can't fix this or at least answer to support requests.

**Comment by DelanoLeslie** [comment]
> I addressed this two weeks ago, we're finishing our finals, and we even made progress on it already (NMP supports 1.18). I did very OK on Linear Algebra, thanks for asking.

Sorry hadn't realized! I was asking as a general question for anyone. :( I am trying to figure out how to contribute, but I cant piece together what specifically needs to be updated or how. Like for instance in pchunk, it says it need a update. As to what need to be changed, I can't figure it out. There is a lot of things that happen that reference each other over multiple repositories. So trying to piece together what something does, and what need to be changed to make it work, or why it doesn't work is hard. I don't mean to be unsympathetic, it was more geared to ask anyone where we are currently with a little more specificity.

**Comment by tippf3hlr** [comment]
I don't know by any means if I executed things correctly, but according to https://github.com/PrismarineJS/prismarine-contribute#updating-to-new-minecraft-versions you first have to update [PrismarineJS/minecraft-data](https://github.com/PrismarineJS/minecraft-data), and in https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md I found a list that need to be done. I was trying to execute the first one and I think you have to use the [version history](https://wiki.vg/index.php?title=Protocol&action=history) of https://wiki.vg/Protocol to update the last already existing JSON file.
My fork: [tippf3hlr/minecraft-data/data/pc/1.18/protocol.json](https://github.com/tippf3hlr/minecraft-data/blob/master/data/pc/1.18/protocol.json) but I changed one or two things so nothing that matters.

Would be nice to hear if this is correct.

Btw always nice to use a file diff tool

**Comment by tippf3hlr** [comment]
just realised minecraft-data is already updated nice

**Comment by rom1504** [comment]
the protocol file in mcdata is already updated indeed
the next step there would be to add the blocks, items,.. data
using https://github.com/PrismarineJS/minecraft-jar-extractor

feel free to join our discord (in particular #contributor room) for more step by step guidance

**Comment by tippf3hlr** [comment]
> the next step there would be to add the blocks, items,.. data

In dataPaths.json everything except protocol.json is referenced to 1.17.1 and below and README is already updated with 1.18.
would the next step be updating node-minecraft-protocol -> mineflayer?

**Comment by tippf3hlr** [comment]
https://github.com/PrismarineJS/mineflayer/pull/2339

**Comment by rom1504** [comment]
> In dataPaths.json everything except protocol.json is referenced to 1.17.1 and below

Yes, so it's not updated

**Comment by rom1504** [comment]
We now have most of the data for 1.18

**Comment by rom1504** [comment]
Next step is chunk dumper + pchunk
https://github.com/PrismarineJS/minecraft-chunk-dumper/pull/24

**Comment by mvnd06** [comment]
Thanks a ton for maintaining this project! Do you have an estimate when 1.18 support will be available?

**Comment by nickelpro** [comment]
No, and for future reference we never provide ETAs. Up-to-date information about current work can be found in #contribute of the Discord if you want to help though.

**Comment by nickelpro** [comment]
Work on pris-chunk is in progress
https://github.com/PrismarineJS/prismarine-chunk/pull/150

For those following the saga, I passed Differential Equations & Linear Algebra with a C+

**Comment by nickelpro** [comment]
1.18 pchunk is at review.

Big question right now is what to do about biome support. Biomes are effectively broken on any non-vanilla server due to Biome data becoming fully dynamic, principally since the introduction of the LoginData packet but very really in 1.18. The good news is no one really cares, as biome support is barely used by anyone, the bad news is if we ship with it broken it will likely stay broken.

**Comment by rom1504** [comment]
the next step is getting materials.json in minecraft data for 1.18

**Comment by rom1504** [comment]
<a href="https://rysolv.com/issues/detail/6aa8b199-8c9f-4660-a1cd-927d7238dc05"><img width="200px" src="https://rysolv.s3.us-east-2.amazonaws.com/FundingButton.png"></a>

**Comment by SaubereSache** [comment]
Whoever does the works, well deserved :)

**Comment by rom1504** [comment]
now done
thanks to
* @nickelpro  (https://github.com/PrismarineJS/prismarine-chunk/pull/150)
* @extremeheat (https://github.com/PrismarineJS/prismarine-block/pull/45)
* myself (https://github.com/PrismarineJS/mineflayer/pull/2339)
