### ISSUE TITLE
Microsoft GamePass Accounts are not working

### ISSUE THREAD

**Issue by Rococoly** [PrismarineJS/mineflayer#2333]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: vanilla/spigot/paper 1.8.9
 - node: 16.13.1

## Detailed description of a problem
When I try to log a Minecraft Microsoft GamePass account it says that the account doesn't own Minecraft but it owns it.

## What did you try yet?
I tried with a non-gamepass account that has Minecraft and it's working but with a Microsoft gamepass account that has Minecraft it doesn't work.

Did you try any method from the API? Yes
Did you try any example? Any error from those? Yes

## Screenshot of the error
![image](https://user-images.githubusercontent.com/65961342/144695980-e81b48ec-6e4b-4914-865b-109f501d02df.png)

## Expected behavior
I expect the bot to log in a server with the Microsoft GamePass account.

**Comment by extremeheat** [comment]
put `process.env.DEBUG = 'minecraft-protocol'` at the top of your code, run it again and post the a link to the log after you get the error

**Comment by Rococoly** [comment]
> put `process.env.DEBUG = 'minecraft-protocol'` at the top of your code, run it again and post the a link to the log after you get the error

![image](https://user-images.githubusercontent.com/95515005/144720285-bf9ac9d6-f567-4af4-b594-e4b051bb6a63.png)

**Comment by Rococoly** [comment]
> put `process.env.DEBUG = 'minecraft-protocol'` at the top of your code, run it again and post the a link to the log after you get the error

![image](https://user-images.githubusercontent.com/95515005/144720604-e84186f6-1a1c-49be-b73c-ddd81201bad1.png)



![image](https://user-images.githubusercontent.com/95515005/144720437-67781c52-f658-4b25-a787-bcf6de57b39a.png)

**Comment by extremeheat** [comment]
Looks like a bug, the entitlement check should be completely removed

**Comment by Rococoly** [comment]
> Looks like a bug, the entitlement check should be completely removed

Thank you it's working now :)
