### ISSUE TITLE
bot.attack(target, swing=true) with iterations of bot.entities caused unknown error

### ISSUE THREAD

**Issue by AsherJingkongChen** [PrismarineJS/mineflayer#2334]
- [ ] The [issue#1245](https://github.com/PrismarineJS/mineflayer/issues/1245) seems to contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: __paper 1.17.1__ __(non-vanilla)__
 - node: v16

## Code preview
```javascript
//const bot = mineflayer.createBot({ ~ })
function hit(){
    var elist = ["witch", "vindicator", "vex", "pillager", "evoker"]
    for(var id in bot.entities){
        var target = bot.entities[id]
        if(target.type != 'mob') continue
        if(target.position.distanceTo(bot.entity.position.offset(0.5, 0.5, 0.5)) > 5) continue
        if(!elist.includes(target.name)) continue
        if(target.isValid && target.health !== 0) bot.attack(target)
    }
}
setInterval(()=>{
    hit()
},250)
```
  
## What did I try yet?

`mineflayer/plugins/entities.js` __`function attack(target, swing=true)`__
__`bot.entities`__

## Expected behavior
call `hit()` =>
  { check each entity in bot.entities and attack any checked entity }
sleep(250)
_(...behaving like multiAura in Wurst7?)_

## Problem
Working nice for a few minutes and suddenly kicked out by unknown reason.
[Video : Crashing moment](https://youtu.be/kYUYSVbnSl0)
[Video : It was idle for a moment and going on](https://youtu.be/IY_a52imwyg)
__It always ended without cautions or error messages.__

**Comment by amoraschi** [comment]
I think this can be avoided by awaiting bot.attack

**Comment by AsherJingkongChen** [comment]
@amoraschi How to asynchronize attack() ?

**Comment by amoraschi** [comment]
await bot.attack

**Comment by AsherJingkongChen** [comment]
[Crashing moment](https://youtu.be/kYUYSVbnSl0)
[It was idle for a moment and going on](https://youtu.be/IY_a52imwyg)

**Comment by aesthetic0001** [comment]
Can you add a `bot.on('error', console.log)` to your code?

**Comment by aesthetic0001** [comment]
Closeable?

**Comment by AsherJingkongChen** [comment]
@aesthetic0001 
At that time, I had found the error caused by bad network connection...
