### ISSUE TITLE
get player position in a while loop

### ISSUE THREAD

**Issue by mab-mab** [PrismarineJS/mineflayer#2341]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: vanilla 1.12.2 
 - node:  14.17.5

## Detailed description of a problem
Logging a players position in a while loop

## What did you try yet?

bot.on("physicsTick")
but it would listen forever

## Your current code
```js

function checkPlayer(name){
    let startTime = Date.now();
    while ((Date.now() - startTime) < 1000) {
       let playerFilter = (entity) => entity.type ==='player'
       let playerEntity = bot.nearestEntity(playerFilter)
        if (distanceVector(playerEntity,bot.entity.position) <=7){
         return true
        }

```

## Expected behavior
constantly updating the player position

**Comment by u9g** [comment]
can I ask why?

**Comment by WhoTho** [comment]
Your code only runs for 1 second after calling the function because of your while condition.

Try using setInterval(function, delay).

This will repeatedly call the function every "delay" ms.
```js
var closeToPlayer = false;

var checkPlayerLoop = setInterval(() => {
    let playerFilter = (entity) => entity.type ==='player'
    let playerEntity = bot.nearestEntity(playerFilter)
    if (distanceVector(playerEntity,bot.entity.position) <=7){
        closeToPlayer = true;
        clearInterval(checkPlayerLoop); // Stops the loop
    }
}, 1000);
```

**Comment by aes0002** [comment]
should be closed i think
