### ISSUE TITLE
Kicked from all servers

### ISSUE THREAD

**Issue by SnyGun** [PrismarineJS/mineflayer#2349]
- [ x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: spigot : 1.17.1 / 1.8.9
 - node: 16.13.0

## Detailed description of a problem
Same as issue https://github.com/PrismarineJS/mineflayer/issues/2209
My bot is disconnected after 10-15 seconds with error : ```{"text":"Internal Exception: io.netty.handler.timeout.ReadTimeoutException"} true```

## What did you try yet?
I have tried several different servers but the problem remains. When i was on my local spigot there is no problem, but when i try to connect on multiplayer server other than mine it disconnect my bot after 10-15 sec with this error.

I have aslo try to set ```checkTimeoutInterval``` to 5 min.

## Expected behavior
I hope that my bot can stay on the servers.

**Comment by amoraschi** [comment]
What's your code

**Comment by SnyGun** [comment]
> What's your code

```const bot = mineflayer.createBot({
  connect: (client) => {
    socks.createConnection({
      proxy: {
        host: "myproxyip",
        port: myproxyport,
        type: 5,
        userId: "myproxyid",
        password: "myproxypass"
      },
      command: 'connect',
      destination: {
        host: "adress2server",
        port: port2server,
      }
    }, (err, info) => {
      if (err) {
        console.log(err)
        return
      }
      client.setSocket(info.socket)
      client.emit('connect')
    })
  },
  username: 'myemail',
  password: 'mypass',
  version: "1.17.1",
  checkTimeoutInterval: 300*1000,
  auth: 'mojang'
});

bot.loadPlugin(armorManager);
bot.loadPlugin(autoeat);

let mcData;
bot.once('spawn', () => {
  mcData = require('minecraft-data')("1.17.1");
  bot.autoEat.options.priority = "foodPoints"
  bot.autoEat.options.bannedFood = []
  bot.autoEat.options.eatingTimeout = 3
});

bot.on("health", () => {
  if (bot.food === 20) bot.autoEat.disable();
  else bot.autoEat.enable();
})

function delay(delayInms) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(2);
    }, delayInms);
  });
}

bot.on('chat', (username, message) => {
  if(username === bot.username) return;
  console.log(message);
})

bot.once('login', async () => {
    console.log('connecté au serveur !');
    await delay(3000);
    bot.chat('/tpa SnyCorleone');
    await delay(3000);
    bot.armorManager.equipAll();
});

bot.on('kicked', console.log);
bot.on('error', console.log);```

**Comment by amoraschi** [comment]
Maybe the proxy is giving that?

**Comment by U5B** [comment]
Have you tested with a vanilla server? Some servers have anticheats that will kick the bot for not responding to specific packets.

**Comment by SnyGun** [comment]
> Maybe the proxy is giving that?

no i tried today and it's not my proxy

**Comment by SnyGun** [comment]
> Have you tested with a vanilla server? Some servers have anticheats that will kick the bot for not responding to specific packets.

i tested today on purpur 1.17.1 ( spigot fork ) and it don't disconnect my bot

**Comment by EndermanHackerVN** [comment]
@SnyGun hello, is the server you are trying to connect to use Vulcan anticheat? Your description seems the exact same as my issue in #2281 
> Reference: https://gist.github.com/freppp/6f669d666835011f3661025c2d9533e2 Line 157

Can you try @U5B's fork of mineflayer? PR #2217 
`npm i https://github.com/PrismarineJS/mineflayer#pull/2217/head`
