### ISSUE TITLE
Add ability to authenticate users before connecting them to the server

### ISSUE THREAD

**Issue by KlusterMonkey** [PrismarineJS/mineflayer#2356]
Would be very useful to be able to easily authenticate my bots before I connect them to the server I need them on. Also means if they disconnect I can easily reconnect them or even send them to another server without having to reauth every time, risking Mojang locking the account.

**Comment by O-of** [comment]
Pretty sure that mineflayer caches tokens, and even if it doesn't you can cache them yourself and use those tokens for your bots

**Comment by SaubereSache** [comment]
It caches tokens after first authentication

**Comment by Pix3lPirat3** [comment]
You can use [flying squid](https://github.com/PrismarineJS/flying-squid) to create a temporary server

```
const mcServer = require('flying-squid')
function startServer() {

  let server = mcServer.createMCServer({
    'motd': 'Authentication Server (Used by Program)',
    'port': 25570,
    'max-players': 100,
    'online-mode': true,
    'logging': true,
    'gameMode': 1,
    'difficulty': 0,
    'worldFolder':'world',
    'generation': {
      'name': 'superflat',
      'options': {
        'seed': '1234567890'
      }
    },
    'kickTimeout': 10000,
    'plugins': {

    },
    'modpe': false,
    'view-distance': 1,
    'player-list-text': {
      'header':'Temporary Server',
      'footer':'Authentication Server'
    },
    'everybody-op': true,
    'max-entities': 100,
    'version': '1.8'
  })

  server.on('error', function(err) { // Fires when there is an error.
    console.log('SERVER ERROR:', err)
  })

  server.on('clientError', function(client, err) { // Fires when client has an error.
    console.log('SERVER CLIENT ERROR:', client, err)
  })

  server.on('listening', function(port) { // Fires when the server is listening.
    console.log('The server is now listening on:', port)
  })

}
```

Then on the bot account(s) you can listen for the 'login' or 'spawn' event to verify that they've been authenticated. This is the system I'm using right now anyways, I'm not sure if there's a way to redirect the existing 'bot', of if I have to simply `mineflayer.createBot` once more, as mineflayer stores tokens and uses them automatically.

**Comment by u9g** [comment]
> You can use [flying squid](https://github.com/PrismarineJS/flying-squid) to create a temporary server
> 
> ```
> const mcServer = require('flying-squid')
> function startServer() {
> 
>   let server = mcServer.createMCServer({
>     'motd': 'Authentication Server (Used by Program)',
>     'port': 25570,
>     'max-players': 100,
>     'online-mode': true,
>     'logging': true,
>     'gameMode': 1,
>     'difficulty': 0,
>     'worldFolder':'world',
>     'generation': {
>       'name': 'superflat',
>       'options': {
>         'seed': '1234567890'
>       }
>     },
>     'kickTimeout': 10000,
>     'plugins': {
> 
>     },
>     'modpe': false,
>     'view-distance': 1,
>     'player-list-text': {
>       'header':'Temporary Server',
>       'footer':'Authentication Server'
>     },
>     'everybody-op': true,
>     'max-entities': 100,
>     'version': '1.8'
>   })
> 
>   server.on('error', function(err) { // Fires when there is an error.
>     console.log('SERVER ERROR:', err)
>   })
> 
>   server.on('clientError', function(client, err) { // Fires when client has an error.
>     console.log('SERVER CLIENT ERROR:', client, err)
>   })
> 
>   server.on('listening', function(port) { // Fires when the server is listening.
>     console.log('The server is now listening on:', port)
>   })
> 
> }
> ```
> 
> Then on the bot account(s) you can listen for the 'login' or 'spawn' event to verify that they've been authenticated. This is the system I'm using right now anyways, I'm not sure if there's a way to redirect the existing 'bot', of if I have to simply `mineflayer.createBot` once more, as mineflayer stores tokens and uses them automatically.

Mineflayer does store tokens and use them automatically, I’m unsure why a flyingsquid server would help in this situation?

**Comment by Pix3lPirat3** [comment]
The OP is wanting a way to authenticate the accounts before having them join a 'production' server, which the way I've been using is creating an empty localhost flying-squid server, so it's just a 'first-time-use' method of verifying the accounts are valid, then afterwards the tokens can be used to join other servers.

I may be explaining this badly, but it's the method I've been using, so it makes sense to me.

**Comment by rom1504** [comment]
looks solved to me
