### ISSUE TITLE
Bot#BlockAtEntityCursor doesn't exist

### ISSUE THREAD

**Issue by SaubereSache** [PrismarineJS/mineflayer#2359]
Is [Bot#BlockAtEntityCursor](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botblockatentitycursorentitybotentity-maxdistance256) still available elsewhere or was it removed entirely?

**Comment by rom1504** [comment]
It'll be available when a release will be done

**Comment by u9g** [comment]
It's back :)
