### ISSUE TITLE
A chat-only mineflayer API? (simplified bot)

### ISSUE THREAD

**Issue by EvModder** [PrismarineJS/mineflayer#2365]
## Feature description
Given that updating Mineflayer to new Minecraft versions (1.18 at the time of writing this) can take weeks to months, it would be super awesome for my case (and potentially many others) to have a "trimmed-down" version of Mineflayer that would require less (or no) effort to update support for new Minecraft versions.

Alternatively, we could look for ways to streamline the existing process to make it easier, but as far as I understand it right now, most of the Mineflayer update process is heavily involved around API features related to the reading or interacting with the bot's surrounding world.

For anyone looking to create just a simple chat bot, which only needs to process / send messages, I feel like it could maybe be done in a simplified mineflayer "core" package which would include the basic login/auth code logic.

This is just an idea to see how other people feel; I'm not expecting anything like this to happen in the near future :)

**Comment by rom1504** [comment]
It already exists, it's https://github.com/PrismarineJS/node-minecraft-protocol + https://github.com/PrismarineJS/prismarine-chat

**Comment by Pix3lPirat3** [comment]
Don't forget you've actually worked on this exact [example](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_chat/client_chat.js) yourself @rom1504 ;)

**Comment by nickelpro** [comment]
This issue would be better defined if there were a list of features that differentiate it from NMP (which does already support 1.18). Otherwise agree with Rom, this already exists
