### ISSUE TITLE
Bots don't deal full-charged damage when pvp-ing.

### ISSUE THREAD

**Issue by Hedgie1** [PrismarineJS/mineflayer#2371]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 6.14.15
 - server: paper 1.17.1
 - node: 14.18.1

## Detailed description of a problem
I am developing a bot with lot of functions, pvp too.
PVP was working great until I installed the new version of mineflayer because of the SkinsRestorer fix.

When I start PVP mode now, the bot will hit me but is dealing very low damage, because he doesn't do full-charged hit.

## Expected behavior
Bot should deal full-charged hits.

## Additional context
Sorry for my bad english :D

**Comment by rom1504** [comment]
Do you mean https://github.com/PrismarineJS/mineflayer/pull/2302 ?
Any idea @U5B ?

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/history.md among those recent changes I'd say
Fixed wrong arm swinging (@IceTank)
And
Send arm_animation before use_entity (@aesthetic0001)

Might be related with your issue

**Comment by nickelpro** [comment]
I don't think we ever accounted for charge damage on swinging

**Comment by Hedgie1** [comment]
I am using mineflayer-pvp plugin, it worked fine but after new mineflayer update it deals lower damage because the swing 
animation is called twice I think.

**Comment by U5B** [comment]
You should make sure that the item you are using is listed here and is the correct attack speed.
https://github.com/PrismarineJS/mineflayer-pvp/blob/c54135944268521c6dc76a92f1bf8c8be5ae7fc2/src/AttackSpeeds.json
I believe this issue should be moved to mineflayer-pvp.

**Comment by Hedgie1** [comment]
Yeah, it's correct. As I said before, it was working fine until new **mineflayer** update (not mineflayer-pvp).

I think it may be related to @rom1504 's comment. (Fixed wrong arm swinging / Send arm_animation before use_entity)

**Comment by Hedgie1** [comment]
The bug is caused by "Send arm_animation before use_entity" patch.

**Comment by rom1504** [comment]
ok so the next step would be identifying the right behavior for this, https://github.com/Heath123/pakkit can help

**Comment by rom1504** [comment]
Should be fixed now, try to update to 3.14.1

**Comment by aesthetic0001** [comment]
Should prob be closed
