### ISSUE TITLE
bot.players['playername'].entity returns null

### ISSUE THREAD

**Issue by EndermanHackerVN** [PrismarineJS/mineflayer#2389]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: lastest
 - server: vanilla/spigot/paper 1.18.1
 - node: 16.13.1

## Detailed description of a problem
bot.players['playername'].entity returns null no matter what.

## Your current code
```js
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
       host: 'ip',
       username: '', 
       hideErrors: false,
       viewDistance: 'far'
})
bot.on('spawn', () => {
	console.clear()
        console.log('Logged in!')
        console.log('Wait...')
        console.log(bot.players['Username'].entity)        
})
```

## Expected behavior
It should return location data, entity data etc.

**Comment by rom1504** [comment]
Wait longer

**Comment by EndermanHackerVN** [comment]
@rom1504 you need to wait how long? like 10 minutes?

**Comment by amoraschi** [comment]
> @rom1504 you need to wait how long? like 10 minutes?
> 

Few seconds, it might be also that the username is not correct

**Comment by u9g** [comment]
Okay, tested this locally and it works fine, reopen with more info if it's not fixed.

Here's the code I used that worked without waiting:
```js
bot.on('spawn', () => {
  console.clear()
  console.log('Logged in!')
  console.log('Wait...')
  console.log(bot.players[bot.username].entity)
})
```
