### ISSUE TITLE
Bot unsneaking on attack

### ISSUE THREAD

**Issue by Clashbestie** [PrismarineJS/mineflayer#2393]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.14.1
 - server: paper 1.17.1
 - node: 16.13.1

## Detailed description of a problem
using 
```js 
bot.attack(entity);
```
causes the bot to unsneak. 

## Expected behavior
The bot not unsneaking

## Additional context
This is because of useEntity in entities.js always setting 'sneaking' to false:
```js 
  function useEntity (target, leftClick, x, y, z) {
    if (x && y && z) {
      bot._client.write('use_entity', {
        target: target.id,
        mouse: leftClick,
        x,
        y,
        z,
        sneaking: false
      })
    } else {
      bot._client.write('use_entity', {
        target: target.id,
        mouse: leftClick,
        sneaking: false
      })
    }
  }
```
replacing 'sneaking: false' with
```js 
bot.getControlState('sneak')
```
fixes this.

**Comment by U5B** [comment]
PRs welcome

**Comment by safazi** [comment]
@rom1504 This can be closed
