### ISSUE TITLE
Wrong bot velocity displayed??

### ISSUE THREAD

**Issue by Creative-Difficulty** [PrismarineJS/mineflayer#2395]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
```js
function logvelo() {
console.log(bot.entity.velocity.y)
}

bot.on("physictick", logvelo)
```

## Expected behavior
The y velocity of the bot gets printed every tick

## Additional context
I always get something like -0.00123012388767 while the bot is standing still

**Comment by amoraschi** [comment]
Fill in the issue

**Comment by Creative-Difficulty** [comment]
yea

**Comment by U5B** [comment]
That is intentional. This is not a bug.
