### ISSUE TITLE
Kicked from the server when trying to connect via a socks5 proxy

### ISSUE THREAD

**Issue by RobinGood14** [PrismarineJS/mineflayer#2396]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.2
 - server: spigot 1.12.2
 - node: 14.15.5

## Detailed description of a problem
When I connect to a server like mc.servername.com:25565 without a proxy everything works fine. But as soon as I try to connect to this server through the socks5 proxy, the bot connects to the server, but it immediately kicks with the reason "Please use domain mc.servername.com instead of connecting via an IP address". But in Socks.createConnection I specify mc.servername.com, not an ip address, but that doesn't help.

## What did you try yet?
I tried a dozen working socks5 proxies, the connection occurs, but immediately kicks for the above reason.

## Your current code
My code is the usual mineflayer-protocol socks5 example:
```js

const mc = require('minecraft-protocol')
const socks = require('socks').SocksClient
const ProxyAgent = require('proxy-agent')

if (process.argv.length < 6 || process.argv.length > 8) {
    console.log('Usage : node client_socks_proxy.js <host> <port> <proxyHost> <proxyPort> [<name>] [<password>]')
    process.exit(1)
}

const proxyHost = process.argv[4]
const proxyPort = process.argv[5]

// This part tests the proxy
// You can comment out this part if you know what you are doing
require('http').get({
    method: 'GET',
    host: 'ifconfig.me',
    path: '/',
    agent: new ProxyAgent({ protocol: 'socks5:', host: proxyHost, port: proxyPort })
}, (res) => {
    if (res.statusCode === 200) {
        process.stdout.write('Proxy ok ip: ')
        res.pipe(process.stdout)
        res.on('close', () => {
            process.stdout.write('\nProxy Connection closed\n')
        })
    } else {
        throw Error('Proxy not working')
    }
})

const client = mc.createClient({
    connect: client => {
        socks.createConnection({
            proxy: {
                host: proxyHost,
                port: parseInt(proxyPort),
                type: 5
            },
            command: 'connect',
            destination: {
                host: process.argv[2],
                port: parseInt(process.argv[3])
            }
        }, (err, info) => {
            if (err) {
                console.log(err)
                return
            }

            client.setSocket(info.socket)
            client.emit('connect')
        })
    },
    agent: new ProxyAgent({ protocol: 'socks5:', host: proxyHost, port: proxyPort }),
    username: process.argv[6] ? process.argv[6] : 'echo',
    password: process.argv[7]
})

client.on('connect', function () {
    console.info('connected')
})
client.on('disconnect', function (packet) {
    console.log('disconnected: ' + packet.reason)
})
client.on('end', function () {
    console.log('Connection lost')
})
client.on('error', function (error) {
    console.log('Client Error', error)
})
client.on('kick_disconnect', (reason) => {
    console.log('Kicked for reason', reason)
})
client.on('chat', function (packet) {
    const jsonMsg = JSON.parse(packet.message)
    if (jsonMsg.translate === 'chat.type.announcement' || jsonMsg.translate === 'chat.type.text') {
        const username = jsonMsg.with[0].text
        const msg = jsonMsg.with[1]
        if (username === client.username) return
        client.write('chat', { message: msg })
    }
})


```

## Expected behavior
Connection to the server domain even through a socks5 proxy. This is what mineflayer does without a proxy.

## Additional context
The server I'm trying to connect to: cheatmine.ru:25565

**Comment by IceTank** [comment]
Some servers check some packets that contain the host name the client used to connect to the server. Mineflayer does not set those values correctly when you use a custom connect function. Add `host` to the createBot options with the host of the server you are trying to connect to. If that does not work try adding `fakeHost` to the createBot options. See here for the option underlying protocol documentation used by mineflayer when connecting: https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/API.md#mccreateclientoptions
