### ISSUE TITLE
async functions don't work for python example.

### ISSUE THREAD

**Issue by ethanperrine** [PrismarineJS/mineflayer#2403]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?
Multiple from file, but in python. 

## What did you try yet?

Did you try any method from the API?
Yes
Did you try any example? Any error from those?
There aren't any examples on async 

## Your current code
``py

/*
from javascript import require, On, Once, AsyncTask, once, off
import time
import easygui
import threading

mineflayer = require('mineflayer')
pathfinder = require('mineflayer-pathfinder')
f = open(easygui.fileopenbox(title="Accounts")).readlines()

# MCname = input("Please type your username here: ")

async def main():
    await makebot()

async def makebot():
    for line in f:
        line = line.split(":")
        _u = line[0].strip()
        _p = line[1].strip()

        try:
            bot = mineflayer.createBot({
                'host': '<server ip>',
                'port': 25565,  # 25565 is default mc port
                'auth': 'mojang',
                'username': _u,
                'password': _p
            })
        except Exception as e:
            print(e)

    @On(bot, "error")
    def spawn(error):
        print(error)
*/

```

## Expected behavior
Multiple accounts from file is supposed to join the server. 

## Additional context
Add any other context about the problem here.

**Comment by extremeheat** [comment]
Not enough information here. What's not working/what's the error?

If you're in Google Colab to use async [you may need `nest_asyncio`](https://stackoverflow.com/questions/64074295/is-there-an-equivalence-of-await-in-google-colab). 

If you want to use threading instead JSPyBridge exports some threading wrappers as `AsyncTask` which you can look at.

![image](https://user-images.githubusercontent.com/13713600/149249291-ac10f058-a448-4fd1-a204-56fa06dc5e46.png)

Your main() function is not being run in the snippet you posted above, so yes nothing will happen.
