### ISSUE TITLE
bot.inventory.items() return nothing

### ISSUE THREAD

**Issue by TheDeadScythe** [PrismarineJS/mineflayer#2404]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.14.1
 - server: vanilla 1.17 (localhost)
 - node: 16.13.0

## Detailed description of a problem
bot.inventory.items() return nothing

## What did you try yet?

iI tried with mineflayer-web-inventory and he say hi have nothing in my inventory

## Your current code
```js


         items = bot.inventory.items()
        const output = items.map(itemToString).join(', ')
        console.log(output)
        Say(output)
```
or

```js

function itemToString (item) {
  if (item) {
    return `${item.name} x ${item.count}`
  } else {
    return '(nothing)'
  }
}

function sayItems (items = bot.inventory.items()) {
    const output = items.map(itemToString).join(', ')
    if (output) {
      Say(output)
    } else {
      Say('empty')
    }
  }
```

he return nothin

**Comment by amoraschi** [comment]
Maybe you have nothing in your inventory

**Comment by TheDeadScythe** [comment]
> Maybe you have nothing in your inventory

No i have full inventory

**Comment by amoraschi** [comment]
By "I", you mean the bot right?

**Comment by TheDeadScythe** [comment]
> By "I", you mean the bot right?

Yes sure

**Comment by amoraschi** [comment]
Btw what's your Say function

**Comment by TheDeadScythe** [comment]
> Btw what's your Say function

` js
function Say(argument) {
	var ply = new String(config.wisper)
	bot.chat(ply + argument)
}
`

**Comment by TheDeadScythe** [comment]
when my game running on 1.16.5 his working

**Comment by rom1504** [comment]
function sayItems (items = bot.inventory.items()) 

That's your bug

The default value will be defined when the function is first defined which is too early
