### ISSUE TITLE
Item's with large amount of NBT crashes client

### ISSUE THREAD

**Issue by DADpea** [PrismarineJS/mineflayer#2408]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.14.1
 - node: 15.6.0

## Detailed description of a problem
I'm trying to build a item grabber, but items with a lot of NBT crashes the bot. I do have the NBT in a file, it is massive.

[nbt.txt](https://github.com/PrismarineJS/mineflayer/files/7877528/nbt.txt)

## What did you try yet?
I found that just a person holding said item near the bot, (or bot holding the item), crashes the bot.

This is the only error I was able to get:
```error Deserialization error for play.toClient : Read error for undefined : The value of "offset" is out of range. It must be >= 0 and <= 49244. Received -16758```

## Expected behavior
Item's with large amount of NBT should be handled correctly.

**Comment by nickelpro** [comment]
Huge amounts of NBT crash the vanilla client to, it's a limitation of the protocol. Does this item work with the Notchian client?

**Comment by DADpea** [comment]
> Huge amounts of NBT crash the vanilla client to, it's a limitation of the protocol. Does this item work with the Notchian client?

The NBT that I was using never crashed my client (though it could be memory atlas). I tried looking around for Notchian cleint white writing this, wasn't able to find anything *good*, have somewhere to point me?

**Comment by U5B** [comment]
Notchian client is the vanilla client. Nickel is asking does this crash the vanilla client?

**Comment by DADpea** [comment]
> Notchian client is the vanilla client. Nickel is asking does this crash the vanilla client?

Oh, sorry just new to this, in my reply I said it never crashed my client, I also never got an error from my client when loading in the item.

**Comment by nickelpro** [comment]
Then it's something we're doing wrong with either protodef or pris-nbt

**Comment by u9g** [comment]
can you make a world dump or something so we can reproduce this?

**Comment by DADpea** [comment]
> can you make a world dump or something so we can reproduce this?
[nbt test.zip](https://github.com/PrismarineJS/mineflayer/files/7899973/nbt.test.zip)
Chest containing the item is in the center of the village.

**Comment by UMRnInside** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/974
This could be a prismarine-nbt bug.

btw `(uint16_t)((int16_t)-16758)` is `48778`, which fits in the range [0, 49244]
