### ISSUE TITLE
Cannot join any server

### ISSUE THREAD

**Issue by EnderHacker0** [PrismarineJS/mineflayer#2415]
my bot cant join any server
`const mineflayer = require('mineflayer')`
`function createBot () {`
`    const bot = mineflayer.createBot({`
`        host: '2b2t.com',`
`        port: 25565,`
`        username: '',`
`        password: '',`
`        auth: 'microsoft'`
`    })    `
`    bot.on('end', function() {`
`        console.log("Bot has ended");`
`        createBot()`
`    });`
`}`
`createBot()`

**Comment by amoraschi** [comment]
Can you add a kicked and error listener, this discussion lacks information

**Comment by EnderHacker0** [comment]
it cant login

**Comment by Pan4ur** [comment]
```const mineflayer = require('mineflayer')
function createBot () {
    const bot = mineflayer.createBot({
        host: '2b2t.dev',
        port: 25565,
        username: '',
        password: '',
        auth: 'microsoft'
    })
    bot.on('end', function() {
        console.log("Bot has ended");
        createBot()
    });
}
createBot()

**Comment by EnderHacker0** [comment]
i tried other servers but it still cant join. it cant login to my microsoft account

**Comment by Pan4ur** [comment]
To other anarchy servers? maybe it's because of the queue

**Comment by EnderHacker0** [comment]
i have a server with no queue and it still cant join

**Comment by EnderHacker0** [comment]
what is 2b2t.dev

**Comment by Pan4ur** [comment]
Server with anti-cheat like on 2b2t for testing bots, clients etc

**Comment by EnderHacker0** [comment]
it cant join any server

**Comment by pintermor9** [comment]
Isnt 2b2t's ip 2b2r.org?

**Comment by EnderHacker0** [comment]
2b2t.com no queue

**Comment by rom1504** [comment]
provide information (error, what server etc) if you want an answer

**Comment by EnderHacker0** [comment]
it shows no error

**Comment by amoraschi** [comment]
> Can you add a kicked and error listener, this discussion lacks information

.

**Comment by rom1504** [comment]
Open a new issue if you have information
