### ISSUE TITLE
Session ID login?

### ISSUE THREAD

**Issue by SamIsOnMC** [PrismarineJS/mineflayer#2417]
## Is your feature request related to a problem? Please describe.
Not really, the feature request would be useful to me tho.

## Describe the solution you'd like
An way of logging in with a Session ID with mineflayer

**Comment by rom1504** [comment]
What are you trying to do ?

Mineflayer does caching of auth tokens already

**Comment by SamIsOnMC** [comment]
> What are you trying to do ?
> 
> Mineflayer does caching of auth tokens already

Session IDs are temporary authentication tokens for logging onto servers with your minecraft account. In some mods it can be used to login, it would be useful if i could use mineflayer with Session IDs

**Comment by aes0002** [comment]
you can use `session` when calling createBot
[example here](https://github.com/PrismarineJS/mineflayer/blob/a0befeb042fe3851ac35887da116c2910f505791/examples/session.js)

**Comment by aesthetic0001** [comment]
Should be closed I think
