### ISSUE TITLE
Unicode Characters don't display correctly.

### ISSUE THREAD

**Issue by adiee5** [PrismarineJS/mineflayer#2422]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: ~~if is is version of mc, then 1.17.1, is there any other version?~~ 3.15.0
 - server: vanilla 1.17.1
 - node: 16.13.2

## Detailed description of a problem
I wanted to print text to the chat in polish language. Sadly diacritic letters display as question marks.

## What did you try yet?
i tried to print the message and find the anwser.

## Your current code
```js

const mineflayer = require('mineflayer')
const vec3 = require('vec3')

const bot = mineflayer.createBot({
    host: 'Server.IP',
    //port: parseInt(process.argv[3]),
    username: /*process.argv[4] ? process.argv[4] :*/ 'Szatanica',
    //password: process.argv[5]
})

bot.on("death", async () => {
    bot.chat("KURWA !!!!!!!! Kurwaaaaaa !!!!!!!!! Co tam się dzieje!!!!! To jest kurwa „straż graniczna\" ????? „Straż\" ?????????? To są maszyny bez serca bez mózgu bez NICZEGO!!! Maszyny ślepo wykonujące rozkazy!!!!! Kurwa!!!!!! Jak tak można!!!!! Boli mnie serce boli mnie cała klatka piersiowa trzęsę się i ryczę!!!! Mordercy!!! Chcecie takiego rządu wciąż ????? Który zezwala na takie rzeczy wręcz rozkazuje tak się zachowywać ??????? Kurwaaaaaaaaa!!!!! I rząd, który zezwala na śmierć kobiet, zamiast na ich ratunek ???? Wszyscy wiecie co się wydarzyło i co się dzieje dookoła!!!")
})



```

## Expected behavior
Letters with diacritics should be displayed correctly

**Comment by u9g** [comment]
I assume by question marks you mean that you are printing to your terminal. In that case, I'd suggest looking into finding a terminal that supports more characters. Trying your code example prints correctly ingame, so this isn't a mineflayer issue.
![dnvbeku](https://user-images.githubusercontent.com/43508353/152686274-72622c44-59c6-4e53-b38c-7144efb9ecd4.png)

**Comment by U5B** [comment]
Prints properly for me, your terminal don't may not support those characters
I suggest trying a different font in your terminal

**Comment by adiee5** [comment]
not terminal........
