### ISSUE TITLE
[ Bug ] Water leads to a bad movement package

### ISSUE THREAD

**Issue by MicroCBer** [PrismarineJS/mineflayer#2423]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: paper 1.18.1
 - node: 16.13.2

## Detailed description of a problem
When the bot gets onto the water, it sends a bad movement package immediately.

## What did you try yet?

set `physics.gravity` to 0

## Your current code
```js

const mineflayer = require("mineflayer");
const mineflayerViewer = require("prismarine-viewer").mineflayer;
const { pathfinder, Movements } = require("mineflayer-pathfinder");
const { GoalNear } = require("mineflayer-pathfinder").goals;
const pvp = require('mineflayer-pvp').plugin

const bot = mineflayer.createBot({
  username: "TestBot",
  host: "sq.s1.vlssu.com",
  port: "42886",
});
bot.loadPlugin(pathfinder);
bot.loadPlugin(pvp);

function toArr(e){
    return [e.x,e.y,e.z]
}



bot.on("chat", async (username, message) => {
  if (message.startsWith("/register"))
    bot.chat(`/register xxxxx123 xxxxx123`);
  else if (message.startsWith("/login")){
    bot.chat(`/login xxxxx123`);
  }

  if(message.startsWith("BotTpa")){
    bot.chat(`/tpa ${username}`);
  }

});




bot.once("spawn", () => {
    bot.physics.gravity=0 
  mineflayerViewer(bot, { port: 3000 }); 
});
bot.on("move",console.log)
bot.on('kicked', console.log)
bot.on('error', console.log)


```

## Expected behavior
Not to send the bad package

## Additional context

Log:
```
Vec3 { x: -282.24961632730486, y: 59, z: 54.10260754988749 }
Vec3 { x: -282.24961632730486, y: 62, z: 54.10260754988749 }
Vec3 { x: -282.24961632730486, y: 62, z: 54.10260754988749 }
Vec3 { x: -282.24961632730486, y: NaN, z: 54.10260754988749 }
{"translate":"multiplayer.disconnect.invalid_player_movement"}
```

**Comment by MicroCBer** [comment]
Temporary solution:
change `node_modules\prismarine-physics\index.js` line 375
`if(!entity.isInWater && !entity.isInLava){` into `if(1){`

**Comment by nickelpro** [comment]
Should be opened on pris-physics, not a Mineflayer proper bug.

**Comment by dumbasPL** [comment]
Seems like this is caused by missing `proportionalLiquidGravity` for `1.18` in [features.json](https://github.com/PrismarineJS/prismarine-physics/blob/master/lib/features.json#L10)
After adding 1.18 the list of versions water starts to work normally.

**Comment by rom1504** [comment]
@dumbasPL can you npm update --depth 9999 and try again?

**Comment by MicroCBer** [comment]
Fixed. Thanks!
