### ISSUE TITLE
bot.dig not working

### ISSUE THREAD

**Issue by Tali13** [PrismarineJS/mineflayer#2425]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: lastest
 - server: custom fork
  - node: 17

```js

setTimeout(() => {
    bot.dig({
      block: bot.blockAtCursor
    })
   }, 1000);
 }
   
```

## Expected behavior
bot starting to mine 

## Additional context
it throw
```
await bot.lookAt(block.position.offset(0.5, 0.5, 0.5), forceLook)
                                        ^

TypeError: Cannot read properties of undefined (reading 'offset')
```

**Comment by amoraschi** [comment]
```js
setTimeout(async () => {
  const block = bot.blockAtCursor()
  if (block == null) return
  await bot.dig(block)
})
```

Consider reading the docs and learning JavaScript Promises

**Comment by Tali13** [comment]
> 

omg ty im new at js
