### ISSUE TITLE
Image from custom filled map

### ISSUE THREAD

**Issue by JIBSIL** [PrismarineJS/mineflayer#2442]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - server: vanilla/spigot/paper 1.17.1
 - node: 16.13.1

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

Building a map viewer that works with custom maps as a mineflayer plugin. Non-vanilla maps are not compatible

## What did you try yet?
Reading the image and mapping it to PNG colors

Did you try any example? Any error from those?

mineflayer-viewer doesn't show map item frames at all

## Your current code
```js

    bot._client.on('map', data => {
            console.log('Map received!')
            const size = 128;
            const image = PNGImage.createImage(size, size);

            console.log(`Map size is ${size}x${size}`)

            for (let x = 0; x < size; x++) {
                for (let z = 0; z < size; z++) {

                    const colorId = data[x + (z * size)];
                    image.setAt(x, z, getColor(colorId));

                }
            }

            image.writeImage(`${__dirname}/map${Math.floor(Math.random() * 100)}.png`, function(err) {
                if (err) throw err;
                console.log('Written to the file');
            });
        })


```

## Expected behavior
Maps to output to file
## Additional context
Maps are blank

**Comment by JIBSIL** [comment]
> Did you check out this plugin? Maybe it could help you
> 
> https://github.com/IceTank/mineflayer-item-map-downloader

Yep, it did not detect any map at all

**Comment by JIBSIL** [comment]
> Is this supposed to be a bug with mineflayer ?

It could be Mineflayer or node-minecraft-protocol, Mineflayer doesn't have any method to do it that I know of

**Comment by extremeheat** [comment]
> Did you check out this plugin? Maybe it could help you
> 
> https://github.com/IceTank/mineflayer-item-map-downloader

I think this could be put in an example. If this works then the maps are being serialized normally, there is no issue here beyond your code

**Comment by JIBSIL** [comment]
> > Did you check out this plugin? Maybe it could help you
> > https://github.com/IceTank/mineflayer-item-map-downloader
> 
> I think this could be put in an example. If this works then the maps are being serialized normally, there is no issue here beyond your code

I think it's something about how I parse images. How could I parse the image buffer that it feeds out

**Comment by u9g** [comment]
Seems answered, closing. Open with more info if there is still some discussion here.
