### ISSUE TITLE
Repl . js example not working

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/mineflayer#2444]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer:latest
 - server: paper #.#.#
 

## Detailed description of a problem
tried the repl.js example didnt work 

## What did you try yet?
your repl.js example
Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
```minecraftBot.on('login', () => {
    const r = repl.start('> ')
    r.context.bot = minecraftBot
  
    r.on('exit', () => {
      minecraftBot.end()
    })
  })

/*
Some code here, replace this
*/


```

## Expected behavior
it was expected to send messages ingame ( basically a interactive console _)

##Screen shot of the error
![image](https://user-images.githubusercontent.com/98881281/152136508-bdcb21e4-0ea6-4b2c-b4b0-4e7bcd34f201.png)
![image](https://user-images.githubusercontent.com/98881281/152136542-23b81607-0d29-438e-9df3-0a4f91290365.png)

**Comment by amoraschi** [comment]
That's not the full code

**Comment by AdiKanGaming** [comment]
yeah i know i just sent the main part of repl.js

**Comment by amoraschi** [comment]
We can't help you without your code

**Comment by IceTank** [comment]
It looks like repl is working just fine. It is not an issue with mineflayer that you do not know how to use repl.

**Comment by amoraschi** [comment]
No, it's an issue of lack of knowledge of JavaScript
