### ISSUE TITLE
 Internal Exception: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by EndermanHackerVN** [PrismarineJS/mineflayer#2445]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: lastest
 - server: vanilla/spigot/paper 1.18.1
 - node: lastest

## Detailed description of a problem
Connecting to some 1.18.1 server throws out 
`Internal Exception: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $`

## Your current code
```js
Default code on the example page
```

## Expected behavior
It should log in

## Additional context
Connect using version 1.17.1 throws out outdated client

**Comment by IceTank** [comment]
This looks like the server kicking the bot. You have to be more specific about what server you are trying to join, what software the server is running and what example you used.
