### ISSUE TITLE
Error codes attempting to run higher level script using mineflayer, may be related to mineflayer errors

### ISSUE THREAD

**Issue by lachyharris** [PrismarineJS/mineflayer#2471]
Hey, having some error codes hitting me, wondering if you can read and tell me whats going on with it? Error codes attached below

I am on minecraft 1.18.1 and using urFafe/Afk/bot 

It is supposed to log in and take me to a set x, y, z. but seems to get these error codes when i am in water (may just be coincidental)
First code: 
at checkStatus (C:\Users\harri\afk_bot\node_modules\minecraft-protocol\src\client\microsoftAuth.js:125:11)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Object.authenticatePassword (C:\Users\harri\afk_bot\node_modules\minecraft-protocol\src\client\microsoftAuth.js:81:34)
[ERROR] Too Many Requests

This pops up a few times until it eventually says it’s tried too many times.

Okay and here is the second error code which has popped up:

Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' } [ERROR] read ECONNRESET
and
Error: write ECONNRESET at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at Framer.ondata (C:\Users\harri\afk_bot\node_modules\readable-stream\lib_stream_readable.js:681:20) at Framer.emit (events.js:315:20) at addChunk (C:\Users\harri\afk_bot\node_modules\readable-stream\lib_stream_readable.js:298:12) at readableAddChunk (C:\Users\harri\afk_bot\node_modules\readable-stream\lib_stream_readable.js:280:11) { errno: -4077, code: 'ECONNRESET', syscall: 'write' } [ERROR] write ECONNRESET

I attempted to have a look at this code to zero succEss. Have been told it’s likely a minecraft-protocol error or mineflayer.

**Comment by lachyharris** [comment]
Here is link to repo:

https://github.com/urFate/Afk-Bot

**Comment by Kashalls** [comment]
> Hey, having some error codes hitting me, wondering if you can read and tell me whats going on with it? Error codes attached below
> 
> I am on minecraft 1.18.1 and using urFafe/Afk/bot
> 
> It is supposed to log in and take me to a set x, y, z. but seems to get these error codes when i am in water (may just be coincidental) First code: at checkStatus (C:\Users\harri\afk_bot\node_modules\minecraft-protocol\src\client\microsoftAuth.js:125:11) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:93:5) at async Object.authenticatePassword (C:\Users\harri\afk_bot\node_modules\minecraft-protocol\src\client\microsoftAuth.js:81:34) [ERROR] Too Many Requests
> 
> This pops up a few times until it eventually says it’s tried too many times.
> 
> Okay and here is the second error code which has popped up:
> 
> Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' } [ERROR] read ECONNRESET and Error: write ECONNRESET at afterWriteDispatched (internal/stream_base_commons.js:156:25) at writeGeneric (internal/stream_base_commons.js:147:3) at Socket._writeGeneric (net.js:785:11) at Socket._write (net.js:797:8) at writeOrBuffer (internal/streams/writable.js:358:12) at Socket.Writable.write (internal/streams/writable.js:303:10) at Framer.ondata (C:\Users\harri\afk_bot\node_modules\readable-stream\lib_stream_readable.js:681:20) at Framer.emit (events.js:315:20) at addChunk (C:\Users\harri\afk_bot\node_modules\readable-stream\lib_stream_readable.js:298:12) at readableAddChunk (C:\Users\harri\afk_bot\node_modules\readable-stream\lib_stream_readable.js:280:11) { errno: -4077, code: 'ECONNRESET', syscall: 'write' } [ERROR] write ECONNRESET
> 
> I attempted to have a look at this code to zero succEss. Have been told it’s likely a minecraft-protocol error or mineflayer.

Looks like you got yourself rate limited by Microsoft. I suggest lowering the amount of (un)successful login attempts. Try updating to the latest version of mineflayer and its dependencies so you can roll with the latest features.

**Comment by extremeheat** [comment]
Remove the password field from your createBot options so code/token-based auth will be done. This will mean you don't need to authenticate every time signing in as caching is done, and by extension will cause less rate limit problems.
