### ISSUE TITLE
bot.clickWindow promise never gets resolved

### ISSUE THREAD

**Issue by Oreoezi** [PrismarineJS/mineflayer#2476]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.18.0
 - server: hypixel 1.8.9
 - node: 16.13.2

## Detailed description of a problem

`await bot.clickWindow` hangs. Possibly hypixel sends incorrect packets. 

## Your current code
```js
await bot.clickWindow(33, 0, 0);
await bot.clickWindow(31, 0, 0);
```

## Expected behavior
Slots 33 and 31 getting clicked and the script continuing as normal.

## Additional context
Without awaiting you are clicking too fast allowing only the first one to register so I had to make a promise
 ```js
await new Promise((res,rej) => setTimeout(res, 500));
``` 

which would be inconsistent on a laggy connection.

**Comment by autowert66** [comment]
This is perhaps because a server plugin does not send the chest-confirmation. 
Take a look at [this example](https://github.com/PrismarineJS/mineflayer/blob/master/examples/advanced/chest_confirm.md).

**Comment by Oreoezi** [comment]
Thank you
