### ISSUE TITLE
Patterns added using bot.addChatPattern() cannot emit "whisper" event

### ISSUE THREAD

**Issue by UMRnInside** [PrismarineJS/mineflayer#2478]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.18.0
 - server: Spigot server, with custom whisper format
 - node: 16.13.2

## Detailed description of a problem
I was trying to add a pattern to parse whisper messages, using `bot.addChatPattern()`
Whisper messages looks like `[私聊]<SomePlayer> Some message` ("私聊" means "whisper")
Someone whispered to the bot, `chat:whisper` event was emitted, but `whisper` event wasn't.

## What did you try yet?
* `bot.addChatPattern()`
* Handling `chat:whisper` event. However, `whisper` event should be emitted IMO.
* I did not try ``bot.chatAddPattern()``, as it's deprcated.

## Your current code
```js
const mineflayer = require('mineflayer');
const bot = mineflayer.createBot();
bot.once('login', () => {
    bot.addChatPattern('whisper', RegExp("^\\[私聊\\]<(.*?)> (.*)$"), {parse: true});
});
bot.on('whisper', (username, message) => {
    console.log("(whisper)", username, message);
});
bot.on('chat:whisper', (username, message) => {
    console.log("(chat:whisper)", username, message);
});
bot.on("messagestr", (msgstr, _1, _2) => {
    console.log("MsgStr", msgstr);
});

```

## Expected behavior
`whisper` event is emitted (instead of `chat:whisper`) when someone whispered to the bot.

## Additional context
"whisper" event is NOT deprcated in [docs/api.md](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#whisper-username-message-translate-jsonmsg-matches)

**Comment by amoraschi** [comment]
Whisper event probably only supports vanilla whispers

**Comment by u9g** [comment]
Solved above by U5B :)
