### ISSUE TITLE
Boatfly is it possible?

### ISSUE THREAD

**Issue by MiClobiMC** [PrismarineJS/mineflayer#2480]
It is possible to make our bot fly with a boat and make routes automatically or that we indicate some coordinates and go to that place

**Comment by amoraschi** [comment]
It could be possible, but boat movement isn't implemented, and much less a pathfinding system for boats

**Comment by IceTank** [comment]
Mineflayer does not support hacks. So boat fly won't be implemented in mineflayer. 

Is it possible for the bot to boat fly? Yes. Anything any other minecraft client can do can also be done with mineflayer as soon as someone implements the same code in mineflayer used by other minecraft clients.

**Comment by aesthetic0001** [comment]
closeable?

**Comment by MiClobiMC** [comment]
> Mineflayer does not support hacks. So boat fly won't be implemented in mineflayer.
> 
> Is it possible for the bot to boat fly? Yes. Anything any other minecraft client can do can also be done with mineflayer as soon as someone implements the same code in mineflayer used by other minecraft clients.

But what advantage does that give? what you say doesn't make sense

**Comment by U5B** [comment]
Boatfly gives an advantage over vanilla players. Mineflayer tries to be as vanilla as possible.

So Mineflayer will not implement boat-flying.
However, as IceTank said, you can replicate the code in hacked clients to create boatfly if you choose to do so.

So yes, boatfly is possible.
No, we are not going to make boatfly for you.

**Comment by MiClobiMC** [comment]
> Boatfly gives an advantage over vanilla players. Mineflayer tries to be as vanilla as possible.
> 
> So Mineflayer will not implement boat-flying. However, as IceTank said, you can replicate the code in hacked clients to create boatfly if you choose to do so.
> 
> So yes, boatfly is possible. No, we are not going to make boatfly for you.

In which part does it say that it does not support mineflayer hacks I have reviewed the official page and it does not say anything

**Comment by amoraschi** [comment]
He meant that they won't implement or accept PRs that add hacks

**Comment by IceTank** [comment]
> In which part does it say that it does not support mineflayer hacks I have reviewed the official page and it does not say anything

This is more off an opinion between most maintainers as most maintainers do not engage in minecraft hacking. If mineflayer added specific hacks to mineflayer maintainers would also have to maintain those hacks. If we start implementing hacks people will ask for other hacks to be implemented too. And there are a lot more important features to be implemented then some specific boat fly hacks that only works in specific versions. Mineflayer itself will probably never implement hacks by itself. But this dose not mean you cannot hack with mineflayer. The plugin system is very powerful and can provide you with everything you would ever need to write any behavior you every want with a mineflayer bot. And if you find something you cannot do with the standard mineflayer api you can submit changes to the api to add specific features you need.

**Comment by autowert66** [comment]
As stated in the comments above, mineflayer won't officially implement BoatFly. 

However, you could create a BoatFly Plugin by yourself.

If you want to do so, a good place to get started is the [AFK-Plugin example](https://github.com/PrismarineJS/mineflayer/blob/master/examples/plugins/afk.js).

Then you probably need to rewrite the source code of any BoatFly mod for mineflayer.
Otherwise, you could try to use a packet monitor like [pakkit](https://github.com/Heath123/pakkit) and try to implement BoatFly on a packet level (using `bot._client.write`).

**Comment by Sunderw3k** [comment]
doesnt bot.attack pretty much have killaura tho?
