### ISSUE TITLE
I don't understand how to start the bot

### ISSUE THREAD

**Issue by 7Zix7** [PrismarineJS/mineflayer#2486]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - server: vanilla 1.12.2

## Detailed description of a problem
I'm just trying to run a bot. I downloaded the code from one of the tutorials, watched 3 tutorials from different people and still don't understand the basics. Exactly how this folder works, how to link it, and so on.

## Your current code
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'localhost',
  port: 59262,
  username: 'lookAt_Bot'
})

function lookAtNearestPlayer () {
  const playerFilter = (entity) => entity.type === 'player'
  const playerEntity = bot.nearestEntity(playerFilter)
  
  if (!playerEntity) return
  
  const pos = playerEntity.position.offset(0, playerEntity.height, 0)
  bot.lookAt(pos)
}

bot.on('physicTick', lookAtNearestPlayer)

## Expected behavior
Запуск бота.

## Additional context
Я установил node js и visual studio code.

**Comment by 7Zix7** [comment]
I understand basic programming -_-
Apparently the translator misunderstood my question. I do not understand what needs to be done ri
ght at the very beginning. I have the downloaded code, I make the server open to the network, give the bot the right port and run it as it says in the tutorials. But it leads to absolutely nothing

**Comment by 7Zix7** [comment]
I understand basic programming -_-
Apparently the translator misunderstood my question. I do not understand what needs to be done right at the very beginning. I have the downloaded code, I make the server open to the network, give the bot the right port and run it as it says in the tutorials. But it leads to absolutely nothing

**Comment by amoraschi** [comment]
Alright, sorry. The "physicTick" event (not recommended btw, use "physicsTick" instead) you're listening to is called 20 times a second, so it is called even if the bot hasn't spawned, try waiting for the spawn event before doing anything

**Comment by 7Zix7** [comment]
The problem is not in the code itself, because it worked in the tutorial. Okay, I'll try to explain.
Chain of actions: downloading programs -> ??? -> bot is playing

I completed the first step, downloaded node js, visual studio code and main flyer.

What should I do where the question marks are? What should I do after I have the code and programs to run the bot?

**Comment by 7Zix7** [comment]
I don't understand. Help, please, i really want use this

**Comment by amoraschi** [comment]
Add an error and kicked listener

**Comment by Karang** [comment]
in a terminal run `node bot.js` in the folder containing the bot.js file (which contains your code)

Might be helpful: https://www.youtube.com/watch?v=dRehDuNj0vU

**Comment by 7Zix7** [comment]
ok, i'll check it tomorrow. thank you in advance

**Comment by 7Zix7** [comment]
I tried everything that was there. I did everything to the point that Visual Studio Code did not detect errors. I sincerely do not understand what I'm doing wrong, but I really want it to work. Maybe I send my folder "mineflayer-master"?

**Comment by rom1504** [comment]
First install https://nodejs.org/en/ ; preferably on linux (for example using WSL if you're in windows)

1. create a completely new folder my_folder
2. put this file https://github.com/PrismarineJS/mineflayer/blob/master/examples/echo.js in it
3. cd my_folder then run npm install mineflayer
4. cd my_folder then run node echo.js

**Comment by 7Zix7** [comment]
Where to create a folder?

**Comment by rom1504** [comment]
C:/User/7Zix7/my_folder

**Comment by 7Zix7** [comment]
What to do with the folder mineflayer-master?

**Comment by 7Zix7** [comment]
delete?

**Comment by 7Zix7** [comment]
Nothing. Just nothing
![image](https://user-images.githubusercontent.com/99723113/154276335-2f5683fe-0c2f-4cf5-9c0f-cd8961da8d0f.png)

**Comment by rom1504** [comment]
run `node echo.js`

**Comment by rom1504** [comment]
but you're going to have to learn programming and some basics about node.js if you want to use this

**Comment by 7Zix7** [comment]
I'm not bad at programming myself. I can easily write my own code instead of this example once I figure out how to actually run it. You are right about node.js basics.

**Comment by 7Zix7** [comment]
In discord helped me. Thanks everyone!!
