### ISSUE TITLE
support 1.18.2

### ISSUE THREAD

**Issue by everettperiman** [PrismarineJS/mineflayer#2502]
- [x ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 8.5.2
 - server: vanilla 1.18.2
 - node: 14.19.0

## Detailed description of a problem
Mineflayer bot works fine for 1.18.1 but throws unsupported protocol errors for 1.18.2.

## What did you try yet?
I rolled back my installation to 1.18.1

## Your current code
example jumper.js 

## Expected behavior
My bot to connect to the server. 

## Additional context
Error code from trying to connect one bot.

Error: unsupported/unknown protocol version: 758, update minecraft-data
    at /home/server/node_modules/minecraft-protocol/src/client/autoVersion.js:32:28
    at /home/server/node_modules/minecraft-protocol/src/ping.js:13:7
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Cannot read property 'minecraftVersion' of undefined
    at /home/server/node_modules/minecraft-protocol/src/client/autoVersion.js:34:42
    at /home/server/node_modules/minecraft-protocol/src/ping.js:13:7
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by rom1504** [comment]
1.18.2 is indeed not supported yet

**Comment by nickelpro** [comment]
https://github.com/PrismarineJS/minecraft-data/pull/517

**Comment by u9g** [comment]
Support is done :)
