### ISSUE TITLE
move mineflayer and other "offical" plugins to a organization

### ISSUE THREAD

**Issue by pokeball99** [PrismarineJS/mineflayer#252]

**Comment by rom1504** [comment]
We are considering moving it to https://github.com/PrismarineJS. Since mineflayer's gitter is already the same as node-minecraft-protocol's gitter and node-minecraft-protocol is in PrismarineJS it makes sense.

**Comment by pokeball99** [comment]
yea i wouldn't see why not to move them there

**Comment by demipixel** [comment]
+1 I guess.

**Comment by roblabla** [comment]
I'm OK with mineflayer moving to PrismarineJS, if that's what people want.

**Comment by deathcap** [comment]
Since moved to https://github.com/PrismarineJS/mineflayer can this be closed?

**Comment by rom1504** [comment]
Yeah closing. We can move some mineflayer-* plugins in prismarinejs later if it is appropriate.
