### ISSUE TITLE
Hi i wanna make my 2bot to join a server with mineflayer and it's has underline and idk why. Can someone help?

### ISSUE THREAD

**Issue by zeelolnew** [PrismarineJS/mineflayer#2541]
There is the code:
var mineflayer = require('mineflayer');
 
let ip = "server ip";
let username = "name";
let ver = "1.18.1";
var bot = mineflayer.createBot({
  host: ip,   
  username: username,
  version: ver
})

bot.on('login', async () => {
    console.log(`bot is on At ${ip}`)
});

 
let ip = "server ip";
let username = "name";
let ver = "1.18.1";
var bot = mineflayer.createBot({
  host: ip,   
  username: username,
  version: ver
})

bot.on('login', async () => {
    console.log(`bot is on At ${ip}`)
  });
or sceeenshoot:
![image](https://user-images.githubusercontent.com/90578111/159372162-d694d337-2f4c-4ca2-8314-7107d1098edc.png)

**Comment by amoraschi** [comment]
You have duplicate variable names

**Comment by amoraschi** [comment]
Can you close this if it's solved

You can also join the Discord Server for further questions like this
