### ISSUE TITLE
Hi now i have 2 bot what can join and how can i make them to leave and join back in 16min?

### ISSUE THREAD

**Issue by zeelolnew** [PrismarineJS/mineflayer#2542]
there is  that last code:
var mineflayer = require('mineflayer');
 
let ip = "server ip";
let username = "username"
let ver = "1.18.1";
var bot = mineflayer.createBot({
  host: ip,   
  username: username,
  version: ver
})

bot.on('login', async () => {
    console.log(`bot is on At ${ip}`)
});

 
let ip1 = "server ip";
let username1 = "username";
let ver1 = "1.18.1";
var bot = mineflayer.createBot({
  host: ip1,   
  username: username1,
  version: ver1
})

bot.on('login', async () => {
    console.log(`bot is on At ${ip}`)
  });

**Comment by amoraschi** [comment]
Can you close this and ask it in the Discord Server instead

**Comment by zeelolnew** [comment]
> Can you close this and ask it in the Discord Server instead

Can u help me here? bc i don't know about the dc sever

**Comment by amoraschi** [comment]
The thing is, Issues are used to report bugs or suggest new features

What do you mean by "don't know about the server"

Here's the link: https://discord.gg/BeR2CHjj

**Comment by EnderTheCoder** [comment]
Just close it anyway.

**Comment by imharvol** [comment]
Check the example https://github.com/PrismarineJS/mineflayer/blob/master/examples/multiple.js
