### ISSUE TITLE
What methods should I use? (low-level)

### ISSUE THREAD

**Issue by Jan3kk** [PrismarineJS/mineflayer#2554]
I have a short question - what functions should I use to perform easy tasks, such as:

- walk to x: 50 y: 20 z: 50
- rightclick sign at x: 10 y: 20 z: 10
- destroy block at x: 50 y: 20 z: 60
- plant seed at x: 100 y: 21 z: 100

Two last ones are rather possible for me to find but it would take me couple of hours to figure out how they actually work (I'm beginner) But I can't really find any function that would make bot walk to certain pos or click certain block.

**Comment by amoraschi** [comment]
It's better if you ask this in the Discord Server, Issues are for bugs and features

**Comment by rom1504** [comment]
Issues and GitHub discussions are fine actually
Discord is not the only place to discuss and GitHub has the benefit to be searchable

**Comment by rom1504** [comment]
For walking to a point see https://github.com/PrismarineJS/mineflayer-pathfinder

For destroying a block use bot.dig

For planting a seed use bot.activateItem

For using signs see the sign example
