### ISSUE TITLE
ReferenceError: microsoft is not defined

### ISSUE THREAD

**Issue by Schwarzeisc00l** [PrismarineJS/mineflayer#2558]
I am trying to use a Microsoft account but it gives this weird error:
ReferenceError: microsoft is not defined
Possible bug?
Note: I'm new to this.

**Comment by amoraschi** [comment]
Can you share your code?

**Comment by Schwarzeisc00l** [comment]
> Can you share your code?

const mineflayer = require('mineflayer')
const config = require('./config.json')
const colors = require('colors')
//creates bot
//this is only for cracked if you want it for online replace this with 
function createBot () {
    const bot = mineflayer.createBot({
        host: config.ip,
        port: `25565`,
        username: config.email,
        password: config.password,
        version: `1.12.2`,
	auth: microsoft
    });
bot.once("login", () => {
    setTimeout(() => {
        console.log(`──────────────────────────────────────────`.blue);
    }, 0);
    setTimeout(() => {
        console.log((`Logged in as: `.green + `${bot.username}`.yellow));
    }, 1);
    setTimeout(() => {
        console.log((`Server: `.green + `0b0t.org`.yellow));
    }, 2);
    setTimeout(() => {
        console.log((`Port: `.green + `25565`.yellow));
    }, 3);
    setTimeout(() => {
        console.log(`──────────────────────────────────────────`.blue);
    }, 4);
});
//===========
// ANTI AFK
//===========
var moveinterval = 0;
var maxrandom = 0;
var lasttime = -1;
var moving = 0;
var actions = [ 'forward', 'back', 'left', 'right']
var lastaction;
var pi = 3.14159;
bot.on('time', function() {
    var randomadd = Math.random() * maxrandom * 20;
    var interval = moveinterval*20 + randomadd;
    if (bot.time.age - lasttime > interval) {
        if (moving == 1) {
            bot.setControlState(lastaction,false);
            moving = 0;
            lasttime = bot.time.age;
        } else {
            var yaw = Math.random()*pi - (0.5*pi);
            var pitch = Math.random()*pi - (0.5*pi);
            bot.look(yaw,pitch,false);

            lastaction = actions[Math.floor(Math.random() * actions.length)];
            bot.setControlState(lastaction,true);
            moving = 1;
            lasttime = bot.time.age;
            bot.swingArm('right');
        }
    }
});
//===========
// SPAMMER
//===========
spammer
var JFile = require('jfile');
var loadArray = new JFile("./ads.txt");
var phrases = loadArray.lines
var spammer =
    setTimeout(function () {
        spammer = setInterval(spam,(config.spamdelay*1000))
    }, 10000)
function spam() {
    var phrase = phrases[Math.floor(Math.random() * phrases.length)]
    bot.chat(`${phrase}`)
    }
//===========
// Relog on kick or error
//===========
bot.on('kicked', (reason) =>{
    console.log(reason)
})
bot.on('error', (err) =>{
    console.log(err)
})
bot.on('end', () => {
    console.log('Bot has ended Relogging in 10 seconds..')
    setTimeout(() => {
        console.log('Attempting to relog..');
        createBot()
    }, 10000);
})
}
createBot()

**Comment by amoraschi** [comment]
Put ' around microsoft so it's a string

Like this:

```js
auth: 'microsoft'

**Comment by amoraschi** [comment]
Put ' around microsoft so it's a string

Like this:

```js
auth: 'microsoft'
```

**Comment by amoraschi** [comment]
@Schwarzeisc00l Can you close this issue if it's solved?

**Comment by Schwarzeisc00l** [comment]
> @Schwarzeisc00l Can you close this issue if it's solved?

sorry i dont how to use Github well.
Closing!
