### ISSUE TITLE
Get all the tab complete value and off-hand item

### ISSUE THREAD

**Issue by QiuChen-Developer** [PrismarineJS/mineflayer#2564]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.2.0
 - server: purpur 1.18.2
 - node: 17.9.0

## Detailed description of a problem
Problem 1: Is there way to get all the tab complete value?
Problem 2: Getting bot's off-hand item

## What did you try yet?
Problem 1: I tried to use `bot.tabComplete()` with a loop but it stack at letter 'd' with no error or timeout
Problem 2: I tried to use `bot.inventory.items()` and `bot.inventory.containerItems()` but does not show the bot's off-hand item.

## My current code
```js

const alpha = Array.from(Array(26)).map((e, i) => i + 65);
const alphabet = alpha.map((x) => String.fromCharCode(x).toLowerCase());
let list = []
for (const temp of alphabet) {
    console.log(temp)
    let loader = (await bot.tabComplete(temp)).map(e => e.match) //.filter(e => e.includes(":"))
    if (loader.length !== 0) {
        list = list.concat(loader)
    }
}
console.log(list)


```

```js

let items = bot.inventory.items().map(function (x) {
    return {
    type: x.type, count: x.count,
    name: x.name, displayName: x.displayName, slot: x.slot
    }
})
let embed = new Discord.MessageEmbed()
    .setColor("RANDOM")
    .setTitle("Bot's Inventory")
    .addField("Inventory Item List", "```" + JSON.stringify(items) + "```")
    .addField("Equipments", "```" + JSON.stringify(bot.inventory.containerItems().map(function (x) {
        return {
            type: x.type, count: x.count,
            name: x.name, displayName: x.displayName, slot: x.slot
        }
    })) + "```")
message.reply({ embeds: [embed] })


```

## Expected behavior
Expect to grab all the tab complete commands like this
![](https://i.imgur.com/ZqmcwMb.png)
And expect to get the off-hand item, but it does not appear
![](https://i.imgur.com/TucjXaF.png)

## Additional context
none.

**Comment by QiuChen-Developer** [comment]
I found that I can use `bot.tabComplete("/")`

**Comment by amoraschi** [comment]
Problem 1: Try using bot.inventory.slots, that should contain off-hand slots too, but it also has null slots, so filter them out

**Comment by QiuChen-Developer** [comment]
Ok, got it. Thanks.
