### ISSUE TITLE
paper-1.18.2-283.jar

### ISSUE THREAD

**Issue by lukasz4444** [PrismarineJS/mineflayer#2570]
Error: unsupported/unknown protocol version: -1, update minecraft-data

TypeError: Cannot read properties of undefined (reading 'minecraftVersion')

**Comment by u9g** [comment]
show your package.json

**Comment by QiuChen-Developer** [comment]
share your code.

**Comment by u9g** [comment]
add version to createbot

**Comment by lukasz4444** [comment]
**@QiuChen-Developer ok.**

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: '', // minecraft server ip
  username: '', // minecraft username
  password: '',
  auth: 'microsoft'
})

**Comment by lukasz4444** [comment]
> add version to createbot

how?

**Comment by CC044** [comment]
> > add version to createbot
> 
> how?

```
const bot = mineflayer.createBot({
  host: '', // minecraft server ip
  username: '', // minecraft username
  password: '',
  auth: 'microsoft',
  version: '1.18.2'
})
```

[https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#mineflayercreatebotoptions](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#mineflayercreatebotoptions)

**Comment by extremeheat** [comment]
Your minecraft-data is out of date, do `npm update --depth 9999`.
