### ISSUE TITLE
Place Block

### ISSUE THREAD

**Issue by VaibhavVerma21** [PrismarineJS/mineflayer#2577]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest. not sure how to check
 - server: Fabric
 - node: 16.14.2
  
## Detailed description of a problem
I am making a bot to afk at my tree farm. For this i want to place saplings. 
It throws error when trying to place sapling if its already placed.

## What did you try yet?

Tried to find if there is a sapling around but can't figure that out too.
Decided to just catch the error and ignore it. but it stills somehow gives error and crashes

## Your current code
```js


try{
      bot.equip(bot.inventory.findInventoryItem(id,null), "hand").catch();
      bot.placeBlock(bot.blockAt(bot.entity.position.offset(1, -1, 0)), vec3(0, 1, 0)).catch();
    } catch(e) { }



```

## Expected behavior
Place sapling when there is none

**Comment by IceTank** [comment]
You are not handling errors correctly as your catch is empty. Also this dose not really work as bot.equip is asynchronous and you are not waiting for the returned promise to resolve before trying to place a block.

This is not an issue with mineflayer but an issue with your code. If you want quick help I suggest you join the PrismarineJS discord. It has a help channel where people can help you with your mineflayer/programming issues. The invite for that discord server is the big banner on the mineflayer Github page.

**Comment by VaibhavVerma21** [comment]
> You are not handling errors correctly as your catch is empty. Also this dose not really work as bot.equip is asynchronous and you are not waiting for the returned promise to resolve before trying to place a block.
> 
> This is not an issue with mineflayer but an issue with your code. If you want quick help I suggest you join the PrismarineJS discord. It has a help channel where people can help you with your mineflayer/programming issues. The invite for that discord server is the big banner on the mineflayer Github page.

so in theory it should fix if i put await there.
and in catch i just wanna ignore the exception and contiune on to the rest of code after it

**Comment by u9g** [comment]
I would suggest asking for help in either the discord (which is shown when you make an issue) or under the discussions tab which is to the right of the issues tab at the top of the page.
