### ISSUE TITLE
Possible bug with executing commands (bot.chat)

### ISSUE THREAD

**Issue by yeetyeeter02** [PrismarineJS/mineflayer#2579]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: Latest as of 15/04/2022, I don't know how to check
 - server: vanilla, 1.18.1
 - node: v17.9.0
 - 
## Detailed description of a problem
I'm trying to make my mineflayer bot join a minecraft server with Nlogin but I can't get it to register.
I have no error, the bot just gets kicked with the reason: {"color":"red","text":"You took too long to register."} true
I understand the reason, I just can't make the bot execute the "/register" command.

## What did you try yet?
I have tried:
- Delaying the execution of bot.chat
- Changing what executes bot.chat
- Logging all messages that might help me find the issue to console, nothing is sent
- Rewriting my entire project

## Your current code
```js
/*
bot.once('spawn', () => {
    console.log('Spawned!');
    bot.chat('/register )IdfhhdH(*D*7gD* )IdfhhdH(*D*7gD*');
});
*/
```

## Expected behavior
The bot to run the "/register" command

**Comment by IceTank** [comment]
Have you tried to log all chat messages that the bot receives? You may be using the command wrong or the server might have some other issue it is telling you about by sending a chat message. You can use the messagestr event on the bot to get all received chat messages.

**Comment by yeetyeeter02** [comment]
I didn't understand that section of the FAQ, but looking over it again has helped me see the issue!
It turns out the password was too long, even if the limit is 32 characters! I guess i have a server to fix, lol
Thank you!
