### ISSUE TITLE
Example program produces deprecation warnings

### ISSUE THREAD

**Issue by FM-96** [PrismarineJS/mineflayer#2580]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.2.0
 - server: paper 1.18.2-287
 - node: 16.6.1

## Detailed description of a problem
Running a slightly modified version of the `reconnector.js` example file (see below for current code) leads to repeated deprecation warnings filling up the console:

```
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
{mcData}.findItemOrBlockById() is deprecated, scheduled to be removed on or after April 1 2022
```

## Your current code
```js
const mineflayer = require('mineflayer')

const loginData = {
	host: 'localhost',
	username: '[REDACTED]',
	password: '[REDACTED]',
	auth: 'microsoft',

}

function createBot() {
	const bot = mineflayer.createBot(loginData)

	bot.on('chat', (username, message) => {
		if (username === bot.username) return
		bot.chat(message)
	})

	bot.on('end', createBot)
}

createBot()
```

## Expected behavior
The `.findItemOrBlockById()` method referenced in the deprecation warning isn't used in the example code. Presumably it is called somewhere in the background during regular operation.

Ideally, a deprecated method shouldn't be used internally at all, but even if it is, it should not print out deprecation warnings when the end user can't do anything about it.

**Comment by u9g** [comment]
can you do `npm install https://github.com/PrismarineJS/mineflayer/tree/u9g-patch-2` and tell me if you still see the error spam?

**Comment by FM-96** [comment]
Well, that *exact* command just threw an error, but installing the branch with `npm install https://github.com/PrismarineJS/mineflayer#u9g-patch-2` did make the messages disappear, yes!

Interestingly, switching back to 4.2.0 didn't cause them to reappear again, and neither did a completely fresh install of 4.2.0. It seems I just had the bad luck to stumble upon some edge case with some dependencies being kept at an older version by my package-lock file?

**Comment by gamerboytr** [comment]
just add this code at the top of your code
```js
console.log = function (...args) {
  if (args[0].includes('is deprecated, scheduled to be removed on or after')) {
    return;
  }
  this(...args);
}.bind(console.log);
```

**Comment by extremeheat** [comment]
Fixed in latest versions, use `npm update --depth 9999` to update everything

**Comment by gamerboytr** [comment]
> Fixed in latest versions, use `npm update --depth 9999` to update everything

still same error

**Comment by FM-96** [comment]
> just add this code at the top of your code
> 
> ```js
> console.log = function (...args) {
> if (typeof args[0] === 'string' && args[0].includes('is deprecated, scheduled to be removed on or after')) {
>   return;
> }
>   this(...args);
> }.bind(console.log);
> ```

This is an absolutely horrible idea that does nothing to fix the underlying issue and instead just clumsily tries to hide it (and breaks *all* deprecation warnings in the process). Nobody should ever do this in any kind of serious program.
