### ISSUE TITLE
Error in playerCollect

### ISSUE THREAD

**Issue by Sunderw3k** [PrismarineJS/mineflayer#2598]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.3.0
 - server: vanilla 1.18.2
 - node: 17.8.0

## Detailed description of a problem
Trying to pick up an item and equip it. Stuck on the picking up part

## What did you try yet?

Im trying a snippet of a code from the chatterbox.js example line 170

## Your current code
```js

    bot.on("playerCollect", (collector, collected) => {
        if (collector.type == "player" && collected.type == "object" && collector.username == bot.username){
            console.log(collected)
            const rawItem = collected.metadata[10];
            console.log(rawItem)
            const item = mineflayer.Item.fromNotch(rawItem);
            console.log(item);
        }
    })


```

## Expected behavior
the console.log() should log 3 times without crashing, yet rawItem is undefined and mineflayer.Item.fromNotch() crashes with TypeError: Cannot read properties of undefined (reading 'fromNotch')

Edit:
I am preeety sure collected.metadata[10] doesnt exist but I dont know what I really need to equip the item so Im just going to wait for help.

**Comment by amoraschi** [comment]
Use this instead:
```js
const Item = require('prismarine-item')

Item.fromNotch(...)
```

If `collected.metadata[10]` doesn't exist, why are you trying to log it? And if it doesn't exist, well yeah, the expected behavior is to crash `Item.fromNotch`

If you want to equip the collected item, I would just get the Item in my inventory with the same ID as the collected Item

**Comment by Sunderw3k** [comment]
The `console.log()` was meant to be used for debugging of what collected.metadata[10] was supposed to be. Also I think the example should be changed to the solution above considering it currently crashes.

**Comment by amoraschi** [comment]
👌 PRs open to fix the examples

**Comment by Sunderw3k** [comment]
Actually Im still confused. What am I supposed to put into the ``Item.fromNotch()``?

**Comment by u9g** [comment]
just do `collected.getDroppedItem()`

**Comment by Sunderw3k** [comment]
Oh it works! Thanks. I'm probably not gonna make a PR because I dont know how I would handle other peoples items - unless minecraft lets me see what items they picked up
