### ISSUE TITLE
Sometime works, Sometime not

### ISSUE THREAD

**Issue by VaibhavVerma21** [PrismarineJS/mineflayer#2599]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server:  Fabric
 - node: v17

## Detailed description of a problem
Trying to make a bot to autocraft golden nuggets to golden blocks. It decided to work yesterday. but when i run it today it fails. sometime when withdrawing nuggets from shulker and always when depositing golden blocks. also when using bot.craft() it was only crafting one thing(but this is for another bug report) 

## What did you try yet?
I have been trying to figure it out this stuff in the discord
https://discord.com/channels/413438066984747026/966333751397318707/966474253937553438
Many people helped. It worked. but today it fails

## Your current code
```js  
  const mcData = require('minecraft-data')(bot.version)
    await bot.waitForChunksToLoad()
    for (let num = 1; num <= 27; num++) {
        for (let i = 1; i <= 3; i++) {
            // bot.chat('/clear')
            await sleep(10)
            var shulker = await bot.openContainer(bot.blockAt(vec3(-7, -49, 15)))
            await shulker.withdraw(mcData.itemsByName['gold_nugget'].id, null, 1728);
            shulker.close()
            const ingot = bot.recipesFor(mcData.itemsByName['gold_ingot'].id, null, 1, bot.blockAt(vec3(-6, -49, 15)))[0]
            const craftingTable = await bot.openBlock(bot.blockAt(vec3(-6, -49, 15)))
            for (let j = 1; j <= 3; j++) {
                for (let s = 1; s <= 9; s++) {
                    await bot.clickWindow(9 + s + 9 * (j - 1), 0, 0)
                    await sleep(10);
                    await bot.clickWindow(s, 0, 0)
                    await sleep(10);
                }
                for (let c = 1; c <= 64; c++) {
                    await bot.clickWindow(0, 0, 0)
                    await sleep(10);
                    await bot.clickWindow(36 + j + 3 * (i - 1), 0, 0)
                    await sleep(10);
                }
            }
            await bot.closeWindow(craftingTable)
        }
        const table = await bot.openBlock(bot.blockAt(vec3(-6, -49, 15)))
        for (let yo = 1; yo <= 9; yo++) {
            await bot.clickWindow(36 + yo, 0, 0)
            await sleep(10);
            await bot.clickWindow(yo, 0, 0)
            await sleep(10);
        }
        for (let yo2 = 1; yo2 <= 64; yo2++) {
            await bot.clickWindow(0, 0, 0)
            await sleep(10);
            await bot.clickWindow(37, 0, 0)
            await sleep(10);
        }
        var shulker = await bot.openContainer(bot.blockAt(vec3(-5, -49, 15)))
        await shulker.deposit(mcData.itemsByName['gold_block'].id, null, 64);
        shulker.close()
    }
    console.log('spawn done')
})
```

## Expected behavior
(Withdraw nuggets.. => craft into ingot and keep in hot bar)x3 => craft ingot to blocks => deposit

**Comment by sefirosweb** [comment]
Hi why you are using a `bot.clickWindow instead this.bot.transfer(options)` or  `ontainer.withdraw(foundItem.type, null, quantity)` / `container.deposit(itemToDeposit.type, null, itemToDeposit.quantity)`

You have an custom server / mods?

**Comment by VaibhavVerma21** [comment]
> Hi why you are using a `bot.clickWindow` instead `this.bot.transfer(options)` or `ontainer.withdraw(foundItem.type, null, quantity)` / `container.deposit(itemToDeposit.type, null, itemToDeposit.quantity)`
> 
> You have an custom server / mods?

 Mods 

VoiceChat
Servux (this allows you to see structure bounding boxes with minihud)
Carpet and Carpet extra (flippin cactus, renewable coral, renewable sponges and accurate block placement).
Lithium (server performance)
phosphor (server performance)

 DataPacks 

Anti-Enderman Grief
More Mob Heads
Silence Mobs
Universal Dyeing
Dragon Drops (head, egg and elytra) this is to help new players get an elytra and remove the need to do large scale end busting.
Armor Statues (books in the shopping district free)
Wandering Trader sells mini blocks and heads (players heads are admins, mods and patreons only). 

and i think i am using withdraw and deposit above.

**Comment by VaibhavVerma21** [comment]
It manage to work. It was working for others but not me. Found out that inventoryViewer somehow prevents to do. I will close the issue in some time if no comments are made.
