### ISSUE TITLE
Using slate for the API ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#260]
The idea would be using [slate](https://github.com/tripit/slate) to make the [api](https://github.com/andrewrk/mineflayer/blob/master/doc/api.md) easier to read.

The plan is : 
- [ ] convert api.md to slate format
- [ ] put the html file in a gh-pages branch of mineflayer
- [ ] have circle ci automatically update the html files

Some related links : 
- [deploying slate](https://github.com/tripit/slate/wiki/Deploying-Slate)
- [slate markdown](https://github.com/tripit/slate/wiki/Markdown-Syntax) (is there any relevant difference to github markdown ?)

**Comment by demipixel** [comment]
I can't say no to better documentation.

**Comment by rom1504** [comment]
What about https://github.com/jsdoc3/jsdoc ?

**Comment by roblabla** [comment]
I think writing explicit documentation is much better. Comments in code tend to be very unfocussed and weird for documentation.

**Comment by rom1504** [comment]
So slate would look like this http://rom1504.github.io/slate/
* does it look better than https://github.com/andrewrk/mineflayer/blob/master/doc/api.md ?
* got to figure out how to not put the slates file in the master branch but still put api.md in the master branch (see https://github.com/tripit/slate#getting-set-up)

**Comment by rom1504** [comment]
see https://spockbot.readthedocs.org/ for inspiration

**Comment by rom1504** [comment]
example of good looking doc http://nalgebra.org/doc/nalgebra/index.html

**Comment by rom1504** [comment]
https://doc.rust-lang.org/book/documentation.html

**Comment by rom1504** [comment]
done with docsify https://rawgit.com/PrismarineJS/mineflayer/master/docs/#/
