### ISSUE TITLE
Bot suddenly quits from server 

### ISSUE THREAD

**Issue by MatLudke** [PrismarineJS/mineflayer#2608]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: vanilla/1.8.9
 - node: 16.15.0

## Detailed description of a problem
my bot quit suddenly from the server after some minutes 

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
`
bot.once('spawn', () =>{

    bot.chat("/login password")

    bot.setQuickBarSlot(4)

    bot.activateItem(true)

   bot.on('windowOpen', () =>{
       bot.clickWindow(12, 0, 0)
   })
`

/*
Some code here, replace this
*/

```

## Expected behavior
A clear and concise description of what you expected to happen.

## Additional context
Add any other context about the problem here.

**Comment by IceTank** [comment]
Add this after creating the bot 
```js
bot.on('error', console.log)
bot.on('kicked', console.log)
```

**Comment by 1ProCrafters** [comment]
Does it have any errors in console after adding IceTank's code
