### ISSUE TITLE
Check the callback of the methods are called at the right time

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#262]
Some callback are called too early or too late. I would be nice to check which one. Doing this automatically would be better (adding a test).
Known callback problem : 
- [ ] bot.equip callback return too soon
- [ ] placeBlock doesn't have a callback (also see #261 )

**Comment by rom1504** [comment]
bot.lookAt (https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#botlookatpoint-force) should have a callback, it's not instantaneous

**Comment by rom1504** [comment]
the callback of bot.lookAt should be called when the move event id emmited = when the position/look has been sent.

Relevant for things depending on where you look : shooting an arrow, moving a vehicle (https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#botmovevehicleleftforward)
it's especially important for arrows : if you shoot before aiming properly it will shoot at the wrong location.

**Comment by rom1504** [comment]
An other way might be sending directly a http://wiki.vg/Protocol#Player_Look packet.

Check if this is not a problem to send that kind of packet too often.

**Comment by rom1504** [comment]
Apparently NCP (NoCheat+) doesn't like instant updates, and mineflayer currently doesn't do any, maybe we should keep doing that.

**Comment by rom1504** [comment]
bot.look and bot.lookAt now have a callback, so that part of this issue is fixed.

**Comment by ViRb3** [comment]
Any update on `bot.equip callback return too soon`? It's causing some funky behavior here...
#326

**Comment by ViRb3** [comment]
Every second time I log the bot on my server he has a pickaxe in his hand, but mineflayer truly believes it's cobblestone. I'm using the following code, modified from the scaffold plugin:
```
function equipBuildingBlock(cb) {
        console.log("Equipping building block")
        // return true if we're already good to go
        if (bot.heldItem && scaffoldBlockTypes[bot.heldItem.type]) { // says cobblestone
            console.log("Already equipped");
            cb();
            return true;
        }

        var scaffoldingItems = bot.inventory.items().filter(function (item) {
            return scaffoldBlockTypes[item.type];
        });

        var item = scaffoldingItems[0];
        if (!item) {
            changeState('stop', 'error');
            return false;
        }

        bot.equip(scaffoldingItems[0], 'hand', function (err) {
            if (err) {
                changeState('stop', 'error', err);
            }

            console.log("Callback in 500");
            setTimeout(function () {
                cb();
            }, 500);
        });
    }
```

**Comment by rom1504** [comment]
I think it's ok now
