### ISSUE TITLE
Return value of isABed is mistyped

### ISSUE THREAD

**Issue by TRCYX** [PrismarineJS/mineflayer#2621]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.3.0

## Detailed description of a problem
In `index.d.ts` we have
https://github.com/PrismarineJS/mineflayer/blob/748629ca81bcd4bdaaecc4840a24e78a89c721e8/index.d.ts#L252
But this function obviously returns boolean:
https://github.com/PrismarineJS/mineflayer/blob/748629ca81bcd4bdaaecc4840a24e78a89c721e8/lib/plugins/bed.js#L13-L15

## Expected behavior
The return value should be boolean.

**Comment by amoraschi** [comment]
#2628 Merged
We can close this
