### ISSUE TITLE
Erreur: require("mineflayer");

### ISSUE THREAD

**Issue by Nelkot** [PrismarineJS/mineflayer#2624]
I'm trying to solve this erreur for 2 hours and still i'm not even sure what erreur it is. So the erreur is the require("mineflayer"); but idk how to get the log of the erreur so if i need it please told me how. Thanks For Helping !

-- index.js --

const mineflayer = require("mineflayer");

var settings = {
    username: "TestMachine",
    host: "localhost",
};

const bot = mineflayer.createBot(settings);

Edit : I'm using eclipse and for 1.8.8

**Comment by amoraschi** [comment]
What's the full error

**Comment by Nelkot** [comment]
> 

How do I get the full error

**Comment by amoraschi** [comment]
Well, how did you get the `require("mineflayer")` error

**Comment by Nelkot** [comment]
when I start the index.js file it says that there is an error at the first line
and when I run it with eclipse it says "Unable to find an Ant file to run."

**Comment by amoraschi** [comment]
Why are you running it with eclipse, this isn't Java, it's JavaScript

**Comment by extremeheat** [comment]
🤣

please see tutorial and ask on discord if you have trouble following it. In order to use mineflayer you must know some Javascript and the basics of how to use node.js/npm

**Comment by Mathrandom7910** [comment]
This is a serious "erreur", I cannot believe this "erreur" was closed without fixing the "erreur".
