### ISSUE TITLE
Error when using window.withdraw()

### ISSUE THREAD

**Issue by PitPot1** [PrismarineJS/mineflayer#2631]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: spigot
 - node: latest

## Detailed description of a problem
I have been encountering errors when using the withdraw() function to get items from a chest to the bot's inventory, the function works file as long as there is only 1 item in the chest but if there are multiple a 'TypeError: Cannot read properties of null (reading 'type')' is thrown (caused by clickDest(), line 264 in inventory.js).

## What did you try yet?

Did you try any method from the API? I TRIED EVERYTHING IM GOING INSANE IVE BEEN TRYING FOR 10 HOURS STRIGHT
Did you try any example? Any error from those? 

## Your current code
```js
client.openChest(chest).then(async (c) => {
                for (let slot = 0; slot < c.inventoryStart; slot++) {
                    const item = c.slots[slot];
                    if (item != null) {
                        try {
                            c.withdraw(item.type, null, 999999)
                            console.log("took "+ item.count + " of " + item.count /* was previously 999999, same error occurs*/);
                        } catch {
                            console.log("inv full");
                            done = true
                            break
                        }
                    } else {
                        console.log("empty slot");
                    }
                }
            })
```

## Expected behavior
Items should be withdrawn from the chest with no errors

## Additional context
help.

**Comment by amoraschi** [comment]
Try using c.slots.length instead of c.inventoryStart, and await c.withdraw

**Comment by PitPot1** [comment]
i did use item.count at first, it didnt change anything
c.slots.length would return the total amount of slots (including those of the bot inventory) so it isnt really helpful
ill try the await part
