### ISSUE TITLE
Anyway to use server selector??

### ISSUE THREAD

**Issue by RavjotSinghgame** [PrismarineJS/mineflayer#2632]
I have been trying to find a way to use server selector in jartex but couldn't find solution anyone?

**Comment by Rat2b2t** [comment]
Use https://github.com/PrismarineJS/prismarine-windows

**Comment by u9g** [comment]
1. Use the switch quickbar slot to the slot of the server selector using: [bot.setQuickBarSlot(slot)](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botsetquickbarslotslot)
2. Activate the item using [bot.activateItem](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botactivateitemoffhandfalse)
3. Wait for the window to open using the ["windowOpen" (window)](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#windowopen-window) event
4. Right click on the item you want in the gui following [this guide](https://u9g.github.io/mineflayer-docs/inventory/simple-inventory-interaction/)
5. Right click on the `item.slot` from the `item` you got from the previous step using [bot.simpleClick.rightMouse (slot)](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botsimpleclickrightmouse-slot)
