### ISSUE TITLE
Stacking 2 shulker boxes causes error - chest.withdraw

### ISSUE THREAD

**Issue by RoseChilds** [PrismarineJS/mineflayer#2641]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.3.0
 - server: vanilla 1.12.2
 - node: 14.19.1

## Detailed description of a problem
Attempting to withdraw multiple items from a chest results in the following error:
```
(node:7316) UnhandledPromiseRejectionWarning: Error: Server rejected transaction for clicking on slot 54, on window with id 1.
```
This leads me to believe the bot is attempting to withdraw an item to a slot that already has stuff in it.
## Your current code
```js
const mineflayer = require("mineflayer");
const pathfinder = require("mineflayer-pathfinder");
const bot = mineflayer.createBot({
  type: "mojang",
  host: "localhost",
  port: 25565,
  username: "bot"
});
bot.loadPlugin(pathfinder.pathfinder);
bot.on("error", console.error);
bot.once("spawn", async() => {
  bot.chat("Looking for chests");
  const nearbyChests = bot.findBlocks({
    matching: (block) => {
      return block.name === "chest";
    },
    maxDistance: 128,
    count: 10000
  });
  let items = new Array(5).fill("sku-uej");
  for(const chest of nearbyChests){
    await bot.pathfinder.goto(new pathfinder.goals.GoalNearXZ(chest.x, chest.z, 2));
    const block = bot.blockAt(chest);
    let chestObj = await bot.openContainer(block);
    const chestItems = chestObj.containerItems();
    await bot.waitForTicks(20);
    for(const item of chestItems){
      let name = item?.nbt?.value?.BlockEntityTag?.value?.CustomName?.value || item.name;
      let _item = items.find(i => name.includes(i));
      if(_item){
        items.splice(items.indexOf(_item), 1);
        await chestObj.withdraw(item.type, null, 1, item.nbt);
        await bot.waitForTicks(20);
      }
      if(items.length === 0) break;
    }
    await bot.closeWindow(chestObj);
    if(items.length === 0) break;
  }
});
```

## Expected behavior
Items get withdrawn until the `items` array is empty or the chests no longer have the desired items.

## Additional context
The bot errors out at the 2nd item.
To reproduce this, fill a double chest with shulker boxes that have been renamed to include `sku-uej` somewhere in the name. Make sure the bot will spawn near the chest, and run the code.

## Thoughts
Maybe it thinks shulker boxes can be stacked? Could be the fact they're renamed and have identical things inside that's fucking with it.

**Comment by RoseChilds** [comment]
![image](https://user-images.githubusercontent.com/78880286/170845451-929337c4-0838-46a1-9c52-c870ff60b401.png)
I'm not quite sure what the `stackSize` property means, but if it means "this item can stack to x", i.e. ender pearls have a `stackSize` of 16, then this is incorrect and probably why the error is occuring.

**Comment by u9g** [comment]
Yeah, I think the fix is to add the rules for stacking correctly to prismarine-windows. For now, you can try just monkeypatching prismarine-windows to always say that two items are different if either is a shulker.

**Comment by RoseChilds** [comment]
Pretty sure the error originates from https://github.com/PrismarineJS/minecraft-data.
[Here](https://github.com/PrismarineJS/minecraft-data/blob/ba957f1c36401a43cc8c7ef503c7ddfa01764e69/data/pc/1.12/items.json#L1002)'s the 1.12 minecraft-data input for `white_shulker_box`. The stack size is 64, where it should be 1. My ender pearl example from earlier seems to succumb to the same fate, as the `stackSize` also seems [wrong](https://github.com/PrismarineJS/minecraft-data/blob/ba957f1c36401a43cc8c7ef503c7ddfa01764e69/data/pc/1.12/items.json#L2490).

Or maybe this is intended behaviour, I'm not to know.

**Comment by RoseChilds** [comment]
Fixed in https://github.com/PrismarineJS/minecraft-data/pull/563
