### ISSUE TITLE
Mining with oresim

### ISSUE THREAD

**Issue by adabugra** [PrismarineJS/mineflayer#2644]
## Is your feature request related to a problem? Please describe.
no

Can you add oresim support to mineflayer (it detecs a ores location with servers seed.)

**Comment by amoraschi** [comment]
There's the findBlock function, but I don't think that feature will be added, mind explaining what Oresim does?

**Comment by Karang** [comment]
It's probably for servers with anti-xray, which sends the ore as regular stone if it's too far.
Unfortunately we don't have a way to simulate the ore generation yet. For 1.18, I'm working on updating prismarine-rng and there is a chance that i'll add terrain and ore generation, since it's not that much more complicated once biomes are figured out. For older version, it's very unlikely to happen.

**Comment by adabugra** [comment]
> There's the findBlock function
> 
> I don't think that feature will be added, mind explaining what Oresim does? I understand that it detects the ore locations, but that can be done already with findBlock.

its for servers that have antixray protection

**Comment by adabugra** [comment]
> It's probably for servers with anti-xray, which sends the ore as regular stone if it's too far. Unfortunately we don't have a way to simulate the ore generation yet. For 1.18, I'm working on updating prismarine-rng and there is a chance that i'll add terrain and ore generation, since it's not that much more complicated once biomes are figured out. For older version, it's very unlikely to happen.

client have that. i need it for 1.17 nether for mining gold

**Comment by amoraschi** [comment]
> > It's probably for servers with anti-xray, which sends the ore as regular stone if it's too far. Unfortunately we don't have a way to simulate the ore generation yet. For 1.18, I'm working on updating prismarine-rng and there is a chance that i'll add terrain and ore generation, since it's not that much more complicated once biomes are figured out. For older version, it's very unlikely to happen.
> 
> client have that. i need it for 1.17 nether for mining gold

PRs open, if clients have that, you could take the Java code and rewrite it in JavaScript

**Comment by adabugra** [comment]
> > > It's probably for servers with anti-xray, which sends the ore as regular stone if it's too far. Unfortunately we don't have a way to simulate the ore generation yet. For 1.18, I'm working on updating prismarine-rng and there is a chance that i'll add terrain and ore generation, since it's not that much more complicated once biomes are figured out. For older version, it's very unlikely to happen.
> > 
> > 
> > client have that. i need it for 1.17 nether for mining gold
> 
> PRs open, if clients have that, you could take the Java code and rewrite it in JavaScript

i can give you java code but i cant rewrite it in javascript
