### ISSUE TITLE
Are we handling slotCount correctly in windows.js ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#265]
As said in https://github.com/andrewrk/mineflayer/pull/166 and http://wiki.vg/Protocol#Open_Window , the number of slots in the packet should exclude the player inventory.

This was a problem for large chest (see https://github.com/andrewrk/mineflayer/commit/a02db44db3e7b8c092a0bfdbace35515bd7f6039#diff-662f0dd08955efb571616b363da8fc40R278), check if it's not a problem for other windows in windows.js.

**Comment by rom1504** [comment]
Also without that change https://github.com/andrewrk/mineflayer/commit/a02db44db3e7b8c092a0bfdbace35515bd7f6039#diff-662f0dd08955efb571616b363da8fc40R278 somehow useChests.js still work, try and figure out why (it should fail without that change)

**Comment by rom1504** [comment]
I really can't figure out what's different between useChests.js and chests.js so that useChests.js doesn't care about the slotcount. I'm going to stop looking for that for now since the problem about slotCount for large chest is fixed.

**Comment by rom1504** [comment]
> 13:51 < Gjum> I noticed that for blocks *without* a persistent inventory (crafting bench, anvil contrary to chest, furnace), the server sends `Number Of Slots = 0` slots when opening the window, maybe that has to do with andrewrk/mineflayer#265?

Check that

**Comment by Karang** [comment]
checked and solved in https://github.com/PrismarineJS/mineflayer/pull/968
