### ISSUE TITLE
How to get the name of a renamed item?

### ISSUE THREAD

**Issue by timof123** [PrismarineJS/mineflayer#2651]
I need to get the name of an item that was renamed on an anvil. The item is in the chest.
The command chest.containerItems() gives the following:
`[
  Item {
    type: 175,
    count: 1,
    metadata: 0,
    nbt: { type: 'compound', name: '', value: [Object] },
    name: 'double_plant',
    displayName: 'Large Flowers',
    stackSize: 64,
    slot: 0
  }
]
`
There is no changed item name here. How to get it?

**Comment by IceTank** [comment]
The new name for a renamed item should be in the nbt tag. You can parse the nbt tag and make it more readable by using the simplify function in prismarine-nbt.

**Comment by u9g** [comment]
item#customName
