### ISSUE TITLE
Play note block song.

### ISSUE THREAD

**Issue by mirkokral** [PrismarineJS/mineflayer#2658]
## Is your feature request related to a problem? Please describe.
I want my bot to play music like the other cool bots on kaboom.pw

## Describe the solution you'd like
Something like this:
```js
//... Some bot starting code ...
bot.on("chat",(username,message) => {
   if(message == "!faded"){
      bot.chat("/tp 100 100 100") // position of note block platform
      bot.initNoteBlocks(vec3(100,100,100),vec3(110,100,110))
      bot.playSong("faded.nbs")
   }
}
```
## Describe alternatives you've considered
none

## Additional context
The song is named "faded.nbs"

**Comment by extremeheat** [comment]
You can't play arbitrary files from the client side. You can only run commands on the server to play a sound (with `/playsound`). If you want to play a beat, you will need to program your bot to send lots of time synchronized `/playsound` commands at different pitches.

You can also upload a custom resource pack to the server (with custom audio in it), have clients download it, then when the playsound command is used, you can play the modified sounds available in the resource pack.

**Comment by VatraXD** [comment]
Why was this closed as completed? Playing noteblocks from a midi shouldn't be too hard, and is entirely possible from the clientside.
