### ISSUE TITLE
Can't make my bot sneak

### ISSUE THREAD

**Issue by 321Proteus** [PrismarineJS/mineflayer#2660]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 
Yes, it doesn't (i looked for the solution but didn't found)
## Versions
 - mineflayer: 4.3.0 (mineflayer.pathfinder is 2.1.1)
 - server: vanilla/spigot/paper 1.18.1
 - node: 17.3.0

## Detailed description of a problem
I want to make a bot that sneaks for 0,5s every three seconds with Mineflayer and Mineflayer-pathfinder. When I try to use `bot.setControlState(sneak, true)` 
the program says that `bot.setControlState is not a function`

## What did you try yet?
tried to use `console.log(bot.entity)` and it said "undefined", tried

## Did you try any method from the API?
Yes.

## Did you try any example? Any error from those?
There are no examples of this currently :|

## Your current code
[Pastebin link](https://pastebin.com/JMVZL3Wg)
```js


/* it has around 60 lines, idk if pasting it would be considered as flooding, im new */

```

## Expected behavior
Bot connects to server and starts walking to the target written in chat, every 3 seconds he crouches for half a second (still walking)

## Additional context
Trying to make Polonaise (traditional Polish dance) in Minecraft.
Any help would be very nice :smiley:

**Comment by amoraschi** [comment]
Start sneaking after spawning, wait for the event "spawn" before executing the function

**Comment by 321Proteus** [comment]
still the same: `setTimeout(bot.setControlState('sneak', true), t)`
`TypeError: bot.setControlState is not a function`

**Comment by 321Proteus** [comment]
Now it's like this https://pastebin.com/P95bu8hs

**Comment by amoraschi** [comment]
You're still executing sneak outside the spawn event

**Comment by 321Proteus** [comment]
So should it look like this?

`const { mineflayer: mineflayerViewer } = require('prismarine-viewer')
bot.once('spawn', () => {
  mineflayerViewer(bot, { port: 3007, firstPerson: false })
sneak(500, 3000)
})
bot.on('message', locateNextGoal)
`

**Comment by 321Proteus** [comment]
OK, I will test it tomorrow, it's 10 PM at Poland

**Comment by 321Proteus** [comment]
Hello @amoraschi , after editing the code to fit your tips, the error had changed.
Now it looks like this: 
```Pathfinder joined the game
(node:11529) Warning: No such label '[object Object]' for console.timeLog()
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/validators:224
    throw new ERR_INVALID_CALLBACK(callback);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at setTimeout (node:timers:143:3)
    at sneak (/home/proteus/Pulpit/Polonez (TOP SECRET)/src/pathfinderer.js:38:5)
    at EventEmitter.<anonymous> (/home/proteus/Pulpit/Polonez (TOP SECRET)/src/pathfinderer.js:66:3)
    at Object.onceWrapper (node:events:509:28)
    at EventEmitter.emit (node:events:402:35)
    at Client.<anonymous> (/home/proteus/Pulpit/Polonez (TOP SECRET)/node_modules/mineflayer/lib/plugins/health.js:13:11)
    at Object.onceWrapper (node:events:510:26)
    at Client.emit (node:events:402:35)
    at FullPacketParser.<anonymous> (/home/proteus/Pulpit/Polonez (TOP SECRET)/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (node:events:390:28) {
  code: 'ERR_INVALID_CALLBACK'
}
```
Any ideas?

**Comment by 321Proteus** [comment]
OK, I've rewritten the code, now it works perfectly. Idk what the bug was.
