### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by RandomTNT** [PrismarineJS/mineflayer#2668]
- https://github.com/PrismarineJS/minecraft-data/issues/575
- https://github.com/PrismarineJS/node-minecraft-protocol/issues/1011

**Comment by maxwellewxam** [comment]
2 monke want 1.19

**Comment by Myiro** [comment]
please 1.19

**Comment by Kashalls** [comment]
someone is working on it.

soon:tm:

**Comment by extremeheat** [comment]
Open for PR, updating protocol data is first step

**Comment by tolacika** [comment]
Just asking, do you have some experimental build-ish something? 😊 
I really wanna mess around with this 😅

**Comment by nickelpro** [comment]
As extremeheat already said, protocol needs to be updated before anything else can happen. It's not hard or complicated, it's just labor. Typically 1-2 hours of transcribing the protocol and then getting it reviewed and doing fixups.

No point in asking the state of 1.19 in mineflayer when there is no protocol support in MCD and thus the bot can't even log in

**Comment by rushic24** [comment]
<div style="width:100%;height:0;padding-bottom:60%;position:relative;"><iframe src="https://giphy.com/embed/pFZTlrO0MV6LoWSDXd" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/waiting-mr-bean-checking-time-pFZTlrO0MV6LoWSDXd">via GIPHY</a></p>

**Comment by rushic24** [comment]
https://giphy.com/gifs/waiting-mr-bean-checking-time-pFZTlrO0MV6LoWSDXd

**Comment by Kashalls** [comment]
@rushic24 Come on and do the dirty work for everyone! You seem to have the freetime waiting. /s

**Comment by rushic24** [comment]
@Kashalls i wish i could, but I recently got introduced to Minecraft and my friends play on 1.19, I started with hello world version that led me here

**Comment by Kashalls** [comment]
> 

No better first steps than baby steps!

**Comment by rushic24** [comment]
I found https://github.com/MrKinau/FishingBot in Java it works for 1.19, Maybe it might help in figuring out the api calls

**Comment by udu3324** [comment]
This issue may help [https://github.com/MCCTeam/Minecraft-Console-Client/issues/2053](https://github.com/MCCTeam/Minecraft-Console-Client/issues/2053)

**Comment by Cabbasca** [comment]
Are you still working on 1.19?

**Comment by rom1504** [comment]
only one person has worked on it for now, there https://github.com/PrismarineJS/minecraft-data/pull/587

feel free to help

**Comment by TigerbyteDev** [comment]
> only one person has worked on it for now, there [PrismarineJS/minecraft-data#587](https://github.com/PrismarineJS/minecraft-data/pull/587)
> 
> feel free to help

I would help, if I would know what is needed to be done. The code for that is too fragmented, as I can figure out what exactly need to be changed for 1.19.

**Comment by elct9620** [comment]
Not sure the `protocol.json` is ready. But I guess it may need to help review all commands to fit 1.19.

I found a document that can be referenced: https://wiki.vg/Protocol

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/issues/575

You can also read https://github.com/PrismarineJS/prismarine-contribute#updating-to-new-minecraft-versions

You can also join #contribute at discord and people will explain

**Comment by rom1504** [comment]
You can also check the dozen of previous similar issues for previous versions that explain the same

**Comment by TigerbyteDev** [comment]
Thank you very much :3

**Comment by TigerbyteDev** [comment]
The first step is already finished by u9g. right?

**Comment by rom1504** [comment]
No, both are incomplete

**Comment by milutinke** [comment]
Hey guys, if haven't figured out all details yet, maybe our discussion in https://github.com/MCCTeam/Minecraft-Console-Client/issues/2053 can help you, we have gone through a lot of research on it and got it working.

**Comment by extremeheat** [comment]
If anyone is interested in this feature please contribute. The open 1.19 PR in node-minecraft-protocol should help handle the protocol side of things.

**Comment by WhatsVape69** [comment]
Is there any update on how soon the update will be

**Comment by SyntheticJay** [comment]
Any progress on this?

**Comment by extremeheat** [comment]
#2743 we need chunk dumps for 1.19 for prismarine-chunk to work

**Comment by rom1504** [comment]
did chunks, next is changing more minor things

**Comment by SyntheticJay** [comment]
how close are we?

**Comment by rom1504** [comment]
If every persons asking contribute 1h of their time to work on it, i think
we are about 5 persons away from release

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/pull/2743 work happening there
It's mostly small fixes now, just need someone to do it

**Comment by ytcalifax** [comment]
Hope that this PR gets finalized soon...

**Comment by ytcalifax** [comment]
Any progress updates?

**Comment by AdminHcat** [comment]
seems to be in trouble?

**Comment by extremeheat** [comment]
We need recipe data in Minecraft data for 1.19

**Comment by Ringo1234ni** [comment]
3 monke want 1.19

**Comment by FelipeAzambuja** [comment]
4 monke want 1.19

**Comment by Andrew-Eathan** [comment]
5 monke want 1.19

**Comment by TigerbyteDev** [comment]
Then the 5 Monke should help for 1.19 👀

**Comment by wujekbobixon** [comment]
I willing to help but i dont have knowlegde about it 🙈

**Comment by Andrew-Eathan** [comment]
5 monke not speak minecraft protocol hieroglyphs, 5 monke only speak
mineflayer

**Comment by TigerbyteDev** [comment]
You could learn it then 🤔. It's all written and explained in the contributing guide.

**Comment by TigerbyteDev** [comment]
You could learn it then 🤔. It's all written and explained in the contributing guide.

**Comment by Ringo1234ni** [comment]
Teach 3 monke Minecraft protocol

**Comment by extremeheat** [comment]
Posting spam here won't make things progress faster. Please consider contributing instead.

**Comment by rom1504** [comment]
pr is there https://github.com/PrismarineJS/mineflayer/pull/2743

current issues are
* something with villager support
* chat fixes to do
* maybe an issue with spawn entity packet

help still welcome, you can discuss at #contribute
