### ISSUE TITLE
A plugin which would allow you to change skin or let us use ely.by account to login

### ISSUE THREAD

**Issue by korrykatti** [PrismarineJS/mineflayer#2670]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
A plugin which would allow us to change skin or let us use other authentication using id and password

## Additional context
And how is the skin of the characters decided ? is it random ?

**Comment by extremeheat** [comment]
You can change account skin at minecraft.net. You can change auth / session servers using the client options documented in https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/API.md (`authServer`, `sessionServer`)
