### ISSUE TITLE
minflayer no work with 1.19

### ISSUE THREAD

**Issue by Soopercooly** [PrismarineJS/mineflayer#2671]
1.19 hmm new update BUTTT!!!!

of course a few bot softwares DIDNT UPDATE their package

AND NOW WE CANT USE ~~MINEFLAYER~~ bruh...

>please FIX

-superfastisfast

**Comment by Soopercooly** [comment]
Who else thinks mineflayer should update to 1.19 🤔

**Comment by extremeheat** [comment]
#2668
