### ISSUE TITLE
How to run a bot in Python through a proxy?

### ISSUE THREAD

**Issue by timof123** [PrismarineJS/mineflayer#2672]
Is it possible to run a bot through a proxy server?  I am writing a bot not in js, but in python.  It is necessary that the bot enter the server under a different ip-address.  How to do it?

**Comment by 1ProCrafters** [comment]
This has a tutorial for usage. https://colab.research.google.com/github/PrismarineJS/mineflayer/blob/master/docs/mineflayer.ipynb

**Comment by SilkePilon** [comment]
can this be reopend?
