### ISSUE TITLE
ForbiddenOperation while logging in

### ISSUE THREAD

**Issue by GGuPP-git** [PrismarineJS/mineflayer#2674]
Error: ForbiddenOperationException
    at call (C:\Users\ematv\OneDrive\Рабочий стол\spamer\node_modules\yggdrasil\src\utils.js:35:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async refresh (C:\Users\ematv\OneDrive\Рабочий стол\spamer\node_modules\yggdrasil\src\Client.js:43:18)

server: 6g6s.xyz a tried use sub-domains(eu.6g6s.xyz, us.6g6s.xyz, mc.6g6s.xyz) but i still have this error

**Comment by amoraschi** [comment]
Can you show your code?

**Comment by GGuPP-git** [comment]
> Can you show your code?

const mineflayer = require('mineflayer')
const config = require('./config.json')

const bot = mineflayer.createBot({
    host: config['host'],
    port: 25565,
    username: config['username'],
    version: '1.12.2'
})

bot.loadPlugin(require('mineflayer-dashboard'))

function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }

async function findShulker() {
    for (let i = 0; i < 9; i++) {
        bot.setQuickBarSlot(i)
        let heldName = bot.heldItem == null ? "kurwa" : bot.heldItem.name
        if (heldName.endsWith('box')) break;     
    }
}

let dupe = false;
let attempts = 0
let check = false

let array = config['whitelist']

bot.on("chat", (username, message) => {
    if (array.includes(username)) {
        if (message == "bots dupe on") {
            dupe = true
        } else if (message == "bots dupe off") dupe = false
        
        if (message.startsWith("say")) {
            bot.chat(message.replace("say", ">[BOT] "))
        }
    }
})

bot.on("time", async () => {

    process.title = "AutoFrameDuper[BOT.NAME: " + bot.username + " : BOT.ATTEMPTS: " + attempts + " : BOT.ITEMNAME: " + (bot.heldItem == null ? "none" : bot.heldItem.name) + "]"

    const entity = bot.nearestEntity()
    let heldName = bot.heldItem == null ? "kurwa" : bot.heldItem.name
    if (entity.name == "item_frame" && dupe) {
        if (!heldName.endsWith('box')) findShulker()
        if (!check && bot.heldItem != null) {
            check = true
            for (let i = 0; i < 5; i++) bot.activateEntity(entity);
            await sleep(235)
            bot.attack(entity)
            attempts += 1
            await sleep(35)
            for (let i = 0; i < 5; i++) bot.activateEntity(entity);
            await sleep(235)
            check = false
        }
    } else if (entity.name != "item_frame" && dupe) {
        await bot.waitForTicks(1500)
        bot.dashboard.log("kurwa nigerska")
    } else return
})

bot.on("login", async () => {
    bot.chat('/login ' + config['password'])
    bot.setQuickBarSlot(0)
    await bot.waitForTicks(120)
    bot.activateItem()
    await bot.waitForTicks(30)
    if (bot.currentWindow != null) { bot.clickWindow(11, 0, 0) }
    if (config['always-on'])  dupe = true
})

**Comment by GGuPP-git** [comment]
i have this error 
![image](https://user-images.githubusercontent.com/86510219/175830326-03b5affb-3933-45af-9a69-e28f28d1167a.png)

**Comment by IceTank** [comment]
Try adding `skipValidation: true` to the bot options. This will skip trying to login with mojang servers when connecting to a offline server.

**Comment by extremeheat** [comment]
Make sure you update all your dependencies, with npm update --depth 9999

It sounds like a problem with your account also, you will probably need to migrate the account to a Microsoft one in order to login.

**Comment by hokindo9000** [comment]
Thanks for the fix
