### ISSUE TITLE
`Auth` isnt valid identifier?

### ISSUE THREAD

**Issue by Nyk0z** [PrismarineJS/mineflayer#2682]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: idk? latest?
 - server: bungeecord
 - node: 18.4.0

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?
Sooo I tried building a bot using a tutorial, then I tried authenticate using microsoft method, and it returns this:
```
SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1040:15)
    at Module._compile (node:internal/modules/cjs/loader:1076:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?
I tried echo example, no result. same error
## Your current code
```js
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'bungee.cord:server', // minecraft server ip
  username: 'MAILGOESHERE', // minecraft username
  password: 'PASSWORDGOESHERE' // minecraft password, comment out if you want to log into online-mode=false servers
  // port: 25565,                // only set if you need a port that isn't 25565
  // version: false,             // only set if you need a specific version or snapshot (ie: "1.8.9" or "1.16.5"), otherwise it's set automatically
  auth: 'microsoft'              // only set if you need microsoft auth, then set this to 'microsoft'
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)

const welcome = () => {
  bot.chat('TEST; If Im able to display this message, then that means Im working. Hi!')
}

bot.once('spawn', welcome)
```

## Expected behavior
A player should join the server and automatically say "TEST; Lorem Ipsum...".

## Additional context
idk, nothing to add

**Comment by extremeheat** [comment]
Syntax error on the password line, which is optional and can be removed. Otherwise you are missing a comma at the end.

**Comment by amoraschi** [comment]
You're missing a "," after the password, also if you're trying to pass the port in the host option, don't, there's a port option for that
