### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'majorVersion')

### ISSUE THREAD

**Issue by 1ProCrafters** [PrismarineJS/mineflayer#2683]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.3.0
 - server: vanilla/spigot/paper 1.18.2
 - node: 16.13.1

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?
I tried readme example. This is straight from readme except string changes

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'localhost', // minecraft server ip
  username: 'bot', // minecraft username
  port: 25565,                // only set if you need a port that isn't 25565
  // version: false,             // only set if you need a specific version or snapshot (ie: "1.8.9" or "1.16.5"), otherwise it's set automatically
  // auth: 'mojang'              // only set if you need microsoft auth, then set this to 'microsoft'
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)

## Expected behavior
Run the bot and get it in Minecraft 
## Additional context
This is straight from the readme, I have had this issue ever since updating to new versions of mineflayer

**Comment by IceTank** [comment]
Run `npm update` and try again. If that does not work post the full error you get.

**Comment by 1ProCrafters** [comment]
Thanks that helped! its fixed now
