### ISSUE TITLE
Error: ForbiddenOperationException

### ISSUE THREAD

**Issue by flightofnoobs** [PrismarineJS/mineflayer#2693]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.3.0
 - server: vanilla/spigot/paper 1.8.9 (Tried on different servers)
 - node: 16.13.2

## Detailed description of a problem
I am trying to log in on a server and it gives me this error right away

## What did you try yet?

tried turning on skipValidation and setting auth to mojang

## Your current code
```js

let BotOptions = {
            host: mccfg.ip,
            username: mccfg.username,
            version: mccfg.version,
            //skipValidation: true,
            //auth: 'mojang'
        }
        if (mccfg.password != "") BotOptions['password'] = mccfg.password

        if (mccfg.port != 25565) BotOptions['port'] = mccfg.port
        console.log(BotOptions)
        bot = mineflayer.createBot(BotOptions)


```

## Expected behavior
Bot being able to join server

## Additional context
the bot can join cracked servers but not premium ones

The credentials are correct. 

Not sure but i think the issue is mojang auth may be removed by microsoft (But you can still login with mojang account using Lunar client)

**Comment by moom0o** [comment]
Same issue, I hope I'm not going to have to migrate my account to microshit.

**Comment by extremeheat** [comment]
Can you use Lunar client to login to the server (online mode)?

**Comment by flightofnoobs** [comment]
> Can you use Lunar client to login to the server (online mode)?

Well not anymore I guess its microsoft disabling mojang accounts

**Comment by extremeheat** [comment]
#2674
