### ISSUE TITLE
1.7.10?

### ISSUE THREAD

**Issue by iocmet** [PrismarineJS/mineflayer#2696]
(I don't think i can fill template, yes my english is really bad)

I really need create bot for 1.7.10 on js but i can't find any library except it, but it not support 1.7.10

**Comment by extremeheat** [comment]
Dupe #432

**Comment by extremeheat** [comment]
As it's not a bug, nobody is currently working on it as it's outside of normal maintenance. If you would like the feature you need to work on it, OSS is very much self service. See the discussion in linked issue if you want to work on it.
