### ISSUE TITLE
NBT documentation unclear

### ISSUE THREAD

**Issue by Plazmaz** [PrismarineJS/mineflayer#270]
The description for item nbt data (https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#itemnbt) is just, "Buffer".

**Comment by rom1504** [comment]
That nbt data is defined in [fromNotch](https://github.com/andrewrk/mineflayer/blob/7890055e1046098487d8ce6ac5ded811813ea7b9/lib/item.js#L50) which is used when [reading set_slot packet](https://github.com/andrewrk/mineflayer/blob/e5b3455b6c433e8d57c93d8e6f579b1e71afc19c/lib/plugins/inventory.js#L412)
That's defined when [reading a slot](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L1140) and in particular when [reading nbt](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L975)

That's done in [prismarine-nbt](https://github.com/PrismarineJS/prismarine-nbt/blob/master/nbt.js#L235)
which doesn't have much documentation and neither does [nbt.js](https://github.com/sjmulder/nbt-js)

Maybe the [wiki page](http://wiki.vg/NBT) would be useful to document how to use that nbt data.

Anyway yes we should document this better, I don't think mineflayer currently use any of that nbt data ?

**Comment by Gjum** [comment]
Setting NBT is relevant for creative slot setting, and for looking if a tool is enchanted. Even though mineflayer itself does not use it currently, it might be a good idea to provide some NBT system that interfaces well with mineflayer, as bot devs certainly will make use of NBT. This does not mean it has to be included in mineflayer, but to be easy to use together with mineflayer.

**Comment by rom1504** [comment]
Yeah sure, actually I think we should probably simply improve the doc of https://github.com/PrismarineJS/prismarine-nbt (or https://github.com/sjmulder/nbt-js) and use that.

**Comment by rom1504** [comment]
issues may go to prismarine nbt
