### ISSUE TITLE
Xcord issue

### ISSUE THREAD

**Issue by ObsidianMC123** [PrismarineJS/mineflayer#2704]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: Xcord #.#.#
 - node: #.#.#

i have issue with xcord when try connect it say checking your minecraft client then kick my bot out can someone help

**Comment by extremeheat** [comment]
Not enough information, please add more information or ask on the Discord (link in the README badge)
