### ISSUE TITLE
How Can I send chat On The Console?

### ISSUE THREAD

**Issue by AlexCode64** [PrismarineJS/mineflayer#2733]
**Does anyone have a code to send messages to the minecraft chat direct from the node console?**

**Comment by amoraschi** [comment]
Yes search in the discussions/issues of this repo this has been asked multiple times already

**Comment by extremeheat** [comment]
https://www.w3schools.com/nodejs/ref_readline.asp +
```js
rl.on('line', line => bot.chat(line))
```
