### ISSUE TITLE
The WindowMenus

### ISSUE THREAD

**Issue by krishnasen2401** [PrismarineJS/mineflayer#2753]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.4.0
 - server: vanilla 1.18.2
 - node: 18.8.0

## Detailed description of a problem
I am trying to reach my skyblock world (Loading terrain message is display before entering) via menu interaction as well as via chat commands 

## What did you try yet?
bot.chat('/game hera') - goes directly to the skyblock world

bot.setQuickBarSlot(0);
bot.activateItem(offhand=false); combo with and without parament - but the window open is not detected by a window!=null or bot.on('windowOpen') both don't detect anything
Did you try any method from the API?
windowOpen

have tried the windowOpen version from https://github.com/PrismarineJS/mineflayer/discussions/2332
Did you try any example? Any error from those?
no
## Your current code
```const mineflayer = require('mineflayer')
const vec3 = require('vec3')
const { mineflayer: mineflayerViewer } = require('prismarine-viewer')
const { pathfinder, Movements, goals: { GoalNear } } = require('mineflayer-pathfinder')
var settings = {
  username: "username",
  host: "mc.herobrine.org",
  version: "1.18.2",   
}
const bot = mineflayer.createBot(settings);

function sleep(ms) {
  return new Promise((resolve) => {
      setTimeout(resolve, ms);
  });
}
bot.on('scoreboardCreated', (scoreboard) => {
  bot.chat(`New scoreboard: ${scoreboard.name}, ${scoreboard.title}`);
  console.log(scoreboard);
})

// kill a mob for this to be displayed
bot.on('scoreboardScoreUpdated', (scoreboard, updated) => {
  bot.chat(`Scoreboard score : ${scoreboard.title}, ${updated.name}, ${updated.value}`);
  console.log('Updated: ' + scoreboard);
})

bot.loadPlugin(pathfinder);

function sayItems (items = bot.inventory.items()) {
  const output = items.map(itemToString).join(', ')
  if (output) {
    console.log(output)
  } else {
    console.log('empty')
  }
}

function itemToString (item) {
  if (item) {
    return `${item.name} x ${item.count}`
  } else {
    return '(nothing)'
  }
}

bot.once("spawn", async () => {
  mineflayerViewer(bot, { port: 3002, firstPerson: true });
  mcData = require('minecraft-data')(bot.version);
  defaultMove = new Movements(bot, mcData);
  console.log('Logging in to Herobrine.org...');
  
  sayItems();
  await sleep(5000);
  console.log('trying game commands check for pickaxe in console');
  bot.chat('/game hera');
  await sleep(10000);
  sayItems();

if (bot.heldItem.type == 795 && bot.heldItem.nbt.value.display.value.Name.value.includes("Quick Select")) {
      console.log("Quick Select")
      if (bot.heldItem.type == 795) {
        console.log("inside while loop");
          bot.setQuickBarSlot(0);
          bot.activateItem(pffhand=false);
          console.log("item activated");
          bot.waitForTicks(20);
          while (bot.currentWindow == null) {
            console.log('window not opened yet')
            bot.setQuickBarSlot(0);
            bot.activateItem();
            await bot.waitForTicks(10);
          }          
          console.log('after window open')
      }
  }
  // menu slot number menu title
  // 14 Quick Select
  // 12 Games
  // 11 Skyblock
});
bot.on('message', msg => {
  console.log(msg.extra[0])
  bot.chat('/pin 1234');
  bot.chat('/game hera');
  })
  
bot.on('chat', (username, message) => {
  console.log(username, message);
  if (username === bot.username) return
  console.log(username, message);
  // bot.inventory.slots
  //     .filter(item => item).forEach((item) => {
  //         bot.chat(stringifyItem(item))
  //     })
});
bot.on('error', (e) => { console.log('Encountered an error: ' + e) });
// 116016 68 58416
//  to
// 116011 68 58416

```

#output
```
# node herobrine.js
ScoreBoard {
  name: 'TAB-Scoreboard',
  title: '§b§lHEROBRINE',
  itemsMap: {}
}
Logging in to Herobrine.org...
compass x 1
Prismarine viewer web server running on *:3002
trying game commands check for pickaxe in console
compass x 1
Quick Select
inside while loop
item activated
window not opened yet
window not opened yet
window not opened yet
window not opened yet
window not opened yet
window not opened yet
window not opened yet
window not opened yet
window not opened yet
window not opened yet
window not opened yet
window not opened yet

```

## Expected behaviour
after selecting menus of in main world join the skyblock

## Additional context
Add a
![2022-08-26_00 51 19](https://user-images.githubusercontent.com/13378434/186824646-e8226a64-c8fb-4dc4-b335-69bd4a45b634.png)

**Comment by krishnasen2401** [comment]
the bot was getting kicked on login before anything happens

`const mineflayer = require('mineflayer')
const vec3 = require('vec3')
const { mineflayer: mineflayerViewer } = require('prismarine-viewer')
const { pathfinder, Movements, goals: { GoalNear } } = require('mineflayer-pathfinder')
var settings = {
  username: "username",
  host: "mc.herobrine.org",
  version: "1.18.2",   
}
const bot = mineflayer.createBot(settings);


bot.on('scoreboardCreated', (scoreboard) => {
  bot.chat(`New scoreboard: ${scoreboard.name}, ${scoreboard.title}`);
  console.log(scoreboard);
})

function sayItems (items = bot.inventory.items()) {
  const output = items.map(itemToString).join(', ')
  if (output) {
    console.log(output)
  } else {
    console.log('empty')
  }
}

function itemToString (item) {
  if (item) {
    return `${item.name} x ${item.count}`
  } else {
    return '(nothing)'
  }
}


bot.once("spawn", async () => {
  mcData = require('minecraft-data')(bot.version);
  defaultMove = new Movements(bot, mcData);
  console.log('Logging in to Herobrine.org...');
sayItems()
});


bot.on('end',reason =>  {
    console.log('bot end',reason);
})

bot.on("kicked", (reason,loggedIN) => {
    console.log("kicked", reason)
    console.log("loggedin",loggedIN)
});
bot.on('message', msg => {
  console.log(message)
  console.log(msg.extra[0])
  bot.chat('/pin 1234');
  bot.chat('/game hera');
  })
  
bot.on('chat', (username, message) => {
  console.log(message);

bot.on('error', (e) => { console.log('Encountered an error: ' + e) });
})
`

### **Output**

```
ScoreBoard {
  name: 'TAB-Scoreboard',
  title: '§b§lHEROBRINE',
  itemsMap: {}
}
Logging in to Herobrine.org...
compass x 1
bot end socketClosed
kicked {"color":"red","translate":"velocity.error.illegal-chat-characters"}
loggedin true
```

**Comment by amoraschi** [comment]
You sending scoreboard data into chat, that probably contains illegal characters such as the color coding

**Comment by krishnasen2401** [comment]
Seems like that was the problem I will try the window code now thanks @amoraschi

**Comment by krishnasen2401** [comment]
@amoraschi  I have changed the code 

```
bot.once("spawn", async () => {
  mineflayerViewer(bot, { port: 3002, firstPerson: true });
  mcData = require('minecraft-data')(bot.version);
  defaultMove = new Movements(bot, mcData);
  console.log('Logging in to Herobrine.org...');
  await sleep(10000);
  if (bot.heldItem.type == 795 && bot.heldItem.nbt.value.display.value.Name.value.includes("Quick Select")) {
    if (bot.heldItem.type == 795) {
      console.log("inside while loop");
        bot.setQuickBarSlot(0);
        bot.activateItem();
        console.log("item activated");
        bot.waitForTicks(20);
        bot.on('windowOpen', (window) => {
            
          if(window.title.includes('Quick Select')){
            
          console.log('window open',window.title)
            bot.clickWindow(14,0,0).then(response =>{
            console.log(response);
            bot.clickWindow(12,0,0).then(response =>{
                console.log(response);
                bot.clickWindow(11,0,0);
                });;
            });
            bot.waitForTicks(60);
            sayItems();
          }
        })
    }
}
});
```

there are 3 pages before I go to the world on clicking the third time it should take me there  but according to the viewer I am still in spawn
![2022-08-26_14 34 17](https://user-images.githubusercontent.com/13378434/186969922-2dba2cf2-b598-4715-a524-232d61c89395.png)
![2022-08-26_14 34 21](https://user-images.githubusercontent.com/13378434/186969926-fe4445ef-c08f-4acc-8b0b-8b4ade35a1d7.png)
![2022-08-26_14 34 26](https://user-images.githubusercontent.com/13378434/186969927-fbfdf023-9470-4edd-8e65-29a708f5036f.png)

**Comment by amoraschi** [comment]
Slots start from 0

**Comment by krishnasen2401** [comment]
@amoraschi  Hi i have to select games,skyblock,hera skyblock is the slot numbers are 14,12,11 right?

**Comment by amoraschi** [comment]
Start counting the slots from 0, the first image shows slot 13; the second, slot 11; the third, slot 10

**Comment by krishnasen2401** [comment]
still the same result 

### **Output**

```
inside while loop
item activated
window open {"text":"Quick Select"}
compass x 1
undefined
undefined
```

as of right now I am using direct command but would like the solve this as well as I intended to right quick sell code when inventory is full
