### ISSUE TITLE
How to clamp the PCM bot?

### ISSUE THREAD

**Issue by VLAADOS1** [PrismarineJS/mineflayer#2763]
Hi, I wanted to ask if it is possible to make it so that the bot clamped the PCM, it clamped and not clicked, it is necessary for afc fishing, since the method with bubbles does not work due to finding a large number of bots nearby

**Comment by VLAADOS1** [comment]
help please

**Comment by amoraschi** [comment]
We do not understand what you mean by "clamp"

Also you can join the Discord server for faster support

**Comment by VLAADOS1** [comment]
I mean by "clamp the PCM bot" The right mouse button is pressed
