### ISSUE TITLE
dig function is undocumented

### ISSUE THREAD

**Issue by Pandapip1** [PrismarineJS/mineflayer#2781]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Detailed description of a problem

The `bot.dig` method is not included in the documentation. This should be fixed.

## Additional context

The `ignore` `forceLook` function should also be documented alongside `bot.dig`

I'm not sure whether this should be submitted as an enhancement or a bug. I suspect someone can recategorize this if I chose the wrong type.

**Comment by amoraschi** [comment]
![IMG_20220929_150554.jpg](https://user-images.githubusercontent.com/68395930/193039235-8fb175e4-1dec-497f-9d7b-dc76edcf3592.jpg)

?

**Comment by Pandapip1** [comment]
Apparently, I'm blind. Sorry!
