### ISSUE TITLE
Check whether rejected transactions are handled properly

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#279]
It's needed for https://github.com/demipixel/shotbow-servers/blob/master/extension.js : 
us.shotbow.net server uses slots in a window as button and when you click it the item isn't taken, and the transaction is rejected.
Apparently mineflayer doesn't react to rejected transactions correctly since the server then doesn't send any other transaction packet (see http://wiki.vg/Protocol#Click_Window)
Also see https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L296

**Comment by rom1504** [comment]
maybe the server doesn't send more than one rejected transaction in a row ?

**Comment by rom1504** [comment]
apparently adding a setTimeout to call the callback if the server doesn't feel like sending a transaction packet does it (it seems to work for @demipixel )

**Comment by roblabla** [comment]
> doesn't feel like sending a transaction packet

... wut ?

**Comment by rom1504** [comment]
Yeah I hope there's a better explanation than that @roblabla ^^

**Comment by rom1504** [comment]
test whether it works or not on vanilla.

**Comment by Gjum** [comment]
Having packet logs for comparison would be useful here.

**Comment by rom1504** [comment]
this issue is too imprecise, closing
