### ISSUE TITLE
How to respawn bot?

### ISSUE THREAD

**Issue by FurnyGo** [PrismarineJS/mineflayer#2799]
Sometimes, when my bot is killed, it can't respawn and sends to the logs "Cannot send chat message".
Maybe there is a way to respawn it?

**Comment by amoraschi** [comment]
The bot should auto respawn, if it's not doing that, maybe there's something blocking the process and slowing down the bot, what's your code?

**Comment by FurnyGo** [comment]
```js
    await bot.once('spawn', ()=> {
        bot.chat("/login "+pass);
        setTimeout(() => {
            bot.chat('/servers');
        }, 400);
    });
    var slot = 12;
    await bot.on('windowOpen', (window) => {
        bot.clickWindow(slot, 1, 0);
        bot.closeWindow(window)
    });
    bot.on('death', ()=> {
        setTimeout(() => {
            bot.chat('/warp testwarp')
        }, 300);
    })
    bot.on('messagestr', (message, messagePosition, jsonMsg)=> {
        if (message.includes("Welcome!")){
            setTimeout(() => {
                    setTimeout(() => {
                        bot.chat('/warp testwarp')
                    }, 150);
            }, 400);
        }
        } 
    })
    bot.on('error', (err)=> {
        bot.quit()
    })
}
```
And it can't respawn after rejoin

**Comment by MrFiend179** [comment]
the thing ur doing wrong is ```bot.on('death', ()=> {
       setTimeout(() => {
           bot.chat('/warp testwarp')
       }, 300);
   })``` bot.on('death') should respawn the bot but it types the chat in the respawn screen causing the bot to stay stuck on that screen try using ```bot.on('spawn', ()=> {bot.chat('/warp testwarp')})``` and on the top u declared that on spawn the bot does the authentication which should be done on ```bot.on('login')``` and a main thing dont use `bot.on` whenever the bot spawns instead use `bot.on('spawn')` its better u can use `bot.once()` when u want to login

**Comment by extremeheat** [comment]
Try removing the /warp on respawn event and see if it works correctly

**Comment by FurnyGo** [comment]
Server has anticheat that prevent respawning in 2 sec after death
So how to respawn bot manually?
