### ISSUE TITLE
bot.dig() not working

### ISSUE THREAD

**Issue by jktechs** [PrismarineJS/mineflayer#2806]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.0
 - server: vanilla 1.19
 - node: 14.17.0

## Detailed description of a problem
The function bot.dig() doesnt seem to work propely. The bot swings his arms but stops before the block is broken and the internal cashe thinks the block has been broken.

## What did you try yet?
I tried the digger.js example but it also didnt work.
what the digger.js code does: [https://youtu.be/r2n3QyjiWz0](https://youtu.be/r2n3QyjiWz0)

## Your current code
The same as the digger.js example

## Expected behavior
The bot should brake the block

## Additional context
when the bot is in creative it also doesnt break the block, but the block does stay in the cashe in contrast to survival were the bot assumes the block is now air.

**Comment by amoraschi** [comment]
What's your code?

**Comment by jktechs** [comment]
it was just spawn protection that i didnt think about and me not searching the open questions well enough
