### ISSUE TITLE
Bot sometimes cannot reconnect

### ISSUE THREAD

**Issue by EnderHacker0** [PrismarineJS/mineflayer#2811]
I've made a bot with prismarine viewer to view my server's spawn on my phone.
Here is my code:
```
const mineflayer = require('mineflayer')
const { mineflayer: mineflayerViewer } = require('prismarine-viewer')
function createBot(){
  const bot = mineflayer.createBot({
    host: 'myserver.address',
    username: 'botusername',
    port: 25565
  })
  bot.once('spawn', ()=>{
    bot.chat('/l password');
    mineflayerViewer(bot, {port: 80, firstPerson: false})
  })
  bot.on('end', function(){
    setTimeout(function() {
      createBot();
    }, 15000);
  })
}
createBot()
```
When I kick the bot with /kick, it reconnects after 15 seconds normally.
But sometimes when it get disconnected it doesn't reconnect.

**Comment by amoraschi** [comment]
It's probably registering too many 'end' events, try changing from `on('end'` to `once('end'`

**Comment by MrFiend179** [comment]
Try it without setTimeout()

**Comment by EnderHacker0** [comment]
> Try it without setTimeout()

It will just wait 15 seconds before reconnecting

**Comment by EnderHacker0** [comment]
> It's probably registering too many `'end'` events, try changing from `on('end'` to `once('end'`

still doesn't work.
Another bug: The viewer sometimes doesn't close when the bot is kicked.
If this happens and the bot reconnects to the server, it will disconnect again and says that the port is already in use

**Comment by MrFiend179** [comment]
> > Try it without setTimeout()
> 
> It will just wait 15 seconds before reconnecting

The reason could be that your bot has a bad ping which causes it to disconnect and in that case it might not reconnect due to bad ping u could instead use `setInterval(()=>{createBot()},500)` It will make the bot reconnect again and again until it joins

**Comment by EnderHacker0** [comment]
> > > Try it without setTimeout()
> > 
> > 
> > It will just wait 15 seconds before reconnecting
> 
> The reason could be that your bot has a bad ping which causes it to disconnect and in that case it might not reconnect due to bad ping u could instead use `setInterval(()=>{createBot()},500)` It will make the bot reconnect again and again until it joins

**Comment by extremeheat** [comment]
Reopen if it's still an issue
