### ISSUE TITLE
Support for pre 1.8 versions

### ISSUE THREAD

**Issue by dark-steveneq** [PrismarineJS/mineflayer#2814]
## Is your feature request related to a problem? Please describe.
I played around with mineflayer for a bit on a local server, and now I want to write some bots to make my life a little bit easier on 1.5.2 server that I'm currently playing on.

## Describe the solution you'd like
Built-in support for older protocol

## Describe alternatives you've considered
1.8- <-> 1.8+ proxy

**Comment by extremeheat** [comment]
https://github.com/PrismarineJS/mineflayer/issues/432
