### ISSUE TITLE
No recipe for redstone torch?

### ISSUE THREAD

**Issue by RodionGromo** [PrismarineJS/mineflayer#2816]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.1
 - server: vanilla 1.12.2
 - node: 19.0.0
 - minecraft-data: 3.16.0

## Detailed description of a problem
I was creating a crafter bot that would craft repeaters from raw materials (redstone dust, logs, stone)
But when I tried to craft redstone torches, the ```bot.recipesAll()``` returned empty array for redstone torch id

## What did you try yet?
I tried reinstalling mineflayer, minecraft-data and updated node

## Your current code
```js
const mineflayer = require("mineflayer")
const mcData = require("minecraft-data")
const bot = mineflayer.createBot()

actualMCData = mcData(bot.version) //bot.version is 1.12.2
console.log(bot.recipesAll(actualMCData.itemsByName.redstone_torch.id))
// actualMCData.itemsByName.redstone_torch.id returns id of redstone torch
// but bot.recipesAll returns empty array
```

## Expected behavior
To recieve Recipe for redstone torch

## Additional context
none

**Comment by MightyPiggie** [comment]
Could it maybe be that you're using the itemsByName instead of the itemsById since you're using the id of the redstone torch?

**Comment by RodionGromo** [comment]
I doubt it. `bot.recipesAll()` requires numerical id, which `actualMCData.itemsByName.redstone_torch.id` already returns.

**Comment by MightyPiggie** [comment]
You were right. However I found why it goes wrong. 

You get the id 76 back which is the redstone torch id. However to be precise its the id for the active redstone torch:
`{
    "id": 76,
    "displayName": "Redstone Torch (active)",
    "name": "redstone_torch",
    "stackSize": 64
  },`

However the itemsByName has no recipe for id 76, but it has a recipe for id 75 which is for the inactive redstone torch:

`{
    "id": 75,
    "displayName": "Redstone Torch (inactive)",
    "name": "unlit_redstone_torch",
    "stackSize": 64
  },`

And here is the recipe for 75.
  
  ` "75": [
    {
      "inShape": [
        [
          331
        ],
        [
          280
        ]
      ],
      "result": {
        "count": 1,
        "id": 75,
        "metadata": 0
      }
    }
  ],`

When I do 
`console.log(bot.recipesAll(actualMCData.itemsByName.redstone_torch.id-1))` it works fine for me.

**Comment by RodionGromo** [comment]
Oh, right! I figured `itemsByName` won't give me any block id's (especially something like active redstone torch) , so I haven't thought about that. Thank you!
