### ISSUE TITLE
multiplayer.disconnect.invalid_public_key on connect

### ISSUE THREAD

**Issue by xailisse** [PrismarineJS/mineflayer#2827]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.1
 - server: Velocity 1.7.2 - 1.19.2 (but if I connect with a version < 1.19.2, server kicks me for Outdated client
 - node: 16.17.0

## Detailed description of a problem
When I try to connect to a server, I have this error :
`connected !
{"translate":"multiplayer.disconnect.invalid_public_key"} false`
My Microsoft account has 2 way auth disabled and is working with MultiMMC

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
```js
const mineflayer = require('mineflayer')

var bot = mineflayer.createBot({
  host: "host.comr",
  version: "1.19.2",
  username: "MyWorkingMicrosoftAccount@hotmail.com",
  password:"MyWorkingPassword",
  verbose: true,
  auth: 'microsoft'
});

bot.on('connect', function(packet) {
  console.log('connected !');
});

bot.on('kicked', console.log)
bot.on('error', console.log)
```

## Expected behavior
A bot that can connect to a server

**Comment by extremeheat** [comment]
1.19.2 is not currently supported. See the PRs in node Minecraft protocol if you would like to contribute.

**Comment by extremeheat** [comment]
#2797
