### ISSUE TITLE
AntiBot problem

### ISSUE THREAD

**Issue by cmetanamaker** [PrismarineJS/mineflayer#2831]
I want to make a bot,but there is antibot on the server and i got problem.The player just needs to fall,but server kick bot.How can I make the bot fall?

**Comment by amoraschi** [comment]
Apply g = GM/r^2

**Comment by matteopolak** [comment]
Physics are enabled by default. If you disabled internal plugins with `BotOptions#loadInternalPlugins`, either enable the physics plugin manually, or enable internal plugins. If those aren't disabled, make sure you didn't disable physics with `Bot#physicsEnabled` (it should be `true`, which is the default).

If all of those requirements are met, please post an MRE (minimal, reproducible example).
