### ISSUE TITLE
counts of inventory

### ISSUE THREAD

**Issue by Lyh0yh** [PrismarineJS/mineflayer#2834]
## Is your feature request related to a problem? Please describe.
I'd like to do a test on the quantity of items in my inventory.
For example, when the wheat in my backpack reaches 640, I will do it once.
## Describe the solution you'd like
any

## Describe alternatives you've considered
I'm sorry, my JS level is low and my English is poor, which is a little difficult for me.
```
function ss () {
  const dropitem = ['wheat']
   const itema = bot.inventory.items().find(item => dropitem.count(item.count))
   if(itema => 640){
      bot.chat('有')}
   else{
      bot.chat('无')
   }}
```
## Additional context
My English and JS level is not very good, so I can't understand some things. I hope I can answer them in as much detail as possible. Thank you very much.I'm sorry,

**Comment by Pix3lPirat3** [comment]
Get all the items in your inventory matching wheat, then loop through the item.count and assign that total number of item.count to a variable

**Comment by extremeheat** [comment]
You're looking for the [.reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) function on JS Array's, which can be used to count.

Try
```js
const countOfWheat = bot.inventory.items().reduce((acc, cur) => {
  if (cur.name.includes('wheat')) return acc + 1 // increment accumulated value by one if we found a wheat
  return acc // continue...
}, 0)
```

or inline,
```js
const countOfWheat = bot.inventory.items().reduce((acc, cur) => cur.name.includes('wheat') ? (acc + 1) : acc, 0)
```
