### ISSUE TITLE
JSON.parse crash in chat.js due to packet.senderName being undefined

### ISSUE THREAD

**Issue by redbandithero** [PrismarineJS/mineflayer#2837]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 1.0.0
 - server: spigot 1.19.2
 - node: 18.12.1

## Detailed description of a problem
SyntaxError: Unexpected token u in JSON at position 0
On line 135 of chat.js in \node_modules\mineflayer\lib\plugins\chat.js packet.senderName is parsed into JSON unsuccessfully, this is due to packet.senderName being "undefined".

I am not currently using any chat methods in my index.js but the bot crashes immediately after anyone chats on the server.

## What did you try yet?

I have tried modifying the packet.senderName to contain curly brackets at the beginning and end while also using the real sender's username provided by "const sender = bot.uuidToUsername[packet.senderUuid]" on line 129 of chat.js.

## Your current code
```js

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
    host: '***',
    port: 25565,
    username: 'ServerBot'
})

```

## Expected behavior
The bot is expected to have no response to chat messages.

## Additional context
I have tried running the bot on multiple different versions of node and different machines with no success.

![image_2022-11-21_160604950](https://user-images.githubusercontent.com/72537818/202969791-c76208bf-eec0-4c77-866b-92dce308b979.png)

Ingame Example:
https://streamable.com/og9byr

**Comment by redbandithero** [comment]
Just tested putting in a predetermined input for the problem and it made it work slightly, enough to atleast get to the other problem which is the very next line of chat.js.

The first problem can be fixed (to my knowledge) by just using that new variable and removing the JSON.parse.
The second instance of the problem doesn't appear to have any alternative variables.
![image](https://user-images.githubusercontent.com/72537818/202973644-0a0cdae6-75d1-4a83-8ae1-43a29affec5d.png)

**Comment by redbandithero** [comment]
> ... doesn't appear to have any alternative variables. 

Current solution is to just replace it with a empty string, solves the crash but means the bot cannot read chat at all.
If anyone has a better solution (which is very likely), then please tell me as I would like the bot to have access to chat.

**Comment by amoraschi** [comment]
1.19.2 isn't supported yet

**Comment by extremeheat** [comment]
#2797
