### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by MuhammadRestu999** [PrismarineJS/mineflayer#2838]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.1
 - server: vanilla 1.19.41
 - node: v18.12.1

## Detailed description of a problem
I'm trying to build a Minecraft bot
i am getting an ECONNREFUSED error
but I can access it using my Minecraft
I used [this](https://www.minecraft.net/en-us/download/server/bedrock) to create the Minecraft server

## Your current code
```js
const mineflayer = require("mineflayer");

const bot = mineflayer.createBot({
  host: "xx.xxx.xxx.xxx",
  port: 19132,
  username: "xxxx"
})
```

## Expected behavior
The bot has successfully connected to the server

**Comment by tupini07** [comment]
I see you're trying to use a Bedrock server, but if I'm not mistaken minflayer is made for Minecraft Java edition, not Bedrock. See #842 for related issue about supporting Bedrock.

**Comment by MuhammadRestu999** [comment]
> 

Okay thank you
