### ISSUE TITLE
Invalid Public Key Signature

### ISSUE THREAD

**Issue by almog-co** [PrismarineJS/mineflayer#2840]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.1
 - server: unknown
 - node: v18.11.0

## Detailed description of a problem
I am trying to connect a bot to a server using the Microsoft authentication method. However, the bot is immediately kicked due to an error message in the console: `{"translate":"multiplayer.disconnect.invalid_public_key_signature"} false`. I found I can login fine on some servers and not others. I have yet to figure out which server software they are running that causes this error.

## What did you try yet?
I verified this error only occurs on some servers. At first I thought it might be an issue with using domain names and not straight IPs, but that was quickly ruled out.

## Your current code
```js
const mineflayer = require('mineflayer')


const bot = mineflayer.createBot({
  host: '127.0.0.1', // minecraft server ip
  port: 25565,
  username: 'microsoftemail@email.com', // minecraft username
  auth: 'microsoft'              // only set if you need microsoft auth, then set this to 'microsoft'
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)
```

## Expected behavior
Bot connects to server

**Comment by extremeheat** [comment]
on 1.19.2?

**Comment by almog-co** [comment]
> 

Yes, 1.19.2

**Comment by extremeheat** [comment]
dupe #2797
