### ISSUE TITLE
Missing args on bot spawn

### ISSUE THREAD

**Issue by frisby-ninja** [PrismarineJS/mineflayer#2848]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 1.0.0
 - server: vanilla 1.19.2
 - node: 16.14.0

## Detailed description of a problem
I'm trying to build a modular bot setup. This entails me having to declare the spawn settings (like server and port) in another file (settings.json). I currently have two scripts (in JavaScript) :
Main.mjs (for executing commands from the terminal), and
Spawner.mjs (for spawning a bot on command).
 

## What did you try so far?

I tried to put the spawn settings inside of the "Spawner.mjs" file, but the issue persisted. I then tried copy+pasting the tutorial bot spawning code. Same thing.

## Your current code
Main.mjs  : 
```js

import { spawnBot } from './Spawner.mjs';

"use strict";

import ps from 'prompt-sync'
const prompt = ps();

const bot = spawnBot();
loop();

function loop() {

    let input = prompt("<Bot Console> ");
    const inputArray = input.split(" ");
    if(inputArray[0] === "get") {
        if(inputArray[1])
        console.log(FileReader.readFile());
    } else if (inputArray[0]=== "exit") {
        console.log(`Exited!`)
    } else {
        console.log(`Command '${inputArray[0]}' not found.`);
        loop();
    }
}



```

Spawner.mjs : 
```js

import pkg from 'mineflayer';
const mineflayer = pkg;
import fs from 'fs';
import path from 'path';
const settings = JSON.parse(fs.readFileSync('./settings.json', 'utf8'));

const shost = settings.host;
const sport = settings.port;
const name = settings.prefix;

const options = {
    username: name,
    host: shost,
    port: sport,
};

export function spawnBot() {
        const bot1 = mineflayer.createBot({
            host: shost,
            port: sport,
            username: name,
            password: 'xd195'
          });
        return bot1;
}


```

Error log (from executing "node Main.mjs" in terminal) : 
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_MISSING_ARGS]: The "options" or "port" or "path" argument must be specified
t\tcp_dns.js:41:30)
    at Object.createClient (C:\Users\Bienvenue\node_modules\minecraft-protocol\src\createClient.js:51:17)
    at Object.createBot (C:\Users\Bienvenue\node_modules\mineflayer\lib\loader.js:94:35)
    at spawnBot (file:///C:/Users/Bienvenue/Documents/MC%20developpement/Mineflayer/NinjaBots/Spawner.mjs:18:33)
    at file:///C:/Users/Bienvenue/Documents/MC%20developpement/Mineflayer/NinjaBots/Main.mjs:8:13
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0) {
  code: 'ERR_MISSING_ARGS'
}
## Expected behavior
What should happen is : 
1. A bot spawns
2. The "Main.mjs" bring up a fake 'Bot Console'
3. I'm now able to execute any command that I program in by detecting the first argument

## Additional context
I use VSCode.

**Comment by amoraschi** [comment]
mineflayer doesn't support 1.19.2

Are you checking that it's reading settings.json correctly?

**Comment by extremeheat** [comment]
Your error is due to host / port arguments you're passing to createBot/createClient are undefined
