### ISSUE TITLE
Drop all itens in inventory

### ISSUE THREAD

**Issue by ruizaoo** [PrismarineJS/mineflayer#2856]
## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper 1.8.9
 - node: #.#.#

## Detailed description of a problem
I'm trying to make bots drop all inventory items using a discord command, but the bot only drops one item and crashes

## Current code
```js

/*
else if (message.content.startsWith('+drop')) {
let split = message.content.split(' ')
if (split[1] == bot.username || split[1] == 'all') {
channel.send(Dropping Items: ${username})
for (item of bot.inventory.items()) {
bot.tossStack(item);
await utils.sleep(3000);
}
return;
}
}
*/


```

**Comment by extremeheat** [comment]
You can join the Discord for questions like this. This is a duplicate question to the one opened in https://github.com/PrismarineJS/mineflayer/issues/1241.

**Comment by ruizaoo** [comment]
Normal items worked normally, but when the bot has enchanted items in inventory, it drops one and crashes.
