### ISSUE TITLE
Can't see the chat

### ISSUE THREAD

**Issue by Choneas** [PrismarineJS/mineflayer#2858]
## Versions
 - mineflayer: npm version 4.5.1
 - server: paper 
 - node: 16.18.1

## Detailed description of a problem
I am building chat receiver but itz not working.

## What did you try yet?
Did you try any method from the API? [ansi](https://github.com/PrismarineJS/mineflayer/blob/master/examples/ansi.js)
Did you try any example? Any error from those? Yes. Yes.

## Your current code
```js
const mineflayer = require('mineflayer') 
function bot(){
    const bot = mineflayer.createBot({
        host: host,
        port: port,
        username: username
    }) 
    
    const { mineflayer: mineflayerViewer } = require('prismarine-viewer')
        bot.once('spawn', () => {
            bot.chat("/server server");
            /* AND I CAN 'T CHAT UNDER THIS CODE AFTER*/
            mineflayerViewer(bot, { port: 3007, firstPerson: false })
    })

    bot.on('message', (message) => {
        console.log(message.toAnsi())
      })

    bot.once("kicked", ()=>{
        console.log('[ERROR] Bot has been kicked or have a error! restarting...');
        bot();})
    bot.once("error", ()=>{
        console.log('[ERROR] Bot has been kicked or have a error! restarting...');
        bot();
});
};

bot();
```

## Expected behavior
Bot can't give me chat information.

**Comment by amoraschi** [comment]
This doesn't really give information, what's your error? What's the server version? 1.19.2 isn't supported yet

**Comment by AshDoesStuf** [comment]
Does bot acutally join the game?

**Comment by ShiniPantz** [comment]
your code works fine for me

**Comment by Zakarya1000** [comment]
Ah, I see the problem. The event is not "message", it's "chat".

`bot.on('chat', (message) => {
   console.log(message.toAnsi())
})`

**Comment by extremeheat** [comment]
Reopen if you have more information
