### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by ozanbaskan** [PrismarineJS/mineflayer#2860]
## Describe the solution you'd like
Is it possible to add support for protocol version 761?

## Additional context
I can create a PR if someone gives me insight about how to implement it.

**Comment by rom1504** [comment]
Blocked by https://github.com/PrismarineJS/node-minecraft-protocol/issues/1046

**Comment by ozanbaskan** [comment]
[This](https://github.com/MrKinau/FishingBot/tree/1.19.3) might be helpful.

**Comment by rom1504** [comment]
done
