### ISSUE TITLE
Fabric support

### ISSUE THREAD

**Issue by AudioAD** [PrismarineJS/mineflayer#2867]
Already have support Forge can add more support Fabric??

**Comment by WhoTho** [comment]
Mineflayer doesn't support forge and it won't support fabric unless someone adds support.

All mineflayer can do at the moment is send a fake mods packet to a forge server saying that it has the required mods, while it actually doesn't.

I imagine something similar can be added for fabric servers but actually supporting the custom mods and incorporating the logic and functions in them is practically impossible (given the mods are written in Java and mineflayer is in JavaScript)

**Comment by frej4189** [comment]
> Mineflayer doesn't support forge and it won't support fabric unless someone adds support.
> 
> All mineflayer can do at the moment is send a fake mods packet to a forge server saying that it has the required mods, while it actually doesn't.
> 
> I imagine something similar can be added for fabric servers but actually supporting the custom mods and incorporating the logic and functions in them is practically impossible (given the mods are written in Java and mineflayer is in JavaScript)

It can definitely be done (by manually defining protocol differences for individual mods), but it is definitely not a job for mineflayer.

**Comment by GleammerRay** [comment]
> Mineflayer doesn't support forge

From what I read at https://github.com/PrismarineJS/mineflayer/issues/2321, Forge is supported at https://github.com/PrismarineJS/node-minecraft-protocol-forge
