### ISSUE TITLE
cannot find module ::998

### ISSUE THREAD

**Issue by Sigmaa0** [PrismarineJS/mineflayer#2869]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: download today so the curent version
 - server: vanilla/spigot/paper none
 - node: 18.12.1

## Detailed description of a problem

When i would download navigate so:
`npm i mineflayer-navigate` or `npm i mineflayer-pathfinder`
that doesn't work.

## What did you try yet?

cmd say : 

`C:\Program Files\nodejs>npm i mineflayer-navigate
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\i'
←[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:841:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:23:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

Node.js v18.12.1`

**Comment by frej4189** [comment]
You are writing `node i` and not `npm i`

**Comment by Sigmaa0** [comment]
no i write npm i

**Comment by Sigmaa0** [comment]
its just a little error i test `npm i mineflayer-navigate` i test this command 1000 time

**Comment by frej4189** [comment]
> no i write npm i

In the snippet you provided, you typed `node i mineflayer-navigate`

**Comment by Sigmaa0** [comment]
yes

**Comment by AnyBananaGAME** [comment]
Try to reinstall NodeJS then

**Comment by Sigmaa0** [comment]
i testing all command

**Comment by Sigmaa0** [comment]
i try 2 time and i go try another time

**Comment by frej4189** [comment]
> i testing all command

Provide a snippet where you type `npm i mineflayer-navigate` instead

**Comment by Sigmaa0** [comment]
i update my comment

**Comment by Sigmaa0** [comment]
and i test npm i, node npm, sudo npm i, sudo node npm i

**Comment by AnyBananaGAME** [comment]
> i update my comment

Try yo reinstall NodeJS on ur machine

**Comment by Sigmaa0** [comment]
yes i go reinstall

**Comment by Sigmaa0** [comment]
i choose LTS 18.12.1 ?

**Comment by Sigmaa0** [comment]
or the current version ?

**Comment by AnyBananaGAME** [comment]
Download the recommended one

**Comment by AnyBananaGAME** [comment]
> Can you provide a screenshot of your Shell where you wrote that command?

Maybe his download was corrupted and the install cmd didn't exist?

**Comment by Sigmaa0** [comment]
[frej4189] i write your command one hundred time today and yesterday

**Comment by Sigmaa0** [comment]
okay i download the current version

**Comment by frej4189** [comment]
> Maybe his download was corrupted and the install cmd didn't exist?

That error will never be thrown by npm.

**Comment by AnyBananaGAME** [comment]
> > Maybe his download was corrupted and the install cmd didn't exist?
> 
> That error will never be thrown by npm. 

I do get the similar error if i do "node i anything" but if he's doing `npm i` and grtting that error he would need to reinstall node with npm

**Comment by Sigmaa0** [comment]
![image](https://user-images.githubusercontent.com/92261648/208418662-87a9d4ba-8e46-4e25-ab1b-722719aa785d.png)

**Comment by Sigmaa0** [comment]
i take it ?

**Comment by AnyBananaGAME** [comment]
Yes select that

**Comment by frej4189** [comment]
> > > Maybe his download was corrupted and the install cmd didn't exist?
> > 
> > 
> > That error will never be thrown by npm.
> 
> I do get the similar error if i do "node i anything" but if he's doing `npm i` and grtting that error he would need to reinstall node with npm

I am usually not one for assuming, but something tells me he is not getting that error from `npm i`

**Comment by AnyBananaGAME** [comment]
> > > > Maybe his download was corrupted and the install cmd didn't exist?
> > > 
> > > 
> > > That error will never be thrown by npm.
> > 
> > I do get the similar error if i do "node i anything" but if he's doing `npm i` and grtting that error he would need to reinstall node with npm
> 
> I am usually not one for assuming, but something tells me he is not getting that error from `npm i`
> 

Maybe he was messing with node paths?

**Comment by Sigmaa0** [comment]
![image](https://user-images.githubusercontent.com/92261648/208418921-31656d61-11ad-4edb-8f89-b6f45ea65809.png)

**Comment by frej4189** [comment]
> Maybe he was messing with node paths?

Sure - and renamed the node binary?

**Comment by Sigmaa0** [comment]
i write my email

**Comment by Sigmaa0** [comment]
here ?

**Comment by Sigmaa0** [comment]
![image](https://user-images.githubusercontent.com/92261648/208419050-7533e9f9-ebe2-4859-925a-889cd73f0d73.png)

**Comment by Sigmaa0** [comment]
when i write my pseudonym that doesn't work but my email work

**Comment by AnyBananaGAME** [comment]
Once you reinstall try to install it again

**Comment by Sigmaa0** [comment]
what why ???

**Comment by AnyBananaGAME** [comment]
And use 
```js
npm i
```

**Comment by Sigmaa0** [comment]
i can't create a cmd.bat raaaa

**Comment by AnyBananaGAME** [comment]
> i can't create a cmd.bat raaaa

Wdym

**Comment by AnyBananaGAME** [comment]
Dont tell me ur using notepad or something
