### ISSUE TITLE
Message-Event - pos is undefined instead of "system"

### ISSUE THREAD

**Issue by CobbleShop** [PrismarineJS/mineflayer#2905]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.7.0
 - server: vanilla/spigot/paper 1.8.9
 - node: 16.3.2

## Detailed description of a problem
On previous builds the "pos"-variable in the message-event used to be "system" for all the server-related messages. However since 4.7.0 it's "undefined"

## Your current code
```js

bot.on("message", (message, pos) => {
    var msg = message.toString()
    let showping = currentCB
    console.log(`[` + ` ${showping} `.green + `] [` + `${pos}`.red + `] ` + placeholder + `[ ${currentTime()} ] ${message.toAnsi()}`)
    }
  })
```

## Expected behavior
Server's "system" messages should be pos = 'system' , but are 'undefined' instead.

**Comment by extremeheat** [comment]
Likely a bug here -- https://github.com/PrismarineJS/mineflayer/blob/6e74ad32c4b71fe810e5d9e1b5ab38142735c7d6/lib/plugins/chat.js#L151

**Comment by frej4189** [comment]
Probably a bug in node-minecraft-protocol

**Comment by frej4189** [comment]
Actually not. positionid is just meant to be camel case
