### ISSUE TITLE
Can a block from hand be placed

### ISSUE THREAD

**Issue by Faromi** [PrismarineJS/mineflayer#2917]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.8.0
 - server: vanilla 1.16.5
 - node: 16.15.1

## Detailed description of a problem
I want to know what kind of item the bot is holding in its hand, because if you call blockPlace not on a block, the bot will crash and give an error (No block has been placed : the block is still air)

## What did you try yet?
I tried to find the item type via bot.heldItem but it doesn't return this information.

## Your current code
```js

const mineflayer = require('mineflayer');
const { pathfinder, Movements, GoalBlock } = require('mineflayer-pathfinder')
const { Vec3 } = require('vec3');
const { RaycastIterator } = require('prismarine-world').iterators;

const bot = mineflayer.createBot({
    host: 'localhost',
    port: 10000,
    username: 'Bot'
})

bot.once('login', () => {
    bot.loadPlugin(pathfinder);
    const mcData = require('minecraft-data')(bot.version);
    const movements = new Movements(bot, mcData);
    bot.pathfinder.setMovements(movements);
});

bot.once('spawn', () => {
    console.log('Bot spawned');
});


function visibleBlock() {
    function getViewDirection(pitch, yaw) {
        const csPitch = Math.cos(pitch);
        const snPitch = Math.sin(pitch);
        const csYaw = Math.cos(yaw);
        const snYaw = Math.sin(yaw);
        return new Vec3(-snYaw * csPitch, snPitch, -csYaw * csPitch);
    };

    bot.blockAtCursorCustom = (maxDistance = 5) => {
        let { position, height, pitch, yaw } = bot.entity;

        const eyePosition = position.offset(0, height, 0);
        const viewDirection = getViewDirection(pitch, yaw);

        const iter = new RaycastIterator(eyePosition, viewDirection, maxDistance);
        let pos = iter.next();
        while (pos) {
            const block = bot.blockAt(new Vec3(pos.x, pos.y, pos.z));
            // TODO: Check boundingBox of block
            if (block && block.type !== 0) {
                block.face = pos.face; // <<<<<<<<<<< Here is the added line
                return block;
            };
            pos = iter.next();
        };
        return null;
    };

    const block = bot.blockAtCursorCustom();
    return block;
};

const faceToDirection = [
    new Vec3(0, -1, 0), // BOTTOM
    new Vec3(0, 1, 0), // TOP
    new Vec3(0, 0, -1), // NORTH
    new Vec3(0, 0, 1), // SOUTH
    new Vec3(-1, 0, 0), // WEST
    new Vec3(1, 0, 0), // EAST
];

bot.on('chat', (username, message) => {
    if (username === bot.username) return;

    if (message == 'place') {
        if (bot.heldItem) {
            if (bot.heldItem.nbt && bot.heldItem.nbt.value && bot.heldItem.nbt.value.Damage || bot.heldItem.stackSize < 64) {
                console.log('Unable to place; a block in your hand cannot be placed, or is not a block at all');
            } else {
                const block = visibleBlock();
                if (block) {
                    const face = block.face;
                    const dir = faceToDirection[face];
                    bot.placeBlock(block, dir);
                } else {
                    console.log('Block is not defined');
                };
            };
        } else {
            console.log('The bot does not have a block that can be placed');
        };
    };
});

console.log('Script started');



```

## Expected behavior
I'd like to know what kind of item I'm holding (block, food, armor, etc.).

## Additional context
Not all items in the game can be placed, such as armor, food, and more. How can I find out?

**Comment by extremeheat** [comment]
> I tried to find the item type via bot.heldItem but it doesn't return this information.

What does it return? Can you log it to the console?

**Comment by Faromi** [comment]
> > I tried to find the item type via bot.heldItem but it doesn't return this information.
> 
> What does it return? Can you log it to the console?

![image](https://user-images.githubusercontent.com/123885122/215992031-5eec8c58-a6b9-41a0-a268-95fdc2ceed5e.png)


> 
> If you want a classification from item name, you'll need to store a map of this yourself as I don't believe we have the information in minecraft data.

See, there are two ways to solve this problem. If it's not possible to get an item's classification from bot.heldItem, then yes, you can make your own. But there is a completely different solution, this is a change in the principle of operation of bot.placeblock, because if the character is not holding a block, but something else, then it crashes the entire script. I think it's possible to return some error to the mineflayer user so that it can be handled. In pathfinder, the goto method returns an error if the specified coordinates could not be reached (code example below).

```js
bot.pathfinder.goto(new GoalNear(x, y, z, 0))
    .then(() => {
        console.log('The bot has successfully reached the specified coordinates');
    })
    .catch(() => {
        console.log('The bot cannot reach the specified coordinates');
    });
```

**Comment by Faromi** [comment]
> > If you want a classification from item name, you'll need to store a map of this yourself as I don't believe we have the information in minecraft data.
> 
> See, there are two ways to solve this problem. If it's not possible to get an item's classification from bot.heldItem, then yes, you can make your own. But there is a completely different solution, this is a change in the principle of operation of bot.placeblock, because if the character is not holding a block, but something else, then it crashes the entire script. I think it's possible to return some error to the mineflayer user so that it can be handled. In pathfinder, the goto method returns an error if the specified coordinates could not be reached (code example below).
> 
> ```js
> bot.pathfinder.goto(new GoalNear(x, y, z, 0))
>     .then(() => {
>         console.log('The bot has successfully reached the specified coordinates');
>     })
>     .catch(() => {
>         console.log('The bot cannot reach the specified coordinates');
>     });
> ```

I'm sorry, the second way of the solution turned out to be workable. Topic closed.

**Comment by Faromi** [comment]
Sorry for the inconvenience, the topic is closed.
