### ISSUE TITLE
Chat verification

### ISSUE THREAD

**Issue by Symmettry** [PrismarineJS/mineflayer#2946]
## Is your feature request related to a problem? Please describe.

Problem: Servers that require chat verification (1.19.2 chat) don't allow the mineflayer bot to be able to chat.

## Describe the solution you'd like

Solution: Verified chat messages

**Comment by extremeheat** [comment]
Did you update your dependencies? 

With `npm update --depth 9999`

**Comment by Symmettry** [comment]
I will try that, thanks.

**Comment by Symmettry** [comment]
It worked, idk why it wasn't earlier, lmao

**Comment by Symmettry** [comment]
Hmm.. it appears to not work some of the time. Every few log-ins the chat works, and other times it doesn't. Don't know if this is mineflayer or the server.

**Comment by extremeheat** [comment]
cc @frej4189

**Comment by frej4189** [comment]
> Hmm.. it appears to not work some of the time. Every few log-ins the chat works, and other times it doesn't. Don't know if this is mineflayer or the server.

Test it in Vanilla minecraft

**Comment by frej4189** [comment]
What do you mean doesn't work? Does it just not send any messages, or do you get kicked?

**Comment by Symmettry** [comment]
Basically, the bot joins a server (minehut.com) and i make it try sending a message via discord-irc. it gives me a message saying i have to be on latest or not have mods like no chat reports (cuz of signing), but other times the message sends to the server. Idk if this is minehut or mineflayer.

**Comment by frej4189** [comment]
Use 1.19.3 instead

**Comment by Symmettry** [comment]
i am using 1.19.3

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'minehut.com',
  username: '##########################'
  auth: 'microsoft',
  version: "1.19.3"
});

**Comment by frej4189** [comment]
And you are waiting some time before sending chat messages?

**Comment by Symmettry** [comment]
Yeah like a few seconds after the join messages are sent to the bot. I'll try waiting longer. Also if i send messages even minutes later they also don't work.

**Comment by extremeheat** [comment]
Does this happen with 1.19.2?

**Comment by PitPot1** [comment]
Same issue here, the server prevents any versions other than 1.19.3 from sending chat messages. But the mineflayer bot is not able to send messages even on 1.19.3. This bug does not occur when sending a message on the server from a vanilla client.

**Comment by frej4189** [comment]
Currently this issue seems specific to the Minehut server. 

The only noticeable difference between Vanilla client and Mineflayer chat packet is the lack of a signature in Vanilla when server does not enforce secure chat. Mirroring this in Mineflayer does not solve the issue, and thus it appears Minehut's version evaluation is context-based and not based on the chat packets

**Comment by Symmettry** [comment]
So is there any way to fix this or no

**Comment by rom1504** [comment]
Yes, go ahead

**Comment by Symmettry** [comment]
what

**Comment by PitPot1** [comment]
@frej4189 What kind of context do you mean? is there a packet i could alter or send to appear like a vanilla client ? Or is it something that mineflayer does that makes it detected as a non vanilla client.
I would really appreciate it if you could help me with this.

**Comment by frej4189** [comment]
If I knew exactly what was wrong I would have fixed it.
