### ISSUE TITLE
Property bot.usingHeldItem missing from index.d.ts Bot's interface

### ISSUE THREAD

**Issue by tomas-kucera** [PrismarineJS/mineflayer#2951]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 8.4.1
 - server: vanilla
 - node: 18.13.0

## Detailed description of a problem
Using TS to code eating behavior of the bot and wanted to check whether the bot finished eating using bot.usingHeldItem and found that the interface is missing this definition.

## What did you try yet?
I added
```ts
usingHeldItem: boolean
```
on line 193 of index.d.ts, which seems to fix the issue.

## Your current code
```ts
if (bot.usingHeldItem) {  }
```

## Expected behavior
To return true/false depending on whether the bot is using the held item or not.

## Additional context
none

**Comment by extremeheat** [comment]
Open for PR
