### ISSUE TITLE
Chat kick issue

### ISSUE THREAD

**Issue by PitPot1** [PrismarineJS/mineflayer#2953]
## Versions
 - mineflayer: 4.8.1
 - server: velocity
 - node: #.#.#

## Detailed description of a problem
NOTE: The server is Minehut.com
Bot gets kicked for "Chat message validation failure" or "Received chat packet with missing or invalid signature." when sending a message that gets edited by the server (using the /ad command). Sending normal chat messages works fine but as soon as you run the /ad command you get kicked and all your chat messages after that get you kicked aswell.

## What did you try yet?

My bot version is on 1.19.3 (the required version to chat on the server).
I have the latest Mineflayer version.

## Expected behavior
The message goes thru and the bot dosen't get kicked.

**Comment by frej4189** [comment]
Known issue of NMP. Addressed in https://github.com/PrismarineJS/node-minecraft-protocol/pull/1067

**Comment by extremeheat** [comment]
Update with `npm update --depth 9999`

If you have updated and it's still happening please reopen.
