### ISSUE TITLE
Adding bot.container.name() / Any alternatives?

### ISSUE THREAD

**Issue by Natsume1990** [PrismarineJS/mineflayer#2957]
Hi, i'm having trouble with obtaining name of container. Basically when you open an chest there is name in top left. Is it possible to somehow get name of current container or maybe will be possible in near future?
![image](https://user-images.githubusercontent.com/123188832/220969083-0e096113-7dc7-4ae1-b534-9cfea280ff96.png)

**Comment by KTibow** [comment]
https://github.com/PrismarineJS/prismarine-windows/blob/master/API.md#windowtitle

**Comment by Natsume1990** [comment]
> https://github.com/PrismarineJS/prismarine-windows/blob/master/API.md#windowtitle

God damn i was looking through api for hour straight and didn't found that, my bad.

**Comment by extremeheat** [comment]
Yes, see `bot.currentWindow.title` if the chest is presently open

**Comment by Natsume1990** [comment]
> Yes, see `bot.currentWindow.title` if the chest is presently open

I started testing it now and it does work completely fine until i want to add `if`.
```
console.log("bot.currentWindow.title")
Print: {"text":"test"}
```
But how can i use it in code like:
```
if (bot.currentWindow.title.includes === "test") {
  console.log("true")
}

**Comment by extremeheat** [comment]
Google how to use String.includes() in JavaScript

**Comment by Natsume1990** [comment]
Dude i'm dumb, closing.
