### ISSUE TITLE
1.19.3 - Chat session not initialized. Can't send chat

### ISSUE THREAD

**Issue by AnthonyvW** [PrismarineJS/mineflayer#2965]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.8.1
 - server: vanilla 1.19.3
 - node: 18.14.2

## Detailed description of a problem
When the bot tries to say anything on an authenticated java edition server (no plugins) using bot.chat("message") it throws this error
```
C:\Users\Me\Desktop\MineFlayer\Bot\node_modules\minecraft-protocol\src\client\chat.js:374
      if (!client._session.uuid) throw Error("Chat session not initialized. Can't send chat")
                           ^

TypeError: Cannot read properties of undefined (reading 'uuid')
    at client.signMessage (C:\Users\Me\Desktop\MineFlayer\Bot\node_modules\minecraft-protocol\src\client\chat.js:374:28)
    at client._signedChat (C:\Users\Me\Desktop\MineFlayer\Bot\node_modules\minecraft-protocol\src\client\chat.js:329:48)
    at C:\Users\Me\Desktop\MineFlayer\Bot\node_modules\mineflayer\lib\plugins\chat.js:177:21
    at Array.forEach (<anonymous>)
    at chatWithHeader (C:\Users\Me\Desktop\MineFlayer\Bot\node_modules\mineflayer\lib\plugins\chat.js:171:25)
    at bot.chat (C:\Users\Me\Desktop\MineFlayer\Bot\node_modules\mineflayer\lib\plugins\chat.js:207:5)
    at EventEmitter.<anonymous> (C:\Users\Me\Desktop\MineFlayer\Bot\index.js:19:7)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.<anonymous> (C:\Users\Me\Desktop\MineFlayer\Bot\node_modules\mineflayer\lib\plugins\chat.js:85:13)
    at EventEmitter.emit (node:events:513:28)
```
## What did you try yet?

I tried uninstall mineflayer, mineflayer pathfinder, updating npm, updating node.js, deleting everything but the script that contains the bot and then reinstalling everything.

Did you try any example? Any error from those?
I tried the mineflayer example, but changed a few lines so it uses microsoft authentication and takes in commandline arguments for the username/ip/port/password

## Your current code
```js

const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node farmer.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}


const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4],
  //password: process.argv[5],
  auth: 'microsoft'
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)


```

## Expected behavior
after the bot logs into the server and you say something in chat it repeats what you said.

## Additional context
I tried asking about how to fix this in the mineflayer discord server and no one was able to figure it out.

**Comment by stefexec** [comment]
I am experiencing the same issue on a fresh install as well. No solution so far, will update if I find something.

**Comment by frej4189** [comment]
This will be fixed with a release for NMP.

**Comment by FelixCharm** [comment]
> mit

I'm still struggling with this issue on the latest version whilst connected to online servers, any advice?

**Comment by extremeheat** [comment]
@FelixCharm 
> I'm still struggling with this issue on the latest version whilst connected to online servers, any advice?

It's not released, you can open a release PR in node-minecraft-protocol

**Comment by FelixCharm** [comment]
> @FelixCharm
> 
> > I'm still struggling with this issue on the latest version whilst connected to online servers, any advice?
> 
> It's not released, you can open a release PR in node-minecraft-protocol

oh ok, thanks
