### ISSUE TITLE
Disable bot respawn

### ISSUE THREAD

**Issue by DaryeDev** [PrismarineJS/mineflayer#2971]
I wanted to leave the bot connected but dead, to use commands but not interfere, but when I kill it, it auto-respawns.

Is there any way to disable auto-respawning?

**Comment by extremeheat** [comment]
I don't believe so, you can open a PR to add this option

**Comment by MrFiend179** [comment]
try this
~~~js
let isBotDead = false;

bot.on('death', () => {
    if (!isBotDead) {
      isBotDead = true;
      console.log("Bot has died.");

      // Prevent respawn
      bot._client.write('client_command', { actionId: 0 });
    }
  });
  
~~~

**Comment by amoraschi** [comment]
> try this
> ~~~js
> let isBotDead = false;
> 
> bot.on('death', () => {
>     if (!isBotDead) {
>       isBotDead = true;
>       console.log("Bot has died.");
> 
>       // Prevent respawn
>       bot._client.write('client_command', { actionId: 0 });
>     }
>   });
>   
> ~~~

There's an option in createBot, this discussion should be closed

**Comment by rom1504** [comment]
Is it documented?

**Comment by MrFiend179** [comment]
> > try this
> > ```js
> > let isBotDead = false;
> > 
> > bot.on('death', () => {
> >     if (!isBotDead) {
> >       isBotDead = true;
> >       console.log("Bot has died.");
> > 
> >       // Prevent respawn
> >       bot._client.write('client_command', { actionId: 0 });
> >     }
> >   });
> >   
> > ```
> 
> There's an option in createBot, this discussion should be closed

keepAlive? other than that i dont see one

**Comment by amoraschi** [comment]
![Screenshot_2023-08-27-22-00-37-127_com.github.android-edit.jpg](https://github.com/PrismarineJS/mineflayer/assets/68395930/19bd32c4-eb4e-4770-a2bc-46edd6833dbf)

**Comment by MrFiend179** [comment]
Yes, this issue is resolved now.
