### ISSUE TITLE
How to label two variables

### ISSUE THREAD

**Issue by Lyh0yh** [PrismarineJS/mineflayer#2973]
## Is your feature request related to a problem? Please describe.
When I use
`bot.addChatPattern('test',/[[].*?].*?messages.you: (.server)(.+)/,{parse: true})`
Two variables are returned.
But they are connected.
Such as
`[Lv.1]abc messages you: 1serverfarm`
`1server,farm`
I want to mark these two variables separately.
Such as
`1server` and `farm`
## Describe the solution you'd like
When I output `[Lv.1]abc messages you: 1serverfarm`
return `1server` and `farm`
Then I can execute the orders separately.
Such as
/server var1(1server)
/res tp var2(farm)
## Additional context
My code
  `bot.on('chat:test', async matches => {
    {console.log('${matches}')}})`
My English is not very good, so I try to express it in detail.
Please let me know if the expression is not clear.
Thanks for your help

**Comment by extremeheat** [comment]
Not an issue with mineflayer, please ask on the discord or put this regex question into ChatGPT.
