### ISSUE TITLE
bot.addChatPattern How to mark multiple variables

### ISSUE THREAD

**Issue by Lyh0yh** [PrismarineJS/mineflayer#2975]
## Is your feature request related to a problem? Please describe.
my code:
`bot.once('spawn', () => {
    bot.addChatPattern('test1',/[[].*?](.*?) messages.you: (.)server(.+)/,{parse: true})
  })`
  `bot.on('chat:test1', (message) => {
    console.log(message)})`
my console:
`[ [ 'KreeDzLs', '1', ' abc' ] ]`
## Describe the solution you'd like
I want to separate several variables.
such as
bot.chat('/server go to 1(var))
bot.chat('/res padd abc(var) KreeDzLs(var)')

## Describe alternatives you've considered
I tried many methods.
But it still didn't come true

## Additional context
I hope it can be realized
When I say residence's name
He will automatically add permissions for me.
But this requires three variables to complete. (servername, username, residence's name)

**Comment by extremeheat** [comment]
Not an issue with mineflayer, please ask on the Discord or use ChatGPT to help you with regex.
