### ISSUE TITLE
Unable to send messages due to missing publicKey

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/mineflayer#2977]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.8.1 from git
 - minecraft-protocol: 1.41.1 from git
 - server: paper
 - node: 14.21.3

## Detailed description of a problem
When trying to use the method bot.Chat, I'm getting the error "Chat disabled due to missing profile public key. Please try reconnecting.", the server is online and has chat signing enabled, I've logged into the account myself to verify it could send messages and it can.

## What did you try yet?

Updating everything and using the latest versions straight from git

## Your current code
```js
const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node main.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}


const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4],
  password: process.argv[5],
  auth: 'microsoft'
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)
```

## Expected behavior
The chat message sends and is viewable by the rest of the server

**Comment by FelixCharm** [comment]
> What version is the server in?

1.19.3

**Comment by SonicandTailsCD** [comment]
Sadly, this may or may not work, as 1.19.3 has the Player Reporting system. That system is broken...

**Comment by SonicandTailsCD** [comment]
Let me tell you what you can do, lah. 

1. Install the plugin named "SkinRestorer (Offline and Online mode)", don't start the server yet!
2. Set your server to offline mode, make sure your server is limited to the amount of players that will be connected simultaneously, otherwise hackers may come and NUKE the server.

If you want, I can join (Offline Mode only - I don't use a premium account yet) and I can see what happens and try to help you...

**Comment by FelixCharm** [comment]
> Let me tell you what you can do, lah.
> 
> 1. Install the plugin named "SkinRestorer (Offline and Online mode)", don't start the server yet!
> 2. Set your server to offline mode, make sure your server is limited to the amount of players that will be connected simultaneously, otherwise hackers may come and NUKE the server.
> 
> If you want, I can join (Offline Mode only - I don't use a premium account yet) and I can see what happens and try to help you...

I don't have permission to modify anything on the server-side of things, I only have permission to run the bot

**Comment by SonicandTailsCD** [comment]
You don't own the server?

**Comment by SonicandTailsCD** [comment]
If you don't, ask the owner to install the SkinRestorer plugin and set that server in offline mode. If you don't know, SkinRestorer applies skins for offline and online mode servers. Offline mode does open up the ability for hackers to join, but the full-on player reporting will be gone, allowing the bot to join and craft.

**Comment by SonicandTailsCD** [comment]
One more thing you can do: go to aternos.org/login and create an account. You'll have a server for FREE!

**Comment by SonicandTailsCD** [comment]
The catch is, there are a few limitations…

**Comment by extremeheat** [comment]
Should be fixed with https://github.com/PrismarineJS/node-minecraft-protocol/pull/1091
