### ISSUE TITLE
How to find the attacker in 'entityHurt' event

### ISSUE THREAD

**Issue by xieleo5** [PrismarineJS/mineflayer#2984]
## Is your feature request related to a problem? Please describe.
I'm using the `entityHurt` event of the bot. But I only find one `entity` which is the victim. Is there any way to also get the attacker who deals the damage? I'd like to find out whether it's a monster or sth else that attack the bot.

## Describe the solution you'd like
Besides an `entity`, also give an `attacker` in the event.

```javascript
bot.on("entityHurt", (entity, attacker) => {})
```

## Describe alternatives you've considered
Any methods that can precisely get the name and position of the attacker would be good.

**Comment by xieleo5** [comment]
If I remember correctly, I believe the hurt event in Minecraft java code should provide both the victim and the damage source. I used it before when I was making some mod. Any suggestion on finding the attacker will be enough. Thanks~

**Comment by Shrecknt** [comment]
> If I remember correctly, I believe the hurt event in Minecraft java code should provide both the victim and the damage source. I used it before when I was making some mod.

Your mod only worked because it was both client-side and server-side

In the current protocol specification, the attacker/damage cause is never sent to the client.
When the player takes damage, it will send a packet to the client to display the hurt animation, and another packet to update the player's health and saturation.

**Comment by 1tsMeMario** [comment]
commenting on this to let you know that i added this feature, just waiting on pull request to get merged hopefully. if not you can look at the code and add it in.
i know its a bit old lol
@xieleo5
