### ISSUE TITLE
bot.chat doesn't work anymore

### ISSUE THREAD

**Issue by SonicandTailsCD** [PrismarineJS/mineflayer#2988]
- Yes, the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 8.11.0
 - server: Spigot 1.18.2
 - node: 17.9.1

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
The bot was joining fine and was working with bot.chat() correctly. Out of nowhere, the bot stops working and throws me off with this error: 
/Users/adm/Desktop/Bot/node_modules/mineflayer/lib/plugins/chat.js:177
        bot._client.chat(smallMsg)
                    ^

TypeError: bot._client.chat is not a function
    at /Users/adm/Desktop/Bot/node_modules/mineflayer/lib/plugins/chat.js:177:21
    at Array.forEach (<anonymous>)
    at chatWithHeader (/Users/adm/Desktop/Bot/node_modules/mineflayer/lib/plugins/chat.js:171:25)
    at EventEmitter.bot.chat (/Users/adm/Desktop/Bot/node_modules/mineflayer/lib/plugins/chat.js:207:5)
    at Object.<anonymous> (/Users/adm/Desktop/Bot/bot2.js:27:5)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

Node.js v17.9.1
What are you building? Simple bot that uses one plugin to load its skin: SkinRestorer
What problem are you trying to solve? I need that bot to join

## What did you try yet?

Did you try any method from the API?No, I don't even know what that is.
Did you try any example? yes
Any error from those? yes

## Your current code
```js

// Here I tell node.js mineflayer and a few other plugins are required to load
const mineflayer = require('mineflayer')

// Here, we set up the server connection (in this case, my skin plugin server)
const bot = mineflayer.createBot({
    host: 'SonicJavaBots.aternos.me',
    port: '37867',
    username: "SonicandTailsCDb",
    version: '1.18.2'
})
// I'm online right now, join up if you want

// And now, we work on the AI here!
// Here's all of the functions:
// One note tho: All functions are placeholders.
function onPhysicsTick () {}
function onSpawn () {
    bot.chat("Hey! I'm working properly :D")
}

// I need to set physicsTick because I want the AI to target me.
bot.on('physicsTick', onPhysicsTick)

// Next, I'm gonna set spawn actions.
bot.on('spawn', onSpawn)

// Set skin, of course!
bot.chat("/skin set SonicandTailsCDb robot1_stevetest")


```

## Expected behavior
The bot joining and having the skin

## Additional context
NO. Thanks :)

**Comment by 678435021** [comment]
You used `bot.chat` before logging in to the server.
Move `bot.chat("/skin set SonicandTailsCDb robot1_stevetest")` inside `onSpawn`

**Comment by SonicandTailsCD** [comment]
Of course I did. There's a bug with the plugin that I use that respawns you after applying the skin. Or maybe it's intentional, idk! After the bot respawns, it does it again. And it loops. What should I do?


On Mar 23, 2023, at 14:28, 678435021 ***@***.***> wrote:

﻿

You used bot.chat before logging in to the server.
Move bot.chat("/skin set SonicandTailsCDb robot1_stevetest") inside onSpawn

**Comment by SonicandTailsCD** [comment]
Oh and me moving that line to onSpawn won't work for me. Anything else I can do?

**Comment by 678435021** [comment]
> There's a bug with the plugin that I use that respawns you after applying the skin.

I think it respawns you to refresh the skin and work properly. I think it's intentional

> After the bot respawns, it does it again. And it loops. What should I do?

`bot.on('spawn', onSpawn)` will trigger everytime your bot spawns or respawns, that's why it loops.
Change `bot.on('spawn', onSpawn)` to `bot.once('spawn', onSpawn)` to make it trigger only once

**Comment by 678435021** [comment]
> Oh and me moving that line to onSpawn won't work for me. Anything else I can do?

It worked for me when I moved it there

**Comment by SonicandTailsCD** [comment]
Alright. I'm gonna try that… don't close this yet, maybe I still have some other issue. Thanks in advance :)

**Comment by SonicandTailsCD** [comment]
This worked, the bot spawned correctly. Thanks :)
