### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'setMovements')

### ISSUE THREAD

**Issue by SonicandTailsCD** [PrismarineJS/mineflayer#2997]
- Yes, the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 8.11.0
 - server: Spigot 1.18.2 (Plugins installed)
 - node: 17.9.1

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
Weird error that doesn't allow me to create a bot. That's all I know.
What are you building? A pathfinding bot that follows me when I say "follow me"
What problem are you trying to solve?

## What did you try yet?

Did you try any method from the API? I don't know how to.
Did you try any example? Yes 
Any error from those? No

## Your current code
```js

// Here I tell node.js mineflayer and a few other plugins are required to load
const { versions } = require('minecraft-data')
const MinecraftData = require('minecraft-data')
const mineflayer = require('mineflayer')
const { pathfinder, Movements, goals } = require('mineflayer-pathfinder')
const GoalFollow = goals.GoalFollow
const pvp = require('mineflayer-pvp').plugin

// Here, we set up the server connection (in this case, my skin plugin server)
const bot = mineflayer.createBot({
    host: 'SonicJavaBots.aternos.me',
    port: '37867',
    username: "SonicandTailsCDb",
    version: '1.18.2'
})

// And now, we work on the AI here!
// Here's all of the functions:
// One note tho: All functions are placeholders.
function onPhysicsTick () {}

function onSpawn () {
    bot.chat("Hey! I'm working properly :D")
    bot.chat("/skin set SonicandTailsCDb robot1_stevetest")
}

function onSpawnMessage () {
    bot.on('chat', (daname, msgg)=>{
        const player = bot.players[daname]
        if (msgg == "follow me") {
            bot.chat("Okay " + daname)
        }
        if (!player || !player.entity){
            bot.chat("I can't see you, " + daname) 
            return
        }
        const data = require('minecraft-data')(bot.version)
        const movements = new Movements(bot, data)
        bot.pathfinder.setMovements(movements)
        
        const goal = new GoalFollow(player.entity, 2)
        bot.pathfinder.setGoal(goal, true)
    })
}

// I need to set physicsTick because I want the AI to target me.
bot.on('physicsTick', onPhysicsTick)

// Next, I'm gonna set spawn actions.
bot.once('spawn', onSpawn)
bot.on('spawn', onSpawnMessage)



```

## Expected behavior
I expected the bot to join and follow me when I say "follow me"

## Additional context
NO. Thanks :)

**Comment by 678435021** [comment]
You didn't load the `pathfinder` plugin.
Add the code below under `mineflayer.createBot()`:
```javascript
bot.loadPlugin(pathfinder)
```

**Comment by 678435021** [comment]
btw, you should just move `bot.on('chat')` inside `onSpawn` and remove `bot.on('spawn', onSpawnMessage)` and `onSpawnMessage`

**Comment by SonicandTailsCD** [comment]
>btw, you should just move bot.on('chat') inside onSpawn and remove bot.on('spawn', onSpawnMessage) and onSpawnMessage

The thing is that a server plugin sends the spawn message to the client when its skin is loaded. 

>You didn't load the pathfinder plugin.

I'm gonna try to load the server now with the correction...

**Comment by SonicandTailsCD** [comment]
Also, wanna join the server? We try to fix it in real time?

**Comment by SonicandTailsCD** [comment]
LOL it said "I can't see you, SkinsRestorer". How do I fix this?

**Comment by 678435021** [comment]
> Also, wanna join the server? We try to fix it in real time?

yeah sure

**Comment by SonicandTailsCD** [comment]
Alright. You know the IP and port?

**Comment by 678435021** [comment]
yup

**Comment by SonicandTailsCD** [comment]
// Here I tell node.js mineflayer and a few other plugins are required to load
const { versions } = require('minecraft-data')
const MinecraftData = require('minecraft-data')
const mineflayer = require('mineflayer')
const { pathfinder, Movements, goals } = require('mineflayer-pathfinder')
const GoalFollow = goals.GoalFollow
const pvp = require('mineflayer-pvp').plugin

// Here, we set up the server connection (in this case, my skin plugin server)
const bot = mineflayer.createBot({
    host: 'SonicJavaBots.aternos.me',
    port: '37867',
    username: "SonicandTailsCDb",
    version: '1.18.2'
})

// Loading!
bot.loadPlugin(pathfinder)

// And now, we work on the AI here!
// Here's all of the functions:
// One note tho: All functions are placeholders.
function onPhysicsTick () {}

function onSpawn () {
    bot.chat("Hey! I'm working properly :D")
    bot.chat("/skin set SonicandTailsCDb robot1_stevetest")
}

function onSpawnMessage () {
    bot.on('chat', (daname, msgg)=>{
        const player = bot.players[daname]
        if (msgg == "follow me") {
            bot.chat("Okay " + daname)
        }
        if (!player || !player.entity){
            bot.chat("I can't see you, " + daname) 
            return
        }
        const data = require('minecraft-data')(bot.version)
        const movements = new Movements(bot, data)
        bot.pathfinder.setMovements(movements)
        
        const goal = new GoalFollow(player.entity, 2)
        bot.pathfinder.setGoal(goal, true)
    })
}

// I need to set physicsTick because I want the AI to target me.
bot.on('physicsTick', onPhysicsTick)

// Next, I'm gonna set spawn actions.
bot.once('spawn', onSpawn)
bot.on('space', onSpawnMessage)

**Comment by 678435021** [comment]
```javascript
// Here I tell node.js mineflayer and a few other plugins are required to load
const { versions } = require('minecraft-data')
const mineflayer = require('mineflayer')
const { pathfinder, Movements, goals } = require('mineflayer-pathfinder')
const GoalFollow = goals.GoalFollow
const pvp = require('mineflayer-pvp').plugin

// Here, we set up the server connection (in this case, my skin plugin server)
const bot = mineflayer.createBot({
    host: 'SonicJavaBots.aternos.me',
    port: '37867',
    username: "aaaa",
    version: '1.18.2'
})

const mcData = require('minecraft-data')(bot.version)

// Setup pathfinder
bot.loadPlugin(pathfinder)
bot.pathfinder.setMovements( new Movements(bot, mcData))

// And now, we work on the AI here!
// Here's all of the functions:
// One note tho: All functions are placeholders.
function onPhysicsTick () {}

function onSpawn () {
    bot.chat("Hey! I'm working properly :D")
    bot.chat("/skin set SonicandTailsCDb robot1_stevetest")

    bot.on('chat', (daname, msg)=>{
        const player = bot.players[daname]
        if (msg == "follow me") {
            if (!player?.entity){
                bot.chat("I can't see you, " + daname)
                return
            }

            bot.chat("Okay " + daname)

            const goal = new GoalFollow(player.entity, 2)
            bot.pathfinder.setGoal(goal, true)
            return
        }
    })
}

// I need to set physicsTick because I want the AI to target me.
bot.on('physicsTick', onPhysicsTick)

// Next, I'm gonna set spawn actions.
bot.once('spawn', onSpawn)

```

**Comment by SonicandTailsCD** [comment]
I'm ready! :D

**Comment by SonicandTailsCD** [comment]
This issue is complete, I don't have that specific issue anymore.
Thanks to @678435021 for his help :)
