### ISSUE TITLE
 how to disable the bot being pushed by water

### ISSUE THREAD

**Issue by 31alper** [PrismarineJS/mineflayer#2999]
water source block is pushing my mineflayer bot how to disable it?

**Comment by amoraschi** [comment]
![image](https://user-images.githubusercontent.com/68395930/228923341-4c584f57-8525-408a-b112-1dc451d6842d.png)
It's not possible to only disable water physics, but in the createBot function you can disable physics entirely

**Comment by 31alper** [comment]
Thanks, that helped me a lot

**Comment by amoraschi** [comment]
Then please mark the response as the solution or the discussion as solved

**Comment by 31alper** [comment]
How?

**Comment by SonicandTailsCD** [comment]
> How?

Click "Close with comment" at the bottom of the text input. See that button at the left, right next to "Comment"? Click that.
