### ISSUE TITLE
1.19.4 compatibility

### ISSUE THREAD

**Issue by TheLogicIsOdd** [PrismarineJS/mineflayer#3005]
A: This request is related to a problem. I have "SleepingServerStarter" which uses your node-minecraft-protocol. Since there isn't 1.19.4 compatibility, the plugin isn't working for my server.

A: I would like to see compatibility with Minecraft v1.19.4 later.

A: I haven't thought about any additional alternatives because there isn't any.

Here is a screenshot of the error while trying to use SleepingServerStarter.
![Screenshot 2023-04-02 100029](https://user-images.githubusercontent.com/82181352/229367627-77694e30-9642-4289-a53d-a8c4dc136d17.png)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/1097

**Comment by Maks-gaming** [comment]
up

**Comment by TheArmagan** [comment]
up

**Comment by eperry** [comment]
This issue seems to be addressed

I have updated my package.js with the new version of minecraft-protocol as it was just released 2 days ago and now I can connect and the example bots work

    "minecraft-protocol": ">=1.42",

**Comment by Whitelisted1** [comment]
This issue seems to now be fixed, if you (@TheLogicIsOdd) could close this issue that would be great
