### ISSUE TITLE
bot.sleep not working when server has operators

### ISSUE THREAD

**Issue by dustinyschild** [PrismarineJS/mineflayer#3008]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.8.1
 - servers
   - papermc: paper-1.19.3-425
   - vanilla: 1.19.3
 - node: 18.15.0

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?\

I am trying to create a simple sleep loop based on day/night cycle. I added my own account as an operator via the server console in order to control the time of day for testing purposes.

While having myself set as an operator, the bot will walk to the bed and try to sleep. The bot clicks on the bed, but does not sleep and throws the timeout error after 3 seconds: (`new Error('bot is not sleeping')`)

## What did you try yet?
- server restarts (paper & vanilla)
- calling `bot.activateBlock` directly
- running the same code on vanilla server (1.19.3)
- deop myself in console (this worked, but is not ideal for the testing I'd like to do)

## Your current code
This is reproducible with `examples/sleeper.js`

## Expected behavior
Bot should sleep

## Additional context
I haven't had the time to be more precise with the scope of the issue

Things I haven't tried yet:
- Setting bot as an operator
- Test if Operator has to be logged in for this to happen
- Test if this is affects other block activation behavior

Tbh this isn't a major issue, I just found it interesting and thought maybe someone would have

**Comment by extremeheat** [comment]
Is this not intended functionality? How does it work with a vanilla client?

**Comment by dustinyschild** [comment]
I tried to get more info on the issue and now I can't reproduce
