### ISSUE TITLE
Read book

### ISSUE THREAD

**Issue by zoga-com** [PrismarineJS/mineflayer#3011]
Hello, I did not find the ability to read books by a bot, could you tell me if this is possible? If yes, I will be grateful if you give an example.

*I need to read NBT of book

**Comment by mvrozanti** [comment]
Have you tried to get the NBT object of the Item? I think that data is in there.

**Comment by Whitelisted1** [comment]
You are able to read the pages, author and title of a book. Here a quick example where the bot, three seconds after spawning, reads the text of the books in its inv.

```js
const mineflayer = require("mineflayer");
const settings = {
    username: "bob",
    host: "localhost",
    port: 25565,
    version: "1.19.4"
};

const bot = mineflayer.createBot(settings);

bot.once("spawn", () => {
    bot.chat("Spawned ...");

    // wait 3 seconds to get items in inv
    setTimeout(() => {
        for (item of bot.inventory.items()) {
            if (item.name == "written_book") {
                console.log(item.nbt.value);

                // might be different item structure in different versions 
                console.log(item.nbt.value.pages.value.value);
            }
        }
    }, 3000);
});
```

**Comment by Jovan-04** [comment]
it appears this issue is resolved - can we close it?
