### ISSUE TITLE
examples/perfectShotBow.js does not load

### ISSUE THREAD

**Issue by tyjtyj** [PrismarineJS/mineflayer#3013]
- [ *] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.8.1
 - server: vanilla/spigot/paper vanilla
 - node: 18.15.0

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?
[mineflayer](https://github.com/PrismarineJS/mineflayer)/[examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples)/perfectShotBow.js

dumping errors
```
node:assert:400
    throw err;
    ^

AssertionError [ERR_ASSERTION]: plugin needs to be a function
    at EventEmitter.loadPlugin (/root/mineflayer/node_modules/mineflayer/lib/plugin_loader.js:16:12)
    at Object.<anonymous> (/root/mineflayer/perfectShotBow.js:12:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

## What did you try yet? nodejs v14 - 18 with same result
npm i minecrafthawkeye

Did you try any method from the API? this is provided examples
Did you try any example? Any error from those? Exmples not working

## Your current code
```js

/*
https://github.com/PrismarineJS/mineflayer/blob/master/examples/perfectShotBow.js
*/

```

## Expected behavior
It should load

## Additional context
https://github.com/sefirosweb/minecraftHawkEye/issues/20

**Comment by Neotastisch** [comment]
Fix:
const minecraftHawkEye = require('minecrafthawkeye');
bot.loadPlugin(minecraftHawkEye.default)

**Comment by tyjtyj** [comment]
> Fix: const minecraftHawkEye = require('minecrafthawkeye'); bot.loadPlugin(minecraftHawkEye.default)

This fixed the issue

**Comment by amoraschi** [comment]
Could you PR the fix?

**Comment by Neotastisch** [comment]
> Could you PR the fix?

Done
