### ISSUE TITLE
Error - SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by Cat123bat** [PrismarineJS/mineflayer#3023]
i have read the js tutorial and learned mineflaer a bit. I also improved the script, but it still doesn't want to work. Кeinstalled node.js several times. I even tried it on different IDLs, but nothing works. Please help me I don't understand what is wrong Here's the code:
const mineflayer = require('mineflayer');

const bot = mineflayer.createBot({
host: 'localhost',
port: 60147
username: 'Bot',
version: "1.18.2",
});

bot.on('chat', (username, message) => { if (username === bot.username) return; 
bot.chat(Hello ${username}! Я бот. Вы написали: ${message}); 
});

bot.on('login', () => {
console.log('Bot successfully authorized on the server!');
});;
Error:
SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.0

**Comment by andriycraft** [comment]
`const mineflayer = require('mineflayer');

const bot = mineflayer.createBot({
    host: 'localhost',
    port: 60147,
    username: 'Bot',
    version: "1.18.2",
});

bot.on('chat', (username, message) => {
    if (username === bot.username) return;

    bot.chat(`Hello ${username}! Я бот. Вы написали: ${message}`);
});

bot.on('login', () => {
    console.log('Bot successfully authorized on the server!');
});;`

**Comment by Cat123bat** [comment]
I use VS code

**Comment by extremeheat** [comment]
You need to know Node.js and JavaScript in order to write a mineflayer bot. This error is not an issue with mineflayer, but the code you are using. Format your code better and it will be more obvious where the syntax error is.
