### ISSUE TITLE
how can i login with a ssid?

### ISSUE THREAD

**Issue by r1shie** [PrismarineJS/mineflayer#3029]
const mineflayer = require('mineflayer');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question('Enter your session ID: ', (ssid) => {
  const bot = mineflayer.createBot({
    host: 'rishieyt123.aternos.me', // Minecraft server to connect to
    session: {
      accessToken: ssid // Session ID obtained from the user input
    }
  });

  bot.on('login', () => {
    console.log('Bot logged in successfully!');
    bot.chat('Hello, world!'); // Send a message in chat
  });

  bot.on('error', (err) => {
    console.log('Bot error:', err);
  });
});

this is my code, how can i login with a ssid?

or is there anyway to login with uuid and session id or something

**Comment by zxxxxo** [comment]
Aren't you the person that pirated my phisher src and sold it as your own?

In any case, stealing someones token and logging into their account is unethical, and you won't get an answer.

However, $50 can settle it :)

**Comment by SonicandTailsCD** [comment]
AYOOOOO :D
