### ISSUE TITLE
Event to catch unparsed messages and to parse custom message groups

### ISSUE THREAD

**Issue by Darker** [PrismarineJS/mineflayer#303]
You can catch all messages by the `message` event. Also, you can add regular expressions to parse server messages. Messages parsed as `whisper` or `chat` will emit their respective events.

My question, or maybe a feature request is:

It would be great to have a callback for my own message (eg. auction message):

```
//Assign chat pattern (this works)
bot.chatAddPattern(/^\[ Auction\] (.*)$/, "auction", "Auction info");
//Possible way to implement it:
bot.chatOn("auction", function(message) {if(show_auctions)console.log(message);});
```

And finally there could be a callback for messages that didn't match any of the registered chat patterns:

```
bot.chatOnUnparsed(function(message) {console.log("SERVER: "+message);});
```

**Comment by rom1504** [comment]
This is actually already possible, but not documented anywhere I think. See https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/chat.js#L40

This only needs documentation.

**Comment by Darker** [comment]
Yeah, I already discovered. I should've added it. But in the meantime I came into another needed enhancement: event for messages that didn't match any regexp. Something like `message_unparsed`.

Shall I start new issue for that?

**Comment by rom1504** [comment]
Done
