### ISSUE TITLE
Different Ways Of Logging In

### ISSUE THREAD

**Issue by r1shie** [PrismarineJS/mineflayer#3034]
hey guys im just wondering how i can login with a SSID (session id) (with mineflayer) 

im not sure how to do this

please if u can help please reply

**Comment by zxxxxo** [comment]
Your last issue was also closed, and making a duplicate one is forbidden.

In any case, stealing someones session token and logging into their account is unethical, and you won't get an answer.

However, $50 can settle it.

**Comment by extremeheat** [comment]
Use the search function instead of creating duplicate issues
