### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'heldItem')

### ISSUE THREAD

**Issue by Fadnix** [PrismarineJS/mineflayer#3040]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.8.1
 - server: paper
 - node: v18.15.0

node_modules\mineflayer\lib\plugins\inventory.js:366
    bot.entity.heldItem = bot.heldItem
                        ^

TypeError: Cannot set properties of undefined (setting 'heldItem')
    at EventEmitter.updateHeldItem (node_modules\mineflayer\lib\plugins\inventory.js:366:25)
    at EventEmitter.setQuickBarSlot (node_modules\mineflayer\lib\plugins\simple_inventory.js:59:9)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
## Your current code
```js
function daddy() {
  setTimeout(() => {
    const playerHead = bot.inventory.items().find(item => item.name === 'player_head');
    if (playerHead) {
      bot.setQuickBarSlot(4);
      console.log('%cdaddy occurred (4)', 'color: red');
    } else {
      bot.setQuickBarSlot(0);
      console.log('%cdaddy occurred (0)', 'color: red');
    }
    setTimeout(() => {
      bot.activateItem();
    }, 6000);
  }, 12000);
}
setInterval(daddy, 18000);
daddy();
/*
*/


```

## Expected behavior
It is supposed to set quick bar slot to 4 if the bot has a player_head in his inventory, else it will set it to 0

## Additional context
usually the code works but its giving that error randomly like every 15-20 minutes

**Comment by williamd5** [comment]
It looks like `bot.entity` is undefined. Is your bot logged into a server?

**Comment by extremeheat** [comment]
Reopen if you have more information
