### ISSUE TITLE
Mojang Account not accepted

### ISSUE THREAD

**Issue by DaddySuff** [PrismarineJS/mineflayer#3060]
[deprecated] mojang auth servers no longer accept mojang accounts to login. convert your account.
https://help.minecraft.net/hc/en-us/articles/4403181904525-How-to-Migrate-Your-Mojang-Account-to-a-Microsoft-Account

**Comment by rom1504** [comment]
Yes, use your Microsoft account

**Comment by DaddySuff** [comment]
i dont own one

**Comment by rom1504** [comment]
All Mojang account can be migrated to Microsoft accounts
