### ISSUE TITLE
Low level packet sending

### ISSUE THREAD

**Issue by Dasupergrasskakjd** [PrismarineJS/mineflayer#3064]
## Is your feature request related to a problem? Please describe.
I want to use low level packet sending to be able to modify the game for my project

## Describe the solution you'd like
Add a function for sending packets directly

## Describe alternatives you've considered
None

## Additional context
None

**Comment by extremeheat** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/unstable_api.md
