### ISSUE TITLE
bot.stopDigging throws a fatal error

### ISSUE THREAD

**Issue by Dasupergrasskakjd** [PrismarineJS/mineflayer#3065]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.8.1
 - server: paper 1.19.3(it allows older version to join)
 - node: 18.14.0

## Detailed description of a problem
it throws a fatal Digging aborted error

## What did you try yet?

it digs a block if it is not digging anything currently, calls bot.stopDigging if it is digging right now

## Your current code
```js

        if(bot.targetDigBlock) bot.stopDigging();
        else bot.dig(block!);


```

## Expected behavior
It should cancels the digging if it is already digging

## Additional context
In the api reference I thought it will only throw the error if I call bot.dig when it is already digging

**Comment by extremeheat** [comment]
This is the intended behavior, to cancel the already existing dig promise. While it may be intended for you, other code listening to the promise are also affected and need to be informed of the Promise cancellation.
