### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'height')

### ISSUE THREAD

**Issue by DanyVolk** [PrismarineJS/mineflayer#3067]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: Lastest
 - server: vanilla/spigot/paper paper
 - node: v20.2.0

When you log on to the server, the code turns off and an error pops up.

I tried the bot.EntityInS method

No.
I tried the very initial example.

## Your current code
const bot = mineflayer.createBot({
  host: serverAddress,
  port: serverPort,
  username: username,
});

/*
const bot = mineflayer.createBot({
  host: serverAddress,
  port: serverPort,
  username: username,
});
*/

```

I was expecting to see the bot log in to the server

ypeError: Cannot set properties of undefined (setting 'height')
    at Client.<anonymous> (/home/daniil/node_modules/mineflayer/lib/plugins/physics.js:264:23)

**Comment by extremeheat** [comment]
This is a problem with your code, likely due to you not waiting for the correct event like `spawn` before calling a mineflayer API. Please go to the discord and provide *all* the code you used to reproduce the error.
