### ISSUE TITLE
1.20 & 1.20.1 Support

### ISSUE THREAD

**Issue by TheDevMinerTV** [PrismarineJS/mineflayer#3075]
## Is your feature request related to a problem? Please describe.

Please support Minecraft: Java Edition 1.20.

## Describe the solution you'd like

Support Minecraft: Java Edition 1.20.

**Comment by TheDevMinerTV** [comment]
Depends on https://github.com/PrismarineJS/node-minecraft-protocol/issues/1230

**Comment by rom1504** [comment]
Nmp support is there, possible to open a PR to add support to mineflayer now

**Comment by TheDevMinerTV** [comment]
Closed by https://github.com/PrismarineJS/mineflayer/commit/d0a1660521a1e6ce62f5da9d19c754ef48d89d7f

Thank you, people!

**Comment by SussyD3V** [comment]
can you add 1.20.2 support please?

**Comment by ptasema** [comment]
{"translate":"multiplayer.disconnect.incompatible","with":["1.20.2"]} false
socketClosed

Is that what can i fix, maybe how as a temporary, unstable solution, or only waiting 1.20.2 support? 
You do very cool things, guys
