### ISSUE TITLE
Ignoring block entities as chunk failed to load at

### ISSUE THREAD

**Issue by cmetanamaker** [PrismarineJS/mineflayer#3076]
When i launch my old script it spam in "Ignoring block entities as chunk failed to load at" in console,but it didn't do that before and i remove all console.log() in code
Script on js,i use only mineflayer

**Comment by streetraceing** [comment]
```js
console.warn = () => {};
```
You can add this to your code

**Comment by extremeheat** [comment]
The above is bad unless you want to disable all your console logging, ignore the above comment.  

You can enable the “hideErrors” flag in the bot options instead.
