### ISSUE TITLE
Multiple accounts from file doesn't work

### ISSUE THREAD

**Issue by Muminwilmer** [PrismarineJS/mineflayer#3078]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.9.0
 - server: paper, idk version
 - node: v19.4.0

## Detailed description of a problem
I'm trying to login using a file, but it says this "

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
Bots (0 / 2) successfully logged in.
" :/

## What did you try yet?
i tried making some changes and removed parts of the code that wasn't really needed

## Your current code
```js

const mineflayer = require('mineflayer');
const fs = require('fs')
const util = require('util')
const readFile = (fileName) => util.promisify(fs.readFile)(fileName, 'utf8')


let config = {
  version: '1.17',
  host: 'og-network.net',
  file: './accounts.txt',
  interval: 500,
};


function makeBot ([_u, _p], ix) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const bot = mineflayer.createBot({
        username: _u,
        password: _p,
        host: config.host,
        port: config.port
      })
      bot.on('spawn', () => resolve(bot))
      bot.on('error', (err) => reject(err))
      setTimeout(() => reject(Error('Took too long to spawn.')), 5000) // 5 sec
    }, config.interval * ix)
  })
}
  
async function main () {
  // convert accounts.txt => array
  const file = await readFile(config.file)
  const accounts = file.split(/\r?\n/).map(login => login.split(':'))
  const botProms = accounts.map(makeBot)
  // const bots = await Promise.allSettled(botProms)
  const bots = (await Promise.allSettled(botProms)).map(({ value, reason }) => value || reason).filter(value => !(value instanceof Error))
  console.log(`Bots (${bots.length} / ${accounts.length}) successfully logged in.`)
  function joinWait(times) {
    if(times < 1) {
      return;
    }
  
    setTimeout(function() {
      bot.chat("/joinq SMP")
      joinWait(times-1);
    }, 10000);
  }
  joinWait(99999)
};

main();


```
## Expected behavior
i want it to log in on all (2) accounts

my file of names is named accounts.txt
![245128950-d24750a1-acf2-4b69-99a4-f12d1d673db5](https://github.com/PrismarineJS/mineflayer/assets/113240095/e36a003a-6dca-4080-9983-6cf10ca436df)

**Comment by ImUserDol** [comment]
Hello, have you figured out the error? If yes, please write about it here and kindly explain how exactly you solved the problem. If not, I can roughly describe to you a way in which it can be solved. Good luck!

**Comment by Muminwilmer** [comment]
no, i couldn't fix it and just gave up after a while

**Comment by ImUserDol** [comment]
I was a little mistaken about the fix, but yesterday I seemed to be able to find a more or less correct solution, but first things first.


Are the bots running on your localhost? (Create your own local server and put bots there)
If the bots also give an error, or connect and immediately exit, then write about it here.
And give me your discord please

**Comment by extremeheat** [comment]
This is a server-sided issue, you are being disconnected by the server (too many clients?). Try a local vanilla server.
