### ISSUE TITLE
Error with module

### ISSUE THREAD

**Issue by MamiaaaXD4747** [PrismarineJS/mineflayer#3080]
I'm getting an error, no matter how much I do, it doesn't get fixed

 - mineflayer: 4.9.0
 - server: vanilla/spigot/paper paper 1.12.2
 - node: v20.2.0

const mineflayer = require('mineflayer');
const pathfinder = require('mineflayer-pathfinder').pathfinder;
const Movements = require('mineflayer-pathfinder').Movements;
const mcData = require('minecraft-data')('1.12.2');

const serverHost = 'Ulagnnhayatxd47uxrD.aternos.me';
const serverPort = 48306;
const username = 'kullanici-adi';

const bot = mineflayer.createBot({
  host: serverHost,
  port: serverPort,
  username: username,
  version: '1.12.2'
});

bot.loadPlugin(pathfinder);

bot.once('spawn', () => {
  console.log('Minecraft sunucusuna bağlandı!');
  const movements = new Movements(bot, mcData);
  movements.scafoldingBlocks = [];

  bot.on('chat', (username, message) => {
    if (username === bot.username) return;

    console.log(`${username}: ${message}`);
    if (message === 'elmas getir') {
      bot.chat('Tamam, elmas aramaya gidiyorum!');
      findDiamond();
    }
  });

  bot.on('path_update', (results) => {
    console.log('Yeni yol hesaplandı:');
    console.log(results);
  });

  bot.on('goal_reached', (goal) => {
    console.log('Hedefe ulaşıldı!');
    console.log(goal);
    if (goal === 'elmas arama') {
      bot.chat('Elmas bulundu ve kırıldı, size getiriyorum!');
      bot.chat('/give ' + username + ' diamond 1');
    }
  });
});

bot.on('error', (err) => {
  console.log('Minecraft sunucusuna bağlanırken hata oluştu:');
  console.log(err);
});

bot.on('end', () => {
  console.log('Minecraft sunucusundan çıkıldı.');
});

function findDiamond() {
  const diamondBlocks = bot.findBlocks({
    matching: mcData.blocksByName.diamond_ore.id,
    maxDistance: 10,
    count: 5
  });

  if (diamondBlocks.length > 0) {
    const diamondBlock = diamondBlocks[0];
    const goal = bot.pathfinder.goalBlock(diamondBlock.position.x, diamondBlock.position.y, diamondBlock.position.z);
    bot.pathfinder.setGoal(goal);
    bot.once('goal_reached', () => {
      bot.dig(diamondBlock);
      findDiamond();
    });
  } else {
    bot.chat('Yakınlarda elmas cevheri bulunamadı!');
  }
}
The above code is the following error

/data/data/com.termux/files/home/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: bot.goalBlock is not a function
    at findDiamond (/data/data/com.termux/files/home/ama.js:66:22)
    at EventEmitter.<anonymous> (/data/data/com.termux/files/home/ama.js:29:7)
    at EventEmitter.emit (node:events:511:28)
    at EventEmitter.<anonymous> (/data/data/com.termux/files/home/node_modules/mineflayer/lib/plugins/chat.js:85:13)
    at EventEmitter.emit (node:events:511:28)
    at Client.<anonymous> (/data/data/com.termux/files/home/node_modules/mineflayer/lib/plugins/chat.js:140:9)
    at Client.emit (node:events:511:28)
    at Client.<anonymous> (/data/data/com.termux/files/home/node_modules/minecraft-protocol/src/client/play.js:46:16)
    at Client.emit (node:events:511:28)
    at emitPacket (/data/data/com.termux/files/home/node_modules/minecraft-protocol/src/client.js:83:12)

Node.js v20.2.0

I'm getting this error I think it's not code related I guess there is a problem in the latest version of the module

**Comment by ImUserDol** [comment]
GoalBlock = pathfinder.goals.GoalBlock
Paste this below the pathfinder line, it should help.

**Comment by extremeheat** [comment]
Copy code directly from the examples. If you need help ask on the discord, the library is working as intended, so there is no issue with mineflayer.
