### ISSUE TITLE
Build barritone into mineflayer

### ISSUE THREAD

**Issue by BLABLA1000gg** [PrismarineJS/mineflayer#3086]
Hey, just wanted to ask if its possible to use barritone somehow in mineflayer its really helpfull for farming diamonds,quartz_ore and so on on Servers that have anticheat

**Comment by extremeheat** [comment]
Yes, it's possible with https://github.com/PrismarineJS/mineflayer-pathfinder.

**Comment by BLABLA1000gg** [comment]
> Yes, it's possible with https://github.com/PrismarineJS/mineflayer-pathfinder.

i didnt mean that i mean build full barritone into mineflayer that also have an AL build in and so on:


https://github.com/cabaletta/baritone

that is barritone
