### ISSUE TITLE
Bug bot don't move

### ISSUE THREAD

**Issue by tchereau** [PrismarineJS/mineflayer#3087]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.9.0
 - server: vanilla 1.20
 - node: 18.16.0

## Detailed description of a problem
while using pathfinder and goal, the bot doesn't move.

## What did you try yet?
pathfinder goalfollow
pathfinder goalnear

**Comment by rom1504** [comment]
1.20 is not supported yet

#3075

**Comment by tchereau** [comment]
> 1.20 is not supported yet
> 
> #3075

https://github.com/PrismarineJS/minecraft-data
`1.20 (1.20, 1.20.1)`

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer#features

minecraft-data != mineflayer
