### ISSUE TITLE
Strange log in the console

### ISSUE THREAD

**Issue by EuroZona** [PrismarineJS/mineflayer#3105]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: spigot
 - node: v18.12.1

## Detailed description of a problem
Chunk size is 56 but only 31 was read ; partial packet : {"name":"sound_effect","params":{"soundId":0,"soundCategory":23,"x":1701737577,"y":1954098789,"z":1852073330,"volume":4.360457892426154e+27,"pitch":273685596534839700000,"seed":[1701737472,100663202]}}; buffer :620017656e746974792e656e6465726d616e2e616d6269656e740005ffffa29400000320000163e13f8000003f77df7e97f88d3a3341f37e

i get this log every time i start the bot, it works but i don't want this to flood my console

my code
```
import { createBot } from 'mineflayer'

function joinBot() {
    const bot = createBot({
        auth: 'microsoft', // optional; by default uses mojang, if using a microsoft account, set to 'microsoft'
        host: 'play.valenamc.net', // minecraft server ip
        port: 25565,       // minecraft server port
        username: '*******', // minecraft username
        password: '*******',
        version: false,     // minecraft version
    })
    bot.on('spawn', () => {
        const playerFilter = (entity) => entity.type === 'player'
        const playerEntity = bot.nearestEntity(playerFilter)
        if (!playerEntity) return
        const pos = playerEntity.position.offset(0, 0, 0)
        bot.lookAt(pos, true)
        bot.setQuickBarSlot(0)
        bot.useOn(playerEntity)
    })
    bot.on('chat', (username, message) => {
        var date = new Date();
        var time = date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds();
        console.log(time + " " + username + ": " + message)
    })
    bot.on('kicked', () => {
        joinBot()
        console.log("Bot rejoined")
    })
}

joinBot()
```

**Comment by CordasMC** [comment]
Have you tried just setting the render distance?

**Comment by EuroZona** [comment]
it's not a render distance problem, chunk stand for the size of the packets

**Comment by EuroZona** [comment]
thx the update works.
