### ISSUE TITLE
unsupported/unknown protocol version: 761 (python)

### ISSUE THREAD

**Issue by GSstarGamer** [PrismarineJS/mineflayer#3112]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: Latest
 - server: vanilla
 - node: 18.12.1

## Detailed description of a problem
Using python 3.11, I have all my packages updated, but getting this error
`unsupported/unknown protocol version: 761, update minecraft-data`

## What did you try yet?
tried `npm update minecraft-data`
updated my npm

## Your current code
```py
from javascript import require, On, Once, AsyncTask, once, off
mineflayer = require('mineflayer')

random_number = id([]) % 1000  # Give us a random number upto 1000
BOT_USERNAME = f'colab_{random_number}'

bot = mineflayer.createBot(
    {'host': 'localhost', 'port': 25565, 'username': BOT_USERNAME, 'hideErrors': False})

# The spawn event
once(bot, 'login')
bot.chat('I spawned')
```

## Expected behavior
Join a server

## Additional context
None

**Comment by PondWader** [comment]
Try running `npm i mineflayer@latest`, if you installed mineflayer a long time ago, you may be a major version behind with minecraft-data in which case `npm update` won't work.

**Comment by GSstarGamer** [comment]
added 89 packages
But still not running.
Also this is Python

**Comment by GSstarGamer** [comment]
I have tried keeping an exact version, but for some reason it doesn't want to join
`Error: unsupported protocol version: 1.19.3`

**Comment by rom1504** [comment]
Delete your node_modules and try again

**Comment by GSstarGamer** [comment]
what exacty do i need to instal this is python?
also I alr did remove all node_mods

**Comment by extremeheat** [comment]
```
python -m javascript update
```

Will run npm update
