### ISSUE TITLE
Smooth Look Library

### ISSUE THREAD

**Issue by 182exe** [PrismarineJS/mineflayer#3118]
## Is your feature request related to a problem? Please describe.
Mineflayer's rotations are pretty rough and are easily detectable by anticheats, so it's fairly hard to get it to work on many servers.

## Describe the solution you'd like
I think an implementation of [this library](https://github.com/nxg-org/mineflayer-smooth-look), which allows for function based rotations into things like pathfinder and pvp would be very welcome.

## Describe alternatives you've considered
I linked mineflayer-smooth-look above, but I think it would just be better as something you could enable.

**Comment by frej4189** [comment]
This is not a Mineflayer issue. Consider opening an issue in pathfinder/PvP instead to allow for custom rotation methods
