### ISSUE TITLE
Unable to dismount - Error: dismount: not mounted

### ISSUE THREAD

**Issue by MikeSimpson** [PrismarineJS/mineflayer#3119]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.10.0
 - server: paper 1.20.1
 - node: 9.7.2

## Detailed description of a problem
When attempting to dismount a boat I get the following error. The player is on the boat as viewed in minecraft.
Error: dismount: not mounted
    at EventEmitter.dismount (/Users/mike/Documents/MC/node_modules/mineflayer/lib/plugins/entities.js:694:25)

## What did you try yet?

I have tried making the robot manually sneak as a fallback but that doesn't work either
## Your current code
```js

 bot.dismount();

```

## Expected behavior
Robot should dismount

**Comment by PondWader** [comment]
What are you doing to mount the bot on the boat, could you provide some code? It's working fine for me.

**Comment by extremeheat** [comment]
Reopen if you can still reproduce after running `npm update --depth 9999` and make sure to provide runnable code to reproduce
