### ISSUE TITLE
Information about nickname length

### ISSUE THREAD

**Issue by Norbiros** [PrismarineJS/mineflayer#3128]
## Is your feature request related to a problem? Please describe.
While working on a Minecraft bot using Mineflayer, I encountered an issue where I used a nickname longer than 16 characters. Unfortunately, Mineflayer did not provide any error messages or indications of the issue. Program was just stopping without any error. Even after attempting to debug the Minecraft protocol, no errors related to the nickname length were displayed.

## Describe the solution you'd like
I would like to see an error message implemented in Mineflayer to address this problem. When a nickname longer than 16 characters is detected, the error message should clearly inform the developer about the nickname length limitation.

**Comment by frej4189** [comment]
Binding to the error event of the bot should give you the information you require.

**Comment by Norbiros** [comment]
> Binding to the error event of the bot should give you the information you require.

I cant check it RN, but I am 99% sure it didn't print error. Only `end` event printed `socketClosed`.

**Comment by extremeheat** [comment]
Not all servers will have this restriction, so a blanket one can't be added to mineflayer. However, the server may be giving you *some* warning, you can enable debug logging to see the client/server packets before the disconnection.

To enable debug logging add `process.env.DEBUG = 'minecraft-protocol'` to the top of your script

**Comment by Norbiros** [comment]
```
  minecraft-protocol writing packet handshaking.set_protocol +0ms
  minecraft-protocol {
  minecraft-protocol   protocolVersion: 762,
  minecraft-protocol   serverHost: 'fw-pl-3.shieldia.pl',
  minecraft-protocol   serverPort: 30150,
  minecraft-protocol   nextState: 2
  minecraft-protocol } +0ms
  minecraft-protocol writing packet login.login_start +27ms
  minecraft-protocol {
  minecraft-protocol   username: 'Hejka_tu_lenka12031',
  minecraft-protocol   signature: null,
  minecraft-protocol   playerUUID: undefined
  minecraft-protocol } +0ms
```
It doesn't have any information about nickname

**Comment by extremeheat** [comment]
You would need to provide the entire console output, from the time you ran the program to the disconnection

**Comment by extremeheat** [comment]
Please provide your code and a screenshot of the terminal then after you ran your code. It doesn't seem right that'd be the only thing outputted.

**Comment by Norbiros** [comment]
This is my code:
```js
const mineflayer = require('mineflayer');
const { mineflayer: mineflayerViewer } = require('prismarine-viewer')

var bot = mineflayer.createBot({
  host: 'rgmc.pl',
  port: 25565,
  username: 'Hejka_tu_lenka123123123123',
  version: "1.19.4",
});

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)
bot.on('end', console.log)
bot.on('spawn', console.log)
```
![Screenshot from 2023-08-03 13-33-59](https://github.com/PrismarineJS/mineflayer/assets/89837724/cf06e074-129f-4474-b408-b20907cac574)

**Comment by extremeheat** [comment]
If Mojang allows you to have that username, and the server disconnects you for it, then the problem is on mojang side. The username you pass to the bot constructor is ignored when in online mode, and is only used for caching. The username you join as is determined by the Mojang authentication/session server. 

Since there is no message sent by the server there doesn't seem like any error clarification that can happen for the user (like throwing a  detailed exception). If it's a vanilla server I recommend opening an issue at bugs.mojang.com for this (client should be kicked and not abruptly disconnected).
