### ISSUE TITLE
entityHit - request to add entity hit check.

### ISSUE THREAD

**Issue by 1ProCrafters** [PrismarineJS/mineflayer#3138]
## Is your feature request related to a problem? Please describe.
I want to be able to check when a entity hit another entity, this will make it able to make bodyguards.

## Describe the solution you'd like
A check that is able to check when a entity hit another entity.

## Describe alternatives you've considered
I have implemented it so that the closest entity is considered the one that hit the other entity but it isnt always accurate.

## Additional context
Code:
`//When an entity gets harmed
		bots[0].on('entityHurt', (entity) => {
			//Ignore if the harmed entity is not the boss
			if (entity.username != bossName) return;

			//Select the entity that hurt the boss, by selecting the nearest entity that is not the boss or another Guard
			//This needs work :/
			target = bots[0].nearestEntity((entity) => {
				return (entity.username != bossName && !(entity.username || '').startsWith(prefix));
			});
		});`

**Comment by extremeheat** [comment]
It could be possible to write a plugin to infer the last damager by looking at the nearest player swing in their direction, but yeah it seems like this information is not sent by the server to the client at present so it can't be known/exposed by mineflayer.
