### ISSUE TITLE
Not sure if this is issue with mineflayer, but i think it is.

### ISSUE THREAD

**Issue by Heringen** [PrismarineJS/mineflayer#3167]
So i'm not much into coding myself, but my friend recently made a bot for minecraft which is supposed to log certain things from chat to discord server via webhooks.
Now that all works nicely, however i don't seem to be able to change which account it's logged in. First time i installed all the packages it told me it recognized first time usage and asked me to login into account - I logged into my main and now even if i delete everything related to bot and whole node_modules folder it always keeps loggin into same account and not asking me to change it.
Now as i said before i'm not into coding too much myself, but i know that it's creating the bot with mineflayer. I've tried changing password of used account, changing ip but it still somehow keeps data and ability to log into my main, making it impossible to log into my alt.
Any ideas/potential fixes?

**Comment by Heringen** [comment]
To add on it, i'm pretty sure issue is the nintendo connection you use, i can't quite sever it.

**Comment by rom1504** [comment]
where's the bot code

**Comment by Heringen** [comment]
> 

Ah my bad

https://github.com/Dutched420/Minecraft-Factions-Bot/tree/main

mineflayer is used in /src/minecraft/createBot.js
Or if you need it with node_modules installed: https://www.mediafire.com/file/my0kcg5kgqlkka1/Minecraft-Factions-Bot-main.rar/file

**Comment by rom1504** [comment]
config is in config.yaml

**Comment by Heringen** [comment]
> 

config.yml is for connecting webhooks, it doesn't handle account authentication

**Comment by rom1504** [comment]
https://github.com/Dutched420/Minecraft-Factions-Bot/blob/main/src/minecraft/createBot.js#L19 well you need to specify the username there

**Comment by Heringen** [comment]
um, where precisely? First time i logined, upon installing pakcages it led me on minecraft for nintendo switch confirmation page(detected my microsoft account and required code), i didn't even run the bot itself yet

**Comment by amoraschi** [comment]
The account is cached in .minecraft/nmp-cache, delete that folder and you will be able to login with another account

**Comment by lkwilson** [comment]
> The account is cached in .minecraft/nmp-cache, delete that folder and you will be able to login with another account

You can overwrite this value with the profilesFolder option when you call createBot. Typescript will complain, but it will work. Alternatively, you can call createClient directly. I use multiple accounts, so I do something like this:
```
createBot({
  username,
  profilesFolder: `profiles/${username}`,
  ...
})
```

**Comment by Heringen** [comment]
> The account is cached in .minecraft/nmp-cache, delete that folder and you will be able to login with another account

Thank you gentleman, it worked!



> > The account is cached in .minecraft/nmp-cache, delete that folder and you will be able to login with another account
> 
> You can overwrite this value with the profilesFolder option when you call createBot. Typescript will complain, but it will work. Alternatively, you can call createClient directly. I use multiple accounts, so I do something like this:
> 
> ```
> createBot({
>   username,
>   profilesFolder: `profiles/${username}`,
>   ...
> })
> ```

I will try this if i happen to need it sometimes, thanks!

**Comment by extremeheat** [comment]
The correct way to change your account is to not change the profile folder, but to change the set username.

**Comment by lkwilson** [comment]
> The correct way to change your account is to not change the profile folder, but to change the set username passed in `username` field.

Right but then it uses the auth token for the first account and logs into the wrong account. It might be a bug then?

**Comment by extremeheat** [comment]
It doesn't use the auth token for the first account, the account data cache is username specific. As long as a username field is specified.

**Comment by lkwilson** [comment]
I’ll try again to confirm but that’s not what happened for me last I tried

**Comment by lkwilson** [comment]
Yeah, idk what I did wrong previously, works just fine now
