### ISSUE TITLE
Proxy Socks5 causes partial packets

### ISSUE THREAD

**Issue by BloxMan00** [PrismarineJS/mineflayer#3186]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.10.1
 - server: vanilla/spigot/paper: Custom
 - node: Latest version

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

We're trying to connect a bot to a server using socks5 proxies to negate a ban.

## What did you try yet?
Did you try any method from the API?
Did you try any example? Any error from those?

We tried the socks5 package as suggested in a previously solved issue.

```js
var Socks  = require("socks5-client");
var mineflayer = require('mineflayer');

mineflayer.createBot({
  stream: Socks.createConnection({
    host: process.env.HOST,
    port: process.env.PORT,
    socksHost: process.env.PROXY,
    socksPort: process.env.PROXY_PORT,
    socksUsername: process.env.PROXY_USER,
    socksPassword: process.env.PROXY_PASSWORD
  }),
  username: process.env.EMAIL,
  password: process.env.PASSWORD,
  version: "1.15.2"
})
```

## Expected behavior

Expected behavior is to have to bot join the server using the sock5 proxy without issues.

## Additional context

2 impartial packets received upon start.

**Comment by PondWader** [comment]
This is not how you use a proxy. You need to pass a connect function, see https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md#how-can-i-use-a-socks5-proxy

Partial packets mean Mineflayer's packet definition are incorrect. If you want the packet definitions to be corrected you need to provide the version of the game you are connecting on and the errors.
