### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by gkursi** [PrismarineJS/mineflayer#3195]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.14.0
 - node: 18.17.0

## Detailed description of a problem
I am unable to login, it was working before, not anymore."
I can still login and play the game normally trough the launcher (with the same account).

## What did you try yet?

I tried updating the package ([#1520](https://github.com/PrismarineJS/mineflayer/issues/1520#issuecomment-749054783))
I tried logging in trough the launcher (it worked)

## Your current code
```js
const bot = mineflayer.createBot({
        host: argv["s"], // minecraft server ip
        username: argv["n"], // username or email, switch if you want to change accounts
        auth: 'microsoft', // for offline mode servers, you can set this to 'offline'
        // port: 25565,                // only set if you need a port that isn't 25565
        // version: false,             // only set if you need a specific version or snapshot (ie: "1.8.9" or "1.16.5"), otherwise it's set automatically
        // password: '12345678'        // set if you want to use password-based auth (may be unreliable). If specified, the `username` must be an email
    })
    bindEvents(bot);
/*
Some code here, replace this
*/


```

## Expected behaviour
Logging in to the given server with the given account

#### The error:
```
Error: Failed to obtain profile data for #########@gmail.com, does the account own minecraft?
    at Object.authenticate (C:\Users\#####\Documents\mineflayer_bot\node_modules\minecraft-protocol\src\client\microsoftAuth.js:31:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by gkursi** [comment]
works now, microsoft issue ig

**Comment by DereC4** [comment]
happening to my friends and I as well for our farming bots, using premium accounts (Microsoft); it fixes itself but we have to restart the program
