### ISSUE TITLE
Add an Offline Mode Support (Mojang is Deprecated so it didn't work)

### ISSUE THREAD

**Issue by ProSteveBedrock** [PrismarineJS/mineflayer#3199]
## Is your feature request related to a problem? Please describe.
Yes? I want to create an AFK Bot but i want to use Offline Mode but the mineflayer says can't login because of Mojang authentication server are offline.

## Describe the solution you'd like
Can you add an Offline mode for auth, for the bot not to authenticate using Mojang server, just proceed connecting to the server.

## Describe alternatives you've considered
...

## Additional context
Nothing bruh

**Comment by frej4189** [comment]
Authmode 'offline' already exists

**Comment by ProSteveBedrock** [comment]
Um oh ok my bad bruh
