### ISSUE TITLE
CI for 1.19 iterates over every 1.19.X versions, which makes it the slowest

### ISSUE THREAD

**Issue by szdytom** [PrismarineJS/mineflayer#3223]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
_Not Related_

## Detailed description of a problem
The CI check for version 1.19 is the slowest one because it iterates over all 1.19.X versions, and that is duplicate. It uses around 20 minutes while a normal one uses around 4 minutes.

## What did you try yet?
_Not Related_

## Your current code

https://github.com/PrismarineJS/mineflayer/blob/08208e2f110af2c6de41fac9a389597aac916412/.github/workflows/ci.yml#L33

Maybe it should be `1.19.1` instead of `1.19`.

## Expected behavior
Run tests on version 1.19 only instead of every 1.19.X versions.

**Comment by rom1504** [comment]
fixed
