### ISSUE TITLE
add some common chat patterns

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#323]
Make chat work on other servers than vanilla

example

``` js
bot.chatAddPattern(/^\[.*?(\w*) -> me \] (.*)$/, "whisper", "essentials whisper");
```

**Comment by Corgano** [comment]
bot.chatAddPattern(/^.*?(\w*) has requested (?:to teleport to you|that you teleport to them)\.$/, "tpRequest", "epicsb tpa request");
Matches request, with create an event tpRequest when matched. Does not discern between tpa or tpahere. handled wasily as such:
bot.on('tpRequest', function(username) {
  if ( username == "masterusername" ) {
    bot.chat("/tpyes")
  }
});

**Comment by rom1504** [comment]
Done

**Comment by SpyrowGr** [comment]
How do you make it tpaccept multiple people? do you just add more of these functions and change the masterusername?
