### ISSUE TITLE
Support Custom Auth (Blessing Skin)

### ISSUE THREAD

**Issue by lava114514** [PrismarineJS/mineflayer#3238]
## Describe the solution you'd like
Allow to use custom auth server in bot spawn like Blessing Skin(https://github.com/bs-community/blessing-skin-manual)

**Comment by SilkePilon** [comment]
This can already be done .createbot has an ‘auth’ option and session server option

**Comment by lava114514** [comment]
But how can i use it ? 
I can't find any introduction about it in readme or api.

**Comment by SilkePilon** [comment]
You need to check out prismarine auth repository. The auth setting can be set to a function that edits the main settings and them emits the session
