### ISSUE TITLE
Add a bot.isVisible(position) function 

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#324]
Line of sight

Something like this https://github.com/rom1504/rbot/blob/master/lib/nearest.js#L17

I'm not sure whether it should be in an internal or external plugin, but anyway it should be more standard.

**Comment by Corgano** [comment]
This should apply to blocks AND mobs. The same check could be used for trying to mine blocks or checking if the mob in range isn't behind a wall when you hit it.

**Comment by rom1504** [comment]
done
