### ISSUE TITLE
Cannot read properties of null (reading 'version') error

### ISSUE THREAD

**Issue by Crecheer** [PrismarineJS/mineflayer#3242]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.14.0
 - server: vanilla 1.20.1
 - node: 20.10.0

## Detailed description of a problem
The Bot isnt starting because of an error which i cant fix. 
## What did you try yet?
I tried many examples from other people but each had the same error, i also tried on offline and online servers but it still dosent work:
```
    const version = require('minecraft-data')(bot._client.version).version
                                                                  ^

TypeError: Cannot read properties of null (reading 'version')
    at next (C:\Users\jan\mcbot\node_modules\mineflayer\lib\loader.js:108:67)
    at Object.createBot (C:\Users\jan\mcbot\node_modules\mineflayer\lib\loader.js:105:34)
    at Object.<anonymous> (C:\Users\jan\mcbot\index.js:4:24)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
```

## Your current code
```js
const mineflayer = require('mineflayer')
const data = require('minecraft-data')

const bot = mineflayer.createBot({
  host: 'localhost',
  port: 25565,
  username: 'bot',
  auth: 'offline',
  version: '1.20'
})


bot.on('login', () => {
  console.log("Logged in")
})
```

## Expected behavior
The bot starts, and writes "Logged in" into the console

## Additional context
Win 11, kinda new to js, i did more html + js

**Comment by SilianZ** [comment]
Have you reinstalled the node modules?

**Comment by amoraschi** [comment]
The proper way to require minecraft-data is like this:
```js
const data = require('minecraft-data')(bot.version)
```
There are examples that show how to do it.
Alternatively you can use `bot.registry` to access minecraft-data directly without having to require it.
Close issue if solved.

**Comment by extremeheat** [comment]
In this case, it seems the error is because you are specifying 1.20 as version but your packages have not been updated to support 1.20.

Please run `npm update --depth 9999` and remove the `version` field -- it can be chosen automatically. Just keep in mind mineflayer does not support 1.20.2+.
