### ISSUE TITLE
entityHurt event is not working

### ISSUE THREAD

**Issue by jonvicbarcenas** [PrismarineJS/mineflayer#3253]
This part of the code is not workinf

bot.on('entityHurt', (entity) => {
  if (entity.type === 'mob') {
    bot.chat(`Haha! The ${entity.mobType} got hurt!`)
  } else if (entity.type === 'player') {
    bot.chat(`Aww, poor ${entity.username} got hurt. Maybe you shouldn't have a ping of ${bot.players[entity.username].ping}`)
  }
})

**Comment by amoraschi** [comment]
Hard to give support without you filling the issue form

**Comment by jonvicbarcenas** [comment]
it only works if i have torch left hand

**Comment by rom1504** [comment]
this is happening here https://github.com/PrismarineJS/mineflayer/blob/15cfeb4fa59edfcddf7a0b70a966294b24d798ed/lib/plugins/entities.js#L344

add some prints there / enable debug mode and fix it, then open a PR

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/issues/3184#issuecomment-1712908542
