### ISSUE TITLE
Unable to create bot

### ISSUE THREAD

**Issue by WnMrChen** [PrismarineJS/mineflayer#3258]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.14.0
 - server: vanilla
 - node: 20.10.0

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
```js
const { createBot } = require('mineflayer')

const bot = createBot({
    username: '#test_bot',
    host: host,
    port: 25565,
})


//.\node_modules\mineflayer\lib\plugins\game.js
//Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'the_end')
//    at handleRespawnPacketData (file:///E:/Code/Typescript/Wnbot5.0-TS/node_modules/mineflayer/lib/plugins/game.js:48:63)
const { minY, height } = bot.registry.dimensionsByName[bot.game.dimension]
//   bot.registry.dimensionsByName is undefined

```

## Expected behavior

successfully created

## Additional context

Bugs appeared after the update

**Comment by WnMrChen** [comment]
I found the problem. Prismarine-registry does not support 1.20.2

**Comment by wgaylord** [comment]
Actually its more of Mineflayer doesn't support 1.20.2 yet.  Since the DemensionCodec is now sent in the configuration state instead of the login packet.
