### ISSUE TITLE
Bot cannot jump repeatedly

### ISSUE THREAD

**Issue by Darthfett** [PrismarineJS/mineflayer#327]
When navigating using mineflayer-navigate, the bot is unable to jump as fast as necessary, due to physics.js preventing jumping from happening too quickly:  https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/physics.js#L99

This bug causes this: https://github.com/Darthfett/helperbot/issues/41

**Comment by rom1504** [comment]
Ah, good point !
That check was added to prevent the bot to jump to quickly was added to fix andrewrk/mineflayer#114 (which it did).
But apparently that's not exactly the correct fix.

We need to find the right way to allow both things to work correctly.

**Comment by Darthfett** [comment]
I wonder if physics.js is setting the bot.entity.onGround too quickly?  It
seems like the reason constantly jumping wouldn't work is because the
server doesn't realize we landed.

It would probably be good to look at the positions sent by the Notchian
client and mineflayer client and compare.  Maybe we could send a second
position update with the on-ground position when we are supposed to have
landed.
