### ISSUE TITLE
Strange Behavior When Switching Accounts

### ISSUE THREAD

**Issue by Mxdi** [PrismarineJS/mineflayer#3299]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.18.0
 - server: vanilla/spigot/paper Vanilla 1.16.5
 - node: 18.16.0
## Detailed description of a problem
I'm trying to switch between Minecraft accounts. However, it won't let me use usernames for both accounts. One account is able to login using the username (has an outlook) and the other account will only let me login if I put the email for the username field (has a gmail). Just curious if this issue is related to the type of email associated with the account. Or if its an issue residing in the package alone. Would really appreciate some help with a fix for this!

## What did you try yet?

I've tried debugging by using an email for the account with an outlook email and then the username for the account with the gmail but it just continues to log into the previously cached account.

## Your current code
```js
const bot = mineflayer.createBot({
       host: ip,
       username: username,
       auth: 'microsoft',
       port: port,
       version: version
})
```

## Expected behavior
To change accounts when I change the username field with another username

## Additional context
It does not change the account when providing another cached accounts' username. It will only swap when I put the email of the second account.

**Comment by Mxdi** [comment]
![image](https://github.com/PrismarineJS/mineflayer/assets/43386840/386cae24-0c5a-4ac2-9b8b-766462abc333)

**Comment by Mxdi** [comment]
I'm starting to believe that maybe I accidentally authenticated the Medi account when in browser when I was first logging into the "havrilla" account. How do I clear the user cache?

**Comment by extremeheat** [comment]
As written in the README:
> If auth is set to microsoft, you will be prompted to login to microsoft.com with a code in your browser. After signing in on your browser, the bot will automatically obtain and cache authentication tokens in the local file system so you don't have to sign-in again. **To switch the account, update the supplied username**. **By default, cached tokens will be stored in your user's .minecraft folder**. For more information on these options and others, see node-minecraft-protocol's [API doc](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/API.md#mccreateclientoptions).

The when auth is set to mojang and password auth is not being done, the username is just an identifier used for caching purposes. This should be made clearer in the readme. If you want to clear the cache you can go into the default profile dir in .minecraft/nmp-cache and clear that.

**Comment by Mxdi** [comment]
> As written in the README:
> 
> > If auth is set to microsoft, you will be prompted to login to microsoft.com with a code in your browser. After signing in on your browser, the bot will automatically obtain and cache authentication tokens in the local file system so you don't have to sign-in again. **To switch the account, update the supplied username**. **By default, cached tokens will be stored in your user's .minecraft folder**. For more information on these options and others, see node-minecraft-protocol's [API doc](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/API.md#mccreateclientoptions).
> 
> The when auth is set to mojang and password auth is not being done, the username is just an identifier used for caching purposes. This should be made clearer in the readme. If you want to clear the cache you can go into the default profile dir in .minecraft/nmp-cache and clear that.

Mojang auth isnt a thing anymore, mineflayer only uses microsoft. I'm confused on what you're trying to explain. The docs say you can use usernames for logging in with the bot??

**Comment by Mxdi** [comment]
Also /npm-cache is not a folder in my roaming/.minecraft

**Comment by Mxdi** [comment]
I see you're trying to say that I should be using emails instead of usernames for online mode = true? So how do I clear the cache to fix my issue? I can not find that folder.

**Comment by extremeheat** [comment]
`auth` can be set to `microsoft` or `offline`. The `username` field when auth is microsoft (by default) is just an identifier used for caching purposes to uniquely identify the account you sign in as it. It won't affect your in-game name.

**Comment by Mxdi** [comment]
> `auth` can be set to `microsoft` or `offline`. The `username` field when auth is microsoft (by default) is just an identifier used for caching purposes to uniquely identify the account you sign in as it. It won't affect your in-game name.

I don't think you have any understanding as to what I'm asking or saying.... Pretty much am just looking for Yes/No answers here. I'm 100% aware that it doesn't affect me in game. 

WHAT I ASKED WAS: 

1. Should I only be using emails to switch accounts with the username field?
2. How do I reset the cached accounts because I do not have the folder you specified in your earlier  comment? .minecraft/nmp-cache **DOES NOT EXIST**

**Comment by LucienHH** [comment]
Both of your questions have been answered quite clearly.

1. As explained, the username field  is used only as a unique identifier for caching no it does not need to be an email.

2. As the username is used to identify the cache changing it will prompt you to log in with new credentials

**Comment by extremeheat** [comment]
> Should I only be using emails to switch accounts with the username field?

No, but you can do that if you want

> How do I reset the cached accounts because I do not have the folder you specified in your earlier comment? .minecraft/nmp-cache DOES NOT EXIST

Pass the `profilesFolder` option and set a different directory, then you should see it. I can't explain what's going on your computer and where specific files are stored there, I can only explain the code as we have it
