### ISSUE TITLE
Bot is not attacking the mobs but detects them.

### ISSUE THREAD

**Issue by Scobrant** [PrismarineJS/mineflayer#3301]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.18.0 (npm audit = 4.1.0)
 - server: vanilla 1.20.1
 - node: 20.11.0

## Detailed description of a problem
I use the guard.js example in the repository but bot only moves to the guarding area and if there is a mob just stares on the mob.

## What did you try yet?
I have tried a few codes or adding attacking methods in the code but it doesn't work either

## Your current code

    const mineflayer = require('mineflayer')
    const { pathfinder, Movements, goals } = require('mineflayer-pathfinder')
    const pvp = require('mineflayer-pvp').plugin
    
    const bot = require("./net")
    
    function guard() {
	bot.loadPlugin(pathfinder)
	bot.loadPlugin(pvp)

	let guardPos = null

	// Assign the given location to be guarded
	function guardArea (pos) {
	guardPos = pos

	// We we are not currently in combat, move to the guard pos
	if (!bot.pvp.target) {
		moveToGuardPos()
	}
	}

	// Cancel all pathfinder and combat
	function stopGuarding () {
	guardPos = null
	bot.pvp.stop()
	bot.pathfinder.setGoal(null)
	}

	// Pathfinder to the guard position
	function moveToGuardPos () {
	bot.pathfinder.setMovements(new Movements(bot))
	bot.pathfinder.setGoal(new goals.GoalBlock(guardPos.x, guardPos.y, guardPos.z))
	}

	// Called when the bot has killed it's target.
	bot.on('stoppedAttacking', () => {
	if (guardPos) {
		moveToGuardPos()
	}
	})

	// Check for new enemies to attack
	bot.on('physicsTick', () => {
	if (!guardPos) return // Do nothing if bot is not guarding anything

	// Only look for mobs within 16 blocks
	const filter = e => e.type === 'mob' && e.position.distanceTo(bot.entity.position) < 16 &&
						e.displayName !== 'Armor Stand' // Mojang classifies armor stands as mobs for some reason?

	const entity = bot.nearestEntity(filter)
	if (entity) {
		// Start attacking
		bot.pvp.attack(entity)
	}
	})

	// Listen for player commands
	bot.on('chat', (username, message) => {
	// Guard the location the player is standing
	if (message === 'guard') {
		const player = bot.players[username]

		if (!player) {
		bot.chat("I can't see you.")
		return
		}

		bot.chat('I will guard that location.')
		guardArea(player.entity.position)
	}

	// Stop guarding
	if (message === 'stop') {
		bot.chat('I will no longer guard this area.')
		stopGuarding()
	}
	})
      }

    module.exports = guard;

/*
        bot.chat('I will guard that location.')
	        guardArea(player.entity.position)
                bot.attack(entity)
*/

```

## Expected behavior
I think it should attack but there is smh that doesn't work with my mineflayer etc. because this is the official code.

**Comment by dylanrobinett** [comment]
It's because there are different mob types that the game recognizes. I ran into this same issue. Change `e.type === 'mob' ` to `e.type === 'hostile'` and this might fix your issue. For some reason minecraft was recognizing 'mob' as slime, golem, allay, phantom, and couple other weird ones so once you make this change they won't attack those mobs but they will attack the main ones that you most commonly run into.

You might also need to change a couple things in gaurd.js but I don't remember, I had to fix the physicstick error in guard.js. I have code very similar to this let me know if you want it. I changed it so that it will guard but I can also command it to attack specific players by their player name.

**Comment by Scobrant** [comment]
> It's because there are different mob types that the game recognizes. I ran into this same issue. Change `e.type === 'mob' ` to `e.type === 'hostile'` and this might fix your issue. For some reason minecraft was recognizing 'mob' as slime, golem, allay, phantom, and couple other weird ones so once you make this change they won't attack those mobs but they will attack the main ones that you most commonly run into.
> 
> You might also need to change a couple things in gaurd.js but I don't remember, I had to fix the physicstick error in guard.js. I have code very similar to this let me know if you want it. I changed it so that it will guard but I can also command it to attack specific players by their player name.

Thank you for your help. Yes it worked, now it works but I think someone needs to correct the code.

**Comment by Scobrant** [comment]
You need to change `e.type === "mob"` to` e.type === "hostile"`
