### ISSUE TITLE
Bot not send captha cod in chat

### ISSUE THREAD

**Issue by DARKSEh** [PrismarineJS/mineflayer#3333]
const mineflayer = require('mineflayer');
const readline = require('readline');
const {mapDownloader} = require('mineflayer-item-map-downloader');
const { userInfo } = require('os');
const fs = require('fs');
const { create } = require('domain');
const mineflayerViewer = require('prismarine-viewer').mineflayer
const Jimp = require('jimp');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const bot = mineflayer.createBot({
  host: 'mc.HolyWorld.ru', // Minecraft сервер
  username: 'Ocholko', // Имя пользователя
  auth: 'offline', // Режим аутентификации
  version: '1.16.5', // Версия Minecraft
});

// Событие при получении сообщения от пользователя в консоли
rl.on('line', (input) => {
  bot.chat(input);
});

// Событие при получении сообщения от другого игрока
bot.on('message', (username, message) => {
  console.log(`${username}: ${message}`);
});

bot.loadPlugin(mapDownloader)
bot.once('login', () => {
  bot.chat('qq')
})

function img_create() {
  // Загрузка всех изображений в новом порядке
let images = [
  "C:/Users/WhichMoon/Desktop/map_000011.png",
  "C:/Users/WhichMoon/Desktop/map_000010.png",
  "C:/Users/WhichMoon/Desktop/map_000008.png",
  "C:/Users/WhichMoon/Desktop/map_000009.png", // Поменяли местами с map_00007.png
  "C:/Users/WhichMoon/Desktop/map_000007.png", // Поменяли местами с map_00009.png
  "C:/Users/WhichMoon/Desktop/map_000006.png",
  "C:/Users/WhichMoon/Desktop/map_000005.png",
  "C:/Users/WhichMoon/Desktop/map_000004.png",
  "C:/Users/WhichMoon/Desktop/map_000003.png",
  "C:/Users/WhichMoon/Desktop/map_000002.png",
  "C:/Users/WhichMoon/Desktop/map_000001.png",
  "C:/Users/WhichMoon/Desktop/map_000000.png"
];

// Создание нового изображения размером 4x3 (4 столбца и 3 строки)
const finalImage = new Jimp(4 * 128, 3 * 128); // Размер каждой картинки 128x128

// Координаты для каждой ячейки в соответствии с новым желаемым порядком
const coordinates = [
  [0, 0],    // [11]
  [128, 0],  // [10]
  [384, 0],  // [9]
  [256, 0],  // [8]
  [0, 128],  // [7]
  [128, 128],// [6]
  [256, 128],// [5]
  [384, 128],// [4]
  [0, 256],  // [2]
  [128, 256],// [3]
  [256, 256],// [1]
  [384, 256] // [0]
];

// Объединение изображений в нужном порядке
for (let i = 0; i < images.length; i++) {
  Jimp.read(images[i], (err, image) => {
      if (err) throw err;

      finalImage.blit(image, coordinates[i][0], coordinates[i][1]);

      // Сохранение результирующего изображения после объединения всех картинок
      if (i === images.length - 1) {
          finalImage.write('C:/Users/WhichMoon/Desktop/result.jpg', (err) => {
              if (err) throw err;
              console.log('Итоговое изображение сохранено на рабочем столе.');
          });
      }
  });
}
}

setTimeout(img_create, 2500)

function captha_log(){
  const axios = require('axios');
  const fs = require('fs');

  // Ваш ключ API RuCaptcha
  const apiKey = 'Апи не палю';

  // Путь к файлу с изображением капчи на рабочем столе
  const imagePath = 'C:/Users/WhichMoon/Desktop/result.jpg';

  // Чтение изображения как base64
  const imageBase64 = fs.readFileSync(imagePath, { encoding: 'base64' });

  // Отправляем изображение на RuCaptcha для решения
  axios.post('http://rucaptcha.com/in.php', {
      method: 'base64',
      key: apiKey,
      body: imageBase64
  })
  .then(response => {
      const captchaID = response.data.split('|')[1]; // Получаем ID решаемой капчи

      // Проверяем результат с интервалом в 5 секунд
      const interval = setInterval(() => {
          axios.get(`http://rucaptcha.com/res.php?key=${apiKey}&action=get&id=${captchaID}`)
          .then(response => {
              const result = response.data;

              if (result.includes('OK')) {
                  const captchaSolution = result.split('|')[1];
                  console.log(captchaSolution);
                  clearInterval(interval); // Останавливаем проверку результата
                  
              } else if (result !== 'CAPCHA_NOT_READY') {
                  console.log('Произошла ошибка при решении капчи.');
                  clearInterval(interval); // Останавливаем проверку результата
              }
          })
          .catch(error => {
              console.error('Ошибка при проверке результата капчи:', error);
          });
      }, 1000); 
  })
  .catch(error => {
      console.error('Ошибка при отправке капчи на RuCaptcha:', error);
  });
}

setTimeout(captha_log, 1500)

bot.on('kicked', console.log)
bot.on('error', console.log)

Бот заходит на сервер получает капчу в виде карты  объеденяет посылает через апи его решать. Приходит код но бот его не выводит в чат помогите пожалуйста!
The bot enters the server, receives a captcha in the form of a card, sends it via the API and solves it. The code arrives, but the bot does not display it in the chat, please help!

**Comment by amoraschi** [comment]
This code is badly formatted and it is in Russian (probably). Put it in a codeblock and narrow down the issue

**Comment by DARKSEh** [comment]
`const mineflayer = require('mineflayer');
const readline = require('readline');
const {mapDownloader} = require('mineflayer-item-map-downloader');
const { userInfo } = require('os');
const fs = require('fs');
const { create } = require('domain');
const mineflayerViewer = require('prismarine-viewer').mineflayer
const Jimp = require('jimp');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const bot = mineflayer.createBot({
  host: 'mc.HolyWorld.ru', // Minecraft server
  username: 'Ocholko', // Username
  auth: 'offline', // Authentication mode
  version: '1.16.5', // Minecraft version
});

// Event when receiving message from user in console
rl.on('line', (input) => {
  bot.chat(input);
});

// Event when receiving message from another player
bot.on('message', (username, message) => {
  console.log(`${username}: ${message}`);
});

bot.loadPlugin(mapDownloader)
bot.once('login', () => {
  bot.chat('qq')
})

function img_create() {
  // Load all images in a new order
let images = [
  "C:/Users/WhichMoon/Desktop/map_000011.png",
  "C:/Users/WhichMoon/Desktop/map_000010.png",
  "C:/Users/WhichMoon/Desktop/map_000008.png",
  "C:/Users/WhichMoon/Desktop/map_000009.png", // Swapped with map_00007.png
  "C:/Users/WhichMoon/Desktop/map_000007.png", // Swapped with map_00009.png
  "C:/Users/WhichMoon/Desktop/map_000006.png",
  "C:/Users/WhichMoon/Desktop/map_000005.png",
  "C:/Users/WhichMoon/Desktop/map_000004.png",
  "C:/Users/WhichMoon/Desktop/map_000003.png",
  "C:/Users/WhichMoon/Desktop/map_000002.png",
  "C:/Users/WhichMoon/Desktop/map_000001.png",
  "C:/Users/WhichMoon/Desktop/map_000000.png"
];

// Create a new image with size 4x3 (4 columns and 3 rows)
const finalImage = new Jimp(4 * 128, 3 * 128); // Each image size is 128x128

// Coordinates for each cell according to the new desired order
const coordinates = [
  [0, 0],    // [11]
  [128, 0],  // [10]
  [384, 0],  // [9]
  [256, 0],  // [8]
  [0, 128],  // [7]
  [128, 128],// [6]
  [256, 128],// [5]
  [384, 128],// [4]
  [0, 256],  // [2]
  [128, 256],// [3]
  [256, 256],// [1]
  [384, 256] // [0]
];

// Merge images in the desired order
for (let i = 0; i < images.length; i++) {
  Jimp.read(images[i], (err, image) => {
      if (err) throw err;

      finalImage.blit(image, coordinates[i][0], coordinates[i][1]);

      // Save the resulting image after merging all images
      if (i === images.length - 1) {
          finalImage.write('C:/Users/WhichMoon/Desktop/result.jpg', (err) => {
              if (err) throw err;
              console.log('Final image saved on desktop.');
          });
      }
  });
}
}


setTimeout(img_create, 2500)
let captchaSolution

function captha_log(){
  const axios = require('axios');
  const fs = require('fs');

  // Your RuCaptcha API key
  const apiKey = '65b8e53a8140014f435996036edc50e0';

  // Path to the captcha image file on desktop
  const imagePath = 'C:/Users/WhichMoon/Desktop/result.jpg';

  // Read the image as base64
  const imageBase64 = fs.readFileSync(imagePath, { encoding: 'base64' });

  // Send the image to RuCaptcha for solving
  axios.post('http://rucaptcha.com/in.php', {
      method: 'base64',
      key: apiKey,
      body: imageBase64
  })
  .then(response => {
      const captchaID = response.data.split('|')[1]; // Get the ID of the captcha being solved

      // Check the result with an interval of 5 seconds
      const interval = setInterval(() => {
          axios.get(`http://rucaptcha.com/res.php?key=${apiKey}&action=get&id=${captchaID}`)
          .then(response => {
              const result = response.data;

              if (result.includes('OK')) {
                  captchaSolution = result.split('|')[1];
                  console.log(captchaSolution);
                  clearInterval(interval); // Stop checking the result
                  
              } else if (result !== 'CAPCHA_NOT_READY') {
                  console.log('An error occurred while solving the captcha.');
                  clearInterval(interval); // Stop checking the result
              }
          })
          .catch(error => {
              console.error('Error checking captcha result:', error);
          });
      }, 1000); 
  })
  .catch(error => {
      console.error('Error sending captcha to RuCaptcha:', error);
  });
}

setTimeout(captha_log, 1500)
function bot_call(){
  bot.on('game', () => {
    bot.chat(captchaSolution)
})
}
setTimeout(bot_call, 3000)


bot.on('kicked', console.log)
bot.on('error', console.log)
`
"In general, when the solved captcha arrives, the bot does not want to display it in the chat. Or simply the chat is unavailable. What other method can be used?"
