### ISSUE TITLE
React to a message sent by the server without username

### ISSUE THREAD

**Issue by PeterTTTW** [PrismarineJS/mineflayer#3352]
Hello, i want my bot to react to a message like "([Server Gamemode] A Game  is starting in 60 seconds! Join by typing /join)". Im already using a message react methode, but it only works on messages from users. How do i make my bot react to this kind of messages.
Best wishes x

**Comment by extremeheat** [comment]
This should definitely be sent on the `message` event. I recommend adding
```js
bot.on('message', console.log)
```
To check. The message position should be set to `system`.

**Comment by PeterTTTW** [comment]
Hello, thanks for the fast answer.  My code is looking like this, what do you mean by position to system? Best wishes x 
this.bot.on('message', async( system, message, username) =>{
          

if (username === this.bot.username) return

          if(message=== " A game is starting in 60 seconds! Join by typing /join")
          {
            //what he does
          }

**Comment by PeterTTTW** [comment]
Did it myself. If anyone wants to know the code:
`this.bot.on('message', async( jsonMsg, message, ) =>{
            console.log(jsonMsg.toString()) // Example chat message
          	const mesg = jsonMsg.toString();
            if(mesg==="SUCCESS! You just received 1 > Common Crate < key(s)!")
              {
                this.bot.chat("/home")

              }`
