### ISSUE TITLE
Attacking on Pre Motion instead of Post.

### ISSUE THREAD

**Issue by 182exe** [PrismarineJS/mineflayer#3358]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.20.1
 - server: vanilla/spigot/paper 1.8.9
 - node: 18.18.0

## Detailed description of a problem
When using bot.attack(Entity), bot sends attack packets after motion packets instead of before, which is not vanilla behavior and causes bans on most anticheats. 

## What did you try yet?
P1XEL suggested I make a custom event in the tickPhysics function to handle it, but I don't know how to use that to fix this.

Did you try any method from the API? Yeah.
Did you try any example? Any error from those? Yes, any instance with bot.attack() causes it.

## Your current code
```js
if (bot.entityAtCursor(3)) {
    bot.attack(bot.entityAtCursor(3));
}
```

## Expected behavior
Send attack packets before motion is applied to the player.

## Additional context
None.

**Comment by extremeheat** [comment]
This is because the methods in question are returning Promises that you are not waiting for. Most mineflayer API methods return promises which means you should await them all with few exceptions, please see the API doc and types file.

**Comment by 182exe** [comment]
sorry if i'm misunderstanding, basically i just have to await bot.attack?

**Comment by 182exe** [comment]
@extremeheat ^
