### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'blocksByName')

### ISSUE THREAD

**Issue by Krstf01** [PrismarineJS/mineflayer#3362]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.20.1 (latest)
 - server: vanilla/spigot/paper 1.20.2 (Purpur)
 - node: 20.9.0

## Detailed description of a problem
The bot is not even able to load.

## What did you try yet?
I tried to use the pathfinder plugin, but it thrown this error: "TypeError: Cannot read properties of undefined (reading 'blocksByName')"

## Your current code
```js

const defaultMove = new Movements(bot)

```

## Expected behavior
No errors at start or at any point.

## Additional context
The other parts of my code worked without the line i highlited before.

**Comment by extremeheat** [comment]
You did not provide any code, so it's not possible to say more without looking at it. You are likely not waiting for the correct events. Copy the code from https://github.com/PrismarineJS/mineflayer/blob/master/examples/pathfinder/gps.js
