### ISSUE TITLE
Do not have protocol data for protocol version 766 (attempted to use 763 data)

### ISSUE THREAD

**Issue by AlphaArchangel** [PrismarineJS/mineflayer#3371]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.20.1
 - server: vanila | paper 1.20.6
 - node: 20.10.0

## Detailed description of a problem
I'm trying to connect a mineflayer bot to minecraft 1.20.6 server. It worked fine in 1.20.4, but when I updated the server to 1.20.6 it all the bots stopped connecting and it is giving me the error `Do not have protocol data for protocol version 766 (attempted to use 763 data)` How can I fix it? Thank you!

![error](https://github.com/PrismarineJS/mineflayer/assets/116897242/a985b825-5621-45e7-83ea-4e6e2fb7a085)

**Comment by extremeheat** [comment]
The error is correct, 1.20.5+ is not currently supported

**Comment by AlphaArchangel** [comment]
Okay, Thank you! @extremeheat

**Comment by MaxtorCoder** [comment]
Any idea on when this will be supported?
