### ISSUE TITLE
1.20.6

### ISSUE THREAD

**Issue by bvandenbon** [PrismarineJS/mineflayer#3405]
The readme states that mineflayer is compatible with 1.20,
however it is not with the latest version of 1.20.

I'm just wondering if support for 1.20.6 will be provided in the future?

**Comment by extremeheat** [comment]
Related
https://github.com/PrismarineJS/node-minecraft-protocol/issues/1305
https://github.com/PrismarineJS/node-minecraft-protocol/issues/1306

It must be supported upstream in node-minecraft-protocol and minecraft-data. There is work for 1.20.5 ongoing in https://github.com/PrismarineJS/minecraft-data/pull/884, contributions are welcome.

**Comment by JosephLahiru** [comment]
Hey, @extremeheat is there a guide for contributions? Any video tutorial resources or documentation are welcome. We are happy to help. Thank you!

**Comment by extremeheat** [comment]
There is no doc for it, it's manually updated by looking at wiki.vg or code changes. I'd recommend looking through the past update PRs to get an idea for what needs to be changed.

There is a #contribute room in our Discord (link in README) where you can talk if you need help with something

**Comment by rom1504** [comment]
this is done
