### ISSUE TITLE
я хочу сохранить капчу в виде картинки, которую видит бот, пробовал **item-map-downloader,** сохранило 6 перевернутых картин из 15 и в разном порядке, приложил фотографию капчи

### ISSUE THREAD

**Issue by wristikl** [PrismarineJS/mineflayer#3409]
я хочу сохранить капчу в виде картинки, которую видит бот, пробовал **item-map-downloader,** сохранило 6 перевернутых картин из 15 и в разном порядке, приложил фотографию капчи
![IMG_20240626_203836_158](https://github.com/PrismarineJS/mineflayer/assets/167366943/068db49b-d3bb-4e06-80dc-bb58241b3fea)

_Originally posted by @wristikl in https://github.com/PrismarineJS/mineflayer/discussions/3408_

**Comment by K1FFDAME** [comment]
Пробовал Print screen? Если не поможет можно на телефон сфоткать

**Comment by K1FFDAME** [comment]
Ну смотря в каком формате можно jpeg или WEbm но другие спецификации там

**Comment by apchhui** [comment]
как ты решил проблему?
