### ISSUE TITLE
bot.openContainer(chest) in paper server return timeout error

### ISSUE THREAD

**Issue by Little-YangYang** [PrismarineJS/mineflayer#3459]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.20.1
 - server: paper 1.20.4
 - node: 18.18.0

## Detailed description of a problem
When trying to open a chest using bot.openContainer(chest), I get the following error:

` Error: Event windowOpen did not fire within timeout of 20000ms`

This only occurs on my localhost Paper 1.20.4 test server. However, when I use the same bot code in a single-player LAN world (vanilla 1.20.4 with Fabric), the openContainer method works as expected, and I can successfully retrieve the chest contents with chestWindow.containerItems().

## What did you try yet?
I wrote a function that navigates the bot to the chest using bot.pathfinder.goto with GoalNear and then calls openContainer. However, on my Paper server, this results in the timeout error mentioned above.

I then switched to a single-player LAN world without changing the bot's code (except for the server port), and everything worked perfectly. The bot could open the chest, and I retrieved the items successfully.

## Your current code

``` ts
class Bot {
    private bot: mineflayer.Bot;
}
```

```ts
async function findAllChests(bot: Bot, direction: 'left' | 'right'): Promise<Vec3[]> {
    const chest_id = bot.getMCData().blocksByName['chest'].id;
    return bot.getBot().findBlocks({
        matching: function (block: Block) {
            // if (block.type === chest_id) {
            //     bot.logger.info(block.getProperties().type);
            // }
            return block.type === chest_id && (block.getProperties().type === 'single' || block.getProperties().type === 'left');
        },
        useExtraInfo: true,
        maxDistance: 64,
        count: 100
    });
}

async function openChest(bot: Bot, chestPostionVec3: Vec3) {
    const chest = bot.getBot().blockAt(chestPostionVec3);
    await bot.getBot().pathfinder.goto(new GoalNear(chestPostionVec3.x, chestPostionVec3.y, chestPostionVec3.z, 1));

    if (chest) {
        bot.logger.info('open chest:', chestPostionVec3);
        try {
            let chestWindow = await bot.getBot().openContainer(chest);
            let items = chestWindow.containerItems();
            bot.logger.info('chest position: ', chestPostionVec3, 'items:', items.map(item => item.customName? item.customName : item.name));
            bot.getBot().closeWindow(chestWindow);
        } catch (error) {
            bot.logger.error('Failed to open chest\n', error);
        }
    }
}

async function scanChest(bot: Bot, direction: 'left' | 'right') {
    let chests = await findAllChests(bot, direction);
    bot.logger.info('Found chests: ' + chests.length, chests);
    for (let chest of chests) {
        await openChest(bot, chest);
    }
}
```

## Expected behavior
The bot should successfully open the chest and retrieve its contents without timing out or encountering any errors. This behavior is expected to be consistent across both vanilla and Paper servers.

## Additional context
* The issue occurs only on a Paper 1.20.4 server; the same bot code works fine in a vanilla single-player LAN world.
* The Paper server has no special plugins installed. I've tested with a fresh install and default settings, but the issue persists.
* No other chest-related issues occur when playing the game manually—only the bot experiences this problem.

**Comment by Little-YangYang** [comment]
after check, bot don't have permission to open container, everything goes well after `/op bot`

**Comment by Starry-Sky-World** [comment]
> after check, bot don't have permission to open container, everything goes well after `/op bot`检查后 bot 没有打开容器的权限，`/op bot` 后一切顺利

啊怎么检查？普通玩家可以打开啊
