### ISSUE TITLE
Couple Problems.

### ISSUE THREAD

**Issue by Darkfield** [PrismarineJS/mineflayer#347]
http://pastebin.com/PWSSMYJD

bot.players doesn't work

        bot.once('login', function() {
            setTimeout(function() {
                console.info('FIRE');
                bot.chat('/register 2222 2222');
            }, 3100);

Doesn't work too.

**Comment by rom1504** [comment]
That works just fine:
```js
var mc = require('minecraft-protocol');
var mineflayer = require('mineflayer');

var ips = [];
var listP = [];
var int = 0;
var tries = 0;
var skaicius = 0;


function makeClient() {
    if (skaicius <= 1) {
        var bot = mineflayer.createBot({
            host: "localhost", // optional
            port: 25565, // optional
            username: makeid(), // email and password are required only for 
        });

        bot.on('connect', function() {
            console.info('connected');
            skaicius++;
        });

	  bot.once('spawn', function() {
        setTimeout(function() {
            console.info('FIRE');
		console.log(bot.players);
            bot.chat('/register 2222 2222');
        }, 3100);
});
        bot.once('login', function() {
            setTimeout(function() {
                console.info('FIRE');
                bot.chat('/register pedsakas2 pedsakas2');
            }, 3100);
            setInterval(function() {
                listP = bot.players;
                bot.chat('Sis servas uzsidaro pyzdinkit is cia' + listP.length);
            }, 4100);
        });

        bot.on('end', function() {
            console.info('disconnected ' + skaicius);
            skaicius--;
        });

        bot.on('kicked', function(reason) {
            console.info('kicked ' + skaicius);
            skaicius--;
        });

        bot.on('error', function(err) {
            console.log(err.stack);
        });
		

        console.info(skaicius);
    };
}

function makeid() {
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz123456789";

    for (var i = 0; i < 14; i++)
        text += possible.charAt(Math.floor(Math.random() * possible.length));

    return text;
}

makeClient();
```

I removed the part of the code I couldn't run (because I don't have that list of proxies)

so
* bot.players works
* `/register` is specific to your plugin, which plugin is it ?
* `bot.on('spawn'` works

anything else ?

**Comment by Darkfield** [comment]
spawn doesn't work, it worked because you forgot to remove this piece of code:

bot.once('login', function() {
            setTimeout(function() {
                console.info('FIRE');
                bot.chat('/register pedsakas2 pedsakas2');
            }, 3100);
            setInterval(function() {
                listP = bot.players;
                bot.chat('Sis servas uzsidaro pyzdinkit is cia' + listP.length);
            }, 4100);
        });

**Comment by rom1504** [comment]
I can't see why removing this would make spawn break.
Can you provide minimal code (without the proxies list and all that I don't have)  example where spawn doesn't work ? (And the server where it doesn't work ? For example spigot)

**Comment by Darkfield** [comment]
I used your provided code, and removed only that piece.

**Comment by rom1504** [comment]
And `console.log(bot.players);` (in spawn) doesn't get printed on a vanilla server ? (It did for me)

**Comment by Darkfield** [comment]
On spigot it doesn't for me.

**Comment by rom1504** [comment]
So apparently this was due to using a too old spigot version.

Feel free to reopen (or open an other issue), if you have more problems.
