### ISSUE TITLE
Mineflayer Python - No Module Error While Requiring Pathfinder

### ISSUE THREAD

**Issue by SiyahEkran** [PrismarineJS/mineflayer#3473]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.20.1
 - server: vanilla/spigot/paper 1.16.5
 - node: 20.18.0

## Detailed description of a problem
Everytime i try to require "mineflayer-pathfinder", i get this error: 🌉 Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'mineflayer-pathfinder' imported from C:\Users\umbal\AppData\Local\Programs\Python\Python312\Lib\site-packages\javascript\js\deps.js
But I HAVE the mineflyer-pathfinder and its version is 2.4.5. BTW I am using the python version of mineflayer

## What did you try yet?
I tried reinstalling both node and nvm, test it out in another version of minecraft, etc.

## Your current code
from javascript import require, On, Once, AsyncTask, once, off
import random, time
mineflayer = require('mineflayer')
pathfinder = require('mineflayer-pathfinder')

## Expected behavior
I want this problem to be solved ASAP.

**Comment by rom1504** [comment]
Did you install that module?

**Comment by SiyahEkran** [comment]
yep i've installed and the problem just got fixed after a reboot
