### ISSUE TITLE
When will it support 1.21.1 ?

### ISSUE THREAD

**Issue by Mashfiqur25** [PrismarineJS/mineflayer#3476]
Mineflayer is working perfectly with 1.20.4 or lower versions, But I am waiting for the update when it will also work on 1.21.1 version of minecraft. 

Please make this update in this wonderful plugin.

**Comment by GenerelSchwerz** [comment]
Duplicate. See #3406 .

**Comment by MightyPiggie** [comment]
It will be supported faster if you try to help debugging the current issues. See #3412 for current status.

**Comment by rom1504** [comment]
dup
