### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by jakibaki** [PrismarineJS/mineflayer#348]
Is there a way to access the scoreboard in mineflayer? I cant seem to find one in the documentation.

**Comment by rom1504** [comment]
No it's not possible with mineflayer api currently. 
If you need it you could implement it using these packets http://prismarinejs.github.io/minecraft-data/?d=protocol#toClient_scoreboard_objective 
(bot._client.on('scoreboard_objective',function(packet){...});

I would accept a PR to do this ;)

**Comment by jakibaki** [comment]
Submitted pull request :)

**Comment by rom1504** [comment]
I think we'll close this when the PR is merged (when I have time to review it, test it and all)

**Comment by jakibaki** [comment]
Ok

**Comment by rom1504** [comment]
Basic functionality is there but I think we're missing a few things (see in http://wiki.vg/Protocol#Scoreboard_Objective) : 
* [ ] handle the actions (removing/updating) properly
* [ ] store the Type

Let's close this issue when that will be done ;)

**Comment by rom1504** [comment]
now done, thanks @wvffle
