### ISSUE TITLE
Cracked and normal acc

### ISSUE THREAD

**Issue by RechixAlt** [PrismarineJS/mineflayer#3481]
So ive seen videos about this, and all of them used cracked accounts, is it possible to use an actual minecraft account?

**Comment by RechixAlt** [comment]
If it does work how?

**Comment by extremeheat** [comment]
Set `  auth: 'microsoft' // for offline mode servers, you can set this to 'offline'` in the createClient options.

**Comment by RechixAlt** [comment]
> Set ` auth: 'microsoft' // for offline mode servers, you can set this to 'offline'` in the createClient options.

how do i add my credentials? or like the login to my account
