### ISSUE TITLE
EntityHurt is not working at 1.20.0

### ISSUE THREAD

**Issue by ErneTalu** [PrismarineJS/mineflayer#3501]
Im using lastest version of Mineflayer and Minecraft 1.20.0. I tried everything but bot.on("entityHurt" is not working. I dont know the other versions but in 1.20.0 with Mineflayer it isnt working. The other entity actions are working but entityHurt is not

**Comment by rom1504** [comment]
Enable debug mode then report packets and reproduction instructions

**Comment by u9g** [comment]
We store entity_status's in mineflayer itself as a map https://github.com/PrismarineJS/mineflayer/blob/3d6e2344751c38428701dc52e9f29dda73f7f782/lib/plugins/entities.js#L22-L30

this is no longer how entity_hurts are received by the client, it is now it's own packet (`hurt_animation`) which needs to make the same event. PR's welcome :D

**Comment by Pix3lPirat3** [comment]
Related issue https://github.com/PrismarineJS/mineflayer/issues/3184

**Comment by miles-igd** [comment]
I'm testing the "hurt_animation" and it seems to only fire when the bot itself gets hurt. It doesn't trigger when a different mob gets hit, which is what I think entityHurt was used for.

Should "damage_event" packet which has the entityId in it, be used instead?

I tested this in 1.20 and 1.21.1 and it should behave the same.
```js
bot._client.on('damage_event', (packet) => {
    const entity = bot.entities[packet.entityId];
    bot.emit('entityHurt', entity);
})
```

**Comment by ErneTalu** [comment]
> I'm testing the "hurt_animation" and it seems to only fire when the bot itself gets hurt. It doesn't trigger when a different mob gets hit, which is what I think entityHurt was used for.
> 
> Should "damage_event" packet which has the entityId in it, be used instead?
> 
> I tested this in 1.20 and 1.21.1 and it should behave the same.
> 
> ```js
> bot._client.on('damage_event', (packet) => {
>     const entity = bot.entities[packet.entityId];
>     bot.emit('entityHurt', entity);
> })
> ```

Thanks

**Comment by ErneTalu** [comment]
> I'm testing the "hurt_animation" and it seems to only fire when the bot itself gets hurt. It doesn't trigger when a different mob gets hit, which is what I think entityHurt was used for.
> 
> Should "damage_event" packet which has the entityId in it, be used instead?
> 
> I tested this in 1.20 and 1.21.1 and it should behave the same.
> 
> ```js
> bot._client.on('damage_event', (packet) => {
>     const entity = bot.entities[packet.entityId];
>     bot.emit('entityHurt', entity);
> })
> ```

Thanks
