### ISSUE TITLE
Проблема при запуске бота на сервер

### ISSUE THREAD

**Issue by crazy445** [PrismarineJS/mineflayer#3521]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.23.0
 - server: vanilla/spigot/paper paper
 - node: 20

## Detailed description of a problem
An error about the chunk is displayed

## What did you try yet?

Nothing helps

## Your current code
```js
[mybot.txt](https://github.com/user-attachments/files/18052054/mybot.txt)

**Comment by extremeheat** [comment]
Not enough information provided. Please write about the issue/actual error, the code, the server version or what you're trying to do
