### ISSUE TITLE
Got kick by server in 1.21.3

### ISSUE THREAD

**Issue by wubushanyan** [PrismarineJS/mineflayer#3522]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.23.0
 - server: vanilla/spigot/paper 1.21.3
 - node: v20.10.0

## Detailed description of a problem
I wana make a afk bot in server to dig some thing, so the script is simple.
I success make the bot login to the server's lobby(And use other player see the bot stand in the lobby to confirm my script is good)

Usually player should use command `/main` to go the slimefun server(Idk is call that server right, in the lobby there have 3 server slimefun | carpetsky | original)

But then I got kick. Console show a string `An internal error occurred in your connection`

## What did you try yet?
Try to open DEBUG in console, it show the biome had load, then got kick.
## Your current code
```js
const mineflayer = require('mineflayer');
const readline = require('readline'); 


const config = {
    username: 'X', 
    host: 'X', 
    port: 25565,
};


async function createBot() {
    try {
        const bot = mineflayer.createBot({
            host: config.host,
            port: config.port,
            username: config.username,
            auth: 'microsoft',
        });

        bot.on('resourcePack', (url, hash) => {
            console.log('Resource pack URL:', url, 'Hash:', hash);
            bot.acceptResourcePack();
        });

        bot.on('kicked', (reason, loggedIn) => {
            console.log('Kicked from the server:', reason, 'Logged in:', loggedIn);
        });

        bot.on('error', (err) => {
            console.error('Error occurred:', err);
        });

        bot.on('end', () => {
            console.log('Bot disconnected. The connection might have been closed by the server.');
        });

        bot.on('login', () => {
            console.log('Bot successfully logged in.');
        });

        bot.once('spawn', () => {
            console.log('Bot spawned in the world.');
        });

        bot.on('death', () => {
            console.log('Bot died.');
        });

        bot.on('message', (message) => {
            console.log('Chat message:', message.toAnsi());
        });

        const rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout,
        });

        rl.on('line', (input) => {
            if (input.startsWith('/')) {
                bot.chat(input);
                console.log(`Executed command: ${input}`);
            } else {
                bot.chat(input);
                console.log(`Sent message: ${input}`);
            }
        });

        return bot;
    } catch (error) {
        console.error('Bot create fail: ', error);
    }
}

createBot();
```

## Expected behavior
- [x] Login to the lobby
- [ ] Turn in to Slimefun server

## Additional context
The end of the DEBUG message
![image](https://github.com/user-attachments/assets/302c04fa-770c-4af6-88a4-03ed864a5954)

**Comment by wubushanyan** [comment]
I looked through the commits and found that the support merge for 1.21.3 failed.
https://github.com/PrismarineJS/minecraft-data/issues/928
If this issue I opened is related to this issue, please remind me to close it or close it directly.

**Comment by extremeheat** [comment]
Only up to 1.21.2 is supported

**Comment by wubushanyan** [comment]
> Only up to 1.21.2 is supported
OK, closed

**Comment by vladbogun1** [comment]
@extremeheat as now 1.21.3 supported, i have same issue, i have to type `/survival`
Server responds in chat with something like `Sending you to "s_arboria"...`
And bot caught disconnected packet with socket closed error with message `An internal error occurred in your connection`, so jumping from proxy server to main is not handled by bot, can we reopen this bug again? or maybe thats not a bug just we need an example how to handle paper(velocity) server jumps
