### ISSUE TITLE
Microsoft login Error : Failed to acquire authorization code from device token (invalid_grant)

### ISSUE THREAD

**Issue by Hitokii** [PrismarineJS/mineflayer#3527]
## Versions
 - mineflayer: 4.23.0
 - server: vanilla 1.20
 - node: 23.1.0

## Detailed description of a problem
I've been trying to log in an alt account, but every time i start node i get a microsoft link with ID and stuff, but when i log into the correct account and verify the code i get this in term (keep spamming):

![image](https://github.com/user-attachments/assets/ab40172a-26e4-4b94-896f-420620df8d41)

## What did you try yet?
Tried to log in again and again.
Tried to remove login cache from .minecraft

## Your current code
```js
const mineflayer = require('mineflayer')

const client = mineflayer.createBot({
  host: 'localhost',
  username: "Lys_Radiata",
  auth: 'microsoft',
})

client.on('error', err => {console.log(err)})

```

## Expected behavior
See my bot log in my minecraft localhost server shared on 25565

**Comment by Hitokii** [comment]
Downgrading to an olderversion seems to have fixed it ?

**Comment by extremeheat** [comment]
"Old version" of what?

**Comment by extremeheat** [comment]
Minecraft version has no impact on auth, which happens before any connection attempt to the server. If your issue was fixed on its own it was probably a temporary auth issue or something with your account.
