### ISSUE TITLE
'An internal error occurred in your connection.' - while changing worlds

### ISSUE THREAD

**Issue by RutekGutek** [PrismarineJS/mineflayer#3529]
### Discussed in https://github.com/PrismarineJS/mineflayer/discussions/3528

<div type='discussions-op-text'>

<sup>Originally posted by **RutekGutek** December 15, 2024</sup>
I was trying to make a bot for specific minecraft server but I got an error.
Every time after the bot logs in with the login command ( bot.chat('/login password'); ) It gets kicked instantly (Normaly after logging in, server should transfer you to lobby (different world))

Code:

```
const mineflayer = require('mineflayer');

const bot = mineflayer.createBot({
    host: 'ip',  
    port: 25565,        
    username: 'name',
    version: '1.21.2'  
});

bot.on("kicked", (r) => {
    console.log(r);
});

bot.on('messagestr', (message) => {
    console.log(message);
    if (message.includes('Verified')) {
        bot.chat('/login password');
}
});
```

Kick reason:

![image](https://github.com/user-attachments/assets/2da26d7f-3c0b-43ac-8d59-f2ec9da86150)

Do you have any ideas?</div>

**Comment by extremeheat** [comment]
This is an issue with the server
