### ISSUE TITLE
Add NPC trade support

### ISSUE THREAD

**Issue by Xstoudi** [PrismarineJS/mineflayer#357]
Hey !
Can you add PNJ trading support ? 
Thanks ! :)

**Comment by pokeball99** [comment]
@Xstoudi what is "PNJ trading"?

**Comment by Gjum** [comment]
NPC (villagers) I suppose

**Comment by rom1504** [comment]
It's planned (see https://github.com/PrismarineJS/mineflayer/issues/113 and https://github.com/PrismarineJS/mineflayer/issues/237) but nobody worked on it yet afaik.
Feel free to try implementing it though !

**Comment by Xstoudi** [comment]
PNJ is NPC in french, my bad.
I don't actually have the time to do this, and I have planned to start to create TypeScript Definitions for each modules arround PrismarineJS (vec3, the smallest is already done).

**Comment by rom1504** [comment]
@plexigras has looked a bit more into this :  https://gist.github.com/plexigras/8ae48c1f679837e3fb5fc081b5ae1b0d)

**Comment by rom1504** [comment]
done !
