### ISSUE TITLE
Missing disconnect kick message ("This server requires FML/Forge to be installed")

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/mineflayer#359]
mineflayer doesn't appear to handle failures to join a server, for example if the server requires FML/Forge — the server will send a message saying so, but mineflayer silently disconnects with no error:

```
mineflayer $ NODE_DEBUG=mc-proto node examples/echo.js localhost 25565
MC-PROTO: 82141 writing packet handshaking.set_protocol
MC-PROTO: 82141 { protocolVersion: 47,
  serverHost: 'localhost',
  serverPort: 25565,
  nextState: 2 }
MC-PROTO: 82141 writing packet login.login_start
MC-PROTO: 82141 { username: 'echo' }
```

Tested with [forge-1.8.9-11.15.0.1715](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.9.html) + mods/[ironchest-1.8.9-6.0.121.768.jar](http://files.minecraftforge.net/maven/cpw/mods/ironchest/index_1.8.9.html) (you need at least one client/server mod, or Forge will let vanilla clients connect). The official client will display the error message:

<img width="966" alt="screen shot 2016-01-21 at 11 08 46 pm" src="https://cloud.githubusercontent.com/assets/5897956/12504652/69ccc126-c094-11e5-9d87-165f17f7831b.png">

corresponding to the server log:

[22:57:37] [Netty Server IO #3/INFO] [FML]: Disconnecting Player: This server requires FML/Forge to be installed. Contact your server admin for more details.

but mineflayer is silent. Used the echo example, but I suspect this failure case should be handled generically in mineflayer (meaning, not something mineflayer bots need to handle themselves), or possibly in node-minecraft-protocol, but I guess mineflayer is more appropriate though I do not yet know the details of how this message is processed ('client kicked' message? something else?).

Relevant:

https://github.com/PrismarineJS/mineflayer/issues/56 MC Forge - an old but still interesting future enhancement

https://github.com/PrismarineJS/mineflayer/issues/309 Need better disconnect handling - not seeing this same error though

**Comment by deathcap** [comment]
Looking at a packet capture in Wireshark, after the client sends its username (login_start message), server replies with this packet (presumably not handled by node-minecraft-protocol?):

```
                        5f00 5d22 5468 6973  "q.a"q.`_.]"This
    2073 6572 7665 7220 7265 7175 6972 6573  .server.requires
    2046 4d4c 2f46 6f72 6765 2074 6f20 6265  .FML/Forge.to.be
    2069 6e73 7461 6c6c 6564 2e20 436f 6e74  .installed..Cont
    6163 7420 796f 7572 2073 6572 7665 7220  act.your.server.
    6164 6d69 6e20 666f 7220 6d6f 7265 2064  admin.for.more.d
    6574 6169 6c73 2e22                      etails." 
```

**Comment by deathcap** [comment]
The 'disconnect' event is emitted when receiving this packet, PR'd to NMP examples in https://github.com/PrismarineJS/node-minecraft-protocol/pull/323 Show disconnect reason in examples — but mineflayer probably should also handle this as well

**Comment by rom1504** [comment]
yeah I think we should just listen on `'disconnect'` too there https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/kick.js

**Comment by deathcap** [comment]
Tested adding in lib/plugins/kick.js, but the only example that listens for kicked is examples/chatterbox.js, I wonder if it is possible/worthwhile to provide a "default" listener for kick/disconnect events? or should all the examples be updated?

**Comment by deathcap** [comment]
Updating all the examples to listen for the mineflayer `kicked` API event is probably superfluous, chatterbox.js already does it as an example (but idk why NODE_DEBUG=mc-proto does not show the disconnect? would be useful if there was some internal debugging mechanism in NMP to see it at least), pull request to listen for login disconnect kicks (including "This server requires FML/Forge to be installed"): https://github.com/PrismarineJS/mineflayer/pull/360
