### ISSUE TITLE
Chat API doesn't support Chinese

### ISSUE THREAD

**Issue by Snownee** [PrismarineJS/mineflayer#362]
In chat.js, 125 lines. Chinese texts are mistakenly filtered.

**Comment by deathcap** [comment]
Filter is:

lib/plugins/chat.js
4:var LEGAL_CHARS = ' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_abcdefghijklmnopqrstuvwxyz{|}~⌂ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜø£Ø×ƒáíóúñÑªº¿®¬½¼¡«»§';

**Comment by Snownee** [comment]
But Chinese is: [\u4e00-\u9fa5]
I'm afraid that is too huge to let this var to assign : )

**Comment by rom1504** [comment]
I'm trying to figure out why was this filter added.
It looks like it tries to filter colors with the paragraph character

https://github.com/PrismarineJS/mineflayer/commit/b5246aaf6f05221ff3c39aa6a94fc31da7acb957

https://github.com/PrismarineJS/mineflayer/commit/6606d7b52f49ed580412a4f7a86b7031dc11f9af

https://github.com/PrismarineJS/mineflayer/commit/217d1fd3084134a6b4eafd1aae1a0632a6a3839b : this filter dates back from the beginning of mineflayer in js (it was c++ before that commit) so indeed it might not be relevant anymore.

Someone should try removing the filter altogether and see if that breaks anything

**Comment by rom1504** [comment]
fixed by #366

**Comment by roblabla** [comment]
This filter probably comes from old version of minecraft where the chat was limited to a subset of ASCII. http://gaming.stackexchange.com/questions/103304/allowed-symbols-characters-in-minecraft-chat

This probably changed when they switched minecraft chat to JSON.
