### ISSUE TITLE
bot does not understand utf8 encoded string

### ISSUE THREAD

**Issue by lastuniverse** [PrismarineJS/mineflayer#365]
upon receipt of chat messages to non-English languages ​​receives unreadable string.
the same thing happens when you send a message to the chat on a non English languages.

**Comment by rom1504** [comment]
Duplicate of #362

**Comment by Snownee** [comment]
Actually I am translating MinecraftChat these days. But this problem really depressed me. this kind of filter can not be nicely modify to support utf-8. And I don't know what this filter's use. After all utf-8 can be support on Minecraft. So I really hope someone could solve this problem. : )

**Comment by rom1504** [comment]
fixed by #366
