### ISSUE TITLE
Make it easier to reuse auth tokens (create a module to store them in profile files ?)

### ISSUE THREAD

**Issue by nomsi** [PrismarineJS/mineflayer#401]
Each time I run my bot (a web client) on my Canada Dedicated Server, then run it on my home server Mojang will automatically reset my password due to "suspicious activity".

Test results: 10 different people had to reset their passwords.

**Comment by Minecheesecraft** [comment]
I never had a problem with this. My best guess your problem is your ip changing quickly. Maybe get an account to dedicate just to the bot?

**Comment by rom1504** [comment]
We recently had that same problem in circle ci testing (https://github.com/PrismarineJS/node-minecraft-protocol/issues/372), I think that's a change mojang made recently.
I think the mojang server is just unhappy about too frequent connections.

One way to avoid the problem would be using access token instead of the password everytime (like the vanilla client does)

**Comment by Cecer** [comment]
I can confirm that Mojang has indeed started stepping up on security to fight the amount of stolen accounts. This has resulted in many issues for myself regarding authentication.

**Comment by pqml** [comment]
Hey, I just made a module to deal easily with tokens if you want : 
https://github.com/pqml/prismarine-tokens

it should works with minecraft-protocol and mineflayer.

**Comment by roblabla** [comment]
Looks cool. Just a nitpick : in your callbacks, always put the error first!
Otherwise it breaks some tools or libraries that makes error handling
easier.

**Comment by pqml** [comment]
Thanks for the feedback! I updated it with proper error handling

**Comment by rom1504** [comment]
done now

**Comment by unixfox** [comment]
@rom1504 Could you explain how to auto save tokens? The lib https://github.com/pqml/prismarine-tokens was very handy because it did the job for me, but I only see the ability to pass tokens myself and not auto save of tokens in the API docs.

**Comment by rom1504** [comment]
This is done by default with mineflayer now. The tokens are saved in your minecraft folder, the same that the launcher uses
