### ISSUE TITLE
Can't seem to craft diamond blocks into diamonds

### ISSUE THREAD

**Issue by siegcommander** [PrismarineJS/mineflayer#405]
My code: http://paste2.org/VtcCWEy1

I haven't had problems crafting anything else, but for some reason I keep crashing when my bot reaches this block of code.

The recipe is defined and is the correct recipe, and I do have diamond blocks in my inventory.

http://puu.sh/nJBAW/a5521d08bb.png

**Comment by rom1504** [comment]
Can you try to run `npm update` and try again ?
I just released a new version of node-minecraft-protocol that will display better errors.

**Comment by siegcommander** [comment]
I updated to the latest minecraft-protocol version, but I seem to have the same error as before.

Side note: Is there anyway I can donate to you? This is an amazing node module

**Comment by rom1504** [comment]
Really, exactly the same error ? Are you sure you're now using minecraft-protocol 0.19.5 ? (npm update will get that for you since mineflayer depends on minecraft-protocol ^0.19.0)

Thanks for proposing to donate, I'm not sure about how that would work atm, there are several contributors and there's currently no particular way to donate to minefayer.

**Comment by siegcommander** [comment]
It says in my file that it is 0.19.5, and I went and checked src/client.js to see if it's the new file and it is.

**Comment by rom1504** [comment]
Can you copy/paste error the exact error you are getting ?

**Comment by siegcommander** [comment]
Sorry I am not at my computer, but the exact error is posted in my last
reply as a screenshot. It is just one line

**Comment by jh1333** [comment]
Any update on this issue?

**Comment by siegcommander** [comment]
@rom1504 Were you able to reproduce the error?

**Comment by rom1504** [comment]
I didn't have time to try yet. I would still be interested by the error. I believe it should have changed after `npm update` (maybe try to rm -rf node_module && npm install to make sure you really have the new version)

**Comment by siegcommander** [comment]
Alright I've dug a little deeper. I wrote a test script to do only one thing: craft diamonds from diamond blocks, and it works. 

Here is the entire function I am having issues with: http://paste2.org/bN1FvNh8

The error is within the `chest.on('close', ...)` code block. The error that is thrown is this:

> Error: AssertionError: Deserialization error for play.toClient : null != null

**However,** whenever I wrap the code within `chest.on('close', ...)` with a setTimeout, like so: http://paste2.org/Ygd0ZZcy

It works successfully. It has something to do with timing, but I don't know what. Any ideas?

**Comment by rom1504** [comment]
"Error: AssertionError: Deserialization error for play.toClient : null != null" Can you paste the whole stack trace for this ?

**Comment by siegcommander** [comment]
How would I do that?

**Comment by rom1504** [comment]
Well, does it only only output that ? I mean, can you paste the full error ?

Anyway, I guess I should try myself to craft these diamonds...

**Comment by siegcommander** [comment]
Yes that is the only error.

**Comment by rom1504** [comment]
Hmm why did you close ? Is the problem solved ?
