### ISSUE TITLE
Why is there no bot.activateBlock callback??!

### ISSUE THREAD

**Issue by jh1333** [PrismarineJS/mineflayer#407]
Why is there no callback function for `bot.activeBlock`? I need to execute other orders after this command, but the block is never activated because everything else is immediately executed, not giving enough time for `bot.activateBlock` to run!

e.g.: I tell my bot to active a lever then after that open a chest, but the lever action is ignored because immediately after `bot.activateBlcok` is called, the bot turns to the chest instead to try and open it.

**Comment by Gjum** [comment]
clicking on a block is instantaneous, as the client just sends a packet and moves on. so instead of putting  code into a callback, you put it directly after the activateBlock call.

**Comment by jh1333** [comment]
Not necessarily. The bot still needs time to turn and look at the lever and click it. If I do `bot.openChest` right after, it will also turn. It's conflicting

**Comment by Gjum** [comment]
Looking at [the code](https://github.com/PrismarineJS/mineflayer/blob/aaa90b25d1d9e0353fdd1284000103febd37e79f/lib/plugins/inventory.js#L98-L113),
you are right, it is indeed more than one packet: `bot.lookAt` sets a new view angle, and after the movement packet got sent, `arm_animation, block_place`.

The last two actions are instantaneous, but `lookAt` is not. So there should really be a callback to `activateBlock`, which would get called after `write('block_place', ...)`.

**Comment by jh1333** [comment]
No problem! I was losing my mind because the documentation says it's instant, but I was 99% sure that it needed a callback. Thanks for the quick response!

I'm going to add a callback myself in the mineflayer code, but any idea when the new fix will be added?

**Comment by rom1504** [comment]
@jh1333 you can make a pull request ;)

**Comment by jh1333** [comment]
@rom1504 Ok I think I figured out how to do a pull request haha

**Comment by rom1504** [comment]
fixed by #408 , thanks @jh1333 !
