### ISSUE TITLE
How do I get the character to left click a furnace once?

### ISSUE THREAD

**Issue by siegcommander** [PrismarineJS/mineflayer#411]
Is there any way to do it? I don't want to use `bot.dig` because that may cause the player to hit the furnance more than once. I just the bot hit the furnace with a stick ONCE.

Any ideas? `bot.activateBlock` doesn't work because that seems to be a right click.

**Comment by rom1504** [comment]
What do you want to do ? Isn't the furnace api appropriate for this ?
