### ISSUE TITLE
Bot throwing item after crafting

### ISSUE THREAD

**Issue by jh1333** [PrismarineJS/mineflayer#413]
Has there ever been an update to #142 ? Or maybe at least a solution to the problem?

**Comment by rom1504** [comment]
afaik #142 has been fixed for a long time. Are you having that issue ? On what kind of server ?

**Comment by jh1333** [comment]
Yes I am having the issue. I'm not exactly sure what the server is running.

Bot when the bot goes to craft, it successfully crafts the first item - but then it throws that item out of its inventory, and stops crafting....never finishing.

**Comment by wvffle** [comment]
Closing in favour of #661
