### ISSUE TITLE
send MC|Brand

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#416]
http://wiki.vg/Protocol_FAQ#What.27s_the_normal_login_sequence_for_a_client.3F

**Comment by deathcap** [comment]
mineflayer already sends MC|Brand? https://github.com/PrismarineJS/mineflayer/commit/a768289d01e12debdf5e5a6a56afd4f88a9d43c7#L24

**Comment by rom1504** [comment]
Oh yeah indeed.
