### ISSUE TITLE
Bot hold right click?

### ISSUE THREAD

**Issue by jsocraft** [PrismarineJS/mineflayer#421]
Is it possible to have a bot hold right click rather than using setInterval & .activateItem() ?

**Comment by Gjum** [comment]
What is your use case for this?

**Comment by jsocraft** [comment]
Holding down right-click to spam a fishing rod

**Comment by Gjum** [comment]
Assuming this is for a fishing farm, it is way more effective to react to the fish bubble particles.

**Comment by jsocraft** [comment]
Is it possible to simulate holding down the right click button though? :3

**Comment by jsocraft** [comment]
Any more ideas on this? I've been experimenting with setInterval and setTimeout but I cant get the result I'm looking for. Holding right-click is the action I'm looking for.

**Comment by Gjum** [comment]
Well, holding right click does different things depending on gamemode, held item, blocks in the way etc.
So a "simple" `holdRightClick` function would not be easily possible and difficult to maintain.

Anyway, if you come over to the [Gitter chat](https://gitter.im/PrismarineJS/mineflayer), there is probably someone who can help you with your specific problem.

**Comment by jsocraft** [comment]
> Assuming this is for a fishing farm, it is way more effective to react to the fish bubble particles.

How would I do this?

**Comment by rom1504** [comment]
using the http://prismarinejs.github.io/minecraft-data/?d=protocol#toClient_world_particles packet

**Comment by rom1504** [comment]
seems solved ?
