### ISSUE TITLE
Check entities by internal id if nothing is found by network id

### ISSUE THREAD

**Issue by ArcticZeroo** [PrismarineJS/mineflayer#430]
When connecting to the server `us.mineplex.com`, the bot instantly crashes as https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/entities.js#L164 returns undefined for some custom spawned entities (not sure which). I was able to successfully connect the bot to the server with no apparent issues, but only after completely commenting out the 'spawn_entity_living' event.

**Comment by Gjum** [comment]
Can you post the packet contents please? It also contains the position with which you could figure out which entity is causing the issue.

**Comment by ArcticZeroo** [comment]
@Gjum this may be a rather basic question (haven't used this API too much) but... how? I don't see an event to log packets. Would I have to use the minecraft-protocol API?

**Comment by Gjum** [comment]
You can just add a `console.log` in that method you linked, and print the received `packet`.

**Comment by ArcticZeroo** [comment]
@Gjum I believe that this is the packet:

`{ entityId: 13890616,
  type: 30,
  x: 0,
  y: -150,
  z: 0,
  yaw: 0,
  pitch: 0,
  headPitch: 0,
  velocityX: 0,
  velocityY: 0,
  velocityZ: 0,
  metadata:
   [ { type: 0, key: 10, value: 16 },
     { type: 0, key: 3, value: 1 },
     { type: 4, key: 2, value: '§r§a§lMineplex Player Servers' },
     { type: 1, key: 1, value: 300 },
     { type: 0, key: 0, value: 32 } ] }`

**Comment by Gjum** [comment]
`type: 30`

Well there's no known entity with ID 30, see http://wiki.vg/Entities#Mobs

So either the server sends unexpected data (possibly to just display the nametag), or the entity list is incomplete.

**Comment by ArcticZeroo** [comment]
@Gjum I see, I'll contact a dev for the server and try to get to the bottom of this! Otherwise I'll just set an if statement for entities that aren't id 30 :P

**Comment by Gjum** [comment]
@rom1504 what would be a good fallback behaviour for unknown entity types?

**Comment by roblabla** [comment]
How does the notchian client react to unknown eid?

**Comment by rom1504** [comment]
We should probably add an entity with an unknown type (fill the corresponding properties with empty values for example)

**Comment by imnofox** [comment]
Looks like an armour stand to me.
That metdata would fit, and 30 is listed as an armour stand on the MC wiki.

**Comment by rom1504** [comment]
So apparently bukkit/spigot/whatever in us.mineplex spawn armor stand using the internal id 30.
That's a custom behavior.

The "problem" is that the vanilla client understands it.

If we want to replicate the behavior of the vanilla client, we could check entities by their internal id if it cannot be found using the network id.
