### ISSUE TITLE
unexpected end of file

### ISSUE THREAD

**Issue by MrSonicMaster** [PrismarineJS/mineflayer#431]
Whenever i connected to a server, i get this error:
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)

What should i try to do to fix this?

EDIT:
If i add a bot.on('error') i get this
Bot error { [Error: unexpected end of file] errno: -5, code: 'Z_BUF_ERROR' }

**Comment by Slushpies** [comment]
How was this solved?

**Comment by rom1504** [comment]
reproduced on `mc.desiredcraft.net`
Not sure what is up

**Comment by rom1504** [comment]
same error with nmp

**Comment by MrSonicMaster** [comment]
Yeah, that's the same server I tested it on.

**Comment by mcparadip** [comment]
Same error

**Comment by mcparadip** [comment]
Same error, but only when i have a block of code that receives chat packets.

**Comment by mcparadip** [comment]
Has this been solved?

**Comment by mcparadip** [comment]
It works fine on RunKit online, maybe it's the node version.

**Comment by MrSonicMaster** [comment]
Sadly, I lost the code I used before to fix the error or else I would put it here.

**Comment by mcparadip** [comment]
@rom1504 said in the other issue:

> If I just ignore that chunk (return cb() instead of return cb(err)) everything else seems to work.

So yea do that.

**Comment by mcparadip** [comment]
He's talking about https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/transforms/compression.js#L64

**Comment by johnpyp** [comment]
This is the most pressing issue for me. I've had to maintain a fork implementing this "quick fix" and its pretty annoying, especially because it seems to cause other bugs.

**Comment by rom1504** [comment]
fixed in https://github.com/PrismarineJS/node-minecraft-protocol/issues/462 + https://github.com/PrismarineJS/node-minecraft-protocol/commit/9cb5810597fed419f65d7a86e7f18c350aabab27

**Comment by lefela4** [comment]
Yo @MrSonicMaster lmao

**Comment by lefela4** [comment]
I just figure out the zlib issue with some packet on some servers xD.
I just look online for the sharing compressed data chunks and I figured the issue out. If this is still alive I will post it there.

**Comment by rom1504** [comment]
Yes the issue is still open so we still need the fix.
Please share ;)

**Comment by lefela4** [comment]
Dupe of https://github.com/PrismarineJS/mineflayer/issues/753#issuecomment-443505337
