### ISSUE TITLE
Some help regarding the bot please

### ISSUE THREAD

**Issue by Slushpies** [PrismarineJS/mineflayer#433]
Im having trouble interacting with the bots inventory such as make it do things like drop all items but one type. Ive read through the api but it doesn't seem to have any info and neither does the example. Some help please?

**Comment by rom1504** [comment]
Did you see the inventory.js example ?
the list and drop functions can be combined to do what you want https://github.com/PrismarineJS/mineflayer/blob/master/examples/inventory.js#L64

(go through the list of items and drop the one not matching a certain name/type)

**Comment by Slushpies** [comment]
Sorry, im still new to java and would love if you could show me an example please

**Comment by Slushpies** [comment]
How do I check whats in a slot in the inv?

**Comment by rom1504** [comment]
Something like this : 
```js
bot.inventory.items().forEach(item => {
  if(item.name!="stone") bot.tossStack(item);
});
```

But really, read the examples code https://github.com/PrismarineJS/mineflayer/blob/master/examples/inventory.js

**Comment by Slushpies** [comment]
where did you get the forEach from? Also how did you know about the .name?

**Comment by imnofox** [comment]
@Slushpies 
`bot.inventory.items()` returns an array.
Every array in JavaScript has the `forEach()` function, which you can [read about here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach).

It would be useful to learn some basic JavaScript before getting started, and there's a plethora of free online lessons for that 😄

**Comment by Slushpies** [comment]
Sorry ;p, got big plans but cant really do anything I want to because I don't have enough info. Thanks for the help tho.
