### ISSUE TITLE
Turning head then activating item

### ISSUE THREAD

**Issue by Slushpies** [PrismarineJS/mineflayer#436]
How do I make the bot turn its head then activate an item. Currently I can get everything to work fine but the bot casts the rod as its turning its head. Anybody have a solution to make it turn before casting?

**Comment by rom1504** [comment]
First call https://github.com/PrismarineJS/mineflayer/blob/master/doc/api.md#botlookatpoint-force-callback then in the callback put your call to activateItem

**Comment by Slushpies** [comment]
function fishing(direction){
    status = 'fishing';
    selectRod();
	bot.look(direction, 0, true, bot.activateItem());
}

It still seems to be having issues.

**Comment by Slushpies** [comment]
nvm, worked it out by making a function with the activateitem command and placed it in the callback area. Thanks for the help!
