### ISSUE TITLE
Server rejecting transaction after throwing items

### ISSUE THREAD

**Issue by Slushpies** [PrismarineJS/mineflayer#441]
Can anybody help me with throwing out any items that aren't rods or fish? I have a snippet of code from a previous response but it crash's my bot when tried more then once. Here's the code:

```
bot.inventory.items().forEach(item => {
        if(item.name!="fish" && item.name!="fishing_rod") {
			  bot.tossStack(item);
		}
    });
```

any help would be much appreciated! This has been giving me grief for a while and its the last problem before my bot is finished. ^-^

**Comment by roblabla** [comment]
```js
var async = require('async');
async.forEach(bot.inventory.items(), function(item, done) {
  if (item.name != "fish" && item.name != "fishing_rod") {
    bot.tossStack(item, done);
  }
});
```
