### ISSUE TITLE
Bot disconnects

### ISSUE THREAD

**Issue by Sitorx** [PrismarineJS/mineflayer#446]
Bot disconnect from server after 0.5s without any error or "disconnected" log

**Comment by rom1504** [comment]
a 1.8 vanilla server ?

**Comment by Sitorx** [comment]
no bukkit, I try examples client_chat and client_auto on this server and client_chat is working but client_auto no

**Comment by Sitorx** [comment]
Examples from minecraft node protocol

**Comment by Sitorx** [comment]
Nevermind i fixed that

**Comment by menschPerson** [comment]
> a 1.8 vanilla server ?

Did you have a problem with the 1.8 server? Because I have one. How did you fix that?
![6ee4847b480ddbcba4fbe810cb0bef11](https://user-images.githubusercontent.com/49818808/62006605-fb162080-b142-11e9-81eb-346d27025431.png)
