### ISSUE TITLE
windowType in 1.8 is a string

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/mineflayer#450]
https://github.com/PrismarineJS/mineflayer/search?utf8=%E2%9C%93&q=windowType
http://wiki.vg/Inventory
http://wiki.vg/index.php?title=Protocol&oldid=7368#Open_Window

We should change all references to windowType to a "minecraft:chest","minecraft:crafting_table"...

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/ae7b67bad1e4e6c0a2bbd8c334d02f32993eb0db/lib/plugins/inventory.js#L220 where is window.type set ?

**Comment by roblabla** [comment]
https://github.com/PrismarineJS/prismarine-windows/blob/master/lib/windows.js#L48 there

**Comment by Karang** [comment]
done in https://github.com/PrismarineJS/mineflayer/pull/968
