### ISSUE TITLE
Bot joins, then leaves.

### ISSUE THREAD

**Issue by TeamMedusa** [PrismarineJS/mineflayer#456]
Hello.
I'm currently testing MineFlayer, but I cannot seem to make the bot stay on the server.
It joins, and then leaves (http://prntscr.com/cuw55z)
Does that for all scripts.
I am using the example .js files, but I don't know if I want to make my bot based on this, if it will not stay.
This is my console after connecting it.
http://prntscr.com/cuw5ec

EDIT: Nevermind, issue is still valid. Anyone who knows how to fix this?

**Comment by TeamMedusa** [comment]
Also, when it is connected, it doesn't do what the script tells it to do.

**Comment by plexigras** [comment]
what are you trying to run?

**Comment by TeamMedusa** [comment]
Currently, I am just trying to run echo.js - Although, any other script does the same

**Comment by plexigras** [comment]
you need to tell what you are doing in detail

**Comment by TeamMedusa** [comment]
http://prntscr.com/cuyuo7

**Comment by plexigras** [comment]
you need to replace username with an actual user name or mojang account email and the password with the actual password

**Comment by roblabla** [comment]
Also, mineflayer is only compatible with minecraft 1.8. Server versions
above that won't work

**Comment by TeamMedusa** [comment]
I know... And I also know what you said roblabla. It's a 1.8 Waterfall (Works with 1.7 - 1.8 and 1.10). Might that be the problem?

**Comment by rom1504** [comment]
Can you see the same behavior on an other server ?

**Comment by PunKeel** [comment]
I suspect the Forge support, but might be wrong.
Login doesn't work on play.epicube.fr - online mode - for instance

**Comment by rom1504** [comment]
Not enough info to do anything.
Reopen with more info if you still have the problem.
