### ISSUE TITLE
How can i Install this?

### ISSUE THREAD

**Issue by kotik1998** [PrismarineJS/mineflayer#458]
Can some one really explain me step-by-step what do i need to install this, like node version, ssl version how to install ursa correctly what pyton i need every thing
cuz i tried ALL and i cant install anything ;/

**Comment by Ezcha** [comment]
1. Make sure you have node installed
2. Open a command prompt
3. Enter "cd /path/to/the/directory/you/want"
4. Enter "npm install mineflayer"
5. Download one with of the example scripts from here
6. Enter "node example_script.js"
You will have to run it with some arguments so check out the example script to figure that out.

**Comment by kotik1998** [comment]
info it worked if it ends with ok
verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
verbose cli   'install',
verbose cli   'mineflayer' ]
info using npm@1.1.4
info using node@v0.6.12
verbose C:\Program Files (x86)\nodejs\\node.exe node symlink
verbose config file C:\Users\Victor\.npmrc
verbose config file C:\Program Files (x86)\nodejs\etc\npmrc
verbose config file C:\Program Files (x86)\nodejs\node_modules\npm\npmrc
verbose mkdir done: C:\Users\Victor\AppData\Roaming\npm 755
verbose mkdir done: C:\Users\Victor 755
verbose caching C:\Users\Victor\node_modules\mineflayer\package.json
verbose loadDefaults mineflayer@1.8.0
verbose cache add [ 'mineflayer', null ]
silly cache add: name, spec, args [ undefined, 'mineflayer', [ 'mineflayer', null ] ]
verbose parsed url { pathname: 'mineflayer',
verbose parsed url   path: 'mineflayer',
verbose parsed url   href: 'mineflayer' }
verbose addNamed [ 'mineflayer', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'mineflayer', '', false ]
verbose raw, before any munging mineflayer
verbose url resolving [ 'https://registry.npmjs.org/', './mineflayer' ]
verbose url resolved https://registry.npmjs.org/mineflayer
http GET https://registry.npmjs.org/mineflayer
ERR! Error: failed to fetch from registry: mineflayer
ERR!     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\npm-registry-client\get.js:139:12
ERR!     at cb (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\npm-registry-client\request.js:31:9)
ERR!     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\npm-registry-client\request.js:136:18)
ERR!     at Request.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:119:22)
ERR!     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:412:12)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1261:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     <http://github.com/isaacs/npm/issues>
ERR! or email it to:
ERR!     <npm-@googlegroups.com>
ERR! 
ERR! System Windows_NT 6.2.9200
ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mineflayer"
ERR! cwd C:\Users\Victor
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: mineflayer
verbose exit [ 1, true ]

**Comment by Ezcha** [comment]
Odd, I'm not sure what that error is about. I could dig a bit deeper into it when I get home.

**Comment by roblabla** [comment]
You're using a ridiculously old version of nodejs and npm. That npm version isn't compatible with the npmjs.com registry since 2014.

You should install nodejs 7.

**Comment by kotik1998** [comment]
i figured out how to install it properly.
HUGE thanks to @L4443 for helping me out.
