### ISSUE TITLE
bot.dig() not working

### ISSUE THREAD

**Issue by L4443** [PrismarineJS/mineflayer#459]
when i try to use the bot.dig() function it just hits the block and dosen't actually dig the block. The same thing happens in creative, it just plays the hit animation whitout actually doing anything.

**Comment by roblabla** [comment]
Can you tell us what version of minecraft you're trying this on ?

**Comment by L4443** [comment]
1.8.9 on a 1.8.4 server

**Comment by kotik1998** [comment]
Hope there's a fix.

**Comment by plexigras** [comment]
is the bot oped? might be a spawn protection thing.

**Comment by L4443** [comment]
Damn i feel stupid right now...

**Comment by falazar** [comment]
Hmm how do we do that on a simple lan server?

**Comment by roblabla** [comment]
There's no spawn protection on a LAN server AFAIK ?
