### ISSUE TITLE
Offline Bots

### ISSUE THREAD

**Issue by iRaphi** [PrismarineJS/mineflayer#460]
Hey, is it possible to log in as an offline bot? I'm trying to test something on my server with a lot of clients connected, but I don't have nearly enough accounts to get it working.

**Comment by kenny-evitt** [comment]
@iRaphi What did you learn? Is it possible? If so, how'd you do it?

**Comment by roblabla** [comment]
If your server is in offline mode, you can just create your bot this way : 

```
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "localhost", // optional
  port: 25565,       // optional
  username: "roblabla",
});
```

I.E. don't specify a password. If you do this, Mineflayer/NMP automatically understand you want to be in offline mode.

**Comment by kenny-evitt** [comment]
@roblabla Thanks! I got it working myself but it's good to know that this (specifying `username` but *not* `password`) was one of the many things I tried that actually helped.
