### ISSUE TITLE
How do we add Proxy on the Bot?

### ISSUE THREAD

**Issue by kotik1998** [PrismarineJS/mineflayer#461]
Hello
I want to know how to add proxys on the bot, 
If u know how to please provide a code so i can paste

**Comment by kotik1998** [comment]
bump

**Comment by rom1504** [comment]
what do you mean ?
this https://github.com/PrismarineJS/node-minecraft-protocol/issues/185#issuecomment-254785390 ?

**Comment by kotik1998** [comment]
Sample code for HTTP proxy

var Http = require("http");
var minecraft = { host: "the.minecraft.server.host.com", port: 25565 };
var proxy = { host: '192.168.1.1', port: 80 };
var req = Http.request({
  host: proxy.host,
  port: proxy.port,
  method: 'CONNECT',
  path: minecraft.host + ":" + minecraft.port
});
req.on("connect", function(res, stream, head) {
  require("minecraft-protocol").createClient({
    stream: stream,
    username: "bleh",
    password: "bleh"
  });
});






on that i can only add my proxy and its done?

**Comment by kotik1998** [comment]
var proxy = { host: '192.168.1.1', port: 80 };

i edit this and it work?

**Comment by kotik1998** [comment]
how can i put that on a .json  file, i have already a script to join a server but how can i add this on the file?

**Comment by kotik1998** [comment]
var mc = require("minecraft-protocol");
var Http = require("http");
var proxy = { address: '159.8.114.37', port: 80 };
mc.Client.connect = function(port, host) {
  var self = this;
  var req = Http.request({
    host: proxy.address,
    port: proxy.port,
    method: 'CONNECT',
    path: host + ":" + port
  });
  req.on('connect', function(res, socket, head) {
    this.setSocket(socket);
  });
  req.end();
};

var mineflayer = require('mineflayer');
var vec3 = mineflayer.vec3;

var toMine = ['cobblestone', 'gold_ore', 'iron_ore', 'coal_ore', 'lapis_ore', 'diamond_ore', 'redstone_ore', 'emerald_ore', 'lit_redstone_ore']


if (process.argv.length < 4 || process.argv.length > 6) {







this is little bit of the script i have
is that the right way to put it? If i put it wrong please help me fixing it, i can launch the bot but the ip is 127.0.1 :/

**Comment by kotik1998** [comment]
i have an ip checker plugin on my test server and the bot is connecting via 127.0.0.1 not the 159.8.114.37', port: 80

**Comment by kotik1998** [comment]
ive already installed this things:
npm install socks5-http-client
npm install socks5-https-client
npm install socks5-client
npm install http

**Comment by kotik1998** [comment]
help?

**Comment by kotik1998** [comment]
bump

**Comment by kotik1998** [comment]
bump

**Comment by roblabla** [comment]
C.F. https://github.com/PrismarineJS/node-minecraft-protocol/issues/185#issuecomment-254785390

You can pass NMP arguments through mineflayer in the createBot method.

So, assuming mineflayer uses a recent enough NMP version 

```js
var mineflayer = require('mineflayer');
mineflayer.createBot({
  stream: Socks.createConnection({
    host: minecraft.host,
    port: minecraft.port,
    socksHost: proxy.host,
    socksPort: proxy.port
  }),
  username: "bleh",
  password: "bleh"
})
```

should work.

**Comment by kotik1998** [comment]
}),
  username: "bleh",
  password: "bleh"
})


what is that username and password?

**Comment by roblabla** [comment]
your minecraft username/password.

**Comment by kotik1998** [comment]
not working, i added the code and put the proxy ip and the username and pw still localhost ip.
maybe i did something wrong

can you update the code that i send there by adding that with proxies?

**Comment by rom1504** [comment]
Can you simply try the code roblabla posted alone to begin with ?
If it works you can then proceed to update your script.

**Comment by kotik1998** [comment]
i tested that by adding the code to the script at the begining

**Comment by kotik1998** [comment]
when i try to launch the .bat file the console just turn off

node tester.js localhost 25565 xxxxxxxxxx@gmail.com xxxxxx233

**Comment by Nixes** [comment]
Try adding a pause to the bottom of your bat file, this will allow you to see what the program returned, which will probably give you clues as to what you are doing incorrectly.

**Comment by kotik1998** [comment]
http://prnt.sc/djjxqi there's your answer
clueless

**Comment by rom1504** [comment]
Instead of putting it at the beginning, can you try just running it ?

**Comment by kotik1998** [comment]
what do you mean?

**Comment by rom1504** [comment]
Step 1) put https://github.com/PrismarineJS/mineflayer/issues/461#issuecomment-267124920 in a file
Step 2) run it
Step 3) report the results

**Comment by kotik1998** [comment]
run in with my bat file that i have?

**Comment by kotik1998** [comment]
http://prnt.sc/djk378
http://prnt.sc/djk3rj


like this?

opened 2 times say press any key to continue then 3rd time appeared this 
http://prnt.sc/djk4dj

**Comment by Nixes** [comment]
Are you sure your minecraft login details are correct? Try logging into a normal minecraft client with them.

**Comment by kotik1998** [comment]
yes they are...

**Comment by Nixes** [comment]
Also note you cannot be logged in from two places at once. So must close your minecraft client when you are using the same account on mineflayer.

**Comment by kotik1998** [comment]
dude i'm not that dumb

**Comment by kotik1998** [comment]
@rom1504 any help?

**Comment by kotik1998** [comment]
bump

**Comment by kotik1998** [comment]
bump

**Comment by kotik1998** [comment]
bump

**Comment by kotik1998** [comment]
bump

**Comment by kotik1998** [comment]
bump

**Comment by algiuxass** [comment]
bump

**Comment by rom1504** [comment]
This has been solved a long time ago. If you have a new issue, open one.
