### ISSUE TITLE
openChest not working?

### ISSUE THREAD

**Issue by safazi** [PrismarineJS/mineflayer#464]
I am passing bot.openChest() a chest block, specifically type 54. The chest doesn't open, but there is no error. Here is what is returned by `bot.openChest(chestblock)`:
```
Chest {
    domain: null,
    _events: {},
    _eventsCount: 0,
    _maxListeners: undefined,
    window: null,
    close: [Function: close],
    withdraw: [Function: withdraw],
    deposit: [Function: deposit] }
````

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/mineflayer/blob/master/examples/chest.js#L105 for an example of use.

**Comment by safazi** [comment]
It turns out I was attempting to open a chest in the world spawn protection region.
