### ISSUE TITLE
Handle custom login server

### ISSUE THREAD

**Issue by hmartinh** [PrismarineJS/mineflayer#476]
Hello!
What can i do, if server, where i want to play with bot has their own "launcher" with kind of encryption like: they send their own session id with they're own type of data encoding, so no way to log in like in default clients.

**Comment by roblabla** [comment]
Without more details. it's hard to say. Usually speaking, custom launchers just use a different auth server. If that's all there is to it, then you can easily support it with a small change to prismarine-yggdrasil (the library that handles auth in mineflayer) : change https://github.com/PrismarineJS/prismarine-yggdrasil/blob/master/lib/yggdrasil.js#L3 so it uses a custom server.

We have talks about supporting custom yggdrasil servers officially eventually,

**Comment by rom1504** [comment]
we're now actually using node-yggdrasil, so it's there https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/Client.js#L8 and there https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/Server.js#L8 you would need to make the change.

**Comment by roblabla** [comment]
Woopsies :)
