### ISSUE TITLE
TypeError: Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by demester5413** [PrismarineJS/mineflayer#477]
Don't know what's going on here, it's probably an easy fix, but if it is I'd love to learn from it.. This happens after I have connected for a couple seconds, it connects and joins the server but then I get this thrown at me:

![untitled](https://cloud.githubusercontent.com/assets/25556785/22622241/778fa752-eb03-11e6-914a-e2cdfa35c454.png)

i'm just using the basic connect script, and also i get it from trying the chatterbox script examples too..

**Comment by Nixes** [comment]
This looks like a bug in the npm version, its been fixed but npm has not been updated yet. Try downloading the version right off github and using that.

**Comment by demester5413** [comment]
It helped, unless it starts acting up again, thanks for that. :D
