### ISSUE TITLE
Two errors

### ISSUE THREAD

**Issue by TheTechPony** [PrismarineJS/mineflayer#479]
A fresh install of mineflayer and minecraft-protocol cause me to get this error
https://gyazo.com/c26c38f466f1bde71d639d1abd659cbd.png

And when I somehow got it to work the chat even wasn't working.

**Comment by TheTechPony** [comment]
didnt mean to close it
https://i.gyazo.com/d6f0585285bb9b21af91a7f1c6604329.png

**Comment by rom1504** [comment]
What version are you connecting to ?

**Comment by rom1504** [comment]
might be related to https://github.com/PrismarineJS/node-minecraft-protocol/issues/464
(84)
is it a custom server ? (server with plugins etc ?)

**Comment by TheTechPony** [comment]
I got it to work now but the chat event isn't working still.

**Comment by TheTechPony** [comment]
This is my code currently
http://pastebin.com/MpZV24UA

**Comment by rom1504** [comment]
About the chat event, see https://github.com/PrismarineJS/mineflayer/blob/master/examples/chatAddPattern.js

**Comment by TheTechPony** [comment]
So I have to add chat patterns for every server? How do I get the raw chat data?

**Comment by rom1504** [comment]
you can use https://github.com/PrismarineJS/mineflayer/blob/master/doc/api.md#message-jsonmsg

Yes you have to add chat patterns for server for use a particular chat plugin, because they have their own chat format

**Comment by TheTechPony** [comment]
Some servers throw this error
https://gyazo.com/c9089d0c4f7e28f6121263d26cf4f50a
Here's one of the servers: litraids.com

**Comment by rom1504** [comment]
what is displayed when you do `bot.on('message',message => console.log(message))` ?

**Comment by TheTechPony** [comment]
https://gyazo.com/d488bf3c43409d5d8514100f93685d73

**Comment by rom1504** [comment]
Can you use http://pastebin.com/ and copy paste instead of posting screenshots ?
can you post the result of `bot.on('message',message => console.log(JSON.stringify(message,null,2)))`

The idea is to see what the messages look like, so we can extract the content from it.

**Comment by TheTechPony** [comment]
There's a whisper at the bottom
http://pastebin.com/x0LevtYK

**Comment by TheTechPony** [comment]
I thought I found a workaround but it wouldn't let me pull usernames. If you could link me to some resources then I'm sure I'd be able to figure it out on my own. I've copied the raw message into regexr.com but I don't know how to deal with the color signs

**Comment by TheTechPony** [comment]
After some intensive google'ing I've solved my issue. Thanks for the support.
