### ISSUE TITLE
Error when joining some servers

### ISSUE THREAD

**Issue by TheTechPony** [PrismarineJS/mineflayer#480]
I've only found one server I can join. I've copied a bunch of errors from joining different servers
http://pastebin.com/FUc2LG1Z

**Comment by rom1504** [comment]
> TypeError: Cannot read property 'displayName' of undefined
use the last version of mineflayer

> SyntaxError: missing ) after argument list
that's an error in your code

> Error: Deserialization error for play.toClient : Read error for name : 120 is no
t in the mappings value
what server + version + plugins?

> Error: Read error for skyLight : undefined
same question

> Error: Invalid credentials. Invalid username or password.
happens when you connect too often

> AssertionError: Deserialization error for play.toClient : Read error for name :
varint is too big
what server

**Comment by TheTechPony** [comment]
Here's one server that throws that error but if you search for general survival servers a lot of them have that so it's a commonly used plugin 
mc.ventureland.net

**Comment by rom1504** [comment]
just tried mc.ventureland.net
works fine
put `version:"1.8"` in bot options
