### ISSUE TITLE
Bot hangs for about ten seconds before emitting any events

### ISSUE THREAD

**Issue by safazi** [PrismarineJS/mineflayer#481]
This is on version 2.1.0 but also occured on 2.0.0

The bot joins when you start the program, and if you were to chat shortly after it joined, the bot would not emit `chat` for about ten seconds, but then it would do all chats received at once. after it does this the first time, chat reacts immediately.

Is this just me?

**Comment by rom1504** [comment]
10 seconds seems like a lot, but the cause of this is it takes some time to parse the chunks, and our chunk implementation is slower in >=1.9
So basically it's "login time"

**Comment by rom1504** [comment]
related https://github.com/PrismarineJS/prismarine-chunk/issues/27

**Comment by rom1504** [comment]
as good as it'll get, blame mojang for complicated chunks
