### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by 27therealone** [PrismarineJS/mineflayer#485]
Keep getting Invalid Credentials. Invalid username or password, then it randomly logins and throws the on.('login') but straight after gets an error: Deserialization error for play.toClient : Read error for name : 7079 is not in mappings value.
After this it goes back to "invalid credentials".

Oh and the host and port details are "mc.aliacraft.net" and port "25565"

**Comment by roblabla** [comment]
Can you give us the code you're trying to run ?

**Comment by 27therealone** [comment]
Yeah sure, obviously I'm going to have to remove my username and password
const mf = require('mineflayer');

var bot = mf.createBot({
    host: 'mc.aliacraft.net',
    port: '25565',
    username: '',
    password: '',
    verbose: true
});

bot.on('login', () => {
    console.log(`Ghost online`);
});

bot.on('whisper', (user, m, rm) => {
    console.log(`Recieved message from: '${user}', message = '${m}', rawMessage = ${rm}`);
    bot.whisper(user, "Ghosting");
});

**Comment by 27therealone** [comment]
Oh and heres the exact error
`/root/node_modules/minecraft-protocol/dist/transforms/framing.js:112
          } else throw e;
                 ^

Error: Deserialization error for play.toClient : Read error for name : 7079 is not in the mappings value
    at ProtoDef.readMapper (/root/node_modules/protodef/dist/datatypes/utils.js:43:34)
    at ProtoDef.read (/root/node_modules/protodef/dist/protodef.js:102:31)
    at /root/node_modules/protodef/dist/datatypes/structures.js:85:32
    at tryCatch (/root/node_modules/protodef/dist/utils.js:83:12)
    at tryDoc (/root/node_modules/protodef/dist/utils.js:90:10)
    at /root/node_modules/protodef/dist/datatypes/structures.js:84:5
    at Array.forEach (native)
    at ProtoDef.readContainer (/root/node_modules/protodef/dist/datatypes/structures.js:79:12)
    at ProtoDef.read (/root/node_modules/protodef/dist/protodef.js:46:25)
    at ProtoDef.read (/root/node_modules/protodef/dist/protodef.js:102:31)
`

**Comment by rom1504** [comment]
you need to specify the version if it's not 1.11.2

**Comment by 27therealone** [comment]
Oh how?

**Comment by 27therealone** [comment]
Oh including version: '1.10' worked. Thank you.
