### ISSUE TITLE
On any version above 1.8 no events are emitted

### ISSUE THREAD

**Issue by 27therealone** [PrismarineJS/mineflayer#487]
After the login emit nothing else is being called unless on version 1.8 (server is compatible with 1.8, 1.9, 1.10, 1.11).

**Comment by rom1504** [comment]
The CI tests indicate otherwise (https://circleci.com/gh/PrismarineJS/mineflayer/398)
How are you testing this ?

**Comment by 27therealone** [comment]
Joined a server and added every event and tried to set off each one, nothing but login worked

**Comment by rom1504** [comment]
Do you have a specific code for this ?
All the example attach other events than login, and they work for other version than 1.8.
Did you specify the version ? Are you using the last version of mineflayer ?

**Comment by 27therealone** [comment]
Latest version of mineflayer, specified the version each time, used the code example for chat so no specific code

**Comment by rom1504** [comment]
which example ? echo.js ? on which server ?

**Comment by 27therealone** [comment]
chatterbox.js and mc.aliacraft.net

**Comment by rom1504** [comment]
@27therealone what version is that server ?

**Comment by rom1504** [comment]
okay I just tried it, for 1.8 and 1.10, it works on this server.
