### ISSUE TITLE
bot.moveSlotItem returns with error

### ISSUE THREAD

**Issue by plexigras** [PrismarineJS/mineflayer#488]
```js
assert.ok(bot.inventory.slots[slot], `no item in slot ${slot}`)
bot.moveSlotItem(slot, 36, console.log)
```

returns an error

```
Error: Server rejected transaction.
```
at [line 467 of inventory.js](https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js#L467)

**Comment by rom1504** [comment]
well, is there something on slot 36 ?

**Comment by plexigras** [comment]
yes but [this](https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js#L495) should handel that

**Comment by rom1504** [comment]
No, that handles the case when you're *holding* an item https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js#L491

**Comment by rom1504** [comment]
ah well, maybe it would handle it

**Comment by rom1504** [comment]
@plexigras are you waiting for the callback ?

**Comment by plexigras** [comment]
yes

**Comment by rom1504** [comment]
I mean, what you put in the first post of the issue is your whole code ?

**Comment by plexigras** [comment]
no i'm trying out my book implementation https://gist.github.com/a21fe04c58aeca16447edb9ff872c3cd

but i'm gonna give the code above a try

**Comment by plexigras** [comment]
oh wait somehow this works:

```js
bot.once('login', () => console.log('loged in'))
bot._client.once('window_items', () => {
  console.log('got items');
  print();
  var [ book ] = bot.inventory.items().filter(({ name }) => name === 'writable_book')
  var slot = book.slot;
  assert.ok(bot.inventory.slots[slot], `no item in slot ${slot}`)
  bot.moveSlotItem(slot, 36, (err) => {
    console.log('err:',err);
    print();
  })
});

function print() {
  var books = bot.inventory.items().filter(({ name }) => name === 'writable_book')
  console.log('books:',books.length);
  console.log('slots:',books.map(book => book.slot));
}
```
