### ISSUE TITLE
is reading chat working?

### ISSUE THREAD

**Issue by syrianrue** [PrismarineJS/mineflayer#498]
while using the chatterbox example, i noticed chat messages wouldnt get logged to the console. whispers would still work fine though. below is the function that should fire when chat updates but its not firing. is it just me or is it happening to others as well?

bot.on('chat', function(username, message) {
console.log(username + ": " + message);
});

**Comment by rom1504** [comment]
Some servers have different chat formats, see the chat patterns example

**Comment by syrianrue** [comment]
your right, it must have been something with the server because bot.on('chat', ... ) did work on another server. the first server it just wouldn't fire though. but i was able to get chat messages in a strange way on that server with bot.on('message', function(msg) {
console.log(msg.extra);
});

idk why bot.on('chat', ... ) simply doesnt fire on that first server. its a spigot server. idk if that makes a difference.

**Comment by rom1504** [comment]
plugins, see that chat patterns example, allows you to parse specific
plugin chat formats ;)

**Comment by syrianrue** [comment]
i get ya now. but now i have an even bigger problem - using regex (jkjk). no i think i got it working fine now. thank you for the help : )

**Comment by rom1504** [comment]
if you have a regex that works for your specific server, please share, it might be useful to other having the same problem ;)

**Comment by syrianrue** [comment]
im terrible with regex but this seemed to work for me...

bot.chatAddPattern(/\ +([^\s]+)?\ (.*)/, "bqchat", "bitquest chat");
bot.on('bqchat', function(username, message) {
  console.log(username +' : '+ message);
});


the messages on chat were in the format of either "Local> username message" or starting with their level if using global chat such as "23 username message".
