### ISSUE TITLE
Spigot 1.11 ( Latest Version ) setVelocity Not Working

### ISSUE THREAD

**Issue by brandon-mueller** [PrismarineJS/mineflayer#508]
When I spawn an entity such as a Bat, setVelocity does not work
when the setAI function is set to FALSE.

I need the AI to be disabled so the entity will stay still
so I can apply custom movements.

This worked in 1.10.

**Comment by Gjum** [comment]
That's not related to the mineflayer project at all.

Try Spigot's JIRA instead: https://hub.spigotmc.org/jira/secure/Dashboard.jspa

**Comment by brandon-mueller** [comment]
My apologies, I was directed to the wrong help page.
