### ISSUE TITLE
Invalid credentials.

### ISSUE THREAD

**Issue by tenten8401** [PrismarineJS/mineflayer#509]
I know there's probably going to be something screwy I'm doing here, but I've got the code as follows:
```
var mineflayer = require('mineflayer');

var bot = mineflayer.createBot({
  host: "localhost", // optional
  port: 25565,       // optional
  username: "email@domain.tld", // email and password are required only for
  password: "password",          // online-mode=true servers
});

bot.on('error', function(err) {
  console.error(err.message);
});
```

I've verified my username and password by directly copy/pasting them from my code into Mojang to have it login flawlessly, and same with the Minecraft launcher.

Was something changed lately with the auth servers? Is there a typo in my code or mineflayer?

The output I'm getting w/o the error handling is:
```
Error: Invalid credentials. Invalid username or password.
    at Request._callback (/opt/helper/node_modules/yggdrasil/lib/index.js:29:12)
    at Request.self.callback (/opt/helper/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/helper/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/helper/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

**Comment by roblabla** [comment]
Mojang banned a bunch of IP addresses recently. You may have received an email containing the following content : 

> We suspect that your Mojang account email and password may have been compromised. To prevent unauthorized use of your account we've reset your account password. If you use that same password on other sites we strongly recommend that you change your password on those sites as well.

**Comment by roblabla** [comment]
Alternatively, you can bypass the whole login procedure by using the same auth tokens that your normal minecraft installation uses. CF : https://github.com/plexigras/mineflayer/blob/234bebd4a140edee791adfe56dced06453093e78/examples/session.js

**Comment by tenten8401** [comment]
God that's frustrating. Hmm...

**Comment by rom1504** [comment]
Seems fixed

**Comment by GunnerBasil** [comment]
I don't think it is, my accounts also got locked :( sorry for the mega necro post
