### ISSUE TITLE
Connection Refused (Error: read ECONNRESET)

### ISSUE THREAD

**Issue by Sw1ck** [PrismarineJS/mineflayer#511]
I can't for the life of me figure this out. I've been trying to set up a simple bot, using one of the examples, but every time I get an error saying the connection is refused.
Here's my code:
```
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "localhost",
  port: 25565,
  username: "TestBot",
});

bot.once('spawn', function() {
  bot.chat('Goodbye, cruel world!');
  bot.quit();
});
```
And here's the output/error I get:
```
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:572:26)
```

I'm using Windows 10 and I have installed the latest updates to NodeJS, npm, minecraft-protocol, and mineflayer.
I have tried the above script on vanilla versions 1.8, 1.8.8, 1.9, 1.10, and 1.11 (jars straight from Mojang). To me, the error seems like the server is refusing connection because of mismatched versions, but that wouldn't make any sense because mineflayer supports those versions.
The only thing I have gotten to work is the "echo client example" from minecraft-protocol on versions 1.8 and 1.8.8, but when I use the script above on mineflayer, I keep getting the above error.

I'm probably making some simple mistake. I've been trying to get it to work for a while, but nothing seems to solve it. Any help is very much appreciated.
Thanks!
Sw1ck

**Comment by plexigras** [comment]
Is online mode disabled?

**Comment by rom1504** [comment]
Default is 1.11.2

You can set the version with version:"1.10" for example

**Comment by rom1504** [comment]
reopen if you have more info

**Comment by duralakun** [comment]
Getting the same error, but happens only sometimes (randomly), when i run the bot on an online server with many plugins.

> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at exports._errnoException (util.js:1018:11)
>     at TCP.onread (net.js:568:26)

**Comment by rom1504** [comment]
well that just means you're getting disconnected by the server
