### ISSUE TITLE
Bot doesn't pick up multicolor usernames correctly

### ISSUE THREAD

**Issue by LewisTehMinerz** [PrismarineJS/mineflayer#512]
I am using the statement `bot.chatAddPattern(/^\[ .*?(\w*) -> me \](.*)$/, "whisper", "essentials whisper");` to allow the bot to read Essentials messages. However, after around 2 minutes of testing, I encountered a major issue.

It doesn't return the correct username when it is multicolored.

I have tried doing it using chat, same issue.
![if you are seeing this, tell me](https://all.foxgirlsare.sexy/8a39d6.png)

It only seems to pick up the final character of my name due to it all being different colors. Can there be a fix for this please? I don't want to send `/msg z Done!` as there can be many people with a z in their name.

~LewisTehMinerz

**Comment by roblabla** [comment]
Isn't that a problem with your regex ? Your username contains the color symbol §, but you're only accepting \w (a-zA-Z). Try using `bot.chatAddPattern(/^\[ .*?([§a-zA-Z]*) -> me \](.*)$/, "whisper", "essentials whisper");`

**Comment by LewisTehMinerz** [comment]
Oh wow. I only just noticed that as well. I'll let you know how it goes.

**Comment by LewisTehMinerz** [comment]
Still can't seem to figure this out. Is this a bug with my code or with the library?

**Comment by LewisTehMinerz** [comment]
Issue is still present.

**Comment by plexigras** [comment]
what dose it pick up? and can you show what your current pattern is and what the unmodified message from the server looks like?

[`bot.on('message', json => console.log(Json.stringify(json)))`](https://github.com/PrismarineJS/mineflayer/blob/master/doc/api.md#message-jsonmsg)

**Comment by rom1504** [comment]
The bug is in your regex. We don't support every imaginable chat format.

However, if you have any more questions about this, feel free to ask in this issue.
