### ISSUE TITLE
User manual ?

### ISSUE THREAD

**Issue by lewisg743** [PrismarineJS/mineflayer#513]
So aside from a single command to install this there isn't to me at least any user guide that tells how to actually use this.

I want to be able to do some bench marking with this tool by having for example 200 'plays' loaded into the server performing same and/or separate scripts, could someone explain to me exactly what I'd have to do, i feel like once i see how its intended to be done it will become clear.

Thanks

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/mineflayer#documentation
in particular https://github.com/PrismarineJS/mineflayer/blob/master/doc/api.md
and https://github.com/PrismarineJS/mineflayer/tree/master/examples

You can pick any example and run it as many time as you want to have multiple bot.

You can also use multiple.js to have multiple bots in a single node instance.

**Comment by roblabla** [comment]
I'm closing this issue since we already do have docs. If you feel anything is missing, feel free to reopen the issue with a comment describing what's missing :).

**Comment by lewisg743** [comment]
There isnt a simple, type this to use it i dont fully understand how this works. There is no step by step guide on using it from what i can see. I just wanna install it and run it, no idea what to download, where to store things, what commands to enter etc

**Comment by plexigras** [comment]
1. https://github.com/PrismarineJS/mineflayer#installation
1. https://github.com/PrismarineJS/mineflayer#usage

**Comment by lewisg743** [comment]
npm install mineflayer

is the only thing thats obvious there, keep in mind im a novice

**Comment by plexigras** [comment]
come over to https://gitter.im/PrismarineJS/mineflayer if you need help

**Comment by lewisg743** [comment]
I mean i just want a simple explanation/guide on using this - a command to install and then a bunch of configurable files does nothing to better my understanding.

**Comment by plexigras** [comment]
minflayer is a libary for nodejs and requires a basic understanding of nodejs to be used.

if you need help with nodejs i can help you over at https://gitter.im/PrismarineJS/mineflayer or you can look up the nodejs basic yourself.

**Comment by lewisg743** [comment]
I mean do you think you could give me a list of instructions on using this, i just wanna just a bunch of bots to see how my server holds up ?

**Comment by plexigras** [comment]
> if you need help with nodejs i can help you over at https://gitter.im/PrismarineJS/mineflayer
