### ISSUE TITLE
Prismarine-Chunk error on Server Join

### ISSUE THREAD

**Issue by KittenPopo** [PrismarineJS/mineflayer#518]
![img_1968](https://cloud.githubusercontent.com/assets/28826980/26286537/ef596248-3e1c-11e7-8bde-4c31dbec4837.PNG)

When I attempt to start the bot on a server it immedietly stops with this error.

I have not modified any files, and was just testing out one of the example scripts.

**Comment by rom1504** [comment]
What server version and kind (vanilla, spigot, etc) ?

**Comment by KittenPopo** [comment]
It is spigot, and it seems to be a spigot error with further testing.

**Comment by JonasFowl** [comment]
Also happens using the vanilla client 'open to LAN' server. (1.11 & 1.11.2) @rom1504

**Comment by rom1504** [comment]
fixed now
