### ISSUE TITLE
Improve printing of errors (in examples)

### ISSUE THREAD

**Issue by theonlygusti** [PrismarineJS/mineflayer#519]
I get this error when attempting to use `mineflayer`

> ```You are using a pure-javascript implementation of RSA.
> Your performance might be subpar. Please consider installing URSA```

How do I fix it?

**Comment by rom1504** [comment]
This is a warning not an error.
See the readme if you want to install Ursa.
But you don't really need to, it works without it.

**Comment by theonlygusti** [comment]
Why doesn't the example program do anything then?

In my file is this:

```
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "localhost", // optional
  port: 25565,       // optional
  username: "email@example.com", // email and password are required only for
  password: "12345678",          // online-mode=true servers
});
bot.on('chat', function(username, message) {
  if (username === bot.username) return;
  bot.chat(message);
});
```

I was expecting the program to stay open, but it closes immediately.

**Comment by theonlygusti** [comment]
Also I can't see anything on RSA or URSA in the readme

**Comment by theonlygusti** [comment]
@rom1504

**Comment by rom1504** [comment]
What server version are you connecting to ?

**Comment by theonlygusti** [comment]
1.11.2, running on Spigot

**Comment by theonlygusti** [comment]
@rom1504 I also tried with the more extended inventory example, same result: app doesn't do anything, just exits immediately after printing "You are using a pure-javascript implementation of RSA. Your performance might be subpar. Please consider installing URSA"

**Comment by roblabla** [comment]
Please give us a packet dump by setting the DEBUG variable to "minecraft-protocol". On linux, this would be `DEBUG=minecraft-protocol node examples/whatever.js`

**Comment by theonlygusti** [comment]
Oh my! I am so sorry for wasting your time.

Turns out that the player wasn't whitelisted on the server, setting `DEBUG` as you suggested revealed.

I wonder if instead of silently exiting if you don't get past the whitelist it should print this info?

**Comment by roblabla** [comment]
We should probably print the kick message in those examples.

**Comment by rom1504** [comment]
yeah https://github.com/PrismarineJS/mineflayer/blob/master/examples/chatterbox.js#L133

**Comment by theonlygusti** [comment]
Maybe mineflayer could be relied upon to print "errors" etc. rather than the scripts, and provide the scripts something like the browser's `e.preventDefault()` to stop this from happening when desired?
