### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by MrSonicMaster** [PrismarineJS/mineflayer#525]
I'm getting this:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

**Comment by MrSonicMaster** [comment]
Fixed by adding 
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`
to end of file

**Comment by roblabla** [comment]
Please please please please **please** don't do this. Something is **wrong** on your setup and you have to fix it. Disabling unauthorized TLS rejection means your connection is completely insecure, and someone could MITM you, get your credentials, and do god knows what with it.

**Comment by MrSonicMaster** [comment]
Thanks for pointing this out, it wasn't for my computer it was for someone who I was helping. I'll have to point this out to them.
