### ISSUE TITLE
Expose a bot.swingArm()

### ISSUE THREAD

**Issue by KittenPopo** [PrismarineJS/mineflayer#535]
I am making a human-like PvP script and need the bot to swing its arm/sword and miss without actually attacking the entity. I can't seem to find this in the API, and was wondering if that was possible?

If not, I guess I could try to get the bot to place a block at the player or "open" the entity to swing its arm. But that may not work out.

Thanks in advance.

**Comment by rom1504** [comment]
Oh yeah it seems we didn't put that in the API.
it's `bot._client.write('arm_animation', {hand:0});`

**Comment by rom1504** [comment]
That should be exposed in a bot.swingArm() , I'm leaving the issue open until we do that.

**Comment by KittenPopo** [comment]
I assume this just plays the arm_swing animation but cannot be used to hit/break anything, right?

**Comment by plexigras** [comment]
yes
