### ISSUE TITLE
Cannot override bot.findBlock

### ISSUE THREAD

**Issue by ViRb3** [PrismarineJS/mineflayer#539]
Greetings,

I just installed [https://github.com/Darthfett/mineflayer-blockFinder](mineflayer-blockFinder) and after debugging my project I noticed that its implementation is always ignored in favor of the one in **mineflayer**.

Here's some code snippets:

My project's code:
```
var bot = mineflayer.createBot({
...
});

// Install the plugin - method override is done here
blockFinderPlugin(bot);

// Sample usage
bot.once('spawn', function() {
  bot.findBlock(...) // the original findBlock is called instead of the plugin`s
});
```

The injection function `blockFinderPlugin` is successfully called and the override code also succeeds:

```
        function findBlockSync(options) {
...
        }

        function findBlock(options, callback) {
...
        }

        bot.findBlock = findBlock;
        bot.findBlockSync = findBlockSync;  
```

Yet the original function is always called instead. I don't know if the issue belongs here or at the plugin dev's repo, so apologies if this isn't meant for here.

Cheers

**Comment by rom1504** [comment]
Ah yes, this is due to the new version system which guess the version and
load the plugin afterwards.
That should be fixed somehow

**Comment by ViRb3** [comment]
Temporary fix was to change the plugin's implementation from `findBlock` to `findBlockEx`, but surely a proper solution would be better.

**Comment by rom1504** [comment]
@plexigras since you implemented the auto version thing, do you have any idea about this ?

Maybe mineflayer should emit an event for when plugin can inject. That kind of break all the current plugin integration though...

**Comment by rom1504** [comment]
#544 fixes this, it'll be available in the next mineflayer release

**Comment by rom1504** [comment]
now fixed, have a look at https://github.com/Darthfett/mineflayer-blockfinder/pull/16
