### ISSUE TITLE
"blockUpdate:(x, y, z)" (oldBlock, newBlock) doesn't fire

### ISSUE THREAD

**Issue by ViRb3** [PrismarineJS/mineflayer#540]
I tried hooking it this way:
```
bot.on('blockUpdate:(-89.5, 10.001, 162.5)', function(oldBlock, newBlock) {
        bot.chat('update update...!');
      });
```

yet it didn't fire. Hooking only `blockUpdate` worked. How do I specify the coordinates for which I wish to listen for block updates?

Thanks!

**Comment by rom1504** [comment]
Block don't have floating point coordinates !
try without the .5 , .001, etc
