### ISSUE TITLE
Problematic reconnect after sudden disconnect

### ISSUE THREAD

**Issue by ViRb3** [PrismarineJS/mineflayer#542]
I'm not sure if this is really what's happening, I'm still investigating. 
**Under stop I mean I instantly close the node.js process.**

I use the below function to equip **cobblestone**, everything works. When I suddenly stop the bot and make him join again, he automatically equips a **pickaxe** the moment he joins, the first item in his inventory. Another weird thing is that if I've broken the block under him while he was disconnected, the bot will be hanging in the air for 4-5 seconds before falling. When I call the below function again, mineflayer believes he's already holding cobblestone, while it's clearly not the case.
```js
function equipBuildingBlock(cb) {
        // return true if we're already good to go
        if (bot.heldItem && scaffoldBlockTypes[bot.heldItem.type]) { // says cobblestone, is actually pickaxe
            cb();
            return true;
        }

        var scaffoldingItems = bot.inventory.items().filter(function (item) {
            return scaffoldBlockTypes[item.type];
        });

        var item = scaffoldingItems[0];
        if (!item) {
            changeState('stop', 'error');
            return false;
        }

        bot.equip(scaffoldingItems[0], 'hand', function (err) {
            if (err) {
                changeState('stop', 'error', err);
                return;
            }
            cb();
        });
    }
```

I suppose mineflayer may not be using the `equip` callback in internal code, thus causing this issue.

**Comment by rom1504** [comment]
Mineflayer doesn't call bot.equip internally.
However you might be re-equiping too early.
When are you calling that function ?

**Comment by ViRb3** [comment]
> Mineflayer doesn't call bot.equip internally.

That's strange, because I just tried logging in with an entirely empty script and the bot still equipped the pickaxe.

> However you might be re-equiping too early.
When are you calling that function ?

I'm giving the bot a good 30 seconds to initialize before calling it, so it's not that.

**Comment by rom1504** [comment]
Please reopen if this is still an issue for you
