### ISSUE TITLE
Let's have a swim

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#545]
I think the api should look like that https://github.com/PrismarineJS/mineflayer/blob/master/doc/api.md#botcreativeflytodestination-cb

Also google says you should listen to https://www.youtube.com/watch?v=lGMZenRI8G8 while implementing this issue.

**Comment by rom1504** [comment]
Is it possible to swim under water with the last PR now @Karang  ? (With what API ?)

**Comment by Karang** [comment]
> Is it possible to swim under water with the last PR now @Karang ? (With what API ?)

Yes it is possible, the controls works as you would expect (press jump to start going up, release to go down). The pathfinding is not yet taking advantage of it, but it can be added.

**Comment by rom1504** [comment]
Okay I think we can close this then
