### ISSUE TITLE
Read and use block entities nbt

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#548]
http://wiki.vg/Protocol#Update_Block_Entity

and 

block entities of http://wiki.vg/Protocol#Chunk_Data

I believe this is where sign texts are now stored.

(will only be useful for >= 1.12)

**Comment by rom1504** [comment]
tile_entity_data

**Comment by wvffle** [comment]
I guess it should be closed by now

**Comment by rom1504** [comment]
Indeed !
