### ISSUE TITLE
Online mode broken due to autoversion

### ISSUE THREAD

**Issue by Frostman** [PrismarineJS/mineflayer#551]
Trying to run echo.js example, but it does nothing.

Workaround was found in comments - specify version explicitly when creating bot (version: "1.12").

tl;dr

1. I've downloaded echo.js example and trying to run it

2. I've enabled debug for minecraft proto

3. Running it with the following command and getting following logs:

```
$ node echo.js myserver.com 25565 "email" "password"
  minecraft-protocol pinging myserver.com +0ms
  minecraft-protocol writing packet handshaking.set_protocol +184ms
  minecraft-protocol { protocolVersion: 47,
  minecraft-protocol   serverHost: 'myserver.com',
  minecraft-protocol   serverPort: 25565,
  minecraft-protocol   nextState: 1 } +0ms
  minecraft-protocol writing packet status.ping_start +7ms
  minecraft-protocol {} +0ms
  minecraft-protocol read packet status.server_info +20ms
  minecraft-protocol { response: '{"description":{"text":"Frostman\\u0027s Minecraft Server"},"players":{"max":20,"online":0},"version":{"name":"1.12","protocol":335}}' } +0ms
  minecraft-protocol writing packet status.ping +1ms
  minecraft-protocol { time: [ 0, 0 ] } +0ms
  minecraft-protocol read packet status.ping +16ms
  minecraft-protocol { time: [ 0, 0 ] } +1ms
  minecraft-protocol ping response { description: { text: 'Frostman\'s Minecraft Server' },
  players: { max: 20, online: 0 },
  version: { name: '1.12', protocol: 335 },
  latency: 17 } +0ms
  minecraft-protocol Server description: { text: 'Frostman\'s Minecraft Server' } +0ms
  minecraft-protocol Server version: 1.12, protocol: 335 +1ms
```

4. Process exits after 30 seconds of running...

**Comment by Frostman** [comment]
What's interesting - adding or removing bot to the whitelist.json doesn't change anything...

I'd really appreciate any help!

**Comment by toomykins** [comment]
I'm having the same problem with all examples. They only work on unauthorized accounts. It will throw an error when a password is given and the username/password is wrong, but they will simply hang when proper credentials are entered.
Tested on vanilla servers 1.8.8 to 1.12

`***@***:~/mineflayer/examples$ DEBUG=* js digger.js localhost 25565 **LEGIT EMAIL OF MOJANG ACCOUNT** **LEGIT PASSWORD**
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
  minecraft-protocol pinging localhost +0ms
  minecraft-protocol writing packet handshaking.set_protocol +186ms
  minecraft-protocol { protocolVersion: 47,
  minecraft-protocol   serverHost: 'localhost',
  minecraft-protocol   serverPort: 25565,
  minecraft-protocol   nextState: 1 } +0ms
  minecraft-protocol writing packet status.ping_start +8ms
  minecraft-protocol {} +0ms
  minecraft-protocol read packet status.server_info +51ms
  minecraft-protocol { response: '{"description":{"text":"A Minecraft Server"},"players":{"max":20,"online":0},"version":{"name":"1.10","protocol":210}}' } +0ms
  minecraft-protocol writing packet status.ping +1ms
  minecraft-protocol { time: [ 0, 0 ] } +0ms
  minecraft-protocol read packet status.ping +2ms
  minecraft-protocol { time: [ 0, 0 ] } +0ms
  minecraft-protocol ping response { description: { text: 'A Minecraft Server' },
  players: { max: 20, online: 0 },
  version: { name: '1.10', protocol: 210 },
  latency: 3 } +1ms
  minecraft-protocol Server description: { text: 'A Minecraft Server' } +0ms
  minecraft-protocol Server version: 1.10, protocol: 210 +1ms
***@***:~/mineflayer/examples$ 
`
The script kinda hangs and then exits after half a minute or so.
tried with 4 different accounts. Experienced on ubuntu 16.04

**Comment by plexigras** [comment]
are you sure its a 1.12 or 1.8.8 server?

> minecraft-protocol Server version: 1.10, protocol: 210 +1ms

**Comment by toomykins** [comment]
> are you sure its a 1.12 or 1.8.8 server?
I tested from 1.8.8 to 1.12, this example was from 1.10.
I read that the program automatically guesses the version and uses the correct protocol

**Comment by plexigras** [comment]
you got the same problem running minecraft-protocol examples?

```
node ./node_modules/minecraft-protocol/examples/client_echo/client_echo.js localhost 25565
```

**Comment by TheTechPony** [comment]
Same problem here

Problem: https://pastebin.com/5Kj9AxGY
Current script: https://pastebin.com/quRPP8Cx

**Comment by Frostman** [comment]
It works for me if version: "1.12" specified

**Comment by TheTechPony** [comment]
I'm trying tons of servers and they all throw errors. When it does work and connect I get an error for chat patterns
https://pastebin.com/LANSzHHX

**Comment by plexigras** [comment]
you got the same problem running minecraft-protocol examples?

**Comment by TheTechPony** [comment]
Minecraft-protocol examples work fine but anything mineflayer I get the deserialization error

**Comment by TheTechPony** [comment]
A lot of the servers I find hit me with that error but there are a few that work fine on.

two examples
mc.differentcraft.net
play.intenseraids.com

**Comment by rom1504** [comment]
@TheTechPony @Frostman @toomykins 
Can you provide example of servers that *don't* work ?

It's important to provide steps to reproduce the problems.

**Comment by rom1504** [comment]
related https://github.com/PrismarineJS/node-minecraft-protocol/issues/348 https://github.com/PrismarineJS/mineflayer/issues/346

**Comment by rom1504** [comment]
so I tried `mc.differentcraft.net`, some specific action is required to go to the real server in-game.

**Comment by rom1504** [comment]
Ok reproduced. Apparently online mode doesn't work with the new autoversion thing.

And we disabled the tests for that in nmp because of mojang banning account that auth too fast...

Let me try to fix it.

**Comment by roblabla** [comment]
@rom1504 we might want to contact mojang about that username banning thing. Maybe we could ask them to whitelist our account ? Or ask them for guidance about avoiding this issue ?

**Comment by plexigras** [comment]
another possible solution might be to redirect the auth package to a local server

http://wiki.vg/Protocol_Encryption#Server
