### ISSUE TITLE
create default issue

### ISSUE THREAD

**Issue by plexigras** [PrismarineJS/mineflayer#552]
so we can have some information like

- what happens when using a minefalyer example?
- what happens when using a nmp example?
- what mineflyer version?
- what server version?
- which server?
- what's the output of DEBUG="minecraft-protocol"?
- what's the error msg?
- what script is used?
- ...

**Comment by rom1504** [comment]
yeah would be nice https://github.com/PrismarineJS/mineflayer/blob/master/doc/contribute.md#reporting-bugs

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/issue_template.md

thanks for the example of content @plexigras
