### ISSUE TITLE
bot.chat not doing anything

### ISSUE THREAD

**Issue by TheTechPony** [PrismarineJS/mineflayer#554]
Here's the chat function
`bot.on("chat", function(username, message) {
    console.log('Chat');
    bot.chat(message)
});`

Here's the full code
https://pastebin.com/ULcVxgtb

It's just not working at all. No errors or anything it's simply not running the function

**Comment by plexigras** [comment]
its probably that the chat isn`t matching the vanilla chat pattern

```js
/^<(?:.+? )?(.+?)> (.*)$/
```
whats the output of

```js
bot.on('message',  msg => console.log(msg.toString()))
```

**Comment by TheTechPony** [comment]
It outputs as you'd expect. So how do I fix this then?

**Comment by TheTechPony** [comment]
It has occurred to me that I'm an idiot and never actually whispered the bot but instead just used the default chat to test it when in fact I should have been using /msg. Fixed and closed.

Thanks for the support! :)

**Comment by TheTechPony** [comment]
Yet again I'm having this issue and I'm using the same code as before but it just decided to stop reading the chat. I feel like these issues are only issues for me and idk why.
https://pastebin.com/DZWNY2V5

**Comment by plexigras** [comment]
whats the output of

```js
bot.on('message',  msg => console.log(msg.toString()))
```

**Comment by TheTechPony** [comment]
https://pastebin.com/NwgydXQk

**Comment by plexigras** [comment]
there is no chat getting logged bc there is no one talking???

**Comment by TheTechPony** [comment]
https://pastebin.com/bQMzfsyN
Towards the end you can see me both say a message in chat and /msg the bot and it's not printing "Chat" in console like the code should.

**Comment by plexigras** [comment]
```
[ Waldheim ]< [ Member ]TheTechPony > t
```

dose not match

```js
/^<(?:.+? )?(.+?)> (.*)$/
```

**Comment by TheTechPony** [comment]
bot.chatAddPattern(/^\[.*?(\w*) -> me \] (.*)$/, "whisper", "essentials whisper");

**Comment by TheTechPony** [comment]
After rigorous testing I found that I have to change it from "whisper" to "chat" for it to work even though it is a whisper.
