### ISSUE TITLE
Full tutorial on how to install

### ISSUE THREAD

**Issue by SuperOP535** [PrismarineJS/mineflayer#558]
I cannot find any good tutorials on how to Install/Run MineFlayer I've installed Nodejs v8.1.3 and I ran npm install mineflayer... but what now?? os: windows 10

**Comment by plexigras** [comment]
`node pathToTheScript.js` for example run `node examples/echo.js`

**Comment by SuperOP535** [comment]
ok thx I will try now!

**Comment by SuperOP535** [comment]
It says stuff about URSA where can I get it @plexigras

**Comment by SuperOP535** [comment]
it just joins and when I chat it does nothing then it leaves

**Comment by roblabla** [comment]
URSA is an optional dependency, you can safely ignore this issue.

Mineflayer is a **library**. You need to write scripts that use it. https://github.com/PrismarineJS/mineflayer/blob/master/examples/echo.js this is the script plexigras is making you run. All it does is connect, and repeat everything you say. If it isn't working, you need to tell us what server you're using it with (address or software + version used)

**Comment by SuperOP535** [comment]
127.0.0.1 50324 (lan) mc 1.11.2

**Comment by SuperOP535** [comment]
Do you know how I can install URSA because npm install ursa gives lots of errors

**Comment by SuperOP535** [comment]
And what node.js version is recommended for MineFlayer?

**Comment by rom1504** [comment]
put "version":"1.12" in the options in echo.js

**Comment by roblabla** [comment]
@rom1504 he's using mc 1.11.2. He needs to put `"version":"1.11"` no ?

@SuperOP535 You should at least use last nodejs LTS. 

URSA doesn't work on windows (well, it does, but it's a real pain in the ass to install). You don't really need it, so you probably shouldn't bother with it. It just makes auth faster, which is mostly useful for servers.

**Comment by rom1504** [comment]
@roblabla oh yes indeed. Autoversion being broken and all...

**Comment by SuperOP535** [comment]
Thanks!!! I think I will try to run Mineflayer on a Linux VM later

**Comment by SuperOP535** [comment]
I can't get it to join an online-mode=true server with version: "1.11.2" it says the first 2 rsa warnings and then exits

**Comment by SuperOP535** [comment]
The bot doesn't change name and it doesn't join online-mode=true servers
here is my code:
`var mineflayer = require('mineflayer');

if(process.argv.length < 4 || process.argv.length > 6) {
  console.log("Usage : node echo.js <host> <port>");
  process.exit(1);
}

var bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: "HelloBot",
  password: "",
  version: "1.11",
  verbose: true,
});

bot.on('chat', function(username, message) {
  if(username === bot.username) return;
  if(username === "SuperOP535){
  bot.chat(message);
  }
});
`

**Comment by SuperOP535** [comment]
![bild](https://user-images.githubusercontent.com/27556391/28026611-ea4cc726-6596-11e7-8b5b-ab3b0f087e7d.png)
Is this the right place to have the folder in?

**Comment by rom1504** [comment]
If it's 1.11.2, you need to write 1.11.2

**Comment by SuperOP535** [comment]
Ok but is that right place for the folder

**Comment by rom1504** [comment]
No, you don't need to globally install mineflayer.
Just run npm install --save mineflayer in your project directory.

**Comment by SuperOP535** [comment]
I did cd to the folder and then the command you sent but it spammed me errors

**Comment by SuperOP535** [comment]
I finally got it to work, the problem was that I had 3 node_modules folders but now I found the right one and the modifications save. thx for helping
