### ISSUE TITLE
Document how to use minecraft-protocol-forge with mineflayer

### ISSUE THREAD

**Issue by Kyso** [PrismarineJS/mineflayer#56]
To some extent, you won't have to implement the mods directly, but at least send the packet that Forge wants to let it work? _shrug_

**Comment by deathcap** [comment]
@rom1504 can you reopen this issue? Still would be a cool feature =) Requires lower-level protocol support first https://github.com/PrismarineJS/node-minecraft-protocol/issues/114

**Comment by deathcap** [comment]
> MinecraftForge mod on server sends packet to mineflayer requesting for mods x, y and z, which are necessary to join.
> Mineflayer responds request by falsifying a succeeded packet, repeats for each requested mod.

Good idea, https://github.com/ORelio/Minecraft-Console-Client/pull/100 (a console client with Forge (1.8 and 1.7.10) support) used this same technique

**Comment by rom1504** [comment]
Yeah reopening. Nothing can be done here until PrismarineJS/node-minecraft-protocol#114 is done though.

**Comment by rom1504** [comment]
Now that nmp has a minecraft-forge plugin, something can be done here.
Not sure if it would be directly in mineflayer or as a mineflayer-forge (a plugin is probably better)

**Comment by rom1504** [comment]
let's close this
It can be reopened if there's a real need
