### ISSUE TITLE
Chest GUI

### ISSUE THREAD

**Issue by digitalsirkeith** [PrismarineJS/mineflayer#567]
Suppose I wish to connect my bot to a Spigot server and there's a plugin installed that provides a chest UI, say for example, Chest Commands GUI. How can I retrieve the chest window instance?

**Comment by 109C** [comment]
`bot.currentWindow` looks promising.

https://github.com/PrismarineJS/mineflayer/blob/2d5e3e98360cc510afdb96182f58d2c2bf86f634/lib/plugins/inventory.js#L509

**Comment by digitalsirkeith** [comment]
"windowOpen" (window) appears to do the trick. However I am unable to interact with the window.

**Comment by rom1504** [comment]
> that provides a chest UI, say for example, Chest Commands GUI

When does that window get opened ?

**Comment by digitalsirkeith** [comment]
It's a skyblock server. A window gets opened when you type "/is"

Handling the event "windowOpen" after sending the command works, however I am still unable to interact with the window. I tried the prismarine-windows API and the lower level methods to click an item.

**Comment by rom1504** [comment]
you could try doing the same as https://github.com/PrismarineJS/mineflayer/blob/2d5e3e98360cc510afdb96182f58d2c2bf86f634/lib/plugins/inventory.js#L253
except you replace the bot.activateBlock by bot.chat("/is")

**Comment by rom1504** [comment]
yes, what's the problem when trying to interact with the window ?

**Comment by digitalsirkeith** [comment]
` Creating a new island for you...
/home/ubuntu/workspace/node_modules/minecraft-protocol/src/transforms/framing.js:76
          throw e;
          ^

Error: Deserialization error for play.toClient : Read error for name : 119 is not in the mappings value
    at ProtoDef.readMapper (/home/ubuntu/workspace/node_modules/protodef/src/datatypes/utils.js:27:31)
    at ProtoDef.read (/home/ubuntu/workspace/node_modules/protodef/src/protodef.js:127:29)
    at tryDoc (/home/ubuntu/workspace/node_modules/protodef/src/datatypes/structures.js:46:32)
    at tryCatch (/home/ubuntu/workspace/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/home/ubuntu/workspace/node_modules/protodef/src/utils.js:67:10)
    at typeArgs.forEach (/home/ubuntu/workspace/node_modules/protodef/src/datatypes/structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (/home/ubuntu/workspace/node_modules/protodef/src/datatypes/structures.js:44:12)
    at ProtoDef.read (/home/ubuntu/workspace/node_modules/protodef/src/protodef.js:39:25)
    at ProtoDef.read (/home/ubuntu/workspace/node_modules/protodef/src/protodef.js:127:29)`

bot.clickWindow throws this error

**Comment by rom1504** [comment]
What server is it ?

**Comment by digitalsirkeith** [comment]
KeiNett

IP: mc.keinett.com

**Comment by digitalsirkeith** [comment]
I tried logging in with my own account using the bot and it throws the same error. I think the error in the packets may be from the server teleporting me to the island.

**Comment by rom1504** [comment]
it seems some custom servers have custom packets, I don't really understand how the vanilla client is ok with that, related to #543

**Comment by digitalsirkeith** [comment]
@rom1504 I tried adding the customPackets attribute to the bot and replacing 0x6C (108) with 0x77 (119) but it still throws the same error.

**Comment by digitalsirkeith** [comment]
Okay, I checked [https://github.com/PrismarineJS/mineflayer/issues/543](url) and tried to understand the object. I fiddled with the source code and added the custom packet attributes and the map key to the protocol.json file. Oddly enough it worked. and created the island. @rom1504

**Comment by ViRb3** [comment]
@digitalsirkeith Could you please elaborate how you managed to fix this issue?

**Comment by digitalsirkeith** [comment]
> @digitalsirkeith Could you please elaborate how you managed to fix this issue?

It's not much of a fix in my opinion but here's how I did it:

1. Open `/node_modules/minecraft-data/minecraft-data/data/pc/1.11/protocol.json`
2. Check the code in #543 
3. Insert the contents of the code into the file in (1), replacing the packet id with the one in your error.

This is a little vague but as I've said. It's not really a fix but rather a workaround.
