### ISSUE TITLE
bot.sleep() does not give error for when monsters are nearby.

### ISSUE THREAD

**Issue by toomykins** [PrismarineJS/mineflayer#568]
bot.sleep() should give an error when it fails, and does so when it's not night, but doesn't give an error if it fails due to monsters nearby.
Can easily be circumvented externally, just thought i'd let you know since it seems like it'd be an internal thing.

**Comment by plexigras** [comment]
we should have a timeout and wait for [protocol#toClient_bed](https://prismarinejs.github.io/minecraft-data/?d=protocol#toClient_bed) at [bed.js#L28](https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/bed.js#L28)

**Comment by rom1504** [comment]
agreed

**Comment by rom1504** [comment]
better than having to check whatever conditions mojang feel like adding

**Comment by ImHarvol** [comment]
> better than having to check whatever conditions mojang feel like adding

What about checking whether this packet is received? 
`{ message: '{"translate":"tile.bed.notSafe"}', position: 2 }`

This is sent as a game info chat message to the client when you try to sleep while there are hostile mobs near the you

**Comment by rom1504** [comment]
why ?
@plexigras already gave the correct solution
