### ISSUE TITLE
"Unexpected token =" when running echo.js

### ISSUE THREAD

**Issue by duralakun** [PrismarineJS/mineflayer#570]
I am using ubuntu and just installed mineflayer, but i cant get the echo script to run.

node node_modules/mineflayer/examples/echo.js

> node_modules/mineflayer/index.js:48
> function createBot (options = {}) {
> SyntaxError: Unexpected token =
>     at exports.runInThisContext (vm.js:53:16)

Could it be that i am running an outdated version of nodejs? (i am using v4.2.6)
I am new to nodejs, pls help

**Comment by plexigras** [comment]
yes update node

**Comment by duralakun** [comment]
ok thanks it worked.
What i did:

> sudo npm install -g n
> sudo n latest
> sudo ln -sf /usr/local/n/versions/node/8.2.1/bin/node /usr/bin/nodejs
(replace 8.2.1 with the latest version)

just leaving this here for people like me
