### ISSUE TITLE
setControlState('forward', true) getting kicked for fly hacking

### ISSUE THREAD

**Issue by duralakun** [PrismarineJS/mineflayer#572]
I just want to move forward with the bot (not fly), i tried it on my local machine and it worked fine with:

> setControlState('forward', true)

but when i try the same on an online server (with many players) i get instantly kicked for fly hacking.

How does the server know the difference between the bot moving and a player? Is there a way around this?

**Comment by KittenPopo** [comment]
It seems it could be 1 of 3 things:

1. The bots ControlState method moves too quickly, which sensitive anticheats can pick up on and assume you are speed hacking.

2. The bot moves very suddenly with no ease, something players cannot do. The anticheat senses this and suspects fly hacking.

3. You are moving slightly upwards or over something, that you would normally fall down onto, and the anticheat thinks you are flyhacking. This might happen if you are moving on half slabs.

The anticheat can't tell the bot moving v.s. the player, as the bot uses the same imput as Minecraft when you hit the "W" key. So it must be something irregular causing the anticheat to kick you.

**Comment by duralakun** [comment]
Thank you KittenPopo !
It was number 3. 
When I did the test the bot was staying on carpet. Now i logged in back without the carpet and this works. The server no longer kicks the bot for fly hacking.

**Comment by duralakun** [comment]
I just did some tests and the bot treats carpets like solid blocks! Meaning it will just walk above them, ofcourse it get kicked for fly hacking ^^

**Comment by rom1504** [comment]
#228
