### ISSUE TITLE
WAIT_TIME_BEFORE_NEW_JUMP to high

### ISSUE THREAD

**Issue by duralakun** [PrismarineJS/mineflayer#573]
at: https://github.com/PrismarineJS/mineflayer/blob/e5f9f4fad53019a3780a48c19d567fac28709a2b/lib/plugins/physics.js#L14

when using the navigator plugin, it cannot do jumps repeatly, this can be easily fixed
by changing

> const WAIT_TIME_BEFORE_NEW_JUMP = 0.3

to

> const WAIT_TIME_BEFORE_NEW_JUMP = 0.07

see also:
https://github.com/PrismarineJS/mineflayer-navigate/issues/14

but I don't know if 0.07 is the correct value or if this will break something else

**Comment by roblabla** [comment]
TBH, instead of "WAIT_TIME_BEFORE_NEW_JUMP, shouldn't we detect when it's safe to jump again internally ? IDK if we have an event like this, but it seems like we should have an `on_ground` event and jump again in that ? Am I missing something ?

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/mineflayer/issues/327
and https://github.com/PrismarineJS/mineflayer/issues/114

not sure what is the correct fix.

**Comment by duralakun** [comment]
about #114
When i set bot.setControlState('jump', true) the bot will jump continously. Sometimes it looks like it doesnt touch the ground, but i think its just lag and it does actually touch the ground. I let the bot jump for 5 min and it never hurted itself.

So far I couldnt find any bugs or unwanted beahviour after setting
> const WAIT_TIME_BEFORE_NEW_JUMP = 0.07

**Comment by rom1504** [comment]
ok I'm fine with that then
