### ISSUE TITLE
Is it possible to view from a Client?

### ISSUE THREAD

**Issue by KittenPopo** [PrismarineJS/mineflayer#577]
I know that there is a mineflayer plugin called Voxel that attempts a 3D rendering of where it is, but I was wondering how easy/difficult it would be to make Mineflayer run in it's own client.

That way users could take full control of the client, and view what it is doing at all times. 

I am fairly confident this would not be too possible as it seems Mineflayer runs off sending packets and simulating what would happen if it was actually in Minecraft.

**Comment by plexigras** [comment]
It is posible to use the vanila client in conjunction with a nmp server as a proxy.

[PrismarineJS/node-minecraft-protocol/tree/master/examples/proxy](https://github.com/PrismarineJS/node-minecraft-protocol/tree/master/examples/proxy)

I might write a mineflayer implementation at some point but first i would like to see the nmp client stream interface to be implemented. https://github.com/PrismarineJS/node-minecraft-protocol/issues/504

**Comment by rom1504** [comment]
have a look at https://github.com/PrismarineJS/mineflayer/issues/315 for the proxy idea.

For the voxel idea, there's https://github.com/voxel/voxel-clientmc and https://github.com/rom1504/voxel-prismarine-world

**Comment by rom1504** [comment]
out of scope of mineflayer, but cool
