### ISSUE TITLE
WindowOpen event doesn't fire on custom window

### ISSUE THREAD

**Issue by ViRb3** [PrismarineJS/mineflayer#582]
I am trying to use mineflayer on a server with BungeeCord. There's a lobby server where you first spawn, and then using either the compass item or the `/servers` command, you can select which server you want to play on, and you get teleported. Unfortunately, the `windowOpen` event never fires on either of the above actions. I confirmed I am logged in and I can send messages before trying the `/servers` command.

Debug log: https://gist.githubusercontent.com/ViRb3/ccdfb1c7d59fbf87e2cb94792afae8b4/raw/3e45374eebed7b2e18764c92300b2c607e98c1b6/log

Script:
```js
var mineflayer = require('mineflayer');

var bot = mineflayer.createBot({
    username: 'Steve',
    verbose: true,
    port: 25565,
    host: 'play.iplexmc.eu',
    version: '1.12'
});

var isIn = true;

bot.on('spawn', function() {
  setTimeout(function () {      
    bot.chat('/login pass123');

    setTimeout(function () {
      bot.chat('/servers');
            
    }, 1500);
  }, 1500);
});

bot.on('windowOpen', function (window) {
  console.log("hurray"); // never reached
  bot.clickWindow(14,0,0);
});
```

**Comment by duralakun** [comment]
Don't know if this helps, but you can see the inventory and what items are in like this (shows also chests):
```
const window = bot.currentWindow || bot.inventory
console.log(window.slots)
```
You can also try this event that gets fired when something in your inventory changes:
```
bot.inventory.on('windowUpdate', onWindowUpdate);
function onWindowUpdate(slot, oldItem, newItem) {
  console.log(slot+": "+newItem);
}
```

**Comment by rom1504** [comment]
fixed
