### ISSUE TITLE
Head not looking issue and other questions

### ISSUE THREAD

**Issue by johnpyp** [PrismarineJS/mineflayer#596]
I have a problem where the head on the bot is not looking towards an entity when I tell it to. I have a loop to auto grind mobs at about once/100ms. I am also using the bot.lookAt property at the beginning of the loop to try to look at the mob. The entities are getting hit and being tracked properly, the problem is just that the head isn't moving at all, no signs of it being responsive so it definitely looks like the bot is hacking.

Other questions rather than issues:

1) how would I make the bot reconnect after it gets kicked to the main menu?

2) How would I route the connection through a proxy so the IP address of the bot to the server isn't my computer IP?

**Comment by roblabla** [comment]
Please post a snippet of the code you're using so we can help you with your lookAt issue.

For your questions : 

1. Just call `bot.connect(yourBotOptionsHere)` to make it reconnect to the server.

2. There are multiple ways to go at using a proxy.
  - You can either use the `stream` option https://github.com/PrismarineJS/mineflayer/issues/461#issuecomment-267124920
  - Or the `connect` option https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_http_proxy/client_http_proxy.js .

**Comment by johnpyp** [comment]
Sorry I didn't post a snippet, was on my phone last night. Thanks for the help with the first two things, I can't believe I missed bot.connect as an option! Here is the full command I am using to attack mobs:

`  if (splitMessage[0] == "!atkmob") {
    if (socket.botinfo.mobgrinding) {
      socket.botinfo.stop = true;
      bot.whisper(username, "Stopped previous grind. Please try again now.");
      return;
    }
    var count = splitMessage[1] || 1;
    var sleep = 100;
    var notFound = 0;
    var fixCount = 0;
    (function myLoop(i) {
      setTimeout(function() {
        if (!socket.botinfo.mobgrinding) {
          socket.botinfo.mobgrinding = true;
        }
        socket.botinfo.atkmobremaining = i;
        socket.botinfo.atkmobmax = count;
        entity = nearestEntity(bot, "mob", 4);

        if (entity) {
          bot.lookAt(entity.position, true);
          if (entity) {
            bot.attack(entity, true);
            notFound = 0;
          }
          fixCount++;
          if (fixCount > 100) {
            bot.chat("/fix all");
            fixCount = 0;
          }
          //  pass the number of iterations as an argument
        } else {
          notFound++;
        }

        if (--i && !socket.botinfo.stop) {
          if (notFound < 200) {
            myLoop(i);
          } else if (nearestEntity(bot, "mob", 10)) {
            notFound = 0;
            bot.whisper(username, "Blazes coming, not here yet.");
            myLoop(i);
          } else {
            bot.whisper(username, "No entities nearby or time limit to listen for new mobs reached. Stopping.");
            socket.botinfo.mobgrinding = false;
            socket.botinfo.stop = false;
            socket.botinfo.atkmobremaining = 0;
            socket.botinfo.atkmobmax = 0;
          }
        } else {
          socket.botinfo.stop = false;
          bot.whisper(
            username,
            "Stop cmd or max clicks received (current: " + i + " start: " + count + ". At 0 it stops.). Stopping."
          );
          socket.botinfo.mobgrinding = false;
          socket.botinfo.atkmobremaining = 0;
          socket.botinfo.atkmobmax = 0;
        } //  decrement i and call myLoop again if i > 0
      }, getRandomInt(sleep, sleep * 1.5));
    })(count);
  }
function nearestEntity(bot, type, maxDist) {
  let id;
  let entity;
  let dist;
  let best = null;
  let bestDistance = null;
  for (id in bot.entities) {
    entity = bot.entities[id];
    if (type && entity.type !== type) continue;
    if (entity === bot.entity) continue;
    dist = bot.entity.position.distanceTo(entity.position);
    if ((!best && dist < maxDist) || (dist < bestDistance && dist < maxDist)) {
      best = entity;
      bestDistance = dist;
    }
  }
  return best;
}

`

Also, in nneartestEntity function, is there any way to specify a specific mob rather than mob as mob type? There is a mobaura detection on the server I play on that hasn't been triggered yet, but I feel like it be. Are there other identifiers I can use to try to narrow what entities get hit (blaze grinding).

**Comment by johnpyp** [comment]
Additionally, how do I catch errors that pop up from for example invalid credentials to make them instead show a message rather than closing the server? Wrapping the createBot function in a try/catch doesn't seem to work.

**Comment by roblabla** [comment]
you can do

```
bot.on("error", function(err) {
    // Do stuff with err here
})
```

However the connection will still probably be closed, so you'll have to call `bot.connect()` again, i think.

**Comment by johnpyp** [comment]
Gotcha. Is there docs for bot.connect? What about the head turning issue?

**Comment by roblabla** [comment]
OK so I went through the lookAt. It's defined [there](https://github.com/PrismarineJS/mineflayer/blob/be8bca3e81d8bc47062c6ac7a9afd3208bd0c67e/lib/plugins/physics.js#L332-L353). This function only updates some properties. Then [sendPosition](https://github.com/PrismarineJS/mineflayer/blob/be8bca3e81d8bc47062c6ac7a9afd3208bd0c67e/lib/plugins/physics.js#L246) is called every 50ms to send the position and look packets to the server.

I think using `force` here is wrong. I'm not sure what `force` is used for, but it's basically wrong because it ignores the server's NACKS. Maybe try not setting `force` ?

As for `bot.connect`, apparently it's not documented. It's an internal function of Mineflayer ^^'. You could just recreate the bot (call `createClient()` again, reset all your handlers...)

**Comment by roblabla** [comment]
Hmm... 🤔  Could you run your bot with `DEBUG=minecraft-protocol node yourbot.js` (setting the DEBUG env variable), reproduce the bug, and put the logs on a gist or somth ? This will allow me to look at the packets the client sends and receives. I suppose the problem is that the server is denying your look updates, but I'd like to make sure, and know why.

**Comment by johnpyp** [comment]
Yeah, I'll do that when I get home. With your suggestion to run an http proxy, how would I do it with the way I have my server configured right now? https://github.com/johnpyp/mineflayer-bot/blob/master/index.js

I am using a standard express server on http, but it seems the example you gave for connect works differently. Can i use http proxies in the same way you use Socks5 in the stream example? I only have http proxies. What package would I use for http client?

**Comment by roblabla** [comment]
In https://github.com/johnpyp/mineflayer-bot/blob/master/index.js#L28, you'd do this instead: 

```
socket.mcbot = mineflayer.createBot({
  username: data["username"],
  password: data["password"],
  verbose: true,
  version: "1.9",
  connect: function(client) {
    const req = Http.request({
      host: "my.http.proxy.ip",
      port: 443,
      method: 'CONNECT',
      path: data["host"] + ":" + parseInt(data["port"])
    });
    req.end();

    req.on("connect", function(res, stream) {
      client.setSocket(stream);
      client.emit('connect');
    });
  }
}
```

And you don't need a specific package. The built-in `http` nodejs client is enough.

**Comment by johnpyp** [comment]
When I turn on debug there is _very_ fast moving text. I believe this to be involved with the fact I changed cb(err) to cb() in compression.js to try to fix the unexpected end of file error. This is the only way the server I play on works. Additionally, the bot doesn't function as normal when I turned on debug. It connected, but none of the previous chat and functionality worked.

**Comment by rom1504** [comment]
Lookat has a callback

**Comment by johnpyp** [comment]
Ah, I understand. Unrelated, but how would I check item durability? It doesn't seem to be in the nbt tags on the item.

**Comment by rom1504** [comment]
It's the metadata value

**Comment by johnpyp** [comment]
Oh, thank you. My bot doesn't seem to be picking up items or exp as well. I will try to recreate on a local server, but at least on a multiplayer server it isn't.

**Comment by johnpyp** [comment]
Seems to pick up items on local server... any idea why not on multiplayer?

**Comment by johnpyp** [comment]
Nevermind again, it seems version 1,9 broke its ability to pick up items, but 1.8.9 works.

**Comment by johnpyp** [comment]
The head moving issue and other physics problems I had changing to 1.8.9. It seems 1.9 was the culprit of most of my issues.

**Comment by roblabla** [comment]
It's still broken on 1.9 though, right ? Maybe this should stay open ? @rom1504 ?

**Comment by johnpyp** [comment]
Yes, and now I just got a weird error after everything else seemed to be working fine. 
`D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:19
2                                                                                                                         
      throw(new Error(`Data buffer not correct size \(was ${data.length}, expected ${BUFFER_SIZE}\)`));                   
      ^                                                                                                                   
                                                                                                                          
Error: Data buffer not correct size (was 12288, expected 196864)                                                          
    at Chunk.load (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\prismarine-chunk\src
\pc\1.8\chunk.js:192:13)                                                                                                  
    at addColumn (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\mineflayer\lib\plugin
s\blocks.js:46:12)                                                                                                        
    at Client.bot._client.on (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\mineflaye
r\lib\plugins\blocks.js:166:5)                                                                                            
    at emitTwo (events.js:125:13)                                                                                         
    at Client.emit (events.js:213:7)                                                                                      
    at Parser.deserializer.on (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\minecraf
t-protocol\src\client.js:102:12)                                                                                          
    at emitOne (events.js:115:13)                                                                                         
    at Parser.emit (events.js:210:7)                                                                                      
    at addChunk (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\readable-stream\lib\_s
tream_readable.js:284:12)                                                                                                 
    at readableAddChunk (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\readable-strea
m\lib\_stream_readable.js:271:11)                                                                                         `

**Comment by johnpyp** [comment]
And with the 1.9 problem, one of the "bugs" turned out to be a feature for me -- not picking exp from mob drops. Is there any way I can turn this "bug" back on in 1.8?

**Comment by johnpyp** [comment]
Restated current errors and cleaned up problems in new issue: https://github.com/PrismarineJS/mineflayer/issues/598
