### ISSUE TITLE
Bot not showing messages that are sent it chat

### ISSUE THREAD

**Issue by CodingCreeperDude96** [PrismarineJS/mineflayer#602]
When you enter to a server like HiveMC, and try console.log messages that are sent in chat, it does nothing. Is this a bug in the package because it looks like it won't give me the raw message or any message sent by a non vanilla server

**Comment by plexigras** [comment]
what are you trying to run?

maybe try `bot.on('message', msg => console.log(msg.toString()))`

**Comment by CodingCreeperDude96** [comment]
Oh, I used the 'chat' event, thank you
