### ISSUE TITLE
Example doesnt work

### ISSUE THREAD

**Issue by Meldiron** [PrismarineJS/mineflayer#606]
I tried ecoh example, I added console log to on.chat..
This on.chat is not triggered at all.

Bot is conencted whole  time, I can use .chat to send message.
But when I try to listen to chat, nothing gets trigered when I type into chat form another acocunt.

**Comment by rom1504** [comment]
what server
it works for vanilla and the version specified in the readme

**Comment by Meldiron** [comment]
Yeah, its not vanilla, thats the problem.
Also, how does .look works?
I do
`bot.look(0,0)`
and it looks at yaw -180, pitch 0.

And I cant use
`bot.lookAt( bot.blockAt(bot.entity.position.offset(0, 0, 1)) );`
becouse it throws error:
```
C:\Users\meldiron\Desktop\mineflayer-master\lib\plugins\physics.js:348
    const delta = point.minus(bot.entity.position.offset(0, bot.entity.height, 0))
                        ^

TypeError: point.minus is not a function
    at Bot.bot.lookAt (C:\Users\meldiron\Desktop\mineflayer-master\lib\plugins\physics.js:348:25)
    at Timeout.setTimeout (C:\Users\meldiron\Desktop\mineflayer-master\examples\echo.js:33:14)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/mineflayer/issues/175#issuecomment-341977706
