### ISSUE TITLE
Walk toggle function?

### ISSUE THREAD

**Issue by Meldiron** [PrismarineJS/mineflayer#608]
Maybe im just blind, but how to make player walk? Line. hold SHIT to move slower while moving.

**Comment by plexigras** [comment]
start walking
`bot.setControlState('forward', true)`

stop walking
`bot.setControlState('forward', false)`

start running
`bot.setControlState('sprint', true)`

stop running
`bot.setControlState('sprint', false)`

https://prismarinejs.github.io/minecraft-data/?d=protocol#toServer_entity_action

start sneaking
```
bot._client.write('entity_action', {
  entityId: bot.entity.id,
  actionId: 0,
  jumpBoost: 0
})
```
stop sneaking
```
bot._client.write('entity_action', {
  entityId: bot.entity.id,
  actionId: 1,
  jumpBoost: 0
})
```
https://prismarinejs.github.io/minecraft-data/?d=protocol#toServer_entity_action

**Comment by rom1504** [comment]
_ should only be used for testing, if it's needed to do something like that then we should add a function mineflayer

**Comment by Meldiron** [comment]
Yeah, it would be great if there is something like:
bot.setControlState('sneaking', true).
I will try to add it and create pull request.

**Comment by rom1504** [comment]
now merged

**Comment by GGxABDUL** [comment]
Hey, when I run `bot.setControlState('forward', true)` . It say that `bot.setControlState` is not a Function. How to fix it?
