### ISSUE TITLE
non vanilla chat

### ISSUE THREAD

**Issue by monsterbear** [PrismarineJS/mineflayer#616]
Hello, Im really new at this And I was needing help for a non vanilla server For the bot to respond to my commands I'm using Rbot https://github.com/rom1504/rbot And Hoping to update it make improvements 

I'm On a multiplayer server And just Need the bot to respond to me on the server With chat plugins? 
https://github.com/PrismarineJS/mineflayer/tree/05337bce8724bb51511bd0ca11ce9f4782142ad5/lib/plugins/chat

Where would this go into Rbot ?

**Comment by rom1504** [comment]
see https://github.com/rom1504/rbot/issues/54#issuecomment-350367886

**Comment by monsterbear** [comment]
Where is the chat file at? I saw it earlier now can' find it.

**Comment by monsterbear** [comment]
Okay i got it in It loads fine And still doesn't respond..

**Comment by rom1504** [comment]
what about you read what I write ?

**Comment by monsterbear** [comment]
Did

**Comment by rom1504** [comment]
Ok so if you read what I wrote then what file did you try to load ?

**Comment by monsterbear** [comment]
You linked me to this https://github.com/PrismarineJS/mineflayer/issues?q=is%3Aissue+chat+is%3Aclosed

**Comment by SuperOP535** [comment]
chatAddPattern?

**Comment by rom1504** [comment]
Now supported
