### ISSUE TITLE
Cannot Connect To "noxiouspvp.com"

### ISSUE THREAD

**Issue by JustinKelleher** [PrismarineJS/mineflayer#618]
I can get my bot to work on all servers, except on "noxiouspvp.com" where I get the error listed below.

**Error**:
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Inflate.zlibOnError (zlib.js:153:15)

**Comment by rom1504** [comment]
duplicate of https://github.com/PrismarineJS/mineflayer/issues/431
