### ISSUE TITLE
Full Chat Text

### ISSUE THREAD

**Issue by BamItsPixel** [PrismarineJS/mineflayer#620]
Is there a way of getting the full text (as the player would see) from the "message" event?

Ik that we can get the raw JSON but it's a pain to parse.

Thank you.

**Comment by plexigras** [comment]
the "json" has a `.toString()`, `.toMotd()` and a `.toAnsi()` method you can use

**Comment by BamItsPixel** [comment]
Thank you- that’s perfect and this library is amazing. o/
