### ISSUE TITLE
Implement knockback

### ISSUE THREAD

**Issue by Syndesi** [PrismarineJS/mineflayer#621]
Hi,

is it normal that my bot doesn't move when he get damage? I tested zombies, a sword with knockback II and a simple punch with the bare hand, but he doesn't move by "himself".

**Comment by BamItsPixel** [comment]
In MC PvP that would count as an anti-knockback mod.

**Comment by rom1504** [comment]
Knockback is not implemented

**Comment by Wqrld** [comment]
I would really like this as a feature for the bot not to get banned on some servers

**Comment by SuperOP535** [comment]
Same

**Comment by theonlygusti** [comment]
Would be nice to have this feature as an option.

At the moment I'm up against a slightly different problem, I want to intercept the knock back package.

I'm assuming the server's plugins use Bukkit's `Player#setVelocity(Vector)` to tell the player how they should be knocked back.

I'd like to be able to add a listener for the packet generated by this to see the values the server plugins are telling my bot to set its velocity to.

**Comment by rom1504** [comment]
It's the entity_velocity packet. You can search for that in mineflayer code
to check how to listen for it.

**Comment by wvffle** [comment]
`entity_velocity` is handled inside mineflayers code but it kind of does not work with current physics.

When I hit the bot `entity.velocity` is updated to
```js
{ x: 0.33828125000000003, y: 0.4509375, z: 0.36796875 }
```
which basicly does nothing. 
I can see the bot move a bit up when i do
```js
bot.entity.velocity.y = 3
```
So there is no way that value which is less than 1 can cause any visible change.

I tried to scale it by 8 and it works only on y axis, so i bet it's due to current physics engine

**Comment by Vap0r1ze** [comment]
If anybody stumbles upon this with the same issue, this is what I use to implement knockback on 1.12.2
```js
bot._client.on('entity_velocity', v => {
  if (bot.entity.id !== v.entityId) return
  setTimeout(() => {
    bot.entity.velocity.x = v.velocityX / 256
    bot.entity.velocity.y = v.velocityY / 512 * 1.5
    bot.entity.velocity.z = v.velocityZ / 256
  }, 0)
})```

**Comment by rom1504** [comment]
does that work well ?
if so why not make a PR ?

**Comment by Vap0r1ze** [comment]
true

**Comment by wvffle** [comment]
@Vap0r1ze How do you know these are correct values? Any reference or just trial and error?

**Comment by Vap0r1ze** [comment]
Trial and error just played with numbers for 3 minutes

**Comment by Oreolicious** [comment]
I'm making a pvp bot in 1.16.5 and this is the code that I used to get perfect knockback handling.
It's a modified version of Vap0r1ze's code

```javascript
bot._client.on('entity_velocity', v => {
    if (bot.entity.id !== v.entityId) return
    
    bot.entity.velocity.x += v.velocityX
    bot.entity.velocity.y += v.velocityY
    bot.entity.velocity.z += v.velocityZ
})
```
