### ISSUE TITLE
Reconnect bot when it's kicked/disconnected

### ISSUE THREAD

**Issue by Roflicide** [PrismarineJS/mineflayer#623]
Is it possible to reconnect the bot when it's kicked/ disconnected? How would I go about doing this?

**Comment by johnpyp** [comment]
You can listen for "end" with:
```
bot.on('end', function() {
	//Reconnect by recalling startup function
})

**Comment by Roflicide** [comment]
I tried that; my code is as follows: 

````
const fs = require('fs')
const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node chatAddPattern.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'chatAddPattern',
  password: process.argv[5],
  version: "1.10.2",
  verbose: true
})

bot.on('spawn', () => {
  bot.end()
})

bot.on('end', (reason) => {
  console.log("Bot ended")
  const bot = mineflayer.createBot({
    host: process.argv[2],
    port: parseInt(process.argv[3]),
    username: process.argv[4] ? process.argv[4] : 'chatAddPattern',
    password: process.argv[5],
    version: "1.10.2",
    verbose: true
  })
})
````

However, after `bot.end()` the bot simply stops; it doesn't restart.

**Comment by johnpyp** [comment]
Not sure exactly. Its possible bot.end() doesn't trigger the 'end' because it is ending the bot, not just the connection. I believe there is a bot.disconnect() that you could try.

**Comment by rom1504** [comment]
you could do something like https://github.com/PrismarineJS/mineflayer/issues/164#issuecomment-29557539
or just restart the node process

**Comment by Roflicide** [comment]
Hi,

Thank you all for the responses. I followed #164, and it worked like a charm. Now, however, I want it to attempt to reconnect every 10 seconds, even when the server has shut down. I'm using the [node.js wait-until plugin](https://www.npmjs.com/package/wait-until), which provides a way to check for a condition every so often, then run a callback after the condition is met or the allotted time expires. Here's what I tried to do: 

````
var mineflayer = require('mineflayer');
var waitUntil = require('wait-until');

var options = {
    host: "host",
    port: port,
    username: "username",
    version: "1.10.2",
    verbose: "true",
    password: "password",
};

var bot = mineflayer.createBot(options);
bindEvents(bot);

function bindEvents(bot) {
    bot.on('login', function() {
        console.log("Bot has logged in");
    });

    bot.on('spawn', function() {
        console.log("Bot has spawned");
    });

    bot.on('kicked', function(reason) {
        console.log("Kicked for ", reason);
    });

    bot.on('end', function(reason) {
        // Wait 10 seconds between tries, and try 9999 times
        waitUntil(10000, 9999, function condition() {
          try {
            console.log("Bot ended, attempting to reconnect...");
                bot = mineflayer.createBot(options);
                bindEvents(bot);
                return true;
           } catch (error) {
                console.log("Error: " + error);
                return false;
            }
            // Callback function that is only executed when condition is true or time allotted has elapsed
        }, function done(result) {
            console.log("Connection attempt result was: " + result);
        });
   });
}
````
If I kick the bot from the server it relogs fine if the server is still online. But if I shut the server down, and the bot attempts to relog, it gives me an 
````
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:25565
````
I'm confused - shouldn't my `catch` statement above be handling the error though? Is there something I'm missing here?

**Comment by rom1504** [comment]
yes, you need to listen of the error event.
bot.on('error',err => doSomething())

**Comment by Roflicide** [comment]
Hi, 

Thanks for the reply. I added the `bot.on('error',err => doSomething())` listener, and it works...but only for 2 times. For some reason, after 2 times the `bot.on(end)` listener is not called. Here's my updated code:

````
var mineflayer = require('mineflayer');

var options = {
    host: "host",
    port: port,
    username: "email",
    version: "1.10.2",
    verbose: "true",
    password: "password",
};

var bot = mineflayer.createBot(options);
bindEvents(bot);

function bindEvents(bot) {

    bot.on('error', function(err) {
        console.log("Bot has encountered an error");
    });

    bot.on('end', function() {
        console.log("Bot has ended");
        setTimeout(relog, 10000);  
    });

    function relog() {
        console.log("Attempting to reconnect...");
        bot = mineflayer.createBot(options);
        bindEvents(bot);
    }
}
````

And here's the output of the code:

````
Bot has encountered an error
Bot has ended
Attempting to reconnect...
Bot has encountered an error
Bot has ended
Attempting to reconnect...
Bot has encountered an error
````
Notice that it doesn't trigger the "bot has ended" message after two times. Any idea why it's doing this?

**Comment by rom1504** [comment]
> It seems that if the error is an "Invalid credentials" error, then the "end" event is not called.

That sounds like a bug. If you figure out where that happens in mineflayer or node-minecraft-protocol, feel free to submit a PR to fix it, that would be appreciated.

**Comment by Roflicide** [comment]
Hi @rom1504, I figured it out!

If you attempt to reconnect using the bot with less than 30 seconds between connections, an "invalid credentials" connection will be thrown. I think this is some sort of defense mechanism Mojang has put into place to prevent people from constantly disconnecting/reconnecting. In mineflayer (or the protocol), this has an error code of "undefined"--perhaps this is why the `end` event is not being triggered?

So in sum: if you enter incorrect credentials, or if you attempt to reconnect within 30 seconds of your last connection, then mineflayer will throw an error code of "undefined", and the "bot.end" event will not be triggered. 

If I wait 30 seconds or more between connections, than the error is not thrown, and the "end" event is called successfully. So here's my workaround to make the bot auto-reconnect:

```
var mineflayer = require('mineflayer');

var options = {
    host: "host",
    port: port,
    username: "email",
    version: "1.10.2",
    verbose: "true",
    password: "password",
};

var bot = mineflayer.createBot(options);
bindEvents(bot);

function bindEvents(bot) {

    bot.on('error', function(err) {
        console.log('Error attempting to reconnect: ' + err.errno + '.');
        if (err.code == undefined) {
            console.log('Invalid credentials OR bot needs to wait because it relogged too quickly.');
            console.log('Will retry to connect in 30 seconds. ');
            setTimeout(relog, 30000);
        }
    });

    bot.on('end', function() {
        console.log("Bot has ended");
        // If set less than 30s you will get an invalid credentials error, which we handle above.
        setTimeout(relog, 30000);  
    });
}

function relog() {
    console.log("Attempting to reconnect...");
    bot = mineflayer.createBot(options);
    bindEvents(bot);
}
````
And now it works like a charm :) 

If I get some time, I'll try and go digging around to see if we can assign some sort of error code (so it's not undefined) when the credentials are invalid (or the person relogs within 30seconds). Then, perhaps that'll make the `bot.end` event trigger.
