### ISSUE TITLE
UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: invalid control: sneak

### ISSUE THREAD

**Issue by BamItsPixel** [PrismarineJS/mineflayer#626]
> UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: invalid control: sneak

I am trying to use bot.setControlState('sneak', true).

It works with "jump" in the exact same line- I have no idea as to why it won't sneak.

I've also tried it immediately after the bow spawns, still the same error- it's very stragne.

**Comment by rom1504** [comment]
Ah the sneak control is merged but not released. I'll release a new version
soon.
On the mean time you can use master.

**Comment by BamItsPixel** [comment]
Ahh alright, it works. Thank you!
