### ISSUE TITLE
Multibot AI

### ISSUE THREAD

**Issue by nextifyy** [PrismarineJS/mineflayer#627]
Hey, its possible to spawn some bots(5?) and controll all of them?

For example: I want to spawn 5 bots and command some of them to dig, walk, fight mobs?

**Comment by roblabla** [comment]
Yes, just create multiple Mineflayer objects.

**Comment by rom1504** [comment]
There are 2 ways :
* Multiple mineflayer object (see multiple.js)
* Multiple node : will be faster because it then uses several process.

There are a few issues asking about that already, try looking for them.
