### ISSUE TITLE
Drop every single item in bot inventory

### ISSUE THREAD

**Issue by SuperOP535** [PrismarineJS/mineflayer#632]
This is a question and not an issue, I want to know how I can use bot.toss ( or any other function ) to drop every single item in bot inventory. Dropping all at once might get counted as hacks in some servers so a way to drop all items in specified inventory/hotbar slot can be used with some interval

**Comment by rom1504** [comment]
go through them all and wait a little bit before each ?

**Comment by SuperOP535** [comment]
Yeah but how do I get a slot & drop items on that one?

**Comment by johnpyp** [comment]
You can equip each one and drop each equipped item.

**Comment by plexigras** [comment]
its `bot.inventory.items()` i think

**Comment by plexigras** [comment]
its `bot.inventory.items()` i think

**Comment by plexigras** [comment]
its `bot.inventory.items()` i think

**Comment by algiuxass** [comment]
My solution how to drop one item. You may loop trough all items and check if there's an item in that slot (bot.inventory.slots[slot]!=null maybe?)
I find prismarine-windows and other stuff VERY confusing, bad documentation.
```
bot.clickWindow(slot, 0, 0, () => {
   bot.clickWindow(-999, 0, 0, () => {
        callback(true);
    })
})
```
