### ISSUE TITLE
Fix async stuff after loading bot

### ISSUE THREAD

**Issue by MeWoody** [PrismarineJS/mineflayer#635]
When I try to use the chatAddPattern function, as shown below, it returns that chatAddPattern is not a function. Any idea why?

`mf.chatAddPattern(/^\[ ?([^ ]*) -> me ?] (.*)$/, 'whisper', 'general whisper');`

mf is, of course, defined as the bot. I would like to implement this in a discord bot and I can't have bots with the same name.

it gives this error:

https://i.imgur.com/EpToySi.png

**Comment by rom1504** [comment]
Can you post your code ? (Or at least the related part, including when you
define "mf")

**Comment by MeWoody** [comment]
The part where I define it is correct, all of the other functions work (mf.on(), mf.chat()). I changed it back to bot but still. I got something else to work though, I get the raw message from the message listener and then pull it through a regex.

**Comment by plexigras** [comment]
> I get the raw message from the message listener and then pull it through a regex.

thats exactly what chatAddPattern does

so you might want to read the source of the chat plugin to see what you are doing different

**Comment by MeWoody** [comment]
The whole problem is that chatAddPattern wasn't recognized as a function, so I found a workaround. I still don't know why it doesn't work though, it's alot easier than adjusting the regex for each server.

**Comment by rom1504** [comment]
If it's not defined it probably means you are somehow not using the last
mineflayer.

**Comment by MeWoody** [comment]
I'll try again in a second, gotta find a server to test it on though. Most non vanilla servers result in it crashing with some partial packet error.

**Comment by plexigras** [comment]
maybe reinstall or update mineflayer

**Comment by rom1504** [comment]
Please report non vanilla crashes in
https://github.com/PrismarineJS/node-minecraft-protocol/issues/532

**Comment by adamlowerj** [comment]
I'm having the same issue. 

> TypeError: bot.chatAddPattern is not a function
    at Object.<anonymous> (D:\dev\minecraft\bot\index.js:37:5)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

I am attempting to run an unmodified copy of chatAddPattern.js provided in the examples on a fresh vanilla 1.12.2 server on version 2.6.1 of mineflayer.

**Comment by plexigras** [comment]
i think i figured it out, i thik its because the plugin gets loaded asynchronously

**Comment by rom1504** [comment]
What gets loaded asynchronously ?

**Comment by plexigras** [comment]
the chat plugin

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/chat.js ?

I can't see any async there. What is async ?

**Comment by plexigras** [comment]
https://github.com/PrismarineJS/mineflayer/blob/dc378923c19cf3b18dbfa7c5ac5cba4d723323ae/index.js#L56-L67

**Comment by rom1504** [comment]
I get it.

You can't call bot stuff before the correct event is emitted. see https://github.com/PrismarineJS/mineflayer/pull/569

**Comment by rom1504** [comment]
This is documented
