### ISSUE TITLE
Boss bar

### ISSUE THREAD

**Issue by ArtFect** [PrismarineJS/mineflayer#639]
Am I blind or is there no way to get custom boss bar text? 
I tried to find wither or dragon in bot.entities but they aren't there

**Comment by plexigras** [comment]
i dont think there is a mineflayer plugin that handles this

but you could write one or you could just do `bot._client.on('boss_bar", ... )`

http://prismarinejs.github.io/minecraft-data/?d=protocol#toClient_boss_bar

also then you might want to parse the `title` field using `new ChatMessage(title)`

**Comment by rom1504** [comment]
We should probably handle that mineflayer. This is a new feature so it's not handled but it should be, if you have some code that implement it, please share it.
Otherwise it should still be implemented, reopening.

**Comment by rom1504** [comment]
If someone is interested, please finish https://github.com/PrismarineJS/mineflayer/pull/659
I'm not merging a half-done feature like that, closing the pr since it's dead.

**Comment by rom1504** [comment]
now done, thanks @wvffle
