### ISSUE TITLE
Jump, flyTo and clearControlState

### ISSUE THREAD

**Issue by MeWoody** [PrismarineJS/mineflayer#640]
Neither of the following functions seem to work:
```javascript
bot.setControlState("jump", false); //Does not stop it from going up in fly
bot.creative.flyTo() //Gives an error that destination.minus() is not a function
bot.clearControlState() //Does not clear the control state at all, it keeps flying up
```

This is the code I use:

```javascript
let des = [bot.entity.position.x, bot.entity.position.y + 40, bot.entity.position.z];
bot.creative.flyTo(des);

//A different way I tried doing it, as flyTo() wasn't working

bot.creative.startFlying();
bot.setControlState("jump", true);
setTimeout(function() {
   bot.setControlState("jump", false)
   bot.clearControlState();
}, 5000)
```

In the first situation, the bot doesn't fly at all and crashes, cause destination.minus() is not a function. In the second situation the bot starts flying, goes up but never stops going up. Any idea why?

**Comment by rom1504** [comment]
What are you trying to do ?

**Comment by plexigras** [comment]
#### bot.creative.flyTo(destination, [cb])

Calls startFlying() and moves at a constant speed through 3d space in a straight line to the destination. destination is a **Vec3**, and often the x and z coordinates will end with .5. This operation will not work if there is an obstacle in the way, so it is advised to fly very short distances at a time.

When the bot arrives at the destination, cb is called.

This method does not attempt any path finding. It is expected that a path finding implementation will use this method to move < 2 blocks at a time.

To resume normal physics, call stopFlying().

https://www.npmjs.com/package/vec3

https://github.com/PrismarineJS/mineflayer/blob/master/doc/api.md#botcreativeflytodestination-cb

**Comment by MeWoody** [comment]
I'm trying to fly up, like 40 blocks, just at the coordinates it is. So enable fly, fly around 40 blocks up (spacebar to go up), and then stop.

**Comment by plexigras** [comment]
maybe try `bot.creative.flyTo(bot.entity.position.offset(0, 0, 40))`

**Comment by MeWoody** [comment]
Yeah that works. I guess I could use that, weird how it wouldn't stop flying before though. Thanks @plexigras
