### ISSUE TITLE
client logs out

### ISSUE THREAD

**Issue by syrianrue** [PrismarineJS/mineflayer#644]
on 1.12.2 spigot servers, i log in fine but the bot will log out after about 15 seconds with no errors. does this happen to anyone else?

var mineflayer = require('mineflayer');
//var vec3 = mineflayer.vec3;

var bot = mineflayer.createBot({
    username: process.argv[4] ? process.argv[4] : "username",
    verbose: true,
    port:parseInt(process.argv[3]),
    host:process.argv[2],
    password:process.argv[5]
});

**Comment by SMemsky** [comment]
Try setting `checkTimeoutInterval` to a higher value like 30 seconds (default is 10, which is even smaller than vanilla client accepts (20s)).
This fixed the problem for me:
```
const bot = mineflayer.createBot({
	host: process.argv[2],
	port: parseInt(process.argv[3]),
	username: process.argv[4],
	verbose: true,
	version: "1.12.2",
	checkTimeoutInterval: 30*1000 // 30 seconds
})
```

**Comment by syrianrue** [comment]
wow that seems to have worked great. thank you so much : )
