### ISSUE TITLE
Moving doesn't work

### ISSUE THREAD

**Issue by MagnificentPako** [PrismarineJS/mineflayer#654]
I tried doing things like `bot.setControlState("jump", true)`, `bot.look(50, 100)` and `bot.navigate.to(bot.entity.position.offset(5,0,0))` but none made it move. Any idea what I'm missing?

Just tested it and picking up items doesn't seem to work either (unless you have to a call a function for that)

**Comment by rom1504** [comment]
what minecraft version ? are you connecting to a vanilla server ? if not try another server, yours might use something that is not supported by mineflayer atm (see https://github.com/PrismarineJS/node-minecraft-protocol/issues/532)

**Comment by MagnificentPako** [comment]
The server is on 1.12. It isn't vanilla. I'll try it on a different server then.

I just found out that `bot.players` isn't populated either, btw.

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/node-minecraft-protocol/issues/532
