### ISSUE TITLE
inventory management

### ISSUE THREAD

**Issue by andrewrk** [PrismarineJS/mineflayer#66]
- [x] Ability to read your inventory
- [x] Ability to change what you are equipping
- [x] Ability to throw stack on the ground
- [x] Ability to throw N number of Z type items on the ground
- [ ] Ensure inventory update event is always emitted when inventory changes
- [ ] Ensure equipped item event is always emitted when equipped item changes
- [x] Ability to craft, both with and without a workbench
- [x] Ability to list the contents of a chest
- [x] Ability to store things in chests
- [x] Ability to list the contents of a dispenser
- [x] Ability to store things in a dispenser
- [x] Ability to get furnace status
- [x] Ability to list the contents of a furnace
- [x] Ability to store things in a furnace
- [x] Support enchanting tables
- [ ] Support brewing stands
- [ ] Support anvils
- [ ] Carefully expose the lower level window click stuff?

**Comment by SinanAkkoyun** [comment]
How can one craft with crafting table? Is there an example?

**Comment by DrMoraschi** [comment]
> How can one craft with crafting table? Is there an example?

bot.craft(recipe, count, craftingTable, [callback])

Please take a look at the API before asking questios

**Comment by SinanAkkoyun** [comment]
> > How can one craft with crafting table? Is there an example?
> 
> bot.craft(recipe, count, craftingTable, [callback])
> 
> Take a look at examples/inventory.js
> 
> And also at the API

Hi, I found it and did that, but the bot just can not craft a pickaxe for example. but a furnace works... I suppose because of multiple materials? Does it work for you at 1.16.4?

**Comment by DrMoraschi** [comment]
> > How can one craft with crafting table? Is there an example?
> 
> bot.craft(recipe, count, craftingTable, [callback])
> 
> Please take a look at the API before asking questios

    I dont usually test in 1.16.4 I think mineflayer doesnt fully support 1.16.4

**Comment by SinanAkkoyun** [comment]
> > Please take a look at the API before asking questios

Yeah, I am sorry, will not happen again

I will try it on other versions, thanks
