### ISSUE TITLE
Getting session data

### ISSUE THREAD

**Issue by Vxrize** [PrismarineJS/mineflayer#673]
Hey,

is there a way to get the session data once the bot logs in? I want to save it, so I can use it to log in without credentials and to avoid temporary bans from logging in to frequently.

Thanks

**Comment by plexigras** [comment]
’bot._client.once('session', console.log)’

**Comment by Vxrize** [comment]
That's what I tried, but it does not return any data at all. I dug through your code base a bit, but could not find the part where the session tokens get emitted

**Comment by Vxrize** [comment]
Found the solution after digging through the code for a little bit.

Once the client authenticates it emits the "session"-event. But this event doesn't pass any information.
The "session" object of _client gets updated. So you would have to use the following code to get the session data:

```
bot._client.once('session', () => {
    console.log(bot._client.session);
});
```
