### ISSUE TITLE
"Looking at" function/method

### ISSUE THREAD

**Issue by Vxrize** [PrismarineJS/mineflayer#674]
Is there a way to get the point or maybe even block the bot is currently looking at?

I am trying to make the bot automatically break the blocks generated at a cobblestone generator.
Afaik you can only break blocks when you pass a block instance, so I'm looking for a way to get the block the bot looks at.

Thanks

**Comment by plexigras** [comment]
outdated but still a good starting point i supose

https://github.com/PrismarineJS/mineflayer/blob/25b89c461aa3544e4d9acad8d7e131851340c6b3/mineflayer-script/lib/ray_tracer.js

**Comment by rom1504** [comment]
why do you need to know what the bot is looking at ?
You need to make it look there, so you already know what is there.

**Comment by Vxrize** [comment]
> why do you need to know what the bot is looking at ?
You need to make it look there, so you already know what is there.

The bot copies the view angle of myself, that way I can align him perfectly at the cobblestone generator.

**Comment by rom1504** [comment]
You can do what plexigras said, but tbh I think a better way would be to find the cobblestone generator using blockAt and then you already know where it is.
There's no real need for a bot to be perfectly aligned or something like that.

**Comment by Vxrize** [comment]
What I'm going to do now is make a command where I pass the x, y, z values of the block and then call the same function again after the callback has been called to break block after block (after a short delay, to let the generator generate a new block).

I was searching for a simple solution, where I just make the bot destroy the block which he is looking at, but apparently it isn't that easy. :) 

#closed
