### ISSUE TITLE
Sign text is undefined (1.12.2)

### ISSUE THREAD

**Issue by safazi** [PrismarineJS/mineflayer#675]
```
Block {
  type: 68,
  metadata: 2,
  light: 0,
  skyLight: 0,
  biome:
   Biome {
     id: 0,
     color: 112,
     name: 'Ocean',
     height: undefined,
     rainfall: 0.5,
     temperature: 0.5 },
  position: Vec3 { x: -153, y: 64, z: 156 },
  name: 'wall_sign',
  hardness: 1,
  displayName: 'Wall Sign',
  boundingBox: 'empty',
  diggable: true,
  material: 'wood',
  harvestTools: undefined,
  drops: [ { drop: 323 } ],
  signText: undefined,
  painting: undefined }
```

Block found with bot.findBlock, and I am not changing the block in any way.

EDIT: this is on bukkit-Spigot.

**Comment by safazi** [comment]
Also, the sign is not blank, before anyone asks :+1:

**Comment by plexigras** [comment]
Good find, we might want to have a look at updating the signText property on update_sign events.

http://wiki.vg/Protocol#Update_Sign
http://minecraft-data.prismarine.js.org/?d=protocol#toServer_update_sign

**Comment by plexigras** [comment]
it might be better to use something like [`updateBlock`](https://github.com/PrismarineJS/mineflayer/blob/7284dd436aac8c94d639af038a3a3f1efdf18473/lib/plugins/blocks.js#L146) over [`emitBlockUpdate`](https://github.com/PrismarineJS/mineflayer/blob/7284dd436aac8c94d639af038a3a3f1efdf18473/lib/plugins/blocks.js#L275) directly.

**Comment by wvffle** [comment]
Any works on this?

**Comment by rom1504** [comment]
No, you can work on it ;)

**Comment by wvffle** [comment]
After some testing I can get sign text on demand on paper 1.12.2

```js
const getSignText = async location => new Promise(resolve => {
  const parse = text => {
    const ChatMessage = require('mineflayer/lib/chat_message')(bot.version)
    return new ChatMessage(JSON.parse(text))
  }

  bot._client.once('tile_entity_data', data => {
    const { Text1, Text2, Text3, Text4 } = data.nbtData.value
    const text = [ Text1, Text2, Text3, Text4 ].map(cm => parse(cm.value).toString()).join('\n')
    resolve(text)
  })

  bot._client.write('update_sign', { location, text1: '', text2: '', text3: '', text4: '' })
})
```

**Comment by rom1504** [comment]
ok you could add it there https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/blocks.js#L261
does it also work in older versions ?

**Comment by wvffle** [comment]
The downside of this is that it generates errors in the server console:
![image](https://user-images.githubusercontent.com/13330620/56497307-4514b800-64fd-11e9-850a-4cb2e63dc96a.png) 
So it's not an ideal solution.

I have to get `tile_entity_data` from the server but I haven't found any other way of doing this. I'll check into this later that day.

**Comment by rom1504** [comment]
I bet the data you want is in the block entities in map_chunk packet

**Comment by wvffle** [comment]
It should be pointed out that since 1.12 and 6921132 sign text is accessible through `blockEntity`

```js
const sign = bot.blockAt(position)
const { Text1, Text2, Text3, Text4 } = sign.blockEntity
if (Text1 === bot.username) {
  bot.chat('That\'s my sign!')
}
```

**Comment by safazi** [comment]
Awesome - thanks for all the help y'all.
