### ISSUE TITLE
Login/register in a server

### ISSUE THREAD

**Issue by BannerGames** [PrismarineJS/mineflayer#676]
Hello. I'm trying to make the bot when joining the server write /register pass123 pass123.
I'm trying to use bot.chat(), but it doesn't works.
I already tried Mineflayer-auto-auth but when I run the code gaves an error.

**Comment by roblabla** [comment]
Please, when you report that something doesn't work, explain what happens. Did you get kicked ? Did it disconnect ? Did the message not get sent? "It doesn't work" should be a banned sentence. If code gives an error, tell us what that error is. Otherwise, we cannot help you :|.

**Comment by plexigras** [comment]
try `bot.loadPlugin(bot => require('mineflayer-auto-auth')(bot, 'pass123'))`

**Comment by BannerGames** [comment]
Hello. Now don't give the error but now after a time the bot leaves and I'm logging the reason. The reason is "§4Tempo limite de sessão excedido, você foi expulso do servidor, por favor, tente novamente!" (Limit session time exceeded, you has been kicked of the server, please, try again!)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/issue_template.md

**Comment by gustavomaltez** [comment]
I know this post is old, but i did a auth system reading chat messages. You can use:

`bot.on('message, msg => {
      if(msg.extra[0] == "Please register using /register <password>")
             bot.chat("/register YourPassword YourPassWord");
      else if(msg.extra[0] == "Please log in using /login <password>")
              bot.chat("/login YourPassword");
})`

You can define variables to save login and  register messages and your password:

it wold look something like: 

`const infos = {
  password: 'awesomepassword',
  registerMsg: 'Please register using /register <password>',
  loginMsg: 'Please log in using /login <password>',
}

bot.on('message', msg => {

  const msgArr = msg.extra;

  //Return if msg don't have extra property
  if(!msgArr) return

  //Authenticate player
  if(msgArr[0].text == infos.registerMsg)
    bot.chat(`/register ${infos.password} ${infos.password}`);
  else if(msgArr[0].text == infos.loginMsg)
    bot.chat(`/login ${infos.password}`);
})`

**Comment by gustavomaltez** [comment]
I know this post is old, but i did a auth system reading chat messages. You can use:

bot.on('message, msg => {
      if(msg.extra[0] == "Please register using /register <password>")
             bot.chat("/register YourPassword YourPassWord");
      else if(msg.extra[0] == "Please log in using /login <password>")
              bot.chat("/login YourPassword");
})

You can define variables to save login and  register messages and your password:

it wold look something like: 

const infos = {
  password: 'awesomepassword',
  registerMsg: 'Please register using /register <password>',
  loginMsg: 'Please log in using /login <password>',
}

bot.on('message', msg => {

  const msgArr = msg.extra;

  //Return if msg don't have extra property
  if(!msgArr) return

  //Authenticate player
  if(msgArr[0].text == infos.registerMsg)
    bot.chat(`/register ${infos.password} ${infos.password}`);
  else if(msgArr[0].text == infos.loginMsg)
    bot.chat(`/login ${infos.password}`);
})

**Comment by Karang** [comment]
Why not simply use https://github.com/G07cha/MineflayerAutoAuth ?
