### ISSUE TITLE
Is there any way of getting the contents of a book?

### ISSUE THREAD

**Issue by unlimitedcoder2** [PrismarineJS/mineflayer#678]

**Comment by plexigras** [comment]
if you mean blocks that have an inventory you can have a look at the chest example.

https://github.com/PrismarineJS/mineflayer/blob/master/examples/chest.js

**Comment by unlimitedcoder2** [comment]
![image](https://user-images.githubusercontent.com/16884313/41731980-bbfa2c32-7577-11e8-82fa-26c5f2eed902.png) That is what I want to get. Is this possible?

**Comment by rom1504** [comment]
there's a book example https://github.com/PrismarineJS/mineflayer/blob/master/examples/book.js
