### ISSUE TITLE
You are sending illegal packets

### ISSUE THREAD

**Issue by xnulliver** [PrismarineJS/mineflayer#680]
Every time the bot enters the server, even if I use the example bot, it is kicked off the server with the following reason: "You are sending illegal packets".

Node-Version: v9.11.1
Mineflayer Version: 2.7.2
Server Version: Spigot 1.8.8
Minecraft Version of the Bot: 1.8.8

**Comment by rom1504** [comment]
Can you try to enable debug mode and send the packets before the crash ?

**Comment by SuperOP535** [comment]
maybe you should tell him/her how to do that (I think it is env var DEBUG=mineflayer but not sure)

**Comment by rom1504** [comment]
It's in the readme there
https://github.com/PrismarineJS/node-minecraft-protocol

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/issue_template.md
