### ISSUE TITLE
Simple issue

### ISSUE THREAD

**Issue by KenWa51** [PrismarineJS/mineflayer#681]
`var bot1 = mineflayer.createBot({
  username: "snip", // email and password are required only for
  password: "snip",          // online-mode=true servers
});`

How do I make a bot join a server after i have created it?

**Comment by plexigras** [comment]
the bot joins automatically the server you specified in the `createBot` method

take a look at the readme to see a very basic exaple

**Comment by KenWa51** [comment]
Ok, so i noticed when I run create bot and there is an error that stops the whole script, is there a way i can catch that error and instead print something to console

**Comment by KenWa51** [comment]
`{Trig Team} [text] 𝕭𝖑𝖔𝖔𝖉 (112577205984301056): !join snip 25565 1
C:\Users\kenwa\Desktop\Trig - Discord Bot\index.js:33
        var bot1 = mineflayer.createBot({
                              ^

ReferenceError: number is not defined
    at Client.client.on.msg (C:\Users\kenwa\Desktop\Trig - Discord Bot\index.js:33:31)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (C:\Users\kenwa\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\kenwa\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\kenwa\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\kenwa\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\kenwa\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)

C:\Users\snip\Desktop\Trig - Discord Bot>pause`

**Comment by KenWa51** [comment]
I figured out it had something to due with the numbers.

**Comment by KenWa51** [comment]
I still dont know how to catch errors;       throw er; // Unhandled 'error' event
      ^

Error: Invalid credentials. Invalid username or password.

**Comment by plexigras** [comment]
either your credentials are wrong or the mojangs auth server is timing you out

**Comment by KenWa51** [comment]
C:\Users\kenwa\Desktop\Trig - Discord Bot\index.js:44
          bot1.chat(`this is a test message.`)
               ^

TypeError: Cannot read property 'chat' of undefined

**Comment by rom1504** [comment]
This is an error in your code. Without your code we can't help you.

However you can probably solve it yourself by looking at the examples.

**Comment by KenWa51** [comment]
![image](https://user-images.githubusercontent.com/28264073/41941699-6469c880-7962-11e8-9a47-a9cd62d26f42.png)

**Comment by rom1504** [comment]
You define bot1 and use it in 2 different cases, that's not going to work.
You can put your code on GitHub or gist, it's better than sending images of
it.

**Comment by KenWa51** [comment]
const mineflayer = require('mineflayer')
const bot = mineflayer.createBot({
  host: "snip", // optional
  port: 25565,       // optional
  username: "snip", // email and password are required only for
  password: "snip",          // online-mode=true servers
  verbose: true
})

bot.on('message', (message) => {
  console.log(message.toAnsi())
})
Error: legit nothing

PS C:\Users\snip\Desktop\cosmic bot> node index.js
PS C:\Users\snip\Desktop\cosmic bot>

**Comment by rom1504** [comment]
What server is this ? (Version ? Vanilla or spigot or something else ?)

**Comment by KenWa51** [comment]
Spigot 1.8-1.12

**Comment by KenWa51** [comment]
hello?

**Comment by rom1504** [comment]
It works for these version of minecraft. Do you have node 8 ?
Can you try any of the examples on your PC on a vanilla server to make sure you are correctly set up ?

**Comment by KenWa51** [comment]
Node v8.9.4
None of the examples work it does the same thing

**Comment by rom1504** [comment]
Can you try on a vanilla server ?

**Comment by KenWa51** [comment]
It did the same thing

**Comment by rom1504** [comment]
Ok can you try to run this script and report the result :
```
console.log("test")
```

**Comment by KenWa51** [comment]
C:\Users\snip\Desktop\cosmic bot>node index.js
test

C:\Users\snip\Desktop\cosmic bot>pause
Press any key to continue . . .

**Comment by rom1504** [comment]
And when you run any mineflayer example you get no output and then it exit ?
How did you install it ?
Any error during installation ?

Can you try running in debug mode to see the packets (see node-minecraft-protocol readme to enable this) ?

**Comment by rom1504** [comment]
I asked multiple questions, I need all the answers
