### ISSUE TITLE
Does bot.craft() work?

### ISSUE THREAD

**Issue by F1nnF41ler** [PrismarineJS/mineflayer#682]
## Just like the title says, does the bot.craft() work?

I've been testing it for the last half an hour, and it seems that I'm not getting it to work.
And after about an hour of trying to figure the reason for why it doesn't work, I've ended up in the conclusion that bot.craft() doesn't work. 

So, basically, I'm asking if bot.craft() works, or whether I'm just too tired and/or stupid.

**Comment by plexigras** [comment]
the unit test says it does

what have you tried?

have you tried [examples/inventory.js](https://github.com/PrismarineJS/mineflayer/blob/master/examples/inventory.js) and said something like `craft 64 stick` in chat?

**Comment by F1nnF41ler** [comment]
Apparently I had some small mistake in my code... now it's working.
