### ISSUE TITLE
Running any example after installation

### ISSUE THREAD

**Issue by Leftier** [PrismarineJS/mineflayer#683]
I'm using windows 10 with node 8.11.3, npm 6.1.0 and minecraft 1.12.2
Just finished installing mineflayer@2.7.3 and tried to execute node echo.js, I tried vanilla an non-vanilla servers, servers with specific ports or default (25565) but I always get this error and the "Chunk size" with different values depending on the server. 

So I tried with another file, jumper.js but still the same error. Also tried the following code to see If I could get a different message 
```
bot.on('uncaughtException', function(err) {
  console.log(err)
})

```
Error: 
```
{ Error: querySrv ENOTFOUND _minecraft._tcp.play.wildercraft.net
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_minecraft._tcp.play.wildercraft.net' }
{ Error: querySrv ENOTFOUND _minecraft._tcp.play.wildercraft.net
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_minecraft._tcp.play.wildercraft.net' }
Chunk size is 10 but only 2 was read ; partial packet : {"name":"combat_event","params":{"event":0}}; buffer :2c003d4ccccd3dcccccd
```

**Comment by Leftier** [comment]
I added this line as suggested in issue#123

So I tried again with jumper.js and got the same error but not the chunk size one:

```
{ Error: querySrv ENOTFOUND _minecraft._tcp.vnlla.net
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_minecraft._tcp.vnlla.net' }
{ Error: querySrv ENOTFOUND _minecraft._tcp.vnlla.net
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_minecraft._tcp.vnlla.net' }

```

So I could execute a command in chat but after doing so the following error occurs:

```
C:\Users\-USER-\Desktop\test\node_modules\minecraft-protocol\src\transforms\framing.js:66
          } else { throw e }
                   ^
```

**Comment by rom1504** [comment]
What minecraft version ? What kind of server ?

**Comment by Leftier** [comment]
On the first post:

> I'm using windows 10 with node 8.11.3, npm 6.1.0 and minecraft 1.12.2
Just finished installing mineflayer@2.7.3 and tried to execute node echo.js, I tried vanilla an non-vanilla servers, servers with specific ports or default (25565) but I always get this error and the "Chunk size" with different values depending on the server.

**Comment by LewisTehMinerz** [comment]
I have a feeling that it's because the library disregards the fact that a server may not have a `_minecraft._tcp` SRV record.

Tried this myself with play.pvpwars.net and it doesn't work.

**Comment by LewisTehMinerz** [comment]
I found a workaround and it won't work on all servers, but if your server works with 1.8 then just set the version to 1.8.

**Comment by rom1504** [comment]
This problem is probably happening because of some specific plugins in your server.
What server is it ?

It's not possible to solve the problem for us without being able to reproduce it.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/issue_template.md

**Comment by unixfox** [comment]
I've the same error @Leftier.
I tried on the server: `us.stratus.network` which accept the minecraft versions from 1.7 to 1.13 (using the plugin ViaVersion).
