### ISSUE TITLE
Respawn Method?

### ISSUE THREAD

**Issue by ROMTypo** [PrismarineJS/mineflayer#685]
I can't seam to find a respawn method, could anyone help me?

**Comment by rom1504** [comment]
It respawn automatically, see respawn.js

**Comment by ROMTypo** [comment]
@rom1504 I can't seem to find it, can you link it? And what currently happens is that when it dies it disconnects and the process exits

**Comment by rom1504** [comment]
That means your server is probably doing something custom on dieing. Check
with debug mode (see node-minecraft-protocol readme)

The respawning logic is there
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/health.js
No respawn.js indeed

**Comment by rom1504** [comment]
No, that's something not supported in your server.
Open a new issue with your custom server name and the details of what you tried.
