### ISSUE TITLE
Issue with windowUpdate

### ISSUE THREAD

**Issue by mspaintmsi** [PrismarineJS/mineflayer#689]
I have a slight problem with this fragment of code:
```js
bot.inventory.on('windowUpdate', (slot, oldItem, newItem) => {
	switch(newItem.type){
		case 4:
			cobbleCount++;
			break;
		case 14:
			goldCount++;
			break;
		case 15:
			ironCount++;
			break;
		case 16:
			coalCount++;
			break;
		case 73:
			redstoneCount++;
			break;
		default:
			break;
	}
});
```

Executing the script gives me an error with this stacktrace:
```
bot.inventory.on('windowUpdate', (slot, oldItem, newItem) => {
              ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/home/mspaintmsi/konni.js:199:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
Where should I put this event for bot.inventory to be already defined?

**Comment by rom1504** [comment]
When the bot has been initialized, so for example you can do that on 'spawn' event.

**Comment by rom1504** [comment]
I think you want to use bot.inventory.items() instead of counting what is in the inventory yourself though.

**Comment by mspaintmsi** [comment]
Putting it in ```bot.on(spawn)``` solved the problem. Thanks :)

As for your suggestions - I need real-time data of how many of these blocks my bots have picked up, and I would use ```bot.inventory.count()``` if I could, but sadly they don't keep those items in their inventories for too long and it would use significantly more resources if I were to constantly refresh it .-.
