### ISSUE TITLE
Getting bot's coords

### ISSUE THREAD

**Issue by nagoL2015** [PrismarineJS/mineflayer#690]
As the title says, how would I get the bot's coords? I have tried bot.entity.position and finding a player outside out 5 blocks and getting their position. But none of that is working. I am just trying to move relative to the bot.

**Comment by rom1504** [comment]
`bot.entity.position` yes that's the one.
What error are you getting ?

**Comment by rom1504** [comment]
see the examples

**Comment by nagoL2015** [comment]
Cannot read property 'position' of undefined

Here is the line of code:

bot.navigate.to(bot.entity.position.offset(-5, 0, 0));

**Comment by rom1504** [comment]
You probably execute that too early. When do you run that ?

**Comment by nagoL2015** [comment]
In the spawn event.

**Comment by rom1504** [comment]
Use the login event

**Comment by Timespeed921** [comment]
i have a similar script and using it in the login event doesnt work
