### ISSUE TITLE
snow is treated as a full block

### ISSUE THREAD

**Issue by MrAlexEsisteGia** [PrismarineJS/mineflayer#692]
the bot floats on snow
https://i.imgur.com/ArProeQ.png
tip: treat the snow like a pressure plate

**Comment by rom1504** [comment]
See
https://github.com/PrismarineJS/mineflayer/issues/228

**Comment by generic-github-user** [comment]
I also noticed this . . . when walking, the bot gets stuck against single snow layers that the player or other entities would not even interact with.

**Comment by UMRnInside** [comment]
In [minecraft-data](https://github.com/PrismarineJS/minecraft-data), `snow_layer` is marked as "block":
[blocks.json#L2109](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.8/blocks.json#L2109) :
```
{
    "id": 78,
    "displayName": "Snow (layer)",
    "name": "snow_layer",
    "hardness": 0.2,
    "stackSize": 64,
    "diggable": true,
    "boundingBox": "block",
    "material": "dirt"
}
```

Changing `boundingBox` to `empty` makes the bot **stand on** (not floating on) snow_layer.

**Comment by Karang** [comment]
duplicate of https://github.com/PrismarineJS/mineflayer/issues/228 changing the bounding box to empty will not solve the issue (the bot will stand on the block bellow it)
