### ISSUE TITLE
Read error for params.set_slot.item.unknown.default.nbtData.type

### ISSUE THREAD

**Issue by thelex0** [PrismarineJS/mineflayer#694]
when bot starts https://hastebin.com/acivuqulis.js

**Comment by KenWa51** [comment]
code

**Comment by thelex337** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/examples/jumper.js (not edited)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/issue_template.md
