### ISSUE TITLE
fishing template

### ISSUE THREAD

**Issue by Liaraswd** [PrismarineJS/mineflayer#695]
can write a simple auto fishing for example? (:

**Comment by plexigras** [comment]
you could try
```js
bot.equip(bot.inventory.findInventoryItem(346), 'hand', bot.activateItem)
bot.once('soundEffectHeard', soundName =>
  if (soundName === 'random.splash')
    setTimeout(bot.activateItem, 500)
)
```

**Comment by Liaraswd** [comment]
@plexigras Um.. I try it but it don't work

**Comment by Liaraswd** [comment]
@plexigras It works great when using an item. I think we should find a new way when the fish eat the bait. XD

**Comment by rom1504** [comment]
duplicate of #619 
I'm ok with having this in mineflayer though, it seems like a quite common feature
