### ISSUE TITLE
global events

### ISSUE THREAD

**Issue by Wqrld** [PrismarineJS/mineflayer#696]
I have multiple boys with `const pigbot = mineflayer.createBot({`
and i want to be able to receive messages for all of them, would it possible to have like a bots.on(''message"), (message, bot) => {} instead of having to copypaste the code three times?

**Comment by rom1504** [comment]
You don't need to copy paste the code, you can use a loop or a function

**Comment by rom1504** [comment]
```js
function createMyBot(params)
{
 const bot = mineflayer.createBot(params);
 bot.on('message', something);
}

createMyBot(param1);
createMyBot(param2);
```

Feel free to create an array or anything else you need too.

**Comment by Wqrld** [comment]
I used a foreach loop with a function as you said, thanks for the awesome project ;P
