### ISSUE TITLE
Autofishing not work

### ISSUE THREAD

**Issue by Liaraswd** [PrismarineJS/mineflayer#697]
**This code for auto fishing,**
But it does not work. Please tell me how to fix it.

This is use for throw a bait `bot.equip(bot.inventory.findInventoryItem(346), 'hand', bot.activateItem)`

This is event for catch it
`bot.on('soundEffectHeard', function(soundName) {
    if (soundName === 'random.splash') {
        bot.chat("Success")
        setTimeout(bot.activateItem, 500)
    }
})`

**Comment by plexigras** [comment]
duplicate of https://github.com/PrismarineJS/mineflayer/issues/695
