### ISSUE TITLE
Data buffer error + Error on digging 'stone'

### ISSUE THREAD

**Issue by PitPanda1** [PrismarineJS/mineflayer#701]
* what you want to do (the objective in english)

Mining a block on a predefined position with blockUpdate(x, y, z)

* what you tried (the code)

```
bot.on('blockUpdate:(-1195, 49, 3992)', (oldBlock, newBlock) => {
	if (state == 'farming') {
		let target = bot.blockAt(newBlock.position);
		if (target && bot.canDigBlock(target)) {
			console.log('Mining', target.name);
			bot.dig(target);
		}
	}
});
```

* what happened

Data buffer error -> occures after a period of time always (maybe 1-2 minutes after starting?):
https://pastebin.com/KwDjLNPi 

Error: Digging aborted -> when a stone on the coordinates appears:
https://pastebin.com/hcetabHR

* what you expected to happen

That it mines the spot correctly. I have no Idea what I can do against this errors. :(

* what mineflayer version?

mineflayer@2.7.3
minecraft-protocol@1.6.0
minecraft-data@2.26.0
mineflayer-navigate@0.0.10

* what server version?

1.8

* which server? (spigot, paper, vanilla, any particular plugins ?)

spigot

* what's the error msg?

1. Error: Data buffer not correct size
2. Error: Digging aborted

* what script is used?

Just a very simple selfmade script to get to the spot and start mining a specific coordinate.
[cobblegenfarmer.zip](https://github.com/PrismarineJS/mineflayer/files/2275700/cobblegenfarmer.zip)

**Comment by rom1504** [comment]
stale
