### ISSUE TITLE
get the hover value of a chat message

### ISSUE THREAD

**Issue by Wqrld** [PrismarineJS/mineflayer#702]
it could just be that i am looking at the wrong thing but it it possible to get the hover message of a chat message? it does not seem to be in the chatmessage object.

**Comment by plexigras** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/lib/chat_message.js#L148-L175

**Comment by rom1504** [comment]
Maybe chat message is missing that info. You can find the whole json object
in the message event.
Feel free to add that to chat message if needed

**Comment by Wqrld** [comment]
got it to work, thanks!
(got my bot banned too lol) :)
