### ISSUE TITLE
Send a message to first ever join

### ISSUE THREAD

**Issue by Paralusion** [PrismarineJS/mineflayer#704]
I want to be able to send a message to people that have joined for the first time. Is there any way this is possible? I've looked through the documentation with no result.

**Comment by Gjum** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#playerjoined-player

then keep an external list of who you have already messaged

**Comment by Paralusion** [comment]
I don't think I completely understand?

**Comment by roblabla** [comment]
Store a list of player UUID in a JSON file or database or whatever. When someone joins (which you can detect with the playerjoined event), check if his uuid is already in the database, if not send a message and add it to the database.

**Comment by roblabla** [comment]
Something like https://github.com/PrismarineJS/mineflayer/blob/913cc2714fc2c43b7818e330700c131540026f1d/examples/chatterbox.js#L155 but keeping track of who you already talked to.

**Comment by Paralusion** [comment]
thank you, I found a way!
