### ISSUE TITLE
multiple.js timed out

### ISSUE THREAD

**Issue by ano95** [PrismarineJS/mineflayer#710]
Hello, I tried running example multiple.js against local paper server (no plugins, 1.12.2, git-Paper-1552). All ten bots join the server, but within 30 seconds, most of them time out.

**Comment by ano95** [comment]
Yes, thanks for pointing that out. Tried running it on better HW, no problems. Also found out that login is using most of the CPU, so setting the interval to a higher number (like 10s) resolved this issue too.

**Comment by rom1504** [comment]
Yeah that's why I setup the interval. Probably we should add a comment
explaining that and that increasing would be a good idea.
