### ISSUE TITLE
bot.on("chat") doesn't works

### ISSUE THREAD

**Issue by Mercury7639** [PrismarineJS/mineflayer#715]
```
bot.on("chat", function(message) {
console.log(message)
  });
```
Hey, when I try that simple script, nothing happens when I write anything in the chat, please help me :)
I only want to get the message, and the username :D

**Comment by plexigras** [comment]
what do you get when you use `bot.on('message', console.log)`?

**Comment by Mercury7639** [comment]
I want to log the message in the console.

**Comment by Mercury7639** [comment]
But when I try to send it in the message, it also doesn't works
And here :
https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#chat-username-message-translate-jsonmsg-matches

**Comment by plexigras** [comment]
if you answer my question i can try to help you.

**Comment by Mercury7639** [comment]
I simply want to log the message
Example:
In Minecraft Chat:
Test123 : Hello
In Console:
Hello

**Comment by plexigras** [comment]
assuming the format is `username : msg` you can do
```js
bot.once('inject_allowed', () => {
  bot.chatAddPattern(/^(?:.+? )?(.+?) : (.*)$/, 'chatmsg')
  bot.on('chatmsg', console.log)
})
```

**Comment by Mercury7639** [comment]
The Problem is, it outputs this 
```
nojang11 Hello undefined ChatMessage {
  json: { extra: [ [Object], [Object], [Object] ], text: '' },
  text: '',
  extra: 
   [ ChatMessage {
       json: [Object],
       text: 'nojang11 ',
       bold: undefined,
       italic: undefined,
       underlined: undefined,
       strikethrough: undefined,
       obfuscated: undefined,
       color: 'gray' },
     ChatMessage {
       json: [Object],
       text: ': ',
       bold: undefined,
       italic: undefined,
       underlined: undefined,
       strikethrough: undefined,
       obfuscated: undefined,
       color: 'dark_gray' },
     ChatMessage {
       json: [Object],
       text: 'Hello',
       bold: undefined,
       italic: undefined,
       underlined: undefined,
       strikethrough: undefined,
       obfuscated: undefined,
       color: 'gray' } ],
  bold: undefined,
  italic: undefined,
  underlined: undefined,
  strikethrough: undefined,
  obfuscated: undefined,
  color: undefined }


```
But I only want the name, and the message :c

**Comment by plexigras** [comment]
`bot.on('chatmsg', (name, msg) => console.log(msg))` should work

**Comment by Mercury7639** [comment]
I wrote this 
```
bot.on('chatmsg', (name, msg) => {
console.log(msg)
bot.chat(name);

});
```
But it doesn't works :c

**Comment by plexigras** [comment]
dose what i put above also not work?

**Comment by Mercury7639** [comment]
No, that works, but it outputs the message in the format
Name : Message 
(Normal minecraft Chat)
But I want to can get the name and the message separately

**Comment by rom1504** [comment]
Use split

**Comment by Mercury7639** [comment]
Thanks <3

**Comment by Mercury7639** [comment]
It doesn't works

**Comment by Mercury7639** [comment]
The problem is I don't know how long the name from a user is, and how long the message is

**Comment by rom1504** [comment]
message.split(':')
