### ISSUE TITLE
bot.look and bot.lookAt

### ISSUE THREAD

**Issue by Mercury7639** [PrismarineJS/mineflayer#717]
Hey I don't know how I should use 
bot.lookAt because I don't know what "point" is 
(See https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botlookatpoint-force-callback)
and when I try to 
bot.look(-89.8, 2.1, true);
then it looks in the false direction

**Comment by rom1504** [comment]
It's Vec3. You can do new Vec3(1,2,3)
