### ISSUE TITLE
mineflayer doesent launch

### ISSUE THREAD

**Issue by leopoldhub** [PrismarineJS/mineflayer#719]
Hello, so, First im french so my english is realy bad... sorry...

When i try to launch my minecraft bot with the cmd command "node index.js", the node cmd create a new line with my folder destination and wait an order... but my bot is not running...

the code of my bot:
`var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "31.220.12.242", 
  port: 25565, 
  username: "xxxxxxx", 
  password: "xxxxxxx", 
  version: "1.12.2"
});

bot.chat("hy");

bot.on('chat', function(username, message) {
  if (username === bot.username) return;
  bot.chat(message);
});`

the screen of the cmd: [http://image.noelshack.com/fichiers/2018/38/6/1537651409-capture.png](url)

**Comment by rom1504** [comment]
what version of node do you have ?

**Comment by leopoldhub** [comment]
the 8.12 LTS

**Comment by rom1504** [comment]
Ah lol.
Mineflayer is not a bot, it's a lib.
There are example of usage in the examples folder.
You can't run index.js

**Comment by leopoldhub** [comment]
i know... i dont just launch index.js... i create a new bot...

Le lun. 1 oct. 2018 à 21:59, Romain Beaumont <notifications@github.com> a
écrit :

**Comment by rom1504** [comment]
Can you try on another server to make sure the problem is with your script
and not the server ?
