### ISSUE TITLE
promisify

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#725]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%246%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PrismarineJS/mineflayer/issues/725)

we can do something like https://nodejs.org/api/fs.html#fs_fs_promises_api to provide promises

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $6.00)

- [<img src='https://avatars1.githubusercontent.com/u/2346494?v=4' alt='rom1504' width=24 height=24> rom1504](https://issuehunt.io/u/rom1504) ($2.00)
- [<img src='https://avatars2.githubusercontent.com/u/17525823?v=4' alt='imharvol' width=24 height=24> imharvol](https://issuehunt.io/u/imharvol) ($2.00)
- [<img src='https://avatars2.githubusercontent.com/u/25003283?v=4' alt='louis030195' width=24 height=24> louis030195](https://issuehunt.io/u/louis030195) ($2.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PrismarineJS/mineflayer/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by plexigras** [comment]
i have not tested it but i think it should work

```javascript
const mineflayer = require('mineflayer')
const { promisify } = require('util')

const promisifyPlugin = bot => {
  bot.promisify = n => {
    if (!bot[n] || bot[n] instanceof Promise) return
    bot[n] = promisify(bot[n])
  }
  ['wake', ...].forEach(bot.promisify)
}

const bot = mineflayer.createBot(...)
bot.loadPlugin(promisifyPlugin)
bot.once('login', () => {
  bot.wake().then(...)
})
```

**Comment by rom1504** [comment]
Yes it's of course possible to promisify mineflayer.
My point was we could have a mineflayer.promises. That seems like a
reasonable choice to support promises without breaking the API

**Comment by wvffle** [comment]
I think I can work on that in my spare time

**Comment by rom1504** [comment]
On this something better we can do is support both callback and promise externally.
Internally we would use only promises (and async/await)

**Comment by ph0t0shop** [comment]
I'm willing to do this, but do you really want to keep supporting callbacks? I think it's beneficial to the quality of the framework to implement this in a breaking way, with everything async/promisified and no more callbacks anywhere.

**Comment by rom1504** [comment]
@ph0t0shop what's the benefit of removing callback for exposed functions ?
All internal can use only promises and exposing callback is just something you call on all functions to add it.

**Comment by extremeheat** [comment]
That would mean a breaking change and that all the existing projects using mineflayer would have to be updated. IMO it’s not worth a breaking change over, there’s no practical benefit other than a slightly simpler API call.

**Comment by rom1504** [comment]
Example 
```
function callbackify (g) {
return function(a, cb) {
return g.then(r => {cb(r); return r;})
}
}
function f(a) {
const b = a+1
return Promise.resolve(b)
}
module.exports = callbackify(f)
```

(Callbackify can be generalised to handle any number of arguments easily enough)

**Comment by rom1504** [comment]
My point is it would not even be simpler.

**Comment by ph0t0shop** [comment]
Yes, but then it can't be the same function so one would have to call a different function depending on whether they want to use the async or the callback version. The way you listed with callbackify will not expose the promise version

**Comment by rom1504** [comment]
Yes it does. The example I did make the function both take a callback and return a promise

**Comment by ph0t0shop** [comment]
These are all the functions that will need to be converted. Non-exposed ones are between parentheses. I'll probably start working on converting them
```bed#wake
bed#sleep
blocks#waitForChunksToLoad
(book#write)
(book#modifyBook)
book#writeBook
book#signBook
chat#tabComplete
chest#deposit
chest#withdraw
craft#craft
(craft#craftOnce)
creative#setInventorySlot
creative#flyTo
digging#dig
dispenser#deposit
dispenser#withdraw
enchantment_table#enchant
enchantment_table#takeTargetItem
enchantment_table#putTargetItem
enchantment_table#putLapis
(furnace#takeSomething)
furnace#takeInput
furnace#takeFuel
furnace#takeOutput
(furnace#putSomething)
furnace#putInput
furnace#putFuel
inventory#consume
inventory#fish
inventory#putSelectedItemRange
inventory#activateBlock
inventory#activateEntity
inventory#activateEntityAt
inventory#transfer
inventory#placeBlock
inventory#clickWindow
inventory#putAway
inventory#moveSlotItem
physics#look
physics#lookAt
simple_inventory#tossStack
simple_inventory#toss
simple_inventory#unequip
(simple_inventory#equipEmpty)
simple_inventory#equip
villager#openVillager
villager#trade
(villager#putRequirements)
(villager#deposit)```

**Comment by rom1504** [comment]
congrats and thanks @ph0t0shop !
