### ISSUE TITLE
find the block the bot is looking at.

### ISSUE THREAD

**Issue by ahibbe** [PrismarineJS/mineflayer#731]
* what you want to do (the objective in english):
I want to find the block the bot is looking at. (In the client, the block is indicated by a thin black frame)

* what you tried (the code):

```js
const yaw = player.entity.yaw;
const pitch = player.entity.pitch;
console.log("yaw=" + yaw + " pitch=" + pitch);
var vecLook = new vec3(
    -Math.cos(pitch) * Math.sin(yaw),
    Math.sin(pitch),
    -Math.cos(pitch) * Math.cos(yaw)
);
var block = mybot.blockAt(vecLook);
if (!block) {console.log(...
```

* what happened:
block is always null

* what you expected to happen:
the block the bot is looking at.

Thanks for this great API!

**Comment by plexigras** [comment]
this is not the first time this has been asked :smile: https://github.com/PrismarineJS/mineflayer/issues/674

**Comment by rom1504** [comment]
now done, thanks @wvffle
