### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by derjp** [PrismarineJS/mineflayer#732]

**Comment by plexigras** [comment]
1. do you get the error when not using the proxy?
2. do you get the error when connecting to a vanilla server?

**Comment by derjp** [comment]
1. No error without proxies
2. I tried connecting the bots on a local spigot server using a proxy for each bot, still the same error

The proxies are ok, I tested them again

**Comment by rom1504** [comment]
How did you test the proxies ?
Do they support CONNECT ?

Did you try with a proxy you start yourself ?

**Comment by derjp** [comment]
I tested the proxies using a node module: https://github.com/chill117/proxy-verifier
I'm not sure how I can check whether a proxy supports CONNECT, how do I check that?

Thanks a lot

**Comment by rom1504** [comment]
I don't know if there is a package to check if CONNECT works, but you could try implementing that check yourself.
Most like most http proxies don't support it.
