### ISSUE TITLE
How can I get the data value of the block the bot is pointing at? The block could be ~20 blocks away.

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/mineflayer#733]

**Comment by theonlygusti** [comment]
@plexigras in what way's it outdated?

**Comment by plexigras** [comment]
it could work if `mf.Point` is replaced with [`Vec3`](https://www.npmjs.com/package/vec3) and 

```js
if (mf.isPhysical(mf.blockAt(cursor).type)) {
```
is replaced with
```js
if (mf.blockAt(cursor).type) {
```

**Comment by plexigras** [comment]
you might also check the blocks bounding box

https://github.com/PrismarineJS/prismarine-block#blockboundingbox
