### ISSUE TITLE
How to hold right-click?

### ISSUE THREAD

**Issue by theonlygusti** [PrismarineJS/mineflayer#734]
Imagine bot is holding a sword in the hand.

How do I start and stop right clicks?

**Comment by plexigras** [comment]
[`bot.activateItem()`](https://github.com/PrismarineJS/mineflayer/blob/52768dabdd6d391a5703597922668f7683dba35d/docs/api.md#botactivateitem)
[`bot.deactivateItem()`](https://github.com/PrismarineJS/mineflayer/blob/52768dabdd6d391a5703597922668f7683dba35d/docs/api.md#botdeactivateitem)
