### ISSUE TITLE
toss Enchanted Book (with StoredEnchantments / ntb)

### ISSUE THREAD

**Issue by ahibbe** [PrismarineJS/mineflayer#735]
* what you want to do (the objective in english)
I want to toss an Enchanted Book (with StoredEnchantments / ntb)

for example:

Item {
  type: 403,
  count: 1,
  metadata: 0,
  nbt:
   { type: 'compound',
     name: '',
     value: { StoredEnchantments: [Object] } },
  name: 'enchanted_book',
  displayName: 'Enchanted Book',
  stackSize: 1,
  slot: 38 }

* what you tried (the code)

bot.toss (item.type, item.metadata, 1, [callback])
there is a parameter for metadata (here 0) but how can I pass the nbt-Data ?

* what happend
tossed any enchanted_book (because of parameter item.type) and not the enchanted_book with nbt

Thank you

**Comment by rom1504** [comment]
Did you find a solution ?

**Comment by plexigras** [comment]
not op but the most obvious solution would be to use `bot.tossStack` :smile:
