### ISSUE TITLE
chatAddPattern but with colours (raw message text I guess)

### ISSUE THREAD

**Issue by theonlygusti** [PrismarineJS/mineflayer#736]
How can I add a pattern that checks for colours?

**Comment by plexigras** [comment]
bot.on('[message](https://github.com/PrismarineJS/mineflayer/blob/52768dabdd6d391a5703597922668f7683dba35d/docs/api.md#message-jsonmsg)', msg => console.log(msg.[toMotd](https://github.com/PrismarineJS/mineflayer/blob/52768dabdd6d391a5703597922668f7683dba35d/docs/api.md#message-jsonmsg)()))

bot.on('[message](https://github.com/PrismarineJS/mineflayer/blob/52768dabdd6d391a5703597922668f7683dba35d/docs/api.md#message-jsonmsg)', msg => msg.[toMotd](https://github.com/PrismarineJS/mineflayer/blob/52768dabdd6d391a5703597922668f7683dba35d/docs/api.md#message-jsonmsg)().match(/regex/g) && console.log(msg.toString()))

**Comment by theonlygusti** [comment]
@plexigras can I make new 'chat' events that match against the motd-formatted raw message?

**Comment by plexigras** [comment]
you can do `bot.emit('chat', ...)` or copy, modify and use

https://github.com/PrismarineJS/mineflayer/blob/52768dabdd6d391a5703597922668f7683dba35d/lib/plugins/chat.js#L38-L46
