### ISSUE TITLE
remove default 'chat' event

### ISSUE THREAD

**Issue by theonlygusti** [PrismarineJS/mineflayer#738]
every message from the server is triggering on chat.

I added my custom pattern.

How do I make it use _only_  my custom pattern before the event is emitted?

**Comment by plexigras** [comment]
you have to remove or change this chat pattern

https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/chat.js#L14

also what is your code?

**Comment by rom1504** [comment]
indeed just remove the default chat pattern in that array.
