### ISSUE TITLE
let the bot sow and harvest plants?

### ISSUE THREAD

**Issue by ahibbe** [PrismarineJS/mineflayer#739]
* what you want to do (the objective in english)
I want to let the bot sow and harvest plants?

* what you tried (the code)
nothing, I expected someting like:

 if (bot.canCanHarvest(block)) 
  bot.harvest(block, onHarvestCompleted)
....

I do not need a complete code just a few key words where to look, if that's possible. Unfortunately I did not find anything in the examples

Thank you

**Comment by plexigras** [comment]
`bot.placeBlock`, `bot.dig` and maybe `bot.activateBlock`

https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md

**Comment by rom1504** [comment]
I think an example showing how to do that would be nice, feel free to create open when you made it work @ahibbe

**Comment by rom1504** [comment]
now done, thanks @wvffle
