### ISSUE TITLE
Sprint jump

### ISSUE THREAD

**Issue by theonlygusti** [PrismarineJS/mineflayer#740]
Can I make the bot look like a player who is holding forward, space, and the sprint key?

**Comment by plexigras** [comment]
[bot.setControlState](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botsetcontrolstatecontrol-state)

**Comment by theonlygusti** [comment]
Why is it so slow? I can walk _without_  sprinting and be faster than:

``js
bot.setControlState('sprint', true);
bot.setControlState('forward', true);
bot.setControlState('jump', true);```

**Comment by theonlygusti** [comment]
aren't those by-default designed to replicate vanilla?

**Comment by rom1504** [comment]
yes. If you find they are wrong, please fix :)
