### ISSUE TITLE
problem inflating chunk uncompressed length 1043 compressed length 861

### ISSUE THREAD

**Issue by 1by** [PrismarineJS/mineflayer#741]
Hey, since today when connecting my bot to the server, it doesn't work anymore, I have made no code changes at all, It just does not want to connect and stay on the server, these are the errors i have come by.
https://hastebin.com/idacasoxey.js
Any help is appreciated. :D

**Comment by 1by** [comment]
EDIT: Changed version to 1.12 and the bot connects now. although nothing works, it connects atleast.
still spitting out errors like https://i.imgur.com/qOkmZNw.png

**Comment by rom1504** [comment]
Your server probably installed an incompatible plugin.
What server is it ?

**Comment by 1by** [comment]
arcadewars.net mario realm.
