### ISSUE TITLE
Scoreboard updated score event

### ISSUE THREAD

**Issue by A5005** [PrismarineJS/mineflayer#742]
Hello, I'm new here, thanks for your free and very useful api!

I have programmed a seller on a popular German citybuild server. There is a problem with the so-called fakemoney. One solution was to check the account balance with /money via (bot.chat) after an incoming payment and then to compare whether the money was actually received. With this solution you can geht kicked by the server, because you constantly send the same command. The next idea was to check the current account balance on the scoreboard, this is displayed in the scoreboard and constantly updated. I have not programmed much with the scoreboard so far, but I was not been able to catch the event where the account balance is updated. I tried with bot.on ('scoreboardScore', (scoreName, itemName, value) to catch the event but this will not fired after a payment has been received and the account balance Is updated in the scoreboard. Thank you.

**Comment by plexigras** [comment]
- what's the output of `DEBUG="minecraft-protocol" node your_bot.js` ?

**Comment by rom1504** [comment]
Yes and what server is that ?

**Comment by A5005** [comment]
My bot is uses minecraft-protocol 1.8.2 (mineflayer 2.7.3). I think the server is a bukkit-spigot, that can connect with clients from 1.8 - 1.12, but 1.8 recommended.

**Comment by derjp** [comment]
```
bot._client.on('packet', (data, metadata) => {
  if (metadata.name === 'scoreboard_team') {
    ...
  }
});
```

You are probably looking for this. :) The packet is called 'scoreboard-team'. 

I assume the server is GrieferGames.net? Then you have to additionally filter for the data.name, 'Kontostandcheck'. You can find the value using data.prefix.

**Comment by rom1504** [comment]
If you just want to bypass your server kick thing, you can do silly things like sending some other random command in the middle so it doesn't detect you are always sending the same command.

**Comment by ahibbe** [comment]
...I've already tried that, but I'm still kicked for general command spamming

**Comment by ahibbe** [comment]
> Afaik your approach isn't working though, as scoreboard packets aren't really reliable and don't get sent sometimes (especially if the server is lagging). At least it's like that on GrieferGames.net.

Yes, it's really about griefergames. That's bad news, I've never noticed that the account balance in the scoreboard is not up to date. I'm afraid there is no solution to recognize fakemoney. Apart from my third idea to put all players on / ignore, but somehow I do not like this solution. I think you know a lot about griefergames, do you have an idea for detecting fakemoney?

**Comment by rom1504** [comment]
You could have multiple bots, one just retrieving the money information, storing it somewhere so the second bot can use it to do the rest.

**Comment by rom1504** [comment]
Or you know, if you are trying to do something good for the server (detecting fakemoney seems good ? I don't know), you can contact the admin and ask him to get the command spam limit up for your bot.

**Comment by A5005** [comment]
Answer to derjp:

> Afaik your approach isn't working though, as scoreboard packets aren't really reliable and don't get sent sometimes (especially if the server is lagging). At least it's like that on GrieferGames.net.

Yes, it's really about griefergames. That's bad news, I've never noticed that the account balance in the scoreboard is not up to date. I'm afraid there is no solution to recognize fakemoney. Apart from my third idea to put all players on / ignore, but somehow I do not like this solution. I think you know a lot about griefergames, do you have an idea for detecting fakemoney?

**Comment by A5005** [comment]
Answer to rom1504 

> If you just want to bypass your server kick thing, you can do silly things like sending some other random command in the middle so it doesn't detect you are always sending the same command.

...I've already tried that, but I'm still kicked for general command spamming

**Comment by A5005** [comment]
Answer to rom1504

> You could have multiple bots, one just retrieving the money information, storing it somewhere so the second bot can use it to do the rest.

I had already thought of 2 bots, but I would really only do it if there is no other possibility (especially since I have only one MC account)

**Comment by A5005** [comment]
Answer to rom1504

> Or you know, if you are trying to do something good for the server (detecting fakemoney seems good ? I don't know), you can contact the admin and ask him to get the command spam limit up for your bot.

I think I have little chance. It is a very tolerant server, where even scamming is not prohibited. Moreover, only expensive ranks (50-100+ EUR) are able to send the messages that can be interpreted as fakemoney. I believe the server operator earns money with it and has no interest to ban fakemony.

**Comment by rom1504** [comment]
Ok, what about reconnecting regularly ? that would probably bypass the server command spam detection

**Comment by rom1504** [comment]
@A5005 why can't it remember about the payment and do the following action on reconnection ?
You can either store the state in a db or handle the reconnection gracefuly so it remembers the state in memory

**Comment by A5005** [comment]
@rom1504 Honestly, it gets a bit too complicated for me, though it would probably work in the wise. I think more and more about your 2 Bot suggestion, that seems to me the safest. With reconnecting I also see the problem that as soon as a transaction fails (on this server) you are called  a scammer (in the global chat) within seconds. (After the reconect you need about 1 minute to reach your shop. Sometimes reconnect does not work because the server is overcrowded).

**Comment by rom1504** [comment]
I see, having 2 bots for this would make sense indeed.

**Comment by derjp** [comment]
@A5005 I'm gonna explain in german as it's really specific issue (not a mineflayer problem)

Ich kenne bisher 2 Wege wie man das Fakemoney von /status erkennen kann:
1. Du speicherst dir die Zeit ab (ich mach das mit Unix-Zeit, mit Date.now) und vergleichst jedes Mal wenn der Bot Geld bekommt ob der zeitliche Unterschied zwischen Join und dem Money kurz ist. Ich hab zum Beispiel eine Zeitspanne von 15000ms zwischen Join und Pay, ansonsten sieht der Bot es als Fakemoney an.

2. Du machst es so, dass der Spieler in der Nähe vom Bot sein muss wenn er payt. Die Statusnachricht wird ja immer am Spawn gesendet, somit wird dieses "Money" nicht erkannt. Das heißt, immer wenn dein Bot Money erkennt (ich denke mal du machst das mit einer RegExp?) schaust du ob der Spieler der gepayt hat in der Nähe vom Bot ist (z.B. innerhalb von 50 Blöcken)

Wäre gut wenn du diese Lösungen für dich behälst, muss nicht jeder wissen. :P Und wäre super wenn du mir das CB/Plot vom Bot oder deinen Ingamenamen sagst, würde mir den gerne mal anschauen. :)

**Comment by A5005** [comment]
@derjp You're right, this is more and more a problem of this special server and not a mineflayer problem. I will contact you via your email.

Thank you for all your answers on this topic!

**Comment by derjp** [comment]
@A5005 I never really check my emails, would be better if you contact me on Telegram @derjp or at the GrieferGames forums

**Comment by A5005** [comment]
@derjp 
I sent you an incorrect entry with telegram (first time I uses this) and you probably blocked me for that, can you undo that? My username there is 'buch bot'
