### ISSUE TITLE
How can I intercept a velocity packet from the server?

### ISSUE THREAD

**Issue by theonlygusti** [PrismarineJS/mineflayer#743]
Can I listen for a `setVelocity` packet from the server? 

And check the vector that the server is telling the bot to set its velocity to?

**Comment by rom1504** [comment]
the velocity is already available as `bot.entity.velocity`

**Comment by theonlygusti** [comment]
@rom1504 isn't that a client-side thing?

I am specifically interested in intercepting the knockback package sent by the server.

I'm assuming the server's plugins use Bukkit's `Player#setVelocity(Vector)` to tell the player how they should be knocked back.

I'd like to be able to add a listener for the packet generated by this to see the values the server plugins are telling my bot to set its velocity to.

**Comment by rom1504** [comment]
No it's not, that value is set by the entity_velocity packet which
mineflayer listen on to set bot.entity.velocity

**Comment by theonlygusti** [comment]
@rom1504 is there an event that gets fired when the server changes that value?

**Comment by rom1504** [comment]
You can, and if you manage to get something useful that mineflayer doesn't
currently provide, please pr it in mineflayer code so everybody can use it
;)
