### ISSUE TITLE
1.13.2 support?

### ISSUE THREAD

**Issue by lela-null** [PrismarineJS/mineflayer#744]
I cant seem to figure out how to get the bot to connect to a 1.13.2 vanilla server, is this a possible version? If so how to set it up?

**Comment by rom1504** [comment]
No it's not supported yet. You can help support by working on
https://github.com/PrismarineJS/prismarine-chunk/pull/47

**Comment by rom1504** [comment]
pchunk is now up to date.
Next step : make #712 work. There are probably some stuff to adapt in mineflayer code.

**Comment by Rundik** [comment]
node-minecraft-protocol already has 1.13.2 support. Did they change some APIs in that update?

**Comment by rom1504** [comment]
yes, see https://github.com/PrismarineJS/prismarine-chunk/issues/57

**Comment by Tomoli75** [comment]
ETA?
(or estimated time of completion)

**Comment by rom1504** [comment]
Nobody is working on it. So I'd say eta around 2050 or maybe 2100

**Comment by TrendMend** [comment]
rip I guess. I really wanted to get a chat client going, bt doesnt look like its happening

**Comment by And-IO** [comment]
This really should be something that’s worked on, I’m using this for a university project on agent behaviour and learning in an open world environment and planning to test it in real servers which will soon be running 1.13 - Mineflayer has massive potential, please don’t abandon it!

**Comment by lela-null** [comment]
ETA for 1.13.2?

**Comment by LewisTehMinerz** [comment]
Desperately need this.

**Comment by alexbudin** [comment]
I see there is a PR for 1.13:
https://github.com/PrismarineJS/prismarine-chunk/pull/60

Any chance this will be pulled and then added support for 1.14.x ?

Thank you.

**Comment by wvffle** [comment]
@alexbudin it's only an update of the linter

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/prismarine-chunk/issues/57

**Comment by TheDevMinerTV** [comment]
Any ETA on this?

**Comment by rom1504** [comment]
Yes, it will be done whenever you finish it.

**Comment by wvffle** [comment]
1.13 support is pretty much here
