### ISSUE TITLE
Move items from chest to bot inventory

### ISSUE THREAD

**Issue by A5005** [PrismarineJS/mineflayer#746]
* what you want to do:
I want to move items from a chest directly to the inventory of the bot (which opens the chest).
I do not want to use withdraw, because it will drop the item somewhere in the area.

* what you tried:
const window = this.curChestObj.window;
This line already returns the window associated with the chest. (64 slots, from slot 27 the inventory starts). However, I do not have a  method for moving the items like bot.moveSlotItem. 
Is that somehow supported by mineflayer? 
Or can this be solved only with the low-level methods window.click etc?

**Comment by plexigras** [comment]
what's wrong with  `bot.moveSlotItem`?

**Comment by rom1504** [comment]
Ok great
