### ISSUE TITLE
Get contents of tab list

### ISSUE THREAD

**Issue by EvilSourcerer** [PrismarineJS/mineflayer#747]
I am wondering if it's possible to get the contents of the list in Minecraft when you press tab in plain text

**Comment by rom1504** [comment]
Yeah that packet
http://minecraft-data.prismarine.js.org/?d=protocol#toClient_tab_complete

bot._client.on("tab_complete", data => ...)

It's not mineflayer high level API though, maybe you can add it :)

**Comment by EvilSourcerer** [comment]
wait but that's an event, not a variable... how do I use it

**Comment by rom1504** [comment]
```
bot._client.on("tab_complete", data => console.log(data))
```

**Comment by EvilSourcerer** [comment]
It has to first send the packet which 'tab_complete', the result is no output when I use that code. How do I send the packet.

**Comment by plexigras** [comment]
http://minecraft-data.prismarine.js.org/?d=protocol#toServer_tab_complete

**Comment by EvilSourcerer** [comment]
that seems to be the right packet... but how is it sent

**Comment by EvilSourcerer** [comment]
wait thats not the player list... thats the command that autofills when you press tab. I was asking to make the messages on the player list readable as plaintext.

**Comment by rom1504** [comment]
this.players

**Comment by EvilSourcerer** [comment]
Fixed! The actual way to get the header and footer of the tab list is : 
bot._client.on("playerlist_header", data => console.log(data))

**Comment by rom1504** [comment]
It would be great to add a mineflayer event (and doc) for this so other people can use it ;)

**Comment by rom1504** [comment]
bot._client provides all the packets but it's low level and can change at any point (whenever mojang feels like changing stuff).
It's better to add stuff to mineflayer API so we can guarantee some stability.

**Comment by rom1504** [comment]
now done, thanks @wvffle
