### ISSUE TITLE
Add displayName in user properties

### ISSUE THREAD

**Issue by A5005** [PrismarineJS/mineflayer#752]
There is a well-known NickNames Bukkit plugin that displays a modified username for other players in the chat window (also in the TAB playerlist). I have not found a way to extract the nickname from the original username. Is there is a chance to realize that ?

The original username can be easily determined via bot.players.
Typical output (non-vanilla Server) shows always the the original username even if the player is nicked.

username: 'UserName',
  ping: 0,
  uuid: '*****-*****-****-*****-*****',
  entity:
   Entity {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     id: 2932485,
     type: 'player',
     position: Vec3 { x: -4412.5, y: 59.001, z: 4114.5 },
     velocity: Vec3 { x: 0, y: 0, z: 0 },
     yaw: 1.2490457723982544,
     pitch: -1.0279847897285246,
     onGround: true,
     height: 1.62,
     effects: {},
     equipment: [ <5 empty items> ],
     heldItem: null,
     isValid: true,
     metadata:
      { '0': 0,
        '1': 300,
        '2': '',
        '3': 0,
        '4': 0,
        '6': 20,
        '7': 0,
        '8': 0,
        '9': 0,
        '10': -1,
        '16': 0,
        '17': 0,
        '18': 8 },
     username: 'UserName',
     timeSinceOnGround: 39.33799999999982 } }

**Comment by rom1504** [comment]
Yes.
Can you add displayName: item.displayName at https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/entities.js#L372
And make a pr for it ?

It's undeed available in the packet
http://minecraft-data.prismarine.js.org/?d=protocol#toClient_player_info

**Comment by rom1504** [comment]
now done, thanks @wvffle
