### ISSUE TITLE
mineflayer bot not redirect to another server

### ISSUE THREAD

**Issue by Artarious** [PrismarineJS/mineflayer#755]
![image](https://user-images.githubusercontent.com/42579810/49338804-428df080-f638-11e8-8b9a-833cbc57174b.png)

Does not give an error, no answer.

minecraft proxy (connect to server) - https://pastebin.com/NZSpRNqq
and mineflayer bot (no connect) - https://pastebin.com/NQq7kg4k (this is all log)

as I understand it, the server redirects the player to another server
but the mineflayer bot is not redirected

**Comment by rom1504** [comment]
Not enough context.

**Comment by rom1504** [comment]
no information
