### ISSUE TITLE
Error when connecting to certain servers.

### ISSUE THREAD

**Issue by 1by** [PrismarineJS/mineflayer#756]
problem inflating chunk
uncompressed length 1029
compressed length 848
hex 8508789c04c0498eb3c60200e0eef7142977b1f403c560b3f81798c150cd68c6aa9d196c46630603c5112245ca21b28ca2dc20dbdc27525659e43b7d7cb6bf7ffbf9afbf25f7cf7fbffdf4cb3f9fbffe9f49c9e78f73b1cdefb198fef85f41207d8b993663af659a489553ab8cad789cbd4bac5d87c4da8dc9789e490af02bbd4410cb8660d4b8467148705036682f3b6bf7363b3857b8c3b5d5851c0a9a15d768b5629536aab5ca74b8e0ae9d70c897691c564e656ce8d954a60c699c94749ec0362386501018f874eb18f5eb683c2392ca866074259deb92601291c64949e7096c33c2cfb7986f110b4bfcf4de6917d1267b6d0bfdca645db8d87b469c8bb722003bac843b56a4d55654ceda3d600779eb28168d8386c781011c05edb8468c13788ca3949dd5698d0560695d2c806a8fb500aeec8bc1383e14ef09fdfdf3b71f0cfd7dd0668acf57c9ad38fb0cc0f2a2f6515616d1a48fc15c7339b56d628aa3948b23074dfde459d975a0121a11971f745f780caf4dd1b4f73a574ff14b7397e7bc9994aa2eb9ee7447a79ee864f4b64989db6130cee14b90d33b4737837c2ec31353dc8f5277f0d7e372f7d32527a89f0e9a60b6fb7a6adc688fc20eeaa1461e72bf7d7953afdb32e7a4097ad8451332e323cf45c30900f360a20bebb1fa31f27845d8bb09f2b04759244eee3177ea1ee4db55e2f2ed5ad99868068b72c65865bdab5a6d75d40509b71bff48761da372dab97a7c83f07c8fa03abad99b1945e9e1f75520dbb1999d4d750875bfe018b0051246ad290fab0d6167d15170785cd9ddbbd4a6eb1c5dff16831eb460aaf0bd1d2fd2498ad93e638e6004870642c9dab444bd0ff82cfacbfc2e8e3e9fa17e2b9453a9e17590b7a5309fb545a0647484b7e129dece66a9c58760addd46067b2f54a6e3a6f2f81acc76cccb83c04a14ad535e44786e228417452db17a32ad56bef1f73e7765e525098e454dd3eb2be127dfda27df3f8fea4536e421660d799f6f98369f3741052493c64666442fd2e7bbc730ded0516ac890242276d78d2eaa785b3313eaf190238a2d0f06031f87d74555c0ca4859313a6fa121b5a08701903c0999594f25faa45f6900fb71e1f5e0f955c3e1eb8544bb4e1f6b7e0926e03d393799f32d2e7bbe9ce9a25107a69da8e26cbc92d3f78f8f8fff000000ffff
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17) errno: -5, code: 'Z_BUF_ERROR' }
Faction flight enabled.
(!) Overworld KOTH is starting in 5h13m53s!
 - X: 24, Y: 65, Z: -142
internal/buffer.js:53
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 10239. Received 10448
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt8 (internal/buffer.js:141:5)
    at readUInt4LE (C:\Users\Seppe\node_modules\uint4\index.js:23:23)
    at Section.getSkyLight (C:\Users\Seppe\node_modules\prismarine-chunk\src\pc\1.8\section.js:81:12)
    at Chunk.getSkyLight (C:\Users\Seppe\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:112:34)
    at Chunk.getBlock (C:\Users\Seppe\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:71:27)
    at blockAt (C:\Users\Seppe\node_modules\mineflayer\lib\plugins\blocks.js:91:26)
    at updateBlock (C:\Users\Seppe\node_modules\mineflayer\lib\plugins\blocks.js:147:22)
    at Client.bot._client.on (C:\Users\Seppe\node_modules\mineflayer\lib\plugins\blocks.js:222:7)
    at Client.emit (events.js:182:13)

**Comment by 1by** [comment]
Edit: my bot works on: VanityMC, OstiaPvP, but no other servers, any idea why? can provide code if necessary.

**Comment by 1by** [comment]
Oh, I can't seem to get minecraft-protocol to work with my code, I'll wait till the fix is released, thanks though!

**Comment by rom1504** [comment]
You can use mineflayer with minecraft-protocol master.
Anyway I'll do a new release soon

**Comment by rom1504** [comment]
now released. Just run npm update
