### ISSUE TITLE
Crashing once joining a server.

### ISSUE THREAD

**Issue by 9budddy** [PrismarineJS/mineflayer#761]
Related to #757 
Server = Spigot
Version = 1.8
Mineflayer = 2.7.3
I am expecting for my discord bot to log into a minecraft server, use a /server command and not crash trying to find some sort of id. I get into the hub, but once I go through onto a /server it crashes.

Hello, while using mineflayer.js with minecraft-protocal.js, I have come upon the problem of an undefined id through a click event that I do not fully understand. Here is my problem error log:
[https://hastebin.com/ivagowecun.coffeescript](https://hastebin.com/ivagowecun.coffeescript)
I have tried adjusting, the true and falses around in the framing.js and adding console logs to find out what is happening.

[https://hastebin.com/emobubilaf.js](https://hastebin.com/emobubilaf.js)
Here is my code and here are the logs that come with it:
[https://hastebin.com/ojuranuvuq.sql](https://hastebin.com/ojuranuvuq.sql)

This is all due to my error at:
[https://media.discordapp.net/attachments/525220244331954187/530132428186976258/2d8f901575de06ed895bd82f97ce7238.png](https://media.discordapp.net/attachments/525220244331954187/530132428186976258/2d8f901575de06ed895bd82f97ce7238.png)

Finally, this is my minecraft-protocol debugging.
[https://hastebin.com/cakuhiyico.bash](https://hastebin.com/cakuhiyico.bash)

**Comment by rom1504** [comment]
now fixed
