### ISSUE TITLE
Out of Range Offset Error

### ISSUE THREAD

**Issue by 9budddy** [PrismarineJS/mineflayer#763]
Related Issue: #756 
Connecting my bot to factions to have it read factiontop data.
When connecting the bot to the server it crashes getting this error: 
![image](https://user-images.githubusercontent.com/39657629/51093346-9bd95b80-1770-11e9-87c5-dc84d808b4f1.png)

Minecraft-Protocol Debug:
https://hastebin.com/ulatufiboc.bash

It's a spigot server, and version 1.8.
I am currently using the most updated version of everything.
I saw it was said to be fixed in the newest version,
but I seem to have gotten this error over my older error. #761

**Comment by rom1504** [comment]
What you could do is dump your chunk to a file and add it to prismarine-chunk tested chunks.
That will make it easier to debug.

**Comment by 9budddy** [comment]
I'm sorry, but I've been looking and I have absolutely no idea how to do that. It seems that the server wouldn't allow my bot to connect on any 1.8 or 1.9 versions, but 1.10 works. It's something I don't understand because I always log on under a 1.8 version. Thanks anyways!

**Comment by micahzgreat** [comment]
I too am having this issue along with my buddy on discord. @rom1504 if you could further assist me with providing a dumped chunk that would be great, i already have mc chunk dumper but i am quite confused on how to actually dumb a chunk...btw un getting literally the same thing

### **[Error](https://i.imgur.com/bxikIJI.png)**

**Comment by micahzgreat** [comment]
here is a debug https://hastebin.com/fazosebuwe.bash

**Comment by micahzgreat** [comment]
Also idk if it has anything to do with my issue but i was looking through the dubug and came across this [Click Me](https://i.imgur.com/GZOHNkZ.png) Like i said not sure if its related or not but this is the only place where the words chunk and buffer are together.

**Comment by rom1504** [comment]
Not enough information
