### ISSUE TITLE
Reconnect ?

### ISSUE THREAD

**Issue by Jan3kk** [PrismarineJS/mineflayer#767]
I want my bot to be join server, type some commands and log it in console,
and then it should wait till he gets kicked when restart and he should rejoin again.

He does join and type command, but then he goes again to the lobby. 
btw. every "//" is useless for u so I don't need to translate it,
bot.activateItem, bot.moveSlot... } = way to join server by clicking item in opened chest.

The problem is after he joins server and types commands, he joins lobby again. Idk why is that ?
My thought is that he gets triggered someway by const bot = mineflayer.. because it connects him again with lobby.

Code:
```js
const Item=require("prismarine-item")("1.8")
const mineflayer = require('mineflayer')
const mcData=require("minecraft-data")("1.8.8")
const sleep = (milliseconds) => {
  return new Promise(resolve => setTimeout(resolve, milliseconds))
}

var options = {
  //host: "sky-land.pl",
  host: "sky-land.pl",
  port: 25565,
  username: "mariusz_podolski",
  verbose: true
};

function checkIfEquipped (err) {
    if (err) {
      console.log(`cannot` + err)
    } else {
      console.log(`Bez problemu //Otwarcie kompasu`)
    }
}

function spacja(){
  console.log('-------------------------')
}


//--------------------------------- tu sie zaczyna kodowanie, wyzej sa funkcje

var bot = mineflayer.createBot(options);

bindEvents(bot);

function bindEvents(bot) {

  //Proces logowania po wejsciu na serwer
  bot.once('login', function() {
    console.log("Ustawienia:");
    console.log(bot.settings)
    spacja()
    console.log("Ustawienia:");
    console.log(bot.settings)
    spacja()
    console.log('--- [ Probuje wejsc na serwer ] ---')
    spacja()
    console.log("Wszedlem na serwer");
    spacja()
    console.log(bot.username)
    spacja()
    bot.chat('/login muszka123')
    console.log('Proba zalogowania')
    spacja()
    bot.setQuickBarSlot(0)
    console.log('Proba zmiany slotu na komapas')
    spacja()
    setTimeout(function() {bot.activateItem()},3)
  
  //Triggeruje sie gdy PPM na kompas i odpali sie okno skrzynki
  bot.on('windowOpen', (window) => {
	sleep(1000).then(() => {
        console.log('Czekanie 1 sekundy.')
		spacja()
    })
    console.log('Otworzylem kompas')
    bot.moveSlotItem(1,2, checkIfEquipped)
    spacja()
    console.log('Wybralem lave ?')
    setTimeout(function() { 
      bot.whisper('Janekk_', 'Wbilem na serwer' )
      bot.whisper('_Freszak_', 'Wbilem na serwer' )
      console.log('Pisze MSG do Janekk_ i _Freszak_ ze wbijam')
    },2000)
    //nastepna komenda
    setTimeout(function() {
       bot.chat('/dom')

       bot.whisper('Janekk_', 'Ide na /dom' )
       bot.whisper('_Freszak_', 'Ide na /dom' )
       console.log('Pisze MSG do Janekk_ i _Freszak ze ide na /dom')
       spacja()
    },3000)

  })
    
  });

  bot.on('kicked', function(reason) {
    console.log("Zostalem wyrzucony za: ", reason);
	bot.quit()
    bot.end()
    bot = mineflayer.createBot(options);
    bindEvents(bot);
  });
}
```

**Comment by rom1504** [comment]
why do you have 2 init function ?

**Comment by Jan3kk** [comment]
> why do you have 2 init function ?

Sorry, it was mistake, my code look like this /\ (I edited)

**Comment by Jan3kk** [comment]
@rom1504 I fixed the problem, but now I'm struggling with other issue.
My bot isn't affected by water for example :/ Idk how to fix that

**Comment by Jan3kk** [comment]
I updated the code, it look like this now ( still same problem, bot connects to lobby after joining good server ):

`const Item=require("prismarine-item")("1.8")
const mineflayer = require('mineflayer')
const mcData=require("minecraft-data")("1.8.8")
const sleep = (milliseconds) => {
  return new Promise(resolve => setTimeout(resolve, milliseconds))
}

var options = {
  //host: "sky-land.pl",
  host: "sky-land.pl",
  port: 25565,
  username: "mariusz_podolski",
  verbose: true
};

function czekaj(){

	sleep(1000).then(() => {
        console.log('Czekanie 1 sekundy.')
		spacja()
    })
	
}

function checkIfEquipped (err) {
    if (err) {
      console.log(`cannot` + err)
    } else {
      console.log(`Bez problemu //Otwarcie kompasu`)
    }
}

function spacja(){
  console.log('-------------------------')
}

function wejdzZrob(){
	
	//Gdy wejdzie na serwer..
	bot.once('login', function() {
    console.log("Ustawienia:");
    console.log(bot.settings)
    spacja()
    console.log('--- [ Probuje wejsc na serwer ] ---')
    spacja()
    console.log("Wszedlem na serwer");
    spacja()
    console.log(bot.username)
    spacja()
    bot.chat('/login muszka123')
    console.log('Proba zalogowania')
    spacja()
    bot.setQuickBarSlot(0)
    console.log('Proba zmiany slotu na komapas')
    spacja()
    setTimeout(function() {bot.activateItem()},3)
	})
	
	//Gdy otworzy okno, w tym przypadku kompas (skrzynie) z serwerami
	bot.on('windowOpen', (window) => {
	sleep(1000).then(() => {
        console.log('Czekanie 1 sekundy.')
		spacja()
    })
    console.log('Otworzylem kompas')
    bot.moveSlotItem(1,2, checkIfEquipped)
    spacja()
    console.log('Wybralem lave ?')
    setTimeout(function() { 
      bot.whisper('Janekk_', 'Wbilem na serwer' )
      bot.whisper('_Freszak_', 'Wbilem na serwer' )
      console.log('Pisze MSG do Janekk_ i _Freszak_ ze wbijam')
    },2000)
	
    //nastepna komenda
    setTimeout(function() {
       bot.chat('/dom')

       bot.whisper('Janekk_', 'Ide na /dom' )
       bot.whisper('_Freszak_', 'Ide na /dom' )
       console.log('Pisze MSG do Janekk_ i _Freszak ze ide na /dom')
       spacja()
    },3000)

  })
  
  //Gdy zostanie wyrzucony
  bot.on('kicked', function(reason) {
    console.log("Zostalem wyrzucony za: ", reason);
	bot.quit()
    bot.end()
    bot = mineflayer.createBot(options);
    relog()
  })
	
	
	
}

function relog(){
	
    console.log('Odpalam funkcje relog(), probuje sie laczyc ponownie...')
	spacja()
	wejdzZrob()
	
}

var bot = mineflayer.createBot(options);

wejdzZrob()`

**Comment by rom1504** [comment]
What is "lobby" ?

**Comment by rom1504** [comment]
Yes there's a debug mode, see the readme

**Comment by Jan3kk** [comment]
I got with the problem, ty.

**Comment by Eoshi** [comment]
News from the program? Because he interests me.
