### ISSUE TITLE
Bot isn't running as expected

### ISSUE THREAD

**Issue by EBMare** [PrismarineJS/mineflayer#768]
I tried to join a multiplayer server.
The server accepts all of the version from 1.8 to 1.13
When I am trying to connect the bot with the server the console says that:
"Error: Version 1.13.1 is not supported." 
Is there a possibility to change the version of the bot?

**Comment by rom1504** [comment]
Yes you can set the "version" option when calling createBot

**Comment by EBMare** [comment]
Could you update the bot for 1.13.2? <3
Thank your for for reply
