### ISSUE TITLE
bot('whisper') never gets triggered

### ISSUE THREAD

**Issue by Jan3kk** [PrismarineJS/mineflayer#769]
As I said, chat event never gets triggered. I think it's because the server isn't vanilla, cuz you got some regex in chat.js.

Whisper doesn't gets fired too.. I'd like it to fire when var player = 'nick' says something on whisper to me.
Anyone got idea how to deal with it ? 
If you don't have any idea how to do that with whisper, you can explain how to do that with chat instead.
Chat in game looks like this: (I will use my nickname)
normal player: [Gracz] Janekk_: hello
vip: [VIP] Janekk_: hello
supervip: [SuperVIP] Janekk_: hello
In chat method, I'd like event to give me username (it can be with rank like gracz vip..) and message, seperately from ':' character. (I will accept any event that gives me whole message)

btw. I tried some chatmsg from a git user but it doesn't work for me.

**Comment by Himself65** [comment]
your meaning is that bot replies `hello Janekk`?

**Comment by Himself65** [comment]
like this?

https://github.com/PrismarineJS/mineflayer/blob/4421c6e29c11d81ec3f15525176f14a8925f82f0/examples/chatterbox.js#L103-L106

**Comment by Jan3kk** [comment]
> like this?
> 
> [mineflayer/examples/chatterbox.js](https://github.com/PrismarineJS/mineflayer/blob/4421c6e29c11d81ec3f15525176f14a8925f82f0/examples/chatterbox.js#L103-L106)
> 
> Lines 103 to 106 in [4421c6e](/PrismarineJS/mineflayer/commit/4421c6e29c11d81ec3f15525176f14a8925f82f0)
> 
>  bot.on('whisper', (username, message, rawMessage) => { 
>    console.log(`I received a message from ${username}: ${message}`) 
>    bot.whisper(username, 'I can tell secrets too.') 
>  }) 
> then
> 
> ```js
> bot.on('whisper', (username, message, rawMessage) => { 
>    // ...
>    bot.whisper(message, username) 
> }) 
> ```

Shortly:
whisper and chat event doesn't gets triggered. I wanted to show how chat looks cuz you need to know if you want to regex message.
