### ISSUE TITLE
In need of dig() function

### ISSUE THREAD

**Issue by Jan3kk** [PrismarineJS/mineflayer#770]
With plugin dig() that author implements, I get an error of some bot.block.position.offset.type === 9 and null..

So I need a simple digging function, that can just dig in straight line (like normal players do, just hold their left click and thats it) I will accept anything that digs like normal player on AFK. 
Thanks !

**Comment by derjp** [comment]
In short, the vanilla MC client calculates which block lies in the line of sight and then sends the position of that block to the server. It does not do anything other than the .dig() method does, which means that the function you are searching for simply does not exist.

I'm not really familiar with the error you received, but if I guessed, you are probably using the method in a wrong way.
Try bot.blockAt(position) to get the block and then use bot.dig(block).
