### ISSUE TITLE
.on('spawn') event firing twice on bungeecord

### ISSUE THREAD

**Issue by 1by** [PrismarineJS/mineflayer#772]
My code: 
bot.on('spawn', function() { //When joined, automatically go to factions.
		

		bot.chat("/onyx");
		let logchannel = client.channels.find(c => c.name == "alt-relog")
		logchannel.send(`Alt with name: ${botname} logged into ${ServerIP} with port: ${ServerPort} at timestamp: ${new Date().toUTCString()}`)
	});
Would there be any way to make it fire once instead of twice? what im thinking is because of the alt going in hub first then the actual factions server it fires the spawn event twice.

**Comment by rom1504** [comment]
Probably but a simple workaround is to use another event or a timeout

**Comment by Mikosikora** [comment]
This is normal, bungecord is invisible switching between servers. So you enter once in the lobby and once in the target server.
