### ISSUE TITLE
Grabbing items from the Creative inventory

### ISSUE THREAD

**Issue by MNDoodieMan** [PrismarineJS/mineflayer#775]
When I try to set a slot to an item in the inventory it doesn't do anything.
My code:
`bot.creative.setInventorySlot(36, 12);`
I'm trying to set the first quickbar slot to sand. What am I doing wrong?

**Comment by rom1504** [comment]
Are you in creative mode ?

**Comment by MNDoodieMan** [comment]
Yeah. I found out why, I had to make an item instance using the prismarine-item lib, instead of only giving a item ID.
