### ISSUE TITLE
Take Screenshot

### ISSUE THREAD

**Issue by redd223JC** [PrismarineJS/mineflayer#780]
Hello, I'm asking if it is possible with MineFlayer, we can take a screenshot from the bot view. Thank you so much !

**Comment by rom1504** [comment]
Not it's not possible, mineflayer doesn't have a rendering engine.

**Comment by redd223JC** [comment]
And with voxel.js like https://github.com/vogonistic/mineflayer-voxel but this project is dated 2013 so it does not work anymore. It's possible ?

**Comment by rom1504** [comment]
Yes it could be possible, you can work on it.

**Comment by redd223JC** [comment]
Okay thank you
