### ISSUE TITLE
Bot's can't start

### ISSUE THREAD

**Issue by carloverhamme** [PrismarineJS/mineflayer#781]
When I try to run my code, it says: Username 'USERNAME' tried to join with an invalid session

My code:

```js
const mineflayer = require("mineflayer");

const server = {
	"host": "localhost",
	"port": 25565
}

const botCount = 1

const nameChars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789'.split("")

let genName = () => {
	let gen = ""

	for(let i=0; i <12;i++) {
		gen += nameChars[Math.floor(Math.random() * nameChars.length)]
	}

	return gen
}

console.log('Loading bots...')

for(let i = 0; i <= botCount; i++) {
	let genBot = mineflayer.createBot({
		'host': connect.host,
		'port': connect.port,
		'username': genName()
	})

	genBot.on('login', () => {
		console.log(genBot.username + ' added to ' + connect.host)
	})
}
```

**Comment by rom1504** [comment]
problems : 
1. `connect` is not defined
2. you didn't pass the password in createBot (is it an offline mode server ?)
3. `server` variable is not used

**Comment by carloverhamme** [comment]
Ooh yea, I changed it so server, didnt update it here. But thanks for the comment that I need a password for online mode.

**Comment by KenWa51** [comment]
Why would you not need a password for online mode?

**Comment by carloverhamme** [comment]
I got it fixed, how to send commands via the terminal?

**Comment by rom1504** [comment]
Look at issues, other people proposed solution to this.
Then you can PR an example to solve the question once and for all.

**Comment by rom1504** [comment]
now we have a repl example, feel free to use it
