### ISSUE TITLE
'spawn' never gets triggered but 'update_health' event is received

### ISSUE THREAD

**Issue by ImHarvol** [PrismarineJS/mineflayer#783]
it's possible your server doesn't send the update_health packet and hence spawn doesn't get emitted https://github.com/PrismarineJS/mineflayer/blob/7e3da452d6c75b44b612f8c174700699687d7495/lib/plugins/health.js#L11

_Originally posted by @rom1504 in https://github.com/PrismarineJS/mineflayer/issues/749#issuecomment-441462483_

---

This is my code:
```JavaScript
const mineflayer = require('mineflayer');
const navigatePlugin = require('mineflayer-navigate')(mineflayer);
const vec3 = require('vec3')

let bot = mineflayer.createBot({
    host: "localhost",
    port: 25565,
    username: "testing",
    version:"1.12.2"
});

bot.on('spawn', () => {
    bot.chat('I spawned, watch out!')
})

bot._client.on('update_health', (packet) => { 
    console.log(packet)
})
```

But even though I'm receiving the _update_health_ packet, the _spawn_ event never gets triggered.

**Comment by rom1504** [comment]
The condition for spawn seems to be incorrect, you can fix it
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/health.js#L20

However why do you want to use the spawn event ?

**Comment by safazi** [comment]
Similar problem here - happening on non-vanilla servers, except the spawn event is only emitted when you join for the first time. Bot logs in and appears in the server the next time the bot is ran, but it never again fires "spawn" until I point it to a different server. Similar code to OP.

**Comment by rom1504** [comment]
The solution has already been given

**Comment by unixfox** [comment]
Same behavior for me, the `spawn` event is never triggered. It appears that the event stopped to work when the `2.7.4` version of Mineflayer was introduced.
I've tried on both vanilla and Spigot minecraft server (1.12.2).

**Comment by rom1504** [comment]
The solution has already been given.

**Comment by tryzombie501** [comment]
This issue also occurs for me even with the solution. When the bot joins the server for the first time the spawn / respawn events do not get called.. I've got a work around on the login event I wait 2500 ms before emitting the spawn event.

It's not the best way to solve this but once the spawn event has fired once it works fine without issues.
If I don't fire the spawn event manually other events will not run for me.

The issue could also be due to my lack of knowledge around node.js

**Comment by rom1504** [comment]
Can your PR what you changed, so we can check it's correct ?
