### ISSUE TITLE
Bot disconnected after logging in

### ISSUE THREAD

**Issue by TheAlan404** [PrismarineJS/mineflayer#784]
If you are reporting a bug please report on these points :

* what you want to do (the objective in english) **start bot**
* what you tried (the code) **i tried some codes, echo, echo edited, navigate**
* what happened **it timed out and closed after login**
* what you expected to happen **do its job and start normally**

In particular it will be useful to provide these informations :

* what happens when using a mineflayer example? **disconnection after 15 sec.**
* what happens when using a node-minecraft-protocol example? **???**
* what mineflayer version? **currently latest, the one for 1.12.2**
* what server version? **1.12.2**
* which server? (spigot, paper, vanilla, any particular plugins ?) **vanilla cracked**
* what's the output of DEBUG="minecraft-protocol" node your_bot.js ? **???**
* what's the error msg? **n o n e**
* what script is used? **ill upload when i go to pc**

**Comment by rom1504** [comment]
Vanilla cracked doesn't exist

**Comment by TheAlan404** [comment]
What... it somehow does in the hosting site... And accualy i fixed the problem by moving the server to another place so issiue done?

**Comment by satyamedh** [comment]
okay if some1 stumbles upon this, just update mineflayer version, that will fix it!

**Comment by kali89d** [comment]
програма вот 
from javascript import require

mineflayer = require('mineflayer')

# create bot
BOT_USERNAME = 'Robol'
bot = mineflayer.createBot({
    'host': 'localhost',
    'port': 54819,
    'username': BOT_USERNAME,
    'hideErrors': False,
    'version': '1.12.2'})
итог 
Exception has occurred: AttributeError
'NoneType' object has no attribute 'pyi'
  File "C:\Users\komp\Desktop\kali\python\mainecraft\Mineflayer.py", line 1, in <module>
    from javascript import require
AttributeError: 'NoneType' object has no attribute 'pyi'

**Comment by TheAlan404** [comment]
> програма вот from javascript import require
> 
> mineflayer = require('mineflayer')
> 
> # create bot
> BOT_USERNAME = 'Robol' bot = mineflayer.createBot({ 'host': 'localhost', 'port': 54819, 'username': BOT_USERNAME, 'hideErrors': False, 'version': '1.12.2'}) итог Exception has occurred: AttributeError 'NoneType' object has no attribute 'pyi' File "C:\Users\komp\Desktop\kali\python\mainecraft\Mineflayer.py", line 1, in from javascript import require AttributeError: 'NoneType' object has no attribute 'pyi'

Please open a new issue
