### ISSUE TITLE
Time is *significantly* wrong

### ISSUE THREAD

**Issue by EmeraldSnorlax** [PrismarineJS/mineflayer#787]
I am expecting the bot to give an accurate reading of the day night cycle; here is my code:

```js
//Commands
bot.on("chat", function(username, message) {
  if (message.startsWith(prefix)) {
    const args = message.slice(prefix.length).trim().split(/ +/g)
    const command = args.shift().toLowerCase()
    if (command === 'time') {
      let time = bot.time.day 
      if (time > 1800) { 
        bot.chat('> It is ' + time + ' ticks! (between midnight and sunrise)')
      } else if (time > 1200) {
        bot.chat('> It is ' + time + ' ticks! (between sunset and midnight)')
      } else if (time > 6000) {
        bot.chat('> It is ' + time + ' ticks! (between noon and sunset)')
      } else if (time > 0) {
        bot.chat('> It is ' + time + ' ticks! (between sunrise and noon')
      } else {
        bot.chat('> it seems something went wrong, s-sorry...')
      }
    }
  }
});
```

However, the time is wildly inaccurate, going above 3000 ticks in some cases...

- no mineflayer examples as far as i am aware
* mineflayer 2.7.5
* server is on 1.12.2
* server is running Paper, the server is constantiam.net

* No error messages given as its not a crash, its just giving wildly inaccurate readings...

Edit;
![12k ticks](https://user-images.githubusercontent.com/43452521/53513032-20cbca80-3abc-11e9-943e-be6155d72c9b.png)

.... yeah, 12,000 ticks isnt normal

**Comment by plexigras** [comment]
> Time is based on ticks, where 20 ticks happen every second. There are 24000 ticks in a day, making Minecraft days exactly 20 minutes long.
The time of day is based on the timestamp modulo 24000. 0 is sunrise, 6000 is noon, 12000 is sunset, and 18000 is midnight.
The default SMP server increments the time by 20 every second.

https://wiki.vg/Protocol#Time_Update
