### ISSUE TITLE
Mineflayer sending messages in a weird way

### ISSUE THREAD

**Issue by Nico170f** [PrismarineJS/mineflayer#789]
Hi.
I'm currently trying to make a mineflayer bot that sends in-game messages in a discord channel. I've made this and it works but, it sends the messages in a weird way. The bot joins fine, and starts sending the messages, the thing is that the bot sends 4 messages, then stops for 2 seconds ish, then sends 4 messages again and repeats. 
I want the bot to send the messages in the same "speed" as they get sent in-game. 

The server is 1.8, Spigot.
Does anyone know how to fix this? 

Code: 
https://hastebin.com/ijolixavib.coffeescript

**Comment by rom1504** [comment]
Is the bot using 100% of your CPU ?
If you do a console.log , does the messages get printed faster ?

**Comment by Smadger1** [comment]
@Nico170f That is Discord rate limiting you I believe. Either combine the most recent 10 messages into 1 message or accept discords rate limiting.

**Comment by rom1504** [comment]
seems fixed, reopen if needed
