### ISSUE TITLE
Force bot to be at specific position

### ISSUE THREAD

**Issue by mcnoname** [PrismarineJS/mineflayer#794]
Hi,
I wanted to let the Bot walk on some non-vanilla Servers but i got flagged by the anti-cheat when i try to move over slabs and stairs. I already know that this is because the slabs are considered as full-blocks by the bot so it looks like he is flying. Now i want to "force" him to be 0.5 blocks lower as he normally would be.
I tried to modify bot.entity.position, but this dont makes the bot move, it only changes tha value. I red something about hijacking bot.position ([here](https://github.com/PrismarineJS/mineflayer/issues/228#issuecomment-85253774)) but bot.position is undefined. Am i doing something wrong or is there another way to accomplish this?

**Comment by rom1504** [comment]
it can only be fixed by supporting bounding box in physics engine I'm afraid... there's an open issue about that

**Comment by mcnoname** [comment]
Yes i know that it could be fixed by supporting bounding box and i had already seen this issue and why it cannot be fixed that easily. what i want to do is something like "teleporting" the bot and ignoring the physics engine.

**Comment by rom1504** [comment]
bot.position = new Vec3(1,2,3) will do it
