### ISSUE TITLE
bot.targetDigBlock.position TypeError: Cannot read property 'position' of null (With video. it keeps multiplying)

### ISSUE THREAD

**Issue by TheMatrix99s** [PrismarineJS/mineflayer#799]
I'm using Navigate and BlockFinder plugins.
What i'm trying is to make the bot chop all the wood within 70 radius (https://pastebin.com/WDTWZJ1j)
But what happened is, when the bot chops 2 wood blocks, the code for some reason keeps multiplying (video example: https://streamable.com/a29uu )
The error message (https://pastebin.com/UiCXyLLJ)
I'm using the latest mineflayer version and the server is on 1.8.8 (open to lan and same error happens for spigot)
i tried setting a timeout for everything but the same thing happened.

**Comment by safazi** [comment]
I stopped using BlockFinder because of this - I didn't have the multiplying, but I did encounter `Cannot read property 'position' of null`.

**Comment by safazi** [comment]
Please add a log inside of `onDiggingCompleted`. I have a feeling it is being called twice. Did you specify to in `createBot` that `version: '1.8.8'` ?

**Comment by safazi** [comment]
Just figured it out - you're using `EventEmitter.on` when you should be using 'EventEmitter.once'.

**Comment by TheMatrix99s** [comment]
> Just figured it out - you're using `EventEmitter.on` when you should be using `EventEmitter.once`.
> `bot.navigate.on -> bot.navigate.once`

Thanks ! that fixed it
