### ISSUE TITLE
Add 3.0.0 milestone

### ISSUE THREAD

**Issue by wvffle** [PrismarineJS/mineflayer#801]
### New features
I guess that after #797, #744 as well as 1.14 support we should bump the version to 3.0.0

I don't know whether or not we should implement all of the lacking physics. That's a bit of work to be done. On the other hand some issues are there for 4 years already.

In my opinion mineflayer-navigate should be included in mineflayer because it's core functionality

### Refactoring
Also I guess that #725 should be implemented as a standard, not as a plugin. I think, we can do that in new major version.

Some words about #341:
I think that we should use classes for most of the things.

prismarine-entity should be a class, not a function.
Also we should have PlayerEntity (that extends Entity) and BotEntity (which extends PlayerEntity). In this scenario we make `bot`, `bot.entity` and `bot.player` (`bot.players[bot.username]` before 34f7019e) one and the same

**Comment by rom1504** [comment]
I don't think it should be called "3.0.0" but something like "more features" milestone is a good idea indeed. You can also use the "projects" functionality of github if you want

**Comment by wvffle** [comment]
I'd resign from callbacks and move entirely to async functions which would break and change entire api

**Comment by wvffle** [comment]
Also if we make `bot` an instance of `Entity`, then we have to add `bot.entity` as a recurrent reference. If we make new major version we can drop it.

**Comment by rom1504** [comment]
Ah no about callbacks vs promise, it would be smarter to just *add* the promise version ie support both. I believe there is already some work that has been done for this (if you look at the issues about it)

**Comment by rom1504** [comment]
I would like to avoid making big breaking change except if there is a very good reason to do so.
There are a bunch of stuff built on top of mineflayer

**Comment by rom1504** [comment]
Prismarine-entity is a class already

**Comment by rom1504** [comment]
too vague, closing, re-open more precise issues if needed
