### ISSUE TITLE
cant build on spigot 1.8.8? (with video and code)

### ISSUE THREAD

**Issue by TheMatrix99s** [PrismarineJS/mineflayer#802]
Basically i want my bot to place a sapling on top of dirt. It works fine on Open to Lan but does not work on any spigot server (tested on 1.8.8) i even tried my own spigot server and it didn't work. it says "planting a sapling was successful" but it doesn't build anything and there are no error messages. (I also tried dirt stone wood and none of them worked)
this is the code (https://pastebin.com/0TmnseVQ)
the video (https://streamable.com/6lrbi)

I'm using the latest mineflayer version

**Comment by TheMatrix99s** [comment]
i didnt mean to close it ._.

**Comment by wvffle** [comment]
First of all, the face vector is not valid. It should be `(0, 1, 0)`, not `(0, 1, -1)`. That's why it doesn't throw any error.

Then, I dunno why but you have to place the block 1 block under so at offset `(0, 0, -1)`

**Comment by TheMatrix99s** [comment]
> First of all, the face vector is not valid. It should be `(0, 1, 0)`, not `(0, 1, -1)`. That's why it doesn't throw any error.
> 
> Then you have to place the block 1 block under so at offset `(0, 0, -1)`
thanks!

**Comment by wvffle** [comment]
Can you check if it works with those settings in vanilla?
