### ISSUE TITLE
Using the bots.forEach option

### ISSUE THREAD

**Issue by PamlaNL** [PrismarineJS/mineflayer#803]
* What you want to do (the objective in English):
I'm trying to make it so both of my accounts/bots will run /server [realm] at login using bots.forEach.

* What you tried (the code)
```
function ready () {
  bots.forEach(bot => {
    bot.on('login', function() {
      bot.chat("/server Atlantes");
      console.log("Succesfully logged in at " + ServerName)
    })
  })
}
```
* What happened:
They just stood at the hub and doesn't run any commands.
* What you expected to happen:
I expect the bots to run the /server command at login. 

I was using mineflayer 2.7.5 when getting this issue.

**Comment by rom1504** [comment]
I think 'login' event is too early.
Try to use a setTimeout (say 20s)

**Comment by PamlaNL** [comment]
```
function ready () {
  bots.forEach(bot => {
    setTimeout(function() {
    bot.on('login', function() {
      bot.chat("/server Atlantes");
      console.log("Succesfully logged in at " + ServerName)
    })
    }, 20000)
    bot.on('error', console.log)
  })
}
```
Set a timeout and the bots still don't run /server Atlantes upon login.

**Comment by wvffle** [comment]
Set the timeout inside `bot.on('login'. function () {`. Not outside.

**Comment by rom1504** [comment]
Wait... Where is that ready function called ?
It needs to be called on the same event loop iteration as createBot,
otherwise you'll miss the login event

Please provide the whole code

**Comment by PamlaNL** [comment]
```
const bots = []
for (let i = 0; i < credentials.length; ++i) {
  setInterval(() => {
    createBot(credentials[i])
    if (i === credentials.length) ready()
  }, 5000)
}

function createBot ({ username, password }) {
  const bot = mineflayer.createBot({
    host: ServerIP,
    port: ServerPort,
    username,
    password,
    version: "1.8.8"
  })

  bots.push(bot)
}

function ready () {
  bots.forEach(bot => {
    bot.on('login', function() {
	setTimeout(function() {
      bot.chat("/server Atlantes");
      console.log("Succesfully logged in at " + ServerName)
	}, 20000)
    })
	bot.on('end', console.log)
  })
}
```

**Comment by rom1504** [comment]
Yeah so that's your problem, you are calling ready at the end, that's
wrong, you need to do the bot.login after each createBot
+ Your set interval / forEach don't make any sense, have a look at the doc
of setInterval

**Comment by wvffle** [comment]
I'd move calling ready to a callback in createBot and call that callback on login like that:
```js
const mineflayer = require('mineflayer'); //Used for the bot its self.
const cron = require('node-cron'); //Required to run tasks at set times.
const spawn = require('child_process').spawn //Required to restart the bot.

const credentials = [
  { username: "X", password: "X" },
  { username: "X", password: "X" }
]

const ServerName = "X";
const ServerIP = "X";
const ServerPort = 25565;
const bots = []
for (let i = 0; i < credentials.length; ++i) {
  setInterval(() => {
    createBot(credentials[i], () => {
      if (i === credentials.length) ready()
    })
  }, 5000)
}

function createBot ({ username, password }, cb) {
  const bot = mineflayer.createBot({
    host: ServerIP,
    port: ServerPort,
    username,
    password,
    version: "1.8.8"
  })

  bot.on('login', () => {
    bots.push(bot)
    cb()
  })
}

function ready () {
  bots.forEach(bot => {
      bot.chat("/server Atlantes")
      bot.on('end', console.log)
      console.log("Succesfully logged in at " + ServerName)
  })
}
```
I guess it should work ;p

**Comment by rom1504** [comment]
That will try to create an infinity of bots. The setInterval need to be removed if you want to loop on the credentials like that.

**Comment by wvffle** [comment]
oh, I haven't seen that. You're right. It should be changet to setTimeout.

**Comment by rom1504** [comment]
Maybe but then put a different timeout value for each bot or they will all
still connect at the same time

**Comment by PamlaNL** [comment]
![image](https://user-images.githubusercontent.com/30055816/57177329-5944a780-6e63-11e9-9258-1817dc2d814e.png)
The bots logged in but never ran the command: "/server Atlantes" upon login.

**Comment by rom1504** [comment]
Well this is again a basic programming thing....
Look at your condition for when to call ready. It will never be executed because i will only get to credentials.length-1

To debug that kind of thing, you can add some console.log everywhere to check what actually get executed.
Or you can use nodejs debugger
