### ISSUE TITLE
BlockFinder | type of wood

### ISSUE THREAD

**Issue by TheMatrix99s** [PrismarineJS/mineflayer#804]
So this is a pretty basic question (i'm new to this)
I want BlockFinder to find 1 type of wood instead of all types of wood like:
    bot.findBlock({
    point: bot.entity.position,
    matching: 17,
    maxDistance: 70,
    count: 1,

17 is the id for wood, but can i do something like 17:0(Oak wood)? because that doesn't seem to work.
hope you understand.
Thanks!

**Comment by wvffle** [comment]
`block.metadata` tells you the type

```js
bot.findBlock({
  point: bot.entity.position,
  matching: (block) => {
    return block && block.type === 17 && block.metadata === 0
  }
})
```

**Comment by TheMatrix99s** [comment]
> `block.metadata` tells you the type
> 
> ```js
> bot.findBlock({
>   point: bot.entity.position,
>   matching: (block) => {
>     return block && block.type === 17 && block.metadata === 0
>   }
> })
> ```

Thanks!

**Comment by rom1504** [comment]
Matching can be a function taking a block as input, see the doc there
https://github.com/Darthfett/mineflayer-blockfinder/blob/master/README.md

So you can look for a given block id + metadata
