### ISSUE TITLE
Bot crashes when sapling turns into a tree (with error code)

### ISSUE THREAD

**Issue by TheMatrix99s** [PrismarineJS/mineflayer#805]
Sometimes when a sapling turns into a tree the bot crashes for some reason.
Error code: https://pastebin.com/mEd5bM9m
I don't think this error is from my code, i tried making the bot do stuff like mining and it crashed when a sapling grew, i tried just letting him join and do nothing and still crashes when a sapling turns into a tree
im using 1.8.8 with latest mineflayer version and the code is specified for version 1.8.8

**Comment by safazi** [comment]
Please show your bot code.

**Comment by TheMatrix99s** [comment]
https://pastebin.com/08fLLbYW
sorry forgot to include the code

**Comment by wvffle** [comment]
What's your node version?

**Comment by TheMatrix99s** [comment]
v10.15.3

**Comment by TheMatrix99s** [comment]
also the same error happens on this code : https://pastebin.com/TkAnrBrd

:/

**Comment by TheMatrix99s** [comment]
literally any code i put; this error happens even without doing anything. i tried it on Open to Lan , spigot 1.8.8 and my vanilla server and still happens

**Comment by rom1504** [comment]
Are you using the last prismarine-chunk ? (Run npm update)

**Comment by TheMatrix99s** [comment]
I did update everything but just to make sure, i made a new folder and downloaded the latest version of everything: mineflayer 2.8.0, prismarine-chunk, prismarine-biome, prismarine-block and many others.
I'm not sure if installing all of these is necessary but i wanted to make sure. (also i hope im doing this right im new)
and the crash is still happening but with a different crash code i think: https://pastebin.com/7XEXaU9K

**Comment by TheMatrix99s** [comment]
is this happening to you? try placing saplings and using bone meal or fast time command to see if it crashes. sometimes it crashes after 1 sapling turning into a tree and sometimes more than 20 saplings

**Comment by TheMatrix99s** [comment]
because if not ill close this and try to figure out what i messed up

**Comment by TheMatrix99s** [comment]
I think i found the solution, i dont know why but when i add this code (https://pastebin.com/ra8RKEJC) it doesnt get kicked.
But when i updated everything, my code doesn't work anymore (even with the old createbot code) it says (https://pastebin.com/bpY6azz5)
this is the code that doesn't work when i updated (https://pastebin.com/08fLLbYW)

**Comment by TheMatrix99s** [comment]
I find the solution, i dont know why but for some reason when i put this code (https://pastebin.com/v1FkP3CM) it doesn't crash and it works fine.
I think it was duo to the fact i used start.bat? (https://pastebin.com/Dh4Ek6nx)
im not really sure.
anyways this fixes it i guess...

**Comment by wvffle** [comment]
Nope, you have found an actual bug. Minecraft allows to remove player from all scorebards.

**Comment by TheMatrix99s** [comment]
> Nope, you have found an actual bug. Minecraft allows to remove player from all scorebards. This was not handled.
> 
> Will be fixed in mineflayer 2.8.1

oh oki glad i could help i guess
