### ISSUE TITLE
Error when removing player from all scoreboards

### ISSUE THREAD

**Issue by wvffle** [PrismarineJS/mineflayer#808]
## Versions
 - mineflayer: 2.8.0
 - server: any
 - node: 12.1.0

## Detailed description of a problem
Bot disconnects with an error when
```
/scoreboard objectives add dummy dummy
/scoreboard players add repl dummy 1
/scoreboard players reset repl
```

## Current code
Repl example

## Expected behavior
Should not throw an error

**Comment by TheMatrix99s** [comment]
https://streamable.com/ztwts
am i doing something wrong? :x

**Comment by wvffle** [comment]
npm install?
