### ISSUE TITLE
My bot can't connect anymore for something about scoreboards?

### ISSUE THREAD

**Issue by TheMatrix99s** [PrismarineJS/mineflayer#810]
My bot used to work just fine when joining servers and stuff, but yesterday for some reason my bot instantly crashes with an error about scoreboards?(https://pastebin.com/bhgVpGqy)
this never happened before :/. I used multiple versions of mineflayer: 2.8.0 2.7.5 2.7.3 and all have the same error. I have Mineflayer + mineflayer-navigate and mineflayer-blockfinder these are the ones i use and they never had this problem until yesterday.
Even this code crashes (https://pastebin.com/G2vLyh3C)
The server is Spigot 1.8.8
Node v10.15.3

**Comment by rom1504** [comment]
Yeah we merged a fix. I'll make a new release soon, but in the meantime use
mineflayer master

**Comment by wvffle** [comment]
#### Please, stick to the issue template.

It's fixed in #809 as @rom1504 said
