### ISSUE TITLE
Merge mineflayer-blockfinder into mineflayer

### ISSUE THREAD

**Issue by wvffle** [PrismarineJS/mineflayer#813]
## Is your feature request related to a problem? Please describe.
`bot.findBlocks` is one of the most commonly used functions. Current implementation is slow and shouldn't be used.

## Describe the solution you'd like
I'd rather make minefalyer-blockfinder a part of mineflayer. It's one of the most used plugins so I'd consider merging it. 

## Describe alternatives you've considered
Alternatively we can remove `bot.findBlocks` from mineflayer if it's too high level function

## Additional context
None ;)

**Comment by rom1504** [comment]
I agree with the fact we need to solve that issue

I think we should not merge it but add it as a dependency (in package.json)
somewhere : either in mineflayer itself or a mineflayer example (with its
own package.json), I'm not sure, it's needed to estimate the code
complexity of mineflayer-blockfinder

**Comment by wvffle** [comment]
Do we have contact with the maintaimer of the blockfinder, @Darthfett? We could move this repo into the organization. It'll be easier to maintain

**Comment by Darthfett** [comment]
@wvffle , I do see notifications on occasion, just haven't been doing much to maintain helperbot/mineflayer-blockfinder.  Is there something I need to do to help here?  I'm willing to "move" the repo, but haven't done this before, so I don't fully understand what that means.

**Comment by wvffle** [comment]
@Darthfett it's called `Transfer Ownership` and it's located inside of repository settings in the danger zone. There's a [guide](https://help.github.com/en/articles/transferring-a-repository) by github. 

It basically means, that all your commits will be present but the actual owner of the repo will be @PrismarineJS organization.

**Comment by Darthfett** [comment]
@wvffle, I'm willing to make the transfer but need permissions in @PrismarineJS to create repositories.  Is someone able to give me that permission?
