### ISSUE TITLE
Underwater walking bug

### ISSUE THREAD

**Issue by lol7344** [PrismarineJS/mineflayer#814]
## Versions
 - mineflayer: 2.8.1
 - server: vanilla 1.12
 - node: 10.15.3

## Detailed description of a problem
A bot, when told to jump in water, instead of swimming starts jumping as if it was on ground. This causes the bot to drown in a few seconds.

## Expected behavior
The bot, when in water and the function bot.setControlState('jump', true) is called, should start swimming and float to the top (or at least, walk on water as if it was swimming).

## Additional context
This problem has been there since the beginning and is pretty limiting, since pathfinding with mineflayer-navigate becomes completely useless near the sea and in places with many lakes/rivers, making the bot effectively useless.

**Comment by SoundOfTheSky** [comment]
I actually solved this by adding loop that checks if player right above water and sets bot.physics.gravity to zero and back to 27 then out of water. Now player can just walk on water.

And additionally to make mineflayer-navigate work properly I little bit changed it's code to make it's think that water is solid block.

**Comment by Ch1sKey** [comment]
Any updates there?
