### ISSUE TITLE
problem inflating chunk

### ISSUE THREAD

**Issue by Wqrld** [PrismarineJS/mineflayer#816]
## Versions
mineflayer@2.8.0
node v8.11.2
server 1.8 viaversioned (saicosky.com)
bot on 1.12.2 as that has the least issues for me
## Current code
```js
accounts.forEach(function (account) {
    botnr++
    setTimeout(function () {

        try {
            console.log(account.name);
            botnames[account.name] = mineflayer.createBot({
                host: config.ip,
                port: config.port,
                username: account.username,
                version: "1.12.2",
                password: account.password
            })

```
(part of the code as it is quite big, the functions are just bot.on('chat' and some hooks that let it message from a web interface)

## Expected behavior
The bot should work fine without any errors

## Additional context
Many errors every 1-2 seconds about chunks?

```
0|cactus  | { Error: unexpected end of file
0|cactus  |     at Inflate.zlibOnError (zlib.js:153:15) errno: -5, code: 'Z_BUF_ERROR' }
0|cactus  | problem inflating chunk
0|cactus  | uncompressed length 1847
0|cactus  | compressed length 1861
0|cactus  | hex (hex)
0|cactus  | { Error: unexpected end of file
0|cactus  |     at Inflate.zlibOnError (zlib.js:153:15) errno: -5, code: 'Z_BUF_ERROR'
```
https://gist.github.com/Wqrld/9d8d542d3839e057ade6fa12e3f4a13b

might have to do with #753

**Comment by rom1504** [comment]
Sounds like a viaversion issue. Reopen if you still have this problem
