### ISSUE TITLE
Ignore invalid username or password

### ISSUE THREAD

**Issue by Wqrld** [PrismarineJS/mineflayer#819]
Currently the program crashes if you have invalid logins, i have a program which could make a lot of invalid logins so is there a way to force it to not crash but just log?
```
0|cactus  | Error: Invalid credentials. Invalid username or password.
0|cactus  |     at /root/bot/node_modules/yggdrasil/lib/utils.js:33:10
0|cactus  |     at IncomingMessage.<anonymous> (/root/bot/node_modules/phin/lib/phin.compiled.js:1:2162)
0|cactus  |     at emitNone (events.js:111:20)
0|cactus  |     at IncomingMessage.emit (events.js:208:7)
0|cactus  |     at endReadableNT (_stream_readable.js:1064:12)
0|cactus  |     at args.(anonymous function) (/root/.nvm/versions/node/v8.11.2/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|cactus  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
0|cactus  |     at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by wvffle** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

**Comment by rom1504** [comment]
No, I already answered him on discord, but he should use bot.on('error'

**Comment by Wqrld** [comment]
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

just for future reference, try/catch only catches errors in your own code and not in submodules, bot.on('error' works fine although it still seems to crash with invalid tablist packets.

**Comment by rom1504** [comment]
No it's not about submodules.
Try catch only catch things that happen in the same event loop iteration, ie sync.

For invalid packets, yes that's not propagated to bot.on('error'
Not sure if we should. It's something to do in the serializer stream
