### ISSUE TITLE
When will minecraft 1.14.1 be supported?

### ISSUE THREAD

**Issue by KenWa51** [PrismarineJS/mineflayer#820]
When do you plan to update to version 1.14.1?

**Comment by wvffle** [comment]
https://github.com/PrismarineJS/prismarine-chunk/issues/57 is a serious problem right now. If we solve it we can update to 1.13 and 1.14. You can work on it if you want. Currently noone is working on it as far as I know.

**Comment by rom1504** [comment]
duplicate of https://github.com/PrismarineJS/mineflayer/issues/744
