### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by squishybanana04** [PrismarineJS/mineflayer#831]
Are there any typescript definitions for this project?

If not I'll write them.

**Comment by rom1504** [comment]
no there aren't any
you can write them

**Comment by rom1504** [comment]
That's done

**Comment by leumasme** [comment]
As typescript is made to allow a gradual transformation of a javascript project to a typescript one, what are arguments against gradually converting to typescript?
I think it would generally make the code cleaner, so im wondering if you considered this @rom1504
