### ISSUE TITLE
Avoid being detected by cheat detection plugins

### ISSUE THREAD

**Issue by Nevgup** [PrismarineJS/mineflayer#835]
Hi :D

I tried to run the bot with an anti-cheat (I was allowed to do that), the problem is that the acted my bot and has banned. The administrators then told me that it was because of the fact that it was not an instance of minecraft

How to make the bot an instance of Minecraft ?

**Comment by rom1504** [comment]
No idea what "instance minecraft" means.
Clarify what you want

**Comment by Nevgup** [comment]
> No idea what "instance minecraft" means. Clarify what you want

The anti cheat detect it's not a minecraft launcher

**Comment by rom1504** [comment]
Ok, then can you rename your issue to "implement features in mineflayer to
avoid being detected by cheat detection plugins".
That is a big task.
If you want to work on it, you can start by looking at all the other issues
on that topic.

Then you can list all the different cheat detection plugin you want to
support and the way they detect cheating.

Finally a last thing you can do is the obvious : ask the server owner to
disable such plugins.

**Comment by Karang** [comment]
The main trigger for anticheat plugins seems to be the physics that is a bit different than vanilla. If you don't want your bot to be detected then make it behave like a legit player.
