### ISSUE TITLE
Problems updating Mineflayer-Voxel

### ISSUE THREAD

**Issue by The-Box1** [PrismarineJS/mineflayer#846]
## Versions
 - mineflayer: 2.9.1
 - server: vanilla 1.12.2
 - node: 10.16.1

## Detailed description of a question
I'm updating Voxel by vogonistic to 1.12.2 but I've hit a snag. Code:

```js
io.sockets.on('connection', function (socket) {
    socket.json.emit('blockData', getBlockInfo()); // This line,
    sendSpawnChunks(socket, bot.entity.position); // This line,
    socket.json.emit('spawn', serializedPosition(bot.entity.position)); // And this line

    bot.on('spawn', function () {
      socket.emit('spawn', serializedPosition(bot.entity.position));
    });
```

Issue: Those 3 lines with comments are in their normal spots but when testing them the bot doesn't seem to be fully setup yet and the functions are being passed undefined values. I tried moving those lines to the beginning of the spawn event but they don't have enough time to send the data to the client before the client starts rendering and throws errors of not having everything needed.

**Comment by rom1504** [comment]
Yes use column events instead (see mineflayer doc)

**Comment by The-Box1** [comment]
I apologize if it's right in front of me and I'm missing it but I can't seem to find it, would you please direct me to the part of the docs you are talking about.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#chunkcolumnload-point

**Comment by The-Box1** [comment]
I'm not sure what you mean by that event. I still get the first error which is "position.toChunkCoordinate is not a function" where position is bot.entity.position and I'm assuming that's because the bot isn't setup yet. If not then I asked the wrong question.

**Comment by rom1504** [comment]
You waited for all the column events to be received and the bot wasn't
spawned yet ?!

**Comment by The-Box1** [comment]
Forgive me for my ignorance, I'm new with this library. So if I understand from my test the chunkColumnLoad event is called for all chunks sent to the client which is 25 IIRC then after all those are sent the spawn event is called.

**Comment by rom1504** [comment]
No, the spawn event is not called.
Can you try using these column events instead ?

**Comment by The-Box1** [comment]
Is there a way to tell when these have finished? There seems to be a random amount of chunks loaded before the event stops firing. I really don't want to have to add timers to check for extended periods of time after the event fires.

**Comment by The-Box1** [comment]
Also, I just restarted my server and now browserify terminated with code 0 and signal of null. But it shows no errors in inspect element, the page is just stuck loading. But socket.io does connect.

**Comment by rom1504** [comment]
You can wait loading of like 10 column, that should be enough

**Comment by rom1504** [comment]
Did it work ?
Feel free to do a pull request if you manage to fix things
