### ISSUE TITLE
Can't add function to Vec3

### ISSUE THREAD

**Issue by The-Box1** [PrismarineJS/mineflayer#847]
## Versions
 - mineflayer: 2.9.1
 - server: vanilla 1.12.2
 - node: 10.16.1

## Detailed description of a question
I'm getting the error: "TypeError: position.toChunkCoordinate is not a function" yet a little bit up in the code I have:
`
  Vec3.prototype.toChunkCoordinate = function () {
    var offset = this.modulus(chunkSize);
    return this.minus(offset).scaled(1 / 32).floored();
  };
`
Where position is bot.entity.position

**Comment by rom1504** [comment]
Provide minimal code that is enough to reproduce the issue please

**Comment by The-Box1** [comment]
`sendSpawnChunks(socket, bot.entity.position);`
Sends chunk data to client.
`
  function sendSpawnChunks(socket, position) {
    var centerChunk = position.toChunkCoordinate();
    var radius = 1;

    for (var x = -radius; x <= radius; ++x) {
      for (var y = -radius; y <= radius; ++y) {
        for (var z = -radius; z <= radius; ++z) {
          var chunk = getChunk(centerChunk.offset(x, y, z));
          if (chunk) {
            socket.json.emit('chunkData', chunk);
          }
        }
      }
    }
  }
`
Handles actually sending the chunks
`
  function getChunk(position) {
    var start = position.toVoxelCoordinate();
    var blocks = new Array(chunkSize.volume());
    var n = 0;
    for (z = 0; z < chunkSize.x; ++z) {
      for (y = 0; y < chunkSize.y; ++y) {
        for (x = 0; x < chunkSize.z; ++x, ++n) {
          var block = bot.blockAt(start.offset(x, y, z));
          if (!block) return undefined;
          blocks[n] = block.type;
        }
      }
    }

    var key = [position.x, position.y, position.z].join('|');

    return {
      position: start,
      key: key,
      blocks: blocks
    }
  }
`
Gets the chunk

**Comment by The-Box1** [comment]
I found the problem. When I updated the Vec3 library I didn't realize there was an instance of it now. So the solution was to use "Vec3.Vec3.prototype.toChunkCoordinate" instead.

**Comment by wvffle** [comment]
Try to do not modify prototype if you don't really need to. Simply create a function that gets Vec3 as a parameter
