### ISSUE TITLE
Trouble connecting to a server !

### ISSUE THREAD

**Issue by Pandattitude** [PrismarineJS/mineflayer#848]
Hi, I would like to use Mineflayer on a Pvp / Faction server. The server accepts Prenium and Crack accounts. there is a register at the beginning, i think it asks nothing mojang about the authentication of the accounts and is based on the register.
I really can not connect with mineflayer on the server.
The server has a HUB to enter, but even in the HUB I see no one.

 - mineflayer: 2.9.1
 - server: Pvp/Faction "Play.Hadaria.fr"
 - node: 12.8.1

To do this I tried different solution, With the password to pass in prenium account it does not work.

![image](https://user-images.githubusercontent.com/45069694/63180369-6ff7be80-c04e-11e9-93b0-61b35a7d023e.png)
![Code avec MDP](https://user-images.githubusercontent.com/45069694/63189408-35991c00-c064-11e9-862a-b0cca919f47a.png)

Without the password to crack account, it still does not work.

![image](https://user-images.githubusercontent.com/45069694/63180125-e34d0080-c04d-11e9-8bf7-daeb4c582464.png)
![image](https://user-images.githubusercontent.com/45069694/63179857-56a24280-c04d-11e9-91d5-d8861fe43915.png)

I based on the sreen below

![Source](https://user-images.githubusercontent.com/45069694/63180950-923e0c00-c04f-11e9-9ddc-492708c9d63d.png)

I hope I have not forgotten anything and I hope there is a solution like that I could put the robot to the test and have fun with the field

here is the server board

![Tableau](https://user-images.githubusercontent.com/45069694/63181357-1abcac80-c050-11e9-8e07-6e8d939bb83c.png)

**Comment by redstonekasi** [comment]
Hello please remove the Account-Details of your Minecraft Account and change your Password.

**Comment by Pandattitude** [comment]
I think I understood why he disconnected.
Once it arrives in the HUB server, it is automatically teleported to the pvp / faction server.
I think it's the fact of changing servers that it spits.
On the other hand when I use the Minecraft protocol, I arrive remained connected to the server even after the teleportation!

would you have a solution to support the server change?

![Preuve](https://user-images.githubusercontent.com/45069694/63203372-490dac80-c08f-11e9-9313-a64486516b07.png)
![Preuve 1](https://user-images.githubusercontent.com/45069694/63203404-82461c80-c08f-11e9-81e6-1ebeefdcd542.png)

```
const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node ansi.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'ansi',
  password: process.argv[5],
  version: 1.8
})

bot.on('message', (message) => {
  console.log(message.toAnsi())
})

```

**Comment by rom1504** [comment]
Can you enable debug mode and report the output ?

**Comment by Pandattitude** [comment]
#```
  minecraft-protocol         }
  minecraft-protocol       ],
  minecraft-protocol       "gamemode": 0,
  minecraft-protocol       "ping": 69,
  minecraft-protocol       "displayName": "{\"text\":\"§2[Baron] §2KOSNOFA\"}"
  minecraft-protocol     }
  minecraft-protocol   ]
  minecraft-protocol } +1ms
  minecraft-protocol read packet play.player_info +1ms
  minecraft-protocol {
  minecraft-protocol   "action": 3,
  minecraft-protocol   "data": [
  minecraft-protocol     {
  minecraft-protocol       "UUID": "c7fff286-699a-32d3-91fd-30c41173f767",
  minecraft-protocol       "displayName": "{\"text\":\"§2[Baron] §2KOSNOFA\"}"
  minecraft-protocol     }
  minecraft-protocol   ]
  minecraft-protocol } +1ms
  minecraft-protocol read packet play.playerlist_header +1ms
  minecraft-protocol {
  minecraft-protocol   "header": "{\"text\":\"\",\"extra\":[{\"text\":\"\n\",\"color\":\"yellow\"},{\"text\":\"✦ \",\"color\":\"yellow\"},{\"text\":\"HADARIA \",\"color\":\"gold\",\"bold\":\"true\"},{\"text\":\"• \",\"color\":\"gray\"},{\"text\":\"PvP/Factions Farm2Win \",\"color\":\"gold\",\"bold\":\"true\"},{\"text\":\"✦\n\",\"color\":\"yellow\"},{\"text\":\"------------------------------------------\n\",\"color\":\"gray\",\"strikethrough\":\"true\"},{\"text\":\"» \",\"color\":\"white\",\"bold\":\"true\"},{\"text\":\"Il y a \",\"color\":\"yellow\",\"bold\":\"true\"},{\"text\":\" \",\"color\":\"aqua\",\"bold\":\"true\"},{\"text\":\"joueurs en ligne \",\"color\":\"yellow\",\"bold\":\"true\"},{\"text\":\"«\n\",\"color\":\"white\",\"bold\":\"true\"},{\"text\":\"------------------------------------------\n\",\"color\":\"gray\",\"strikethrough\":\"true\"},{\"text\":\"Bienvenue sur \",\"color\":\"yellow\"},{\"text\":\"play.hadaria.fr\",\"color\":\"aqua\"}]}",
  minecraft-protocol   "footer": "{\"text\":\"\",\"extra\":[{\"text\":\"------------------------------------------\n\",\"color\":\"gray\",\"strikethrough\":\"true\"},{\"text\":\"Tu es actuellement sur le \",\"color\":\"yellow\",\"bold\":\"true\"},{\"text\":\"Hub\n\",\"color\":\"gold\"},{\"text\":\" Utilise la \",\"color\":\"yellow\",\"bold\":\"true\"},{\"text\":\"boussole \",\"color\":\"aqua\",\"bold\":\"true\"},{\"text\":\"pour rejoindre le \",\"color\":\"yellow\",\"bold\":\"true\"},{\"text\":\"Factions \",\"color\":\"aqua\",\"bold\":\"true\"},{\"text\":\"\n\",\"color\":\"white\"},{\"text\":\"------------------------------------------\",\"color\":\"gray\",\"strikethrough\":\"true\"}]}"
  minecraft-protocol } +0ms
undefined:1
{"text":"","extra":[{"text":"


SyntaxError: Unexpected token
 in JSON at position 29
    at JSON.parse (<anonymous>)
    at Client.<anonymous> (c:\Users\rockd\node_modules\mineflayer\lib\plugins\tablist.js:13:49)
    at Client.emit (events.js:203:13)
    at FullPacketParser.<anonymous> (c:\Users\rockd\node_modules\minecraft-protocol\src\client.js:82:12)
    at FullPacketParser.emit (events.js:203:13)
    at addChunk (c:\Users\rockd\node_modules\readable-stream\lib\_stream_readable.js:297:12)
    at readableAddChunk (c:\Users\rockd\node_modules\readable-stream\lib\_stream_readable.js:279:11)
    at FullPacketParser.Readable.push (c:\Users\rockd\node_modules\readable-stream\lib\_stream_readable.js:240:10)
    at FullPacketParser.Transform.push (c:\Users\rockd\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (c:\Users\rockd\node_modules\protodef\src\serializer.js:81:10)

```
Here is the party that bug, it will be the symbol?

**Comment by roblabla** [comment]
There's an (unescaped) `\n` within `header.extra[0].text` which is causing JSON.parse to fail. Apparently, a string in "real" JSON has to fall within this range:

```
string
    '"' characters '"'

characters
    ""
    character characters

character
    '0020' . '10ffff' - '"' - '\'
    '\' escape

escape
    '"'
    '\'
    '/'
    'b'
    'f'
    'n'
    'r'
    't'
    'u' hex hex hex hex
```

In particular, characters under 0020 aren't allowed, which means raw `\n` is not allowed. But the minecraft JSON parser accepts it because it's very forgiving. Mineflayer/NMP would need to change JSON parser to a more forgiving one to handle this.

**Comment by Pandattitude** [comment]
Okay, so I have to wait for it to change the JSON.parse: /

Otherwise with "Minecraft-protocol", I am connected to the server without problem.

![robot co](https://user-images.githubusercontent.com/45069694/63215114-fdf0a980-c121-11e9-82db-a2e7fe7120b5.png)
![code co](https://user-images.githubusercontent.com/45069694/63215125-4f993400-c122-11e9-8f39-a872d3c8cf76.png)

But I can not use for example the "Farmer.js" from Mineflayer that I would like to improve later to make a farmer autonomous.
As I use the "createclient ()" and not the "CreateBot ()"

![erreur de plugin !](https://user-images.githubusercontent.com/45069694/63215214-bec35800-c123-11e9-8830-1f9ec013ed43.png)

```
`const mc = require('minecraft-protocol')
const Vec3 = require('vec3')
const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node echo.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

const bot = mc.createClient({
  version: 1.8,
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'echo',
  password: process.argv[5]
})
let mcData
bot.on('inject_allowed', () => {
  mcData = require('minecraft-data')(bot.version)
})

// To fish we have to give bot the seeds
// /give farmer wheat_seeds 64

function blockToSow () {
  return bot.findBlock({
    point: bot.entity.position,
    matching: (block) => {
      if (block && block.type === mcData.blocksByName['farmland'].id) {
        const blockAbove = bot.blockAt(block.position.offset(0, 1, 0))
        return !blockAbove || blockAbove.type === 0
      }

      return false
    }
  })
}

function blockToHarvest () {
  return bot.findBlock({
    point: bot.entity.position,
    matching: (block) => {
      return block && block.type === mcData.blocksByName['wheat'].id && block.metadata === 7
    }
  })
}

function loop () {
  try {
    const toHarvest = blockToHarvest()
    if (toHarvest) {
      return bot.dig(toHarvest, () => {
        return setImmediate(loop)
      })
    }

    const toSow = blockToSow()
    if (toSow) {
      return bot.equip(mcData.itemsByName['wheat_seeds'].id, 'hand', () => {
        bot.placeBlock(toSow, new Vec3(0, 1, 0), () => {
          setImmediate(loop)
        })
      })
    }
  } catch (e) {
    console.log(e)
  }

  // None blocks to harvest or sow. Postpone next loop a bit
  setTimeout(loop, 1000)
}

bot.once('login', loop)
`
```

It does not take into account the Mineflayer, I do not know how the add or if it is possible at most?

@roblabla @rom1504 
Sorry, I'm new ^^

**Comment by rom1504** [comment]
You can make a pr to mineflayer to optionally ignore malformed tab list
(just try catch)

**Comment by Pandattitude** [comment]
Effectively, Try-Catch works, I can connect to the server but it stays connected 10 seconds :/
it connects and disconnects, but the possif point, it happens to connect to the server "Pvp / faction"

![Code 5 sec](https://user-images.githubusercontent.com/45069694/63217674-c8ac8180-c14a-11e9-8d1d-ee1eb3e6be9e.png)
![erreur](https://user-images.githubusercontent.com/45069694/63217684-03aeb500-c14b-11e9-8458-24bd85748f92.png)

```
const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node robot.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}
try{
const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'robot',
  password: process.argv[5],
  version: 1.8
})
} catch (err){
    console.log(err);
}
console.log("Le Programme continue ...");

```

**Comment by rom1504** [comment]
That's not where you should put the try catch, you need to put it where the
tab list get parsed

**Comment by Pandattitude** [comment]
@rom1504 
So it gives this:
Otherwise I planted again: /

![code test](https://user-images.githubusercontent.com/45069694/63225119-65affe80-c1cd-11e9-97fc-a170d571aa32.png)

```
module.exports = inject
try{
function inject (bot) {
  const ChatMessage = require('../chat_message')(bot.version)

  bot.tablist = {
    header: new ChatMessage(''),
    footer: new ChatMessage('')
  }

  bot._client.on('playerlist_header', (packet) => {
    if (packet.header) {
      bot.tablist.header = new ChatMessage(JSON.parse(packet.header))
    }

    if (packet.footer) {
      bot.tablist.footer = new ChatMessage(JSON.parse(packet.footer))
    }
  })
}
} catch (err){
    console.log(err);
}

```
![erreur 421](https://user-images.githubusercontent.com/45069694/63225124-6a74b280-c1cd-11e9-95d3-3b5d711e7e90.png)

Do you have an idea?
I am lost: o

**Comment by rom1504** [comment]
you need to put the try catch where the JSON.parse happens, not outside
trying to try catch a function definition doesn't make any sense

**Comment by wvffle** [comment]
I've commented about this in #837

**Comment by rom1504** [comment]
Could you pull request this please ?

**Comment by wvffle** [comment]
@rom1504 I'm in the middle of a trip right now, so I cannot do the PR :( I'll be back in 1.5 months

**Comment by Pandattitude** [comment]
Thank you very much :D @wvffle @rom1504 @roblabla  I did this and it works!

![ça marche](https://user-images.githubusercontent.com/45069694/63396593-dc185080-c3c7-11e9-9eb9-95859ae85c94.png)

with this code, the double account remains connect :D

**Comment by wvffle** [comment]
If it seems to be working I'll try to find some time to patch it and to create some tests for it when I'll have WiFi connection

**Comment by wvffle** [comment]
Closing because it's a duplicate of #837

**Comment by ehfgw236-arch** [comment]
const mineflayer = require('mineflayer');

const bot = mineflayer.createBot({
  host: 'TNT_JHM-PacF.aternos.me',
  port: 44144,
  username: 'BotPlayer123'
});

bot.on('login', () => {
  console.log('البوت دخل السيرفر وبقي ثابتًا في مكانه!');
});

bot.on('chat', (username, message) => {
  if (username === bot.username) return;
  console.log(`<${username}> ${message}`);
});

bot.on('error', err => console.log(err));
bot.on('end', () => console.log('البوت خرج من السيرفر'));
