### ISSUE TITLE
Getting the Item Thrower

### ISSUE THREAD

**Issue by redstonekasi** [PrismarineJS/mineflayer#849]
## Versions
 - Mineflayer: 2.9.1
 - Server: Spigot 1.12.2
 - Node: 12.7.0

## Question
Hello,
just a quick question: How do I get the Thrower of an Item? I know this should be possible because in the NBT-Data of an Item there is a "Thrower" Attribute.
Thanks!
(I think this is related to #774)

## My Code
```javascript
bot.on('playerCollect', function(collector, collected) {
    if (collector.type === 'player' && collected.type === 'object') {
        const rawItem = collected.metadata[6];
        const item = Item.fromNotch(rawItem);
        console.log(item.metadata);
     }
});
```

**Comment by SiebeDW** [comment]
Im pretty sure there is no thrower attribute on dropped items. I can't find it.

**Comment by redstonekasi** [comment]
I can't show you right now, but i'll post a screenshot when I'm home.
________________________________

**Comment by rom1504** [comment]
Reopen if you still need it
