### ISSUE TITLE
Latency always reports 0

### ISSUE THREAD

**Issue by kekmane** [PrismarineJS/mineflayer#850]
i would ask this question on discord but i dont use discord, so how do you check if the server is lagging and then execute an action, this would be very useful to some players on my a server i play on

**Comment by rom1504** [comment]
bot._client.latency

**Comment by enohpsyeoj** [comment]
> bot._client.latency

i mean like lagspikes when the server stops responding completely for like 30 full seconds

**Comment by rom1504** [comment]
can you share the code producing that output ?
that feature should work

**Comment by enohpsyeoj** [comment]
> can you share the code producing that output ?
> that feature should work

```var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
    host: "constantiam.net", // optional
    port: 25565, // optional
    username: oopdetails, // email and password are required only for
    password: oopdetails, // online-mode=true servers
    version: "1.12.2" // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
});
bot.on('chat', function(username, message) {
	setInterval(function(){ 
	console.log(bot._client.latency) 
	if(bot._client.latency != 0) {//ignore this
		setInterval(function(){//ignore this2
			console.log('ok latency went up')//ignore this2
		}, 1000);//ignore this3
	}
	}, 100);
	
});
```

**Comment by enohpsyeoj** [comment]
> can you share the code producing that output ?
> that feature should work

can you tell me how to check for lag spikes tho

**Comment by roblabla** [comment]
@rom1504 latency seems to only be set for server-generated clients and in ping. And it makes sense, the client can't know the latency from `keep_alive`s because it doesn't initiate them.

-------------

If the server *actually* stops responding entirely (e.g. doesn't send keep-alives anymore), the bot will end up disconnecting automatically. In your case, the server is quite clearly still sending keep-alives, so detecting that won't help detect lagspikes anyways.

IIRC, modern minecraft servers send keepalives from a different thread than world events (to avoid players disconnecting when the server is lagging too much). So you'd need to pick a world event that should happen often enough, and debounce based on this. I have no clue what event could be used for this. Maybe have the bot attempt placing a block, and see how long it takes for the server to acknowledge it? Or maybe player movement would work? No clue.

**Comment by enohpsyeoj** [comment]
> @rom1504 latency seems to only be set for server-generated clients and in ping. And it makes sense, the client can't know the latency from `keep_alive`s because it doesn't initiate them.
> 
> If the server _actually_ stops responding entirely (e.g. doesn't send keep-alives anymore), the bot will end up disconnecting automatically. In your case, the server is quite clearly still sending keep-alives, so detecting that won't help detect lagspikes anyways.
> 
> IIRC, modern minecraft servers send keepalives from a different thread than world events (to avoid players disconnecting when the server is lagging too much). So you'd need to pick a world event that should happen often enough, and debounce based on this. I have no clue what event could be used for this. Maybe have the bot attempt placing a block, and see how long it takes for the server to acknowledge it? Or maybe player movement would work? No clue.

i tried time but it was unreliable and i would have to make some kind of complex system for it not to do false positives

**Comment by enohpsyeoj** [comment]
> @rom1504 latency seems to only be set for server-generated clients and in ping. And it makes sense, the client can't know the latency from `keep_alive`s because it doesn't initiate them.
> 
> If the server _actually_ stops responding entirely (e.g. doesn't send keep-alives anymore), the bot will end up disconnecting automatically. In your case, the server is quite clearly still sending keep-alives, so detecting that won't help detect lagspikes anyways.
> 
> IIRC, modern minecraft servers send keepalives from a different thread than world events (to avoid players disconnecting when the server is lagging too much). So you'd need to pick a world event that should happen often enough, and debounce based on this. I have no clue what event could be used for this. Maybe have the bot attempt placing a block, and see how long it takes for the server to acknowledge it? Or maybe player movement would work? No clue.

also if it happens tons of people get kicked, i usually dont but like lots of people

**Comment by enohpsyeoj** [comment]
> @rom1504 latency seems to only be set for server-generated clients and in ping. And it makes sense, the client can't know the latency from `keep_alive`s because it doesn't initiate them.
> 
> If the server _actually_ stops responding entirely (e.g. doesn't send keep-alives anymore), the bot will end up disconnecting automatically. In your case, the server is quite clearly still sending keep-alives, so detecting that won't help detect lagspikes anyways.
> 
> IIRC, modern minecraft servers send keepalives from a different thread than world events (to avoid players disconnecting when the server is lagging too much). So you'd need to pick a world event that should happen often enough, and debounce based on this. I have no clue what event could be used for this. Maybe have the bot attempt placing a block, and see how long it takes for the server to acknowledge it? Or maybe player movement would work? No clue.

how do you check for keepalives

**Comment by kekmane** [comment]
@rom1504 i tried to do it on different servers and it had the same problem, i still want to check keepalives but i dont know how to

**Comment by rom1504** [comment]
Try what roblabla proposed

**Comment by kekmane** [comment]
> Try what roblabla proposed

i dont really get what he proposed, i already tried that and id rather use a more seamless method,

**Comment by kekmane** [comment]
> Try what roblabla proposed

?

**Comment by wvffle** [comment]
You might try to use `bot.player.ping` which is sent by the server to the client. I don't know wether or not it could help you detect lag spikes

**Comment by kekmane** [comment]
> You might try to use `bot.player.ping` which is sent by the server to the client. I don't know wether or not it could help you detect lag spikes

i think that should work, thanks brother

**Comment by kekmane** [comment]
> You might try to use `bot.player.ping` which is sent by the server to the client. I don't know wether or not it could help you detect lag spikes

i tested it and the ping seems to be the same, if youre wondering what my code is its 
```
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "constantiam.net", // optional
  port: 25565,       // optional
  username: "", // email and password are required only for
  password: "",          // online-mode=true servers
  version: "1.12.2"               // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
});
bot.on('login', function() {
	setInterval(function(){   console.log(bot.player.ping) }, 3000);

});
bot.on('error', err => console.log(err))
```

**Comment by wvffle** [comment]
> the ping seems to be the same

You mean that the ping is `0` or is it a constant value like `30` or something?

**Comment by kekmane** [comment]
> > the ping seems to be the same
> 
> You mean that the ping is `0` or is it a constant value like `30` or something?

it slowly goes up until a certain value like 143 or something and it doesnt change after that

**Comment by wvffle** [comment]
Can you show the output?

**Comment by wvffle** [comment]
You can handle `playerUpdated` event and check for your ping. If after, lets say, `player.ping * 1.5` timeout there is no new `playerUpdated` event for your player then you may say, the server is lagging

**Comment by kekmane** [comment]
> You can handle `playerUpdated` event and check for your ping. If after, lets say, `player.ping * 1.5` timeout there is no new `playerUpdated` event for your player then you may say, the server is lagging

that would be hard to implement but it could be possible but is have to brainstorm how to check if it is not responding for a few seconds

**Comment by roblabla** [comment]
@kekmane use a debouncer. https://lodash.com/docs/4.17.15#debounce

**Comment by kekmane** [comment]
> @kekmane use a debouncer. https://lodash.com/docs/4.17.15#debounce

what does it do, i dont really understand the docs

**Comment by roblabla** [comment]
Debounce returns a function. Each time you call the function, it resets a timer. If you don’t call the function before the timer reaches 0, it will call the callback you provided to the debounce function.

**Comment by wvffle** [comment]
This solution should work provided that server sends packet with every ping update

**Comment by kekmane** [comment]
> Debounce returns a function. Each time you call the function, it resets a timer. If you don’t call the function before the timer reaches 0, it will call the callback you provided to the debounce function.

so i definitely think that debounce should work but when i use debounce with time it just doesnt reset the timer for some reason and  even though its calling the function anwys
```
var mineflayer = require('mineflayer');
var fs = require('fs');
var _ = require('lodash');
var replace = require("replace");
var json = require('json');
const clock = require('world-clock')()
const parseJson = require('parse-json');
const math = require('math');  
var switchen = 1

var bot = mineflayer.createBot({
    host: "localhost", // optional
    port: 51131, // optional
    username: "", // email and password are required only for
    password: "", // online-mode=true servers
    version: "1.12.2" // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
});
function run() {
   console.log('abc');
}
var realFunction =
  _.debounce(run, 3500);



bot.on('time', function() {
	realFunction()
console.log(bot.time)
})
``` 
it works with bot.on("chat" but for some reason not with  time

**Comment by wvffle** [comment]
@kekmane so just an event that happens more commonly or bind it to more events like `playerUpdated`, `move` and `entityUpdate` or even `entityMoved`

**Comment by kekmane** [comment]
> @kekmane so just find an event that happens more commonly or bind it to more events like `playerUpdated`, `move`, `entityUpdate`, `entityMoved` or `message`

i would use those  but there is no constant stream dependent on the server of those functions

**Comment by roblabla** [comment]
You can likely trigger those changes yourself from the bot. For instance, `bot.say("/help")` should make the server reply to you, leading to a message event happening. Digging a block should result in an item being spawned. Moving around between two chunks should result in chunk being loaded/unloaded.

**Comment by kekmane** [comment]
> You can likely trigger those changes yourself from the bot. For instance, `bot.say("/help")` should make the server reply to you, leading to a message event happening. Digging a block should result in an item being spawned. Moving around between two chunks should result in chunk being loaded/unloaded.

will try

**Comment by rom1504** [comment]
I'm sure you can figure out how to code this

**Comment by rom1504** [comment]
ok fix it then

**Comment by wvffle** [comment]
>how do i restart the bot when i get timed out

Ask this on the discord/gitter server

Let's focus on the issue

>rom1504 changed the title ~How to ping server aka check if the server is lagging~ Latency always reports 0

What should be `bot._client.latency`? Should it be same as `bot.player.ping`?

**Comment by roblabla** [comment]
@kekmane the point of an issue tracker is to track issues with the library. Not to answer every question. Please use the appropriate communication channel (gitter/discord).

—————

IMO we should just document that bot._client.latency does not exist for proper nmp clients, only for those generated by server. IIRC ping just gives you what the server sends you right? What happens if a server modifies the player tab in a way that removes the user from it? I’ve seen that done (mostly on minigame servers), I suppose ping would return a similarly bogus value (0/null).
