### ISSUE TITLE
bot.whisper wont send

### ISSUE THREAD

**Issue by kekmane** [PrismarineJS/mineflayer#856]
so im trying to trigger a whisper when someone says !bannedplayers and it literally wont work my data in my bannedplayers.txt file is nothing and it still gives me the error,
my code is 
```
			if(message == '!bannedplayers') {
				fs.readFile('C:/Users/La Fam/Desktop/kekbot_rewritten(tm)/players/bannedusers.txt', function read(err, data) {
					if (err) {
					}
					
			bot.whisper(username, data)	
			if(content1 = '') {
				bot.whisper(username, 'no users are currently banned')
			}
			})



        }
```
 the error i get is 
```
C:\node_modules\mineflayer\lib\plugins\chat.js:78
    message.split('\n').forEach((subMessage) => {
            ^

TypeError: message.split is not a function
    at chatWithHeader (C:\node_modules\mineflayer\lib\plugins\chat.js:78:13)
    at Bot.bot.whisper (C:\node_modules\mineflayer\lib\plugins\chat.js:112:5)
    at read (C:\Users\La Fam\Desktop\kekbot_rewritten(tm)\ok.js:142:10)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by rom1504** [comment]
Message needs to be a string
Use JSON.stringify to serialize it

**Comment by wvffle** [comment]
@kekmane Either specify the encoding or use `data.toString()`. 

`fs.readFile` and `fs.readFileSync` returns raw `Buffer` instance if no encoding specified

https://nodejs.org/api/all.html#all_fs_readfile_file_options_callback

**Comment by rom1504** [comment]
Unclear issue, reopen if you have something specific that looks like a bug
