### ISSUE TITLE
Inconsistent event names

### ISSUE THREAD

**Issue by wvffle** [PrismarineJS/mineflayer#859]
Right now we have events like `entityUpdate` and `bossBarUpdated`
which may be a little bit confusing and nonintuitive for newcomers

I think that most of the events should be in present and not past time

Changing that would be a breaking change for already existing projects but would make event names more consistent

**Comment by roblabla** [comment]
To avoid breaking changes, we could introduce aliases to keep the old names around.

**Comment by rom1504** [comment]
I don't really think it's worth it. Especially now that we have typescript definition for autocomplete
