### ISSUE TITLE
How do I detect stuff when a loop is going on?

### ISSUE THREAD

**Issue by Miniller** [PrismarineJS/mineflayer#862]
So basically, there is a while loop. So it's going well. But if I write something else, it won't detect it. I can't stop the loop.
So how do I make it so the loop is going but everything else works too

**Comment by rom1504** [comment]
Code, what are you trying to do, what didn't work

**Comment by wvffle** [comment]
It's javascript/node related question not a mineflayer one.

**Comment by rom1504** [comment]
Pretty sure he's asking about mineflayer, even if he's not really asking in an useful way.
Let's give him a chance to explain

**Comment by 1by** [comment]
@Miniller if you can elaborate i might be able to help you

**Comment by Miniller** [comment]
I asked this 20 days ago and already fixed it. I didn't have any time to write here.
