### ISSUE TITLE
Crash after some time connecting to hypixel.net

### ISSUE THREAD

**Issue by MrZillaGold** [PrismarineJS/mineflayer#870]
## Versions
 - mineflayer: 2.9.6
 - server: ??? Hypixel

## Detailed description of a problem
After some connection to the Hypixel.net server, the script crashes, I assume that this happens during automatic teleportation to the AFK server.

https://pastebin.com/8ye6HKdn

1.8: https://i.imgur.com/txnoUie.png
1.12: https://i.imgur.com/APTDLDj.png

**Comment by MrZillaGold** [comment]
I got debug along with error https://pastebin.com/8ye6HKdn

**Comment by wvffle** [comment]
Could you do a ```console.log(blockEntity[`Text${i}`])``` before line 45 in `lib/plugins/blocks.js`?

**Comment by wvffle** [comment]
#871 Should fix the issue for 1.12. Don't know about 1.8
