### ISSUE TITLE
bot.player non existent now?

### ISSUE THREAD

**Issue by HelloImCamden** [PrismarineJS/mineflayer#877]
## Versions
 - mineflayer: 2.9.6
 - server: paper
 - node: v10.10.0

## Detailed description of a problem
I've been working on a rewrite of one of my bots. I noticed when tweaking a few things that I was randomly finding undefined objects. For some reason bot.player is constantly being considered as undefined even though the bot is connected. Not sure what changed and maybe I'm just missing something, but I have no ability to get things like uuid as `bot.uuid` also throws as undefined even though the account is connected to the server.
## Current code
```js
	const bot = mineflayer.createBot({
		host: client.config.server.host, 
		version: client.config.server.version,
		username: credentials.username,
		password: credentials.password, 
		verbose: true,
	});

	bot.on('login', () => {
		console.log(bot.username);
		console.log(bot.player);
	});
```

## Expected behavior
I should receive an object called bot.player detailing the username, uuid, position etc

**Comment by wvffle** [comment]
Check if this works for you:

```js
bot.on('playerJoined', (player) => {
  if (player.username !== bot.username) return
  console.log(bot.player === player, bot.player, player)
})
```

**Comment by HelloImCamden** [comment]
Output is 

```js
false undefined { username: 'PhoneCall',
  ping: 0,
  uuid: 'd19d6dc6-8aa4-431f-87dd-9215faee5224',
  displayName:
   ChatMessage {
     json: { text: '', extra: [Array] },
     text: '',
     extra: [ [ChatMessage] ],
     bold: undefined,
     italic: undefined,
     underlined: undefined,
     strikethrough: undefined,
     obfuscated: undefined,
     color: undefined } }
```

**Comment by wvffle** [comment]
Try to add a timeout of 1ms before console.log
