### ISSUE TITLE
Run the rbot 

### ISSUE THREAD

**Issue by Script-Book** [PrismarineJS/mineflayer#878]
Hello, I have a question about rbot how to run it?

**Comment by rom1504** [comment]
What failed when you followed the readme ?

**Comment by Script-Book** [comment]
I got lost in the usage part .

**Comment by Script-Book** [comment]
Exactly in it 
Usage
If you specify a master the bot will only obey to him
rbot <host> <port> <name> <password> [<master>]
If you cloned the repo, run node rbot.js instead.

**Comment by Script-Book** [comment]
So how to  specify a master and clone the repo ?

**Comment by rom1504** [comment]
https://github.com/rom1504/rbot#installation read this a few times
