### ISSUE TITLE
Improve auth error

### ISSUE THREAD

**Issue by MrZillaGold** [PrismarineJS/mineflayer#880]
If we try to use html tags as user authorization data (email: `<script>alert(document.cookie)</script>@gmail.com` and/or password: `<script>alert(document.cookie)</script>`), we get an error:
https://imgur.com/gL8iE34
![](https://i.imgur.com/gL8iE34.png)

I understand that it is associated with another library, but it has not been updated for more than 2 years and I think the author is no longer developing it.
Can you fix this problem at your library level?

**Comment by rom1504** [comment]
Actually the error your got just mean the Mojang server banned you. Try
from another ip

**Comment by MrZillaGold** [comment]
Mojang did not ban this ip address, I use the data to connect:

<script>alert(document.cookie)</script>@gmail.com
<script>alert(document.cookie)</script>

If using normal data: 
example@example.com
12345678
Connection is normal.

**Comment by rom1504** [comment]
Ok well I can already tell you that Mojang thing is *not* coded in js and
does not return html, so your attempt at injection won't have any effect.

**Comment by MrZillaGold** [comment]
It’s just that with my react application, users can connect to Minecraft servers through Mineflayer. During authorization, they can specify absolutely any data. Why not catch this error and not display a library error? This would allow it to be caught using `.on('error')`

**Comment by MrZillaGold** [comment]
In fact, the user can use as a password: `<script>alert(document.cookie)</script>` . But if we try to log in with such data through the library, we get an error.
![](https://imgur.com/FN0BOAZ)

**Comment by rom1504** [comment]
Sounds like something that should be handled in your react application.

Sounds like there is a bug in node-yggdrasil indeed, but the fix is not to
emit an error, the fix is to handle that kind of password properly.

Same on your side.

**Comment by wvffle** [comment]
It's possible that mojang returns an error page because you use forbidden characters in email. Your app should verify email address and/or strip html tags (or any other characters that arent supposed to be in an email)

**Comment by MrZillaGold** [comment]
With other tags, everything is fine. But still, why not handle this error on the library side and output it to .on ("error")?

**Comment by wvffle** [comment]
In my opinion we should throw something like `Authentication server error`. JSON error doesn't say anything useful for a regular user and may be hard to understand.
