### ISSUE TITLE
How to Control Bot Chatting through terminal/cmd

### ISSUE THREAD

**Issue by MaxProg2** [PrismarineJS/mineflayer#886]
const mineflayer = require('mineflayer'); //you should "npm i mineflayer" before starting and install nodejs

const connect = {
    'host': 'mc.comugamers.com', //ip
    'port': 25565, //port
    'version': '1.8' //current max version is 1.12.2 for mineflayer
}

const botCount = 0 //how many bots should join

console.log('Starting bots...');//says in console that the bots are starting

for(let i = 0; i <= botCount; i++) {
    let genBot = mineflayer.createBot({
        'host': connect.host,
        'port': connect.port,
        'version': connect.version,
        'username': 'BotMAX3'
    })
    genBot.on('login', () => {
        //console.log("'"+genBot.username+ "' logged in") //says the name of the bot that has logged in in console (not used tho lol)
        console.log('A bot joined: '+i)
genBot.chat('/login BOT');
    })
}

Thats my Code, i would want to make it chat what i write through the terminal/cmd

**Comment by rom1504** [comment]
See this example
https://github.com/PrismarineJS/mineflayer/blob/master/examples/repl.js
