### ISSUE TITLE
I have a question about selecting a game from lobby

### ISSUE THREAD

**Issue by MaxProg2** [PrismarineJS/mineflayer#887]
well in the server, when u click the modalities item which is a compass, and it opens a chest with items who are different modalities, how can i make my bot just select the item for slot 13 which is skywars

**Comment by plexigras** [comment]
you can look into the inventory.js file or try around with `bot.clickWindow(slot, mouseButton, mode, cb)`

**Comment by MaxProg2** [comment]
yes i fixed it but, how would i do to right click on the Compass which is the item that opens the Chest with the modalities, cause if i use bot.activateItem() it just makes him disappear after 3 seconds.
