### ISSUE TITLE
i have a question, when i install a plugin

### ISSUE THREAD

**Issue by MaxProg2** [PrismarineJS/mineflayer#888]
do i have to install a plugin? and if i do have to, how do i do? do i just open terminal and write "npm mineflayer-navigate" and it installs? or do i have to open the mineflayer folder and install it there?

or either its already has the plugins?

**Comment by wvffle** [comment]
```
npm install mineflayer-navigate
```

And then add it in the code:
```js
// require mineflayer and other stuff
const navigatePlugin = require('mineflayer-navigate')(mineflayer);

// create your bot
const bot = mineflayer.createBot(...)

navigatePlugin(bot);
```
