### ISSUE TITLE
my bot wont find block

### ISSUE THREAD

**Issue by MaxProg2** [PrismarineJS/mineflayer#890]
i wrote a code to make my bot find block in sync, but my bot is not moving at all, i tryed from putting the example code, to changing to an minecraft server jar

**Comment by rom1504** [comment]
Can you provide the full code and full error ?

**Comment by MaxProg2** [comment]
const mineflayer = require('mineflayer');
const navigatePlugin = require('mineflayer-navigate')(mineflayer);
var blockFinderPlugin = require('mineflayer-blockfinder')(mineflayer);
const bot = mineflayer.createBot({ 
  username: 'SurvivalBot',
  host: 'localhost',
  port: 39307,
  version: '1.12.2',
});
// Enable Plugin
navigatePlugin(bot);
bot.loadPlugin(blockFinderPlugin);
// optional configuration

bot.once('spawn', function() {
  bot.findBlockSync({
    point: bot.entity.position,
    matching: 17,
    maxDistance: 256,
    count: 1,
  })
})

**Comment by rom1504** [comment]
What is the error ?

As discussed on discord, I think you should learn some basics first. Did
you start working on that already ?

**Comment by MaxProg2** [comment]
yes, but i mean it gives no error, it just does not act at all, and when i kill him bot chats that he found a diamond block then leaves, it gives no error at console, its weird

**Comment by rom1504** [comment]
Yes that's normal your code is not doing anything with the block you
retrieved from find block

**Comment by MaxProg2** [comment]
const mineflayer = require('mineflayer');  --REQUIRES MODULE
const navigatePlugin = require('mineflayer-navigate')(mineflayer);
var blockFinderPlugin = require('mineflayer-blockfinder')(mineflayer);
const bot = mineflayer.createBot({   --CREATES BOT WITH OPTIONS
username: 'SurvivalBot',
host: 'localhost',
port: 39307,
version: '1.12.2',
});
// Enable Plugin
navigatePlugin(bot); --ENABLES PLUGIN IN BOT
bot.loadPlugin(blockFinderPlugin);
// optional configuration

bot.once('spawn', function() { -- BOT ON SPAWN 
bot.findBlockSync({ -- FINDS BLOCK SYNCHRONOUSLY
point: bot.entity.position, -- POSITION OF WHERE TO START
matching: 17, -- BLOCK ID
maxDistance: 256, --MAX BLOCKS DISTANCE
count: 1, --HOW MUCH BLOCKS U WANT TO FIND OF THE SAME ID
}) -- END FINDBLOCK
}) --END ONCE SPAWN

**Comment by rom1504** [comment]
Ok, so this code will find a block. Is that what you want it to do ?

**Comment by MaxProg2** [comment]
Yes

**Comment by rom1504** [comment]
Issue solved then ?

**Comment by wvffle** [comment]
Seems to be resolved
