### ISSUE TITLE
Join server with menu

### ISSUE THREAD

**Issue by car1ot** [PrismarineJS/mineflayer#892]
`bot.on('windowOpen', (windw) => {`
`	// Called when client send command /servers`
`	bot.clickWindow(5, 0, 0);`
` });`

`bot.on('login', () => {
	setTimeout(() => {
		bot.chat("/servers");
	}, 2000)
})`

After clicking on slot 5 (this is melon_block item) from lobby in vanilla, user connect to another server. In mineflayer it dont work

**Comment by rom1504** [comment]
What do you expect to happen ?

**Comment by alexanderbkl** [comment]
Try iterating through window
