### ISSUE TITLE
'Possible EventEmitter memory leak' when breaking blocks

### ISSUE THREAD

**Issue by period** [PrismarineJS/mineflayer#893]
After breaking blocks continuously for around 30 minutes, 

(node:6116) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 blockUpdate:(-12, 100, 21) listeners added. Use emitter.setMaxListeners() to increase limit

is raised.

The blocks being broken are the same 10 blocks each time in a cobblestone generator.

**Comment by rom1504** [comment]
Sounds like an error in your code where you are listening many times the
same event. What is your code ?

**Comment by period** [comment]
function dig() {
        if (bot.targetDigBlock) return console.log("Failed dig and digging already");
        var locatedBlock = false;
        for (var i = 2; i < 8; i++) {
            if (locatedBlock == true) continue;
            bot.look(sbBot.generatorPos.yaw, sbBot.generatorPos.pitch, true);
            var target = bot.blockAt(bot.entity.position.offset(0, i, 0));
            if (target && bot.canDigBlock(target) && target.name.includes("cobblestone")) {
                locatedBlock = true;
                bot.dig(target, digDone);
            }
        }
        if (locatedBlock == false) {
            setTimeout(() => {
                digDone();
            }, 250);
        }
    }
    function digDone() {
        if (state == "MINING") return dig();
    }

**Comment by rom1504** [comment]
You are trying to dig several blocks at the same time which doesn't make
sense.
You need to use the dig callback properly
