### ISSUE TITLE
Mushroom bounding boxes not working properly; change boundingBox property in blocks.json

### ISSUE THREAD

**Issue by Venrilder** [PrismarineJS/mineflayer#894]
Mushrooms are currently treated as solid blocks
Reproducing:
Command a bot to move along a path that requires going through mushrooms. The bot will jump onto and begin hovering over them instead of moving through them.
Fix:
https://github.com/kamesa7/CoryBot/commit/66597e4a525f87a347bc503bc8e97c6b6122a6f5#diff-15b5f51b965cd041f2ffcb455cbc9daf
Seems to work fine for me after those changes.

**Comment by rom1504** [comment]
Feel free to do a PR on minecraft data project

**Comment by rom1504** [comment]
Why close ? Was it fixed ?

**Comment by wvffle** [comment]
Seems like it's unrelated to mineflayer but related to minecraft-data
