### ISSUE TITLE
Obfuscation maps from 19W36A

### ISSUE THREAD

**Issue by lela-null** [PrismarineJS/mineflayer#897]
I know that 1.13 and 1.14 are not ready but I am wanting to know if the obfuscation maps released in 1.15 will be able to help in moving this project along?

**Comment by rom1504** [comment]
No I don't see how.
What is missing for updates in this project is not new knowledge or new
tools but simply someone who is both competent enough and have a few hours
to fix the few things needed for update.
Currently there is two groups of people interested in this project :
1. Me, and some contributors who have the skills but don't have the time to
work on this
2. Lot of people who are usually very young and do not have the skills to
do any contributions (see discord server)

However I have time to guide whoever wants to work on this, if you do, or
anyone else do, I could explain what needs to be done and help along the
way.

**Comment by wvffle** [comment]
@rom1504 Shouldn't we create a roadmap or some todo for 1.13+ so anyone who wants to contribute on that would know what to do? Github projects seem like a good tool for that.

**Comment by wvffle** [comment]
Only thing that comes to my mind in which the obfuscation maps would help is block sizes for #228 if that info is even deobfuscated
