### ISSUE TITLE
Does supplying 'stream' make the 'version' parameter ignored?

### ISSUE THREAD

**Issue by period** [PrismarineJS/mineflayer#898]
When using a socks proxy by supplying stream, like this:

```
mineflayer.createBot({
stream: Socks.createConnection({ // socks stuff }),
username: "",
password: "",
version: "1.12.2"
});
```

I am getting weird mapping errors relating to protodef upon login. In all the times I've used mineflayer, I have found this down to being due to version differences. When not using a socks proxy, the bot connects and works just fine. The socks proxy in question has been confirmed as working through curl.

Does supplying a 'stream' cause the 'version' parameter to be ignored? If so, how would I go about forcing a specific version.

Thanks!

**Comment by rom1504** [comment]
No it doesn't.
However most likely your proxy is not providing correctly a tcp stream.
What kind of proxy are you using?

**Comment by period** [comment]
SOCKS5

**Comment by rom1504** [comment]
Ok what's your full code ?

**Comment by period** [comment]
```
const Socks = require("socks5-client");
const mineflayer = require("mineflayer");
const navigatePlugin = require("mineflayer-navigate")(mineflayer);
const tokens = require("prismarine-tokens");
const Vec3 = require("vec3")

var mfOptions = {
    stream: Socks.createConnection({
        host: "",
        port: 25565,
        socksHost: "",
        socksPort: 1080
    }),
    username: "",
    password: "",
    version: "1.12.2",
};
tokens.use(mfOptions, function (err, opts) {
    var bot = mineflayer.createBot(opts);
    navigatePlugin(bot);

    bot.on("error", function (error) {
        console.log(error);
    })
    bot.on("login", function () {
        console.log("Connected!");
    });
});
```

The error(s): https://paste.ee/p/utrnE

**Comment by rom1504** [comment]
Can you try something like
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js
instead ?

**Comment by period** [comment]
As in, my mfOptions should become what's between line 12 and 36 or...?

**Comment by rom1504** [comment]
Yes

**Comment by period** [comment]
Works. Thank you very much!

ps: do you have a paypal for donations?

**Comment by rom1504** [comment]
Yes, https://paypal.me/rom1504

**Comment by period** [comment]
Sent some. Thanks again.

**Comment by rom1504** [comment]
You're welcome, thanks for the donation!
