### ISSUE TITLE
Chat event gives username that does not belong to any player

### ISSUE THREAD

**Issue by creepinson** [PrismarineJS/mineflayer#899]
## Versions
 - mineflayer: 2.10.0
 - server: vanilla/spigot/paper 1.8, bungeecord with viaversion up to 1.15
 - node: 10.18.1

## Detailed description of a question
I'm not sure what could be causing this to happen on my server, but either way I don't know how to get it so that anytime the bot recieves a chat message without a username in it, it doesn't crash.

Chat message: come
Chat message: found path. I can get there in 2 moves.
Chat message: Please do not spam in chat
C:\Users\thebo\pathfinding\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'entity' of undefined

Here is my code for the chat message:
```javascript
bot.on('chat', (oldUsername, message) => {
        var username = oldUsername;
        // navigate to whoever talks
        console.log("Chat message: " + message);
        if (message.split(">")[1] != null) {
            username = message.split(">")[0];
            username = username.substr(message.indexOf(' ') - 1);
        }
        if (username != undefined && username != "") { // THIS SHOULD BE WORKING FINE
            if (username === bot.username) return;
            const target = bot.players[username].entity;
            if (message === 'come') {
                bot.navigate.to(target.position);
            } else if (message.startsWith("follow")) {
                var followTarget = bot.players[message.substring(message.indexOf("follow") + 2)];
                if (followTarget != null) {
                    bot.navigate.to(followTarget.entity.position);
                }
            } else if (message === 'stop') {
                bot.navigate.stop();
            }
        }

    });

**Comment by creepinson** [comment]
Also, when i used the chat add pattern instead of what im doing here,
it just says not a function, and when I put inside inject_allowed it doesn't do anything at all...

**Comment by wvffle** [comment]
Have you tried to log the username? Also keep in mind that servers can use custom names in chat. I remember that on some servers there were `/nick` commands or something like that. Maybe the guy who wrote the message had changed nickname?

There is also a possibility that it was a vanished admin considering the server uses some plugin that makes all clients think that vanished player is offline.

In my opinion, the condition in your code should be something like:

```js
if (username in bot.players) {
```

**Comment by rom1504** [comment]
not enough info
