### ISSUE TITLE
crouch and uncrouch are not correctly implemented

### ISSUE THREAD

**Issue by IdanHo** [PrismarineJS/mineflayer#904]
The event listeners at:
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/entities.js#L122
and
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/entities.js#L126

listen for events that are not emitted anywhere.

**Comment by rom1504** [comment]
it's not "unused legacy code", it's a bug

**Comment by Karang** [comment]
This can be implemented by parsing the metadata correctly https://wiki.vg/Entity_metadata#Entity
