### ISSUE TITLE
legacy.craftlandia.com.br (1.5.2 - 1.12.2)

### ISSUE THREAD

**Issue by Escanor2019** [PrismarineJS/mineflayer#911]
this server has 1 viaversion to leave the server 1.5.2 .1.12.2 but I can’t log in despite being able to log in the 1.8.8 native server them chrons.craftlandia.com.br (1.8.8 - 1.15.2)

the script dont run
![image](https://user-images.githubusercontent.com/47899748/74610267-74219900-50d0-11ea-8d0f-bd1a249c6834.png)

i try all versions
look:
```js
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "legacy.craftlandia.com.br", // optional
  port: 25565,       // optional
  username: "TATATAT", // email and password are required only for
  version: "1.11.1"             // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
});

bot.on('chat', function(username, message) {
  if (username === bot.username) return;
  bot.chat(message);
});
bot.on('error', err => console.log(err))
```

**Comment by Escanor2019** [comment]
The plugin they let to accept new versions of minecraft is called CraftlandiaProtocolSupport created by schevchik in version 1.5 of minecraft.

In the case of chronos it is possible using viaversion.

It's a bug in the script since I can log in normally using the minecraft client.

**Comment by wvffle** [comment]
![](https://0x0.st/iHei.png)
I can successfully connect to the server without any errors on `1.12.2`. Be sure to pass `1.12.2` as a version number and not `1.12`

**Comment by Escanor2019** [comment]
Look
![image](https://user-images.githubusercontent.com/47899748/74612075-ccf92d80-50e0-11ea-93fe-9faceac8b642.png)

**Comment by wvffle** [comment]
I can't really see what's there. Have you specified the version in the example?

**Comment by Escanor2019** [comment]
@wvffle 

look:
![image](https://user-images.githubusercontent.com/47899748/74612350-5ad61800-50e3-11ea-9ade-657a2a9c9396.png)
look2:
![image](https://user-images.githubusercontent.com/47899748/74612352-6295bc80-50e3-11ea-998a-ae01bc4c9a43.png)

**Comment by wvffle** [comment]
There may be limit of 1 connection per ip address. Try to add [`kicked`](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#kicked-reason-loggedin) event.

**Comment by Escanor2019** [comment]
@wvffle ok i got it

![image](https://user-images.githubusercontent.com/47899748/74615414-4273f680-50ff-11ea-87be-c2ea4f2308b8.png)

how can I loop asynchronously to create bulk bots for specific commands and movements on the server?
can i earn 1 pvp against players? the server has 1 event called 'gladiator' every saturday where each clan with a maximum of 20 players fight each other for money and tags.

I could create 5 clans with 20 bots each and order the pvp since the items are enchanted and don't require a lot of mechanics.

**Comment by Escanor2019** [comment]
my current code

<code>
const mineflayer = require('mineflayer')

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node ansi.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}






for(var i = 1;i <= 6;i++) {
setInterval(function() {},6000);
(async () => {
   

const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: "HidraShield" + i,
  password: process.argv[5],
  version: "1.12.2"
})

console.log("HidraShield" + i)

bot.on('message', (message) => {
  console.log(message.toAnsi())
  bot.chat("/register 123456");
  bot.chat("/login 123456");
  bot.chat("/tell bbatemanbr2 eae");
  function intervalFunc() {
    bot.chat("me da 15k para falar no all");
  }
  setInterval(intervalFunc,3000);
  
})



})();
}
<code>

**Comment by Escanor2019** [comment]
![image](https://user-images.githubusercontent.com/47899748/74615484-03927080-5100-11ea-80e6-7c8a17725368.png)

**Comment by wvffle** [comment]
Either ask on the [discord server](https://discordapp.com/invite/GsEFRM8)/gitter or create a new issue as the original one is resolved
