### ISSUE TITLE
how can I keep bots stopped and schedule out-of-sync tasks?

### ISSUE THREAD

**Issue by Escanor2019** [PrismarineJS/mineflayer#912]
i want to create 1 pvp bot army in my clan in legacy.craftlandia.com.br for the war that always has sat 8:00 pm on between 500 players with each clan with 25 players. since i don't have many friends faithful, active and you can't trust strange beginners.

I'm looking for keywords "schedule" "task" "async" "multi" "alive" and I haven't found it in any github file. could you show me how i can maintain connections with 3 players asynchronous with scheduled responses?

look my example 
you can see in the code my attempts to schedule and execute asynchronously.
only console.log("message") works with scheduled and asynchronous task
![image](https://user-images.githubusercontent.com/47899748/74621410-a3a9c300-511b-11ea-8f62-16ba6ef71edf.png)

it doesn’t schedule and it doesn’t have asynchrony, you can only schedule console.log ("message")

**Comment by wvffle** [comment]
You already received an answer from one of our discord members ![](https://0x0.st/iXoB.png
)

Listen to `error` and `kicked` events if you want to see why the bot isn't on the server anymore

**Comment by Escanor2019** [comment]
I wasted time seeing a ready solution.

If I had started this in C and using the minecraft protocols wiki I would have already finished.

you are dumber than 1 monkey

I don't know why you program, but you have in the future as any type of developer.

You don't create products and solutions, you create problems with a bunch of monkey followers.

**Comment by rom1504** [comment]
@Escanor2019 is now blocked due to rudeness.
