### ISSUE TITLE
Chunks not loading/bot can't move

### ISSUE THREAD

**Issue by Gamer745** [PrismarineJS/mineflayer#914]
## Versions
 - mineflayer: 2.11.0
 - server: spigot 1.7.10 (With join versions up to 1.8.9)
 - node: 12.14.0

I'm going to put this as a question as I assume this wouldn't be supported, as its a old server/game version but I hope I can at least find a fix for this use case,  since I really need it on this server. 

When the bot joins basically any other server other than the main one I need it to, it can't load chunks or move. It can turn its head but if it walks its basically just frozen. If I break blocks under it, then it will float. It can send chat messages and commands.

The reason I say its not loading chunks is because when I first log in, or go to spawn on the server (on a actual client) my screen is just white until I press something like move or my mouse then it all appears. Maybe its detecting some packet when it logs in that is not a normal vanilla client?

**Comment by wvffle** [comment]
Mineflayer tries to imitate the vanilla client so I doubt it's a packet stuff.
I guess someone could debug this if they had some spare time.

I advise you to ask this question in our [discord server](https://discordapp.com/invite/GsEFRM8). There are a lot of people willing to help you.
Be aware that we recently enabled some security settings, so if you are a new discord user then you may be required to wait a couple of hours before joining.

**Comment by Gamer745** [comment]
Aight I had all the code in the login function, I guess this caused a overload or something because after a bit I realized the bot would disconnect. Accidentally had it there, fixed and and now it can move and stuff, weird how its only on the one server.
