### ISSUE TITLE
bot.look is not a function

### ISSUE THREAD

**Issue by SWEDCODER** [PrismarineJS/mineflayer#918]
## Versions
 - mineflayer: 2.11.0
 - server: paper
 - node: 13

## Detailed description of a problem
When I use a function of bot (bot.look() in this case), this throws a TypeError (bot.look is not a function)

## Context code (I don't think it comes from this snippet the full code is lower)
```js
bot.on("chat", (username, message) =>{
				// if(username === bot.username) return;
				let date_ob = new Date();
				let date = ("0" + date_ob.getDate()).slice(-2);
				let day = date_ob.getDay();
				let month = ("0" + (date_ob.getMonth() + 1)).slice(-2);
				let year = date_ob.getFullYear();
				let hours = date_ob.getHours();
				let minutes = date_ob.getMinutes();
				let seconds = date_ob.getSeconds();
				let curMes = day + "-" + month + "-" + year + " " + hours + ":" + minutes + " <" + username + ">" + message;
				console.log(curMes);
				fs.appendFile('logmess.txt', curMes + "\n" , function (err) {
						if (err) throw err;
						console.log('Saved!');
			});
			if(message === "!start"){
				bot.look(bot.entity.yaw + 180, bot.entity.pitch);
					
			}
				
			})
```

## Full Code
The full code is available here because I don't think the error comes from the above context code since it worked without the if statement https://github.com/SWEDCODER/pofd-proxy/blob/master/pofdPublic.js

## Expected behavior
I expected the bot to rotate its head 180 degrees

## Additional context
It's a proxy bot which transfers packets from a fake player connected on a remote server to a localhost server and vice-versa, I am actually trying to make it a chatbot while being able to play on it

**Comment by rom1504** [comment]
What is the full error ?

**Comment by SWEDCODER** [comment]
Thanks for the quick response, you're a boss! 
The full log is here: https://pastebin.com/reLGJ9zf

**Comment by rom1504** [comment]
The reason you got this error is you disabled the physics plugin. bot.look
is part of this plugin. You need to enable it.

**Comment by SWEDCODER** [comment]
Oh god, okay, I'm such an idiot, thank you I'm going to try this, if it works I'll close the issue

**Comment by SWEDCODER** [comment]
Oh, activating physics actually make the game lag so much, I remember why now. Thank you so much it works now, I'm closing this
