### ISSUE TITLE
Look/LookAt parameterizable velocity/duration

### ISSUE THREAD

**Issue by joaosilvalopes** [PrismarineJS/mineflayer#919]
## Is your feature request related to a problem? Please describe.
I would like to have parameterizable (velocity(rad/ms) or duration(ms)) for the look and lookAt functions.

## Describe the solution you'd like
I suggest the following api:
```
bot.look(yawn, pitch, { velocity: number, duration: number });
```

This way we could maintain backwards compatibility with the previous functionality (if the third parameter is falsy use the current velocity, if it is true look instantly, if it is an object use the velocity/duration given)

## Describe alternatives you've considered
We could also move this new functionality into a new method: 
```
bot.lookAtGradually(yawn, pitch, { velocity: number, duration: number });
```

**Comment by rom1504** [comment]
Sounds good. I'd accept a PR on this.

**Comment by joaosilvalopes** [comment]
I have a friend @pedrodacosta, that will open a pr on this, will review it later :+1:

**Comment by Karang** [comment]
Currently, the look update is always instantaneous (from the bot point of view), the delay is only there for other clients. The speed is already parametrizable by changing `bot.physics.yawSpeed` (default is 0.3 rad/s). Do you want to change this (apparent) delay at each call or do you want to really add a delay for the bot (so it would not be instantaneous).
Can you tell us a bit more about the application of this feature (so we could propose something that fits better) ?

**Comment by rom1504** [comment]
sounds like this isn't needed
