### ISSUE TITLE
Optimize digging

### ISSUE THREAD

**Issue by wvffle** [PrismarineJS/mineflayer#923]
## Is your feature request related to a problem?
There are a limited number of event listeners so using one listener per block whilst digging is not optimal

## Describe the solution you'd like
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/digging.js#L51-L64 this should be one global handler and checked against some location cache object

## Additional context
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/digging.js#L29

**Comment by rom1504** [comment]
What problem do you want to solve by changing this behavior ?

**Comment by wvffle** [comment]
Sometimes it can exceed the limit of 11 max listeners. Also applying a lot of listeners may be slower than using one and checking against a cache object. This should be at least benchmarked.

**Comment by rom1504** [comment]
Can't see why. Read the implementation of event listener, I think you'll
understand better what it's doing

**Comment by Karang** [comment]
Is is still an issue? I can't see why either. Anyway, digging is kind of slow process due to the game mechanics (one block at a time) so I'm not sure why this would need to be optimized.

**Comment by rom1504** [comment]
yeah, not an issue
