### ISSUE TITLE
Click on a entity

### ISSUE THREAD

**Issue by Systemwartung** [PrismarineJS/mineflayer#926]
Hey,

I have a question I have made a BOT. The function is that he clicks on an NPC but he clicks on a hologram how can I define which entity I mean?

Please give me a reason

**Comment by wvffle** [comment]
Duplicate of #925
Duplicate of #826 

> You can get it from an event or from `bot.entities` or `bot.players[username].entity`.

**Comment by Systemwartung** [comment]
yes but how do I define which entity I mean you can give me an example
