### ISSUE TITLE
join on Server = crash

### ISSUE THREAD

**Issue by Systemwartung** [PrismarineJS/mineflayer#927]
I have a problem when my BOT is clicked on an NPC and moved to another server, the bot crashes and goes offline

**Comment by rom1504** [comment]
Can you give less information please ? We are a bit overwhelmed by so much
context

**Comment by Systemwartung** [comment]
there are bungeecord systems and when my bot enters a sub-server it stops

**Comment by wvffle** [comment]
The issue template is there for reason. We should close every issue that does not follow them unless they're descriptive enough.

**Comment by Systemwartung** [comment]
OK Sorry If my bot joins on a Server and there are NPC´s he click on an npc and the bot will be send to another Server but when he send to this server he crashs I can join on the Lobby but i cant join on an sub-server becaus the bot crashes

**Comment by rom1504** [comment]
Here is the template https://github.com/PrismarineJS/mineflayer/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Please provide all these information
