### ISSUE TITLE
entity ID

### ISSUE THREAD

**Issue by Systemwartung** [PrismarineJS/mineflayer#928]
who I can find out a entity ID from an npc

**Comment by rom1504** [comment]
entity.id

**Comment by Systemwartung** [comment]
yes but if i want to define it i have to know the id how do i find it out

**Comment by Systemwartung** [comment]
With mcpd

**Comment by wvffle** [comment]
what? You don't need mcpd nor defining an entity... Simply use the id or the entity object. First of all ask on discord how to do the thing you want to do... Don't guess the solution to the problem

**Comment by rom1504** [comment]
Open an issue by following the issue template and providing all the details after trying on your side for at least 30min.
