### ISSUE TITLE
Adding an option enable IP-Forwarding and connect to a port of a bungeecord server without having to use a localhost to redirect bot.

### ISSUE THREAD

**Issue by ItsJokerz** [PrismarineJS/mineflayer#931]
## Is your feature request related to a problem? Please describe.
Adding an option enable IP-Forwarding and connect to a port of a bungeecord server without having to use a localhost to redirect bot, so I can see kick errors and all that.

Thanks for your time.

**Comment by rom1504** [comment]
Can you try to explain what you actually want to do ?
I didn't understand what feature you want

**Comment by ItsJokerz** [comment]
A way to "bypass" the message that it appears when you try to connect the bot to a server port directly: "If you wish to use IP forwarding, please enable it in your BungeeCord config as well!", it would be good so I can send a bot directly to a gamemode instead of the bungeecord proxy to get the info I want of my gamemode since by default, I have to setup a bungeecord proxy with a custom plugin to redirect bot to the port I want. IDK if you understood the whole thing but yeah.

**Comment by wvffle** [comment]
This message seems like a bungeecord doesn't allow connecting in a way you want your bot to connect. Check your bungeecord config.

**Comment by kadenscott** [comment]
Yeah this isn't something mineflayer is capable of fixing. It's a server-side message. If the Bungeecord network is setup properly, this message will appear because the proxy has to handle the authentication of accounts.
