### ISSUE TITLE
can't fishing

### ISSUE THREAD

**Issue by hutu13879513663** [PrismarineJS/mineflayer#932]
## Versions
 - mineflayer: 2.11.0
 - server: vanilla 1.11.2
 - node: v12.16.1

## Detailed description of a problem
收杆不正常
Abnormal closing  --Translated by Google

## Current code
the \examples\fisherman.js 127.3.3.3 25565

## Expected behavior
每次鱼咬钩的时候都收杆。
Stop every time a fish bites.  --Translated by Google

## Additional context
鱼咬钩的时候不收竿，偶尔才会收杆。
The fish does not close the rod when it bites, and occasionally closes the rod.  --Translated by Google

**Comment by rom1504** [comment]
Do you get any error ?
Can you try to enable debug mode (see readme as to how) and report what are
the packets received/sent at this time ?

**Comment by hutu13879513663** [comment]
think for you reply, i did't get error,i will try to enable debug mode and try it again.

**Comment by hutu13879513663** [comment]
the debug message is too big,how can i send it to there.

**Comment by hutu13879513663** [comment]
![the prt sc](https://user-images.githubusercontent.com/6470932/77846604-c8e52300-71e9-11ea-94a3-f35d8feb4f51.png)

**Comment by hutu13879513663** [comment]
[thelog.txt](https://github.com/PrismarineJS/mineflayer/files/4398638/thelog.txt)

**Comment by hutu13879513663** [comment]
you can see that
https://github.com/PrismarineJS/mineflayer/pull/937
