### ISSUE TITLE
Mineflayer unknown transaction confirmation

### ISSUE THREAD

**Issue by ErrorMessage404** [PrismarineJS/mineflayer#936]
My console keep spamming warning along the line of this and I'm not sure what it means, could someone help me

`WARNING : unknown transaction confirmation for window 0, action 2702 and accepted false
WARNING : unknown transaction confirmation for window 0, action 19635 and accepted false
WARNING : unknown transaction confirmation for window 0, action 16711 and accepted false
WARNING : unknown transaction confirmation for window 0, action 1702 and accepted false
WARNING : unknown transaction confirmation for window 0, action 1033 and accepted false
WARNING : unknown transaction confirmation for window 0, action 21137 and accepted false
WARNING : unknown transaction confirmation for window 0, action 7778 and accepted false`

**Comment by ImHarvol** [comment]
Can you provide more information? What are you trying to do?

**Comment by Karang** [comment]
Reopen when you can provide more informations.
