### ISSUE TITLE
Click bot on "bausucht.net"

### ISSUE THREAD

**Issue by CyborgCodeDEV** [PrismarineJS/mineflayer#939]
## Versions
 - mineflayer: 2.11.0
 - server: spigot 1.8.8
 - node: 6.12.1

## Detailed description of a question
I want to click an NPC on a specific server (`bausucht.net`) but I don't get it working.

What I tried:
- bot.useOn() (which worked on my localhost)
- bot.activateEntity()

Can you please help me? I think it would help to capture the packets from the client to the server, is there any way to do that (multi-bungee-network, spigot servers with ip whitelist, online-mode true)

I tried all solutions given from:
1. #926
2. #925
3. #826

-> Please don't mark as duplicate, other issues didn't help me

Thank you in advance.

**Comment by plexigras** [comment]
useful would be your code, what you expect to happen and what is actually happening

**Comment by CyborgCodeDEV** [comment]
My code: https://pastebin.com/aEKESuVn

**I expext:** I expect that the bot changes to the citybuild-server (which happens by right-clicking the npc)

**What happens:** The bot turns to the npc but doesn't get sent to the other server

**Comment by plexigras** [comment]
```js
	for (id in bot.entities) {
```
should probably look more like

https://github.com/PrismarineJS/mineflayer/blob/d404b6480ad36aac618033f92680e6291984f091/examples/trader.js#L53-L54

and i'm pretty sure `bot.activateEntity(entity)` would be the right way to go here

**Comment by CyborgCodeDEV** [comment]
Thanks for your answer, but sadly this didn't solve my problem... 

https://hastebin.com/ejufuhoqol.js

I tried to click every single entity at the npc's position because I thought that another entity (for example an armor stand) could be the trigger for the server change.

Here is a picture of the NPC I want to click: 
![image](https://user-images.githubusercontent.com/46001261/78982504-8c3af500-7b22-11ea-8101-5d532173be0f.png)

I hope you can help me with this, thanks!

**Comment by plexigras** [comment]
hmm, you could log the entities in range by doing

```
console.log(bot.entities.filter(e => bot.entity.position.distanceTo(e.position) < 3))
```

**Comment by CyborgCodeDEV** [comment]
The command you sent didn't work for me

This printed following output:
```
const players = Object.keys(bot.entities).map(id => bot.entities[id])
console.log(players.filter(e => bot.entity.position.distanceTo(e.position) < 3))
```
https://hastebin.com/cuxufudito.coffeescript

**Comment by FabiCrafter** [comment]
CyborgCodeDEV hab die gleiche frage xd

**Comment by Gamingfant** [comment]
The npc is surrounded by invisible armorstands. I think the bot can't click on them.

**Comment by wvffle** [comment]
@MegaSilas the bot can click on any entity

**Comment by CyborgCodeDEV** [comment]
There is a person on this server who got it working with Mineflayer but he doesn't want to say how he did that...

**Comment by iCrashPhones** [comment]
just click every entity, chances are, it will work. Not very ideal tho so try to narrow it down

**Comment by CyborgCodeDEV** [comment]
I tried that but that didn't work either. I think I have to give up, but thanks to all of you for trying to help me.
