### ISSUE TITLE
Error on chat message

### ISSUE THREAD

**Issue by SpikeThatMike** [PrismarineJS/mineflayer#957]
bot.on('chat', (username, message, type, rawmessage) => {
  console.log(`${rawmessage}`)
  })

I have this code to display the chat messages in the console but i keep getting this error message after a few messages
https://paste.menudocs.org/paste/gh2j2

**Comment by rom1504** [comment]
It's unrelated with this code. Can you provide details about your minecraft
version and the server you're connecting to

**Comment by SpikeThatMike** [comment]
using version 1.8.9 and mc-central.net for the server
