### ISSUE TITLE
bot.on('chat') doesnt pick up some messages

### ISSUE THREAD

**Issue by SpikeThatMike** [PrismarineJS/mineflayer#958]
bot.on('chat', (username, message, type, rawmessage) => {
  console.log(`${username} >>> ${message})
this code picks up on all the chat messages except this one, does anyone know a fix for this?
![image](https://user-images.githubusercontent.com/37084002/79892686-cd70b600-83fa-11ea-9151-647ee206e1db.png)

**Comment by ImHarvol** [comment]
I would say it's because it's not a "chat" event. It probably is a ["message" event](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#message-jsonmsg)

**Comment by SpikeThatMike** [comment]
so i would use 
bot.on('message')
console.log(message)?

**Comment by ImHarvol** [comment]
Yes, similar as 'chat', but 'message' only returns the messaje in json format
```js
bot.on('message', (jsonMsg) => {
  console.log(jsonMsg)
})
```

**Comment by SpikeThatMike** [comment]
ive done this thanks.
but when i try do if("has joined the server" in jsonMsg) it doesnt do whats in the if function e.g
      if ("has joined the lobby" in jsonMsg) {
        mcc.chat("/factions")

**Comment by ImHarvol** [comment]
I think the in operator looks in the keys of the object, not the value. Try console.log(jsonMsg) and see what's the format of jsonMsg

I have no idea about the error

**Comment by SpikeThatMike** [comment]
this is the jsonMsg
https://paste.menudocs.org/paste/gh2j2
how would i make it check main message which includes the 'has joined the server'

**Comment by ImHarvol** [comment]
You can use `jsonMsg.extra[3].text.includes('has joined the server')`

For these questions better use the [Discord](https://discord.gg/Bh5wFX)
