### ISSUE TITLE
1.15.2 support

### ISSUE THREAD

**Issue by arantesxyz** [PrismarineJS/mineflayer#961]
## Is your feature request related to a problem? Please describe.
I'm trying to make a bot to load my farms during the night.

## Describe the solution you'd like
I wanted the bot to support the 1.15.2 version of minecraft.

## Describe alternatives you've considered
I'm currently using the minecraft-protocol library but it has less features and it's slower to develop.

## Additional context
Just wanna know when 1.15.2 will be available. :P

**Comment by Vikbor5342** [comment]
This wolud be extreamly nice

**Comment by rom1504** [comment]
now that 1.14.4 is done, this is possible
will need : 
* updating https://github.com/PrismarineJS/prismarine-windows/blob/master/index.js (would be best to move this data to minecraft data)
* https://github.com/PrismarineJS/prismarine-chunk/issues/80
* update https://github.com/PrismarineJS/prismarine-item/blob/master/index.js#L80 (might be nice to use features.json there)
* mineflayer PR

**Comment by rom1504** [comment]
done
