### ISSUE TITLE
plz help me

### ISSUE THREAD

**Issue by helloiamyeet** [PrismarineJS/mineflayer#964]
hi i am new to js and was wondering how this function worked 

 host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'digger',
  password: process.argv[5]

i cant find any connections to any other script plz help me 
and i do not know how to get my bot to join my home mincraft server?? help

**Comment by ImHarvol** [comment]
Before anything: Please, try to use the [Discord](https://discord.gg/u2eZrQB) if you need to ask thay way we dont flood github issues.

As the [docs](https://nodejs.org/docs/latest/api/process.html#process_process_argv) say:
> The `process.argv` property returns an array containing the command line arguments passed when the Node.js process was launched. 

If you want to run an example like https://github.com/PrismarineJS/mineflayer/blob/master/examples/ansi.js, you have to run it like this:
```bash 
node ansi.js <host> <port> [<name>] [<password>]
```
Obviusly, change the host, port, name and password.
You can also hardcode the values: `host: '127.0.0.1'`

**Comment by helloiamyeet** [comment]
Hi i tryed this and it does not work it just prints the host and port in
the cmp

**Comment by helloiamyeet** [comment]
Oh i see thank you... you are fantastic also i love you work keep it up
thanks
