### ISSUE TITLE
Cannot move using packets on proxy

### ISSUE THREAD

**Issue by AkosMaster** [PrismarineJS/mineflayer#965]
`

            delta = 0.1
	newPosition = lastPosition;
	newPosition.x += Math.random() > 0.5 ? delta : -delta;
	newPosition.y += Math.random() > 0.5 ? delta : -delta;
	newPosition.z += Math.random() > 0.5 ? delta : -delta;

	client.write("position", newPosition);

	lastPosition = newPosition;
`

this is what I'm using to do antiafk from my proxy client. The server either teleports me back or I just don't appear to move at all. I am interested in how other libraries achieved movement with packets. If anyone knows a reliable method, please help.

(lastPosition is always the last position packet the server sent me)
I am on 1.12.2

**Comment by ImHarvol** [comment]
Mineflayer has its own [physics plugin](https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/physics.js) that already send a `position_look` packet, so you can try to modify the `bot.entity.position` instead of sending the packet yourself
