### ISSUE TITLE
Consider adding/promoting a bounty system

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#985]
It's not that rare that people want to pay for an issue to get solved.
I think we might use a system such as 
* https://gitpay.me/#/
* https://www.bountysource.com/

so that people that want to pay can pay people that want to get paid.

I have 0 experience with that kind of system, if someone knows what's good / what works, do say

I'm also not 100% convinced whether it's a good idea. Sure it makes sense that work get paid, but also I feel it changes a bit the spirit of the work if it's not volunteer work, people might focus less on the interesting part and more on what users want.

**Comment by rom1504** [comment]
yeah not convinced at all this is a good thing, let's reopen if needed

**Comment by wvffle** [comment]
Wouldn't it be easier to simply add some donation links of the active maintainers to the readme?

**Comment by rom1504** [comment]
That's completely different imho.
That would be to reward the job done not to incentive doing work on a
particular thing.
