### ISSUE TITLE
bot connect then do action

### ISSUE THREAD

**Issue by Phaired** [PrismarineJS/mineflayer#986]
Hello, I want the bot to connect this part is ok, then click on selected item on GUI to change server then type a command and click on selected on a gui, then AFK how can I do that, if someone can help me, I will be very grateful 
thanks

```js
var mineflayer = require('mineflayer');
var AutoAuth = require('mineflayer-auto-auth')
var bot = mineflayer.createBot({
  host: "",
    port: 25565,      
    username: "",
    version: "1.8.9",
    keepAlive: true,
  plugins: [AutoAuth],
  AutoAuth: {
    logging: true,
    password: '',
    ignoreRepeat: true
  }
});
function sleep(milliseconds) {
  const date = Date.now();
  let currentDate = null;
  do {
    currentDate = Date.now();
  } while (currentDate - date < milliseconds);
}
bot.on('login', function() {
  console.log("Bot connected!");
  sleep(10000);    
  console.log("sleep 10s ok");
  bot.setQuickBarSlot(0)
  console.log("hotbar slot ok");
  sleep(1000);    
  bot.once('windowOpen', onWindowOpen)
  console.log("item active");
  console.log(window.selectedItem);
  bot.clickWindow(14, 1, 0, (err) => {
	});
});

```

**Comment by hexatester** [comment]
```
bot.on('login', function() {
console.log("Bot connected!");
setTimeout(()=>{

console.log("sleep 10s ok");
bot.setQuickBarSlot(0)
console.log("hotbar slot ok");
bot.activateItem()
bot.once('windowOpen', (window)=>{
bot.clickWindow(14, 1, 0, (err) => {
setTimeout(()=>{bot.chat("/afk")},10*1000)
});
})
}, 10*1000);
});
```

Please next time, Ask on discord.
Or pm me https://t.me/hexatester

**Comment by Phaired** [comment]
Hi thanks for help, but this doesn't work, I think the bot need to be connecting to do these actions because on login (with the password) he was teleported then I need he do : slot 1 then right click on compass to open GUI, then click on specific slot, then type a command, and finally click on another specific slot a GUI.

**Comment by hexatester** [comment]
I suggest adding chatPattern when your server asking for password, and others chat based event.

Example
Server send `Login with the command "/login <password>"`, you could catch it using regex (chatAddPattern). Rather than using setTimeout or sleep, indefinitely.

```js
bot.chatAddPattern(
  /^Login with the command "\/login <password>"$/,
  "auth_login"
);
bot.once("auth_login", () => {
  bot.chat("/login password");
});
```

**Comment by Phaired** [comment]
I log with the plugin https://github.com/G07cha/MineflayerAutoAuth and it's work perfectly my problem is after the bot type the password I just won't open the compass and click on desired server (item)

**Comment by hexatester** [comment]
I see. Is there any other way to do it, without using gui / clock.
For example, using `/connect survival`.

**Comment by Phaired** [comment]
No it's a only a gui after the login is confirmed ^^

**Comment by hexatester** [comment]
To right click an item use (bot.activateItem)[http://mineflayer.prismarine.js.org/#/api?id=botactivateitem]
Also callback is your friend.

```js
bot.once("windowOpen" (window) => {
// click slot here
// if window not closed bot.closeWindow(window)
// Send command
// Repeat
// bot.once("windowOpen" (window) => {})
});
```

More on (window)[https://github.com/PrismarineJS/prismarine-windows]

And makes sure you clicking the correct slot!

**Comment by Phaired** [comment]
What’s callback and use it ?

**Comment by hexatester** [comment]
Callback is a function that you put into another function as argument, and called when the main function finished.


Example

```js
function sayHi() {
  console.log("hi");
}
setTimeout(sayHi, 3 * 1000);
```

`sayHi` is called after `setTimeout` finished (run sayHi after 3 * 1000 ms).

**Comment by Phaired** [comment]
var mineflayer = require('mineflayer');
var AutoAuth = require('mineflayer-auto-auth')
var bot = mineflayer.createBot({
  host: "",
    port: 25565,       
    username: "",
    version: "1.8.9",
    keepAlive: true,
  plugins: [AutoAuth],
  AutoAuth: {
    logging: true,
    password: '',
    ignoreRepeat: true
  }
});
function sleep(milliseconds) {
  const date = Date.now();
  let currentDate = null;
  do {
    currentDate = Date.now();
  } while (currentDate - date < milliseconds);
}

bot.on('serverAuth', function() {
console.log("Bot connected!");

function sayHi() {
bot.setQuickBarSlot(0);
bot.activateItem();
bot.once('windowOpen', (window) => {
setTimeout(()=>{bot.chat("afk")},10*1000);

}, 1*1000);
setTimeout(sayHi, 1 * 1000);
}

});

I try this and it doesn't work help

**Comment by wvffle** [comment]
Please, for questions like
> Why doesn't my code work?
and
> How to do this and that?

I kindly ask you to use our discord server. https://discord.gg/eybmzRR
If you don't use discord you can also use gitter. https://gitter.im/PrismarineJS/mineflayer

**Comment by rom1504** [comment]
I actually disagree for this kind of case. I think it makes sense to use an issue for this so he can : 
* Post all his code without polluting Discord
* Put more context information

Discord is good for a short exchanges, when you need a bigger context, issues do make sense.

**Comment by rom1504** [comment]
In this particular case here is what's missing so we can help you @Phaired is any error you got.
You can put it here, and it's also useful you read it yourself

**Comment by TheAlan404** [comment]
I'm helping him code this, the issue can be closed I think.

**Comment by rom1504** [comment]
Ok
