### ISSUE TITLE
Wiki Improvement

### ISSUE THREAD

**Issue by hexatester** [PrismarineJS/mineflayer#987]
I want to add new pages to wiki.
Here my temp repo [hexatester/mineflayer-wiki](https://github.com/hexatester/mineflayer-wiki).
 #908

**Comment by rom1504** [comment]
It seems like you mostly added tutorials. That's nice !
What do you think to put it in docs/tutorial in the main repo instead of
the wiki ? That would make it possible to show these tutorials in the web
doc

**Comment by hexatester** [comment]
Oh. I see.

**Comment by hexatester** [comment]
Work in progress...

**Comment by hexatester** [comment]
Waiting for review.

**Comment by hexatester** [comment]
Closing this issue, duplicate of another issue
