### ISSUE TITLE
Optimize chest.deposit

### ISSUE THREAD

**Issue by ImHarvol** [PrismarineJS/mineflayer#988]
## Is your feature request related to a problem? Please describe.
It could be, chest.deposit is throwing `(node:16890) UnhandledPromiseRejectionWarning: Error: missing source item 86:null in (54,90)` after a few stacks are deposited
Edit: This error has nothing to do with mineflayer, I was a problem of my code

## Describe the solution you'd like
Right now the bot deposits the item one by one, and if you need to deposit an entire inventory of stacks, that's going to be a hell lol of sent packets, which is not ideal: maybe a server could start rejecting transactions after so many packets?

## Describe alternatives you've considered
Instead of deposit items one by one, deposit the entire slot in the chest

I haven't look yet at how the bot currently handles chest.deposit, but I'll take a look

**Comment by Karang** [comment]
What you want to look at is `bot.transfer` https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js#L234 as it is the function called by deposit, withdraw, etc..

The `transferOne` internal function name is a bit misleading as it is supposed to transfer multiple item of the same type as once (up to a stack).

If that is not the behavior you observe, then indeed there must be a bug somewhere.

**Comment by ImHarvol** [comment]
Thanks! I see the problem should be in `clickDest()`: https://github.com/PrismarineJS/mineflayer/blob/4fdde4e15bac5cf22d888aabe9b20cd13f33a871/lib/plugins/inventory.js#L302

In my case the behavior is this https://streamable.com/u1qe8q

**Comment by Karang** [comment]
I found the bug, I'll commit a fix
