### ISSUE TITLE
handle the server resending the rotation of the bot

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#993]
there https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/physics.js#L373

probably needed to check the flags for this, see https://wiki.vg/Protocol#Player_Position_And_Look_.28clientbound.29

**Comment by Karang** [comment]
I had a look to fix the issue, but it seems like this is the normal behavior.

The server is sending a player position and look packet containing the correct yaw and pitch and mineflayer update it correctly. But other players are seeing the freshly spawned bot looking at yaw = 0 until the bot start moving. This is also the case when a player with a vanilla client spawn, if he don't move his mouse, other players will see the character looking at yaw = 0. Somehow the pitch is correct...

A workarround would be to immediately send a position and look packet to the server with a slightly different yaw (like yaw+0.001, the server will only send the update to other players if it detect a change).

As it is vanilla behavior, I suggest to leave it as it is and this issue can be closed.
