### ISSUE TITLE
Bot fails to log on

### ISSUE THREAD

**Issue by uAliFurkanY** [PrismarineJS/mineflayer#997]
## Versions
 - mineflayer: latest
- server: paper
 - node: I don't know, glitch's version

## Detailed description of a problem
It fails to log on 75% of the time. Sometimes it works.

## Current code
```js
const mineflayer = require("mineflayer");
let bot = mineflayer.createBot({
  host: "0b0t.org",
  username: process.env.USERNAME,
  password: process.env.PASSWORD,
  version: "1.12.2"
});
```

## Expected behavior
It should log on, this is what it returns:
```
Error: Invalid credentials. Invalid username or password.

    at /rbd/pnpm-volume/c772bafc-0c80-472b-887f-a0edf64a0521/node_modules/mineflayer/node_modules/yggdrasil/lib/utils.js:60:10

    at /rbd/pnpm-volume/c772bafc-0c80-472b-887f-a0edf64a0521/node_modules/mineflayer/node_modules/phin/lib/phin.min.js:1:1150

    at processTicksAndRejections (internal/process/task_queues.js:88:5)
```

**Comment by uAliFurkanY** [comment]
Probably a bug from me

**Comment by uAliFurkanY** [comment]
No it just doesn't work

**Comment by wvffle** [comment]
What does 'latest' mean in mineflayer version?
What does 'papaer' mean in server version?
Check your node version with `node -v`

You're providing wrong username and password. If you don't have a premium minecraft account then remove the `password` field.

**Comment by uAliFurkanY** [comment]
I think I found the solution. If you try to log on while the server is full
or you logged on too many times, it doesn't work and says invalid
credentials

**Comment by rom1504** [comment]
Yes Mojang does this, if you login too many times, it bans you temporarily
