### ISSUE TITLE
Bot gets kicked right after sending a message

### ISSUE THREAD

**Issue by uAliFurkanY** [PrismarineJS/mineflayer#999]
## Versions
 - mineflayer: 2.14.1
 - server: paper 1.12.2
 - node: v12.13.0

## Detailed description of a problem
Bot gets kicked right after sending a message via "/msg"

## Current code
```js
bot.on('spawn', () => {
 bot.chat("/msg " + op[0] + " Logged in.")
})
```

## Expected behavior
Bot should stay

## Additional context
I receive the message but the bot gets kicked right after without a kick event being triggered. This is on 0b0t.org. It works when I delete the chat line

**Comment by hexatester** [comment]
Maybe the server kicked you, because you send the command / chat too fast.

Please, join [PrismarineJs Discord server.](https://discord.com/invite/GsEFRM8). We gladly help you there.

**Comment by uAliFurkanY** [comment]
It's definitely possible but it doesn't kick you after 10 seconds
And it didn't kick me ona mc client for msging in the first 10 seconds

**Comment by rom1504** [comment]
how do you measure "first 10 seconds" ?
spawn event is definitely too early

**Comment by uAliFurkanY** [comment]
I don't know but it gets kicked everytime it sends a message now

**Comment by uAliFurkanY** [comment]
I think I got it. It's sending too many commands but that doesn't explain the first one.

**Comment by hexatester** [comment]
No. You don't understand, yet.
This will send the chat 15 seconds after you spawn in

```js
bot.once("spawn", () => {
  setTimeout(() => bot.chat(`/msg ${op[0]} Logged in!`), 15 * 1000);
});
```

**Comment by uAliFurkanY** [comment]
actually the bot was sending something when it logs on so I made a loop for pending messages and it worked
